.changeset/tame-dodos-float.md, packages/svelte/src/internal/client/validate.js, packages/svelte/tests/runtime-legacy/samples/keyed-each-dev-unique-update/_config.js, packages/svelte/tests/runtime-legacy/samples/keyed-each-dev-unique-update/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12832. We have each block key validation errors already, however the logic only worked on mount and not updates.
=> fix: ensure each key validation occurs for updates

.changeset/calm-clocks-raise.md, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
This shouldn't cause any issues, but I'm adding a changeset around it just in case. Profiling this and whilst Sets do add a slight bit of overhead compared to arrays when small, arrays are terrible compared to Sets with lots of dependencies – such as when used in each blocks.
=> chore: improve signal perf by using Set rather than array for reactions

.changeset/brown-turkeys-tap.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/events.js
Addresses https://github.com/sveltejs/svelte/issues/12639#issuecomment-2285064117. I thought JSDOM supported passive events, but it doesn't appear to, so I'm unsure of what to do about a test case here.
=> fix: ensure onwheel is passive by default

packages/svelte/messages/compile-warnings/template.md
Added examples of how `<svelte:component>` can be replaced, maybe helpful for people encountering the warning.
Maybe lifting the restrictions on `@const` is something worth reconsidering 🤔.
=> docs: More guidance on migrating away from `<svelte:component>`.

.changeset/pink-countries-repair.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/Attribute.js, packages/svelte/src/compiler/phases/2-analyze/visitors/BindDirective.js, packages/svelte/src/compiler/phases/2-analyze/visitors/ExportNamedDeclaration.js, packages/svelte/src/compiler/phases/2-analyze/visitors/ExportSpecifier.js, packages/svelte/src/compiler/phases/2-analyze/visitors/Identifier.js, packages/svelte/src/compiler/phases/2-analyze/visitors/StyleDirective.js, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/EachBlock.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/src/compiler/types/index.d.ts, packages/svelte/src/compiler/types/template.d.ts, packages/svelte/types/index.d.ts
Necessary for #12824. This sets `binding.kind` for all bindings _before_ we walk the AST in the analysis phase, but only in legacy mode.
(In runes mode it's more awkward because declarations can be anywhere, and we can't set `kind` at the declaration site until we know definitively whether we're in runes mode or not. When we get rid of legacy mode, this restriction will go away. In the meantime, it doesn't matter for #12824, because it's about `$:` statements which are only valid in legacy mode.)
Doing it this way means we can provide better warnings during the analysis phase.
=> chore: set `binding.kind` before analysis

.changeset/lucky-experts-float.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/EachBlock.js, packages/svelte/tests/snapshot/samples/each-string-template/_expected/client/index.svelte.js
minor tweak — if an each block doesn't need to reference the index, remove it from the generated code, since unused parameters can't be safely removed by minifiers
=> fix: omit `$$index` parameter where possible

.changeset/strange-pillows-greet.md, packages/svelte/messages/compile-warnings/script.md, packages/svelte/src/compiler/phases/2-analyze/visitors/Identifier.js, packages/svelte/src/compiler/phases/2-analyze/visitors/LabeledStatement.js, packages/svelte/src/compiler/phases/2-analyze/visitors/MemberExpression.js, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/declarations.js, packages/svelte/src/compiler/warnings.js, packages/svelte/tests/validator/samples/reactive-module-variable/input.svelte, packages/svelte/tests/validator/samples/reactive-module-variable/warnings.json
closes #9287. ~~Right now, this causes a test failure, because of a case where we don't know that a binding is state until we've completed the analysis phase. Ideally, we would have a complete picture of state vs non-state by the time scopes have been generated — I've been meaning to fix that for a while now, and this forces the issue~~
=> feat: better compiler warnings for non-reactive dependencies of reactive statements

.changeset/tricky-coats-shop.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/tests/snapshot/samples/purity/_expected/client/index.svelte.js
We only need this flag if there's a binding. Otherwise it's just wasteful
=> fix: skip unnecessary `$$legacy` flag

packages/svelte/src/internal/client/runtime.js
We used to have it this way and it seemed ideal to refactor to avoid recursion, however there doesn't seem to be any real performance benefit that I can see. This code reads better and is easier to refactor in recursive form.
=> chore: bring back recursive processing of effects

sites/svelte-5-preview/src/routes/docs/content/03-appendix/03-deprecations.md
The preview docs have a deprecation section which did not mention this yet.
=> docs: Add `<svelte:component>` deprecation section also to preview docs.

.changeset/lazy-carrots-buy.md, packages/svelte/src/internal/client/dom/elements/transitions.js
Fixes https://github.com/sveltejs/svelte/issues/12844#issuecomment-2292019099. I also confirmed this did not regress the memory leak that https://github.com/sveltejs/svelte/pull/12759 fixed. It seems we only need to abort the intro, rather than the outro – I must have added to both call-sites because it seemed right, but clearly that wasn't right.
=> fix: ensure outro animation is not prematurely aborted

sites/svelte-5-preview/src/routes/docs/content/02-examples/01-universal-reactivity.md
=> docs: add note on destructured declarations

.changeset/rich-elephants-relax.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/AssignmentExpression.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/AssignmentExpression.js, packages/svelte/src/compiler/phases/3-transform/shared/assignments.js, packages/svelte/tests/snapshot/samples/destructured-assignments/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/destructured-assignments/_expected/server/index.svelte.js, packages/svelte/tests/snapshot/samples/destructured-assignments/index.svelte.js
Noticed that we're transforming destructuring assignments even if all the identifiers are normal bindings. This fixes it
=> feat: better destructuring assignments

packages/svelte/src/internal/client/runtime.js
Reverts sveltejs/svelte#12861
So it turns out that Firefox's Spidermonkey really doesn't perform as well with recursive functions as V8. Looking into the performance trace of the REPL shows this function to be eating up almost all the time now, so reverting this change seems wise.
=> Revert "chore: bring back recursive processing of effects"

packages/svelte/src/internal/client/dom/blocks/each.js
Tweaks the each block logic so it's slightly more efficient. `Array.from` isn't free, even on an empty array. So if we can avoid doing that work entirely, then it's a win win. 
Additionally, we don't need to eagerly create `Set`s for things that might never happen. It means we do a bunch of `has` checks when that might not even be needed. Not to mention that creating the Sets each time we reconcile has a memory cost, even if we don't use them.
=> chore: tweak each block logic

.changeset/hot-kangaroos-invite.md, packages/svelte/src/internal/client/dom/template.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
This greatly simplifies and speeds up our internal signal dependency logic. We no longer need a `Set` and we handle duplicates by design – removing the need to check for duplicates. This also gets rid of a lot of convoluted logic that has bothered me for a while.
=> chore: refactor internal signal dependency heuristic

.changeset/eighty-days-wave.md, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/tests/runtime-legacy/samples/binding-value-prop/Field.svelte, packages/svelte/tests/runtime-legacy/samples/binding-value-prop/_config.js, packages/svelte/tests/runtime-legacy/samples/binding-value-prop/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12860. This was a recent regression from https://github.com/sveltejs/svelte/pull/12843 where the binding identifier is marked as `reassigned` but not `mutated` in legacy mode, meaning that we didn't correctly put in the correct `flags` for the prop runtime. We can instead just look for `binding.updated` as this captures either, and fixes this issue.
=> fix: correctly ensure prop bindings are reactive when bound

.changeset/nasty-penguins-pump.md, packages/svelte/src/internal/client/dom/blocks/snippet.js, packages/svelte/src/internal/server/blocks/snippet.js, packages/svelte/types/index.d.ts
Add cleanup type to return value of setup function
=> fix: improve createRawSnippet types with cleanup type

.changeset/orange-laws-drop.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/fragment.js, packages/svelte/tests/snapshot/samples/bind-component-snippet/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/dynamic-attributes-casing/_expected/client/main.svelte.js, packages/svelte/tests/snapshot/samples/purity/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/state-proxy-literal/_expected/client/index.svelte.js
We handle the case where an `{expression}` is empty during SSR, resulting in no text node being created, by passing a flag to `first_child` and `sibling`. But we do it more often than we need to — it only needs to happen when dealing with a single `ExpressionTag`, rather than a `Text` node or a sequence of the two.
=> feat: more efficient checking for missing SSR text node

.changeset/brown-radios-itch.md, packages/svelte/svelte-html.d.ts
=> fix: ensure typings for `<svelte:options>` are picked up (Svelte 5 version)

.changeset/big-students-deliver.md, packages/svelte/svelte-html.d.ts
=> fix: ensure typings for `<svelte:options>` are picked up (Svelte 4)

sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
=> docs: mention removal of `foreign` namespace

.changeset/swift-queens-begin.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js
closes https://github.com/sveltejs/svelte-hmr/issues/26
When HMR is enabled, wrap the "define custom element" call inside an if statement that checks if it already exists
=> feat: support HMR with custom elements

.changeset/flat-moose-arrive.md, packages/svelte/src/internal/client/reactivity/sources.js
Reverts sveltejs/svelte#12921. This breaks https://github.com/sveltejs/svelte/pull/12545
=> Revert "fix: avoid extra work in mark_reactions"

.changeset/rich-ladybugs-admire.md, packages/svelte/src/index.d.ts, packages/svelte/types/index.d.ts
Minimal update to slightly improve the legibility of the hint, because `"` is displayed as `\"`
Before:
After:
---
While we're at it, we may provide a copy-pasteable hint:
```ts
{
'Function passed to {@render ...} tag must be of type Snippet': "import type { Snippet } from 'svelte'";
} & typeof SnippetReturn
```
* Swapped hint and symbol so that the hint is displayed first
* Replaced `_` key with `"problem": "solution"` structure
* Made a copy-pasteable solution
It renders as:
What do you think of this?
It's not possible to make a multi-line hint, as new lines are displayed as `\n`. 
---
If your PR …
=> fix: small legibility improvement

.changeset/famous-mirrors-count.md, documentation/docs/02-template-syntax/02-basic-markup.md, packages/svelte/src/utils.js, sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
=> fix: align list of passive events with browser defaults, and add documentation

.changeset/popular-news-happen.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/AwaitBlock.js, packages/svelte/tests/runtime-legacy/samples/await-then-shadowed/_config.js, packages/svelte/tests/runtime-legacy/samples/await-then-shadowed/main.svelte
=> fix: ensure await scope shadowing is computed in the correct order

.changeset/wild-moose-destroy.md, packages/svelte/src/compiler/phases/2-analyze/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/fragment.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/_expected/server/index.svelte.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/index.svelte
We're setting all attributes on custom elements through properties, so we need to preserve those subtrees, else the attributes get lost
fixes #12934
=> fix: don't skip custom elements with attributes

.changeset/nervous-adults-sell.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/Program.js, packages/svelte/tests/runtime-runes/samples/store-from-derived/_config.js, packages/svelte/tests/runtime-runes/samples/store-from-derived/main.svelte
=> fix: ensure `$store` reads are properly transformed

.changeset/spotty-trees-provide.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/declarations.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/var-declarations/_config.js, packages/svelte/tests/runtime-runes/samples/var-declarations/main.svelte
- fixes #12807: state declared with var is now retrieved using a new `safe_get` function, which works like `get` but checks for undefined
- fixes #12900: ensure we're not creating another new scope for block statements of function declarations, which resulted in var declarations getting "swallowed" (because they were hoisted to the function declaration scope and never seen by our logic)
=> fix: more robust handling of var declarations

.changeset/rare-ears-agree.md, packages/svelte/src/internal/client/timing.js
I noticed that we were doing a `typeof window !== 'undefined'` check in the client output, which seems unnecessary to me. If we use `esm-env` the bundler will replace `BROWSER` with `true` and should eliminate the unused branches.
Do we even need this check though? I notice `client` in the directory name...
=> chore: update client check for smaller bundle size

sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
=> docs: add note on stricter attribute syntax

.changeset/mighty-poets-fix.md, packages/svelte/src/compiler/index.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/compiler/phases/3-transform/index.js, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/src/compiler/state.js, packages/svelte/src/compiler/types/index.d.ts, packages/svelte/src/compiler/utils/mapped_code.js, packages/svelte/src/compiler/validate-options.js, packages/svelte/src/internal/client/dom/elements/events.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/client/validate.js, packages/svelte/types/index.d.ts
just makes like a little simpler and more consistent (without a breaking change) — closes #12980
=> chore: default options.filename to "(unknown)"

.changeset/wet-pears-buy.md, packages/svelte/src/index.d.ts, packages/svelte/src/legacy/legacy-client.js, packages/svelte/tests/runtime-legacy/shared.ts, packages/svelte/types/index.d.ts
Add a new option to the legacy class component interface so that `flush_sync` can be omitted. Part of https://github.com/sveltejs/kit/issues/12248
=> feat: allow non-synchronous legacy component instantiation

.changeset/beige-lamps-ring.md, .changeset/green-windows-tap.md, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/proxy.test.ts
closes #13003. We were doing a couple of things wrong — the `deleteProperty` trap should always return `true`, not just when the property previously existed (I was surprised by this, but try it — `delete {}.foo`), and we need to create an `UNINITIALIZED` source when deleting a property that exists on the target otherwise it will show up in `ownKeys`
=> fix: handle deletions of state proxy properties

.changeset/khaki-donkeys-jump.md, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/proxy.test.ts
With the change to not mutate the underlying object anymore, some bugs related to array mutation occured. To fix those we need to initialize the `length` property source eagerly to catch the initial value, and then properly update it at the right times.
fixes #13022
=> fix: properly handle proxied array length mutations

pnpm-lock.yaml
taking another stab at https://github.com/sveltejs/svelte/pull/12790...
It looks like this works now that our dependencies have been upgraded (https://github.com/sveltejs/svelte/issues/12224)
=> chore: remove 40 dependencies from lockfile

.changeset/six-beans-laugh.md, packages/svelte/src/compiler/phases/2-analyze/visitors/BindDirective.js, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/utils.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/src/compiler/types/index.d.ts, packages/svelte/tests/validator/samples/binding-import-component/errors.json, packages/svelte/tests/validator/samples/binding-import-component/input.svelte, packages/svelte/tests/validator/samples/binding-import-element/errors.json, packages/svelte/tests/validator/samples/binding-import-element/input.svelte, packages/svelte/types/index.d.ts
Alternative to #13033, fixes #13027 — prevents binding to imports, just like we already prevent binding to other constants (including derived values).
=> fix: prevent binding to imports

.changeset/seven-news-live.md, packages/svelte/src/internal/client/dom/elements/events.js, packages/svelte/tests/runtime-runes/samples/event-attribute-delegation-8/_config.js, packages/svelte/tests/runtime-runes/samples/event-attribute-delegation-8/main.svelte
Fixes #13030. We just need to remove our custom `currentTarget` handler after we're done with the event.
=> fix: ensure event currentTarget is reset after propagation logic

.changeset/happy-dolls-joke.md, packages/svelte/src/compiler/phases/1-parse/index.js, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteBody.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteDocument.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteSelf.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteWindow.js, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/special-element.js, packages/svelte/tests/compiler-errors/samples/options-children/_config.js, packages/svelte/tests/compiler-errors/samples/self-reference/_config.js, packages/svelte/tests/compiler-errors/samples/svelte-selfdestructive/_config.js, packages/svelte/tests/compiler-errors/samples/window-children/_config.js
Started working on #12925 and found a bunch of things we can improve first:
- we should do as much validation during analysis, rather than parsing, as possible — it makes it much easier to (for example) have squigglies that cover a meaningful range, rather than being between two characters
- we're generating every element twice! once for the opening tag, once for the closing tag. the second one just gets discarded. this is silly and wasteful and almost certainly my bad
- the order of stuff in this file is all over the place. tidied it up — consts, export default, helper functions — rather than leaving everything weirdly interleaved
Aside from the squigglies, this doesn't change anything so I'll self-merge once green to unblock
=> chore: tidy up parser

packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/compiler/types/template.d.ts, packages/svelte/tests/snapshot/_config.js, packages/svelte/tests/snapshot/samples/inline-module-vars/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/inline-module-vars/_expected/server/index.svelte.js, packages/svelte/tests/snapshot/samples/inline-module-vars/index.svelte, packages/svelte/types/index.d.ts
I thought I'd provide a test as a start for https://github.com/sveltejs/svelte/issues/12995
I was going to try to implement more of this, but it's been quite a long time since I've looked at this code and things have changed a fair amount since then
=> chore: put module variables above template for later inlining

.changeset/gentle-needles-train.md, packages/svelte/messages/compile-errors/template.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/tests/compiler-errors/samples/element-invalid-name/_config.js, packages/svelte/tests/compiler-errors/samples/element-invalid-name/main.svelte
=> fix: error on invalid element name

.github/workflows/ci.yml, .github/workflows/release.yml
GitHub began the Node16 deprecation process a year ago [^1][^2]. The CI runs have been annotated with the deprecation warnings.
This PR updates both [actions/checkout](https://github.com/actions/checkout) and [actions/setup-node](https://github.com/actions/setup-node) to V4. No breaking changes introduced.
[^1]: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
[^2]: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> chore: update CI workflows to use latest version of actions

.changeset/eleven-icons-sniff.md, packages/svelte/messages/compile-errors/template.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteBody.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/special_element.js
Fixes https://github.com/sveltejs/svelte/issues/13021. We should be throwing an error when spreading to `<svelte:body>` as there might be an expectation that these work (they don't work today).
=> fix: error on incorrect attributes for svelte:body

.changeset/eighty-mails-develop.md, packages/svelte/src/internal/client/dom/blocks/html.js, packages/svelte/src/internal/server/blocks/html.js, packages/svelte/tests/runtime-legacy/samples/binding-contenteditable-html-initial/_config.js, packages/svelte/tests/runtime-legacy/shared.ts, packages/svelte/tests/runtime-runes/samples/html-tag-empty/_config.js, packages/svelte/tests/runtime-runes/samples/html-tag-empty/main.svelte
Fix https://github.com/sveltejs/svelte/issues/13069 `{@html}` should handle null and undefined as empty string
I didn't have permission to write to https://github.com/sveltejs/svelte/pull/13072, so this is a follow up with the fixes.
=> fix: render undefined html as the empty string

.changeset/chilly-waves-count.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/store-from-state-2/_config.js, packages/svelte/tests/runtime-runes/samples/store-from-state-2/main.svelte, packages/svelte/tests/runtime-runes/samples/store-from-state/_config.js, packages/svelte/tests/runtime-runes/samples/store-from-state/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13002.
There were actually a few issues that needed resolving:
- we weren't correctly disconnecting effects from the parents effects (if an effect is created in a derived, and that derived is in a branch, then the child effect will go to the branch)
- we had a linked list on deriveds for ownership of effects, which was pointless as it was also the same linked list used on effects – meaning a deriveds child would incorrectly then link to when to the effect graph – causing all sorts of random things being destroyed. I have no idea how this went missed, but we just now use a single array called `children` to store any effects or deriveds that are owned by a derived.
- when we execute effects we need to ensure that the child is the latest after …
=> fix: ensure reactivity system remains consistent with removals

documentation/blog/2024-09-01-whats-new-in-svelte-september-2024.md
lemme know if I missed anything!
=> docs: "What's new in Svelte" September newsletter

.changeset/heavy-cars-ring.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/tests/runtime-browser/custom-elements-samples/host-rune/_config.js, packages/svelte/tests/runtime-browser/custom-elements-samples/host-rune/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13121
=> fix: ensure $host rune correctly compiles in variable declarations

package.json, pnpm-lock.yaml, sites/svelte-5-preview/package.json, sites/svelte.dev/package.json, sites/svelte.dev/tsconfig.json
removes another 100 lines from our lockfile
=> chore: upgrade svelte-check and changesets

.changeset/hip-beers-shake.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/tests/snapshot/samples/inline-module-vars/_expected/client/index.svelte.js
=> Revert "fix: hoist imports on top"

.changeset/metal-cameras-jump.md, packages/svelte/scripts/generate-types.js, packages/svelte/src/reactivity/index-client.js, packages/svelte/src/reactivity/index-server.js, packages/svelte/src/store/public.d.ts, packages/svelte/src/transition/public.d.ts, packages/svelte/types/index.d.ts
As a byproduct of #12239 some types were changed from being directly exported to indirectly exported. TypeScript is bad at following these types while generating d.ts files, so we can't do that. A check at the end of the types generation was added to prevent regressions in the future. Fixes #13128
Also removes the old types from `svelte/reactivity` which are deprecated for a while now.
=> fix: ensure types are easier to follow for TypeScript

.changeset/tame-frogs-shave.md, packages/svelte/messages/client-errors/errors.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RenderTag.js, packages/svelte/src/internal/client/dom/blocks/snippet.js, packages/svelte/src/internal/client/errors.js, packages/svelte/src/internal/client/index.js, packages/svelte/tests/runtime-runes/samples/snippet-undefined/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-undefined/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12999.
If the snippet function is nullish and not a chain expression we now throw an error to have parity with non-dynamic references.
=> fix: prevent nullish snippet for rendering empty content

.changeset/selfish-trainers-kiss.md, packages/svelte/src/internal/client/dom/template.js, packages/svelte/tests/runtime-browser/samples/sole-script-tag/_config.js, packages/svelte/tests/runtime-browser/samples/sole-script-tag/main.svelte
We have a `run_scripts` function which is invoked in case a template block contains a script tag, and that function replaces the script tags (so that they actually run). If such a script tag is first or last in the template, the replacement is not picked up by our `node.first_node/last_node` logic anymore, and so it contains a stale tag. That means on cleanup the remove logic fails. In the case of the referenced issue, it just runs past the script tag till the very end of the head, removing the just added style tag from the new page.
Fixes #13086
=> fix: ensure inner script tags are properly removed

.changeset/strange-trains-destroy.md, packages/svelte/src/html-tree-validation.js, packages/svelte/src/internal/server/dev.js
The current logic is wonky, if we don't have a `parent_tag` we should still continue to validate the element.
=> chore: improve SSR parent element validation

.changeset/fuzzy-tigers-swim.md, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/tests/runtime-runes/samples/props-default-value-rest/_config.js, packages/svelte/tests/runtime-runes/samples/props-default-value-rest/inner.svelte, packages/svelte/tests/runtime-runes/samples/props-default-value-rest/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13187. This ensures that we update the local fallback value in the case where the fallback is used so that we persist local changes to bindable props. Otherwise, any incoming changes from the outside will reset the incoming value back to the old fallback value.
=> fix: ensure locally mutated bindable props persist with spreading props

.changeset/tough-snails-chew.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/nested-in-pseudo/_config.js, packages/svelte/tests/css/samples/nested-in-pseudo/expected.css, packages/svelte/tests/css/samples/nested-in-pseudo/expected.html, packages/svelte/tests/css/samples/nested-in-pseudo/input.svelte
Closes #13203
The problem is that we were checking for `NestingSelectors` only in the selectors of the immediate child of the selectors. Since Nesting could be in selectors like `:is` or `:where` or `:has` that can also be nested i think we need to walk the selectors to find if there's a selector or not.
=> fix: allow for nesting selector in pseudoclasses

.changeset/late-geckos-draw.md, packages/svelte/src/internal/client/dev/equality.js
Closes #13214 
I'm not 100% sure with this fix but i don't think we can really do much here...it's a very niche case because you are trying to access something where you can't check if `STATE_SYMBOL` is there without causing trouble in the first place.
But since it's no harm i guess we can just try catch it. No test for the moment but i actually just thought of a way to test this so i'm gonna try to write a test.
=> fix: try catch `strict_equals` to avoid error accessing `STATE_SYMBOL`

.changeset/polite-pugs-attend.md, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/inspect-derived-3/Item.svelte, packages/svelte/tests/runtime-runes/samples/inspect-derived-3/List.svelte, packages/svelte/tests/runtime-runes/samples/inspect-derived-3/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-derived-3/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13189
=> fix: ensure $inspect effects are fine-grain

.changeset/wild-mugs-cover.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/tests/snapshot/samples/text-nodes-deriveds/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/text-nodes-deriveds/_expected/server/index.svelte.js, packages/svelte/tests/snapshot/samples/text-nodes-deriveds/index.svelte
As per https://github.com/sveltejs/svelte/pull/13171#issuecomment-2343763030 we were creating unnecessary deriveds in the compiled code.
This was a bit tricky to fix because in the `RegularElement` visitor we call `build_template` that if there's more than one call creates this deriveds and push them to the `init`. However in `RegularElement` if we realise that there's state the template that we just built is unused and we proceed to process the children which calls `build_template` again creating another set of deriveds (which this time will be actually pushed to the update).
To fix this i've splitted the logic to check how many states/calls are there in it's own function (used by `build_template`) so that i can use that function instead in `RegularElement`.
I went with snapshot tests …
=> fix: avoid creating unnnecessary deriveds for text nodes with call

.changeset/ten-singers-repair.md, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/tests/compiler-errors/samples/component-invalid-name/_config.js, packages/svelte/tests/compiler-errors/samples/component-invalid-name/main.svelte
fixes #13194
We narrowed the allowed characters in #13057, but didn't take into account all possible (and for JavaScript identifiers allowed) unicode characters. This widens that, which also removes the accidental breaking change (because in Svelte 4 you were allowed to use these unicode characters).
=> fix: allow more characters in the unicode range as component identifiers

.changeset/flat-flies-know.md, packages/svelte/src/internal/client/dom/elements/events.js, packages/svelte/tests/runtime-browser/custom-elements-samples/events-slotted/_config.js, packages/svelte/tests/runtime-browser/custom-elements-samples/events-slotted/main.svelte
Closes #13162
We were going from parentNode to parentNode but if something is a slot of a custom element we should first go to the `assignedSlot` or else the inside of the custom element will be skipped.
P.s. i paired on this with @oscard0m and was hella fun to figure out! 😈
I manually checked that if you wrap the custom element with a div and add an `onclick` on it event delegation still works and i wanted to also add a test for this but i struggled to figure out a way to do it...if you think it's necessary i can try tomorrow (and if you have any ideas on how to do it it would be cool 😄).
If your PR …
=> fix: allow custom element events on slot to bubble inside custom element

.changeset/hot-peaches-clean.md, packages/svelte/elements.d.ts
As noticed by in https://github.com/sveltejs/svelte/issues/13201#issuecomment-2348313554_ the ts `AutoFill` type is missing a few valid tokens for the `autofill` field
https://html.spec.whatwg.org/#autofill-field
=> fix: add missing `autocomplete` tokens

packages/svelte/messages/compile-errors/style.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/tests/compiler-errors/samples/css-nesting-selector-root/_config.js, packages/svelte/tests/compiler-errors/samples/css-nesting-selector-root/main.svelte
It's a valid CSS rule, which means "select the scope root": https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector#using_outside_nested_rule
Found out while reading up more on `&` as part of #13209
=> fix: allow `&` to appear at the top when inside a `:global(...)`

.changeset/violet-bats-brake.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/ExpressionStatement.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/sourcemaps/samples/effects/_config.js, packages/svelte/tests/sourcemaps/samples/effects/input.svelte
This adds a new dev-time only `dev_effect_stack` variable, which executed effects are pushed to and eventually cleared out after everything's settled. If it doesn't settle however, i.e. you run into an infinite loop, the last ten effects are printed out so you get an idea where the error is coming from. For proper source mapping I also had to add location info to the generated effects.
Closes #13192
=> feat: add infinite loop effect callstack

packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/tests/runtime-runes/samples/await-pending-destroy/_config.js, packages/svelte/tests/runtime-runes/samples/await-pending-destroy/main.svelte
The promise callbacks used on `{#await}` can resolve after the block has been destroyed, which leads to other errors.
See #13236 
A simple solution : set the `input` to **null** in order to disable the callbacks.
=> fix: disable promise callback when {#await} is destroyed

.changeset/stale-rats-check.md, packages/svelte/messages/compile-errors/template.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/1-parse/read/options.js, packages/svelte/tests/validator/samples/tag-emoji/_config.js, packages/svelte/tests/validator/samples/tag-emoji/input.svelte, packages/svelte/tests/validator/samples/tag-hyphen/_config.js, packages/svelte/tests/validator/samples/tag-hyphen/input.svelte, packages/svelte/tests/validator/samples/tag-invalid/errors.json, packages/svelte/tests/validator/samples/tag-reserved/errors.json, packages/svelte/tests/validator/samples/tag-reserved/input.svelte
Fixes #13244. Follows the [WHATWG spec](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) when validating the `customElement` option in `<svelte:options>`.
This is _technically_ a breaking change because the validator would no longer accept uppercase letters in `customElement`; however, any code that did do this is invalid and would error immediately at runtime anyway, so I argue that it isn't a breaking change.
=> fix: follow spec for `customElement` option

documentation/docs/02-template-syntax/08-bindings.md
Relates to #13156, applies corrections regarding #13230.
If you try to construct a `FileList` you get this, because sometimes the DOM APIs are just 🔥:
> Uncaught TypeError: Illegal constructor
If this is too much stuff/the example should go elsewhere, I'm happy to revise this as necessary.
(Tried linting, but it's kinda broken for me.)
<details>
<summary>Output</summary>
```log
Oops! Something went wrong! :(
ESLint: 9.9.1
Error: Cannot find module 'E:\dev\svelte\node_modules\.pnpm\svelte-eslint-parser@0.41.0_svelte@packages+svelte\node_modules\svelte\compiler\index.js'
at createEsmNotFoundErr (node:internal/modules/cjs/loader:1171:15)
at finalizeEsmResolution (node:internal/modules/cjs/loader:1159:15)
at resolveExports (node:internal/modules/cjs/loader:584:14)
at Module._findPath …
```
=> docs: fixes relating to `bind:files` & note on `FileList` API

packages/svelte/scripts/generate-types.js, packages/svelte/src/events/public.d.ts, packages/svelte/src/internal/client/dom/elements/events.js, packages/svelte/tests/types/events.ts, packages/svelte/tsconfig.json, packages/svelte/types/index.d.ts
When programatically adding events using svelte/events `on` it doesn't correctly type `document` and `window` events.
```ts
on(window, 'keydown', (event) => {
if (event.key === 'h') {
console.log('Hello')
}
})
```
this won't work because window it falls under the EventTarget typing, which makes the event be of type `Event`
We should automatically have typings for both document and window, since this is very common when doing keybindings, drag drop and others.
By adding these two mappings we can fix it
```ts
/**
* Attaches an event handler to the window and returns a function that removes the handler. Using this
* rather than `addEventListener` will preserve the correct order relative to handlers added declaratively
* (with attributes like `onclick`), which use event delegation for …
```
=> fix: add document and window to svelte/events on types.

.changeset/good-zebras-turn.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/utils.js, packages/svelte/src/compiler/utils/sanitize_template_string.js
see https://github.com/sveltejs/svelte/pull/13262#issuecomment-2352749832. This feels like a more 'correct' fix, and results in tighter output in cases like `{'{'}`
=> sanitize template strings once assembled

sites/svelte-5-preview/src/routes/docs/content/01-api/04-event-handlers.md
Added documentation on managing multiple event handlers and spreading props.
This will help folks avoid this issue while waiting for a compiler warning.
#12533  Svelte 5: Adding local event handler to elements with spread props looks like a pitfall.
=> docs: Add spread guidance for multiple event handlers

.changeset/hot-glasses-roll.md, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-runes/samples/effect-order-3/_config.js, packages/svelte/tests/runtime-runes/samples/effect-order-3/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13237. Found out that we can likely avoid `flush_sync` when using `$inspect` because the real culprit turned out to be the fact we weren't setting the flushing flag, doh!
=> fix: avoid flushing sync with $inspect

packages/svelte/scripts/check-treeshakeability.js, packages/svelte/scripts/generate-types.js, packages/svelte/src/compiler/validate-options.js
assuming this is unobjectionable, I will add enforcement of it to the sveltejs eslint config
=> fix: import process for improved Deno compatibility

.changeset/stupid-dodos-hide.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/BindDirective.js, packages/svelte/src/compiler/utils/builders.js, packages/svelte/src/internal/client/dom/elements/bindings/input.js, packages/svelte/src/internal/client/dom/elements/bindings/media.js, packages/svelte/src/internal/client/dom/elements/bindings/select.js, packages/svelte/src/internal/client/dom/elements/bindings/size.js, packages/svelte/src/internal/client/dom/elements/bindings/universal.js, packages/svelte/src/internal/client/dom/elements/bindings/window.js
This is a follow-up to #13143, and takes it to its logical conclusion. If the getter and the setter are the same thing, we can simply omit the setter. Given this:
```svelte
<input bind:value={someprop}>
```
```diff
-$.bind_value(input, someprop, ($$value) => someprop($$value));
+$.bind_value(input, someprop);
```
Is this worthwhile? A good idea? Not sure.
I took the opportunity to make some naming more consistent while I was at it.
=> feat: omit unnecessary setters from bindings

.changeset/early-taxis-allow.md, packages/svelte/messages/client-warnings/warnings.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/CallExpression.js, packages/svelte/src/internal/client/dev/console-log.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/warnings.js, packages/svelte/src/internal/shared/clone.js
Wrap console.log/warn/error statements in DEV mode with a check whether or not they contain state objects. Closes #13123
This is an alternative or enhancement to #13070. Alternative if we deem it the better solution. Enhancement because it's not as robust as a custom formatter: We only check the top level of each entry (though we could maybe traverse a few levels), and if you're logging class instances, snapshot currently stops at the boundaries there and so you don't get snapshotted values for these (arguably this is a more general problem of $inspect and $state.snapshot), whereas with custom formatter it doesn't matter at which level you come across it.
=> feat: provide guidance in browser console when logging `$state` objects

packages/svelte/src/index-client.js, packages/svelte/src/internal/client/dev/legacy.js, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/dom/blocks/svelte-element.js, packages/svelte/src/internal/client/dom/elements/transitions.js, packages/svelte/src/internal/client/dom/legacy/lifecycle.js, packages/svelte/src/internal/client/dom/template.js, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/render.js, packages/svelte/src/internal/client/runtime.js
This is something I've wanted to do for a while now. It gets rid of all the `current_*` naming and instead keeps things more concise and inline with other variable names we have.
=> chore: improve runtime variable naming

.changeset/khaki-camels-punch.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/client/types.d.ts, packages/svelte/tests/runtime-runes/samples/effect-order-4/_config.js, packages/svelte/tests/runtime-runes/samples/effect-order-4/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13251.
When we invoke `$effect`s in a component, we defer them so that we have child -> parent sequencing. However, this doesn't take into account the fact an `$effect` might have been created inside another nested `$effect.pre` or template effect – in which case, we incorrectly associate the `$effect` with the component's effect rather than the correct `$effect.pre` or template effect. So this adds support for knowledge of the parent.
=> fix: ensure correct parent effect is associated with render effects

packages/svelte/src/compiler/phases/3-transform/client/types.d.ts, packages/svelte/src/compiler/phases/3-transform/client/visitors/AwaitBlock.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/Comment.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/EachBlock.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/Fragment.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/HtmlTag.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/IfBlock.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/KeyBlock.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/RenderTag.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/SlotElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/SvelteElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/fragment.js
#13075 added support for expressions in templates, but I think we can neaten it up a bit — rather than creating new `push_quasi` and `push_expression` functions, `state.template` can just be an `Array<string | Expression>` that gets processed later. This is more efficient, and in line with how similar problems are solved elsewhere in the codebase. (In terms of variable naming: it's awkward to have an array with a singular name — `quasi` — which then forces the individual quasi to be called something cumbersome like `quasi_to_add`. It should just be `quasis.push(quasi)`! Though really it should have been `strings.push(string)`, because we're not actually dealing with quasis at this point.)
Another benefit of this approach is that we can vary the output more easily — we could, if we chose, …
=> chore: tweak template generation logic

package.json, pnpm-lock.yaml
enforces that `process` is imported
=> chore: bump @sveltejs/eslint-config

.changeset/silly-fishes-deny.md, .changeset/wild-mice-look.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/internal/client/dev/css.js, packages/svelte/src/internal/client/dom/css.js, packages/svelte/src/internal/client/index.js, packages/svelte/tests/runtime-browser/samples/mount-in-iframe/App.svelte, packages/svelte/tests/runtime-browser/samples/mount-in-iframe/Child.svelte, packages/svelte/tests/runtime-browser/samples/mount-in-iframe/_config.js, packages/svelte/tests/runtime-browser/samples/mount-in-iframe/main.svelte
Hello Svelte Team,
I use Svelte to create injectable widgets in other apps.
I found a good way to do this with svelte by mounting component into an `iframe`.
This way, it allows a good resource cleanup and good responsive layout.
I used to do this in Svelte 4 and in Svelte 5 prior PR #12374.
In the specified PR, the process of injecting css into dom was changed.
This breaks some cases of mounting a component into an `iframe`:
- If the component is destroyed then remounted, the css is not injected again
- In dev, HMR does not work anymore (i did not succeed to make it work for now)
This PR enhances `append_styles` to allow it to be aware of the current component context and correctly inject css.
It also fix the need to pass `is_custom_element` to `append_styles` since it's a similar case. …
=> fix: allow component to be mounted in iframe

packages/svelte/src/internal/client/runtime.js
small thing while looking into #13282 — we don't encounter destroyed effects here, so we can remove the `// TODO` and just check for inertness
=> chore: remove unused DESTROYED check

.changeset/brave-candles-serve.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/derivations-no-colon/input.svelte, packages/svelte/tests/migrate/samples/derivations-no-colon/output.svelte, packages/svelte/tests/migrate/samples/derivations/input.svelte, packages/svelte/tests/migrate/samples/derivations/output.svelte, packages/svelte/tests/migrate/samples/state-and-derivations-sequence/input.svelte, packages/svelte/tests/migrate/samples/state-and-derivations-sequence/output.svelte
Closes #13278
While working on this i noticed that the sequence expression was a problem for `$state` too. Also while the migration correctly migrate this
```ts
$: double = (console.log(double), count * 2);
```
the resulting code will actually error at runtime because a derived is accessing himself. This however is a bit harder to migrate effectively because either we should move it to state+effect (kinda 🤮) or we should have an external non stateful variable. Regardless i think we should do this in a separate PR.
If your PR concerns Svelte 4 (including updates to …
=> fix: correctly migrate sequence expressions

.changeset/silent-elephants-film.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/internal/client/dom/css.js, packages/svelte/tests/runtime-browser/samples/mount-in-iframe/Child.svelte, packages/svelte/tests/runtime-browser/samples/mount-in-iframe/GrandChild.svelte, packages/svelte/tests/runtime-browser/samples/mount-in-iframe/_config.js
#13225 did not fully fix the described issue: As soon as you have a child component, that child component's anchor will not be in the right ownerDocument yet, and so the logic falls down.
To fix that, we would need to move the ownerDocument check into the microtask - and that map check was mainly done to avoid just that. So instead I opted to simplify the code and just remove the map checks. According to my benchmarking (https://jsbench.me/3hm17l0bxl/1) this has no impact on performance assuming that you'll have cache hits roughly half the time - and even if you'd have much more cache hits, the performance loss is microscopic. Given that the default mode is to not inject styles, this will not be common anyway, so I favor removing that map.
=> fix: simplify and robustify appending styles

.changeset/lucky-drinks-push.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/migrate/samples/props-interface/input.svelte, packages/svelte/tests/migrate/samples/props-interface/output.svelte
=> fix: handle `$$Props` interface during migration

packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/client/types.d.ts
I missed this on my PR that added the effect parent to the deferred component effects, meaning the owner if a derived was never being connected to the effect. I don't believe this fixes anything standalone, but it's the correct thing to do given how the internal mechanics around ownership work.
=> fix: ensure component effects have the correct reaction owner

.changeset/plenty-rings-stare.md, packages/svelte/src/internal/client/constants.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/tests/runtime-runes/samples/effect-inside-derived/_config.js, packages/svelte/tests/runtime-runes/samples/effect-inside-derived/main.svelte
Fixes #13296. Right now, effects created inside deriveds are attached to whichever effect (if any) is running then the derived happens to be evaluated. That can mean that the effect is never added to the tree at all, and if it _is_ added it's added in a location that's effectively random. This PR fixes it.
=> fix: attach effects-inside-deriveds to the parent of the derived

packages/svelte/src/internal/client/dom/elements/custom-element.js, packages/svelte/src/internal/client/runtime.js
An opportunity created by #13309 — if we create an effect root inside custom elements (which seems like the more correct thing to do anyway) then we can simplify `flush_queued_root_effects`.
Tests will fail until #13309 is merged
=> chore: create effect root for custom element

.changeset/new-baboons-fetch.md, documentation/docs/02-template-syntax/02-basic-markup.md, packages/svelte/src/utils.js
This was done previously to align with browser behavior, but the browser behavior actually only makes them passive on window/document/body. Since wheel events are not delegated, we can revert their passive-by-default setting. Closes #13318
For touchstart/touchmove we're not changing it because these events are delegated, which means they happen a lot more often on a target higher up the tree, which may cause jank.
=> fix: don't make wheel events passive by default

.changeset/cold-socks-learn.md, packages/svelte/src/animate/index.js
Continuation of #13107. I've tried so far in vain to solve the Firefox bugs, and will likely admit defeat since it's a real edge case.
It turns out we can't infer the effective zoom level from `style.width` relative to the bounding client rect, because of CSS transforms. Instead we need to read `element.currentCSSZoom` or — in Safari, which doesn't support it — calculate it manually by walking up the DOM.
I did find [some other issues](https://svelte-5-preview-git-better-flip-svelte.vercel.app/#H4sIAAAAAAAAE4WU3Y6bMBCFX2VKKwFVAiTZVSUCkfoAfYLNXjjGBGuNbdlD2hTx7pX5y6ZIyZUHn-_MwIxN65VcMOulb60nSc281Puptbfy8Krdg70wgcxbeVY1hrqdzFLDNR6O8oi81sogtFAKrqGD0qga_METE8lrgszfH6VjBUMQDJEZCzl8s0iQBT450YL5kdWCY-D7Ybif2L9K1TcQTcPCMVPZSIpcSbBVU5aCBSG0bn_wccinOpFg8ozVfhB_V1wwCPh6PfNHpEpaBAM5_CJYRaVQygR9aIgsVB2E …
=> feat: better `flip` animations

.changeset/unlucky-spies-flow.md, packages/svelte/src/internal/client/dev/inspect.js
It's not really actionable and also confusing because the user doesn't see `$state.snapshot` anywhere in their code
Came up in https://discord.com/channels/457912077277855764/1153350350158450758/1286319132639363193
=> fix: silence snapshot warnings inside `$inspect`

.changeset/perfect-ants-allow.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-runes/samples/attribute-if-string/_config.js, packages/svelte/tests/runtime-runes/samples/attribute-if-string/main.svelte
Alternative to #12734. Closes #12664. This feels like a more principled approach to the problem: if something is a non-string and exists as a property on the element, set it as a property, otherwise set it as an attribute.
This allows us to handle some of the platform's oddities gracefully, without needing to ship a lookup to the browser: if a component contains `<div translate="no">`, then we disable translation on that element (with `div.setAttribute('translate', 'no')`). If it contains `translate={false}`, we achieve the same outcome with `div.translate = false`.
~~Draft because I just realised that we still need a lookup for SSR~~
=> fix: set strings as attributes, non-strings as properties if property exists

.changeset/beige-clocks-notice.md, packages/svelte/src/internal/client/dom/elements/attributes.js
I, err... broke the site. Turns out some elements (e.g. `<svg>`) have getter-only properties, and trying to set them as properties instead of attributes causes a crash. This fixes it. There's no test, because JSDOM appears to behave different than browsers.
=> fix: only set attribute as property if element has setter

packages/svelte/src/internal/client/dom/elements/attributes.js
Followup to #13341. I haven't actually tested or benchmarked this, but it seems like this ought to be an improvement, as we're now using the same cache in the new place we're using `get_setters()`.
=> perf: improve get_setters cache

packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js
This is a precursor to #13270. We need to change how we deal with the combination of attributes and class/style directives, and ideally unify how attributes are handled between `RegularElement` and `SvelteElement`. A first step towards that is moving the special case logic (for specific elements like `<img>` or `<input>` or whatever) out of the loop in which we separate attributes out into their different types.
This PR just tries to make the logic a bit less entangled, and a bit easier to follow, with fewer variables declared far from their usage sites etc.
=> chore: refactor `RegularElement` visitor

packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/SvelteElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/element.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/element.js, packages/svelte/src/internal/client/dom/elements/attributes.js
This extracts the refactoring stuff out of #13338. It doesn't change any behaviour, it just dries the code out — at present there's a ton of duplication between `RegularElement` with a `SpreadAttribute`, and `SvelteElement` (which always uses `set_attributes` because we need to be conservative about custom elements).
The next step will be to generate code differently so as to fix #13270, but merging this first will reduce the noise of that work substantially. I'll self-merge this once green, since it's just moving some code around, so that I can continue working on that.
=> chore: refactor `set_attributes` code generation

packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/effects-with-alias-run/input.svelte, packages/svelte/tests/migrate/samples/effects-with-alias-run/output.svelte
When importing run if there's already a function called run we alias our own run. There was a missing space resulting in broken code.
=> fix: missing space when importing run as in migration

documentation/examples/20-7guis/04-7guis-timer/App.svelte
The example doesn't work when copied to a fresh sveltekit project, it produces errors such as `ReferenceError: window is not defined` and `ReferenceError: requestAnimationFrame is not defined`
- an example of this pattern used else where in the codebase [link](https://github.com/sveltejs/svelte/blob/main/documentation/tutorial/06-bindings/12-bind-this/app-b/App.svelte)
- relevant discord convo [link](https://discord.com/channels/457912077277855764/1286736007613644800)
If your PR concerns Svelte 4 (including updates to [svelte.dev.docs](https://svelte.dev/docs)), please ensure the base branch is …
=> docs: Update 7guis-timer example to support SSR context

packages/svelte/package.json, pnpm-lock.yaml
removes some more dev dependencies
=> chore: upgrade rollup plugins

.changeset/perfect-avocados-greet.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/internal/client/dom/legacy/event-modifiers.js, packages/svelte/src/legacy/legacy-client.js, packages/svelte/tests/migrate/samples/event-handlers-with-alias/input.svelte, packages/svelte/tests/migrate/samples/event-handlers-with-alias/output.svelte, packages/svelte/tests/migrate/samples/event-handlers/input.svelte, packages/svelte/tests/migrate/samples/event-handlers/output.svelte, packages/svelte/tests/migrate/samples/state-ts/output.svelte, packages/svelte/types/index.d.ts
Closes #13273
This is super draft and it's just to play around with the output and discuss.
=> fix: migrate events to be more inline with svelte 4

.changeset/tasty-mice-admire.md, packages/svelte/src/internal/client/render.js, packages/svelte/tests/runtime-runes/samples/mount-unmount-anchor/Component.svelte, packages/svelte/tests/runtime-runes/samples/mount-unmount-anchor/_config.js, packages/svelte/tests/runtime-runes/samples/mount-unmount-anchor/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13371#issuecomment-2371439151. We need to ensure we remove the anchor text node from the root when we unmount.
=> fix: properly remove root anchor node on unmount

packages/svelte/src/compiler/utils/compile_diagnostic.js
Just adding a new line to multiline comment of `typedef` definition.
It simply improves syntax highlighting(in VS Code).
=> chore: add a newline to multiline comment for proper syntax highlighting

.changeset/nice-brooms-battle.md, packages/svelte/src/internal/client/dev/ownership.js, packages/svelte/tests/runtime-runes/samples/ownership-with-proxy/_config.js, packages/svelte/tests/runtime-runes/samples/ownership-with-proxy/main.svelte
Closes #13376
This fixes the problem but i fear we might have this problem elsewhere and this can still be somewhat tricked unless we specify a lot of constraint. The problem when someone returns some non null value from a proxy regardless of the key eg
```svelte
<script>
import { setContext, getContext } from "svelte";
setContext("", new Proxy({}, {
get(){
return {};
}
}));
getContext("");
</script>
```
inside the ownership validation function we assume that if it has metadata it's the svelte metadata object (honestly a reasonable assumption considering it's a Symbol). But in this case the object will always be this empty object. So when trying to access `owners.add` on it or `[ADD_OWNER]` we end up with a runtime error.
By adding `owners in object` check it's fixed but that will fail if …
=> fix: ownership getting tricked by proxies

packages/svelte/src/compiler/phases/3-transform/utils.js, packages/svelte/src/internal/client/dom/template.js, packages/svelte/tests/runtime-browser/samples/head-scripts/_config.js, packages/svelte/tests/runtime-browser/samples/head-scripts/main.svelte
`template_with_script()` is buggy when it contains only one `<script>` element, because the `run_scripts()` will clone and replace the scripts.
There no problem when using a DocumentFragment because they are replaced immediately inside the fragment.
But with a single node the element cannot be replaced, and it's done later with queue_micro_task().
=> So the cloned script is put on the DOM, but `template_with_script()` will return the previous script element (so reactivity is broken).
See #13378 
Should I make a test for that ?
If your PR concerns Svelte 4 (including updates to …
=> fix : reactivity bug with single script in svelte:head

.changeset/early-needles-bake.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/css-ignore/input.svelte, packages/svelte/tests/migrate/samples/css-ignore/output.svelte
Blank CSS, could contain SCSS or similar that needs a preprocessor. Since we don't care about CSS in this migration, we'll just ignore it.
=> fix: blank CSS contents while migrating

sites/svelte-5-preview/src/app.html
just noticed we're not preloading on hover on the preview site. we're leaving performance on the table
=> preload on hover

.changeset/nervous-chefs-exist.md, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/a11y.js, packages/svelte/tests/validator/samples/a11y-consider-explicit-label/input.svelte
fixes #13365, and will allow the SvelteKit tests to start passing again
=> fix: treat `<img>` alt attribute as content for a11y labelling purposes

.changeset/lazy-queens-agree.md, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/css/samples/unused-nested-at-rule/_config.js, packages/svelte/tests/css/samples/unused-nested-at-rule/expected.css, packages/svelte/tests/css/samples/unused-nested-at-rule/input.svelte
Closes #13390
I spend quite a bit of time to try to fix this just to realise that there's no reason a nested AtRule should mark the wrapping rule as used.
```css
.foo {
display: grid;
@media (orientation: landscape) {
grid-auto-flow: column;
}
}
```
this is equivalent to
```css
.foo {
display: grid;
}
@media (orientation: landscape) {
.foo {
grid-auto-flow: column;
}
}
```
but if foo is unused it will still be unused inside the media query.
=> fix: don't consider used rules with atrules in the block

.changeset/eight-waves-mate.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/slots-custom-element/input.svelte, packages/svelte/tests/migrate/samples/slots-custom-element/output.svelte
No issue, it was reported by Theo on discord.
=> fix: avoid migrating slots in custom elements

packages/svelte/src/action/public.d.ts, packages/svelte/src/animate/index.js, packages/svelte/src/compiler/index.js, packages/svelte/src/compiler/preprocess/index.js, packages/svelte/src/easing/index.js, packages/svelte/src/index-client.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/motion/spring.js, packages/svelte/src/motion/tweened.js, packages/svelte/src/store/shared/index.js, packages/svelte/src/transition/index.js, packages/svelte/src/version.js, packages/svelte/types/index.d.ts
there's truly no point in doc comments including links to a page that just includes the exact some content. It just creates extra work when generating the docs pages, since we would have to strip out the links (which sometimes have a `Docs: ` prefix and sometimes don't), and it creates the possibility of the links getting stale if we evolve the site structure.
=> chore: remove links from docs

documentation/docs/01-introduction/03-reactivity-fundamentals.md
On the new site we're building, we have collapsible boxes explaining differences between legacy and runes mode. This PR adds some example content, which gets synced into the other repo
=> docs: add legacy callouts

packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/event-handlers-with-alias/output.svelte, packages/svelte/tests/migrate/samples/event-handlers/output.svelte
I was working on the migration for `svelte:component` but the code to compose together the instance was getting a bit messy because we were trying to add stuff all in the same place if there was no `script` or one by one if there was one. I changed this a bit by using an `insertion_point` variable that we can set to then insert stuff sequentially. It seems to work fine except some minor changes in whitespace but i would love an extra look from @dummdidumm 
I'm using this already locally to add the migration for svelte component.
P.s. i've also noticed another bug that i had to fix locally which is that we never visit the expression of `svelte:component` even in normal analysis. This means that if the expression is using `$$props` we don't have `uses_props` correctly initialized. Should i …
=> chore: refactor migration composition logic

documentation/blog/2024-10-01-whats-new-in-svelte-october-2024.md
lemme know if i missed anything!
=> docs: "What's new in Svelte" October newsletter

.changeset/funny-houses-kick.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/props-interface/input.svelte, packages/svelte/tests/migrate/samples/props-interface/output.svelte
=> fix: migrate `$$Props` without creating non existent props

.changeset/many-fishes-warn.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/props-and-labeled/input.svelte, packages/svelte/tests/migrate/samples/props-and-labeled/output.svelte
=> fix: move labeled statements that need reordering after props insertion point

packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/tests/css/samples/global-nested-block/_config.js, packages/svelte/tests/css/samples/global-nested-block/expected.css, packages/svelte/tests/css/samples/global-nested-block/input.svelte
=> fix: mark nesting selectors of global parents as used

.changeset/young-ducks-punch.md, packages/svelte/src/compiler/phases/1-parse/read/style.js, packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/tests/css/samples/nested-css-combinator/_config.js, packages/svelte/tests/css/samples/nested-css-combinator/expected.css, packages/svelte/tests/css/samples/nested-css-combinator/input.svelte, packages/svelte/tests/validator/samples/css-invalid-combinator-selector-1/errors.json, packages/svelte/tests/validator/samples/css-invalid-combinator-selector-2/errors.json, packages/svelte/tests/validator/samples/css-invalid-combinator-selector-3/errors.json
Solved by moving the combinator positioning validation into the analysis phase
Fixes #13433
=> fix: allow combinator at start of nested CSS selector

.changeset/neat-ways-allow.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/SlotElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/SlotElement.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/component.js, packages/svelte/src/internal/client/dom/blocks/slot.js, packages/svelte/src/internal/client/dom/legacy/misc.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-runes/samples/snippets-as-slots/_config.js, packages/svelte/tests/runtime-runes/samples/snippets-as-slots/child.svelte, packages/svelte/tests/runtime-runes/samples/snippets-as-slots/main.svelte
This allows people to use snippets to fill slots. It is implemented in the same way the default slot interop is already implemented, by passing a boolean to the hidden `$$slots` object, and using that at runtime to determine the correct outcome. The impact on bundle size is neglible.
By enabling this, we can enhance our migration script to always transform slot usages (including `let:x` etc) to snippets. This wasn't possible before because we couldn't be sure if the other side was transformed to using render tags at the same time. This will be part of #13419. This is important because currently the migration script is transforming `<slot />` creations inside components, but since it's not touching its usage points the migration will make your app end up in a broken state which you have to …
=> feat: enable snippets to fill slots

.changeset/nine-kids-whisper.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/props-rest-props/output.svelte, packages/svelte/tests/migrate/samples/slots-custom-element/input.svelte, packages/svelte/tests/migrate/samples/slots-custom-element/output.svelte, packages/svelte/tests/migrate/samples/slots-with-$$props/input.svelte, packages/svelte/tests/migrate/samples/slots-with-$$props/output.svelte, packages/svelte/tests/migrate/samples/slots/input.svelte, packages/svelte/tests/migrate/samples/slots/output.svelte, packages/svelte/tests/migrate/samples/svelte-component/output.svelte
Closes #13467 (i've also fixed a bug regarding the migration of `$$slots` when the component is a custom element.
EDIT: it was simple enough so i also fixed #13466 
EDIT to the EDIT: i also fixed #13472 in this PR...since it was not reviewed yet i just pushed here, if you need a clearer vision while reviewing you can just look at the separate commits since they are pretty much self contained.
=> fix: correctly migrate `$$slots` with bracket member expressions & slots with static props

.changeset/friendly-taxis-hammer.md, packages/svelte/elements.d.ts
The `search` element only has global attributes [MDN](<https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search#attributes>)
fixes #13487 
=> feat: add types for the `search` element

.changeset/great-dots-wonder.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/single-assignment-labeled/input.svelte, packages/svelte/tests/migrate/samples/single-assignment-labeled/output.svelte
I took a shot at closing #13460
Also closes #13459
It seems to work fine but i don't know if i'm missing some weird use case i was not able to think about.
=> feat: support migration of single assignment labeled statements

.changeset/small-suns-lie.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/slot-usages/_config.js, packages/svelte/tests/migrate/samples/slot-usages/input.svelte, packages/svelte/tests/migrate/samples/slot-usages/output.svelte, packages/svelte/tests/migrate/samples/svelte-component/output.svelte
Now that snippets can fill slots, we can add logic to migrate slot usages
There's some cases where it doesn't look as nice due to indentation but I'm not sure how much time we should invest in that
=> feat: migrate slot usages

.changeset/gold-pens-sell.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/svelte-self-name-conflict/input.svelte, packages/svelte/tests/migrate/samples/svelte-self-name-conflict/output.svelte, packages/svelte/tests/migrate/samples/svelte-self-skip-filename/_config.js, packages/svelte/tests/migrate/samples/svelte-self-skip-filename/input.svelte, packages/svelte/tests/migrate/samples/svelte-self-skip-filename/output.svelte, packages/svelte/tests/migrate/samples/svelte-self/input.svelte, packages/svelte/tests/migrate/samples/svelte-self/output.svelte, packages/svelte/tests/migrate/test.ts, packages/svelte/types/index.d.ts, sites/svelte-5-preview/src/lib/Output/Compiler.js, sites/svelte-5-preview/src/lib/workers/compiler/index.js
This adds the ability to migrate `svelte:self` which is deprecated. We need the filename to be able to auto-import so i've added it to the signature of the migrate function. If the user is using an older version of the cli which doesn't pass the filename in i've added a `@migration-task` as a comment.
Don't know if we want to do it but i'd say if we want to do it better do it now than later. I'll prepare a PR for `kit` too to pass the filename during the migration script.
If your PR concerns Svelte 4 (including updates to [svelte.dev.docs](https://svelte.dev/docs)), please ensure the base branch is …
=> feat: migrate `svelte:self`

.changeset/fair-items-bathe.md, packages/svelte/src/internal/client/dom/elements/bindings/media.js
I'm a little nervous about this because the code I deleted _looks_ like it's doing something useful, and it's basically impossible to test for, but:
- I don't really understand what, and
- Right now, media elements are broken — toggling `paused` doesn't cause a media element with `bind:paused` to start playing
This fixes it, as far as I can tell. I've tested `mount` and `hydrate` with media elements that are rendered immediately, media elements that are rendered after a state change, and media elements with an artificial network delay that I would expect to trigger whatever `canplay` timing edge cases we'd encounter.
=> fix: add media listeners immediately when using `bind:paused`

.changeset/tiny-ads-press.md, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/RegularElement.js, packages/svelte/src/compiler/phases/nodes.js, packages/svelte/src/compiler/types/template.d.ts, packages/svelte/tests/runtime-runes/samples/custom-element-svelte-class/_config.js, packages/svelte/tests/runtime-runes/samples/custom-element-svelte-class/main.svelte
Closes #13426 
Initially i just marked every custom element as dynamic but that would've been a lot more code generated if there was a custom element that was actually skipped (this was problematic only because that custom element ends up having an attribute (the virtual class file). Since i needed the `path` to mark the tree as dynamic i've added it to the metadata because i didn't find a way to get the path from the element itself but if there's a better approach i can change it obviously.
If your PR concerns Svelte 4 (including updates to [svelte.dev.docs](https://svelte.dev/docs)), please ensure the …
=> fix: mark custom element with virtual class attribute as dynamic

.changeset/eighty-hornets-breathe.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/tests/runtime-runes/samples/dynamic-attribute-and-attribute-directive-2/_config.js, packages/svelte/tests/runtime-runes/samples/dynamic-attribute-and-attribute-directive-2/main.svelte
Since the issue has come up multiple times and i didn't see much activity on #13338 (sorry @Rich-Harris if you were working on it) i took a shot at it. This PR make the test pass (i've also added the same logic for `style` attribute and directive since it also can be overridden by the directive. I've used the same technique that we use for the class and style directive of creating a derived for the function and change the `value` there. There's a bit of duplication which i don't particularly like but maybe it's better for readability.
Are there are better ways of doing this?
If your PR concerns Svelte 4 …
=> fix: apply class/style directives after attributes

.changeset/giant-ladybugs-thank.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/src/internal/client/dom/legacy/lifecycle.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-legacy/samples/immutable-before-after-update/ImmutableTodo.svelte, packages/svelte/tests/runtime-legacy/samples/immutable-before-after-update/_config.js, packages/svelte/tests/runtime-legacy/samples/immutable-before-after-update/main.svelte, packages/svelte/tests/runtime-legacy/samples/immutable-mutate-object/_config.js, packages/svelte/tests/runtime-legacy/samples/immutable-mutate-object/main.svelte
- make sure to not overfire before/afterUpdate
- make sure to not fire mutable sources when they were mutated
- only show deprecation warning when in runes mode to not clutter up console (this is in line with how we made it in other places)
fixes #13454
=> fix: make immutable option work more correctly

.changeset/soft-stingrays-attend.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/svelte-self-name-conflict/input.svelte, packages/svelte/tests/migrate/samples/svelte-self-name-conflict/output.svelte, packages/svelte/tests/migrate/samples/svelte-self/output.svelte
=> fix: use `analysis.name` when migrating `<svelte:self>`

.changeset/beige-donkeys-exercise.md, packages/svelte/src/compiler/phases/3-transform/index.js
Similar to a change that was part of #10459
Fixes https://github.com/sveltejs/svelte-loader/issues/238
=> fix: ensure source and filename are known to compileModule's source map

.changeset/loud-walls-wave.md, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-runes/samples/each-was-empty/_config.js, packages/svelte/tests/runtime-runes/samples/each-was-empty/main.svelte
Fix #13550 
The `block()` function inside `each()` can run multiples times when the collection is a different falsy array (ex. `array = undefined` and then `array = null` or `array = []`).
It seems that this is causing a conflict between `reconcile()` and the `fallback_fn` effect, which is no longer reactive.
=> When the array change from empty to empty, it is better to do nothing at all.
All tests are OK.
Should I add a test for this specific case ?
=> fix: do no rerun the each block when array change from empty to empty

.changeset/ninety-months-laugh.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-3/main.svelte, packages/svelte/tests/signals/test.ts
Deriveds now cleanup accordingly when the effect that they were created in gets destroyed. This should resolve a memory leak with deriveds that created in branch/root effects – and thus were previously never cleaned up as these effects don't know of the deriveds in the first place. This essentially aims to solve this memory leak:
```svelte
<script>
import Foo from './Foo.svelte';
let count = $state(0);
let toggle = $state(0);
</script>
{#if toggle}
{@const double = count * 2}
<Foo double={double} />
{/if}
<button onclick={() => toggle = !toggle}>toggle</button>
<button onclick={() => count++}>increment</button>
<script>
const { double } = $props();
// read the prop, now it leaks when we toggle and hide this component
double;
</script>
```
Above the `double` derived leaks, with this PR we …
=> fix: ensure effects destroy owned deriveds upon teardown

.changeset/slow-badgers-invite.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/dom/elements/bindings/input.js
Closes #13565 no test because apparently JSDom doesn't support this stuff.
=> fix: avoid assigning input.value if the value is the same to fix `minlength`

.changeset/eleven-humans-kneel.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/clean-block-inner-effects/_config.js, packages/svelte/tests/runtime-runes/samples/clean-block-inner-effects/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13573. Alternative to https://github.com/sveltejs/svelte/pull/13586
=> fix: cleanup non-branch effects created inside block effects

.changeset/pink-shirts-film.md, packages/svelte/src/internal/client/proxy.js, packages/svelte/tests/runtime-runes/samples/inspect-deep-array/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-deep-array/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13494. It turns out that we don't correctly update the length of a proxied array upon deletions – which is why the inspect causes so many issues here.
=> fix: ensure proxied arrays correctly update their length upon deletions

.changeset/silly-houses-promise.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/src/compiler/types/css.d.ts, packages/svelte/tests/css/samples/has/_config.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/has/input.svelte, packages/svelte/types/index.d.ts, sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
The main part of #13395
This implements scoping for selectors inside `:has(...)`. The approach is to first descend into the contents of a `:has(...)` selector, then in case of a match, try to match the rest of the selector ignoring the `:has(...)` part. In other words, `.x:has(y)` is essentially treated as `x y` with `y` being matched first, then walking up the selector chain taking into account combinators.
This is a breaking change because people could've used `:has(.unknown)` with `.unknown` not appearing in the HTML, and so they need to do `:has(:global(.unknown))` instead
=> breaking: scope `:has(...)` selectors

packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/has/_config.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/has/input.svelte
We need to ignore the leading combinator within a `:has(...)`, else it would not stop matching, assuming there are more parent selectors (which there aren't) and always fail.
https://github.com/sveltejs/svelte/pull/13567#issuecomment-2412405131
No changeset because not released yet
=> fix: handle leading combinators within `:has(...)`

documentation/docs/03-runes/02-side-effects.md, documentation/docs/04-runtime/04-imperative-component-api.md, documentation/docs/05-misc/04-custom-elements.md, packages/svelte/src/compiler/preprocess/index.js, packages/svelte/types/index.d.ts
=> docs: more fixes

.changeset/clean-sloths-nail.md, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/tests/runtime-runes/samples/props-local-teardown/Component.svelte, packages/svelte/tests/runtime-runes/samples/props-local-teardown/_config.js, packages/svelte/tests/runtime-runes/samples/props-local-teardown/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13605. Now we have ownership of deriveds, if we have the case where a prop is re-assigned locally then we need to ensure that upon teardown of the local component we switch to using that value and not that of the parent derived, as that derived will now be destroyed already.
=> fix: ensure local prop value is read during teardown

.changeset/bright-seas-brake.md, packages/svelte/elements.d.ts
The `until-found` value of the `hidden` attributes allows find-in-page functionnality, and the `beforematch` event can intercept it. 
[spec](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute) [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden#using_until-found) [REPL](<https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE0WMwWrDMBBEf0VMLwm4zd21BPmObA-utYoF8q6xZIdg_O9FJNDT8OYxsyPExBntbYf0E6PFdZ7RoDznCnnjVBgNsq7LUJuuN-PCwRI-8qgPgqvRXXpHQtL5uJEYE70lvHzFMXrPYgmrlJg-g67iq6Gi8stBF576Mox2P_HZWGf2OjJmUMma-Cvp_UR4r87fVR4Hifu_JukuPm6OBA0m9TFE9mjLsvLxc_wBJY1zmuYAAAA=>) 
Please note that [the Svelte codebase is currently being rewritten for Svelte 5](https://svelte.dev/blog/runes). Changes should target Svelte 5, which lives on the default branch …
=> feat: hidden until found and beforematch

.changeset/cool-apes-confess.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/reactive-statements-reorder-not-deleting-additions/input.svelte, packages/svelte/tests/migrate/samples/reactive-statements-reorder-not-deleting-additions/output.svelte
Closes #13615
Not super happy with this but didn't find a better way. The problem is that the code assumes that we will remove one character in case of `\n` or 2 in case of `\r\n`. However based on how `MagicString` works if we inserted a character at that position before removing at that position will also remove the inserted character.
To fix this i snip the already transformed string to take a look at what we are removing and i trim it...any character left is added to the remove starting point.
I don't think we can find a situation where we have a character after the carriage so this should work.
If …
=> fix: ensure inserted code is preserved during migration

.changeset/nine-vans-admire.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
https://github.com/sveltejs/svelte/pull/13563 introduced owned deriveds, but it turns out that eagerly attaching each derived to its parent effect upon creation wasn't ideal. Instead, we can lazily do it upon encountering a read on a derived in a context where there is no active reaction. I can't believe I didn't think of this sooner!
Before:
After:
=> chore: improve derived ownership model

.changeset/happy-eggs-rest.md, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/dom/elements/bindings/input.js, packages/svelte/tests/runtime-runes/samples/checkbox-binding-derived/_config.js, packages/svelte/tests/runtime-runes/samples/checkbox-binding-derived/checkbox.svelte, packages/svelte/tests/runtime-runes/samples/checkbox-binding-derived/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13604. 
When we mount the each block for the first time, the collection won't be connected to this effect as the effect hasn't finished running yet and its deps won't be assigned. However, it's possible that when reconciling the each block that a mutation occurred and it's made the collection `MAYBE_DIRTY`, so reading the collection again can provide consistency to the reactive graph again as the deriveds will now be `CLEAN`.
=> fix: ensure each block consistency to internal mutations to the collection

.changeset/shiny-jobs-judge.md, packages/svelte/src/internal/client/runtime.js
Missed an opportunity to check if `deps` was already populated or not. If it is populated, we know that we don't need to add or check for ownership on the derived having `deps` means we've already done this work before – avoiding the need to do a O(n) lookup in the parents.
=> chore: improve runtime performance of derived signals

.changeset/eighty-dryers-pretend.md, documentation/docs/98-reference/.generated/client-errors.md, packages/svelte/messages/client-errors/errors.md, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/errors.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-runes/samples/side-effect-each/_config.js, packages/svelte/tests/runtime-runes/samples/side-effect-each/main.svelte
The problem of mutations in logic block expressions has come up a dozen or so times now, the latest is https://github.com/sveltejs/svelte/issues/13446. The common one is sorting in the expression:
```svelte
{#each items.sort() as item (item)}
<p>{item}</p>
{/each}
```
This PR changes it so block effects behave a bit like deriveds and forbid state mutations. This in turn will help developers find issues in their applications quickly by hitting the error about unsafe mutations rather than too many updates error message which is harder to track down.
=> breaking: disallow state mutations in logic block expression

.changeset/popular-dolphins-shake.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/reactive-statements-reorder-with-comments/input.svelte, packages/svelte/tests/migrate/samples/reactive-statements-reorder-with-comments/output.svelte
Closes #13618 
There's also another situation that i think we should fix somehow but i think it involves a bit of discussion so i'll open a new issue about it.
=> fix: better migration for leading and trailing comments

.changeset/forty-chicken-heal.md, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/tests/runtime-runes/samples/await-non-promise/_config.js, packages/svelte/tests/runtime-runes/samples/await-non-promise/main.svelte
=> fix: use `internal_set` in `await` block

.changeset/khaki-mirrors-warn.md, packages/svelte/elements.d.ts
=> fix: `method` is case insensitive

.changeset/eight-pans-worry.md, packages/svelte/src/internal/client/dom/blocks/svelte-component.js, packages/svelte/tests/runtime-runes/samples/transition-component/Foo.svelte, packages/svelte/tests/runtime-runes/samples/transition-component/_config.js, packages/svelte/tests/runtime-runes/samples/transition-component/main.svelte
Fix #13645 
The block() used in `$.component()` must use the flag `EFFECT_TRANSPARENT` in order to preserve transition.
=> fix : $.component() break transition

.changeset/light-crews-deny.md, packages/svelte/src/internal/client/dev/inspect.js, packages/svelte/tests/runtime-runes/samples/inspect-exception/Component.svelte, packages/svelte/tests/runtime-runes/samples/inspect-exception/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-exception/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13577. If we encounter a runtime exception when getting the values for an inspection we bail out reporting the inspection. This can occur naturally because inspect effects are run sync, and thus they can operate before a parent render effect runs that would have invalidated the inspect effect had they not be sync.
=> chore: avoid reporting inspections when an exception occurs

.changeset/healthy-poets-float.md, packages/svelte/src/compiler/phases/2-analyze/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/fragment.js, packages/svelte/tests/runtime-legacy/samples/autofocus-2/_config.js, packages/svelte/tests/runtime-legacy/samples/autofocus-2/main.svelte, packages/svelte/tests/runtime-legacy/samples/autofocus-3/_config.js, packages/svelte/tests/runtime-legacy/samples/autofocus-3/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13644
=> fix: correctly applies autofocus to static elements

.changeset/slimy-garlics-beg.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/impossible-migrate-beforeUpdate-afterUpdate/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-beforeUpdate-afterUpdate/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-prop-and-$$props/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-prop-and-$$props/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-prop-non-identifier/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-prop-non-identifier/output.svelte, packages/svelte/tests/migrate/samples/unused-beforeUpdate-afterUpdate-extra-imports/input.svelte, packages/svelte/tests/migrate/samples/unused-beforeUpdate-afterUpdate-extra-imports/output.svelte, packages/svelte/tests/migrate/samples/unused-beforeUpdate-afterUpdate/input.svelte, packages/svelte/tests/migrate/samples/unused-beforeUpdate-afterUpdate/output.svelte
Closes #13464
I've added a migration task comment at the beginning and since `afterUpdate` and `beforeUpdate` was not throwing i added the throw for them too. Since i was at it i thought that sometimes we just left imports lingering there and it would be a shame not migrating an otherwise migratable file just for this so i added a bit of "treeshake" logic to remove the import if it's not used.
=> feat: add `migration-task` comment after errors

.changeset/good-kings-try.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/slot-non-identifier/input.svelte, packages/svelte/tests/migrate/samples/slot-non-identifier/output.svelte
=> feat: add `migration-task` for impossible to migrate slots

.changeset/nasty-teachers-end.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/impossible-migrate-beforeUpdate-afterUpdate/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-prop-and-$$props/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-prop-non-identifier/_config.js, packages/svelte/tests/migrate/samples/svelte-self-skip-filename/_config.js, packages/svelte/tests/migrate/test.ts
=> feat: tell users of `@migration-task`

.changeset/witty-shirts-confess.md, packages/svelte/src/internal/server/dev.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-runes/samples/snippet-raw-component-ssr-dev/Child.svelte, packages/svelte/tests/runtime-runes/samples/snippet-raw-component-ssr-dev/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-raw-component-ssr-dev/main.svelte
Fixes the problem delineated in #13654...the problem is when you render a snippet that render a component inside an element. This is because the code looks like this
```ts
App[$.FILENAME] = "App.svelte";
import * as $ from "svelte/internal/server";
import { createRawSnippet, mount } from 'svelte';
import Child from './Child.svelte';
function App($$payload, $$props) {
$.push(App);
let count = 0;
const hello = createRawSnippet((count) => ({
render: () => `<div></div>`,
setup(target) {
mount(Child, { target });
}
}));
$$payload.out += `<div>`;
$.push_element($$payload, "div", 15, 0);
hello($$payload);
$$payload.out += `</div>`;
$.pop_element();
$.pop();
}
App.render = function () {
throw new Error("Component.render(...) is no longer valid in Svelte 5. See …
```
=> fix: reset `reset_element` in `render` to prevent runtime error

.changeset/violet-buses-cross.md, packages/svelte/src/compiler/utils/compile_diagnostic.js
Closes https://github.com/sveltejs/svelte/issues/13628.
=> chore: CompileDiagnostic no longer extends Error

.changeset/ten-vans-divide.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/slot-non-identifier/input.svelte, packages/svelte/tests/migrate/samples/slot-non-identifier/output.svelte, packages/svelte/tests/migrate/samples/slot-shadow-props/input.svelte, packages/svelte/tests/migrate/samples/slot-shadow-props/output.svelte
Closes #13665
While fixing i also noticed that we were incorrectly removing the let directive in the case where we don't migrate the slot if the let directive were there before the name of the slot.
=> fix: migrated snippet shadowing prop and let directive removal

.changeset/early-rockets-join.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/$$slots-used-as-variable-$$props/input.svelte, packages/svelte/tests/migrate/samples/$$slots-used-as-variable-$$props/output.svelte, packages/svelte/tests/migrate/samples/$$slots-used-as-variable/input.svelte, packages/svelte/tests/migrate/samples/$$slots-used-as-variable/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-slot-change-name/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-slot-change-name/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-slot-change-name/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-slot-non-identifier/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-slot-non-identifier/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-slot-non-identifier/output.svelte, packages/svelte/tests/migrate/samples/slots-multiple/input.svelte, packages/svelte/tests/migrate/samples/slots-multiple/output.svelte, packages/svelte/tests/migrate/samples/slots-with-$$props/input.svelte, packages/svelte/tests/migrate/samples/slots-with-$$props/output.svelte, packages/svelte/tests/migrate/samples/slots/input.svelte, packages/svelte/tests/migrate/samples/slots/output.svelte
Closes #13667
For the moment i've decided to bail out if we found a snippet that would change name. @dummdidumm was arguing that we should migrate `dashed-slot` to `dashed_slot` but since at the usage site we bail out if we found a non valid identifier i think we should bail inside the component too.
=> fix: bail out if slot name changes and $$slots assigned to variable

packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/runtime.js
Addresses the comment made in https://github.com/sveltejs/svelte/pull/13660#discussion_r1807121465. This PR makes effect cleanup more consistent and ensures we always remove any deriveds in an effect regardless of if it's a block effect or not. I also moved the functions into `effects.js` as that seems a better location for them all.
=> chore: ensure effect destruction of deriveds is consistent

.changeset/brave-rivers-jam.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/tests/runtime-runes/samples/effect-order-5/_config.js, packages/svelte/tests/runtime-runes/samples/effect-order-5/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13682 and adds a test to ensure we don't regress here again.
=> fix: ensure user effects are correctly executed on initialisation

.changeset/sweet-melons-itch.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/$$slots-used-as-variable-$$props/output.svelte, packages/svelte/tests/migrate/samples/$$slots-used-as-variable/output.svelte, packages/svelte/tests/migrate/samples/css-ignore/output.svelte, packages/svelte/tests/migrate/samples/jsdoc-with-comments/input.svelte, packages/svelte/tests/migrate/samples/jsdoc-with-comments/output.svelte, packages/svelte/tests/migrate/samples/props-and-labeled/output.svelte, packages/svelte/tests/migrate/samples/props-rest-props/output.svelte, packages/svelte/tests/migrate/samples/props/output.svelte, packages/svelte/tests/migrate/samples/reactive-statements-reorder-not-deleting-additions/output.svelte, packages/svelte/tests/migrate/samples/slots-below-imports/output.svelte, packages/svelte/tests/migrate/samples/slots-multiple/output.svelte, packages/svelte/tests/migrate/samples/slots-with-$$props/output.svelte, packages/svelte/tests/migrate/samples/slots/output.svelte, packages/svelte/tests/migrate/samples/svelte-component/output.svelte, packages/svelte/tests/migrate/samples/svelte-self-name-conflict/output.svelte, packages/svelte/tests/migrate/samples/svelte-self/output.svelte
Closes #13631
To "keep the comment" i cleaned up the jsdoc comment a bit removing the `*` and the `/**` and `*/`. Since a lot of stuff in the jsdoc is just JSDoc instead of an actual comment i stop at the first comment that starts with `@` but i don't know if this is the right strategy. Let's talk about it.
=> fix: use typedef for JSDoc props and maintain comments

.changeset/healthy-bees-wave.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/not-blank-css-if-error/input.svelte, packages/svelte/tests/migrate/samples/not-blank-css-if-error/output.svelte
This
```svelte
<script>
export let error = true;
</script>
<div>
{$$props}
</div>
<style lang="postcss">
div{
color: red;
}
</style>
```
was erroneusly migrated to
```svelte
<script>
export let error = true;
</script>
<div>
{$$props}
</div>
<style lang="postcss">/*$$__STYLE_CONTENT__$$*/</style>
````
=> fix: don't blank css on migration error

.changeset/famous-insects-sort.md, packages/svelte/src/internal/client/dom/elements/transitions.js
I noticed that we weren't wrapping the transition events that we dispatch without the current reaction. Let's be consistent as this is a sync event and the handler will be executed sync too (because of `element.dispatchEvent`), so we should ensure intro and outro events aren't associated with the transition block effect.
=> chore: ensure transition events are dispatched without current reaction

documentation/docs/02-template-syntax/05-styles-and-classes.md
=> docs: replace `<div>` with `<svelte-css-wrapper>` for style props

.changeset/nasty-guests-hammer.md, packages/svelte/elements.d.ts
fixes https://github.com/sveltejs/svelte/issues/13661
=> fix: webview can contain any string for preload

.changeset/tidy-spies-beg.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/component.js, packages/svelte/tests/runtime-runes/samples/slot-svelte-fragment-render-tag/_config.js, packages/svelte/tests/runtime-runes/samples/slot-svelte-fragment-render-tag/child.svelte, packages/svelte/tests/runtime-runes/samples/slot-svelte-fragment-render-tag/main.svelte, packages/svelte/tests/runtime-runes/samples/snippets-as-slots/child.svelte, packages/svelte/tests/runtime-runes/samples/snippets-as-slots/main.svelte
- correctly assign children snippet to default slot, fixes #13067
- allow `svelte:fragment` without `let:` directives to be rendered by `@render children()`, fixes #13066
=> fix: better children snippet / default slot interop

packages/svelte/src/compiler/migrate/index.js
This ensures that during migration, $deriveds are only applied to Identifiers, and not object properties. 
Fixes #13723. 
=> fix: don't migrate `$: foo.bar = baz` to use `$derived()`

.changeset/giant-plants-shout.md, packages/svelte/src/internal/client/dom/elements/events.js, packages/svelte/src/internal/client/dom/elements/transitions.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/tests/runtime-runes/samples/event-context/_config.js, packages/svelte/tests/runtime-runes/samples/event-context/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13684 and is a better approach than https://github.com/sveltejs/svelte/pull/13694 https://github.com/sveltejs/svelte/pull/13719.
Essentially, we have a complicated issue that only affects Chromium and they're well aware of it https://chromestatus.com/feature/5128696823545856. If you have an element with `onblur`, the event will fire _synchronously_ if that element is removed from the DOM or if the element or its parent moves in certain cases. This behaviour was discovered because of the improved validation around block effects erroring on state mutations – but has nothing to do with this issue at all, it actually was great that it helped show this huge issue. 
In the ideal world, event handlers are always without a reactive context – because …
=> fix: ensure event context is reset before invoking callback

.changeset/nasty-geese-turn.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/derivations/input.svelte, packages/svelte/tests/migrate/samples/derivations/output.svelte, packages/svelte/tests/migrate/samples/effects/input.svelte, packages/svelte/tests/migrate/samples/effects/output.svelte
- detect store mutations and not use `$derived` in that case, fixes #13723
- better detect `let x` that can be folded into `$derived`, fixes #13727
=> fix: more accurately detect `$derived` migration use cases

.changeset/moody-kids-brake.md, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/css/samples/has/_config.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/has/input.svelte
=> fix: do not comment out unused selectors that are inside an unused selector

.changeset/large-carrots-behave.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/impossible-migrate-beforeUpdate-afterUpdate/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-prop-and-$$props/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-prop-non-identifier/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-slot-change-name/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-slot-non-identifier/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-with-errors/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-with-errors/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-with-errors/output.svelte, packages/svelte/tests/migrate/samples/svelte-self-skip-filename/_config.js, packages/svelte/tests/migrate/test.ts
=> feat: don't print errors on migration errors

documentation/docs/07-misc/07-v5-migration-guide.md
Looks like an artifact from `$on` which is invalid here.
Also fix a typo.
=> docs: Remove copy pasted argument from `$set`.

.changeset/chatty-feet-unite.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/props-ts/input.svelte, packages/svelte/tests/migrate/samples/props-ts/output.svelte
=> fix: properly migrate ts with inferred type comments

.changeset/witty-flies-impress.md, documentation/docs/98-reference/.generated/client-warnings.md, packages/svelte/messages/client-warnings/warnings.md, packages/svelte/src/internal/client/warnings.js, packages/svelte/src/legacy/legacy-client.js, packages/svelte/tests/runtime-runes/samples/legacy-recursive-reactive-block/_config.js, packages/svelte/tests/runtime-runes/samples/legacy-recursive-reactive-block/main.svelte
As per discord discussion this add the name of the file the warning is generated from to `legacy_recursive_reactive_block`. The name is only available in dev but that's not a problem since the warning is only thrown in `DEV` anyway. If for some reason `FILENAME` should not be there i've used "a file (we can't know which one)" as a fallback (not sure about the parenthesis tbf).
Simon originally had the idea of passing the filename and position with via the ast but the run function is meant to be visible in the code so i think this approach is more than enough.
=> fix: show filename information in `legacy_recursive_reactive_block`

sites/svelte-5-preview/src/routes/docs/content/02-examples/04-old-vs-new.md
Not sure how long this fix to the preview site will be relevant now that Svelte 5 is out (congrats! 🎉) and we are moving to the new omnisite, but some REPL examples of the *new* syntaxes in the "Old vs new" page still has
```svelte
<button on:click={() => count++}>...</button>
```
in them despite diffed examples embedded in the doc itself already properly reflected the changes. The links are now updated to show
```svelte
<button onclick={() => count++}>...</button>
```
=> docs: use new Svelte 5 event handler syntax on preview site examples

.changeset/few-rocks-remain.md, packages/svelte/src/internal/client/dom/elements/transitions.js, packages/svelte/tests/runtime-runes/samples/effect-tracking-transition/_config.js, packages/svelte/tests/runtime-runes/samples/effect-tracking-transition/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13773. Similar to https://github.com/sveltejs/svelte/pull/13774, but targeting the source of the issue in this case
=> fix: ensure $effect.tracking returns false inside transition functions

.changeset/red-coats-grin.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/SvelteElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/element.js, packages/svelte/tests/runtime-runes/samples/dynamic-spread-and-attribute-directive/_config.js, packages/svelte/tests/runtime-runes/samples/dynamic-spread-and-attribute-directive/main.svelte
=> fix: prevent spread attribute from overriding class directive

documentation/docs/02-runes/05-$props.md, documentation/docs/03-template-syntax/07-@render.md, documentation/docs/06-runtime/02-context.md, documentation/docs/07-misc/03-typescript.md
I have a spell checker and I'm willing to use it.
=> docs: Fix various typos.

documentation/docs/07-misc/07-v5-migration-guide.md
Quick fix for Migration Guide adding the link to the tutorial. This also removes the visible "TODO LINK TO TUTORIAL" text from the page.
=> docs: fix TODO to add link to tutorial in migration guide

.changeset/afraid-turtles-invent.md, packages/svelte/src/index.d.ts, packages/svelte/src/internal/client/render.js, packages/svelte/types/index.d.ts
=> feat: Define the MountOptions type

CONTRIBUTING.md, README.md, documentation/docs/07-misc/99-faq.md, packages/svelte/README.md, sites/svelte-5-preview/src/routes/docs/content/02-examples/01-universal-reactivity.md
I arguably didn't have to update old blog post links, but it's better for SEO to have those links go directly instead of through a redirect
=> docs: update tutorial links

.changeset/dull-wolves-judge.md, packages/svelte/src/internal/client/dom/elements/transitions.js
Custom CSS properties are being renamed in Svelte 5 while used inside custom transitions. This was working fine in Svelte 4, and I just stumbled across an error in this code. The failure uncovered that these cases were not handled correctly.
Unrelated tests are failing on my machine (runtime-runes).
=> fix: broken property name derivation in keyframe generation

.changeset/beige-llamas-grab.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/internal/client/dom/elements/events.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/derived-get-context/Child.svelte, packages/svelte/tests/runtime-runes/samples/derived-get-context/_config.js, packages/svelte/tests/runtime-runes/samples/derived-get-context/main.svelte, packages/svelte/tests/runtime-runes/samples/event-handler-component-invalid-warning/_config.js, packages/svelte/tests/runtime-runes/samples/event-handler-invalid-warning/_config.js
Closes https://github.com/sveltejs/svelte/issues/13493.
This PR allows the usage of `getContext()` inside `$derived` runes. Previously, you could use it, but only on init and not updates – and this inconsistency was unnecessary. We can make it work just like we do in other places.
One interested thing came about from this change – a bunch of our existing tests broke because they incorrectly did not pass `is_runes` internally as the derived never had access to the `ctx` which contained if we're in runes or not, meaning that they were not working correctly – so I had to fix them too.
=> feat: allow usage of getContext() within $derived runes

documentation/docs/07-misc/07-v5-migration-guide.md
In the docs, I believe there may be a minor typo in the explanation of `$state` vs `let`. This removes the typo; if it's intentional wording, I can close this PR.
=> docs: clarifying wording in explanation of state rune in v5 migration guide

packages/svelte/src/index.d.ts, packages/svelte/types/index.d.ts
a few wording tweaks, and most importantly mark `events` as deprecated - we don't want to encourage its use.
=> chore: tweak MountOptions docs

documentation/docs/01-introduction/03-svelte-files.md
=> docs: note TS caveat about module exports

documentation/docs/07-misc/07-v5-migration-guide.md
I assume they were accidentally left there because they used to be separate lines each with their own `>` at the beginning of the line, but whoever collapsed them into one line forgot to remove the extra arrow.
Whatever the case is, this commit removes (probably) all of these leftover `>` symbols.
=> docs: Cleanup some leftover `>` symbols from the migration doc

documentation/docs/07-misc/07-v5-migration-guide.md
Currently, in the Svelte 5 Migration guide, under the `$props` migration, the example uses `class` as a variable name which it passes down to a button. However, the `class` variable is not declared and cannot be declared, so this PR changes the variable to access the one which actually exists.
=> docs: fix using reserved word in example

.changeset/little-hotels-poke.md, packages/svelte/src/store/utils.js, packages/svelte/tests/runtime-runes/samples/store-unsubscribe-not-referenced-after/main.svelte
Closes https://github.com/sveltejs/svelte/issues/13840. This issue keeps coming up time and time again. I think we can make the process of migration smoother by just internally wrapping the `subscribe` function in an `untrack` internally – which is what people would have had to have done in their functions anyway.
=> fix: internally wrap store subscribe in untrack

.changeset/short-jokes-speak.md, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/tests/runtime-runes/samples/props-assignment-tracking/_config.js, packages/svelte/tests/runtime-runes/samples/props-assignment-tracking/main.svelte
Closes https://github.com/sveltejs/svelte/issues/13813. We shouldn't be tracking `current_value` when doing sets to props, otherwise we oversubscribe.
=> fix: ensure props internally untracks current_value on sets

.changeset/nine-pigs-approve.md, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-legacy/samples/bind-export-const-with-spread/Test.svelte, packages/svelte/tests/runtime-legacy/samples/bind-export-const-with-spread/_config.js, packages/svelte/tests/runtime-legacy/samples/bind-export-const-with-spread/main.svelte
Closes #13844...initially i wanted to prevent binding when the binder was in legacy mode but this
```svelte
<script>
import A from "./A.svelte";
let x = $state();
</script>
<A
bind:x
/>
{x}
```
works and we can't change it without a breaking (svelte 6 wen?) so disallow this
```svelte
```svelte
<script>
import A from "./A.svelte";
let x = $state();
</script>
<A
bind:x
{...{}}
/>
{x}
```
seems weird.
=> fix: allow binding to const with spread in legacy mode

packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/SvelteElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/element.js, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/dom/elements/style.js, packages/svelte/src/internal/client/dom/operations.js
Some little improvement to `set_style()` in order to avoid the check to `style.getPropertyValue()`
See issue https://github.com/sveltejs/svelte/issues/13791
Demo here : [REPL](https://adiguba-svelte-5-test-git-improvesetstyle-adigubas-projects.vercel.app/#H4sIAAAAAAAACpVTy27bMBD8FYJtkQZNLSdoLiwtoP_QW9UDJa5kohRFkCvHhqB_Lx9yhDh2gV4kLXdmdpa7mmirNHjKfk3UiB4ooz-spQ8UTzYG_gAaIcR-GF0TT7hvnLJYVqZCDUiaQQ-O7MhHjwLh813nAMzd_fdz3oHHNT15PGlgFW0Hg19fQHV7ZKQetKzovJISamVVNFVh5EPbthWNOF6sPgzXogZdcm-FKXMFEgAx4srYEUlsZ1dRhCNWlNTKSHYQeoRdNjSTouRFVrmQi_43_6m5ct4KJ6-9UCbdHpfqkDtltWj-dG4YjQyCDsJlkGmz2USdOWEr_LlXnkRGeAXEA_lC1jJJrgjZfwrXwVxUzs6u6EZA0L0ieVt2SqOZb6vmA-5BQ4NvrikzF0aADBbVEG9c8mL5vsxFhzeTafUusmFkqfASXmmOF-eJxOmkdF7uODQyZZ5U3mpxYqTVcExrOq-YksS1OENflMQ9I8_Qv8flxVmAvXCdMox8s0eyTc_HhfMq8rjdflpVos93hjqn5ELq …
=> feat: Little improvement to set_style()

.changeset/hungry-dogs-happen.md, packages/svelte/src/reactivity/map.js, packages/svelte/tests/runtime-runes/samples/derived-map/_config.js, packages/svelte/tests/runtime-runes/samples/derived-map/main.svelte
Closes https://github.com/sveltejs/svelte/issues/13817. Quite an edge-case but one we need to support. When using a SvelteMap inside a reactive context such as a derived for the first time, registering of dependencies that get "upgraded" from a version to a property source might get missed as the context hasn't yet been registered to the sources. To avoid this, we can further increment the version when a further set is applied to a SvelteMap property signal, and where that signal hasn't yet been wired up. The increment to version will ensure on stale references get hooked up accordingly.
=> fix: ensure SvelteMap reactivity persists through deriveds

packages/svelte/src/reactivity/date.test.ts
The test for `SvelteDate` fail on some timezone, like mine (CEDT/CEST "France/Paris").
=> This is because the initial date is set to midnight, and the Date/UTCDate may differ based on the user timezone.
I changed the test in order to redo the same calculations with Date.
I think this should work on all timezone.
=> fix: date test fail for some timezone

.changeset/cool-clocks-march.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/reactivity/store.js, packages/svelte/src/internal/client/validate.js, packages/svelte/tests/runtime-runes/samples/bound-store-sub/Child.svelte, packages/svelte/tests/runtime-runes/samples/bound-store-sub/_config.js, packages/svelte/tests/runtime-runes/samples/bound-store-sub/main.svelte
Closes https://github.com/sveltejs/svelte/issues/13825.
This is an interesting one.
1. In legacy mode, we allow bound stores to persist and have their properties update – however, you get a warning that you're writing to a non-reactive property when doing so – this removes that warning as things work fine.
2. In runes mode, we allow bound store subs to work like they do in legacy mode. We do this by marking the bound store sub inside the prop getter and then capturing this and using this logic to apply the different heuristics.
=> fix: enable bound store props in runes mode components

.changeset/plenty-plums-sparkle.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/internal/client/dom/operations.js, packages/svelte/tests/runtime-runes/samples/snippet-after-text/Child.svelte, packages/svelte/tests/runtime-runes/samples/snippet-after-text/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-after-text/main.svelte, packages/svelte/tests/snapshot/samples/skip-static-subtree/_expected/client/index.svelte.js
Fixes https://github.com/sveltejs/svelte/issues/13852. We needed to pass through `is_text` like we do in other traversal operations for hydration to properly capture the empty text node.
=> fix: ensure snippets after empty text correctly hydrate

packages/svelte/src/internal/client/dom/elements/transitions.js
Fix https://github.com/sveltejs/svelte/issues/13681
On some rare case when a out transition is quickly canceled, the "dummy transition" `onfinish` can be executed after the cancel, and the node will be removed from the DOM.
It seems that setting onfinish back to `noop` fixes the problem.
However the bug is not systematic (the joys of race conditions), and I can't come up with a proper test for this.
=> fix : Rapidly toggling element with out: transition causes incorrect node removal

.changeset/smooth-dragons-push.md, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/tests/runtime-runes/samples/event-without-params-clash/_config.js, packages/svelte/tests/runtime-runes/samples/event-without-params-clash/main.svelte
Closes #13872 (it also prevent from logging `_` which is good.
=> fix: prevent var name clashing for delegated events without params

.changeset/shaggy-seals-judge.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/not-prepend-props-to-export-let/input.svelte, packages/svelte/tests/migrate/samples/not-prepend-props-to-export-let/output.svelte
=> fix: prevent migration script from adding `props.` to the `export let` identifier

documentation/docs/06-runtime/02-context.md
=> docs: fix typo where setContext should be getContext

.changeset/strong-buttons-juggle.md, packages/svelte/src/action/public.d.ts, packages/svelte/types/index.d.ts
Fix a typo
Unsure of if this doc is generated here or in the svelte types file.
=> fix: typo in `Action` types

documentation/docs/02-runes/03-$derived.md
In the v4 docs it was clearly explained why we need to use `$:` to re-evaluate assignments, this is missing for the `$derived` rune and could be a pitfall for people new to the framework.
Note: should be fixed in the tutorial as well.
=> docs: clarify why we need to use the derived rune

.changeset/gentle-bulldogs-cough.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/SvelteElement.js, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/svg-attribute-case/_config.js, packages/svelte/tests/runtime-runes/samples/svg-attribute-case/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13878
=> fix: ensure SVG element attributes have case preserved

.changeset/strong-dogs-obey.md, packages/svelte/src/compiler/legacy.js
Besides being private API that shouldn't be exposed, they caused our AST explorer on the Svelte site to traverse endlessly
fixes https://github.com/sveltejs/svelte.dev/issues/480
=> fix: remove metadata from legacy AST

.changeset/blue-boats-call.md, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/tests/runtime-runes/samples/await-no-catch-error/_config.js, packages/svelte/tests/runtime-runes/samples/await-no-catch-error/main.svelte
Closes https://github.com/sveltejs/svelte/issues/13817
=> fix: rethrow errors from await block if no catch block exists

.changeset/giant-bags-wash.md, packages/svelte/src/internal/client/dom/elements/bindings/input.js, packages/svelte/tests/runtime-runes/samples/state-bind-group/_config.js, packages/svelte/tests/runtime-runes/samples/state-bind-group/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13894. We forgot to remove this logic when we made proxies no longer mutate the backing object.
=> fix: ensure bind:group works as intended with proxied state objects

.changeset/late-wombats-cheer.md, packages/svelte/src/internal/client/dom/elements/attributes.js
Fixes https://github.com/sveltejs/svelte/issues/13686. JSDOM didn't report any difference, so wasn't sure how to test this nicely.
=> fix: ensure value is correctly set to zero on the progress element

.changeset/shy-penguins-beg.md, packages/svelte/src/compiler/phases/2-analyze/visitors/SnippetBlock.js, packages/svelte/tests/runtime-runes/samples/snippet-comment-sibling/Child.svelte, packages/svelte/tests/runtime-runes/samples/snippet-comment-sibling/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-comment-sibling/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13865. We forgot to skip comment nodes in the validation logic.
=> fix: skip comment nodes in snippet validation logic

.changeset/brave-fans-sneeze.md, packages/svelte/src/compiler/utils/compile_diagnostic.js, packages/svelte/tests/migrate/samples/impossible-migrate-with-errors/_config.js, packages/svelte/types/index.d.ts
As discussed in #13937 i'm adding an empty stack trace to the error to show the frame and info on the error if the build fails.
=> fix: add empty stack to `CompileDiagnostic` to show error on build

.changeset/tasty-frogs-boil.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/remove-blocks-whitespace/input.svelte, packages/svelte/tests/migrate/samples/remove-blocks-whitespace/output.svelte
This kinda closes #13933...since now having no whitespace before the blocks is enforced by svelte let's trim everything while migrating.
Edit this will also close #13483 (we can't really fix the inconsistencies without a breaking change unfortunately)
=> fix: trim whitespace while migrating blocks

documentation/docs/07-misc/07-v5-migration-guide.md
Make the casing of the word ‘DOM’ in the Svelte 5 migration guide consistent.
#13957
=> docs: consistently capitalize `DOM` in the Svelte 5 migration guide (#13957)

.changeset/sweet-candles-poke.md, packages/svelte/src/reactivity/map.js, packages/svelte/tests/runtime-runes/samples/derived-map/_config.js, packages/svelte/tests/runtime-runes/samples/derived-map/main.svelte
Closes #13947 ...i'm not sure this is the right fix and i'm not sure of the performance implications. The problem is that basically just checking for null and !null is not enough. In this case both have a reaction because of the second variable read but not every reaction in `s` are in `version`.
This seems to fix the issue and tests are green but i have the feeling this could overfire the increase of version.
=> fix: more exhaustive check during `SvelteMap.set` in deriveds

documentation/docs/06-runtime/03-lifecycle-hooks.md
`beforeUpdate` is deprecated so we should use `$effect.pre` instead in the `tick` example.
=> docs: use `$effect.pre` instead of `beforeUpdate`

documentation/docs/03-template-syntax/01-basic-markup.md, documentation/docs/98-reference/.generated/client-errors.md, documentation/docs/98-reference/.generated/client-warnings.md, packages/svelte/messages/client-errors/errors.md, packages/svelte/messages/client-warnings/warnings.md, packages/svelte/src/internal/client/errors.js
Update (some) of the links pointing to the old preview site as mentioned in #13982.
This updates all the links in `documentation/` and `packages/svelte/messages`, but doesn't touch others present in `packages/svelte/` or fix the original link in that issue.
I didn't add a changeset as it was only docs. But, if the error messages have changed, would that need a changeset?
=> docs: update links to point to new site

documentation/docs/01-introduction/02-getting-started.md
looks a little weird having an `<h3>` before the first `<h2>`, and there's no particular reason the hierarchy needs to be this way
=> docs: update 02-getting-started.md

.changeset/clean-badgers-battle.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/store/index-client.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-10/_config.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-10/main.svelte, packages/svelte/tests/runtime-runes/samples/derived-unowned-10/theme.svelte.js
Fixes https://github.com/sveltejs/svelte/issues/14002. In `effect_tracking` we shouldn't be tracking if the derived is purely unowned – because even unowned deriveds can be reactive if they're used in another reactive context – thus `$effect.tracking()` should return `true` in those cases.
=> fix: ensure effect_tracking correctly handles tracking reactions

.changeset/soft-snails-retire.md, packages/svelte/src/index-client.js, packages/svelte/types/index.d.ts
my quest to redirect our docs to the new format never ends...
=> docs: fix broken links

.changeset/tiny-boxes-exist.md, packages/svelte/src/ambient.d.ts, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/src/index-client.js, packages/svelte/src/index.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/types/index.d.ts
closes https://github.com/sveltejs/svelte/issues/13982
I just deleted the link for `untrack` because I couldn't find someplace new to point it. It seems we don't have an example of using it. Perhaps someone can add an example inline later or something
=> chore: update links to preview site

packages/svelte/src/internal/client/timing.js
closes https://github.com/sveltejs/svelte/issues/13961
allows testing some browser code without jsdom
performance-wise these are equivalent because rollup will replace `BROWSER` and evaluate the ternary at compilation time
=> fix: don't access requestAnimationFrame eagerly

.changeset/eighty-pianos-sip.md, packages/svelte/src/store/index-client.js, packages/svelte/tests/store/test.ts
Only count down after timeout, else we would reach 0 before our own render effect reruns, but reach 1 again when the tick callback of the prior teardown runs. That would mean we re-subcribe unnecessarily and create a memory leak because the old subscription is never cleaned up.
=> fix: more robust re-subscribe detection for `fromStore`

.changeset/red-berries-watch.md, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/server-side-rendering/samples/css-injected-options-nested/Nested.svelte, packages/svelte/tests/server-side-rendering/samples/css-injected-options-nested/_expected.html, packages/svelte/tests/server-side-rendering/samples/css-injected-options-nested/_expected_head.html, packages/svelte/tests/server-side-rendering/samples/css-injected-options/_expected_head.html, packages/svelte/tests/server-side-rendering/samples/css/_expected_head.html
When CSS is externalized we rightfully rely on the following tooling chain to properly minify CSS. When we inject the CSS however, that tooling won't be able to do that, so we gotta do it ourselves. This PR brings back most of that logic that existed in Svelte 4. Fixes #13716
=> fix: minify injected CSS in prod mode

.changeset/shaggy-frogs-fetch.md, packages/svelte/src/store/index-client.js, packages/svelte/tests/runtime-runes/samples/toStore-subscribe/_config.js, packages/svelte/tests/runtime-runes/samples/toStore-subscribe/main.svelte
Closes https://github.com/sveltejs/svelte/issues/14010. Whilst reading the store value with a `console.log` isn't guaranteed to be the latest value (as stores are subscriptions and effects run on microtasks) the template should definitely eventually get in sync, and from the example, it doesn't on initial render. This PR fixes that by checking if intermittent value changes during subscription.
=> fix: ensure toStore subscription correctly syncs latest value

packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/server-side-rendering/samples/css-injected-options-minify/_config.js, packages/svelte/tests/server-side-rendering/samples/css-injected-options-minify/_expected.html, packages/svelte/tests/server-side-rendering/samples/css-injected-options-minify/_expected_head.html, packages/svelte/tests/server-side-rendering/samples/css-injected-options-minify/main.svelte, packages/svelte/tests/server-side-rendering/samples/css-injected-options-nested/Nested.svelte, packages/svelte/tests/server-side-rendering/samples/css-injected-options-nested/_expected.html, packages/svelte/tests/server-side-rendering/samples/css-injected-options-nested/_expected_head.html
immediately after merging #14006 I noticed there's a bug when pruning one selector in a list of several; this fixes it
no changeset because not released yet
=> fix: ensure comma is also pruned if necessary

documentation/docs/01-introduction/02-getting-started.md, documentation/docs/01-introduction/03-svelte-files.md, documentation/docs/02-runes/03-$derived.md, documentation/docs/02-runes/04-$effect.md, documentation/docs/03-template-syntax/05-await.md, documentation/docs/03-template-syntax/06-snippet.md, documentation/docs/03-template-syntax/15-animate.md, documentation/docs/04-styling/04-nested-style-elements.md, documentation/docs/06-runtime/01-stores.md, documentation/docs/06-runtime/03-lifecycle-hooks.md
This fixes some typos introduced in #13919 and adds a few words clarifying _when_ it is that `doubled` would otherwise remain unchanged.
=> docs: fix various typos in reference docs

.changeset/thin-icons-sort.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/BindDirective.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/UseDirective.js, packages/svelte/tests/runtime-legacy/samples/deconflict-contextual-action/_config.js, packages/svelte/tests/runtime-runes/samples/lifecycle-render-order-for-children-6/_config.js, packages/svelte/tests/runtime-runes/samples/lifecycle-render-order-for-children-6/main.svelte
This PR changes the ordering of event handlers, bindings and actions so they're now created in order of usage – which means that they fall in line with the logic and control-flow ordering too.
=> fix: ensure element effects are executed in the correct order

.changeset/khaki-carrots-mix.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-legacy/samples/props-reactive-destroy/Child.svelte, packages/svelte/tests/runtime-legacy/samples/props-reactive-destroy/_config.js, packages/svelte/tests/runtime-legacy/samples/props-reactive-destroy/main.svelte, packages/svelte/tests/runtime-runes/samples/props-reactive-destroy/Child.svelte, packages/svelte/tests/runtime-runes/samples/props-reactive-destroy/_config.js, packages/svelte/tests/runtime-runes/samples/props-reactive-destroy/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14025. We should be destroying child effects before deriveds, it was obviously on reflection now. Also means we can undo the changes in https://github.com/sveltejs/svelte/pull/13611!
=> fix: ensure child effects are destroyed before their deriveds

packages/svelte/src/compiler/phases/3-transform/client/visitors/BindDirective.js
spotted here: https://github.com/sveltejs/svelte/pull/14038#pullrequestreview-2405700437
also changes to use the same variable name as is used elsewhere for this purpose
=> chore: remove unnecessary ternary

.changeset/wild-parents-begin.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-browser/custom-elements-samples/element-effect-context/_config.js, packages/svelte/tests/runtime-browser/custom-elements-samples/element-effect-context/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13848.
When we set custom element attributes/props, we should be doing so without the current effect/reaction active. Otherwise, the custom element lifecycle might attach effects/dependencies to the wrong reaction and all manner of things can incorrectly occur. I tried to create a test for this using our Playwright testing but I couldn't get it to load up multiple custom elements so I gave up.
=> fix: ensure custom element attribute/prop changes are in their own context

.github/workflows/sync-request.yml
this means that merges to `main` will trigger docs PRs on svelte.dev
=> chore: add sync request workflow

documentation/docs/03-template-syntax/14-in-and-out.md
This is my first PR in the docs. I'd like to contribute more, so please be easy on me. I noticed the [in and out](https://svelte.dev/docs/svelte/in-and-out) docs wouldn't work without the correct import from transition. This will make it a bit obvious.
=> docs: Update in and out docs to show the imports

documentation/docs/02-runes/07-$inspect.md
The information note that `$inspect` works only in dev should deserve higher priority and be present in a quick skim of the documentation, not possible if placed at the end.
=> docs: note of `$inspect` being dev only moved to top position

documentation/docs/03-template-syntax/14-in-and-out.md
Without a `y` value, `fly` is indistinguishable from `fade`
=> add parameters to `in:fly`

documentation/docs/03-template-syntax/05-await.md
Closes #13990
Adds a example of dynamic component usage with the help of {#await...} syntax
=> docs : add an example of using dynamic components

.changeset/sour-feet-carry.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/is-not-where-has/input.svelte, packages/svelte/tests/migrate/samples/is-not-where-has/output.svelte
Closes #13765...if you can think of more weird case to test please let me know.
EDIT: i've added a slightly better test and realised that we could have a problem if the user has something like this
```svelte
{`
<style>
.this :is(a .problem){}
</style>
`}
```
in the template...should we care?
Also weirdly `replaceAll` from `MagicString` did not got the job done, might be worth opening an issue there.
=> fix: wrap `:id`, `:where``:not` and `:has` with `:global` during migration

.changeset/rotten-cups-float.md, packages/svelte/src/index.d.ts, packages/svelte/tests/types/component.ts, packages/svelte/types/index.d.ts
With the type change for `bind:this` on components (related issues are [this language-tools issue](https://github.com/sveltejs/language-tools/issues/2522) and [13430](https://github.com/sveltejs/svelte/issues/13430)).
Recommended way is to do this (per [this](https://github.com/sveltejs/language-tools/issues/2522#issuecomment-2380048973) comment):
> ```diff
> <script lang="ts">
>     import CloneWorkflowDialog from './dialogs/CloneWorkflowDialog.svelte';
> 
> -   let cloneWorkflowDialog : CloneWorkflowDialog;
> +   let cloneWorkflowDialog : ReturnType<typeof CloneWorkflowDialog>;
> </script>
> ```
Since we currently have the `Component` type exported by svelte that has the `Exports` we can rely on that and do this instead:
```diff
import CloneWorkflowDialog from …
```
=> feat: add `ComponentExports` utility type

documentation/docs/07-misc/07-v5-migration-guide.md
```diff
-<footer>
-  ---<slot name="header" />---
-  +++{@render footer()}+++
-</footer>
+<footer>
+  ---<slot name="footer" />---
+  +++{@render footer()}+++
+</footer>
```
this slot name should be `footer` instead it was `header`
=> docs: typo `footer` instead it was `header`

.changeset/curvy-melons-knock.md, packages/svelte/src/compiler/validate-options.js
=> fix: allow `warningFilter` option for `compileModule`

documentation/docs/03-template-syntax/05-await.md
The language added in #13993 is a little confusing:
- it's not a 'dynamic component', it's just a component
- `import()` isn't a function, it's a function-like expression
- the result of calling it is a module, not a component
=> docs: improve lazy import example

documentation/docs/02-runes/05-$props.md
The docs added in #13994 are helpful but also somewhat misleading: the message should be a loud and clear 'don't mutate props' followed by details and examples, rather than an illustration of mutating a prop that _does_ work but without mentioning the warning that happens when you do.
There were also some errors in the code snippets, which is really a consequence of a) the fact that we have to manually keep snippets and playground links in sync, and b) the fact that we don't have typechecking of `.svelte` snippets (which would have caught the `object = { count = 0 }` syntax error, for example). We should fix both of those.
=> docs: fix docs on mutating props

documentation/docs/98-reference/30-runtime-warnings.md
this was importing the wrong stuff
=> docs: fix runtime-warnings page

documentation/docs/02-runes/03-$derived.md, documentation/docs/02-runes/04-$effect.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/types/index.d.ts
alternative to #14060. In general we should put documentation on the functions themselves — that way there's a single source that populates everything. 
It's also good to use realistic motivating examples where possible — in particular it's good to avoid `console.log` in examples of effects, since it's better to use `$inspect` (particularly when dealing with state proxies).
=> docs: tweak untrack description, provide an example of usage

.changeset/warm-eyes-protect.md, documentation/docs/07-misc/04-custom-elements.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/tests/runtime-browser/custom-elements-samples/props-rune-attributes/_config.js, packages/svelte/tests/runtime-browser/custom-elements-samples/props-rune-attributes/main.svelte, packages/svelte/tests/runtime-browser/custom-elements-samples/props-rune-attributes/my-widget.svelte
We didn't account for the `$props` rune being writtin in a way that makes some props unknown, and they would only be visible through the `customElement.props` definition. This changes the iteration to account for that and also adds a note to the documentation that you need to list out the properties explicitly.
fixes #13785
=> fix: recognize all custom element prop definitions

.changeset/empty-hairs-love.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js
Fixes https://github.com/sveltejs/svelte/issues/14087. It's safari specific, so I'm unable to create a unit test for this.
=> fix: ensure video elements autoplay in safari

documentation/docs/03-template-syntax/11-bind.md, documentation/docs/03-template-syntax/13-transition.md, documentation/docs/99-legacy/02-legacy-reactive-assignments.md, documentation/docs/99-legacy/40-legacy-component-api.md, packages/svelte/src/ambient.d.ts, packages/svelte/tests/runtime-legacy/samples/dynamic-element-store/main.svelte, packages/svelte/types/index.d.ts
These have snuck in in various places over the years.
This doesn't touch the blog posts, whose canonical home is now the svelte.dev repo, and which are pending removal in this repo in #13818.
=> chore: replace non-breaking spaces

.changeset/selfish-chicken-argue.md, packages/svelte/src/reactivity/map.js, packages/svelte/src/reactivity/set.js, packages/svelte/tests/runtime-runes/samples/svelte-set-generators/_config.js, packages/svelte/tests/runtime-runes/samples/svelte-set-generators/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14094. Turns out that passing the value to a Set/Map in DEV causes the generator to close and yield before we get a chance to iterate over it. So if we do the logic in DEV to create a Set/Map from the value then we should probably use that instead to iterate over.
=> fix: ensure SvelteMap and SvelteSet work with generators in dev

documentation/docs/07-misc/02-testing.md
The browser condition is also necessary to test runes, so it makes sense to add it to the first occurence to the vite config. Also add a note about more fine-grained alias conditions.
Closes #13961
=> docs: note browser condition earlier

documentation/docs/02-runes/04-$effect.md
It seems #12200 is back again after the site migration, maybe it is worth checking if previous docs fixes exist or not. 
closes #13912
=> docs: fix `$effect` section examples

packages/svelte/src/compiler/types/index.d.ts, packages/svelte/types/index.d.ts
Since Svelte 5, comments are also preserved on the client
Noticed this while closing #6805
=> docs: fix description

.changeset/yellow-pumas-rule.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/export-props-multiple-declarations/input.svelte, packages/svelte/tests/migrate/samples/export-props-multiple-declarations/output.svelte
=> fix: migrate multiple declarations with only some exported correctly

.changeset/modern-pets-punch.md, packages/svelte/src/compiler/phases/2-analyze/types.d.ts, packages/svelte/src/compiler/phases/2-analyze/visitors/RegularElement.js, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/component.js, packages/svelte/tests/runtime-runes/samples/html-namespace-infer-a-tag/_config.js, packages/svelte/tests/runtime-runes/samples/html-namespace-infer-a-tag/div.svelte, packages/svelte/tests/runtime-runes/samples/html-namespace-infer-a-tag/main.svelte, packages/svelte/tests/runtime-runes/samples/svg-namespace-infer-a-tag/_config.js, packages/svelte/tests/runtime-runes/samples/svg-namespace-infer-a-tag/main.svelte, packages/svelte/tests/runtime-runes/samples/svg-namespace-infer-a-tag/svg.svelte
`<a>` tags are valid in both the SVG and HTML namespace.  If there's no parent, we therefore have to look downwards to see if it's the parent of a SVG or HTML element.
fixes #7807
fixes #13793
=> fix: correctly infer `<a>` tag namespace

documentation/docs/05-special-elements/05-svelte-element.md
=> docs: note what the value of `this` can be on `svelte:element`

.github/workflows/docs-preview-create-request.yml, .github/workflows/docs-preview-delete-request.yml
This should allow preview deployments to be created for PRs from external contributors
=> chore: use `pull_request_target` instead of `pull_request` event in workflows

documentation/docs/03-template-syntax/11-bind.md
Since the note from the tutorial is missing from the actual docs, i put the same note into the docs as well. 
Original note: https://svelte.dev/tutorial/svelte/dimensions
=> Add same note as in tutorial to documentation for "Dimension bindings"

.changeset/short-lions-search.md, packages/svelte/src/internal/client/validate.js
=> fix: only output the key for each_key_duplicate

.changeset/mean-seas-give.md, .changeset/purple-owls-hug.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/jsdoc-with-comments/input.svelte, packages/svelte/tests/migrate/samples/jsdoc-with-comments/output.svelte, packages/svelte/tests/migrate/samples/props-ts/input.svelte, packages/svelte/tests/migrate/samples/props-ts/output.svelte
Fixes #14140
Keeps inline comments when migrating types, as we already do with other statement types [L783](https://github.com/sveltejs/svelte/blob/551284ca2259d934d34b71a38071d85684bd6d4f/packages/svelte/src/compiler/migrate/index.js#L783C1-L783C43)
```ts
export let step: number | null = null // In-line comments are now kept
```
```ts
interface Props {
step: number | null; // In-line comments are now kept
}
```
Added tests for Typescript and JSDoc migration. In the latter, the comments are merged with leading comments. See `tests/migrate/jsdoc-with-comments/output.svelte`
=> fix: ensure migrate keeps inline/trailing comments in $props type definition and produces non-broken code

documentation/docs/07-misc/07-v5-migration-guide.md
=> docs: fix migration guide typo

.github/workflows/pkg.pr.new-comment.yml, .github/workflows/pkg.pr.new.yml
After we merge https://github.com/sveltejs/svelte.dev/pull/745 it could be cool to have the link to the playground directly in the comment.
This is following pkg.pr.new recommendation to add a custom comment with some modification on my part to make it more useful for us. I'm not entirely sure what would happen on merge but i guess we can always iterate.
=> chore: add custom comment with link to playground for `pkg.pr.new`

.changeset/rotten-toys-fix.md, packages/svelte/src/transition/index.js, packages/svelte/types/index.d.ts
part of https://github.com/sveltejs/svelte.dev/pull/791. Will expedite a release once green
=> fix: update links in JSDoc

.changeset/four-countries-taste.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte, packages/svelte/tests/validator/samples/ts-unsupported-modifier-readonly/errors.json, packages/svelte/tests/validator/samples/ts-unsupported-modifier-readonly/input.svelte
This PR fixes #14152 where an implicit public access modifier on a constructor parameter prevents the Svelte runtime from correctly generating the class. When the class is instantiated, attempting to log or display the property results in undefined instead of the expected value.
=> fix: issue with implicit public modifier causing undefined properties

.changeset/quick-eels-occur.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/css/samples/not-selector-global/_config.js, packages/svelte/tests/css/samples/not-selector-global/expected.css, packages/svelte/tests/css/samples/not-selector-global/expected.html, packages/svelte/tests/css/samples/not-selector-global/input.svelte, packages/svelte/tests/css/samples/not-selector-hash-on-right-elements/_config.js, packages/svelte/tests/css/samples/not-selector-hash-on-right-elements/expected.css, packages/svelte/tests/css/samples/not-selector-hash-on-right-elements/expected.html, packages/svelte/tests/css/samples/not-selector-hash-on-right-elements/input.svelte, packages/svelte/tests/css/samples/not-selector/_config.js, packages/svelte/tests/css/samples/not-selector/expected.css, packages/svelte/tests/css/samples/not-selector/expected.html, packages/svelte/tests/css/samples/not-selector/input.svelte, packages/svelte/tests/css/test.ts, packages/svelte/tests/migrate/samples/is-not-where-has/output.svelte
fixes https://github.com/sveltejs/svelte/issues/14168
This mostly reverts the whole "selectors inside `:not` are scoped" logic. Scoping is done so that styles don't bleed. But within `:not`,everything is reversed, which means scoping the selectors now means they are more likely to bleed. That is the opposite of what we want to achieve, therefore we should just leave those selectors alone.
The exception are `:not` selectors with descendant selectors, as that means "look up the tree" and we need to scope all ancestor elements in that case.
=> fix: remove scoping for most `:not` selectors 

documentation/docs/07-misc/03-typescript.md
Users are sometimes confused when they can't find `HTMLDivAttributes` because it simply doesn't exist. This PR lets users know where to find the other types.
related discord help thread https://discord.com/channels/457912077277855764/1303330319423897600
=> docs: `SvelteHTMLElements` can be used for creating component wrapper

.changeset/pink-doors-chew.md, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/tests/runtime-runes/samples/await-render-error-restore-reaction/_config.js, packages/svelte/tests/runtime-runes/samples/await-render-error-restore-reaction/main.svelte
=> fix: restore active reaction if then block throws

.changeset/four-jobs-care.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/has/_config.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/has/input.svelte
We didn't collect sibling elements of a given element to then check the `:has` selectors. This adds the logic for that. Fixes #14072
=> fix: handle sibling combinators within `:has`

.changeset/chatty-gorillas-poke.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/impossible-migrate-$bindable-bindable-var-1/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$bindable-bindable-var-1/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$bindable-bindable-var-1/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-1/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-1/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-1/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-2/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-2/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-2/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-3/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-3/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-3/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-4/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-4/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-4/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$props-props-var-1/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$props-props-var-1/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$props-props-var-1/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-1/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-1/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-1/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-2/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-2/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-2/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-3/_config.js, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-3/input.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-$state-state-var-3/output.svelte
Closes #14215
As usual with the migration script you start simple and then you realise new edge cases. This started simply with a `state` variable erroring when migrating to `$state`. Then i realised the same could be true for `$derived` and `$props` and `$bindable`.
There are some false negative here: technically this is migratable
```svelte
<script>
export let props;
</script>
```
because
```svelte
<script>
let { props } = $props();
</script>
```
is valid but while with props is probably fine trying to migrate when the binding is in the expression that we are migrating is a lot more complex for `derived` for example (because we create some new derived in some cases and we don't have a node for that. But i would say this is still good enough and better have some false negative for an …
=> fix: add migration task when there's a variable named that would conflict with a rune

.changeset/seven-clocks-pull.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/slot-use_ts-2/_config.js, packages/svelte/tests/migrate/samples/slot-use_ts-2/input.svelte, packages/svelte/tests/migrate/samples/slot-use_ts-2/output.svelte, packages/svelte/tests/migrate/samples/slot-use_ts-3/_config.js, packages/svelte/tests/migrate/samples/slot-use_ts-3/input.svelte, packages/svelte/tests/migrate/samples/slot-use_ts-3/output.svelte, packages/svelte/tests/migrate/samples/slot-use_ts/output.svelte
=> fix: add `lang="ts"` attribute during migration if needed

.changeset/lazy-chefs-float.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/shadowed-forwarded-slot/input.svelte, packages/svelte/tests/migrate/samples/shadowed-forwarded-slot/output.svelte
=> fix: account for shadowing children slot during migration

documentation/docs/03-template-syntax/06-snippet.md
Added a missing slash to a component closing tag
=> docs: Svelte code typo Update 06-snippet.md

.changeset/nice-chicken-wonder.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/fragment.js, packages/svelte/tests/runtime-runes/samples/img-loading-lazy-no-static/_config.js, packages/svelte/tests/runtime-runes/samples/img-loading-lazy-no-static/main.svelte
=> fix: consider img with loading attribute not static

.changeset/bright-papayas-sneeze.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/tests/runtime-runes/samples/reassigned-store-not-state/_config.js, packages/svelte/tests/runtime-runes/samples/reassigned-store-not-state/main.svelte
Closes #14233
The fix was slightly more involved because at that state we still can't have full certainty if we are in rune mode because we are still modifying the module scope.
=> fix: do not treat reassigned synthetic binds as state in runes mode

.changeset/mighty-ads-appear.md, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/fragment.js, packages/svelte/tests/snapshot/samples/inline-module-vars/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/_expected/server/index.svelte.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/index.svelte
Closes #14241
cc. @benmccann if you want to try the output in the playground
=> fix: consider static attributes that are inlined in the template

.changeset/hot-ladybugs-clap.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/is-not-where-has/input.svelte, packages/svelte/tests/migrate/samples/is-not-where-has/output.svelte
Adds a "are we inside a `:global`" check
fixes #14088
=> fix: don't wrap pseudo classes inside `:global(...)` with another `:global(...)`

.changeset/mean-worms-fetch.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/slot-non-identifier/input.svelte, packages/svelte/tests/migrate/samples/slot-non-identifier/output.svelte
Fixes named slots with a reserved keyword not working anymore after migration. Re-uses the `@migration-task` logic for invalid identifiers.
Fixes #14277
=> fix(migration): named slots with reserved keywords

packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/runtime.js
Not sure why we need the extra variable. We can also simplify it a bit without needing it.
=> chore: simplify signal capturing logic

.changeset/hot-frogs-melt.md, packages/svelte/src/internal/client/dom/blocks/key.js, packages/svelte/src/internal/client/reactivity/equality.js, packages/svelte/tests/runtime-runes/samples/key-unchanged-value/_config.js, packages/svelte/tests/runtime-runes/samples/key-unchanged-value/main.svelte
=> fix: use strict equality for key block comparisons in runes mode

.changeset/beige-files-pull.md, .changeset/great-bulldogs-wonder.md, packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/src/compiler/phases/2-analyze/css/css-warn.js, packages/svelte/src/compiler/phases/2-analyze/css/utils.js, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/src/compiler/types/css.d.ts, packages/svelte/tests/css/samples/has/_config.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/has/input.svelte, packages/svelte/tests/css/samples/is/_config.js, packages/svelte/tests/css/samples/is/expected.css, packages/svelte/tests/css/samples/is/input.svelte, packages/svelte/tests/css/samples/not-selector-global/expected.css, packages/svelte/tests/css/samples/not-selector-global/input.svelte, packages/svelte/tests/css/samples/root/_config.js, packages/svelte/tests/css/samples/root/expected.css, packages/svelte/tests/css/samples/root/expected.html, packages/svelte/tests/css/samples/root/input.svelte
We previously marked all `:root` selectors as global-like, which excempted them from further analysis. This causes problems:
- things like `:not(...)` are never visited and therefore never marked as used -> we gotta do that directly when coming across this
- `:has(...)` was never visited, too. Just marking it as used is not enough though, because we might need to scope its contents
Therefore the logic is enhanced to account for these special cases. Fixes #14118
While fixing this I cleaned up some inconsistencies in what we mark as global. This simplified code and fixed some adjacent bugs, which conindicentally also fixes #14189
=> fix: account for `:has(...)` as part of `:root`

.changeset/shaggy-flowers-kneel.md, packages/svelte/package.json, packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/ExportNamedDeclaration.js, packages/svelte/src/compiler/phases/2-analyze/visitors/ExportSpecifier.js, packages/svelte/src/compiler/phases/2-analyze/visitors/ImportDeclaration.js, packages/svelte/src/compiler/utils/ast.js, packages/svelte/src/compiler/utils/builders.js, pnpm-lock.yaml
=> fix: bump `is-reference` dependency to fix `import.meta` bug

.changeset/fast-ligers-repeat.md, documentation/docs/98-reference/.generated/compile-errors.md, packages/svelte/messages/compile-errors/template.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteDocument.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteWindow.js, packages/svelte/tests/validator/samples/illegal_spread_element-document/errors.json, packages/svelte/tests/validator/samples/illegal_spread_element-document/input.svelte, packages/svelte/tests/validator/samples/illegal_spread_element-window/errors.json, packages/svelte/tests/validator/samples/illegal_spread_element-window/input.svelte
Seems like we missed this validation for these special Svelte elements, but have it on the others.
=> fix: disallow invalid attributes for `<svelte:window>` and `<svelte:document>`

.changeset/fresh-pigs-divide.md, packages/svelte/src/internal/client/constants.js, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/validate.js, packages/svelte/src/legacy/legacy-client.js, packages/svelte/tests/runtime-runes/samples/mount-props-updates/_config.js, packages/svelte/tests/runtime-runes/samples/mount-props-updates/component.svelte, packages/svelte/tests/runtime-runes/samples/mount-props-updates/main.svelte
The detection whether or not props are writable is buggy; it doesn't take into account the case when instantiating components via `mount` or legacy-`new`
Fixes #14161
This posed an interesting question: What to do about (non-)`bind:`able properties? The answer I arrived on was: Treat it as if everything that _can_ be bound _is_ treated as bound, and everything else as readonly. In other words, if you're reassigning a prop, it will diverge from the passed in props if it's not bindable or not set in the parent, otherwise it will mutate the passed in props. I think that makes the most sense, given that you can't control this behavior from the outside.
=> fix: ensure props passed to components via mount are updateable

.changeset/chatty-singers-sin.md, packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/not-selector/expected.css, packages/svelte/tests/css/samples/not-selector/input.svelte
fixes the css bug part of #14299
=> fix: mark pseudo classes nested inside `:not` as used

.changeset/strange-adults-visit.md, packages/svelte/src/compiler/validate-options.js
=> fix: avoid relying on Node specifics within compiler

.changeset/wicked-readers-knock.md, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/utils.js, packages/svelte/tests/runtime-legacy/samples/inline-expressions-2/_config.js, packages/svelte/tests/runtime-legacy/samples/inline-expressions-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14324
=> fix: ensure inline object literals are correctly serialised

documentation/docs/07-misc/07-v5-migration-guide.md
I believe its a typo? event handlers in svelte 4 have custom data passed to the callback with the .detail property, not .details
=> docs: use e.detail instead of e.details in migration examples

.changeset/moody-bears-change.md, packages/svelte/src/compiler/phases/2-analyze/visitors/CallExpression.js, packages/svelte/tests/runtime-legacy/samples/inline-expressions-subtree/_config.js, packages/svelte/tests/runtime-legacy/samples/inline-expressions-subtree/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14343
=> fix: ensure dynamic call expressions correctly generate output

.changeset/cool-trains-yawn.md, packages/svelte/src/internal/shared/clone.js, packages/svelte/tests/runtime-runes/samples/inspect-recursive-2/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-recursive-2/main.svelte
Closes https://github.com/sveltejs/svelte/issues/14336
=> fix: ensure internal cloning can work circular values

.changeset/unlucky-icons-sit.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/ClassBody.js, packages/svelte/tests/runtime-runes/samples/class-disabinguate-private-method-definition/_config.js, packages/svelte/tests/runtime-runes/samples/class-disabinguate-private-method-definition/main.svelte
=> fix: include method definitions in class private fields

.changeset/kind-horses-lay.md, packages/svelte/elements.d.ts
Add the [ContentVisibilityAutoStateChangeEvent](https://developer.mozilla.org/en-US/docs/Web/API/ContentVisibilityAutoStateChangeEvent)
[Example](https://svelte.dev/playground/3d380840b0774e138cfeb51ff419f4ac?version=5.2.4)
=> feat: add content-visibility: auto state change event

.changeset/tiny-trainers-sleep.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/AssignmentExpression.js, packages/svelte/tests/runtime-runes/samples/private-identifiers-not-this/_config.js, packages/svelte/tests/runtime-runes/samples/private-identifiers-not-this/main.svelte
Closes #13965
Unless i'm missing something obvious there's no reason to not always transform PrivateIdentifiers that are also inside the class private state so no need to check for the left object to be `this`. JS will stop them to modify a private identifier which is not of the same class and if it is from the same class it's fine to use `set` to set it.
=> fix: always use set for private identifiers

documentation/docs/07-misc/03-typescript.md
Fix TS error: Cannot invoke an object which is possibly 'undefined'.
=> docs Update 03-typescript.md

.changeset/rich-worms-burn.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/event-spread-timing/_config.js, packages/svelte/tests/runtime-runes/samples/event-spread-timing/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14385. Interestingly, it seems the tests in https://github.com/sveltejs/svelte/pull/11230 still pass here so I assume that we've fixed this issue through some other changes in the codebase since.
=> fix: ensure spread attribute events are attached synchronously

.changeset/lovely-mayflies-sing.md, packages/svelte/src/ambient.d.ts, packages/svelte/src/legacy/legacy-client.js, packages/svelte/types/index.d.ts
The transitionary interface `ComponentType` not being exported from the `*.svelte` module declaration causes issues when running `tsc` with `"declaration": true`: `error TS4082: Default export of the module has or is using private name 'ComponentType'.`
Exporting the interface from the  solves this problem in my reproduction (see: #14256)
> pnpm add https://pkg.pr.new/svelte@14257
holy smokes, `pkg.pr.new` is cool:
[Broken reproduction with svelte@5.1.9](https://stackblitz.com/edit/vitejs-vite-fgmgkx?file=src%2Findex.ts)
↓
[Fixed reproduction with svelte@https://pkg.pr.new/svelte@14257](https://stackblitz.com/edit/vitejs-vite-2hpal5?file=src%2Findex.ts)
~since `packages/svelte/src/ambient.d.ts` is included in `packages/svelte/types/index.d.ts` when building I wasn't sure if I should …
=> fix: export private legacy ComponentType (#14256)

.changeset/fuzzy-lies-battle.md, .changeset/wicked-buses-work.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/general-siblings-combinator-key/_config.js, packages/svelte/tests/css/samples/general-siblings-combinator-key/expected.css, packages/svelte/tests/css/samples/general-siblings-combinator-key/input.svelte, packages/svelte/tests/css/samples/siblings-combinator-each-else-nested/_config.js, packages/svelte/tests/css/samples/siblings-combinator-each-else-nested/expected.css, packages/svelte/tests/css/samples/siblings-combinator-each-else-nested/expected.html, packages/svelte/tests/css/samples/siblings-combinator-each-else-nested/input.svelte, packages/svelte/tests/css/samples/siblings-combinator-key/_config.js, packages/svelte/tests/css/samples/siblings-combinator-key/expected.css, packages/svelte/tests/css/samples/siblings-combinator-key/input.svelte
fixes part of #14399, and makes the code a bit less chaotic
=> fix: correctly prune key/each blocks

packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/src/compiler/types/index.d.ts
this extracts part of #14315 because I need it for the CSS pruning work. will instamerge once green to unblock
=> chore: initialize snippet binding correctly

packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js
trying to extract small changes out into separate PRs so that the eventual PR addressing #14399 doesn't contain too many changes. 
In `get_possible_element_siblings`, if we encounter a preceding element and `adjacent_only` is true, we can return immediately instead of breaking. Since there's no `break`, `prev` is always undefined after the first loop has run, meaning we always need to run the second loop.
Will instamerge to unblock the other work
=> chore: simplify css pruning slightly

.changeset/cool-gifts-sniff.md, packages/svelte/src/html-tree-validation.js, packages/svelte/src/internal/server/dev.js, packages/svelte/tests/runtime-runes/samples/invalid-html-ssr/_config.js, packages/svelte/tests/runtime-runes/samples/invalid-html-ssr/main.svelte
This reverts #13255 / #13158, and helps with the validation error part of #14120
If you would have a component like this...
```svelte
<td>hi there</td>
```
...and then render it on the server via our `render` function like this:
```js
const result = render(Main);
```
...then right now you get an error saying that `td` is not valid at this position. But that doesn't seem right, because we should give people the benefit of the doubt: It may very well be that someone renders such a component and then correctly puts it into a `tr` tag themselves on the server (another example is rendering a full html document like in #14120).
All the other validation where there's a known parent (X not valid inside Y) is untouched by this.
Doing this as cleanup prior to tackling #13331
=> fix: relax parent validation

.changeset/breezy-insects-live.md, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/tests/runtime-runes/samples/await-non-promise/_config.js, packages/svelte/tests/runtime-runes/samples/await-non-promise/main.svelte
fixes #14439
This bug was introduced in #13642 because setting the input to `null` means the equality check ("is the input different") fails if you set the value to `null`
Also fixes #14441 - this bug was present for a long time, and the reason is the same as for the other bug: The equality check always returns "yes this is the same" if the value is `undefined` initially. The fix is similar; we need to initialize the input to something that can never be equal to whatever value is passed
=> fix: show `:then` block for `null` value

.changeset/tender-balloons-relate.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/unused-ts-as-expression/_config.js, packages/svelte/tests/css/samples/unused-ts-as-expression/expected.css, packages/svelte/tests/css/samples/unused-ts-as-expression/input.svelte
Fixes #14204 — this refactors `get_possible_element_siblings` to make it non-recursive, and use `context.path` and `fragment.nodes` rather than `node.parent` and `node.prev`. We should now be able to get rid of all references to those properties, but I'll do that in a separate PR.
=> fix: disregard TypeScript nodes when pruning CSS

.changeset/great-crabs-rhyme.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
This was an odd memory leak that I've been tracking for weeks. I made the discovery today whilst looking into another issue that it was to do with `untrack`. Specifically, we only attach a derived to the parent effect when we're in a non tracking context – however, because nested deriveds only recorded their parent as effect, it meant that nested deriveds were incorrectly being added to the same effect after each run.
Rather than have the awkwardly deal with removing a derived from the parent each time, and know that deriveds can only be created where they are declared, we can instead just make the parent of a derived by that of an effect or another derived.
=> fix: addresses memory leak when creating deriveds inside untrack

packages/svelte/package.json, playgrounds/sandbox/package.json, pnpm-lock.yaml
`nodemon` appeared to be unused
upgrading `@rollup/plugin-commonjs` fixes a peer dependency warning
=> chore: remove unused dep and upgrade another one

.changeset/big-hats-wonder.md, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/unused-selector-in-between/expected.css, packages/svelte/tests/css/samples/unused-selector-leading/expected.css, packages/svelte/tests/css/samples/unused-selector-multiple/_config.js, packages/svelte/tests/css/samples/unused-selector-multiple/expected.css, packages/svelte/tests/css/samples/unused-selector-multiple/input.svelte
Closes #14426
I think this is a better strategy to keep the commas...before we were adding the comma everytime i was not the last selector but if every other selector is unused we don't need to add the comma or it will produce invalid css.
Instead i moved the logic to keep the previous comma when there's a new used selector that has a previous used selector.
=> fix: css pruning producing invalid css

packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js
extracting a couple of cosmetic changes out of #14456 to make the diff more explicit, will merge once green
=> chore: minor css-prune.js tweaks

.changeset/brave-keys-rescue.md, packages/svelte/src/compiler/phases/2-analyze/visitors/ExpressionTag.js, packages/svelte/src/compiler/phases/2-analyze/visitors/Text.js, packages/svelte/tests/validator/samples/invalid-node-placement-8/errors.json, packages/svelte/tests/validator/samples/invalid-node-placement-8/input.svelte
fixes #14466
The logic introduced in #14395 was flawed - not every text or expression outside the template is the child of an attribute. This turns it around: We know that every child of a fragment is inside the template, so we ignore all text/expression tags that are not child of a fragment
=> fix: ignore text and expressions outside the template when validating HTML

.changeset/itchy-timers-relax.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/component.js, packages/svelte/tests/css/samples/render-tag-loop/_config.js, packages/svelte/tests/css/samples/render-tag-loop/expected.css, packages/svelte/tests/css/samples/render-tag-loop/input.svelte
fixes #14472, and also makes improves snippet resolution (it was only handling strings and identifiers, not literals, meaning `answer={42}` was interpreted as 'could be any snippet').
There might be other situations that could result in a loop, trying to think of any
=> fix: prevent infinite loops when pruning CSS

package.json, pnpm-lock.yaml
removes a handful of dependencies. lessens the number of things depending on punycode, which causes an annoying warning while running tests, but doesn't solve it yet unfortunately
=> chore: bump jsdom to 25.0.1

packages/svelte/src/transition/index.js, packages/svelte/types/index.d.ts
=> docs: fix scale description

.changeset/silly-readers-double.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SpreadElement.js, packages/svelte/tests/runtime-runes/samples/props-spread-operator/Child.svelte, packages/svelte/tests/runtime-runes/samples/props-spread-operator/_config.js, packages/svelte/tests/runtime-runes/samples/props-spread-operator/main.svelte
fixes #14482. We need to treat `[...x]` the same as `[...x.values()]`, because that's what it often implies
=> fix: treat spread elements the same as call expressions

.changeset/popular-dogs-exist.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/render-tag-loop/expected.css, packages/svelte/tests/css/samples/snippets-elements/expected.css, packages/svelte/tests/css/samples/snippets-elements/input.svelte
=> fix: correctly prune CSS for elements inside snippets

.changeset/proud-crews-itch.md, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-runes/samples/dynamic-element-svg/_config.js, packages/svelte/tests/runtime-runes/samples/dynamic-element-svg/main.svelte
This fixes part of #14479 — attributes like `viewBox` were failing because the name was being lowercased and _then_ used to look up the value, creating a mismatch.
It doesn't fix the client-side error though, which happens because the contents of the `<svelte:element>` have an HTML template when they need an SVG one. Not yet sure what a good solution to that looks like.
=> fix: render attributes during SSR regardless of case

playgrounds/sandbox/run.js
`playgrounds/sandbox/run.js` doesn't work for components containing bigints, because they can't be serialized to JSON. There isn't really a great fix for this issue but this at least allows the sandbox to run
=> serialize bigint AST, albeit incorrectly

documentation/docs/07-misc/03-typescript.md
Also fix adjacent code examples
closes #14187
=> docs: add tsconfig.json info to TS docs

packages/svelte/src/internal/client/dom/elements/bindings/input.js, packages/svelte/tests/runtime-runes/samples/effect-tracking-binding-set/_config.js, packages/svelte/tests/runtime-runes/samples/effect-tracking-binding-set/main.svelte
Added a test to show why we need bindings events to have no reactive context, as per requested in https://github.com/sveltejs/svelte/pull/14511
=> chore: add test for binding event reactive context

.changeset/neat-news-dance.md, packages/svelte/src/compiler/phases/3-transform/client/types.d.ts, packages/svelte/src/compiler/phases/3-transform/client/visitors/EachBlock.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/Program.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/UpdateExpression.js, packages/svelte/tests/runtime-runes/samples/bigint-increment-mutation/_config.js, packages/svelte/tests/runtime-runes/samples/bigint-increment-mutation/main.svelte, packages/svelte/tests/runtime-runes/samples/bigint-increment/_config.js, packages/svelte/tests/runtime-runes/samples/bigint-increment/main.svelte
=> fix: leave update expressions untransformed unless a transformer is provided

documentation/docs/02-runes/02-$state.md
=> docs: hints on preserving reactivity

documentation/docs/02-runes/02-$state.md
https://github.com/sveltejs/svelte/pull/14311#issuecomment-2513930512
closes https://github.com/sveltejs/svelte/issues/14261
closes #14300
=> docs: how to javascript

.changeset/afraid-worms-clean.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/UseDirective.js, packages/svelte/tests/runtime-runes/samples/nullish-actions/_config.js, packages/svelte/tests/runtime-runes/samples/nullish-actions/main.svelte
Closes #13555 ...this may need some discussion because i don't know if it was done on purpose but it was simple enough i said, why not.
Also working on this i noticed we are creating an unnecessary thunk where we could just pass the action in (especially since it's not reactive)...should we fix this too?
=> fix: don't throw with nullish actions

.changeset/wicked-zebras-exist.md, packages/svelte/src/internal/client/dom/elements/bindings/shared.js, packages/svelte/src/reactivity/date.js, packages/svelte/src/reactivity/date.test.ts
alternative to #14512 — instead of using the nearest parent effect, we use whichever reaction was active when the instance was created
=> fix: ensure SvelteDate cached methods have correct reactive context

.changeset/hip-forks-exercise.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/error-boundary-20/Child.svelte, packages/svelte/tests/runtime-runes/samples/error-boundary-20/_config.js, packages/svelte/tests/runtime-runes/samples/error-boundary-20/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14526. This was a tricky one, because the infinite loop protection doesn't happen in the effect tree, but rather at the root level – so we need to capture the last effect that was scheduled to invoke an error boundary.
=> fix: capture infinite_loop_guard in error boundary

.changeset/giant-windows-dance.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/ClassBody.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js
`$state.raw` and `$derived(.by)` will not have a state symbol on them, potentially causing a disastrous amount of traversal to potentially not find any state symbol. So it's better to not traverse them.
Potentially someone could create a `$state` while creating `$state.raw` or inside a `$derived.by`, but that feels so much of an edge case that it doesn't warrant a perf hit for the common case.
Fixes #14491
=> fix: don't try to add owners to non-`$state` class fields

documentation/docs/98-reference/.generated/client-warnings.md, packages/svelte/messages/client-warnings/warnings.md
should fix the build errors in https://github.com/sveltejs/svelte.dev/pull/926
=> chore: fix docs

documentation/docs/99-legacy/20-legacy-slots.md
=> docs: tweak slot docs

packages/svelte/tests/runtime-runes/samples/inline-expressions/main.svelte
The unit test **runtime-runes/inline-expressions** use `toLocaleString()` on a `number`, which gives different results depending on the user's locale.
Ex : `7.36` will be printed as `7,36` (with a comma) on some locale like french, italien or spanish...
I simply replaced `toLocaleString()`  with `toString()`
=> [chore] Don't use locale-specific code in test inline-expressions

.changeset/sixty-tables-fold.md, packages/svelte/src/internal/client/loop.js
supersedes #4531, fixes #4468. It turns out that `performance.now()` uses a different clock to `requestAnimationFrame`, or at least they behave as though that were true. You can see if yourself by doing this:
```js
function go() {
const then = performance.now();
requestAnimationFrame((now) => {
if (now < then) {
console.error('oops! rift detected in spacetime continuum');
}
});
}
```
If you call `go()` enough times, you'll likely see the error, especially in Chrome.
#4531 offers one fix, but I think this one is probably more future-proof, and means that the first frame of a spring loop 'does' something which likely isn't true with the alternative.
No test because I have no idea how.
=> fix: respect the unidirectional nature of time

.changeset/blue-fans-greet.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/index.js, packages/svelte/tests/runtime-runes/samples/form-default-value/_config.js, packages/svelte/tests/runtime-runes/samples/form-default-value/main.svelte
When the `value` or `checked` attribute of an input or the contents of a textarea were static, setting the `defaulValue/defaultChecked` property caused the latter to take precedence over the former. This is due to how we transform the code: If the value is static, we put it onto
=> fix: handle static form values in combination with default values

.changeset/beige-windows-happen.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/IfBlock.js, packages/svelte/src/internal/client/dom/blocks/if.js, packages/svelte/tests/runtime-runes/samples/bind-this-no-state/main.svelte
Closes https://github.com/sveltejs/svelte/issues/12833.
Thanks to @adiguba for the idea as shown in https://github.com/sveltejs/svelte/discussions/13313. This PR aims to make `{#if}` blocks tree-shakable without any runtime performance regressions.
The principle is very similar to https://github.com/sveltejs/svelte/discussions/13313, but executed very differently to ensure that the following remain true:
- We don't have to change any existing tests and there should be no observable behaviour difference or breaking changes
- We don't cause runtime overhead and too much code size explosion
- We allow tree-shaking of if block conditions
The result of these things, means that this PR compiles this:
```svelte
{#if false}
Hello world
{:else}
LOL!
{/if}
```
In to this:
```js
var consequent = …
```
=> chore: make if blocks tree-shakable

documentation/docs/07-misc/99-faq.md
I added a link to Tauri that links to their SvelteKit docs and then sent them a PR to make it easier to find info about mobile apps from there: https://github.com/tauri-apps/tauri-docs/pull/3048
=> docs: add a mobile app FAQ

documentation/docs/07-misc/07-v5-migration-guide.md
...about slotted content behavior
Related to #14564
=> docs: note before/afterUpdate breaking change

.changeset/cool-clocks-film.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/form-default-value/_config.js, packages/svelte/tests/runtime-runes/samples/form-default-value/main.svelte
Fixes #14558
Any unforseen side effects that could come from this? (didn't add a test yet because I'm in a rush and want to have that question answered first)
=> fix: treat `undefined` and `null` the same for the initial input value

.changeset/little-berries-worry.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/component.js, packages/svelte/tests/runtime-runes/samples/bind-and-spread-precedence/_config.js, packages/svelte/tests/runtime-runes/samples/bind-and-spread-precedence/input.svelte, packages/svelte/tests/runtime-runes/samples/bind-and-spread-precedence/main.svelte
=> fix: ensure bindings always take precedence over spreads

.changeset/large-humans-report.md, packages/svelte/src/motion/public.d.ts, packages/svelte/types/index.d.ts
this was lost to a merge conflict when we shipped `Spring` and `Tween`, oops
=> fix: reinstate `prefersReducedMotion`

documentation/docs/03-template-syntax/03-each.md
i don't understand how this text suddenly reappeared, it's not on the production deploy of svelte.dev nor should it be (since it's duplicative). and yet it's in the `03-each.md` file? wtf
=> docs: where the hell did this come from?

.changeset/stupid-buckets-drum.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/ClassBody.js, packages/svelte/tests/runtime-runes/samples/class-state-conflicting-get-name/_config.js, packages/svelte/tests/runtime-runes/samples/class-state-conflicting-get-name/main.svelte
=> fix: deconflict `get_name` for literal class properties

documentation/docs/98-reference/.generated/client-warnings.md, documentation/docs/98-reference/.generated/compile-warnings.md, documentation/docs/98-reference/.generated/server-errors.md, documentation/docs/98-reference/.generated/shared-errors.md, documentation/docs/98-reference/.generated/shared-warnings.md, packages/svelte/messages/client-warnings/warnings.md, packages/svelte/messages/compile-warnings/script.md, packages/svelte/messages/compile-warnings/style.md, packages/svelte/messages/compile-warnings/template.md, packages/svelte/messages/server-errors/lifecycle.md, packages/svelte/messages/shared-errors/errors.md, packages/svelte/messages/shared-warnings/warnings.md
=> docs: more details for errors/warnings on the site

.changeset/cyan-ducks-train.md, packages/svelte/src/internal/client/dom/elements/bindings/input.js
Closes https://github.com/sveltejs/svelte/issues/14630.
We can actually restore selection on an input that has `bind:value` and the input differs because of a function binding accessor. In fact, we can re-use the restoration logic [implementation from React](https://github.com/facebook/react/blob/372ec00c0384cd2089651154ea7c67693ee3f2a5/packages/react-dom-bindings/src/client/ReactInputSelection.js#L194-L195).
Unfortunately, JSDOM doesn't seem to emulate selection changes when the value changes, so I didn't come up with a test.
=> fix: restore input binding selection position

.changeset/red-worms-suffer.md, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/css/samples/global-block/expected.css, packages/svelte/tests/css/samples/global-block/input.svelte
Closes #14568
I'm not entirely sure if there's a better way: i think keyframes are the only thing transformed that are not selectors but this should make sure that we transform everything, we just don't touch the selectors.
=> fix: transform everything that is not a selector inside `:global`

.changeset/clean-bobcats-fail.md, packages/svelte/src/internal/shared/clone.js, packages/svelte/tests/runtime-runes/samples/state-snapshot-array-holes/_config.js, packages/svelte/tests/runtime-runes/samples/state-snapshot-array-holes/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14653
=> fix: ensure $state.snapshot clones holey arrays correctly

.changeset/shy-carpets-rescue.md, packages/svelte/src/motion/spring.js
Issue: https://github.com/sveltejs/svelte/issues/14645
After using the `{instant: true}` option with `Spring.set()`, a subsequent (non-instant) `.set()` sometimes displayed unexpected behavior. See Issue link for reproduction, .gif of example, and more details.
This PR overwrites the Spring's #last_value after updating instantly so that no data/context from before the `instant` `.set()` lingers to interfere with future `.set()`s. After building this modified version of svelte and linking it to a sveltekit project, I no longer see the glitchy behavior described in the Issue linked above.
I saw no tests in the `/svelte/tests/` directory that use the newly created Spring class and don't feel currently knowledgeable enough to write a full suite myself. I'm also unsure how I would test the …
=> fix: overwrite #last_value when Spring is `.set()` with `{instant: true}`

.changeset/sharp-shoes-look.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-browser/custom-elements-samples/late-ce-mount/_config.js, packages/svelte/tests/runtime-browser/custom-elements-samples/late-ce-mount/main.svelte
fixes #14391
In #13337 the "when to set as a property" logic for custom elements was adjusted. A bug was introduced during this, and it consists of several parts, of which the latter I'm not sure what's the best solution, hence opening this to discuss.
The problem is that during `set_custom_element_data`, `get_setters` is the only check done to differentiate between setting the value as a prop (has a setter) or as an attribute (doesn't have a setter).
The solution is to take into account whether or not the custom element is already registered, and defer getting (and caching) its setters until then. Instead, fall back to a "an object is always set as a prop" heuristic.
Part 1 of the bug is that this only checks the setters of the prototype, but you can also add setters to the instance …
=> fix: correctly set custom element props

.changeset/khaki-guests-switch.md, packages/svelte/src/reactivity/window/index.js, packages/svelte/tests/server-side-rendering/samples/reactivity-window/_expected.html, packages/svelte/tests/server-side-rendering/samples/reactivity-window/main.svelte, packages/svelte/types/index.d.ts
=> fix: correctly handle ssr for `reactivity/window`

.changeset/silent-tips-cover.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/form-default-value-spread/_config.js, packages/svelte/tests/runtime-runes/samples/form-default-value-spread/main.svelte, packages/svelte/tests/runtime-runes/samples/form-default-value/_config.js
Closes #14634
I was not able to fully port the test without spreads because there's one single test I tried and failed to fix which is the textarea with `defaultValue` and a `child`. Do anyone has any idea on how could i fix this?
=> fix: make `defaultValue` work with spread

documentation/docs/98-reference/.generated/compile-warnings.md, packages/svelte/messages/compile-warnings/template.md
Found a typo in the compiler warnings docs in [script context deprecated](https://svelte.dev/docs/svelte/compiler-warnings#script_context_deprecated)
It said +++context+++ instead of +++module+++
=> docs: typo in ## script_context_deprecated

.changeset/long-boxes-flow.md, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/tests/parser-legacy/samples/attribute-unquoted/input.svelte, packages/svelte/tests/parser-legacy/samples/attribute-unquoted/output.json
This pull request introduces the ability to allow unquoted slashes in attributes within the Svelte compiler. The key changes include modifications to the parser to handle unquoted slashes, as well as updates to the test cases to ensure this new feature is properly validated.
**Changes to the Svelte compiler**:
* [`packages/svelte/src/compiler/phases/1-parse/state/element.js`](diffhunk://#diff-7b392039dd08109dbbe1b76e614dc5fa1801f49a3a626cb229534af1263f3d46R507-R524): Modified the `read_attribute` function to handle unquoted slashes in attribute values. When it's an unquoted slash, parser will handle it as a quoted slash. 
**Updates to test cases**:
* [`packages/svelte/tests/parser-legacy/samples/attribute-unquoted/input.svelte`](diffhunk://#diff-3db67cd7f70fc4bdb0773f8f19690eccd3404005ad08 …
=> fix: Allow unquoted slash in attributes

.changeset/giant-moons-accept.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/IfBlock.js, packages/svelte/src/compiler/phases/3-transform/utils.js, packages/svelte/tests/runtime-runes/samples/svg-namespace-if-block/Child.svelte, packages/svelte/tests/runtime-runes/samples/svg-namespace-if-block/_config.js, packages/svelte/tests/runtime-runes/samples/svg-namespace-if-block/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14671.
=> fix: ensure if block paths retain correct template namespacing

.changeset/cold-cows-enjoy.md, packages/svelte/src/reactivity/media-query.js, packages/svelte/tests/helpers.js, packages/svelte/tests/runtime-runes/samples/media-query/_config.js, packages/svelte/tests/runtime-runes/samples/media-query/main.svelte
=> fix: don't add parenthesis to media query if already present

.changeset/twelve-hairs-marry.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/index.js, packages/svelte/src/compiler/phases/1-parse/index.js, packages/svelte/src/compiler/phases/1-parse/read/expression.js, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/src/compiler/phases/1-parse/state/tag.js, packages/svelte/src/compiler/phases/1-parse/utils/bracket.js, packages/svelte/tests/parser-legacy/samples/loose-invalid-block/input.svelte, packages/svelte/tests/parser-legacy/samples/loose-invalid-block/output.json, packages/svelte/tests/parser-legacy/samples/loose-invalid-expression/input.svelte, packages/svelte/tests/parser-legacy/samples/loose-invalid-expression/output.json, packages/svelte/tests/parser-legacy/samples/loose-unclosed-block/input.svelte, packages/svelte/tests/parser-legacy/samples/loose-unclosed-block/output.json, packages/svelte/tests/parser-legacy/samples/loose-unclosed-open-tag/input.svelte, packages/svelte/tests/parser-legacy/samples/loose-unclosed-open-tag/output.json, packages/svelte/tests/parser-legacy/samples/loose-unclosed-tag/input.svelte, packages/svelte/tests/parser-legacy/samples/loose-unclosed-tag/output.json, packages/svelte/tests/parser-legacy/test.ts, packages/svelte/tests/parser-modern/samples/loose-invalid-block/input.svelte, packages/svelte/tests/parser-modern/samples/loose-invalid-block/output.json, packages/svelte/tests/parser-modern/samples/loose-invalid-expression/input.svelte, packages/svelte/tests/parser-modern/samples/loose-invalid-expression/output.json, packages/svelte/tests/parser-modern/samples/loose-unclosed-open-tag/input.svelte, packages/svelte/tests/parser-modern/samples/loose-unclosed-open-tag/output.json, packages/svelte/tests/parser-modern/samples/loose-unclosed-tag/input.svelte, packages/svelte/tests/parser-modern/samples/loose-unclosed-tag/output.json, packages/svelte/tests/parser-modern/test.ts, packages/svelte/types/index.d.ts
This implements a new option for the parser, `loose`, which means the parser is forgiving with the syntax and tries to continue parsing even if it encounters broken code. It does not parse no matter what, but handles the most common "in the middle of typing" scenarios gracefully.
closes #4818
Our language tools can then make use of this to provide better intellisense in more situations.
=> feat: loose parser mode

.changeset/many-worms-attend.md, packages/svelte/src/internal/client/runtime.js
Fixes some of the performance issues on https://github.com/sveltejs/svelte/issues/14721
If we have an unowned derived that is actively in the graph, we can mark it as CLEAN. It's only if it's not in the graph can we not.
=> fix: improve unowned derived performance

.changeset/tame-eggs-work.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/inspect-trace/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-trace/main.svelte
=> fix: correctly highlight first rerun of `$inspect.trace`

.changeset/tiny-kings-serve.md, packages/svelte/src/compiler/phases/1-parse/read/expression.js, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/src/compiler/phases/1-parse/state/tag.js, packages/svelte/src/compiler/phases/1-parse/utils/bracket.js, packages/svelte/tests/parser-legacy/samples/loose-invalid-expression/input.svelte, packages/svelte/tests/parser-legacy/samples/loose-invalid-expression/output.json, packages/svelte/tests/parser-legacy/samples/loose-unclosed-tag/input.svelte, packages/svelte/tests/parser-legacy/samples/loose-unclosed-tag/output.json, packages/svelte/tests/parser-modern/samples/loose-invalid-expression/input.svelte, packages/svelte/tests/parser-modern/samples/loose-invalid-expression/output.json, packages/svelte/tests/parser-modern/samples/loose-unclosed-tag/input.svelte, packages/svelte/tests/parser-modern/samples/loose-unclosed-tag/output.json
- handle invalid expressions inside each/await
- handle `<component.` (i.e. in the middle of typing a component that starts with a lowercase)
=> chore: loose parser improvements

documentation/docs/99-legacy/30-legacy-svelte-component.md
It's not obvious how to create dynamically rendered components in Svelte 5.
If you come from Svelte 4 and search for `svelte:component`, you'll most likely end up on [this page](https://svelte.dev/docs/svelte/legacy-svelte-component), which only gives a cursory explanation for runes mode. The [migration guide's section on `<svelte:component>`](https://svelte.dev/docs/svelte/v5-migration-guide#Breaking-changes-in-runes-mode-svelte:component-is-no-longer-necessary) has a great example that clears things up. Adding a link to that would be very helpful.
=> docs: Link to migration guide from <svelte:component> documentation

.changeset/tasty-deers-agree.md, packages/svelte/src/internal/client/dev/equality.js, packages/svelte/tests/runtime-runes/samples/state-proxy-equality-mismatch/_config.js, packages/svelte/tests/runtime-runes/samples/state-proxy-equality-mismatch/main.svelte
Fixes #14705, alternative to #14729
=> fix: compare array contents for equality mismatch detections, not the arrays themselves

.changeset/famous-mugs-rhyme.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js
=> fix: remove unwanted properties from both replaced and unreplaced nodes

.changeset/calm-maps-cover.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-browser/samples/typescript-class-and-interface/_config.js, packages/svelte/tests/runtime-browser/samples/typescript-class-and-interface/main.svelte
related: #14743 #14744 @Rich-Harris 
This PR fixes a build issue that occurs when esrap 1.3.0 or later is used.
When compiling the following component:
```svelte
interface MyInterface {}
class MyClass implements MyInterface {}
</script>
<p>hello</p>
```
The following error occurs:
```
error during build:
src/routes/Component.svelte (4:26): Expected '{', got 'implements' (Note that you need plugins to import files that are not JavaScript)
file: /path/to/project/src/routes/Component.svelte:4:26
2:   interface MyInterface {}
3: 
4:   class MyClass implements MyInterface {}
```
=> fix: remove 'implements' from class declaration

packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/runtime-browser/samples/typescript-class-and-interface/_config.js, packages/svelte/tests/runtime-browser/samples/typescript-class-and-interface/main.svelte, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte
- move a test
- revert seemginly unnecessary code changes (@Rich-Harris why were those necessary? Was it maybe necessary prior to #14744, i.e. battling symptoms rather than the cause?)
- adds a test that fails without #14744
=> chore: TS fixes cleanup

documentation/docs/98-reference/.generated/compile-warnings.md, packages/svelte/messages/compile-warnings/template.md
makes info about the migration script easier to find, along with a more detailed explanation about why self-closing tags are silly
https://svelte-dev-git-preview-svelte-14758-svelte.vercel.app/docs/svelte/compiler-warnings#element_invalid_self_closing_tag
=> add self-closing-tags info

.changeset/nine-buses-own.md, packages/svelte/src/compiler/phases/2-analyze/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/utils.js, packages/svelte/tests/runtime-runes/samples/svg-namespace-if-block-2/_config.js, packages/svelte/tests/runtime-runes/samples/svg-namespace-if-block-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14723 and fixes https://github.com/sveltejs/svelte/issues/14751.
=> fix: ensure svg namespace for `<a>` elements is correct

.changeset/tough-dingos-deliver.md, packages/svelte/package.json, packages/svelte/scripts/check-treeshakeability.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/CallExpression.js, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/compiler/phases/types.d.ts, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/flags/index.js, packages/svelte/src/internal/flags/tracing.js
`$inspect.trace` introduces generation of call stacks during DEV, and this can add significant overhead in hot-paths. If `$inspect.trace` is unused, then there shouldn't be a performance deficit in DEV.
=> fix: ensure $inspect.trace code is treeshaken out if unused

.changeset/cool-ducks-carry.md, packages/svelte/package.json, packages/svelte/scripts/process-messages/index.js, packages/svelte/src/compiler/phases/3-transform/index.js, pnpm-lock.yaml
=> fix: bump esrap dependency

.changeset/modern-colts-drive.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/compiler/phases/types.d.ts
Follow up to https://github.com/sveltejs/svelte/pull/14770. I missed the call-site for handling serialisation in Svelte modules.
=> fix: treeshake `$inspect.trace` code if unused in modules

.changeset/calm-shrimps-remain.md, packages/svelte/package.json
This PR adds the `worker` condition for entrypoints that exports dual browser/non-browser files, so that `worker` resolves to the non-browser file.
In Svelte 5, there has been issues using it in Astro and Cloudflare (https://github.com/withastro/adapters/issues/485). The cloudflare integration configures Vite with `ssr.target: 'webworker'`, which also changes the resolve conditions to `browser`, `development|production`, etc.
<details>
<summary>Additional info: about why `browser` condition is used</summary>
Usually if a library have either `browser` or `node` conditions, it's more likely for `browser` to work in those worker-based environments, like Cloudflare's workerd or Vercel edge since they don't support node-based APIs. Though today these environments do have some form of …
=> feat: add "worker" exports condition

.changeset/twenty-shoes-peel.md, packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/css/samples/global-block/expected.css, packages/svelte/tests/css/samples/global-block/input.svelte
Fixes https://github.com/sveltejs/svelte/issues/14713
=> fix: Allow to disable animation prefix

documentation/docs/98-reference/.generated/client-errors.md, documentation/docs/98-reference/.generated/client-warnings.md, documentation/docs/98-reference/.generated/compile-warnings.md, packages/svelte/messages/client-errors/errors.md, packages/svelte/messages/client-warnings/warnings.md, packages/svelte/messages/compile-warnings/a11y.md, packages/svelte/src/compiler/warnings.js, packages/svelte/src/internal/client/errors.js, packages/svelte/tests/validator/samples/a11y-click-events-have-key-events/warnings.json, packages/svelte/tests/validator/samples/slot-warning/warnings.json, packages/svelte/tests/validator/samples/slot-warning2/warnings.json
there's some redundant links in the messages, plus some unnecessarily qualified links
=> docs: fix links in some errors/warnings

README.md
Content in the svelte.dev section was outdated. So just updated the links and wording.
=> chore: remove svelte.dev section from README.md

.changeset/chatty-dolphins-complain.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
Fixes https://github.com/sveltejs/svelte/issues/14846. This ensures that we properly attach unowned deriveds to their dependencies. Previously, we might only attach one of the dependencies if that dependency was also a mismatched version – which meant we skipped all the other dependencies.
=> fix: ensure unowned deriveds correctly get re-linked to the graph

.changeset/happy-plums-greet.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/derived-disconnect/_config.js, packages/svelte/tests/runtime-runes/samples/derived-disconnect/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14896.
=> fix: ensure disconnected deriveds correctly connect again

packages/svelte/scripts/generate-version.js, packages/svelte/src/index.d.ts, packages/svelte/src/version.js, packages/svelte/types/index.d.ts
Remove one that is unnecessary, and make another one appear nice in markdown.
closes #14850
=> docs: tweak links

.changeset/real-dolphins-return.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/shared/utils.js
Instead of using `array.indexOf` we can use the cached prototype method, avoiding any monkey-patching in DEV and also ensuring the IC is always hot in both dev and prod. Should hopefully resolve https://github.com/sveltejs/svelte/issues/14875.
=> fix: use cached indexOf array prototype method internally

.changeset/violet-cows-reply.md, packages/svelte/src/motion/tweened.js
Fixes #14849 by adjusting when `this.#current.v` is read in `Tween.set`, getting the behavior more in line with the (now deprecated) `tweened`. See the issue for demos illustrating the problem.
I couldn't think of an appropriate test for this. As this is my first PR for Svelte, any help or feedback would be greatly appreciated!
=> fix: Make Tween work with continuous target changes

documentation/docs/02-runes/05-$props.md
This is always the first place I look when I forget how to use `svelte/elements`, but the real documentation on it is buried under Misc/Typescript.
=> docs: add note about svelte/elements to $props

.changeset/tidy-dragons-thank.md, packages/svelte/src/internal/client/validate.js, packages/svelte/tests/runtime-runes/samples/bindable-prop-and-export/Component.svelte, packages/svelte/tests/runtime-runes/samples/bindable-prop-and-export/_config.js, packages/svelte/tests/runtime-runes/samples/bindable-prop-and-export/main.svelte
Closes #14805
I'm not sure if we really want to this but tbf seems a good change since the `bind` property will still be the actual prop and not the function.
=> fix: don't throw `bind_invalid_export` if there's also a bindable prop with the same name

documentation/docs/03-template-syntax/12-use.md
Currently, the docs for `use:` give an example of using the `Action` interface to type an action. In it, `null` is specified as the optional type argument for the parameter. Unfortunately, this means the example leads to the following type error in practice, on the line where `use:gestures` is contained: `Expected 2 arguments, but got 1.`
The solution is to switch the type argument for the parameter to `undefined`. This gets rid of the type error, accomplishes the intended behaviour, and matches the default value for the generic to begin with.
No testing required as it is a documentation change. To recreate the type error simply copy and paste the example into any svelte project. I couldn't figure out how to get the playground compiler to do type-checking in svelte files to show it …
=> docs: Switch typing of Action<Parameter> from null to undefined in 12-use.md

documentation/docs/02-runes/02-$state.md, documentation/docs/07-misc/02-testing.md
=> docs: add code of files being tested

.changeset/forty-books-taste.md, packages/svelte/src/internal/client/dom/elements/attributes.js
No test because no way to do that
fixes #14739
=> fix: guard against `customElements` being unavailable in browser extension contexts

benchmarking/benchmarks/reactivity/kairo/kairo_avoidable.js, benchmarking/benchmarks/reactivity/kairo/kairo_broad.js, benchmarking/benchmarks/reactivity/kairo/kairo_deep.js, benchmarking/benchmarks/reactivity/kairo/kairo_diamond.js, benchmarking/benchmarks/reactivity/kairo/kairo_mux.js, benchmarking/benchmarks/reactivity/kairo/kairo_repeated.js, benchmarking/benchmarks/reactivity/kairo/kairo_triangle.js, benchmarking/benchmarks/reactivity/kairo/kairo_unstable.js
I want to keep us better aligned with the official benchmark which also uses 1000 iterations, rather than 100.
https://github.com/milomg/js-reactivity-benchmark/blob/main/src/kairoBench.ts#L36
We couldn't do this before because our old signal implementation was too slow and it added on several minutes to the the CI time, but we can now since we fixed those perf issues many months ago. This will help with tuning our existing implementation too – as the number of iterations will better reflect the overhead.
=> chore: expand benchmark iterations

documentation/docs/02-runes/04-$effect.md
while reviewing #14821, I realised that the `$effect.tracking()` docs come across a bit strangely now that we have `createSubscriber`. I think it makes more sense to just link to those docs to explain the purpose of the rune, rather than laboriously recreating a worse version of the abstraction (which someone might, seeing those docs, decide to use).
It also means that we're spending less real estate on an extremely niche feature that most people shouldn't be touching
=> docs: simplify `$effect.tracking()` docs

.changeset/gold-olives-care.md, packages/svelte/src/transition/index.js, packages/svelte/tests/runtime-legacy/samples/class-shortcut-with-transition/_config.js
Supersedes #8907 (previous PR targets the `svelte-4` branch and updates a no-longer-existent test), fixes #8533
=> fix: account for min-width/height in `slide` transition

.changeset/cool-apples-report.md, packages/svelte/src/motion/tweened.js, packages/svelte/tests/motion/test.ts
Right now, non-numeric values cause interpolation in `tweened` or `Tween` to fail unless you provide a custom interpolator. It would probably be more useful if they just snapped to their new value instead — if you need some slightly different behaviour (e.g. flipping at the halfway mark) then you can continue to provide your own interpolator, but with this PR it's no longer required.
Supersedes #8678, closes #7543.
[Demo](https://svelte.dev/playground/hello-world?version=pr-14941#H4sIAAAAAAAAE22SwXLbIBCGX2WHi-wZR3Yy04ssudNbb730VvWAYK0wQaCBVdxUw7sXgdzWTi5C_Pst-7PszAwfkFXsK2pt4WKdlrBBqQjllu3YWWn0rPoxM3obF24Ror5mfRnH0r-ipkXruMePdGENoaF4DKu9cGqkU2taUsNoHcEMYuqU-DYRBDg7O0CRM_fIvTJ9cbyBv18QzT05WFLWJDKysZ4noAQ2YPCSkzZLrKU5Ly159RsreNxd98Jq6yooOj1hkcWwu8vJlqq_lldsWbaxer3_dz9TdxORTY48vWlsWuYF17HmnLy …
=> feat: allow non-numeric values to be tweened by snapping immediately to new value

.changeset/modern-wasps-punch.md, packages/svelte/src/motion/spring.js
Supersedes #7011 and #11337 (updates the `Spring` class as well as the legacy `spring` store). Rather than introducing new API, it just clamps the elapsed time to a 30th of a second, which results in continuous motion with the occasional dropped frame, but avoids things going wacky with longer pauses.
Closes #7010
=> fix: prevent long delays causing erratic spring behaviour

.changeset/silver-humans-yawn.md, documentation/docs/98-reference/.generated/client-warnings.md, packages/svelte/messages/client-warnings/warnings.md, packages/svelte/src/internal/client/warnings.js, packages/svelte/src/transition/index.js
Alternative to #5922, closes #4948. We can't just set `display` to `block` or something else because in many cases that will result in broken styles — the best we can do is encourage people to use flex/grid layouts instead.
=> feat: warn on using `slide` transition with invalid `display` styles

.changeset/sharp-dryers-try.md, documentation/docs/98-reference/.generated/compile-errors.md, packages/svelte/messages/compile-errors/script.md, packages/svelte/src/compiler/errors.js, packages/svelte/tests/compiler-errors/samples/runes-invalid-each-binding-this/_config.js, packages/svelte/tests/compiler-errors/samples/runes-invalid-each-binding/_config.js, packages/svelte/tests/compiler-errors/samples/runes-invalid-each-mutation/_config.js
=> docs: tweak "invalid assignment" compiler error message

.changeset/tough-guests-sniff.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/AssignmentExpression.js, packages/svelte/tests/runtime-runes/samples/proxy-coercive-assignment-warning/_config.js, packages/svelte/tests/runtime-runes/samples/proxy-coercive-assignment-warning/main.svelte
=> fix: silence false-positive stale value warning

.changeset/long-weeks-brush.md, packages/svelte/src/animate/index.js
Supersedes #7207, closes #7205, and attempts to make the logic slightly easier to follow (this damn near broke my brain)
- [5.17.0](https://svelte.dev/playground/d6d27cd6b789451085fe894fb15f9ef1?version=5.17.0)
- [this PR](https://svelte.dev/playground/d6d27cd6b789451085fe894fb15f9ef1?version=pr-14957)
=> fix: account for parent scale when animating elements

.changeset/sixty-paws-compete.md, packages/svelte/src/internal/client/dom/elements/transitions.js
This is a slightly hacky fix for #4712. It works by adding `style="overflow: hidden"` on transitioning elements, if the transition includes `overflow: hidden` (which is the case for `slide`, for example).
We _could_ argue that we shouldn't bother with this, since it's fixed in Safari 18. I just wanted to see how easy the fix would be.
=> fix: apply `overflow: hidden` style when transitioning elements, where necessary

.changeset/yellow-dodos-smell.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/tests/runtime-runes/samples/ownership-function-bindings/Child.svelte, packages/svelte/tests/runtime-runes/samples/ownership-function-bindings/_config.js, packages/svelte/tests/runtime-runes/samples/ownership-function-bindings/main.svelte
alternative to #14960 — I might be missing something but I think we just need to call the getter inside the effect, rather than doing any fancy static analysis footwork
Closes https://github.com/sveltejs/svelte/issues/14956
=> fix: properly add owners to function bindings

.changeset/fifty-chefs-invent.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/read-version-previous-reaction/Component.svelte, packages/svelte/tests/runtime-runes/samples/read-version-previous-reaction/_config.js, packages/svelte/tests/runtime-runes/samples/read-version-previous-reaction/main.svelte
=> fix: reset dependency read versions after reaction execution

.changeset/tender-apples-scream.md, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/tests/runtime-runes/samples/each-updates-9/_config.js, packages/svelte/tests/runtime-runes/samples/each-updates-9/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14961. 
[We have logic in the each block today](https://github.com/sveltejs/svelte/blob/main/packages/svelte/src/internal/client/dom/blocks/each.js#L478-L479) that assumes that the child effects of an each block effect are always the entries of the each block. This is not correct – as the expression used to get the collection for the each block might also create its own effects. Previously, we'd override the effects created from `get_collection` and it would cause a bunch of issues.
To avoid this, we can wrap the collection expression in a derived that enables us to instead put the effects associated with that collection with the derived rather than the each block effect.
=> fix: wrap each block expression in derived to encapsulte effects

.changeset/hot-kings-shout.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/internal/client/reactivity/store.js, packages/svelte/tests/runtime-runes/samples/store-update-on-destroy/Test.svelte, packages/svelte/tests/runtime-runes/samples/store-update-on-destroy/_config.js, packages/svelte/tests/runtime-runes/samples/store-update-on-destroy/main.svelte
Closes #14950 
While working on this initially with @oscard0m i actually found out of a separate bug, a memory leak: basically if you did something like this
```svelte
<script>
let { store } = $props();
$effect(()=>{
return ()=>{
$store;
}
});
</script>
```
the store was accessed for the first time after the teardown of the stores executed. So a new subscription was created for the store that generally would've been cleaned up by the teardown but since it already ran it was stuck in memory.
This was even worse for stuff that was accessed on component destroy asynchronously.
This solution does two things:
1. the `setup_stores` function doesn't register the `teardown` immediately but returns a function that does that. This function is called after `pop` so that register even after every …
=> fix: store access on component destroy

CONTRIBUTING.md
=> fix: Remove out-of-date note from CONTRIBUTING.md

.changeset/healthy-hairs-run.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/tests/runtime-runes/samples/error-boundary-21/Child.svelte, packages/svelte/tests/runtime-runes/samples/error-boundary-21/_config.js, packages/svelte/tests/runtime-runes/samples/error-boundary-21/main.svelte
Closes #14994
Thanks to @trueadm for the guidance (he actually solved the bug in #14998 ...we then talked a bit and since this seemed a better alternative we switched to this).
=> fix: never consider inert boundary effects

documentation/docs/98-reference/.generated/compile-errors.md, packages/svelte/messages/compile-errors/template.md, packages/svelte/src/compiler/errors.js, packages/svelte/tests/validator/samples/const-tag-placement-1/errors.json, packages/svelte/tests/validator/samples/const-tag-placement-2/errors.json
In #14993 i forgot to update the error message...this fixes that (no changeset since it's not bumping anything)
=> docs: update error message for `const_tag_invalid_placement`

.changeset/lemon-llamas-reflect.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/tests/runtime-runes/samples/transition-each-4/_config.js, packages/svelte/tests/runtime-runes/samples/transition-each-4/main.svelte
This has been on my radar for a while now, and the fix became obvious today. When we resume children on an effect tree, we need to execute any of the stale effects that are dirty. We should be scheduling effects rather than just running them sync – otherwise we don't the correct topological ordering.
=> fix: ensure resume effects are scheduled in topological order

.changeset/thirty-starfishes-shout.md, documentation/docs/03-template-syntax/18-class.md, packages/svelte/elements.d.ts
=> feat(elements): Expose ClassValue

.changeset/rich-donkeys-wink.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/tests/snapshot/samples/text-nodes-deriveds/_expected/client/index.svelte.js
When dealing with things like this, where a text node's value involves multiple expressions involving function calls...
```svelte
<p>{one()} + {two()} + {three} = {one() + two() + three}</p>
```
...we create deriveds for the expressions to avoid (for example) recalculating `{two()}` when only `one` changed.
But we take it a bit too far — we also create an unnecessary derived for `{three}`. This fixes it. It also renames the very strange 'stringified_text' (what next, a numberfied number?) to 'expression'
=> fix: create fewer deriveds for concatenated strings

.changeset/cuddly-walls-pretend.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/tests/snapshot/samples/nullish-coallescence-omittance/_config.js, packages/svelte/tests/snapshot/samples/nullish-coallescence-omittance/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/nullish-coallescence-omittance/_expected/server/index.svelte.js, packages/svelte/tests/snapshot/samples/nullish-coallescence-omittance/index.svelte
Currently, Svelte will almost always append a nullish coallescence statement (`maybeNullish ?? alternate`) to any interpolations in a template expression, regardless of whether there already is one. This changes that, so that nullish coallescence to a non-null literal will stay the same, and in `stuff ?? null` cases, `null` is replaced with an empty string.
=> fix: omit unnecessary nullish coallescing in template expressions

.changeset/fresh-cycles-sneeze.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
As documented in https://github.com/sveltejs/svelte/pull/14784, one of the downsides of `untrack` today is that it sets the active reaction to `null`. This is highly problematic as it leads to the effect tree being malformed – as shown with the test case. Instead of setting `active_reaction` to `null` we instead use an `untracking` flag. To prevent breaking changes, writes inside of `untrack` are permitted.
This doesn't fix the issues are making writes inside `untrack` possibly causing glitching, but I think fixing the bigger issue of the effect tree being mangled is probably as important.
=> fix: ensure untrack correctly retains the active reaction

packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/reactivity/sources.js
small addition to #15069 — only call `onchange` once for array mutations
- [#15069](https://svelte.dev/playground/hello-world?version=pr-15069#H4sIAAAAAAAAE41RS07DMBC9ymAh1VaTtAFWJUnFjju0XbjptDEYO7InBRTl7thNKlggxMrW-_l5pmdGviFbsWfU2sK7dfoAHA-K8CBYwo5Ko2erTc_os426CAR8cj21bebPqClie-nxN7y2htBQiGGFr51qqdqaLWkkqBtpTuihhFtPkpAvxWPkrrx07pvbLBPIE7hL4D6Bh10C_UVK1owxXEzAlsKT3mrMtD3x0Z15I1vfWOIhU0yvROXUYF5CPoFDPIYoKRbffU1xk6aAsm7AHoEa9Aghrwvzcug7TaAMSPDKnDROH4M0DdZi31EoCaGnVvVr2XMBZRX_lrWdb3hslEniaS5gvYalgDnkYqgiWSxG898xvlFH4sFyufzP4_CMzuPFZd1PU7C1VR81L1YZPktgJoZi0VYjMU1suC4vMmHLhB_EVuQ6HHbDF_eYNblXAgAA)
- [this PR](https://svelte.dev/playground/hello-world?version=pr-15073#H4sIAAAAAAAAE41RS07DMBC9ymAh1VaTtAFWJUnFjju0XbjptDEYO7InBRTl7thNKlggxMrW-_l5pmdGviFbsWfU2sK7dfoAHA-K8CBYwo5Ko2erTc_os426CAR8cj21 …
=> fix: only call `onchange` once for array mutations

.changeset/ninety-chefs-know.md, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-runes/samples/untracked-derived-local/_config.js, packages/svelte/tests/runtime-runes/samples/untracked-derived-local/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/15077
=> fix: address regression with untrack

.changeset/pink-wolves-search.md, packages/svelte/src/utils.js, packages/svelte/tests/runtime-runes/samples/form-novalidate-casing/_config.js, packages/svelte/tests/runtime-runes/samples/form-novalidate-casing/main.svelte
This PR fixes #15082 by correctly handling the HTML element `novalidate` attribute casing through `noValidate` DOM property mapping.
=> fix: correctly handle `novalidate` attribute casing

.changeset/tasty-pigs-greet.md, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/AwaitBlock.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/SlotElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/element.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js
This fixes a small regression introduced in #15050. Prior to that PR, we would handle memoization in different ways throughout the compiler; now, the memoization logic is more explicit and consistent. The decision of _whether_ to memoize happens inside `build_attribute_value` (or `build_template_chunk`), using the passed-in logic — if an expression contains a `CallExpression`, we memoize — but this elides an important distinction between component props and other expressions.
In most cases, an expression like `a + b` doesn't get memoized (it doesn't contain a `CallExpression`). But for component props, we _do_ memoize these expressions, because otherwise we get overfiring in a case like this:
```svelte
<Foo active={i === index} />
```
The result, post-#15050, is that anything containing a …
=> fix: avoid double deriveds in component props

.changeset/dirty-sloths-move.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/value-attribute-null-undefined/_config.js, packages/svelte/tests/runtime-runes/samples/value-attribute-null-undefined/main.svelte
Previously there was an inconsistency where a `value` attribute (correctly) wasn't set if initially `undefined` (resulting in the input value being a blank string), but if the `value` attribute was first set to a non-nullish value, and then changed to `undefined`, then the string "undefined" would appear as the input value, rather than the expected empty string.
Fixes #4467
=> fix: consistently set value to blank string when value attribute is undefined

.changeset/large-islands-cover.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js
small follow-up to #15056 — we can simplify the logic a tiny bit (and avoid mutating the AST node), but more to the point we can apply the same optimisation to `||` expressions. ultimately it would be nice to extend this to more cases (variables with a known set of possible values, ternaries, etc) but for now just picking the lowest-hanging fruit
=> fix: optimise || expressions in template

.changeset/strange-hairs-trade.md, packages/svelte/src/utils.js, packages/svelte/tests/runtime-runes/samples/attribute-boolean-case-insensitivity/_config.js, packages/svelte/tests/runtime-runes/samples/attribute-boolean-case-insensitivity/main.svelte
This PR is a follow-up to #15083, in an attempt to further correct the issue in #15082, by expanding HTML element boolean attribute support, especially when the HTML attributes casing don't match the DOM property (IDL attribute) casing.
The following attribute support has been added:
- [`defer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer)
- [`disablepictureinpicture`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#disablepictureinpicture)
- [`disableremoteplayback`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#disableremoteplayback)
... and the following attribute support has been improved (case mapping):
- [`allowfullscreen`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#allowfullscreen)
- …
=> fix: expand boolean attribute support

packages/svelte/src/compiler/phases/3-transform/client/visitors/EachBlock.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/src/compiler/types/template.d.ts, packages/svelte/src/internal/client/dom/blocks/each.js
Noticed this while working on something adjacent. We populate each block metadata with an `array_name` that's only used within the client transform. In the spirit of keeping code as close to where it's used as possible, this PR moves the code into that transform. It also eliminates a declaration in favour of an argument to the render callback:
```diff
-const $$array = () => $.get(x);
-$.each(node, 1, $$array, $.index, ($$anchor, x, $$index) => {
+$.each(node, 1, () => $.get(x), $.index, ($$anchor, x, $$index, $$array) => {
// ...
});
```
=> chore: tweak each block code

packages/svelte/src/compiler/phases/2-analyze/index.js
small, harmless tweak that will make the diff of an upcoming PR smaller
=> chore: construct analysis before module walk

packages/svelte/src/compiler/phases/1-parse/state/tag.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/types.d.ts, packages/svelte/src/compiler/phases/2-analyze/visitors/CallExpression.js, packages/svelte/src/compiler/phases/2-analyze/visitors/RenderTag.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/RenderTag.js, packages/svelte/src/compiler/types/template.d.ts
another harmless tweak a la #15108, which reduces the size of an upcoming PR diff. It's also more efficient (less traversal) and more self-contained, since the logic now resides in the `RenderTag` analysis and transformation visitors instead of also polluting the `CallExpression` visitor
=> chore: tweak render tag logic

.changeset/few-beans-bow.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
Fixes https://github.com/sveltejs/svelte/issues/15111. 
We don't need to eagerly connect deriveds to their parents – we don't do this in effects, so we can apply the same heuristic here too. If we lazily do it upon read of the derived from within a parent derived. If no read is done, we skip pushing it into the children. This will avoid the buggy case linked, and also provide a nice performance uplift by avoiding array allocations for cases where don't need to do them.
=> fix: lazily connect derievds (in deriveds) to their parent

packages/svelte/src/index-client.js, packages/svelte/src/internal/client/context.js, packages/svelte/src/internal/client/dev/legacy.js, packages/svelte/src/internal/client/dev/ownership.js, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/src/internal/client/dom/blocks/boundary.js, packages/svelte/src/internal/client/dom/blocks/html.js, packages/svelte/src/internal/client/dom/blocks/snippet.js, packages/svelte/src/internal/client/dom/blocks/svelte-element.js, packages/svelte/src/internal/client/dom/legacy/lifecycle.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/render.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/client/validate.js, packages/svelte/src/legacy/legacy-client.js, packages/svelte/tests/signals/test.ts, packages/svelte/types/index.d.ts
The `runtime.js` module is a mess of all sorts of different concerns. Lately I've had to work in it a fair bit and it's just really hard to keep a mental map of what lives where when the module is so large.
This PR moves all the component-context-related stuff into its own module, as a starting point. (We already do this for server code)
=> chore: move context code into new module

.changeset/curly-balloons-relate.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/has/_config.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/has/input.svelte
Fixes #15027 and fixes #14995
When the target element is inside a block or component, get_following_sibling_elements was looking only for sibling elements after the block/component. This PR fixes it by starting the search from the begging of the block/component and skipping nodes that go before the target element.
Also, I noticed that selector like `.elem:has(+ .not-adjacent-sibling)` isn't marked as unused. [Example](https://svelte.dev/playground/hello-world?version=5.19.2#H4sIAAAAAAAAA22NSwrCMBBArxJm1aKYfQwBPwvvYF00mRELMSnJ-CmldzcB3bl783gzM0Po7wQKTuR9FK-YPIqGcGDCFtZwHTxlUOcZeBprV0Xx363dOG7ykzxXZ_tM_7yLgSlwOQPamr2W1nRBO3PQ0lVCc9QSCxXOPHmqyFbd-tysBLZirnPHLvqYlEiE2yqWkstfX94wvRkUpwctl-UDlGGV1NgAAAA=). Though, it's false negative and isn't that bad.
=> fix: correctly look for sibling elements inside blocks and components

.changeset/blue-rocks-play.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-7/_config.js, packages/svelte/tests/signals/test.ts
Fixes https://github.com/sveltejs/svelte/issues/15111 fully.
This is a follow up to https://github.com/sveltejs/svelte/pull/15129. If a derived is disconnected from the reactivity graph, then it should destroy any child effects/deriveds that it has. Furthermore, instead of blindly attaching a derived to it's original parent derived – we mark it as unowned, as the derived value might have been passed around to other owners since and thus not be associated anymore. For example if you create a class instance (that has derived properties) inside a derived and then pass that elsewhere, it's not technically owner by the original derived anymore.
=> fix: improve derived connection to ownership graph

.changeset/famous-bulldogs-tan.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/has/_config.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/has/input.svelte
Fixes #14910
The issue occurs only when `:has()` targets at a component's root element and because `include_self` is `false`.
I came to the conclusion that this is the same case as `:root:has(.scoped)`.
=> fix: do not prune selectors like `:global(.foo):has(.scoped)`

.changeset/unlucky-gorillas-hunt.md, packages/svelte/src/internal/client/context.js, packages/svelte/src/internal/client/dev/ownership.js
Instead of doing ownership addition at each `getContext` call site, we do it once as the `setContext` call site and make the state basically global.
- avoids potential false positives in edge cases
- makes the whole thing more performant, especially around things like calling `getContext` inside a list item component
- false negatives are unlikely from this (as shown by no current tests failing)
No new test added because this is mainly about performance.
fixes #15072
=> fix: widen ownership when calling setContext

.changeset/ten-cougars-look.md, packages/svelte/src/internal/client/dev/ownership.js
The component identity could change due to HMR, so we fall back to checking the filenames as well
No test because this requires HMR and changes to a file being made.
fixes #14746
=> fix: prevent false-positive ownership validations due to hot reload

documentation/docs/02-runes/04-$effect.md
This is mentioned in the migration to svelte 5 guide, but is not directly mentioned.
> ...where dependencies would be for example moved into a function and no longer be visible as a result
> determining the dependencies at runtime, and therefore being immune to refactorings
https://svelte.dev/docs/svelte/v5-migration-guide#Reactivity-syntax-changes-$:-$derived-$effect
=> [docs] clarify that `$effect` analyzes functions deeply

packages/svelte/src/internal/client/dom/blocks/each.js
This check was added in #13930 but it's not very clear what it does, and no tests fail if we remove it, because `is_inert` is never true (in the test suite, at least). The repro in #13926 is [still fixed in this PR](https://svelte.dev/playground/1841f931f328483283516f946b1a44e0?version=branch-remove-inert-check)
=> chore: remove inert check from each block reconciliation

documentation/docs/03-template-syntax/09-@const.md, documentation/docs/03-template-syntax/11-bind.md, documentation/docs/04-styling/01-scoped-styles.md
---
This PR does the following:
- Adds the missing `>` to `<svelte:boundary` in `03-template-syntax/09-@const.md`
- Fixes the #audio link in `03-template-syntax/11-bind.md`
- Fixes the comment-out in `04-styling/01-scoped-styles.md`
=> docs: fix typos and a link

.changeset/sweet-mails-clean.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/general-siblings-combinator-svelteelement/_config.js, packages/svelte/tests/css/samples/general-siblings-combinator-svelteelement/expected.css, packages/svelte/tests/css/samples/general-siblings-combinator-svelteelement/input.svelte
Fixes #14890
I wonder whether `loop_child` should also return SlotElement and RenderTag like does `get_possible_element_siblings`. I couldn't comprehend or make up a case which requires it but fails.
=> fix: encounter svelte:element in blocks as sibling during pruning css

.changeset/long-moles-join.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/tests/runtime-runes/samples/effect-tracking-unowned/_config.js, packages/svelte/tests/runtime-runes/samples/effect-tracking-unowned/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/15212
I should have changed this in https://github.com/sveltejs/svelte/pull/15137. As deriveds are now technically not owned and we have a dedicated `untracked` flag, we can remove this heuristic entirely. You can still track things inside an unowned derived, because that derived is still technically reactive. We had to do this with https://github.com/sveltejs/svelte/pull/14005 because deriveds were just broken.
=> fix: ensure tracking returns true, even if in unowned

playgrounds/sandbox/index.html, playgrounds/sandbox/package.json, playgrounds/sandbox/scripts/download.js, playgrounds/sandbox/scripts/hash.js, playgrounds/sandbox/ssr-dev.js, playgrounds/sandbox/ssr-prod.js
Copying playgrounds to the sandbox in this repo, for local debugging, is currently a bit of a chore, as is the reverse operation. This PR adds two new scripts. The first one downloads a playground to `playgrounds/sandbox/src` (it will use the hash, if present, and if not get the data from `svelte.dev/playground/api`):
```bash
pnpm download https://svelte.dev/playground/8a021b2ec2064230bde4a10b08464876?version=5.19.7
```
The second hashes the current contents of `playgrounds/sandbox/src` and copies a URL to the clipboard:
```bash
pnpm hash
```
=> chore: add download/hash scripts for sandbox

.changeset/great-planes-swim.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/custom-element-attributes/_config.js, packages/svelte/tests/runtime-runes/samples/custom-element-attributes/main.svelte
Avoid going through the `element.value = element.__value = newValue` condition because `__value` is actually how Lit stores the current value on the element, and messing with that would break things: Lit would think the value hasn't changed (because `__value` is already set to the new value by us) and doesn't fire an update.
fixes #15194
=> fix: properly set `value` property of custom elements

.changeset/light-ligers-switch.md, packages/svelte/src/internal/client/dom/elements/attributes.js
When a custom element is created before Svelte hydration kicks in, it will scaffold itself, using the properties given via attributes. Now when a custom element property is set during Svelte's hydration, the Svelte custom element component could run logic like updating an each block. Without turning off hydration mode during that time, the update would try to pick up existing element nodes (because it thinks they must be there because of hydration mode), and crash.
No test because it would require a setup where we can ensure the element is scaffolded before hydration runs.
Fixes #15213
=> fix: ensure custom element updates don't run in hydration mode

.changeset/wicked-apes-sin.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/hydration/samples/repair-mismatched-a-href/_expected.html, packages/svelte/tests/hydration/samples/repair-mismatched-a-href/main.svelte
We had some duplicated and buggy code, removing it fixes #15120
=> fix: hydrate `href` that is part of spread attributes

.changeset/nasty-pigs-lay.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-12/_config.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-12/main.svelte, packages/svelte/tests/signals/test.ts
Fixes https://github.com/sveltejs/svelte/issues/15229. 
Fixes https://github.com/sveltejs/svelte/issues/15180.
Where we know that an unowned that was temporarily made unowned, and has definitely become owned again, we can remove the unowned flag entirely. This is the inverse of the logic that makes the derived temporarily unowned to begin with.
=> fix: when re-connecting unowned deriveds, remove their unowned flag

packages/svelte/src/internal/client/runtime.js
I might be missing some subtlety relating to effect ordering, but it seems we can simplify `process_effects`, making it non-recursive and removing some indirection. Is there any behaviour that would change with this PR? Avoiding the array allocation and for loop seems like a nice performance win, on top of the simpler code.
=> chore: simplify process_effects

.changeset/fuzzy-zoos-repeat.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/attribute-spread-input/_config.js, packages/svelte/tests/runtime-runes/samples/attribute-spread-input/main.svelte
Fix issue https://github.com/sveltejs/svelte/issues/15237 : "Using spread syntax '{...rest }' with props doesnt work correctly!"
Note : the issue is about the input input text `value`, but there's the same problem with `checked`.
`set_attributes()` use `removeAttributes()` which removes the attribute without impacting the JS state of `value/checked`, so the result is not constant.
This work only on the initial state, but not when the `value/checked` was previously set by JavaScript.
=> The `value/checked` properties must be set explicitly.
Note : I not launched **lint** and all **test**s because it generates strange errors on my config (before any change in the code).
=> fix: value/checked not correctly set using spread

.changeset/thick-carrots-arrive.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/ClassBody.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/internal/client/dev/ownership.js, packages/svelte/src/internal/client/index.js, packages/svelte/tests/runtime-runes/samples/non-local-mutation-with-binding-8/CounterBinding.svelte, packages/svelte/tests/runtime-runes/samples/non-local-mutation-with-binding-8/CounterContext.svelte, packages/svelte/tests/runtime-runes/samples/non-local-mutation-with-binding-8/_config.js, packages/svelte/tests/runtime-runes/samples/non-local-mutation-with-binding-8/main.svelte
- `$derived` can contain `$state` declarations so we cannot ignore them, so this reverts #14533
- instead, we add equality checks to not do this expensive work unnecessarily
- this also adds a render effect similar to the class ownership addition when it detects a getter on a POJO during ownership addition
fixes #15164
=> fix: recurse into `$derived` for ownership validation

documentation/docs/06-runtime/03-lifecycle-hooks.md
The same description is defined in both the docs and type definition:
https://github.com/sveltejs/svelte/blob/a3e49b611094559a2c4f3830dec2cc75680140ab/documentation/docs/06-runtime/03-lifecycle-hooks.md?plain=1#L50-L52
https://github.com/sveltejs/svelte/blob/a3e49b611094559a2c4f3830dec2cc75680140ab/packages/svelte/types/index.d.ts#L361-L368
Since the docs also import the type definition, it resulted in the same content shown twice:
=> docs: remove duplicate `onDestroy` description

.changeset/slow-meals-wait.md, packages/svelte/src/compiler/phases/2-analyze/visitors/Attribute.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/dom/operations.js, packages/svelte/src/internal/client/dom/template.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/_expected/client/index.svelte.js
Closes #15268
Follow up to #15141 ...we now use `importNode` in FF (which based on some test i did in that PR seems to actually be faster in FF) and `cloneNode` in the rest...this also mean we don't have to do the trick we did for `handle_lazy_img` because it was only an issue in FF.
Not sure how to add a test for this.
Also do we have a way to be sure it's not messing with performance in FF?
=> fix: use `importNode` to clone templates for Firefox

.changeset/rare-hounds-wave.md, packages/svelte/src/internal/client/dom/elements/transitions.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js
This should help avoid doing unnecessary work.
=> chore: tweak effect self invalidation logic

.changeset/short-fireants-talk.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte
When transforming TypeScript code, abstract methods were incorrectly included in the generated JavaScript output. Given the following TypeScript code:
```ts
abstract class MyClass {
abstract myMethod(): void;
}
```
The transformation produced invalid JavaScript:
```js
class MyClass {
myMethod()
}
```
This resulted in a syntax error in the browser.
This PR ensures that abstract methods are removed during transformation, so the output JavaScript becomes:
```js
class MyClass {}
```
Resolves #15260
=> fix: ignore typescript abstract methods during code transformation

.changeset/thirty-feet-tap.md, packages/svelte/src/internal/server/index.js, packages/svelte/src/internal/server/types.d.ts, packages/svelte/tests/server-side-rendering/samples/head-component-props-id/HeadNested.svelte, packages/svelte/tests/server-side-rendering/samples/head-component-props-id/_config.js, packages/svelte/tests/server-side-rendering/samples/head-component-props-id/main.svelte
=> fix: correctly ssr component in `svelte:head` with `$props.id()` or `css='injected'`

packages/svelte/src/internal/client/dom/template.js, packages/svelte/tests/runtime-legacy/shared.ts, packages/svelte/tests/runtime-runes/samples/props-id/_config.js, packages/svelte/tests/runtime-runes/samples/props-id/main.svelte
Currently tests for `$props.id` are a bit brittle because the id will be shared between all tests...this means that if we add a new test that uses `$props.id` before the current test the old test will fail for apparently no reason. This can be very confusing so we definitely need to fix this.
I changed the test to make sure that all the ids are different and in hydrate mode i've also cut the numbers out and checked that the first ones starts with `s` meaning they are the same as the server. I don't know if this is the right approach but it's the only one i could think of to actually test that the values comes from the server.
cc @adiguba maybe is worth for you to take a look at this.
=> chore: fix `$props.id` tests

.changeset/good-spiders-own.md, packages/svelte/src/compiler/phases/2-analyze/index.js
This was the result of a `@ts-expect-error` silencing other type errors, which lead to this creeping in. This changes it so that the object is fully set, so we'll get type errors when new properties need to be added
fixes #15284
=> fix: ensure AST analysis on `svelte.js` modules succeeds

packages/svelte/tests/preprocess/test.ts
The tests are spitting out lots of warnings that this line will error with vitest 3
=> chore: add missing await in tests

.changeset/little-laws-sit.md, packages/svelte/src/compiler/phases/3-transform/client/types.d.ts, packages/svelte/src/compiler/phases/3-transform/client/visitors/EachBlock.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/tests/runtime-runes/samples/each-bind-store-no-warning/_config.js, packages/svelte/tests/runtime-runes/samples/each-bind-store-no-warning/main.svelte
=> fix: do not warn for `binding_property_non_reactive` if binding is a store in an each

documentation/docs/03-template-syntax/11-bind.md
Just two small corrections in example that generate the `element_invalid_self_closing_tag` warning.
=> docs: fix two element_invalid_self_closing_tag warning in example

.changeset/wicked-apples-yawn.md, packages/svelte/src/internal/client/dom/elements/events.js
The DOM could've been updated already by the time the event bubbling logic is reached, so the target element itself could not be notified of the event because it is marked as disabled. But the target could not have been disabled because it emits the event in the first place, so we emit regardless.
No test because not reproducible in jsdom environment.
Fixes #15256
=> fix: fire delegated events on target even it was disabled in the meantime

packages/svelte/src/internal/client/runtime.js
`root_effects` doesn't do anything. it's always identical to `queued_root_effects`
=> chore: simplify flush_sync

LICENSE.md
This PR updates the copyright holder in the `LICENSE.md` file from "these people" to "Svelte Contributors". This change is considered more formal and follows common best practices seen in most open-source repos.
However, there are other alternatives worth mentioning:
- Acknowledging Rich Harris for creating Svelte: "Rich Harris and Svelte Contributors" (similar to how the Vue repo uses "Yuxi (Evan) You and Vue contributors").
- Acknowledging the Svelte Team for maintaining the project: "Svelte Team" (similar to how Nuxt uses "Nuxt Team"). This can also be combined with contributors: "Svelte Team and Contributors"
The capitalisation of "Contributors" is intended to show respect and to indicate it as a defined term, similar to how "You" is treated in the Apache 2.0 license.
=> docs: rephrase copyright holder

.changeset/serious-glasses-kiss.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js
`?? ''` is automatically added to the end of all template variables.
This PR just handle some cases where it is not necessary, like binary operators or some unary operator (except void & delete)
=> chore: remove unnecessary `?? ''` on some expressions

packages/svelte/src/compiler/phases/scope.js, packages/svelte/src/compiler/types/index.d.ts, packages/svelte/types/index.d.ts
Before we can tackle things like https://github.com/sveltejs/svelte/pull/15292#issuecomment-2675281669 we will need to add logic to bindings. The obvious thing to do is replace the `Binding` interface with a class.
For now, this doesn't change anything beyond that, though you can imagine adding methods like `get_possible_values` or `is_reactive` and so on in future.
=> chore: make Binding a class

packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/ExportSpecifier.js, packages/svelte/src/compiler/phases/scope.js
This makes the definition of `binding.updated` clearer, and makes it impossible for it to be out of sync with `binding.mutated` and `binding.reassigned`, even if we reassign/mutate in more places in future
=> chore: create `binding.updated` getter

.changeset/green-geckos-tickle.md, packages/svelte/src/compiler/phases/2-analyze/visitors/Attribute.js, packages/svelte/src/compiler/phases/2-analyze/visitors/CallExpression.js, packages/svelte/src/compiler/phases/2-analyze/visitors/TaggedTemplateExpression.js, packages/svelte/src/compiler/phases/scope.js
Ostensibly, this property exists to prevent event handlers being incorrectly used for delegation (since that changes their signature, meaning the original call would no longer be valid). But that's already taken care of by this check:
https://github.com/sveltejs/svelte/blob/3c4a8d425b8192dc11ea2af256d531c51c37ba5d/packages/svelte/src/compiler/phases/2-analyze/visitors/Attribute.js#L154-L156
It's therefore not doing anything useful and can be removed
=> chore: remove unnecessary `binding.is_called` property

.changeset/mighty-dryers-smoke.md, .changeset/violet-camels-heal.md, benchmarking/benchmarks/reactivity/kairo/kairo_avoidable.js, benchmarking/benchmarks/reactivity/kairo/kairo_broad.js, benchmarking/benchmarks/reactivity/kairo/kairo_deep.js, benchmarking/benchmarks/reactivity/kairo/kairo_diamond.js, benchmarking/benchmarks/reactivity/kairo/kairo_mux.js, benchmarking/benchmarks/reactivity/kairo/kairo_repeated.js, benchmarking/benchmarks/reactivity/kairo/kairo_triangle.js, benchmarking/benchmarks/reactivity/kairo/kairo_unstable.js, benchmarking/benchmarks/reactivity/mol_bench.js, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/index-client.js, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/src/internal/client/dom/task.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/legacy/legacy-client.js, packages/svelte/tests/runtime-legacy/samples/animation-css/_config.js, packages/svelte/tests/runtime-legacy/samples/animation-js-easing/_config.js, packages/svelte/tests/runtime-legacy/samples/animation-js/_config.js, packages/svelte/tests/runtime-legacy/samples/dynamic-element-animation/_config.js, packages/svelte/tests/store/test.ts, packages/svelte/types/index.d.ts
I suspected our flushing logic was unnecessarily baroque, and on closer inspection it looks like we can simplify it quite a bit. This PR does so: it gets rid of the `scheduler_mode` stuff in favour of just flushing the root effect queue until it's empty. This means a) we don't need to mess around with microtasks (theoretically this will improve performance for updates that spawn further updates, though it's unlikely to be measurable) and b) we don't need to do any book-keeping to prevent infinite loops — we just... put everything in a loop.
We can also get rid of the `process_deferred` middleman, and lose a now-unnecessary try-finally block.
Due to the vagaries of the `Animation` shim we use in the test suite, this does necessitate a couple of harmless edits to a handful of tests.
I also …
=> chore: simplify flushing

.changeset/lemon-cougars-buy.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/element.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/element.js, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/dom/elements/class.js, packages/svelte/tests/runtime-runes/samples/class-directive-mutations/_config.js, packages/svelte/tests/runtime-runes/samples/class-directive-mutations/main.svelte
* Closes #15386
* Remove useless cssHash when using spreading on a not-scoped element.
I updated the previous test to include speading, and I noticed that spreading adds the cssHash on all elements, even those that are not "scoped".
=> fix: class:directive not working with $$restProps

packages/svelte/src/internal/client/runtime.js
no need for the `main_loop` label, we can make things simpler. also changes some variable names to be more compact and descriptive
=> chore: simplify `process_effects`

.changeset/hip-oranges-hang.md, documentation/docs/98-reference/.generated/compile-errors.md, packages/svelte/messages/compile-errors/template.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/visitors/BindDirective.js, packages/svelte/tests/validator/samples/bind-group-snippet-parameter/errors.json, packages/svelte/tests/validator/samples/bind-group-snippet-parameter/input.svelte
Closes #15037
Alternative to #15040
=> fix: disallow `bind:group` to snippet parameters

.changeset/gentle-humans-call.md, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/a11y.js, packages/svelte/tests/validator/samples/a11y-no-noninteractive-element-interactions/input.svelte, packages/svelte/tests/validator/samples/a11y-no-noninteractive-element-interactions/warnings.json
Fixes https://github.com/sveltejs/svelte/issues/8283
I want to use native `dialog` elements. A common pattern for modal dialogs is dismissing them by clicking on the backdrop pseudo-element. This is achieved by assigning a click event handler to the dialog itself. Svelte is perfect for this task. Except Svelte raises a warning (`a11y_no_noninteractive_element_interactions`) about adding a click event handler to the dialog element, because Svelte treats it as non-interactive. This is what I want to change.
Svelte considers elements non-interactive if they don’t have a `widget` superclass and their roles are not `toolbar`, `tabpanel`, `cell`, or `generic`. The dialog-related roles are `dialog` and `alertdialog`, [both of them having a superclass …
=> fix: make dialog element and role interactive

.changeset/selfish-cougars-allow.md, packages/svelte/package.json, packages/svelte/src/compiler/phases/1-parse/acorn.js, packages/svelte/src/compiler/phases/1-parse/ambient.d.ts, packages/svelte/tests/parser-modern/samples/comment-before-script/output.json, packages/svelte/tests/parser-modern/samples/snippets/output.json, packages/svelte/tests/parser-modern/samples/typescript-in-event-handler/output.json, packages/svelte/tsconfig.json, pnpm-lock.yaml
Since the original library is abandoned, we had to fork it and continue maintenance there.
This PR switches out the package to https://github.com/sveltejs/acorn-typescript
The two notable changes from this are:
- no more "fix the TS AST afterwards" walk, might speed up things a tiny bit
- the `end` of a `Pattern` now also includes the type annotation, i.e. `const msg: boolean = true` will not have `end: 9` but `end: 18`
=> fix: switch to our fork acorn typescript plugin

package.json, pnpm-lock.yaml
upgrades `eslint-plugin-n` to get a big speedup from https://github.com/eslint-community/eslint-plugin-n/issues/404
=> chore: speed up linting

documentation/docs/02-runes/01-what-are-runes.md
The intro docs page for runes includes a flavor-text dictionary entry for "rune".
https://svelte.dev/docs/svelte/what-are-runes
This seems to have some special/invalid character, which is displayed differently in different browsers:
| Browsers |
|--------|
| Chromium <br/><img width="569" alt="Screenshot 2025-03-04 at 8 40 44 PM" src="https://github.com/user-attachments/assets/27d93f9f-df8d-4d48-8575-7a26cc27feed" /> |
| Firefox <br/><img width="569" alt="Screenshot 2025-03-04 at 8 42 52 PM" src="https://github.com/user-attachments/assets/f4b2d2af-b58c-4e96-bf49-020bd834e7fb" /> |
| Safari <br/><img width="569" alt="Screenshot 2025-03-04 at 8 42 59 PM" src="https://github.com/user-attachments/assets/9d36945d-739e-45ca-836f-1d56d0f1190c" /> | 
This should be switched to something that …
=> docs: fix 'rune' phonetic spelling

documentation/docs/03-template-syntax/01-basic-markup.md
`01-basic-markup.md` was using an old svelte-ignore syntax with dashed rule names (`a11y-autofocus`). I fixed it with a underscored one (`a11y_autofocus`).
There is no old-syntaxed `svelte-ignore` in the docs anymore.
=> docs: Update 01-basic-markup.md with new svelte-ignore syntax

.changeset/shy-falcons-occur.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/effect-root-5/_config.js, packages/svelte/tests/runtime-runes/samples/effect-root-5/main.svelte, packages/svelte/tests/runtime-runes/samples/toStore-teardown/_config.js, packages/svelte/tests/runtime-runes/samples/toStore-teardown/child.svelte, packages/svelte/tests/runtime-runes/samples/toStore-teardown/main.svelte
Alternative to #15439. Fixes #15426
=> fix: run effect roots in tree order

.changeset/real-cameras-attack.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/style-update/_config.js, packages/svelte/tests/runtime-runes/samples/style-update/main.svelte
* Closes #15309
When we pass the style value directly, `set_attribute()` is used.
But with spreading, it was set by an assign on `element.style.cssText` (or `node[prop]` for custom-element).
This cause the text to be parsed/corrected by the browser, and the value of the attribute will be different.
With this fix, spreading also use `set_attribute()` for style.
=> fix: spreading style is not consistent with attribute

.changeset/metal-spoons-scream.md, packages/svelte/elements.d.ts
This PR adds support for the new `closedby` attribute to the `dialog` element, by adding definitions for it and it's enumerated values in the element types (`HTMLDialogAttributes`).
Spec: https://html.spec.whatwg.org/#attr-dialog-closedby
=> feat: Add `closedby` to `HTMLDialogAttributes` (dialog element)

.changeset/hungry-monkeys-fly.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/CallExpression.js
To make `console.log(some_state)` more useful, we transform it to this, which prints a snapshot of the state along with instructions on how to do it yourself:
```js
console.log(...$.log_if_contains_state('log', some_state));
```
There's no need to do this if you're just doing `console.log('HERE')` or `console.log('WHY WONT THIS WORK')` or whatever. There are doubtless other cases we could similarly optimise but literals are the obvious place to start
=> fix: skip `log_if_contains_state` if only logging literals

packages/svelte/src/compiler/phases/2-analyze/visitors/Attribute.js, packages/svelte/src/compiler/phases/scope.js
I added an `is_function` method on `Binding` in #15460. Turns out there's at least one more place we can use it. I also added some TypeScript trickery ([thanks for the assist, v0](https://v0.dev/chat/type-narrowing-in-type-script-XmHkOfWgYwx)) so that you can type narrowing when you use it
=> chore: reuse is_function helper

.github/workflows/pkg.pr.new-comment.yml
I noticed this job fail on one of my PRs
https://github.com/sveltejs/svelte/actions/runs/13740490010
=> chore: add missing permissions for `pkg.pr.new-comment`

documentation/docs/06-runtime/03-lifecycle-hooks.md
This is my first contribution to the Svelte project. 
Fix for [Issue #15404](https://github.com/sveltejs/svelte/issues/15404) where the theme toggle callback function in the lifecycle hooks documentation was using an undefined `toggleValue` variable.
- Modified the `toggle()` function to correctly toggle the theme state variable
- Changed from using undefined `toggleValue` to properly using the existing `theme` variable
- Made the implementation match the 'After' playground example code
Verified that the modified example code is now consistent with the correct implementation shown in the "After" playground link.
This PR ensures that users following the documentation won't encounter undefined variable errors when implementing dark mode toggling.
Fixes #15404
=> docs: correct toggle function in lifecycle hooks example

.changeset/sharp-elephants-invite.md, packages/svelte/src/compiler/phases/2-analyze/visitors/CallExpression.js, packages/svelte/src/internal/client/context.js, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/client/types.d.ts, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access-2/Component.svelte, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access-2/_config.js, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access-2/main.svelte, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access-3/Component.svelte, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access-3/_config.js, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access-3/main.svelte, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access/Component.svelte, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access/_config.js, packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access/main.svelte, packages/svelte/tests/runtime-runes/samples/nested-effect-conflict/_config.js
Today, if you read some state inside a teardown function, you get the _latest_ state:
```js
const prev = value;
return () => {
// could be `true` but is usually `false`, depending on
// whether the teardown is running because the effect
// is about to re-run (because `value` changed) or
// because it's being destroyed (because the
// component unmounted, for example)
console.log(prev === value); 
};
});
```
This is counter-intuitive to many people, especially those coming from React, since this is perhaps the one place where stale closures _don't_ make things more confusing:
```js
const [value, setValue] = useState(...);
useEffect(() => {
const prev = value;
return () => {
console.log(prev === value);
};
});
```
On one level, this is just how signals work. The same …
=> fix: on teardown, use the last known value for the signal before the set

.changeset/plenty-bats-lay.md, packages/svelte/elements.d.ts
This adds missing `files` and `group` properties to match the respective `bind:files` and `bind:group`.
Unless I'm mistaken, it seems that the `files` and `group` attributes are missing from the HTMLInputAttributes type in [element.d.ts](https://github.com/sveltejs/svelte/blob/dbd4617ac42a4bf5e97af05f2d5bc6a0517e24b2/packages/svelte/elements.d.ts#L1069-L1124).
The typings for the binding 'bind:group' and 'bind:files' are present (as [seen here](https://github.com/sveltejs/svelte/blob/main/packages/svelte/elements.d.ts#L1119-L1121)) but the individual properties aren't.
Note that the bindings exists on [the deprecated ](https://github.com/sveltejs/language-tools/blob/02db54de1f2fc44d958d67113a9d0fb41a8f6fe7/packages/svelte2tsx/svelte-jsx.d.ts#L1192-L1196) `SvelteInputProps`, so maybe this …
=> fix: Add files and group properties to HTMLInputAttributes

.changeset/brown-rockets-shake.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/untracked-write-pre/_config.js, packages/svelte/tests/runtime-runes/samples/untracked-write-pre/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/15499. We need to ensure that if there was a previous active reaction and we have untracked writes, that we propagate those writes to that reaction too.
=> fix: ensure transient writes to tracked parent effects works as expected

documentation/docs/07-misc/99-faq.md
when searching for [`tsx`](https://svelte.dev/search?q=tsx) on the main site. One reference appears. I switched it to a more appropriate language identifier.
=> docs: remove random reference to tsx

.changeset/hungry-dancers-tap.md, packages/svelte/package.json
results in a smaller package. don't need to distribute unused files
this may close (or not, we'll see) https://github.com/sveltejs/svelte/issues/15182
=> chore: don't distribute unused types definitions

.changeset/gold-hairs-jog.md, packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/tests/css/samples/view-transition/expected.css, packages/svelte/tests/css/samples/view-transition/input.svelte
For instance, specifying a tree-structural pseudo-class to `::view-transition-new` should still constitute a valid global-like selector.
Fixes #15312
---
This PR tweaked some tests, which wouldn't pass before but do now; however they're far from being exhaustive, as I'm sure this needs a little bit of thinking.
Secondly, this PR introduced a fix that's certainly way too broad in scope, additionally and "accidentally" allowing `:host` as well to be re-specified. Frankly, there may be quite a bit to discuss there.  
Or we can start by having a specific exception for `:only-child` only, and solely for `::view-transition-new()` and `::view-transition-old()`, as at least these combinations seem to be legitimate.
`pnpm test` went fine; the linting one failed to run... but it's nearly midnight …
=> fix: Allow global-like pseudo-selectors refinement

.changeset/cuddly-chefs-refuse.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/has/_config.js, packages/svelte/tests/css/samples/has/expected.css, packages/svelte/tests/css/samples/has/input.svelte, packages/svelte/tests/css/samples/render-tag-loop/_config.js, packages/svelte/tests/css/samples/render-tag-loop/expected.css, packages/svelte/tests/css/samples/render-tag-loop/input.svelte
Fixes #14072, alternative of #15207
`:has()` was matching only against descendants or siblings, but not sibling's descendants.
In this variant, I made `apply_selector` and related functions bidirectional. So the same logic can be applied to all selectors.
Changing the direction for selectors passed into `:has()` broke `p:has(+ y)` for the test `has-with-render-tag` and to fix it I added diving into the `@render()` tags during gathering siblings, which fixed the `render-tag-loop` test.
I also tried to cache the function retrieving neighbor elements and got the following cache hits rates on the test cases:
descendant_forward: 94,23%
descendant_backward: 55,91%
children_forward: 84,00%
children_backward: 33,51%
sibling_forward: 69,42%
sibling_backward: 59,94%
next_forward: 41,40% …
=> fix: correctly match `:has()`'s selector during css pruning

documentation/docs/98-reference/.generated/client-errors.md, packages/svelte/messages/client-errors/errors.md
=> docs: add docs on state_unsafe_mutation error

documentation/docs/07-misc/07-v5-migration-guide.md
Hi, sorry if I didn't submit an issue first--I think this is a small enough change that it's not exactly warranted. I just wanted to switch to nicer looking arrows for aesthetic reasons.
From this:
To this:
Somewhat related, I'm baffled over why this code outputs the way it does. The code seems correct, but it still adds the 'count' when it shouldn't. Found in the same file. I know it's a minor thing, but still 🫤
=> docs: updated -> to  → in v5-migration-guide

documentation/docs/07-misc/07-v5-migration-guide.md
=> chore: tweak migration doc diff blocks

.changeset/thick-pans-fold.md, packages/svelte/src/compiler/phases/2-analyze/visitors/Attribute.js, packages/svelte/tests/runtime-runes/samples/unhoist-function-accessing-snippet/_config.js, packages/svelte/tests/runtime-runes/samples/unhoist-function-accessing-snippet/main.svelte
=> fix: don't hoist listeners that access non hoistable snippets

documentation/docs/02-runes/04-$effect.md
Function bindings allow us to simplify the examples in 'when not to use effect' quite a bit
=> docs: use function bindings in "when not to use effect"

documentation/docs/06-runtime/02-context.md
Noticed while reviewing #15533 — our context docs are really rather strange:
- they talk exclusively about state, when oftentimes context doesn't involve state at all (see the [tutorial](https://svelte.dev/tutorial/svelte/context-api) for example)
- it doesn't even talk about context until you get below the fold (and inexplicably puts the first mention inside backticks). Instead it talks awkwardly about global state and talks vaguely about 'drawbacks' without illustrating what the supposed danger is
- 'slotted content'
- it doesn't explain how reassigning context breaks the link, which is the main thing people have run into
In short it needed a complete rewrite
=> docs: rewrite context docs

packages/svelte/src/internal/client/proxy.js
no point creating this if `value` is a primitive or an existing state proxy
=> chore: create stack lazily when proxying value

.changeset/nine-laws-rush.md, packages/svelte/src/compiler/phases/3-transform/client/types.d.ts, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/AssignmentExpression.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/ClassBody.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/declarations.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/snapshot/samples/bind-component-snippet/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/class-state-field-constructor-assignment/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/destructured-assignments/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/function-prop-no-getter/_expected/client/index.svelte.js
See https://github.com/sveltejs/svelte/pull/15069#issuecomment-2737452999
=> fix: simplify set calls for proxyable values

.changeset/happy-cameras-bow.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/jsdoc-with-comments/input.svelte, packages/svelte/tests/migrate/samples/jsdoc-with-comments/output.svelte
This addresses trailing inlined JSDoc property descriptions being deleted by svelte-migrate, see #15530.
Previously:
```js
/** @type {number} [comment_default_value=1] - This has a comment and a default value. */
export let comment_default_value = 1;```
```
The comment would be removed in the migrated version:
```js
/**
* @typedef {Object} Props
* @property {number} [comment_default_value].
*/
/** @type {Props} */
let { comment_default_value = 1 } = $props();
```
With the change in this PR it becomes the following:
```js
/**
* @typedef {Object} Props
* @property {number} [comment_default_value] - This has a comment and a default value.
*/
/** @type {Props} */
let { comment_default_value = 1 } = $props();
```
The default value description in the JSDoc is still removed, but that's probably …
```
=> fix: Keep inlined JSDoc comments in property conversion of svelte-migrate

.changeset/young-poets-wait.md, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/effect-cleanup/_config.js, packages/svelte/tests/runtime-runes/samples/untrack-own-deriveds/_config.js, packages/svelte/tests/runtime-runes/samples/untrack-own-deriveds/main.svelte, packages/svelte/tests/signals/test.ts
Follow-up to #15553 which fixes [this case](https://github.com/sveltejs/svelte/pull/15300#issuecomment-2660814372).
Unfortunately it changes the behaviour of effects in a way that could be considered breaking — in a case like this, where a derived that's local to an effect depends on state _outside_ the effect...
```js
let count = $state(0);
let double = $derived(count * 2)
console.log('init ' + double);
return function() {
console.log('cleanup ' + double);
console.log(this);
};
});
```
...today the effect will re-run when `count` changes, but in this PR it won't. I'm not sure there's a way to have that behaviour _and_ have effects not depend on deriveds that depend entirely on local state. I _think_ this is the right trade-off, but I'd love to hear from other maintainers.
=> fix: don't depend on deriveds created inside the current reaction

packages/svelte/src/compiler/migrate/index.js
this is causing lint failures on unrelated PRs
=> chore: camelCase -> snake_case

.changeset/twelve-bananas-destroy.md, packages/svelte/src/store/index-client.js, packages/svelte/tests/runtime-runes/samples/toStore-subscribe2/_config.js, packages/svelte/tests/runtime-runes/samples/toStore-subscribe2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/15557
=> fix: ensure toStore root effect is connected to correct parent effect

documentation/docs/98-reference/.generated/client-errors.md, packages/svelte/messages/client-errors/errors.md
Follow-up to #14932. I had expressed concerns about the example being a bit confusing (since it involves cyclicality, which is likely a red herring in most scenarios) but I also think we can explain the rationale more clearly. 'The reactive graph could become unstable' is a bit in-the-weeds; we can express it more concretely. We can also provide an example of how to fix it by turning the assigned state into a derived.
=> docs: update state_unsafe_mutation message

.changeset/afraid-penguins-battle.md, packages/svelte/src/internal/client/proxy.js
closes #15546
More details in the connected issue, but the TL;DNR version is that when running the dev server, the `init_array_prototype_warnings` function causes problems with the iframe/JavaScript interactions for 3rd party integrations, such as with Recurly and other payment providers. This is caused because the check for a proxied value involves passing the `value` to check if it exists within. 
By simply wrapping the `get_proxied_value` function in a `try/catch`, we avoid the problem of halting the JS run by the 3rd party script on the iframe it controls.
I intended to write a test for this function, but it appears that the existing proxy test file only runs tests against the `proxy` function. I can still do that, but it seemed out of keeping with the patterns I see in the code base …
=> fix: allow get_proxied_value to return original value when error

.changeset/forty-snakes-lay.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/reassigned-deriveds/input.svelte, packages/svelte/tests/migrate/samples/reassigned-deriveds/output.svelte
Since now deriveds are writable we can properly migrate even reassigned labeled statements...i did add a check for the version so that in older versions we migrate to compatible code but maybe that's unnecessary?
Also i still migrate this
```ts
$: something = 43;
```
to state because it's better.
=> feat: migrate reassigned deriveds to `$derived`

packages/svelte/src/compiler/migrate/index.js
Since the migration ships with `svelte` there's no need to check for the version.
=> chore: revert version check in migrate

.changeset/nice-pianos-punch.md, documentation/docs/98-reference/.generated/compile-errors.md, packages/svelte/messages/compile-errors/script.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/visitors/CallExpression.js, packages/svelte/tests/validator/samples/rune-invalid-spread-derived-by/errors.json, packages/svelte/tests/validator/samples/rune-invalid-spread-derived-by/input.svelte, packages/svelte/tests/validator/samples/rune-invalid-spread-derived/errors.json, packages/svelte/tests/validator/samples/rune-invalid-spread-derived/input.svelte, packages/svelte/tests/validator/samples/rune-invalid-spread-state-raw/errors.json, packages/svelte/tests/validator/samples/rune-invalid-spread-state-raw/input.svelte, packages/svelte/tests/validator/samples/rune-invalid-spread-state/errors.json, packages/svelte/tests/validator/samples/rune-invalid-spread-state/input.svelte
This will make #15579 safer...is technically a breaking but we are probably safe from this.
=> fix: prevent state runes from being called with spread

documentation/docs/01-introduction/02-getting-started.md
I've seen a really depressing number of people saying you can't build a SPA with SvelteKit. Some portion of that may be due to https://github.com/sveltejs/kit/issues/12580, which I'm working on, but I also think some of it is just ignorance or confusion. I'm hoping this change will help on the education side
=> docs: clarify what you can build with SvelteKit

.changeset/weak-knives-battle.md, packages/svelte/src/internal/client/dom/elements/class.js, packages/svelte/tests/css/samples/undefined-with-scope/expected.html, packages/svelte/tests/css/samples/undefined-with-scope/input.svelte
=> fix: ensure `undefined` class still applies scoping class, if necessary

.changeset/rare-falcons-admire.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/AssignmentExpression.js, packages/svelte/tests/html_equal.js, packages/svelte/tests/runtime-runes/samples/proxy-coercive-assignment-warning/_config.js, packages/svelte/tests/runtime-runes/samples/proxy-coercive-assignment-warning/main.svelte
=> fix: silence assignment warning on more function bindings

.changeset/pink-lamps-leave.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/ClassBody.js
Fixes #15621 by adding a setter to `$derived` class fields.
=> fix: add setter to `$derived` class fields

.changeset/kind-elephants-behave.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/onmount-prop-access/Component.svelte, packages/svelte/tests/runtime-runes/samples/onmount-prop-access/_config.js, packages/svelte/tests/runtime-runes/samples/onmount-prop-access/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/15606. We were calling `old_values.clear()` in the wrong place!
=> fix: ensure clearing of old values happens independent of root flushes

packages/svelte/src/compiler/phases/3-transform/client/transform-template/index.js, packages/svelte/src/compiler/phases/3-transform/client/transform-template/to-functions.js, packages/svelte/src/internal/client/dom/operations.js, packages/svelte/src/internal/client/dom/template.js, packages/svelte/tests/snapshot/samples/await-block-scope/_expected/client-functional/index.svelte.js, packages/svelte/tests/snapshot/samples/bind-component-snippet/_expected/client-functional/index.svelte.js, packages/svelte/tests/snapshot/samples/dynamic-attributes-casing/_expected/client-functional/main.svelte.js, packages/svelte/tests/snapshot/samples/hello-world/_expected/client-functional/index.svelte.js, packages/svelte/tests/snapshot/samples/hmr/_expected/client-functional/index.svelte.js, packages/svelte/tests/snapshot/samples/nullish-coallescence-omittance/_expected/client-functional/index.svelte.js, packages/svelte/tests/snapshot/samples/purity/_expected/client-functional/index.svelte.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/_expected/client-functional/index.svelte.js, packages/svelte/tests/snapshot/samples/state-proxy-literal/_expected/client-functional/index.svelte.js, packages/svelte/tests/snapshot/samples/text-nodes-deriveds/_expected/client-functional/index.svelte.js
Note, this PR is against #15538 
You can use this [playground link](https://svelte-dev-git-templating-mode-selector-svelte.vercel.app/playground/hello-world?version=pr-15599) if you want to play around with the output.
It's implementing a version of the comment from @Rich-Harris https://github.com/sveltejs/svelte/pull/15538#issuecomment-2744437678 that moves the logic to invoke the function to the runtime instead of build time. Basically instead of actually creating the body of an arrow function this create a structure that `template_fn` can convert to a series of functional calls. Specifically the structure looks like this
```ts
type TemplateStructure = {
/** the element name */
e: string, 
/** if defined the custom element that the element extends */
is?: string,
/** all the attributes …
```
=> chore: alterative functional templating syntax

.changeset/pretty-dingos-unite.md, packages/svelte/src/internal/client/runtime.js
Fixes https://github.com/sveltejs/svelte/issues/15690. During `process_effects` we always set the `active_reaction` to be that of the effect which means that we were missing a guard for checking if that was the case.
=> fix: address untracked_writes memory leak

documentation/docs/02-runes/08-$host.md
This adds a link from the docs for the `$host` directive to the docs for custom elements. Custom elements are introduced much later, so a link forwards would help someone who is reading the docs sequentially.
=> docs: add link from $host directive docs to custom elements docs

.changeset/clever-news-enjoy.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/sources.js
closes #15529 (see https://github.com/sveltejs/svelte/pull/15529#issuecomment-2729138326)
=> fix: allow `$.state` and `$.derived` to be treeshaken

.changeset/stupid-vans-draw.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/global-with-nesting/expected.css, packages/svelte/tests/css/samples/global-with-nesting/input.svelte
Fixes #14616
Personal though: I think RelativeSelector with `:global()` must contain nothing else (exceptions are `:not()` and `:has()`) because it is ambiguous whether the part outside `:global()` should be scoped, and if yes, what is the point of `:global()` then. But it will be a breaking change.
=> fix: better scope `:global()` with nesting selector `&`

.changeset/nervous-kids-shake.md, packages/svelte/src/internal/client/constants.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
=> fix: set deriveds as `CLEAN` if they are assigned to

documentation/docs/03-template-syntax/13-transition.md
I got caught up wondering why my transition wasn't working - and it was because I needed a global transition. As currently written, the sentence: 
> A transition is triggered by an element entering or leaving the DOM as a result of a state change.
Makes it sound like transitions are always triggered by elements entering/leaving the DOM - however, that is only true for global transitions, which are not the default. I took a stab at clarifying this, and raising the importance of this by moving up the local/global section to the first paragraph. I created a dedicated section for 'Global Transitions' which contains the example, and I added an explanation of how to actually specify `|global`
=> docs: raise importance of global vs local transitions

documentation/docs/01-introduction/04-svelte-js-files.md, documentation/docs/02-runes/02-$state.md
=> docs: explain restriction on exporting reassigned state

.changeset/pretty-planes-visit.md, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-runes/samples/writable-derived-2/_config.js, packages/svelte/tests/runtime-runes/samples/writable-derived-2/main.svelte, packages/svelte/tests/runtime-runes/samples/writable-derived-2/util.svelte.js
Fixes https://github.com/sveltejs/svelte/issues/15721. We needed to increment the version after we execute the derived.
=> fix: improve internal_set versioning mechanic

.changeset/weak-doors-yell.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/labeled-statement-reassign-state/input.svelte, packages/svelte/tests/migrate/samples/labeled-statement-reassign-state/output.svelte
=> fix: don't transform reassigned state in labeled statement in `$derived`

.changeset/stale-gorillas-judge.md, documentation/docs/98-reference/.generated/compile-warnings.md, packages/svelte/messages/compile-warnings/script.md, packages/svelte/src/compiler/phases/2-analyze/visitors/Identifier.js, packages/svelte/src/compiler/warnings.js, packages/svelte/tests/validator/samples/static-state-reference/input.svelte, packages/svelte/tests/validator/samples/static-state-reference/warnings.json
alternative to #15171. closes #11883, closes #13079.
In addition to tweaking the message (and suggesting a derived instead of a closure when the reference is inside a `$state` declaration, per https://github.com/sveltejs/svelte/pull/15171#issuecomment-2672302931) it tweaks the detailed description the message links to.
=> fix: update `state_referenced_locally` message

.changeset/angry-mayflies-matter.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/SnippetBlock.js, packages/svelte/src/internal/client/dev/validation.js, packages/svelte/tests/runtime-runes/samples/validate-undefined-snippet-default-arg/_config.js, packages/svelte/tests/runtime-runes/samples/validate-undefined-snippet-default-arg/main.svelte
Closes #15749
Technically we could've avoid all the fallback_idx conundrum and just allow undefined too but this should be more correct most of the times and it's not really a problem since it's mostly in dev. I also thought of using a `Set` instead of an array but it's not really worth it since there will never be a lot of params anyway.
=> fix: correctly validate `undefined` snippet params with default value

.changeset/dirty-zebras-do.md, packages/svelte/src/internal/server/dev.js, packages/svelte/src/internal/server/payload.js, packages/svelte/tests/runtime-runes/samples/head-payload-validation/_config.js, packages/svelte/tests/runtime-runes/samples/head-payload-validation/main.svelte
Closes #15753
We could've changed the validation to use something else in case of `head` but i thought it would've been nicer to just refactor the head payload to be a class too (also with a nice `clone` method) so we could check `instanceof`.
=> fix: correctly validate head snippets on the server

documentation/docs/02-runes/05-$props.md, documentation/docs/03-template-syntax/01-basic-markup.md
=> docs: add some missing details around string coercion and handling of nullish values

documentation/docs/03-template-syntax/06-snippet.md
This is an alternative to #15172, which feels a little duplicative to me. Splitting the section up into three subsections makes it easier to scan for the example you're looking for while keeping the linear flow. Closes #14020, Closes https://github.com/sveltejs/svelte/pull/15172
[preview link](https://svelte-dev-git-preview-svelte-15745-svelte.vercel.app/docs/svelte/snippet#Passing-snippets-to-components)
=> docs: headers for snippet prop section

.changeset/green-starfishes-shave.md, documentation/docs/98-reference/.generated/compile-errors.md, packages/svelte/messages/compile-errors/style.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/compiler-errors/samples/css-global-block-multiple-1/_config.js, packages/svelte/tests/compiler-errors/samples/css-global-block-multiple-1/main.svelte, packages/svelte/tests/compiler-errors/samples/css-global-block-multiple-2/_config.js, packages/svelte/tests/compiler-errors/samples/css-global-block-multiple-2/main.svelte, packages/svelte/tests/compiler-errors/samples/css-global-block-multiple/_config.js, packages/svelte/tests/compiler-errors/samples/css-global-block-multiple/main.svelte, packages/svelte/tests/css/samples/global-block/_config.js, packages/svelte/tests/css/samples/global-block/expected.css, packages/svelte/tests/css/samples/global-block/input.svelte
We have to allow `:global x, :global y` selector lists because CSS preprocessors might generate that from `:global { x, y {...} }`
=> fix: relax `:global` selector list validation

.changeset/selfish-onions-begin.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/utils.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/snapshot/samples/nullish-coallescence-omittance/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/nullish-coallescence-omittance/_expected/server/index.svelte.js, packages/svelte/tests/snapshot/samples/skip-static-subtree/_expected/client/index.svelte.js, packages/svelte/tests/sourcemaps/samples/attached-sourcemap/input.svelte
Noticed while looking into something unrelated that this input...
```svelte
<script>
let choice = $state('one');
</script>
<input type="radio" bind:group={choice} value="one" />
<input type="radio" bind:group={choice} value="two" />
<input type="radio" bind:group={choice} value="three" />
<p>{choice}</p>
```
...yields this output:
```js
input.value = null == (input.__value = 'one') ? '' : 'one';
```
At minimum, it should be this instead:
```js
input.value = input.__value = 'one' ?? '';
```
But we can go much further. Something I've been meaning to get round to for a while is to add some simple partial evaluation, which would make it possible to avoid the `?? ''` stuff in a lot more cases. @Ocean-OS made some progress on this front in #15374 but I'd like it to be able to accommodate …
=> feat: add partial evaluation

.changeset/sweet-adults-complain.md, packages/svelte/src/internal/client/runtime.js
Fixes #15262
Apologies @trueadm , you were right in #15694 that the check was _not_ redundant, my suggestion was wrong. `reaction` cannot be `null`, so when `previous_reaction` is `null` the check was now `true` when it should've been `false`. Therefore reinstating this check.
=> fix: avoid unnecessary read version increments

.changeset/fifty-buckets-return.md, packages/svelte/src/index-client.js, packages/svelte/types/index.d.ts
Tests are OK, except for those using Playwright, which I didn't install. Linting crashes for me with an Eslint "Cannot find module" error. I'm holding off on fixing these setup issues, I'm not sure if it's worth it for a one-word docs change.
---
I tried to follow the guidance given by the docs for `createEventDispatcher` to type a custom event without a detail argument. The function documentation mentions that the `never` type can be used for this. However, when doing this, I'm getting a Typescript error `Expected 2-3 arguments, but got 1` when calling `createEventDispatcher`.
I searched the dedicated v4 docs site and found [this section on createEventDispatcher](https://v4.svelte.dev/docs/typescript#script-lang-ts-events) which includes `event: null; // does not accept a payload`. I …
=> docs: correct the suggested type for custom events without detail (Svelte 4)

packages/svelte/src/internal/client/dom/blocks/html.js, packages/svelte/src/internal/client/reactivity/effects.js
We erroneously treat `{@html ...}` tags as a block effect, when really it's more like a template effect. The distinction isn't hugely important today, but it will become more significant with some future work that's planned, so merging this will reduce the size of an upcoming diff.
It also means we only need to create one effect per `{@html ...}` tag instead of two.
=> chore: use template_effect for html tags

.changeset/pretty-beers-care.md, documentation/docs/98-reference/.generated/compile-errors.md, packages/svelte/messages/compile-errors/style.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/css/css-analyze.js, packages/svelte/tests/compiler-errors/samples/css-global-block-in-pseudoclass/_config.js, packages/svelte/tests/compiler-errors/samples/css-global-block-in-pseudoclass/main.svelte
=> fix: emit error on wrong placement of the `:global` block selector

.changeset/eleven-roses-speak.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/error-boundary-22/Child.svelte, packages/svelte/tests/runtime-runes/samples/error-boundary-22/_config.js, packages/svelte/tests/runtime-runes/samples/error-boundary-22/main.svelte
fixes #15674 
When `DEV=false`, the `should_rethrow_error` check wasn't being performed, which led to errors during the initial mount not triggering `destroy_effect`. This prevented proper removal of elements inside the boundary. I belive this issue relates to commit 10897ac38c3c2828558329b345368372bcf2412d.
To address this, I've moved the DEV-specific logic into an explicit `if` block to distinguishes between DEV and non-DEV behaviors, ensuring consistency across both scenarios.
I couldn't run test with `DEV=false` because `DEV` is controlled by the `NODE_ENV=production` via `esm-env`. So I've added a test case to simulate a similar condition by creating an error scenario where `component_context` is `null`.
=> fix: ensure `<svelte:boundary>` properly removes error content in production mode

packages/svelte/tests/runtime-legacy/samples/ondestroy-prop-access/_config.js, packages/svelte/tests/runtime-legacy/shared.ts, packages/svelte/tests/runtime-runes/samples/event-handler-component-invalid-warning/_config.js, packages/svelte/tests/runtime-runes/samples/event-handler-invalid-values/_config.js, packages/svelte/tests/runtime-runes/samples/event-handler-invalid-warning/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-exception/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-trace-null/_config.js, packages/svelte/tests/runtime-runes/samples/unhoist-function-accessing-snippet/main.svelte, packages/svelte/tests/signals/test.ts
this has been driving me barmy. before: reams of gibberish. after:
self-merging immediately, i can't go back
=> chore: squelch test console output

.changeset/strong-coins-peel.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/impossible-migrate-$derived-derived-var-3/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-slot-change-name/output.svelte, packages/svelte/tests/migrate/samples/impossible-migrate-slot-non-identifier/output.svelte
The warning would just say
> This migration would change the name of a slot making the component unusable
Now it says
> This migration would change the name of a slot (derived to derived_1) making the component unusable
I'm totally open to changing the message itself.
For me, as a newbie, it was really unhelpful to not have any context so I included the name of the "bad" slot here.
=> fix: improve error message for migration errors when slot would be renamed

benchmarking/compare/index.js
The output of `pnpm bench:compare` is very hard to read. This makes it actually usable. Self-merging so I can use it on existing PRs
=> chore: better `bench:compare` script

.changeset/tall-cherries-fix.md, packages/svelte/src/compiler/phases/2-analyze/visitors/Identifier.js, packages/svelte/tests/compiler-errors/samples/invalid-rune-name-shadowed/_config.js, packages/svelte/tests/compiler-errors/samples/invalid-rune-name-shadowed/main.svelte.js
Fixes #12888
I'm a bit unsure but looks like I fixed it in the right place.
=> fix: emit right error for a shadowed invalid rune name

.changeset/little-worms-wonder.md, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/runtime-runes/samples/bigint-invalid/_config.js, packages/svelte/tests/runtime-runes/samples/bigint-invalid/main.svelte
=> fix: prevent invalid BigInt calls from blowing up at compile time

.changeset/blue-badgers-play.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/tests/runtime-runes/samples/nullish-empty-string/_config.js, packages/svelte/tests/runtime-runes/samples/nullish-empty-string/main.svelte, packages/svelte/tests/snapshot/samples/purity/_expected/client/index.svelte.js
=> fix: treat nullish expression as empty string

packages/svelte/src/compiler/phases/scope.js
extracted from #15893 — whether it's an error or not depends on TypeScript. using `ignore` instead of `expect-error` means it won't fail with an up to date `"dom"` lib or whatever it is that controls this stuff
=> chore: ts-ignore Math.f16round

.changeset/short-impalas-exist.md, packages/svelte/src/internal/client/dom/elements/bindings/media.js
Closes #7400
Firefox also uses these events to [update the built-in video control's buffered track](https://hg-edge.mozilla.org/mozilla-central/file/a031b94b3d8e1d98ec6ae030cfda68b778df6edb/toolkit/content/widgets/videocontrols.js#l838) if I found the right file.
=> fix: more frequently update `bind:buffered` to actual value

.changeset/shaggy-toys-arrive.md, packages/svelte/src/compiler/utils/ast.js, packages/svelte/tests/runtime-runes/samples/class-private-fields-assignment-shorthand/_config.js, packages/svelte/tests/runtime-runes/samples/class-private-fields-assignment-shorthand/main.svelte
=> fix: proxify the value in assignment shorthands to the private field

.changeset/ten-plants-carry.md, packages/svelte/src/compiler/phases/3-transform/server/visitors/VariableDeclaration.js, packages/svelte/tests/runtime-runes/samples/props-and-slots/Child.svelte, packages/svelte/tests/runtime-runes/samples/props-and-slots/_config.js, packages/svelte/tests/runtime-runes/samples/props-and-slots/main.svelte, packages/svelte/tests/server-side-rendering/samples/props-id-and-$$slots/main.svelte
=> fix: don't spread away `$$slots` from `$props` is it's used

.changeset/hot-seals-hang.md, packages/svelte/src/internal/client/dom/elements/events.js
In the client code `replay_events`, accessing `dom.onload` and `dom.onerror` causes CSP violations without unsafe-inline for script-src-attr or script-src. Fortunately the guards are unnecessary because `Element.removeAttribute` is a no-op when it doesn't exist ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute)), so it's straightforward cleanup that shaves bytes regardless of the CSP behavior.
Reproduction - https://github.com/ryanatkn/svelte-reproduction-csp-inline-script in [this commit](https://github.com/ryanatkn/svelte-reproduction-csp-inline-script/commit/e1350667e30dd0478115c65b66b428f1f4adc211)
From what I can tell, this partially addresses a couple of issues but doesn't close them - it only silences the problems when the handlers are not added …
=> fix: remove unncessary guards that require CSP privilege when removing event attributes

documentation/docs/07-misc/99-faq.md
remove dead link from the docs, vitest seem to have removed svelte example.
this was the corresponding PR that removed it from vitest https://github.com/vitest-dev/vitest/pull/7767
=> docs: remove dead link in 07-misc/99-faq.md

documentation/docs/03-template-syntax/11-bind.md
Add missing bindings docs.
We also may want to include a fix of #15811 here if it's the docs issue.
P.S.: I noticed that `<input>` in some examples is self-closed and isn't in others. Should it be unified across all examples?
=> docs: add missing bindings

.changeset/serious-moles-yell.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/VariableDeclaration.js, packages/svelte/src/compiler/phases/3-transform/shared/assignments.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/src/compiler/utils/ast.js, packages/svelte/tests/snapshot/samples/destructured-assignments/_expected/client/index.svelte.js
Currently, the compiler assumes that whenever you use array destructuring that the object you're destructuring is an array, and can be interpreted as this:
```js
let [a, b] = object;
// svelte thinks this is equivalent:
let a = object[0];
let b = object[1];
```
However, due to iterators, and anything else using `Symbol.iterator`, [this breaks things](https://svelte.dev/playground/hello-world?version=5.28.1#H4sIAAAAAAAACm2OwWrDMAyGX0WIHZI1tDtnaaDssvuOSQ6Oo4KZIwdbWReM3304Zd1luoj_4_-QIrKaCWt8J2sd3Jy3ExQ0GaGpxAqvxlLAuoso25J7GWD1a12W5Ri-yEpmowr0H9eOhVgC1tgE7c0ibc8AlgQ67VaWAc7wFEQJFbHnXgCeu49tHp09GiGvxPmhKCFmK89myE7w8nrPKa9U7um6shbjGAxrTzOx_Hn7qcNh76Wem9Pjl2ZcRRyDY22N_jzHh53at2yBCRB3PzWne7nFCoW-BWvxK6WhQlHG3gxPWF-VDZR-AAOQ59NbAQAA). This fixes that by reusing the original destructuring …
=> fix: rewrite destructuring logic to handle iterators

documentation/docs/02-runes/02-$state.md
> Classes will not be proxied
The goal is to spell out the above specifically. The previous iteration created a gap in this phrase. Making it harder to grok.
=> docs: Clarify when is a variable proxied

.changeset/polite-tips-enjoy.md, packages/svelte/src/compiler/legacy.js, packages/svelte/tests/parser-legacy/samples/generic-snippets/input.svelte, packages/svelte/tests/parser-legacy/samples/generic-snippets/output.json
I forgot to add it to the legacy parser too which is needed for language-tools.
=> fix: add `typeParams` to `SnippetBlock` for legacy parser

documentation/docs/03-template-syntax/03-each.md
not _totally_ sure this is necessary, but it came up in #15752. expands on what 'diff' means
=> docs: clarify keyed each blocks

documentation/docs/03-template-syntax/01-basic-markup.md
=> docs: clarify ordering of attributes with spread

.changeset/chilled-otters-hear.md, packages/svelte/elements.d.ts
=> fix: falsy attachments types

packages/svelte/src/compiler/phases/2-analyze/visitors/Attribute.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/internal/client/dom/elements/class.js
remove redundant word in comment
=> chore: remove redundant word in comment

documentation/docs/06-runtime/02-context.md
Fix imported module path from 'svelte' to './state.svelte.js' to help the reader see where the custom global state object comes from (in the context of the tutorial).
=> chore: fix docs typo in 02-context.md

.changeset/sweet-islands-sell.md, packages/svelte/src/reactivity/media-query.js, packages/svelte/tests/runtime-runes/samples/media-query/_config.js, packages/svelte/tests/runtime-runes/samples/media-query/main.svelte
=> fix: avoid auto-parenthesis for special-keywords-only `MediaQuery`

.changeset/cuddly-flowers-poke.md, packages/svelte/src/runtime/internal/Component.js
- **fix: properly remove event listeners in Component's removeEventListener**
=> fix: properly remove event listeners in Component's removeEventListener (v4)

package.json
#15965 caused 4.2.20 to be released. Unfortunately it was tagged as `latest`. This should prevent that from happening if we need to cut another 4.x release.
=> chore: add --tag legacy to prevent svelte 4 being published as latest

.changeset/fifty-llamas-know.md, packages/svelte/src/compiler/phases/3-transform/utils.js
was looking into how we can make fewer things in #15538 need to be aware of the templating mode (which will make everything more robust) and ran into this `<pre>` logic. Took me a while to wrap my head round it but it turns out we way overcomplicated things in #14922 — the essence of this logic is that if the first node inside a `<pre>` is a single newline, we need to strip it because otherwise hydration breaks:
```js
document.body.innerHTML = `<pre>
<div>...</div>
</pre>`;
document.body.querySelector('pre').firstChild; // DIV, not the newline
```
Instead of doing a convoluted song and dance we can just express that directly. For #15538, we _do_ want to strip any remaining leading newline, but that should happen in `template_to_functions`, not here
=> chore: simplify `<pre>` cleaning

.changeset/nervous-hotels-clean.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/tests/runtime-runes/samples/svelte-meta-css-wrapper/Component.svelte, packages/svelte/tests/runtime-runes/samples/svelte-meta-css-wrapper/_config.js, packages/svelte/tests/runtime-runes/samples/svelte-meta-css-wrapper/main.svelte
spotted while working on #15538 — if we insert a `<svelte-css-wrapper>`, it desyncs the template from the `locations` array, meaning the `__svelte_meta` object (which allows things like the inspector to work) is attached to the wrong element
=> fix: attach __svelte_meta correctly to elements following a CSS wrapper

documentation/docs/03-template-syntax/12-bind.md
this extracts out the first bit of #14905 and adds a playground link
=> docs: improve bind:group example

documentation/docs/02-runes/02-$state.md
Was just reading https://svelte.dev/docs/svelte/$state and I really don't like the 'Class instances are not proxied' breakout quote. It doesn't make sense to disrupt the flow with noise about classes at this point, and it's redundant — the very next sentence is "State is proxified recursively until Svelte finds something other than an array or simple object".
Verdict: get rid of it
=> docs: move some `$state` information around

packages/svelte/elements.d.ts, packages/svelte/svelte-html.d.ts
Covers https://github.com/sveltejs/svelte/issues/15971.
**TL;DR:** adds autocomplete support to `SvelteHTMLElements` while preserving its functionality that key can be any string using `string & {}` TS trick.
---
=> feat: enable TS autocomplete for Svelte HTML element definitions

documentation/docs/02-runes/04-$effect.md
Closes: https://github.com/sveltejs/svelte/issues/15955
Following the discussion on this [issue #15955 ](https://github.com/sveltejs/svelte/issues/15955), @elliott-with-the-longest-name-on-github encouraged me to submit a PR to update the ["money spent / money left" example](https://svelte.dev/playground/untitled?version=5.30.2#H4sIAAAAAAAAE51SsW6DMBT8FcvqABINdOhCIFKXTt06lg4GHpElYyz8iECIf69tcIIipo6-u3f3fPZMJWuBpvRzkBXyTpKSy5rLq6YRbbgATdOfmeKkrMgCBt9GPpQ66RsItFjJNBzhVScRJBobmumq5wovhSxQABLskAmSk7ckOXtMKyM22ItGhhAk4Z0R0OwIN-tIQzd-90HVhvy2HsGNiQFCMltBgd7XoecV2xzXNV7XaEcth7ZfRv7kujnsTX2Qd7USb5rFjwZkJlgJwpWRcakG04cpOS9oz-QVCuoeInXW-RyEJL-sG0b7Wy6kZWM-u7CFxM5tdrIl9qg72vB74H-y7T2iXROHyVb0CLanp1yNk4D1A1jQ91hzrQSbUtIIGLcir0ylJDm9Q7urz42bX4UwIk2xH2D5Xf4A7SeMcMQCAAA=) in the [“When *not* to use …
=> docs: Improve sample code in `When not to use $effect` section

.changeset/lazy-singers-pretend.md, packages/svelte/src/compiler/phases/1-parse/read/style.js, packages/svelte/tests/css/samples/unicode-identifier/_config.js, packages/svelte/tests/css/samples/unicode-identifier/expected.css, packages/svelte/tests/css/samples/unicode-identifier/expected.html, packages/svelte/tests/css/samples/unicode-identifier/input.svelte
Found in https://discord.com/channels/457912077277855764/1372972353213960232
Specs: https://www.w3.org/TR/CSS22/syndata.html#characters
The unicode sequences (`\123`) weren't considered that caused falsy css_unused_selector and even css_expected_identifier (`#\31 23` is a valid selector of `id="123"`).
=> fix: correctly parse escaped unicode characters in css selector

.changeset/old-insects-divide.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/tests/runtime-runes/samples/effect-teardown-stale-value/_config.js, packages/svelte/tests/runtime-runes/samples/effect-teardown-stale-value/main.svelte
Fixes the issue reported here: https://www.reddit.com/r/sveltejs/comments/1ku7skr/can_someone_explain_this_weird_behavior_i_really. Previously, deriveds read during effect teardown were being marked clean, which caused them to hold onto incorrect values if they depended on state that had just changed
=> fix: don't mark deriveds as clean if updating during teardown

documentation/docs/03-template-syntax/12-bind.md
There's been a few PRs that think "lvalue" is a typo in the documentation, this should clear up any confusion. 
Closes #16006
=> docs: add link to lvalue info on `bind:` docs

playgrounds/sandbox/run.js
QOL thing — i use the sandbox a lot to see how stuff compiles, and `dev: true` introduces a lot of noise that i almost never want
=> chore: use dev: false in sandbox

documentation/docs/05-special-elements/04-svelte-body.md
Adds a missing 'at' in the third sentence of the description for clarity.
This is a small documentation typo fix and does not affect functionality or code logic.
=> docs: add missing 'at' in sentence three of description

.changeset/tiny-poems-scream.md, packages/svelte/src/internal/client/dom/elements/transitions.js
Fix the issue reported at https://github.com/sveltejs/svelte/issues/14732
=> fix: transitions might render animated elements without animation styles applied for the duration of some rendering frames when they start

.changeset/rude-drinks-relate.md, packages/svelte/src/compiler/phases/3-transform/server/visitors/AssignmentExpression.js, packages/svelte/tests/snapshot/samples/class-state-field-constructor-assignment/_expected/client/index.svelte.js, packages/svelte/tests/snapshot/samples/class-state-field-constructor-assignment/_expected/server/index.svelte.js, packages/svelte/tests/snapshot/samples/class-state-field-constructor-assignment/index.svelte
Fixes #16050. It appears that we weren't doing enough checks on reassignments in SSR mode, so reassignments like these...
```js
this.foo.bar = 5;
foo.bar = 5;
```
would be incorrectly transformed to
```js
this.bar(5);
this.bar(5);
```
If `this.bar` was a derived class field. Additionally, since derived class fields are now transformed to getters and setters per #15964, we don't need to transform (public) derived assignments to function calls.
=> fix: correctly transform reassignments to class fields in SSR mode

package.json
We forgot to remove these when the `sites` directory was migrated to the [svelte.dev repo](https://github.com/sveltejs/svelte.dev)
=> chore: remove site scripts from `package.json`

.changeset/dry-squids-compete.md, packages/svelte/elements.d.ts, packages/svelte/svelte-html.d.ts
Reverts #15972, since it caused #16046 — a far more pressing limitation than the one #15972 addressed
=> Revert "feat: enable TS autocomplete for Svelte HTML element definitions"

.changeset/violet-actors-teach.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/SnippetBlock.js, packages/svelte/tests/runtime-runes/samples/snippet-destructure-array/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-destructure-array/main.svelte
=> fix: destructuring snippet arguments

packages/svelte/tests/html_equal.js, packages/svelte/tests/runtime-legacy/samples/binding-select/_config.js, packages/svelte/tests/runtime-legacy/samples/input-list/_config.js, packages/svelte/tests/runtime-legacy/samples/namespace-html/_config.js, packages/svelte/tests/runtime-legacy/samples/select-in-each/_config.js, packages/svelte/tests/runtime-legacy/shared.ts
This fixes a particular bugbear of mine with our test setup.
We have an `assert.htmlEqual` utility that compares two HTML strings. Before doing so it normalizes them, because otherwise you'd have to pay very close attention to hydration markers and whitespace and stuff that distracts from the thing being tested (if a test _does_ need to pay attention to those things it is able to do so, but `htmlEqual` is the wrong tool).
The trouble is that the output of the normalization process is prohibitively difficult to read, and my brain gets fatigued trying to work out what needs to change about the output when I see something like this:
```diff
- Expected
+ Received
<select><option selected="" value="[object Object]">put
your
left
leg
in</option><option value="[object Object]">your
left
leg …
```
=> chore: better HTML normalization test helper

.changeset/metal-rivers-laugh.md, packages/svelte/elements.d.ts
The `xmlns` attribute is not only allowed on SVG elements, but on all HTML elements. 
Fixes https://github.com/sveltejs/svelte/issues/16079
=> fix: add `xmlns` attribute to HTMLAttributes type

documentation/docs/02-runes/02-$state.md
Closes #16123
Given it's not immediately clear that `Object.create` has the same "limitations" of class i guess it's fine to add a small note in the docs about it.
=> docs: add note on `Object.create`

packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/src/internal/client/constants.js, packages/svelte/src/internal/client/dev/tracing.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/reactivity/types.d.ts
I don't think there's much value in removing the existing proxy path (https://github.com/sveltejs/svelte/pull/16060#issuecomment-2960229436)
=> remove PROXY_REMOVE_PATH

.changeset/soft-oranges-approve.md, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/legacy/legacy-client.js
Closes https://github.com/sveltejs/svelte/issues/16040
Alternative to #16141
Looks like there is no need for tracking these signals, they just need to use `safe_equals` equality check.
=> fix: prevent memory leaking signals in legacy mode

packages/svelte/src/internal/client/reactivity/effects.js
follow-up to #16150. While merging `main` into the `async` branch I realised that I messed up the condition here — we only want to schedule effects that are dirty, not the ones that are clean. But it turns out they're _already_ scheduled, and this code is completely unnecessary.
We do still need it on the `async` branch, but not here
=> chore: remove some unnecessary code

packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js
This shouldn't be a getter. At the moment it's fine because a bug in `esrap` is masking it, but that bug will soon be fixed
=> chore: fix `$.attachment` prop

documentation/docs/07-misc/02-testing.md
Fixes #16182
The alternative is to come up with a completely different example. FWIW I have actually used this pattern to verify an effect is only running `n` times.
=> fix: Make docs example not infinitely recurse

.changeset/short-mails-know.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/Component.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/tests/runtime-runes/samples/dynamic-component-nested/A.svelte, packages/svelte/tests/runtime-runes/samples/dynamic-component-nested/_config.js, packages/svelte/tests/runtime-runes/samples/dynamic-component-nested/main.svelte
Fixes #16163 caused by regression in #16118
=> fix: avoid shadowing a variable in dynamic components

.changeset/fair-laws-appear.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/attribute-selector-matches-derictive/expected.css, packages/svelte/tests/css/samples/attribute-selector-matches-derictive/input.svelte, packages/svelte/tests/css/samples/class-directive/_config.js, packages/svelte/tests/css/samples/class-directive/expected.css, packages/svelte/tests/css/samples/class-directive/input.svelte
=> fix: match class and style directives against attribute selector

.changeset/big-carpets-stare.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/class-directive/_config.js, packages/svelte/tests/css/samples/class-directive/expected.css, packages/svelte/tests/css/samples/class-directive/input.svelte
=> fix: address css class matching regression

.changeset/clever-dodos-jam.md, documentation/docs/98-reference/.generated/client-errors.md, packages/svelte/messages/client-errors/errors.md, packages/svelte/src/internal/client/dev/inspect.js, packages/svelte/src/internal/client/errors.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-runes/samples/inspect-state-unsafe-mutation/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-state-unsafe-mutation/main.svelte, packages/svelte/tests/runtime-runes/samples/inspect-with-untracked/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-with-untracked/main.svelte
Closes #16156
It's important for inspect to be pure both because it's not there in production and because being sync it can tear the graph. While writing the test i've also noticed that if you did this
```ts
$inspect(a).with((...args)=>{
console.log(...args);
b;
});
```
`b` was also a dependency of the whole inspect (and it was not even showing up in the logs) so i untracked the `inspector` call (keeping the snapshot outside of the `untrack` to deeply read the value)
=> fix: untrack `$inspect.with` and add check for unsafe mutation

packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js
ran into this needless indirection while working on async stuff — select value handling looks like it needs a bit of a tidy up, of which this is an easy first start. self-merging to unblock since it should be very uncontroversial
=> chore: reduce some select.value indirection

packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/dom/elements/bindings/select.js
Follow-up to #16250. There's a lot of unnecessary dancing around with `<select>` values that we can solve by being smarter about the order in which things happen — if we initialize the child `<option>` values first, we don't need to muck about passing the value into the `init_select` function that sets up the `MutationObserver`.
This, in turn, will allow us to get rid of the special handling of that attribute, ~~but I'll do that as a follow-up.~~ changed my mind
=> chore: simplify `<select>` initialization

.changeset/little-kings-smoke.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
Fixes #15829 and potentially #15853
I can't quite articulate yet why this is right, but I _think_ it is. Basically, an unowned derived should still add itself as a reaction while it is properly connected, which means it can be cleaned up correctly - and this connection is indicated by it having reactions.
=> fix: ensure unowned deriveds can add themselves as reactions while connected

.changeset/short-fireants-flow.md, documentation/docs/98-reference/.generated/client-errors.md, packages/svelte/messages/client-errors/errors.md, packages/svelte/src/index-client.js, packages/svelte/src/index-server.js, packages/svelte/src/internal/client/constants.js, packages/svelte/src/internal/client/errors.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/types.d.ts, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/server/abort-signal.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-runes/samples/get-abort-signal/_config.js, packages/svelte/tests/runtime-runes/samples/get-abort-signal/main.svelte, packages/svelte/types/index.d.ts
This extracts `getAbortSignal()` from #15844, since it is (at least theoretically) independently useful and is easier to review in isolation. 
It _may_ prove necessary to expose `STALE_REACTION` in some form, so that people can do `signal.reason === ???` inside a `.catch` handler to determine whether or not to rethrow an error. But rather than get bogged down in design questions around what it should be called and where it should be exported from, I think we can safely cross that bridge later if we need to.
=> feat: add `getAbortSignal()`

packages/svelte/src/compiler/index.js, packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/compiler/phases/1-parse/index.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/types.d.ts, packages/svelte/src/compiler/state.js
per https://github.com/sveltejs/svelte/pull/16255#discussion_r2175461400, this scratches an itch I've had for a while: we put a lot of stuff on `context.state.analysis` that doesn't really form part of the analysis phase, it's just a convenient place to stick it.
It would be _more_ convenient if that stuff was part of the global state exported from `state.js` — just as we guard dev-only compiler logic in `if (dev)` rather than `if (context.state.analysis.dev)` we could also do `if (runes)`, for example.
While doing this I realised that we don't need to do `state.reset` inside `parse(...)`, because we only actually need to reset `source` and `locator`. This means `parse` no longer needs to take an unused `filename` option, so we can remove this in Svelte 6 and make that API simpler.
This …
=> chore: move stuff from `analysis` into global compiler state

.changeset/new-trees-behave.md, packages/svelte/src/internal/client/constants.js, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/runtime.js
While looking into #16263 I realised that we can _drastically_ simplify the `prop` implementation now that deriveds are writable. Some of the code in red is pretty hard to understand, but deleting it causes no tests to fail. Just to be safe, I added a changeset so that this creates a new version that we can roll back from if it causes any issues.
=> chore: simplify props

packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/tests/runtime-legacy/samples/prop-no-change/_config.js
#16270 removed a condition which seemed to keep passing the corresponding test, but it actually introduced a regression since the PROPS_IS_UPDATED is always set when accessors should be created, which is the case by default in legacy mode tests. Setting accessors to false in the test reveals the regression, so this reverts that part of the refactoring.
No changeset since #16270 wasn't released yet
=> fix: revert props legacy mode regression

packages/svelte/src/internal/client/constants.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js
another small `async` change extracted into its own PR — better communicates intent, and allows effects to be preserved for other reasons
=> chore: rename EFFECT_HAS_DERIVED to EFFECT_PRESERVED

packages/svelte/src/internal/client/dom/blocks/boundary.js, packages/svelte/src/internal/client/error-handling.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/types.d.ts
This aligns with #15844 and makes things a bit more sensible
=> chore: convert boundary implementation to a class

.changeset/fifty-hats-watch.md, packages/svelte/package.json, pnpm-lock.yaml
fixes #16286. will self-merge once green since this is causing a bunch of regressions
=> fix: bump esrap

packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js
Prompted by https://github.com/sveltejs/svelte/pull/15844/files#r2178611259 — the `reaction_sources` stuff is pretty inscrutable. Changing it to an object with named properties helps a bit, I think, (and I'd expect named properties to be microscopically faster to read than numbered ones) and doing the equality check before the `.includes` check is low-hanging fruit
=> chore: `reaction_sources` -> `source_ownership`

packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/dom/elements/bindings/select.js
=> chore: remove unused `mounting` variable from `select_option` call

packages/svelte/src/internal/client/runtime.js, packages/svelte/src/reactivity/map.js, packages/svelte/src/reactivity/set.js
Simpler way to avoid memory leaks in #16239
=> chore: use `update_version` instead of `WeakRef` in `SvelteSet`/`SvelteMap`

packages/svelte/src/internal/client/runtime.js
was looking into whether we could use the new `update_version` mechanism to make it cheaper to answer 'was this source created inside the current reaction?', and noticed that we're currently doing a check inside a loop that should be outside, since the answer is always the same
=> chore: simplify/optimize source_ownership occurrence

packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/reactivity/create-subscriber.js, packages/svelte/src/reactivity/map.js, packages/svelte/src/reactivity/set.js, packages/svelte/src/reactivity/url-search-params.js, packages/svelte/src/reactivity/utils.js
we have two functions for silently incrementing sources (one in `proxy.js`, one in `reactivity/utils.js`). we only need one
=> chore: DRY out increment logic

.changeset/new-candles-marry.md, packages/svelte/src/internal/client/context.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/types.d.ts
couple of changes here:
- the only time an effect gets deferred is if it's a top-level `$effect`. when `pop` runs, the current active effect/reaction are the same as they were when the effect was declared, so the `set_active_effect` and `set_active_reaction` calls are no-ops. By extension, we don't need to stash the current active effect/reaction, and we don't need to wrap the effect creation in a try-catch
- since we don't need to stash the effect/reaction, `component_context.e` can just be an array of functions rather than an array of objects — less memory usage for components with effects
- we can identify a top-level `$effect` because the current `active_effect` is a `BRANCH_EFFECT`, and the current `active_reaction` is `null`. These conditions do not obtain in any other …
=> chore: simplify component pop

.github/workflows/ecosystem-ci-trigger.yml
mistakenly used read before as i thought reactions were enough, but a test showed a 403 so lets try with write...
=> fix: set write permission for PR in ecosystem-ci-trigger workflow

packages/svelte/src/compiler/phases/3-transform/client/visitors/SlotElement.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/component.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js
another change extracted from #15844 — this removes the `memoize_expression` helper in favour of the consistent `Memoizer` approach used elsewhere
=> chore: remove memoize_expression

packages/svelte/tests/runtime-runes/samples/error-boundary-9/_config.js
honestly no idea why this was necessary on the async branch but apparently isn't any more, but it does seem like it _shouldn't_ be necessary, so I'll self-merge once green since this is currently blocking all other PRs
=> chore: fix error boundary test

.changeset/popular-tips-lie.md, packages/svelte/src/internal/client/dom/blocks/boundary.js, packages/svelte/src/internal/client/reactivity/batch.js, packages/svelte/tests/runtime-runes/samples/async-effect-pending/_config.js, packages/svelte/tests/runtime-runes/samples/async-effect-pending/main.svelte
This makes `$effect.pending()` updates more predictable and reliable
=> fix: update `$effect.pending()` immediately after a batch is removed

package.json, pnpm-lock.yaml
I was getting an unmet peer dep warning version because the version of `@vitest/coverage-v8` doesn't match the version of `vitest`
=> chore: fix peer dependency warning

documentation/docs/02-runes/03-$derived.md
=> docs: diligently describe destructured derived declarations

CONTRIBUTING.md
=> chore: update to new pnpm syntax

packages/svelte/src/ambient.d.ts, packages/svelte/types/index.d.ts
I noticed that the JSDoc formatting for the `$effect.root` rune seemed incorrect, so I fixed it to match the rest of the documentation.
=> docs: fix `$effect.root` jsdoc formatting

documentation/docs/07-misc/03-typescript.md, packages/svelte/svelte-html.d.ts
Since #9070 it's prefered to use the "enhance svelte elements" way of doing things. That's so long ago that we can now remove the other option from the docs, and eventually remove the backwards compatibility that still allows the old way of doing things.
=> docs: remove mention of deprecated way to enhance typings

.changeset/clever-toys-decide.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/props-derived-teardown/Teardown.svelte, packages/svelte/tests/runtime-runes/samples/props-derived-teardown/_config.js, packages/svelte/tests/runtime-runes/samples/props-derived-teardown/main.svelte
The prior logic was wrong because it reexecuted when something was clean, but we want to when it's not. The remaining fix was to also check the reactions: A derived is set to `MAYBE_DIRTY` if it doesn't have any reactions anymore as a result of e.g. an effect that listened to it tearing down. We don't want to rerun in that case.
Fixes #16363
=> fix: don't reexecute derived with no dependencies on teardown

.changeset/curly-buttons-burn.md, packages/svelte/src/compiler/phases/2-analyze/visitors/ExportNamedDeclaration.js, packages/svelte/tests/validator/samples/default-export-indirect/errors.json, packages/svelte/tests/validator/samples/default-export-indirect/input.svelte
Currently, the compiler will throw an error if you use `export default` in a component.
However, it doesn't throw if you use `export { foo as default }` or `export { foo as 'default' }`. This fixes that.
=> fix: disallow `export { foo as default }` in `<script module>`

.changeset/healthy-carpets-deny.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/tests/runtime-runes/samples/async-ownership-validation/Child.svelte, packages/svelte/tests/runtime-runes/samples/async-ownership-validation/_config.js, packages/svelte/tests/runtime-runes/samples/async-ownership-validation/main.svelte
=> fix: move ownership validation into async component body

.changeset/new-fireants-bake.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js
=> fix: move store setup/cleanup outside of async component body

.changeset/mighty-balloons-rush.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/tests/runtime-runes/samples/async-derived-destructured/Child.svelte, packages/svelte/tests/runtime-runes/samples/async-derived-destructured/_config.js, packages/svelte/tests/runtime-runes/samples/async-derived-destructured/main.svelte, svelte.config.js
=> fix: allow async destructured deriveds

.changeset/fresh-birds-jam.md, packages/svelte/src/internal/client/dom/blocks/boundary.js, packages/svelte/src/internal/client/reactivity/batch.js
No test for this because I can't figure how to make something broken without it, but I'm fairly sure this _is_ necessary. While debugging an app that uses remote functions, I noticed that batches weren't reliably getting removed, and in at least some cases the root cause is that the `queueMicrotask` callback in a boundary is getting tangled up with the `queueMicrotask` callback in `Batch.ensure`
=> fix: prevent batches from getting intertwined

.changeset/silent-rockets-tease.md, packages/svelte/src/internal/client/dev/tracing.js, packages/svelte/src/internal/client/reactivity/store.js, packages/svelte/tests/runtime-runes/samples/inspect-trace-store/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-trace-store/main.svelte
Before:
After:
Ought to be uncontroversial so I'm going to go ahead and self-merge once green — I need this to debug some remote functions/async stuff (it's tripping up over SvelteKit's internal stores, which I can't wait to get rid of)
=> fix: tag stores for `$inspect.trace()`

.changeset/four-spiders-type.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/ConstTag.js, packages/svelte/src/internal/client/reactivity/props.js
Adds missing labels to `@const` and props
=> fix: add labels to `@const` tags and props

packages/svelte/src/internal/client/reactivity/batch.js
Been taking a run at a few overlapping issues relating to effect flushing recently and I keep making these same changes over and over again in separate contexts, so I figured I'd open a PR for them
=> chore: small tidy up

.changeset/grumpy-boats-beg.md, .changeset/shiny-walls-fix.md, .changeset/thick-mice-kick.md, packages/svelte/src/internal/client/dev/debug.js, packages/svelte/src/internal/client/reactivity/batch.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-runes/samples/1000-reading-derived-effects/Component.svelte, packages/svelte/tests/runtime-runes/samples/1000-reading-derived-effects/_config.js, packages/svelte/tests/runtime-runes/samples/1000-reading-derived-effects/main.svelte, packages/svelte/tests/runtime-runes/samples/async-binding-update-while-focused/_config.js, packages/svelte/tests/runtime-runes/samples/async-binding-update-while-focused/main.svelte, packages/svelte/tests/runtime-runes/samples/async-effect-triggers-await/_config.js, packages/svelte/tests/runtime-runes/samples/async-effect-triggers-await/main.svelte, packages/svelte/tests/runtime-runes/samples/binding-update-while-focused-2/_config.js, packages/svelte/tests/runtime-runes/samples/binding-update-while-focused-2/main.svelte
- fixes #16413 (and closes #16464)
- fixes #16423 (and closes #16477)
- fixes #16403
I wish I could claim credit for this but it's all @dummdidumm, I'm just opening a PR to make working on it easier. Essentially, we now create a fresh batch to handle any state changes that occur during effects that run after the prior batch is committed
=> fix: unset batch before flushing queued effects

.changeset/healthy-carpets-deny.md, packages/svelte/elements.d.ts
> [`accept-charset`](https://html.spec.whatwg.org/multipage/forms.html#attr-form-accept-charset) — Character encodings to use for [form submission](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission-2)
> The `accept-charset` attribute gives the character encodings that are to be used for the submission. If specified, the value must be an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for "`UTF-8`". [\[ENCODING\]](https://html.spec.whatwg.org/multipage/references.html#refsENCODING)
https://html.spec.whatwg.org/multipage/forms.html#attr-form-accept-charset
=> chore: rename form `accept-charset` attribute

.changeset/cool-insects-argue.md, packages/svelte/src/internal/client/reactivity/batch.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-runes/samples/async-effect-conservative/_config.js, packages/svelte/tests/runtime-runes/samples/async-effect-conservative/main.svelte
Ironically, the part of #16482 that fixed the infinite loop bug in #16403 introduced an even worse infinite loop that made remote functions unusable. I have learned, for the 19th or so time, that it is _absolutely_ not safe to `mark_reactions` when triggering a batch re-run.
It turns out we (which in this case is the royal 'we') were doing something rather silly: we were queueing _all_ leaf effects when traversing the tree, not just the `DIRTY`/`MAYBE_DIRTY` ones. In the common case that's fine, because they get flushed immediately and they get filtered with `is_dirty`, but if the effects are deferred (because async work is happening) then on the next run they are all marked `DIRTY` and re-executed.
This PR makes everything somewhat more efficient. Firstly, it only queues effects that are …
=> fix: preserve dirty status of deferred effects

.changeset/violet-ways-sleep.md, packages/svelte/src/compiler/validate-options.js
This causes `compileModule` to ignore component options, while still erroring on unknown options, which is useful for things like vite-plugin-svelte which don't know _which_ options should be ignored in the module case
=> feat: ignore component options in `compileModule`

CONTRIBUTING.md, documentation/docs/01-introduction/02-getting-started.md, documentation/docs/07-misc/02-testing.md, documentation/docs/98-reference/.generated/compile-warnings.md, packages/svelte/README.md, packages/svelte/messages/compile-warnings/template.md
Same as https://github.com/sveltejs/cli/pull/634
=> docs: use sh instead of bash in source blocks

.changeset/shaggy-comics-fail.md, .changeset/wise-hairs-pay.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/internal/client/dom/css.js, packages/svelte/tests/runtime-browser/custom-elements-samples/host-rune-access-injected-css/_config.js, packages/svelte/tests/runtime-browser/custom-elements-samples/host-rune-access-injected-css/main.svelte, packages/svelte/tests/runtime-runes/samples/custom-element-injected-styles/Thing.svelte, packages/svelte/tests/runtime-runes/samples/custom-element-injected-styles/_config.js, packages/svelte/tests/runtime-runes/samples/custom-element-injected-styles/main.svelte
Closes #16472
Small technicality...I'm pretty sure the actual reproduction doesn't work anyway...but that was not working even before. The reason is that the reproduction is missing css inject. However this got me thinking...given that the style tag is meant to be inside the custom element shouldn't we always inject when building a custom element?
=> fix: `append_styles` in an effect to make them available on mount

.changeset/shiny-berries-call.md, packages/svelte/src/compiler/phases/1-parse/index.js, packages/svelte/src/compiler/phases/1-parse/state/element.js
this doesn't appear to do anything? No tests fail if we remove it. If it _is_ important for `parser.index` to be at the end of the file as opposed to `parser.template`, then we could just do this (where `source` is imported from `state.js`)...
```js
parser.allow_whitespace();
parser.index = source.length;
```
...but it's not clear to me what that would change.
=> chore: remove `parser.template_untrimmed`

.changeset/long-roses-train.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/AwaitBlock.js, packages/svelte/tests/runtime-runes/samples/async-await/_config.js, packages/svelte/tests/runtime-runes/samples/async-await/main.svelte
=> fix: allow await expressions inside `{#await ...}` argument

.changeset/chilly-bananas-train.md, packages/svelte/src/internal/client/dom/elements/events.js
Firefox seems to garbage collect event objects during event propagation if no global/shared reference to the event object is kept between multiple event handlers. That discards the `__root` marker set on the event object to early, leading to duplicate processing.
I am not sure what is a good way to test this.
=> fix: double event processing in Firefox (#16522)

documentation/docs/03-template-syntax/08-@html.md, documentation/docs/06-runtime/03-lifecycle-hooks.md, documentation/docs/07-misc/07-v5-migration-guide.md, documentation/docs/98-reference/.generated/compile-errors.md, packages/svelte/messages/compile-errors/script.md
#16550 made various 'corrections', some of which made sense ('server-side rendering' should always be hyphenated), others less so. Our docs strive for a conversational tone, in which colloquialisms (such as 'as such' for 'therefore') are preferable to stilted words like 'thus' which just don't occur in spoken English and make everything sound clunky. Nevertheless this PR tries to find a balance between them, while fixing some of the awkward phrasing.
Some usages of 'as such' were, I would argue, perfectly fine. For example in the context of
> Content rendered this way is 'invisible' to Svelte and as such will not receive scoped styles'
'as such' expands to
> Content rendered this way is 'invisible' to Svelte and (as it is invisible to Svelte) will not receive scoped styles'
unless you …
=> docs: remove 'thus', fix some phrasing

.changeset/thick-snakes-look.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SnippetBlock.js, packages/svelte/src/compiler/phases/types.d.ts, packages/svelte/tests/compiler-errors/samples/snippet-invalid-export/_config.js, packages/svelte/tests/compiler-errors/samples/snippet-invalid-export/main.svelte
Closes #16474
I'm not entirely sure if this is the best way to do this, as I don't know if there's any other reason that a snippet wouldn't be able to be exported, but this should work.
=> fix: emit `snippet_invalid_export` instead of `undefined_export` for exported snippets

.changeset/quiet-donuts-wonder.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/ForOfStatement.js, packages/svelte/src/compiler/utils/builders.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/client/reactivity/async.js, packages/svelte/tests/runtime-runes/samples/async-reactivity-loss-for-await/_config.js, packages/svelte/tests/runtime-runes/samples/async-reactivity-loss-for-await/main.svelte
Currently, `await` expressions not inside an async derived are wrapped in `track_reactivity_loss` in dev to warn of a reactivity loss. 
However, `for await` loops are not. This PR fixes that.
=> chore: emit `await_reactivity_loss` in `for await` loops

packages/svelte/src/compiler/phases/3-transform/shared/assignments.js, packages/svelte/src/compiler/utils/builders.js
noticed while reviewing #16542 — we have a `b.async` helper that just adds the `async` flag to an existing function expression, when we should just be passing that option to `b.arrow` or `b.function` etc
=> chore: remove `b.async`

packages/svelte/package.json, packages/svelte/src/compiler/preprocess/index.js, packages/svelte/src/compiler/preprocess/private.d.ts, packages/svelte/src/compiler/utils/mapped_code.js, pnpm-lock.yaml
https://github.com/ampproject/remapping was archived. Strangely https://www.npmjs.com/package/@ampproject/remapping was not deprecated, but it looks like development has ceased on it
This fixes it for our users. It's still pulled into our `devDependencies` via `vitest`, so I filed an issue there: https://github.com/vitest-dev/vitest/issues/8417
=> chore: switch to jrdigewell version of remapping library

playgrounds/sandbox/package.json, playgrounds/sandbox/scripts/create-test.js
I often play around with stuff locally and then turn it into a test, this automates the last mile of that
=> chore: add script to generate test from playground

.changeset/healthy-crabs-marry.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/tests/runtime-runes/samples/async-template-async-sync-mixed/_config.js, packages/svelte/tests/runtime-runes/samples/async-template-async-sync-mixed/main.svelte
Compiler does sync then async but `memoizer.apply` did it the other way around
=> fix: ensure correct order of template effect values

.changeset/cool-garlics-fail.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/tests/runtime-runes/samples/async-reference-in-snippet/_config.js, packages/svelte/tests/runtime-runes/samples/async-reference-in-snippet/app.svelte, packages/svelte/tests/runtime-runes/samples/async-reference-in-snippet/main.svelte
=> fix: place instance-level snippets inside async body

.changeset/fuzzy-shrimps-dream.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/custom-element-attributes/_config.js, packages/svelte/tests/runtime-runes/samples/custom-element-attributes/main.svelte
Fixes #16591 
This PR introduces a check for builtin custom elements (`is` attribute) inside the `set_custom_element_data` helper in order to correctly set properties that have a setter.
I would like to add tests but I am not familiar with the codebase and wasn't able to find the correct path.
=> fix: Add check for builtin custom elements in `set_custom_element_data`

.changeset/thick-books-fail.md, packages/svelte/elements.d.ts
It seems like this is a valid value and it has been working for me, however I did find conflicting information on whether it is supported or not.
Supporting Evidence:
- https://github.com/WICG/client-hints-infrastructure?tab=readme-ov-file#opt-in-mechanism
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Client_hints#overview
- https://developer.chrome.com/docs/privacy-security/user-agent-client-hints#introducing_the_new_user-agent_client_hints
- https://github.com/httpwg/http-extensions/issues/189
Conflicting Evidence:
- https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv
=> chore(elements.d.ts): add "Accept-CH" as valid value for `http-equiv`

.changeset/orange-chefs-float.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/tests/runtime-runes/samples/async-derived-reverse-order/_config.js, packages/svelte/tests/runtime-runes/samples/async-derived-reverse-order/main.svelte
When an async derived already has a previous promise that is still pending, we were not accessing the `then` property of the new promise. If that property access causes signals to be read, that meant that those dependencies were lost and as such the derived wouldn't rerun anymore when it should. The fix is to make sure to always access the thennable.
Discovered this while working on the `query.stream` PR (it didn't update in some cases and this is the reason why)
=> fix: ensure async deriveds always get dependencies from thennable

.changeset/wise-schools-report.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js
=> fix: place store setup inside async body

.changeset/ninety-olives-report.md, packages/svelte/src/compiler/utils/builders.js
Found this while working on #16688.
Like #15511, this acknowledges the fact that you can make a variable named `undefined`. Since `b.call` replaces non-trailing nullish arguments with `b.id('undefined')`, you can do [this sort of cursed thing](https://svelte.dev/playground/hello-world?version=5.38.6#H4sIAAAAAAAACm3LsQ6CMBRG4Vdp7gIkBPcqJG6O7uBQ7d-kyaUl7UU0hHc3DDq5fjlnpWBGkKYLmKNaYmKrSlgvsBXV5Dwjk-5Xkve0dztQ_b3O09TkJ1h2u5uMf_6IQRAkk6ZTfiQ_STeEQRii5mDhfIBVrerLSrWdKjhycTsO4XT4xatZjBd1TXH0GU1CjvxEWbgYi2qjmgQvIS1pxnarSYznxQdL2hnO2D6MeTLm5QAAAA==).
=> fix: replace `undefined` with `void(0)` in CallExpressions

.changeset/old-taxis-relate.md, packages/svelte/src/internal/client/dom/task.js, packages/svelte/src/internal/client/reactivity/batch.js, packages/svelte/tests/runtime-runes/samples/async-top-level-error-nested-obsolete/main.svelte, packages/svelte/tests/runtime-runes/samples/dynamic-component-transition/_config.js, packages/svelte/tests/runtime-runes/samples/dynamic-if-component-transition/_config.js
Consolidates our scheduling system that had diverged into two - queue_micro_task and Batch.ensure-queues and resolves some edge case race conditions related to flushSync along the way.
Extracted (and robustified) from #16709
=> fix: clean up scheduling system

CONTRIBUTING.md
Fix `Here's` to `Here are`
Fix `/test` to the right folder `/tests`
=> docs: Fix some inaccuracies

packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/types.d.ts, packages/svelte/src/compiler/phases/2-analyze/visitors/AwaitExpression.js, packages/svelte/src/compiler/phases/2-analyze/visitors/TitleElement.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/TitleElement.js, packages/svelte/src/compiler/types/template.d.ts
=> chore: remove analysis.state.title

packages/svelte/src/compiler/phases/3-transform/server/visitors/EachBlock.js, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/utils.js
titles are handled differently now, so we can do away with this junk
=> chore: simplify `build_template`

.github/workflows/ecosystem-ci-trigger.yml, .github/workflows/pkg.pr.new-comment.yml, .github/workflows/release.yml
these have now served their purpose, and no longer need to slow down our CI (it takes around a minute to set up which is outrageous)
=> chore: remove actions-permissions monitor

.changeset/sixty-crabs-laugh.md, packages/svelte/src/internal/server/index.js, packages/svelte/src/legacy/legacy-server.js
needed for SvelteKit support, at least until we rip out Svelte 4 support from Kit
=> fix: add `then` to class component `render` output

packages/svelte/src/internal/server/dev.js, packages/svelte/src/internal/server/index.js, packages/svelte/src/internal/server/renderer.js, packages/svelte/src/internal/server/renderer.test.ts, packages/svelte/tests/server-side-rendering/samples/head-multiple-title/_config.js
working on fixing some async hydration stuff, and that means making `renderer.child` a bit less catch-all. doing this as a starting point, to unblock other work. will self-merge once green
=> chore: add explicit renderer.head method

.changeset/tasty-snails-dress.md, packages/svelte/src/compiler/phases/3-transform/server/visitors/shared/element.js, packages/svelte/tests/server-side-rendering/samples/async-directive-with-spreading/_expected.html, packages/svelte/tests/server-side-rendering/samples/async-directive-with-spreading/main.svelte
=> fix: async `class:` + spread attributes were compiled into sync server-side code

packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/dom/task.js
We use `queue_idle_task` in exactly one place — removing defaults from inputs. To my mind it really doesn't warrant this special treatment — you have to have _hundreds_ of `<input>` elements with a server-rendered `value` or `checked` attribute before it takes more than a single millisecond to remove all those attributes, at least on this four year old machine, and if they _don't_ have a `value` attribute then you're actually making things worse with `requestIdleCallback`.
Just feels like a bad use of our complexity budget.
I think we can actually go further in simplifying this — like, what if we didn't bother removing these attributes at all until the form in question gets reset? — but for now I'm focused on just removing `queue_idle_task` to unblock further simplifications as to how we …
=> chore: replace queue_idle_task with queue_micro_task

packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/src/internal/client/dom/task.js, packages/svelte/src/internal/client/reactivity/batch.js
this code is infuriatingly resistant to refactoring, but i'm chipping away at it
=> chore: simplify batch logic a bit more

packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/src/internal/client/dom/task.js, packages/svelte/src/internal/client/reactivity/async.js, packages/svelte/src/internal/client/reactivity/batch.js
I'm working to simplify some of the batching logic as a precursor to a larger overhaul that will hopefully make some of the gnarlier edge cases easier to wrangle.
This is a small step in that direction. Previously, we would reinstate a batch at the end of its life — this is one of those things that gets shoehorned into a codebase just to get the tests passing, but it never really made much sense to me. Turns out we don't need it.
The outcome is a simpler batch lifecycle — when you `flush` a batch, it either sticks around because it has pending async work or it gets removed straight away, with no zombie in-between state.
More to come in follow-up PRs
=> chore: simplify batch logic

.changeset/swift-starfishes-knock.md, packages/svelte/src/internal/client/dom/blocks/boundary.js, packages/svelte/tests/runtime-runes/samples/async-attachment-in-block/_config.js, packages/svelte/tests/runtime-runes/samples/async-attachment-in-block/main.svelte
This fixes a somewhat nasty bug that prevents effects (such as attachments) running inside newly-resolved pending boundaries under some circumstances.
As the comment suggests, it feels like a _bit_ of a kludge, but for now we need it.
=> fix: flush when pending boundaries resolve

.changeset/nervous-flies-laugh.md, packages/svelte/src/compiler/phases/2-analyze/visitors/VariableDeclarator.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/Identifier.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/runtime-runes/samples/rest-props-excludes-properties/_config.js, packages/svelte/tests/runtime-runes/samples/rest-props-excludes-properties/component.svelte, packages/svelte/tests/runtime-runes/samples/rest-props-excludes-properties/main.svelte
=> fix: don't replace rest props with `$$props` for excluded props

.changeset/seven-flies-drop.md, packages/svelte/src/compiler/phases/3-transform/server/visitors/MemberExpression.js, packages/svelte/tests/runtime-runes/samples/class-state-derived-private/main.svelte
=> fix: correctly transform `$derived` private fields on server
