sveltejs/svelte

- compiler/generate/index.js
- compiler/generate/visitors/EachBlock.js
- compiler/generate/visitors/Element.js
- compiler/generate/visitors/IfBlock.js
- compiler/generate/visitors/MustacheTag.js
- compiler/generate/visitors/Text.js
- test/compiler/if-block-elseif-text/_config.js
- test/compiler/if-block-elseif-text/main.html
I was wondering why text nodes did not correctly work with anchors, turns out there were issues with all kinds of elements too.
> correctly insert non-element children before an anchor

- compiler/parse/state/mustache.js
- test/parser/if-block-else/output.json
- test/parser/if-block-elseif/output.json
Some else blocks were also missing `end` markers, so I added some, although I’m not 100% sure those are correct. Also noticed that the `start`/`end` markers from trimmed textnodes should maybe reflect the actual text content rather than the whole block?
> also trim whitespace from elseif/else blocks

- compiler/generate/index.js
- test/compiler/get-state/_config.js
- test/compiler/get-state/main.html
Return the component state when using `get()` without any arguments
References #73
> return state when using get without key

- .travis.yml
* Removed unnecessary `sudo` field.
- According to [the CI docs](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), `sudo` is `false` by default for repositories enabled in 2015 or later. [This repository was created in 2016.](https://github.com/sveltejs/svelte/commit/fc7e6e6827c3e9f2a29ec1c6ec957bab9f195841)
* Updated the Node version ID `"stable"` to `"node"`.
- According to [the nvm docs](https://github.com/creationix/nvm/blob/26fec8035f80c82c768427c86ff2fd09693b5d68/README.markdown), `stable` is deprecated and currently just an alias for `node`.
> Improve Travis CI configs

- .gitignore
- compiler/generate/index.js
- compiler/generate/visitors/attributes/addComponentAttributes.js
- compiler/generate/visitors/attributes/addElementAttributes.js
- package.json
- test/sourcemaps/basic/input.html
- test/sourcemaps/basic/test.js
- test/sourcemaps/script/input.html
- test/sourcemaps/script/test.js
- test/test.js
This look a little bit longer than I'd like – did I ever mention that I hate sourcemaps? – but fixes #60 by way of https://github.com/Rich-Harris/magic-string/pull/114, and paves the way for loaders and the CLI to generate nice accurate maps.
> Sourcemaps

- compiler/generate/index.js
- test/compiler/component-data-dynamic/Widget.html
- test/compiler/component-data-dynamic/_config.js
- test/compiler/component-data-dynamic/main.html
This turned out to be a simple typo! Sorry it took me this long to look into it. :)
I added this scenario to `component-data-dynamic` as it already contains several similar tests, but let me know if I should split it into its own test case.
> Fix typo in generator's contextualise; solves #46

- compiler/generate/index.js
- compiler/generate/visitors/EachBlock.js
- compiler/generate/visitors/Element.js
- compiler/generate/visitors/IfBlock.js
- test/compiler/each-block-random-permute/_config.js
- test/compiler/each-block-random-permute/main.html
This is a first step towards keyed iteration, see #81, #77, #33 
The changes got a bit more invasive than I had hoped, but the tests do pass so thats a plus :-)
The `EachBlock` changes currently take the index as key, which is pretty useless for now, but pending some bikeshedding on actual keyed `{{#each}}` syntax, this should be good to go.
> WIP: separate create from mount

- compiler/generate/index.js
- compiler/generate/visitors/EachBlock.js
- compiler/generate/visitors/Element.js
- compiler/generate/visitors/IfBlock.js
This PR groups detach statements into a single if branch.
Note that I haven't modified the teardown template to deal with empty lists: you can end up with extra newlines and an empty if in those cases. Should that be left for minifiers or should we handle them?
Closes #99.
> Improve teardown code by unifying detach branches

- compiler/validate/js/propValidators/computed.js
- test/validator/computed-values/errors.json
- test/validator/computed-values/input.html
With the PR merged this code snipped will fail to compile: 
```
export default {
computed: {
bar: () => { return new Date().getTime(); }
}
};
```
Helps newbies to properly use computed properties and verifies the compiler does not generate broken code (would generate `if (   ) ` somewhere in the code base otherwise.
> Verify computed property dependencies

- README.md
Add [charpeni/svelte-example](https://github.com/charpeni/svelte-example) into README tools.
- es output format
- Eslint
- Babel (presets: es2015 & stage-3)
- Svelte
- Hello World component with default data & Two-Way binding (input)
- Counter component with default data and on:click directive with an observer on this value
- CatList and Cat components as nested components
> Add charpeni/svelte-example into README tools

- .editorconfig
- .flowconfig
This does *not* mean that svelte is using flow (yet ? :-), it is only
that people using flow for code completion get some meaningful results
instead of flow complaining about a missing .flowconfig file.
The editorconfig is so that people who use spaces by default get their
editor using tabs like expected.
> add editorconfig and flowconfig files

- compiler/generate/index.js
- compiler/generate/visitors/Component.js
- compiler/generate/visitors/Element.js
A couple of simple improvements in this PR:
Cleaned up the generated code for teardown when there are no `teardownStatements` or `detachStatements`. No more empty `if`s or extra newlines.
Fixed a regression introduced when `Component` was split from `Element`: `detachStatements` now works correctly on them, too.
Disregard yesterday's PR, I got confused!
> Improve teardown code

- compiler/parse/state/tag.js
- test/parser/attribute-unique-error/error.json
- test/parser/attribute-unique-error/input.html
Like we discussed in #128 I went ahead and make the parser complain about duplicated attribute names.
> Make sure parser only allows unique attribute names

- compiler/generate/index.js
- test/compiler/pass-no-options/_config.js
- test/compiler/pass-no-options/main.html
- test/test.js
While working on #145 I noticed that creating a component without passing an empty options object was not possible. This PR is fixing that.
> Make passing options to component optional

- src/generate/visitors/attributes/addElementAttributes.js
- src/utils/flattenReference.js
- test/generator/event-handler-event-methods/_config.js
- test/generator/event-handler-event-methods/main.html
- test/generator/event-handler-this-methods/_config.js
- test/generator/event-handler-this-methods/main.html
See #162 – this PR allows things like 
```html
<div on:click='event.stopPropagation()'>...</div>
<input on:click='this.select()'>
```
> Allow event handlers to call methods of `event` and `this`

- src/generate/index.js
- src/generate/visitors/Component.js
See #150 – the consensus seems to be in favour of keeping `mount` out of the public API. We can always reverse the decision in future if there's a convincing need for it
> make mount private

- src/validate/js/index.js
- test/validate.js
- test/validator/export-default-duplicated/errors.json
- test/validator/export-default-duplicated/input.html
- test/validator/export-default-must-be-object/errors.json
- test/validator/export-default-must-be-object/input.html
This prevents confusing errors of the sort encountered in #188
> throw if default export is not an object literal

- src/generate/visitors/attributes/lookup.js
- test/generator/input-list/_config.js
- test/generator/input-list/main.html
Fixes #178 by using `setAttribute(...)` for `list` instead of updating the property
> use setAttribute() for list attributes

- src/index.js
- test/parse.js
Fixes a minor oversight – parse errors should be intercepted by `options.onerror` the same as validator errors etc. This allows build tool plugins to use `err.loc` and `err.frame` to provide useful and nicely formatted feedback about where the error is.
> intercept parse errors with options.onerror

- src/generate/css/process.js
- test/server-side-rendering/styles-nested/_actual.css
- test/server-side-rendering/styles/_actual.css
Fixes the issue I mentioned in #140 where the generated CSS has spaces prepended to it which does not currently help with sourcemaps.
> stop prepending CSS with spaces (fixes #140)

- src/validate/index.js
- test/validate.js
Ref #102. Doesn't exactly *fix* the issue – the CLI and build tool integrations will need to ensure that `options.name` is valid – but will make the resulting error a bit less mysterious.
> throw if options.name is illegal

- .gitignore
- src/generators/dom/index.js
- src/generators/dom/visitors/Component.js
- src/generators/dom/visitors/EachBlock.js
- src/generators/dom/visitors/Element.js
- src/parse/state/mustache.js
- test/generator/each-block-keyed/_config.js
- test/generator/each-block-keyed/main.html
- test/parser/each-block-keyed/input.html
- test/parser/each-block-keyed/output.json
This implements keyed updates, as discussed in #81. For now, it's a slightly naive implementation – it re-mounts each iteration every time the block updates, which in many cases is wasteful – but that's okay, since we can iterate on the performance aspects once we're happy that the behaviour is correct.
You opt in to keyed updates like so:
```html
{{#each todos as todo @id}}
<p>{{todo.description}}</p>
{{/each}}
```
In this case, if an item was removed from the middle of the `todos` array, all `<p>` elements would continue to represent the same todo item, *as long as each todo item had an `id` property*. (The property doesn't need to be called `id`, of course.)
<details>
<summary>sample code</summary>
```js
function renderMainFragment ( root, component ) {
var eachBlock_anchor = …
```
> Keyed updates

- package.json
- src/generators/dom/index.js
- test/generate.js
fixes #218. *Technically* a breaking change from 1.5.0, but since `options.standalone` isn't yet used anywhere I think we can get away with calling it 1.6.0
> allow custom path for helpers

- src/parse/state/tag.js
- test/parser/error-void-closing/error.json
- test/parser/error-void-closing/input.html
See #224. This handles the special case where someone tries to do something like `</input>`. It doesn't handle other unexpected closing tags, which will require a bit of extra work.
> provide useful feedback on encountering void element closing tag

- src/generators/dom/visitors/Element.js
- src/generators/dom/visitors/attributes/addElementAttributes.js
- src/generators/dom/visitors/attributes/binding/index.js
- src/shared/dom.js
It seems like there are a few more things that can be split off into shared functions to reduce code duplication. In this PR, I'm moving the `.addEventListener`, `.removeEventListener`, and `.setAttribute` calls into shared functions. This further decreases the (minified, ungzipped) code size.
> Move addEventListener, removeEventListener, setAttribute into shared

- src/generators/dom/index.js
If the `sharedPath` contains any special characters, the generated `import` statement is not correctly escaping them. This PR fixes that.
As an added bonus, unit tests pass on Windows again. Previously, the unit tests which used `shared` were generating
```javascript
import { things } from 'C:\some\path\svelte\shared.js'
```
which is the same as `'C:somepathsvelteshared.js'`, which reify rightfully balked at.
> Properly escape sharedPath in generated import statements

- src/generators/dom/visitors/attributes/addComponentAttributes.js
- test/generator/attribute-partial-number/Component.html
- test/generator/attribute-partial-number/_config.js
- test/generator/attribute-partial-number/main.html
Fixes #234 
Figured I'd finally fix one of these issues I'm reporting, let me know if there's any more tests that should be added to make sure this doesn't break anything.
> Fix partial numbers being detected as numbers

- src/generators/dom/index.js
- src/generators/dom/visitors/Component.js
- test/generator/component-yield-multiple-in-if/Widget.html
- test/generator/component-yield-multiple-in-if/_config.js
- test/generator/component-yield-multiple-in-if/main.html
> make yield renderer names globally unique

- src/generators/shared/css/transform.js
- test/generator/css-comments/_config.js
- test/generator/css-comments/main.html
Fixes #252, and insodoing reveals another odd way in which JSDOM behaves differently from browsers. We'll have to get round to submitting issues at some point, as these test cases are probably quite valuable, and I *really* can't be bothered to test with a headless browser
> handle multiline comments in CSS

- src/parse/state/tag.js
- src/utils/voidElementNames.js
- test/parser/elements/input.html
- test/parser/elements/output.json
Hi Svelte gang. I'm trying out svelte for the first time for some server-side rendering and I ran across this bug. I want to note that this is potentially my first open-source contribution. ✊ 
I am importing `index.html` via _svelte/ssr/register_, but the compiler throws a ParseError on the `<!doctype>` tag because the regular expression for valid tag names doesn't account for the leading `!`. For the same reason, "doctype" isn't recognized as a valid void element.
It's a pretty simple bug so I hope that this explanation is sufficient.
> Dont throw parse error on doctype declaration

- test/generator/onrender-fires-when-ready-nested/_config.js
- test/generator/onrender-fires-when-ready/_config.js
- test/generator/set-in-observe/_config.js
- test/generator/set-in-onrender/_config.js
- test/ssr.js
This adds the `skip-ssr` option for tests. This builds on top of #253 
There are a few tests that I think should pass and are issues with the SSR:
- component-binding
- component-binding-nested
- raw-mustaches
- component-yield
- svg-xmlns (waiting on #262)
- text-node-top-level
> [WIP] Skip some client tests for SSR

- src/generators/dom/visitors/attributes/addElementAttributes.js
- src/shared/dom.js
- test/generator/svg-xlink/_config.js
- test/generator/svg-xlink/main.html
- test/helpers.js
Initially I made it accept *any* namespaced attribute, but I'm not sure there are any valid explicit namespaces for attributes other than `xlink`, so in the interests of simplicity and minimising surface area for bugs, the distinction is between `setAttribute` and `setXlinkAttribute`. Easy to change later if nec
> handle xlink attributes

- src/generators/dom/visitors/attributes/addElementAttributes.js
- test/generator/svg-xmlns/_config.js
While working on #261 I found out that the client code doesn't actually set xmlns as an attribute, resulting in the outputted code to not have a namespace if converted to the string. The server handles this correctly.
> xmlns should be added as an attribute for consistency

- src/generators/dom/index.js
- src/generators/dom/visitors/attributes/binding/index.js
- src/shared/methods.js
- test/generator/onrender-chain/Item.html
- test/generator/onrender-chain/List.html
- test/generator/onrender-chain/_config.js
- test/generator/onrender-chain/main.html
Fixes #263. It does so by separating the public `set` method from the component-specific `_set` — `component.set(...)` calls `component._set(...)`, but then *flushes* the queue of `onrender` hooks (stored at the root instance) that were waiting until the component was in the DOM.
> always flush render hooks, even if initiator is a nested component

- src/generators/dom/index.js
- src/generators/dom/visitors/MustacheTag.js
Basically, anything that touches the DOM is slow. Because if that, this PR checks if any data changes before touching the DOM. 
You can see the performance by comparing the dbmonster built with this PR to the normal one: https://svelte-dbmonster-perf.surge.sh/dist/index.html
Here are some screenshots from my late 2012 i5 macbook pro:
The dbmonster based off this PR will jump up to 600fps, but the regular dbmonster doesn't go past 60fps. I'm not sure why the dbmonster based off this PR has such sudden fps jumps (although it doesn't drop below 60 for me.)
> Improve performance by checking that the data changes

- src/generators/Generator.js
- test/sourcemaps.js
- test/sourcemaps/basic/test.js
- test/sourcemaps/script/test.js
- test/sourcemaps/static-no-script/input.html
- test/sourcemaps/static-no-script/test.js
While investigating https://github.com/sveltejs/svelte/issues/293 it became apparent that Svelte needs more information to generate decent sourcemaps — namely, it needs to know where the output file is being generated so that it can populate the `sources` field correctly (or rather pass that information onto magic-string so that *it* can populate it correctly).
This mostly affects the CLI (e.g. rollup-plugin-svelte doesn't care about the sourcemap source as Rollup takes care of that sort of thing).
> add outputFilename option for sourcemap generation

- src/generators/dom/visitors/Component.js
- src/generators/dom/visitors/attributes/addComponentAttributes.js
- test/generator/component-events-each/Widget.html
- test/generator/component-events-each/_config.js
- test/generator/component-events-each/main.html
Component event handlers currently use `this.__svelte`, like DOM event handlers (where `this` is the component/element). `this.__svelte` doesn't exist on components (and maybe shouldn't since it's just a convenient way to store references in the DOM?)
> [WIP] failing test for first bug in #290

- src/generators/shared/processCss.js
- src/parse/read/style.js
- test/generator/css-space-in-attribute/_config.js
- test/parse.js
- test/parser/css/output.json
- test/parser/error-css/error.json
- test/parser/error-css/input.html
A few tweaks to how CSS is handled — the AST is generated at parse time (necessary if we're to do any validation on it) and tidied up and turned into a POJO, because that's slightly easier to work with than the native css-tree format. Any errors that happen at parse time are normalised so that they get the same code frame etc as syntax errors elsewhere
> Normalise CSS parse errors

- src/generators/Generator.js
- src/generators/dom/index.js
- src/generators/dom/visitors/EachBlock.js
- src/generators/dom/visitors/Element.js
- src/generators/dom/visitors/MustacheTag.js
- src/generators/dom/visitors/RawMustacheTag.js
- src/generators/dom/visitors/Text.js
- src/generators/dom/visitors/attributes/addElementAttributes.js
- src/generators/dom/visitors/attributes/binding/index.js
- test/generate.js
- test/generator/deconflict-builtins/_config.js
- test/generator/deconflict-builtins/get.js
- test/generator/deconflict-builtins/main.html
- test/ssr.js
Fixes one aspect of #222, wherein this...
```html
<script>
import { get } from 'ajax';
export default {...};
</script>
```
...would create a conflict between the user's import and Svelte's built-in import in the case of shared helpers. Credit to @Swatinem who was right (as usual 😀 ) to point out that a method for creating helper aliases on-demand was the best way to use shared helpers.
> Deconflict shared helpers with user imports

- src/generators/Generator.js
- src/generators/dom/index.js
- src/generators/dom/visitors/Component.js
- src/generators/dom/visitors/EachBlock.js
- src/generators/dom/visitors/IfBlock.js
- src/generators/server-side-rendering/visitors/EachBlock.js
- test/generator/deconflict-contexts/_config.js
- test/generator/deconflict-contexts/main.html
Fixes the remaining bug in #222/#251, whereby code like this...
```html
{{#each components as component}}
<li>{{component}}</li>
{{/each}}
```
...would blow up because `component` is 'special'. It does so by renaming the context introduced by the `each` block to something safe.
> Deconflict each-blocks contexts with reserved words

- src/generators/dom/visitors/attributes/binding/index.js
- test/generator/binding-textarea/_config.js
- test/generator/binding-textarea/main.html
Part of #10. More to do (but in a separate PR, as these may require some investigation):
> use input events for two-way binding with textareas and non-checkbox/radio inputs

- .gitignore
- src/parse/state/tag.js
- test/parse.js
- test/parser/implicitly-closed-li/input.html
- test/parser/implicitly-closed-li/output.json
Starting to dig into #258 and #224 and related issues. As a starting point, Svelte needs to do a better job of handling situations like these:
```html
<div><p>some text</div>
<ul>
<li>a
<li>b
<li>c
</ul>
```
This PR addresses both cases, by noting which elements are forbidden from containing which other elements, and by closing all currently open elements until the one that corresponds to a particular closing tag
> handle implicitly closed elements

- src/generators/dom/index.js
- src/generators/dom/visitors/attributes/binding/index.js
- test/generator/dev-warning-missing-data-binding/_config.js
- test/generator/dev-warning-missing-data-binding/main.html
Ref #249. If a template has a binding...
```html
<input bind:value>
```
...and the component is initialised without a value for `value`, an error will be thrown in dev mode.
(Also fixes my *ahem* [deliberate mistake](https://github.com/sveltejs/svelte/pull/320/files#diff-63b1c2c951c4dda845ff23351e808431R309) in the last PR)
> throw error in dev mode for missing bound properties (#249)

- src/generators/dom/index.js
- test/generate.js
Ref #177. `options.target` is required (for top-level components), but it doesn't make sense to include the check for every component if not in dev mode
> throw in dev mode if options.target is absent

- src/parse/read/directives.js
- test/parser/error-event-handler/error.json
- test/parser/error-event-handler/input.html
Ref #220. Rather than using Acorn's tokenizer to determine when an expression has ended, we read each character until we get to a quote mark (for quoted event directives) or a whitespace character (for unquoted ones), handling escaped quote marks as necessary. Then, we parse the whole lot as a program.
This avoids cryptic errors like 'unterminated string constant' and allows us to give more useful feedback.
> better errors for malformed event handlers 

- src/generators/dom/index.js
Fixes #342. I'm not *entirely* thrilled with the wording of this error message.
Putting this check in `._set` as opposed to in `.set` seemed to be the most straightforward, as there's not really a good mechanism for having different versions of the helper functions themselves in dev vs regular mode.
> typecheck argument in _set when in dev mode

- src/generators/dom/index.js
This fixes #337, but also fixes the situation [here](https://svelte.technology/repl/?version=1.10.0&gist=b178c0560c9783bc983a154659553fb4). If you import things that conflict with helpers, but are not using shared helpers, these helpers will be aliased where they are used, but they will not be aliased where they are actually defined.
> deconflict helpers when not using shared helpers

- src/parse/read/script.js
This resolves issue #344.
When the Svelte library is included inline in an HTML document, this line closes the HTML script block unexpectedly.
This prevents that from happening, and also prevents (most) minifiers from converting it back to `'</script>'`, which is why `'</scr' + 'ipt>'` was not used.
> Resolved embedded Svelte library breaking HTML document

- src/generators/dom/index.js
A `let` has snuck by the in the generated code for adding css:
Input:
```html
<h1>Hello {{name}}!</h1>
<style>
h1 {
color: red;
}
</style>
```
Output:
```js
let addedCss = false;
function addCss () {
var style = createElement( 'style' );
style.textContent = "\n  h1[svelte-895830737], [svelte-895830737] h1 {\n    color: red;\n  }\n";
appendNode( style, document.head );
addedCss = true;
}
function renderMainFragment ( root, component ) {
// ...
```
It is sneaking by the ES5 syntax check in the tests (introduced in #82) because the css block is appended before the starting point of the check, `renderMainFragment`. I played with possible ways of updating the check, but I couldn't find a non-hacky approach since there are few types of blocks that may appear (at least `applyComputations` and …
> Remove ES2015 let from css block

- src/index.js
As per the recommendation of @PaulBGD, I have changed the `create` API method to use `new Function` instead of an indirect eval.
All existing tests pass as expected, and real world implementation tests behave the same.
> Changed `create` API method to use `new Function()`

- package.json
css-tree 1.0.0-alpha17 introduces some non backwards compatible changes. The path in the package to the walker changes (from `css-tree/lib/utils/walk.js` to `css-tree/lib/walker/index.js`) and its API changes. I tried to update Svelte to work with the new version, but was unable to do so quickly. So I think we should pin at this version, and then revisit this later once its API has settled down.
> pin css-tree at 1.0.0-alpha16

- src/generators/dom/index.js
- test/generator/samples/deconflict-non-helpers/_config.js
- test/generator/samples/deconflict-non-helpers/main.html
- test/generator/samples/deconflict-non-helpers/module.js
Should resolve #388. This could probably do with some unit tests still though,
> Deconflict non helper functions

- README.md
When I was writing this up I wasn't thinking about how generating SSR code defaulted to CommonJS format.
> Note different default format for SSR

- src/generators/dom/index.js
- src/utils/removeObjectKey.js
- test/generator/samples/imported-renamed-components/main.html
I realized my change in #390 didn't correctly handle the case when you are removing the last key in an object and it has a trailing comma. Previously, it would leave the comma, which would lead to malformed output. Now we're removing all the way up to the end of the object node, which seems like the best way to make sure we get the comma, if present.
> Fix removing last key in object when it has a trailing comma

- src/parse/read/expression.js
- test/generator/samples/attribute-dynamic-reserved/_config.js
- test/generator/samples/attribute-dynamic-reserved/main.html
The changes in #385 caused undesirable behavior with tags like `{{123}}`. Since `123` matches `/^\w+$/`, this is now turned into `root.123`.
This PR restricts the special handling only to tags made up of all lowercase letters, which will cover all the cases where the tag is a reserved word. Other cases will continue to be parsed by Acorn.
> Only do special reserved name handling when tag is all lowercase letters

- src/generators/Generator.js
- src/generators/annotateWithScopes.js
- src/generators/dom/index.js
- src/generators/dom/visitors/Component.js
- src/generators/dom/visitors/attributes/addElementAttributes.js
- src/generators/server-side-rendering/index.js
- src/generators/server-side-rendering/visitors/Component.js
- test/generator/samples/deconflict-template-1/_config.js
- test/generator/samples/deconflict-template-1/main.html
- test/generator/samples/deconflict-template-1/module.js
- test/generator/samples/deconflict-template-2/_config.js
- test/generator/samples/deconflict-template-2/main.html
This isn't a particularly graceful solution. We simply make sure we avoid conflicts with *all* identifiers in the component's source, instead of just the ones that would actually collide with us. The code for determining the set of all identifiers lives inline in the case where we need it (when the `export default` isn't the last thing in the script), but it could be moved elsewhere if we end up needing this functionality anywhere else.
> Deconflict `template` variable (#392)

- src/generators/dom/visitors/attributes/addElementBinding.js
- test/generator/samples/binding-input-radio-group/_config.js
I have removed the code that sets the radio input's state to unchecked. Browsers already toggle the state correctly for members of the same radiogroup.
> Fix: binding input radio group #399

- rollup/rollup.config.main.js
- rollup/rollup.config.ssr.js
Many of the transforms being done by Buble aren't required for Node 4. Disabling them is nicer, and also slightly decreases the size of the bundle - down from 385KB to 375KB.
> Disable Buble transforms not needed for Node 4

- .gitignore
- src/generators/Generator.js
- src/generators/dom/index.js
- src/generators/server-side-rendering/index.js
- test/css/index.js
- test/css/samples/basic/expected.css
- test/css/samples/basic/input.html
Nice simple solution to #409. Eventually we'll need to get CSS sourcemaps working as well, but this is a good first step which should hopefully enable tooling like rollup-plugin-svelte to make server-rendering CSS a bit easier.
> include css in compiler output

- src/generators/dom/index.js
- src/shared/index.js
- test/generator/samples/computed-values-function-dependency/_config.js
- test/generator/samples/computed-values-function-dependency/main.html
Fixes #413. While I was at it, renamed `applyComputations` to the less sesquipedalian `recompute`.
> recompute computed values with functions as dependencies

- src/generators/dom/visitors/attributes/addComponentBinding.js
- test/generator/samples/component-binding-deep/Widget.html
- test/generator/samples/component-binding-deep/_config.js
- test/generator/samples/component-binding-deep/main.html
fixes #420, still have to make a test for this
> Fixes #420

- src/generators/dom/visitors/attributes/addComponentBinding.js
- src/generators/dom/visitors/attributes/addElementBinding.js
- src/generators/dom/visitors/attributes/binding/getSetter.js
- src/utils/flattenReference.js
- test/generator/samples/component-binding-deep-b/ComponentSelector.html
- test/generator/samples/component-binding-deep-b/Editor.html
- test/generator/samples/component-binding-deep-b/_config.js
- test/generator/samples/component-binding-deep-b/main.html
- test/sourcemaps/samples/binding/test.js
This fixes a slightly brain-bending bug encountered while working on the next version of the REPL, whereby bindings could end up mutating the wrong object. Fun times.
> prevent hard-to-reproduce bug with deep two-way bindings

- src/validate/js/index.js
- test/validator/samples/import-root/errors.json
- test/validator/samples/import-root/input.html
That the root context is called `root` is ingrained pretty deeply, and it seems difficult to deconflict this with an import of `root`. So for now it's probably best to simply disallow this entirely during validation.
> disallow `import root` during validation

- src/generators/dom/visitors/attributes/addElementAttributes.js
- test/generator/samples/event-handler-custom-node-context/_config.js
- test/generator/samples/event-handler-custom-node-context/main.html
> Bind callback passed to custom events to the node context

- src/parse/read/expression.js
- test/generator/samples/attribute-prefer-expression/_config.js
- test/generator/samples/attribute-prefer-expression/main.html
> Treat literals as special cases when parsing

- src/parse/read/script.js
- test/parser/index.js
- test/parser/samples/error-script-unclosed/error.json
- test/parser/samples/error-script-unclosed/input.html
Sometimes in the REPL you'll start writing a `<script>` tag, and before you get a chance to close it the compiler goes haywire. This PR prevents that
> Prevent unclosed <script> causing infinite loop

- src/generators/Generator.js
- src/generators/dom/index.js
- src/generators/dom/utils/findBlock.js
- src/generators/dom/visitors/Component.js
- src/generators/dom/visitors/EachBlock.js
- src/generators/dom/visitors/Element.js
- src/generators/dom/visitors/IfBlock.js
- src/generators/dom/visitors/MustacheTag.js
- src/generators/dom/visitors/RawMustacheTag.js
- src/generators/dom/visitors/attributes/addElementAttributes.js
- src/generators/dom/visitors/attributes/addElementBinding.js
- test/generator/index.js
Ref #419. Figured we may as well create a PR for this branch — will hold off on merging until we resolve this question:
> The way that the `tmp` (formerly `__tmp`) identifier is now being handled in the branch feels like it *might* lead to conflicts. Better probably would be to just generate it (with `generator.current.getUniqueName`) once, store it somewhere on the generator, and then use that in the other places where we need it, similar to how the deconflicted name for `component` is being handled.
> use snake case in generated identifiers (#419)

- src/generators/dom/index.js
- src/shared/index.js
- test/generator/index.js
This fixes #431. It adds ~100 bytes to an app (presumably less after gzip), so there's an argument against doing it, but it does mean that people stuck supporting IE11 and old Android phones don't need to do anything extra to get their Svelte apps running.
Thoughts? Should it be behind a `legacy` option, or is that unwanted complexity?
> use assign helper, to avoid compatibility headaches

- src/generators/dom/index.js
- src/index.js
- test/generator/index.js
This changes prototype assignments from this...
```js
// not shared, no custom methods
Foo.prototype.get = get;
Foo.prototype.fire = fire;
Foo.prototype.observe = observe;
Foo.prototype.on = on;
Foo.prototype.set = set;
Foo.prototype._flush = _flush;
// shared, no custom methods
Foo.prototype = assign( {}, proto );
// not shared, custom methods
Foo.prototype = template.methods; 
Foo.prototype.get = get;
Foo.prototype.fire = fire;
Foo.prototype.observe = observe;
Foo.prototype.on = on;
Foo.prototype.set = set;
Foo.prototype._flush = _flush;
// shared, custom methods
Foo.prototype = assign( {}, template.methods, proto );
```
...to this:
```js
// not shared, no custom methods
assign( Foo.prototype, {
get: get,
fire: fire,
observe: observe,
on: on,
set: set,
_flush: _flush
});
// shared, no …
```
> better prototype assignment

- src/utils/removeObjectKey.js
- test/generator/samples/attribute-partial-number/main.html
#442 (part two) — Svelte now removes properties from objects the same way a human would. Probably overkill but quite satisfying... will probably make sense to abstract this into a general purpose node removal function that can be used for eliminating `import` declarations and default exports with no remaining purpose.
> generate more idiomatic code when removing object properties

- src/generators/dom/index.js
- test/generator/samples/computed-empty/_config.js
- test/generator/samples/computed-empty/main.html
Fixes #452.
Referencing `computations.length` instead of `templateProperties.computed` prevents the generator from adding in invalid code when an empty object is passed as the `computed` value.
I've added a (passing) test that ensures that the component instantiates while having an empty `computed` object.
> Fixed empty component 'computed' from throwing error.

- src/generators/dom/visitors/Element/Attribute.js
- src/generators/dom/visitors/Element/Element.js
- test/runtime/samples/select-one-way-bind-object/_config.js
- test/runtime/samples/select-one-way-bind-object/main.html
Fixes #423. Little bit inelegant but it's an awkward special case — we need to ensure that the attribute is updated *after* child option nodes are updated.
> correctly bind one-way select value attributes (#423)

- src/validate/js/propValidators/methods.js
- src/validate/js/utils/checkForAccessors.js
- test/validator/index.js
- test/validator/samples/properties-methods-getters-setters/errors.json
- test/validator/samples/properties-methods-getters-setters/input.html
closes #425. Only checks `methods`, but can easily be added to other properties if we see fit
> better error for attempts to use getters/setters for methods

- src/generators/dom/visitors/Text.js
- test/runtime/samples/select-no-whitespace/_config.js
- test/runtime/samples/select-no-whitespace/main.html
This doesn't *close* #189 as there is more to do, but it addresses some of the low-hanging fruit — avoiding whitespace nodes inside elements that can't contain text, like `<select>` and `<ul>`
> don't create whitespace nodes inside elements like <select>

- src/generators/dom/index.js
- src/utils/CodeBuilder.js
- test/js/samples/computed-collapsed-if/expected.js
- test/js/samples/computed-collapsed-if/input.html
Ref #450. Adds a new `addConditionalLine` method to `CodeBuilder` which collapses things like this...
```js
if ( foo ) {
bar();
}
if ( foo ) {
baz();
}
```
...into things like this:
```js
if ( foo ) {
bar();
baz();
}
```
Only used inside `recompute` for now, but could probably be used elsewhere as well.
> collapse consecutive if-statements with the same condition (#450)

- src/generators/Generator.js
- src/validate/index.js
- src/validate/js/propValidators/components.js
- test/validator/index.js
Fixes #451; also adds warning if `options.name` doesn't begin with a capital letter, as that is what triggered #451 to begin with.
> Avoid component name as global identifier

- src/generators/dom/visitors/Element/meta/Window.js
- test/runtime/samples/window-bind-scroll-update/_config.js
- test/runtime/samples/window-bind-scroll-update/main.html
Ref #404. With this PR, in a situation like this...
```html
<:Window bind:scrollY='y'/>
```
...changing the value of `y` programmatically will result in the window scrolling. (The value of `y` remains constrained to the scrollable range.)
In a lot of situations this kind of bidirectional binding is unnecessary, but it would violate expectations if it didn't work this way so I think it's worth the modest overhead, which basically amounts to this:
```diff
+var window_updating = false;
var onwindowscroll = function ( event ) {
+  window_updating = true;
component.set({
y: this.scrollY
});
+  window_updating = false;
};
window.addEventListener( 'scroll', onwindowscroll );
+component.observe( 'y', function ( y ) {
+  if ( window_updating ) return;
+  window.scrollTo( window.scrollX, y );
+}); …
```
> window scroll bindings are bidirectional

- src/generators/Generator.js
- src/generators/dom/index.js
- test/runtime/samples/dev-warning-missing-data-binding/_config.js
- test/runtime/samples/dev-warning-missing-data/_config.js
- test/runtime/samples/dev-warning-missing-data/main.html
Fixes #475 - makes missing properties a warning instead of a fatal error, and makes missing properties that would be whitelisted globals not even be a warning.
> Make missing properties only a warning

- src/generators/Generator.js
- src/generators/dom/Block.js
- src/generators/dom/index.js
- src/generators/dom/preprocess.js
- src/generators/dom/visitors/Component/Attribute.js
- src/generators/dom/visitors/Component/Binding.js
- src/generators/dom/visitors/Component/Component.js
- src/generators/dom/visitors/Component/EventHandler.js
- src/generators/dom/visitors/EachBlock.js
- src/generators/dom/visitors/Element/Attribute.js
- src/generators/dom/visitors/Element/Binding.js
- src/generators/dom/visitors/IfBlock.js
- src/generators/dom/visitors/MustacheTag.js
- src/generators/dom/visitors/RawMustacheTag.js
- src/generators/dom/visitors/YieldTag.js
- src/generators/server-side-rendering/Block.js
- src/generators/server-side-rendering/visitors/Component.js
- src/generators/server-side-rendering/visitors/EachBlock.js
- src/generators/server-side-rendering/visitors/Element.js
- src/generators/server-side-rendering/visitors/IfBlock.js
- src/generators/server-side-rendering/visitors/MustacheTag.js
- src/generators/server-side-rendering/visitors/RawMustacheTag.js
- test/js/index.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/each-block-changed-check/input.html
Ref #381. So far, I'm just refactoring the each-block code, because it's grown a little bit wild and woolly. The work done for this PR (identifying which dependencies a fragment has) should also support #472
> Only update each blocks when their dependencies have changed

- src/validate/html/index.js
- src/validate/html/validateElement.js
- src/validate/html/validateWindow.js
- src/validate/index.js
- src/validate/js/index.js
- test/validator/samples/binding-invalid-on-element/errors.json
- test/validator/samples/binding-invalid-on-element/input.html
- test/validator/samples/binding-invalid/errors.json
- test/validator/samples/binding-invalid/input.html
This started out as a PR for #406, but I figured we ought to do some validation on bindings before adding any more of them.
> validate bindings

- src/generators/dom/visitors/Element/meta/Window.js
- test/runtime/samples/window-event-context/_config.js
- test/runtime/samples/window-event-context/main.html
Discovered while working on #496 — `<:Window>` events can't access component state (at least, not correctly). This fixes that.
> allow window events to access state

- src/generators/dom/visitors/Element/Binding.js
This PR fixes an issue where a `select` element is not set to the correct value on the initial creation of a component.
Mainly done in response to [@saibotsivad](https://gitter.im/sveltejs/svelte?at=58f679b0cfec91927250e250), but I have also experienced this behavior when writing Svelte components with `select` elements.
This snippet simply forces the select item to update after the `each_block` has been rendered, allowing `select.value` to be set.
I have not included the test that @saibotsivad created to prevent plagiarism.
/cc @saibotsivad
> Initialize select element `value` upon creation of component.

- src/generators/dom/visitors/EachBlock.js
- src/generators/dom/visitors/Element/Binding.js
- test/runtime/samples/binding-input-checkbox-group-outside-each/_config.js
- test/runtime/samples/binding-input-checkbox-group-outside-each/main.html
- test/runtime/samples/each-block-dynamic-else-static/_config.js
- test/runtime/samples/each-block-dynamic-else-static/main.html
#498 was actually a twofer — if a dynamic each block has a static else block, then it's possible to create a situation where Svelte tries to update the else block (which doesn't have an `update` method). This fixes that.
> allow dynamic each-block to have static else-block

- src/generators/dom/visitors/Element/Binding.js
Fixes a bug with audio bindings — when replaying an ended audio track, it should return to the start, but because each of `currentTime`, `duration` and `paused` had their own 'lock' variables, state was getting out of sync with the DOM. Fixed by sharing a lock variable between all bindings on the same element.
It *does* mean we have `var audio_updating = false` repeated once per binding. I think the solution to that would be to add a `block.addVariable` method that declares all (or most) variables in a single block at the top — this would also make the code marginally easier to read (in my opinion):
```js
// before
var p = createElement( 'p' );
var text_value = root.foo;
var text = createText( text_value );
appendNode( text, p );
var text_1 = createText( "\n" );
var p_1 = createElement( …
```
> prevent bindings interfering with each other on the same element

- src/generators/dom/Block.js
- src/generators/dom/visitors/Component/Binding.js
- src/generators/dom/visitors/Element/Attribute.js
- src/generators/dom/visitors/Element/Binding.js
- src/generators/dom/visitors/Element/meta/Window.js
- src/generators/dom/visitors/MustacheTag.js
- test/js/samples/collapses-text-around-comments/expected.js
- test/js/samples/each-block-changed-check/expected.js
fixes #504 — results in *slightly* more readable code without the possibility of variables being initialised more than once
> hoist variables where appropriate

- src/generators/Generator.js
- src/generators/dom/preprocess.js
- src/generators/dom/visitors/Component/Binding.js
- src/generators/dom/visitors/Component/Component.js
- src/generators/dom/visitors/Component/EventHandler.js
- src/generators/dom/visitors/Element/Element.js
- src/generators/dom/visitors/Element/EventHandler.js
- src/generators/dom/visitors/Element/meta/Window.js
- src/generators/server-side-rendering/Block.js
- src/generators/server-side-rendering/index.js
- src/generators/server-side-rendering/visitors/Component.js
- src/utils/reservedNames.js
- src/validate/js/index.js
- src/validate/js/propValidators/components.js
- test/js/samples/collapses-text-around-comments/expected.js
- test/js/samples/computed-collapsed-if/expected.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/event-handlers-custom/expected.js
- test/js/samples/if-block-no-update/expected.js
- test/js/samples/if-block-simple/expected.js
- test/runtime/samples/state-deconflicted/_config.js
- test/runtime/samples/state-deconflicted/main.html
- test/validator/samples/component-cannot-be-called-state/errors.json
- test/validator/samples/component-cannot-be-called-state/input.html
- test/validator/samples/import-root/errors.json
- test/validator/samples/import-root/input.html
This scratches a long-standing itch (#507) and fixes a bug whereby this would fail:
```html
{{#each roots as root}}
{{root}}
{{/each}}
```
The `state` equivalent now works, as `state` is treated as a reserved word.
> rename root to state, and allow state to be used as context

- test/runtime/samples/select-change-handler/_config.js
- test/runtime/samples/select-change-handler/main.html
These two REPL issues:
* https://svelte.technology/repl?version=1.17.2&gist=eb693d0f85a05e17500fcce2a5aea647
* https://svelte.technology/repl?version=1.17.2&gist=5ec3e1ac9df113d4719fdfe3854b75da
The `on:change` event does not fire with the updated value, it fires with the previous value.
> failing test for bound event handler on <select> elements

- src/generators/dom/visitors/Element/Element.js
- test/runtime/samples/select-change-handler/_config.js
- test/runtime/samples/select-change-handler/main.html
I'm marking this [WIP] because I'm a little unsure of my change here still, but also because the unit test is still failing for some reason. I see some other unit tests involving `<select>` have been disabled, apparently because of limitations or bugs in jsdom.
The specific test cases ([REPL](https://svelte.technology/repl?version=1.17.2&gist=eb693d0f85a05e17500fcce2a5aea647), [REPL](https://svelte.technology/repl?version=1.17.2&gist=5ec3e1ac9df113d4719fdfe3854b75da)) seem to work with this change when they're compiled and manipulated manually - and no other unit tests break.
The idea in the PR is to move _all_ of the attribute handling of `<select>` elements (attaching event handlers, etc) after the code for handling its children - but within that code generated by visiting the …
> [WIP] Fix select change handler

- src/generators/dom/visitors/IfBlock.js
- test/js/samples/if-block-simple/expected.js
- test/js/samples/use-elements-as-anchors/expected.js
- test/runtime/samples/if-block-or/_config.js
- test/runtime/samples/if-block-or/main.html
Fixes #532 by always wrapping the condition in simple if blocks in parentheses.
> fix simple if blocks with top-level or conditions (#532)

- src/parse/read/expression.js
- test/runtime/samples/paren-wrapped-expressions/_config.js
- test/runtime/samples/paren-wrapped-expressions/main.html
Fixes #534. [Acorn's docs](https://github.com/ternjs/acorn#main-parser) do warn that the the `ParenthesizedExpressions` nodes created when the `preserveParens` option is enable are non-standard, but using this does not seem to have ill effects. Svelte is still able to walk the tree and rewrite the expressions appropriately according to the context.
> fix parsing of expressions wrapped in parentheses (#534)

- src/generators/dom/visitors/Element/Binding.js
- test/runtime/samples/binding-select-initial-value/_config.js
- test/runtime/samples/binding-select-initial-value/main.html
- test/runtime/samples/binding-select-multiple/_config.js
- test/runtime/samples/binding-select/_config.js
- test/runtime/samples/select-change-handler/_config.js
- test/runtime/samples/select-one-way-bind-object/_config.js
Fixes #539.
For better compatibility with older browsers (and jsdom before v10). I made a few changes to the tests which were previously disabled, resolving inconsistencies which I assume came about since they didn't run in the first place. You may wish to verify that my assumptions are accurate, though.
While I've updated it to add the `multiple` attribute, the `binding-select-multiple` test is still failing in jsdom. I think I may have found the cause and will investigate further.
I've also tested the code in Firefox, Chrome and Safari. I'm not able to boot a Windows VM at the moment, so I'm hoping that IE and Edge behave as they should here.
> Use .querySelector(':checked') instead of .selectedOptions, enable several <select> tests

- src/generators/dom/index.js
- src/generators/dom/sharedNames.js
Fixes #538 - admittedly a picky thing, but it was bound to be a problem sometime, and is currently stopping us from upgrading to Acorn 5.
> correctly handle when helper functions have been internally renamed (#538)

- src/generators/dom/visitors/IfBlock.js
- test/js/samples/if-block-no-update/expected.js
> generate less code for if-blocks with else-blocks

- src/generators/dom/visitors/YieldTag.js
- test/runtime/samples/component-yield-placement/Modal.html
- test/runtime/samples/component-yield-placement/_config.js
- test/runtime/samples/component-yield-placement/main.html
> Fix yield block placement

- src/generators/dom/visitors/Element/addTransitions.js
- src/shared/transitions.js
- test/runtime/samples/transition-js-delay-in-out/_config.js
- test/runtime/samples/transition-js-delay-in-out/main.html
- test/runtime/samples/transition-js-delay/_config.js
- test/runtime/samples/transition-js-delay/main.html
- test/runtime/samples/transition-js-dynamic-if-block-bidi/_config.js
Fixes #562, by separating the transition object from the *program* (a transition could have multiple programs if it's bidirectional and flips back and forth, and a program will continue until its delayed replacement starts)
> Fix delays on bidirectional transitions

- src/generators/dom/Block.js
- src/generators/dom/visitors/EachBlock.js
- src/shared/dom.js
- test/helpers.js
- test/js/samples/each-block-changed-check/expected.js
- test/runtime/samples/each-block-keyed-dynamic/_config.js
- test/runtime/samples/each-block-keyed-dynamic/main.html
- test/runtime/samples/each-block-keyed-random-permute/_config.js
- test/runtime/samples/each-block-keyed-random-permute/main.html
- test/runtime/samples/transition-js-each-block-keyed-intro-outro/_config.js
- test/runtime/samples/transition-js-each-block-keyed-intro-outro/main.html
- test/runtime/samples/transition-js-each-block-keyed-outro/_config.js
Will explain this work in #373. The placement of outroing nodes is still wrong — that's the final part, and my brain is too melted at this point to figure it out.
> ensure outroing each block iterations don't jump to the top

- src/generators/dom/visitors/IfBlock.js
- test/js/samples/if-block-no-update/expected.js
- test/js/samples/if-block-simple/expected.js
- test/js/samples/use-elements-as-anchors/expected.js
- test/runtime/samples/component-if-placement/Component.html
- test/runtime/samples/component-if-placement/_config.js
- test/runtime/samples/component-if-placement/main.html
Fixes #569, but ensuring that if-block anchors are mounted *after* the if-block contents (the anchors are needed for updating — i.e. if a block is added/removed — rather than for the initial mounting)
> Fix insertion order of if blocks and their anchors

- src/generators/dom/visitors/IfBlock.js
Fixes a bug I just saw in the REPL
> fix destruction of compound if blocks with outros

- src/generators/dom/visitors/Element/Element.js
- test/runtime/samples/select-props/_config.js
- test/runtime/samples/select-props/main.html
> On `<select>`, don't try generating prop code until visiting attributes

- package.json
- src/generators/dom/interfaces.ts
- src/generators/shared/utils/getGlobals.ts
- src/generators/shared/utils/getIntro.ts
- tsconfig.json
Continuing the work done in https://github.com/sveltejs/svelte/pull/573 this PR fixes further typing errors
> Fix some typing errors

- src/generators/dom/visitors/EachBlock.js
very minor fixes to `each-block-keyed`:
* initiating `{$last}` variable to null
* removing redundant `{$expected} ? ...` checks inside the `if ({$expected}) ...` loop
* removing one unnecessary cycle in the deletion loop `while{} vs do {} while`
* removing the `next.last <=> last.next` reconnections in `outro` since the update loop already resets the links with `iteration.last = last; last.next=iteration`
All test passing but the last point may be risky since I don't fully understand all the different ways that outro gets called.
> minor fixes - redundant conditions and loops

- src/generators/dom/visitors/Element/Element.ts
- src/generators/dom/visitors/Element/lookup.ts
- src/generators/server-side-rendering/visitors/Element.ts
- src/parse/state/tag.ts
- src/validate/html/validateElement.ts
- test/parser/samples/textarea-children/input.html
- test/parser/samples/textarea-children/output.json
- test/runtime/samples/textarea-children/_config.js
- test/runtime/samples/textarea-children/main.html
- test/runtime/samples/textarea-value/_config.js
- test/runtime/samples/textarea-value/main.html
- test/server-side-rendering/samples/textarea-children/_expected.html
- test/server-side-rendering/samples/textarea-children/main.html
- test/server-side-rendering/samples/textarea-value/_expected.html
- test/server-side-rendering/samples/textarea-value/main.html
- test/validator/samples/textarea-value-children/errors.json
- test/validator/samples/textarea-value-children/input.html
This primarily fixes #582, but also address some other behaviour around textareas:
```html
<textarea value='{{foo}}'/>
<textarea>{{foo}}</textarea>
```
A textarea with both a value attribute *and* children will fail validation.
As a corollary to the above:
```html
<textarea>
<p>surprise! this isn't an element</p>
</textarea>
<textarea value="\n\t<p>surprise! this isn't an element</p>\n"/>
```
Before (incorrect):
```html
<textarea value="42"></textarea>
```
After:
```html
<textarea>42</textarea>
```
> Better handling of textareas

- src/generators/Generator.ts
- src/validate/html/index.ts
- test/runtime/samples/helpers-not-call-expression/_config.js
- test/runtime/samples/helpers-not-call-expression/main.html
- test/validator/samples/helper-clash-context/input.html
- test/validator/samples/helper-clash-context/warnings.json
> always use helpers if referenced, not just for CallExpressions, and warn on context clashes

- src/generators/dom/visitors/Component/Binding.ts
- src/generators/dom/visitors/Element/Binding.ts
- src/generators/dom/visitors/shared/binding/getSetter.ts
- src/parse/read/directives.ts
- test/parser/samples/error-binding-rvalue/error.json
- test/parser/samples/error-binding-rvalue/input.html
- test/runtime/samples/binding-input-text-deep-computed-dynamic/_config.js
- test/runtime/samples/binding-input-text-deep-computed-dynamic/main.html
- test/runtime/samples/binding-input-text-deep-computed/_config.js
- test/runtime/samples/binding-input-text-deep-computed/main.html
- test/runtime/samples/binding-input-text-deep-contextual-computed-dynamic/_config.js
- test/runtime/samples/binding-input-text-deep-contextual-computed-dynamic/main.html
Fixes #602. This PR allows binding to computed member expressions:
```html
<select bind:value='prop'>
<option>foo</option>
<option>bar</option>
<option>baz</option>
</select>
<input bind:value='obj[prop]'>
<pre>
{{JSON.stringify(obj)}}
</pre>
```
[Demo](https://svelte.technology/repl?version=local&gist=7d46a89da34540ad907f411e9ff9a38c) (won't work until this is released...)
Probably most useful when binding to properties that can't be written using dot notation where you don't control the structure of the data (`user["last-name"]` or whatever), but will work with arbitrarily complex member expressions.
> support binding to computed member expressions

- package.json
- src/generators/Generator.ts
- src/generators/dom/visitors/Element/Element.ts
- src/generators/server-side-rendering/index.ts
- src/generators/server-side-rendering/visitors/Element.ts
- src/generators/shared/processCss.ts
- src/interfaces.ts
- test/css/index.js
- test/css/samples/cascade-false-global-keyframes/expected.css
- test/css/samples/cascade-false-global-keyframes/input.html
- test/css/samples/cascade-false-global/_config.js
- test/css/samples/cascade-false-global/expected.css
- test/css/samples/cascade-false-global/input.html
- test/css/samples/cascade-false-keyframes/expected.css
- test/css/samples/cascade-false-keyframes/input.html
- test/css/samples/cascade-false/_config.js
- test/css/samples/cascade-false/expected.css
- test/css/samples/cascade-false/input.html
Addresses #583 by adding a `cascade` option. If `cascade` is false, and a component has a `<style>` attribute, *all* elements get the `svelte-123xyz` attribute (not just the component's top-level elements), and selectors are transformed in such a way that they only apply to the component's own elements, *not* to child components.
This seems to be more in line with the wider community's expectations of how CSS scoping should work, and makes it easier to do certain forms of analysis such as identifying redundant selectors, and omitting the `svelte-123xyz` attribute on nodes that won't benefit from it. I'm therefore proposing that we remove the option in v2 and *never* cascade styles, unless selectors have been wrapped with the `:global(...)` escape hatch (which is the convention used by …
> add cascade option, to prevent components inheriting styles

- package-lock.json
- package.json
- src/generators/dom/visitors/YieldTag.ts
- test/helpers.js
- test/runtime/index.js
- test/runtime/samples/component-nested-deep/Level1.html
- test/runtime/samples/component-nested-deep/Level2.html
- test/runtime/samples/component-nested-deep/Level3.html
- test/runtime/samples/component-nested-deep/_config.js
- test/runtime/samples/component-nested-deep/main.html
Fixes #625.
Also makes the printout of compiled code a bit easier to read. Haven't spent any time fixing it yet (though I assume somewhere a component is being destroyed before it's being unmounted)
> Unmount `yield` fragments in parent's unmount method, not destroy

- src/generators/dom/visitors/Element/Binding.ts
- src/generators/dom/visitors/Element/EventHandler.ts
- src/shared/dom.js
Addresses #621. This is only really disguising the real problem, which is that people are generating ESM bundles for non-ESM environments, but it's probably not Svelte's job to deal with that. And even if it was, then a cryptic error of the type seen in #621 isn't the way to go about it.
> rename addEventListener and removeEventListener

- src/validate/html/validateElement.ts
Correctly handle `<!doctype>` while also making the check a little clearer.
> Fix the missing component check

- src/generators/dom/visitors/Component/Binding.ts
- src/generators/dom/visitors/Element/Binding.ts
- src/generators/dom/visitors/shared/binding/getSetter.ts
- src/generators/server-side-rendering/Block.ts
- src/generators/server-side-rendering/visitors/Component.ts
- src/utils/deindent.ts
- src/utils/getObject.ts
- src/utils/getTailSnippet.ts
- test/helpers.js
- test/runtime/index.js
- test/runtime/samples/component-binding-computed/Nested.html
- test/runtime/samples/component-binding-computed/_config.js
- test/runtime/samples/component-binding-computed/main.html
- test/server-side-rendering/index.js
> allow components to have computed member expressions for bindings

- src/generators/Generator.ts
- src/utils/clone.ts
- test/parser/index.js
Closes #632. Tested with large source and it adds a fraction of 1% to the compilation time, so I think we can get away with adding this without an option.
> include ast in svelte.compile return value

- src/generators/dom/visitors/Element/Binding.ts
- test/runtime/samples/binding-select-initial-value-undefined/_config.js
- test/runtime/samples/binding-select-initial-value-undefined/main.html
> Sync state with view if <select> binding does not have initial value

- src/generators/Generator.ts
- src/generators/dom/Block.ts
- src/generators/dom/interfaces.ts
- src/generators/dom/preprocess.ts
- src/generators/dom/visitors/shared/binding/getSetter.ts
- test/runtime/samples/binding-indirect/_config.js
- test/runtime/samples/binding-indirect/main.html
This fixes the second bug in #639. I can't claim that the implementation is all that neat — it feels like maybe some things aren't exactly where they 'belong' (e.g. `indirectDependencies` probably belongs on `DomGenerator` rather than `Generator`, but then we'd have to change how `contextualise` works, which I didn't want to get into right now), and this probably needs to apply to `bind:group` as well — but I'm a firm believer in fixing first and finessing later. And this fixes a blocking issue for me, so I'm going to merge it in and cut a release 😀
> mark indirect dependencies of <select> bindings

- src/generators/dom/visitors/EachBlock.ts
- src/generators/server-side-rendering/visitors/EachBlock.ts
- test/runtime/samples/each-block-else-starts-empty/_config.js
- test/runtime/samples/each-block-else-starts-empty/main.html
Fixes #662, and another bug that it turns out existed prior to 1.23 (SSR failed if the each-else block was empty)
> fix each-else blocks that are empty on initial render

- src/parse/utils/hash.ts
- src/shared/transitions.js
- test/css/samples/basic/expected.css
- test/css/samples/cascade-false-global-keyframes/_config.js
- test/css/samples/cascade-false-global-keyframes/expected.css
- test/css/samples/cascade-false-keyframes/_config.js
- test/css/samples/cascade-false-keyframes/expected.css
- test/css/samples/cascade-false-pseudo-element/expected.css
- test/css/samples/cascade-false/expected.css
- test/css/samples/keyframes/expected.css
- test/css/samples/media-query/expected.css
- test/js/samples/collapses-text-around-comments/expected-bundle.js
- test/js/samples/collapses-text-around-comments/expected.js
- test/server-side-rendering/samples/styles-nested/_actual.css
- test/server-side-rendering/samples/styles-nested/_actual.html
- test/server-side-rendering/samples/styles-nested/_expected.css
- test/server-side-rendering/samples/styles-nested/_expected.html
- test/server-side-rendering/samples/styles/_actual.css
- test/server-side-rendering/samples/styles/_actual.html
- test/server-side-rendering/samples/styles/_expected.css
- test/server-side-rendering/samples/styles/_expected.html
This PR substantially improves framerate when there are lots of CSS transitions in a document with a combination of techniques:
* rather than (insanely) creating a separate `<style>` tag for each transition, we just create the one, lazily, and update it
* Identical transitions are deduped — if an element has the exact same keyframes as another one that's currently in progress, we don't create a new CSS animation for it
* We use `stylesheet.insertRule(rule, index)` rather than `style.textContent = rule`
* Animations are only removed from the `<style>` tag once there are no active transitions — i.e. when frame drops caused by updating the CSSOM are less likely to be noticed
> improve transition performance

- src/generators/dom/visitors/EachBlock.ts
- test/sourcemaps/index.js
- test/sourcemaps/samples/each-block/input.html
- test/sourcemaps/samples/each-block/test.js
This implements the idea mentioned in https://github.com/sveltejs/svelte/issues/681#issuecomment-311350689
> hack sourcemap to mitigate confusion caused by missing data for each block

- src/generators/dom/visitors/Element/EventHandler.ts
- test/runtime/samples/event-handler-hoisted/_config.js
- test/runtime/samples/event-handler-hoisted/main.html
> alias #component in hoisted event handlers

- mocha.opts
- src/generators/dom/index.ts
- src/generators/dom/visitors/Element/addTransitions.ts
- src/shared/index.js
- src/shared/transitions.js
- test/js/samples/collapses-text-around-comments/expected-bundle.js
- test/js/samples/computed-collapsed-if/expected-bundle.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/event-handlers-custom/expected-bundle.js
- test/js/samples/if-block-no-update/expected-bundle.js
- test/js/samples/if-block-simple/expected-bundle.js
- test/js/samples/non-imported-component/expected-bundle.js
- test/js/samples/non-imported-component/expected.js
- test/js/samples/onrender-onteardown-rewritten/expected-bundle.js
- test/js/samples/onrender-onteardown-rewritten/expected.js
- test/js/samples/use-elements-as-anchors/expected-bundle.js
- test/runtime/samples/transition-js-events/_config.js
- test/runtime/samples/transition-js-events/main.html
Fixes #702. This PR looks slightly more involved than might be expected from the title, which is because I think we need to satisfy the following constraints:
* `[in|ou]tro.start` events should fire *during* `component.set(...)`, not in the next tick. That way, it's easy to collect all the start events associated with a particular update — could get confusing otherwise
* It should be possible to do `this.on('intro.start', ...)` inside `oncreate` in time to capture any intros that happen on initial render
Because of that, we need to separate `_oncreate` from `_postcreate`, and control the order in which functions are called. I think the end result is actually slightly more logical/readable than what we had before.
> Fire intro.start and outro.start events

- src/generators/dom/visitors/Element/Binding.ts
- test/runtime/samples/binding-select-in-yield/Modal.html
- test/runtime/samples/binding-select-in-yield/_config.js
- test/runtime/samples/binding-select-in-yield/main.html
> ensure data is up to date when re-rendering yield blocks

- src/generators/dom/index.ts
- test/runtime/samples/css/Widget.html
- test/runtime/samples/css/_config.js
Fixes #722 — `#` characters were being escaped in `stringify`, but weren't later being unescaped when the final code is generated. Oops!
> unescape `#` character

- src/generators/dom/visitors/Component/Component.ts
- test/runtime/samples/component-binding-blowback-c/Nested.html
- test/runtime/samples/component-binding-blowback-c/_config.js
- test/runtime/samples/component-binding-blowback-c/main.html
Fixes #721. A nice side-effect of #709 (centralising post-state-change operations in the root component) is that we can use `child._set` rather than `child.set` when updating nested components, preventing whatever binding blowback insanity was causing the array length to jump around bizarrely.
> use _set, not set, when updating child components

- src/generators/dom/visitors/Component/EventHandler.ts
- src/generators/dom/visitors/Element/EventHandler.ts
- src/parse/index.ts
- src/parse/read/directives.ts
- src/parse/state/tag.ts
- src/validate/html/validateEventHandler.ts
- test/runtime/samples/event-handler-shorthand-component/Widget.html
- test/runtime/samples/event-handler-shorthand-component/_config.js
- test/runtime/samples/event-handler-shorthand-component/main.html
- test/runtime/samples/event-handler-shorthand/_config.js
- test/runtime/samples/event-handler-shorthand/main.html
Implements the proposal in #638:
```html
<IntermediateComponent on:foo='fire("foo",event)'/>
<IntermediateComponent on:foo/>
```
It also works with elements.
> Event propagation shorthand

- src/generators/dom/index.ts
- src/generators/dom/visitors/Element/Element.ts
- test/js/samples/collapses-text-around-comments/expected-bundle.js
- test/js/samples/collapses-text-around-comments/expected.js
- test/js/samples/css-media-query/expected-bundle.js
- test/js/samples/css-media-query/expected.js
closes #375. Doesn't have much effect on gzipped size, but the generated code looks a lot tidier and there's slightly less of it to parse.
> use helper to encapsulate styles, rather than being repetitious

- src/css/Stylesheet.ts
- test/css/samples/combinator-child/_config.js
- test/css/samples/combinator-child/expected.css
- test/css/samples/combinator-child/expected.html
- test/css/samples/combinator-child/input.html
Fixes #743. If `options.cascade` is true (or unspecified), CSS selectors are transformed by replacing them altogether. This makes it impossible to minify selectors by removing whitespace around combinators. Easiest solution (since we're removing `cascade: true` soon enough) is just to disable combinator minification in these cases.
> avoid string manipulation bugs by not minifying combinators if `cascade: true`

- src/generators/dom/Block.ts
- src/generators/dom/index.ts
- src/generators/server-side-rendering/index.ts
- src/generators/server-side-rendering/visitors/Component.ts
- src/utils/stringify.ts
- test/runtime/samples/component-static-at-symbol/Email.html
- test/runtime/samples/component-static-at-symbol/_config.js
- test/runtime/samples/component-static-at-symbol/main.html
I say [WIP] but this should be pretty much done.
This changes the escaping of `@` and `#` sigils to not use a prepended `\` (which gets further escaped by `JSON.stringify`, and complicates the unescaping) and instead just increases by 1 any runs of `@` or runs of `#`.
There are still a couple of gotchas:
- at the point where we're escaping injected CSS, we only want to escape `@`, because there is no further `#` unescaping that happens on that string after that point. There's probably a more elegant solution than what I have. Maybe still use `stringify` but then immediately unescape the `#` ones?
- the hash that maps characters to their HTML escaped versions in the SSR generated code contains `&#39;` as the replacement for `'`, which we have to now represent as `&##39;`. Not really a huge …
> saner escaping/unescaping of `@` and `#` sigils

- src/generators/dom/Block.ts
- src/generators/dom/index.ts
- src/generators/dom/visitors/Element/EventHandler.ts
- src/generators/dom/visitors/IfBlock.ts
- test/js/samples/if-block-no-update/expected-bundle.js
- test/js/samples/if-block-no-update/expected.js
It occurred to me that the `get_block` functions, which determine which block to render in a series of `if...elseif...else` blocks, can always be hoisted. Should save a microscopic amount of work when `if` blocks are inside `each` blocks, with no downside that I can think of.
I also renamed `get_block` to `select_block_type` (and `current_block` to `current_block_type`) since I think that's marginally more descriptive of what's happening.
> Hoist if block selectors

- src/css/Selector.ts
- test/css/index.js
- test/css/samples/descendant-selector-non-top-level-outer/_config.js
- test/css/samples/descendant-selector-non-top-level-outer/expected.css
- test/css/samples/descendant-selector-non-top-level-outer/expected.html
- test/css/samples/descendant-selector-non-top-level-outer/input.html
> apply encapsulating attributes to correct elements and selector parts

- src/generators/server-side-rendering/visitors/Slot.ts
- src/parse/state/tag.ts
- test/runtime/samples/component-slot-nested/Nested.html
- test/runtime/samples/component-slot-nested/_config.js
- test/runtime/samples/component-slot-nested/main.html
- test/server-side-rendering/index.js
- test/validator/samples/component-slot-nested/errors.json
- test/validator/samples/component-slot-nested/input.html
> support nested <slot> elements

- src/generators/dom/index.ts
- test/js/samples/collapses-text-around-comments/expected-bundle.js
- test/js/samples/collapses-text-around-comments/expected.js
- test/js/samples/computed-collapsed-if/expected-bundle.js
- test/js/samples/computed-collapsed-if/expected.js
- test/js/samples/css-media-query/expected-bundle.js
- test/js/samples/css-media-query/expected.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/event-handlers-custom/expected-bundle.js
- test/js/samples/event-handlers-custom/expected.js
- test/js/samples/if-block-no-update/expected-bundle.js
- test/js/samples/if-block-no-update/expected.js
- test/js/samples/if-block-simple/expected-bundle.js
- test/js/samples/if-block-simple/expected.js
- test/js/samples/legacy-input-type/expected-bundle.js
- test/js/samples/legacy-input-type/expected.js
- test/js/samples/non-imported-component/expected-bundle.js
- test/js/samples/non-imported-component/expected.js
- test/js/samples/onrender-onteardown-rewritten/expected-bundle.js
- test/js/samples/onrender-onteardown-rewritten/expected.js
- test/js/samples/setup-method/expected-bundle.js
- test/js/samples/setup-method/expected.js
- test/js/samples/use-elements-as-anchors/expected-bundle.js
- test/js/samples/use-elements-as-anchors/expected.js
- test/runtime/index.js
- test/runtime/samples/options/_config.js
- test/runtime/samples/options/main.html
- test/runtime/samples/pass-no-options/_config.js
- test/runtime/samples/pass-no-options/main.html
Closes #550, closes #777. `this.options` is stored on the component instance, so you can pass through whatever you want and it'll be accessible in lifecycle hooks and methods.
> attach options to component (#550)

- src/generators/dom/visitors/Element/Attribute.ts
- src/generators/dom/visitors/Element/StyleAttribute.ts
- src/shared/dom.js
- src/utils/getExpressionPrecedence.ts
- test/js/index.js
- test/js/samples/inline-style-optimized-multiple/expected-bundle.js
- test/js/samples/inline-style-optimized-multiple/expected.js
- test/js/samples/inline-style-optimized-multiple/input.html
- test/js/samples/inline-style-optimized-url/expected-bundle.js
- test/js/samples/inline-style-optimized-url/expected.js
- test/js/samples/inline-style-optimized-url/input.html
- test/js/samples/inline-style-optimized/expected-bundle.js
- test/js/samples/inline-style-optimized/expected.js
- test/js/samples/inline-style-optimized/input.html
- test/js/samples/inline-style-unoptimized/expected-bundle.js
- test/js/samples/inline-style-unoptimized/expected.js
- test/js/samples/inline-style-unoptimized/input.html
Ref #455. This generates better code for style attributes — this...
```html
<div style='font-size: 12px; color: {{color}}; transform: translate({{x}}px,{{y}}px);'></div>
```
...becomes this:
```diff
function create_main_fragment ( state, component ) {
-  var div, div_style_value;
+ var div;
return {
create: function () {
div = createElement( 'div' );
this.hydrate();
},
hydrate: function ( nodes ) {
-      div.style.cssText = div_style_value = "font-size: 12px; color: " + ( state.color ) + "; transform: translate(" + ( state.x ) + "px," + ( state.y ) + "px);";
+     div.style.setProperty('font-size', "12px");
+     div.style.setProperty('color', state.color);
+     div.style.setProperty('transform', "translate(" + state.x + "px," + state.y + "px)");
},
mount: function ( target, anchor ) { …
```
> optimize style attributes

- src/validate/html/a11y.ts
- test/validator/samples/a11y-html-has-lang/input.html
- test/validator/samples/a11y-html-has-lang/warnings.json
Adding warning for a11y on html tag without lang attribute. 
Refers to #820.
> feat(a11y): add warning missing lang on html tag

- package.json
- src/css/Selector.ts
- yarn.lock
https://github.com/csstree/csstree/issues/47
This has apparently been addressed, and it looks like we can now import just the parser. (It looks like at some point between then and now we stopped using css-tree's walker and started using `estree-walker` for walking the AST?) This upgrade does increase the bundle size, but not as dramatically as alpha16 -> alpha17 would have.
I had to make one other change for a renamed property in order to get the tests to pass, but css-tree's changelog should be looked at more thoroughly.
> Update css-tree [WIP]

- src/generators/dom/visitors/Element/Element.ts
> Quote `class` property name in attributes.

- src/generators/dom/visitors/Element/Binding.ts
- src/validate/html/validateElement.ts
I need this for a little side project of mine.
It's hard to add tests as these three IDL attributes are readonly (the spec for testing the existing `currentTime` and `duration` attributes is skipped for that same reason), but happy to provide a REPL/gist example once it's merged.
> Make buffered/played/seekable attributes of media element bindable

- src/generators/dom/visitors/Element/Binding.ts
- src/shared/dom.js
- test/js/samples/media-bindings/expected-bundle.js
- test/js/samples/media-bindings/expected.js
- test/js/samples/media-bindings/input.html
Follow-up to #819. Rather than using `requestAnimationFrame`, we're just binding to media events, which prevents unnecessary updates at 60fps.
It also converts the idiotic `TimeRanges` object into an array like `[{start, 0, end: 42}]`.
This needs some additional follow-up work to reach its true potential — we need to coalesce updates that belong to the same event, and use `requestAnimationFrame` for `played` updates (but only when playing, and combined with `currentTime` bindings. Currently it uses `timeupdate` which only fires about 4 times a second). That will involve some refactoring, so I've left it out of this PR for now.
> remove requestAnimationFrame stuff, convert time ranges to {start, end} objects

- src/validate/html/index.ts
- src/validate/html/validateElement.ts
- test/validator/samples/component-slotted-each-block/errors.json
- test/validator/samples/component-slotted-each-block/input.html
- test/validator/samples/component-slotted-if-block/errors.json
- test/validator/samples/component-slotted-if-block/input.html
This closes #849. It doesn't *fix* it, it just causes a validation error to be thrown if `slot='foo'` is encountered inside an if or each block.
Maybe we could actually make that work in future, but going through it in my head just now it seemed like it would be rather complex. As @mrkishi says, it's relatively easy to work around.
> compile time error on slotted content inside if/each blocks. closes #849

- src/generators/Generator.ts
- src/generators/dom/index.ts
- src/generators/dom/preprocess.ts
- src/generators/dom/visitors/EachBlock.ts
- test/helpers.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
- test/runtime/index.js
Just a small change to make generated code a bit more readable:
```diff
function create_main_fragment(state, component) {
var h1, text, text_1, ul;
-  var each_block_value = state.cats;
+  var cats = state.cats;
-  var each_block_iterations = [];
+  var each_blocks = [];
-  for (var i = 0; i < each_block_value.length; i += 1) {
-    each_block_iterations[i] = create_each_block(state, each_block_value, each_block_value[i], i, component);
+  for (var i = 0; i < cats.length; i += 1) {
+    each_blocks[i] = create_each_block(state, cats, cats[i], i, component);
}
> more readable each block values

- src/generators/dom/visitors/Element/EventHandler.ts
- src/utils/validCalleeObjects.ts
- src/validate/html/validateEventHandler.ts
- test/runtime/samples/event-handler-console-log/_config.js
- test/runtime/samples/event-handler-console-log/main.html
- test/validator/samples/method-nonexistent-helper/warnings.json
- test/validator/samples/method-nonexistent/warnings.json
- test/validator/samples/window-event-invalid/warnings.json
fixes #782. It does mean that `console` is a bit of a special case, though I personally think it's worth it as it's something I very often want when I'm debugging stuff. (If you disagree strongly, say so!)
> allow console.* calls in event handlers

- src/generators/dom/visitors/Element/Element.ts
- test/runtime/samples/escaped-text/_config.js
- test/runtime/samples/escaped-text/main.html
Ref #868. These should be using `stringify`, which escapes sigils, rather than `JSON.stringify`.
> Escape sigils in .textContent and .innerHTML

- .prettierrc
- package.json
- yarn.lock
As of version 1.6.0, Prettier supports per-project configuration with a `.prettierrc` file. This is nice because you can now configure your editor of choice to format on save and you can have it use formatting rules specific to that project. I have my editor and a few projects set up this way, and it feels good. Configuring your editor to autoformat on save is also useful for actually maintaining the prettier'd code, because no one is going to take the time to run the npm script regularly.
One question is, for the things that have diverged from prettier's code style, whether it would be better to format them all now as part of this PR, or to format files as they are being otherwise changed.
> upgrade prettier; use .prettierrc

- README.md
- src/generators/shared/utils/wrapModule.ts
- src/index.ts
Part of #824. This is a bit hacky but it seemed to be the most localized change that addresses this. Basically I'm replacing `options.onwarn` and `options.onerror` with versions that take one argument (the warning/error) and call the user's original callback with two arguments (the warning/error and the default handlers). The reason for this was so that the several places where `options.onwarn` and `options.onerror` are called can all remain the same. This can be changed if that seems a bit _too_ hacky.
> pass default onwarn and onerror handlers to user's callbacks

- src/generators/dom/visitors/Element/lookup.ts
The MDN HTML attribute reference didn't include the `audio` element under the `muted` property. I updated the MDN reference and inserted `audio` here, too. Without this, `muted={{ false }}` will render the `muted` property on `audio` elements, thus muting them [(demo)](https://svelte.technology/repl?version=1.17.0&gist=9e9b34b6eb5114777db8ea056a90d88e).
I didn't see any tests for this sort of thing, so I didn't write one.
Is there a script I missed that parses the mdn page for this data? If not, would it be helpful to have one? I might be able to do that shortly.
> supported "muted" property as boolean on audio element

- src/generators/dom/Block.ts
- src/generators/dom/preprocess.ts
- src/generators/server-side-rendering/visitors/EachBlock.ts
- src/parse/state/mustache.ts
- test/parser/samples/each-block-destructured/input.html
- test/parser/samples/each-block-destructured/output.json
- test/runtime/samples/each-block-destructured-array/_config.js
- test/runtime/samples/each-block-destructured-array/main.html
[Example repo](https://github.com/jacobmischka/svelte-destructure-test), ran with svelte `npm link`ed to branch as indicated in readme.
Note this does not do object destructuring, just array destructuring.
Input:
```handlebars
<div>
{{#each Object.entries(map) as [key, value], i}}
<h2>{{ key }}: {{ i }}</h2>
{{#each Object.entries(value) as [subkey, subvalue], j}}
<p>
{{subkey}}: {{subvalue}}
</p>
{{/each}}
{{/each}}
</div>
<script>
export default {
data() {
return {
map: {
key: {
subkey: 'subval',
subkey2: 'subval2'
},
anotherKey: {
anotherSubkey: 'anotherSubval',
anotherSubkey2: 'anotherSubval2'
}
}
};
}
};
</script>
```
Result:
Fixes #888
> Add array destructuring for each contexts

- yarn.lock
1.8.0 doesn't exist anymore it looks like.
Supercedes & fixes #898
> Fix yarn.lock electron entry

- src/validate/html/validateEventHandler.ts
- test/validator/samples/method-nonexistent-helper/warnings.json
- test/validator/samples/method-nonexistent/warnings.json
- test/validator/samples/window-event-invalid/warnings.json
[Gitter convo](https://gitter.im/sveltejs/svelte?at=59e751445c40c1ba79b72499).
This is a little hacky, as the handling of `options.*` is different than other things that are already in there. It's not like `set`/`fire`/`destroy`, as we're calling `options.something()`, not just `options()` - and it's not like `this`/`event`/`console`, as those variables already exist in scope, and for `options` we need to output `component.options.whatever()`.
> allow options.* as event handler callee

- src/css/Selector.ts
- test/css/samples/attribute-selector-only-name/_config.js
- test/css/samples/attribute-selector-only-name/expected.css
- test/css/samples/attribute-selector-only-name/input.html
#905 seems to be caused by `attributeMatches` trying to match a name-only attribute selector like `[foo]` to an html node that has that attribute and a value like `foo="bar"`. I made `attributeMatches` return true if the attribute matches and there is no `expectedValue`, since the css selector attribute has no value and there is nothing to expect, so it won't go looking for it and blow up as it was.
> Fixes #905 css attribute name only bug

- src/generators/Generator.ts
- test/runtime/samples/oncreate-async-arrow-block/_config.js
- test/runtime/samples/oncreate-async-arrow-block/main.html
- test/runtime/samples/oncreate-async-arrow/_config.js
- test/runtime/samples/oncreate-async-arrow/main.html
- test/runtime/samples/oncreate-async/_config.js
- test/runtime/samples/oncreate-async/main.html
Just checking if the function is async and outputting `async function` if so, rather than just always only outputting `function`. The tests don't do anything but use `await` inside the function. If the `async` keyword is not present, using `await` in the function is a syntax error, so runtime tests will fail.
I also wrote tests for `js/samples`, but as the README says to avoid those and the runtime tests are sufficient, I am not including them unless you'd like me to.
> oncreate async, fixes #904

- package.json
- tsconfig.json
- yarn.lock
TypeScript 2.6 changes the behaviour of tagged template literals. The upshot is that we need to import `__makeTemplateObject` from `tslib`, by using the `importHelpers` option
> add tslib and use importHelpers - fixes #919

- src/generators/shared/utils/wrapModule.ts
The arguments here were being rendered separated by newlines rather than commas. I'm guessing this stopped working (i.e., the array was no longer getting silently converted into a comma-separated string) when switching to the fancier tagged template mechanism for code generation. Switched this to manually calling `.join`, like in other parts of this file.
Thanks to @hperrin for catching this!
> fix factory arguments for globals in UMD output

- src/generators/dom/visitors/Element/Binding.ts
- test/runtime/samples/binding-indirect-computed/_config.js
- test/runtime/samples/binding-indirect-computed/main.html
This doesn't feel like the most elegant thing in the world, but it works, just by removing computed properties from the list of values that are updated. I can't think of any situations off the top of my head in which this wouldn't work...?
> possible fix for #893

- src/generators/dom/preprocess.ts
- test/runtime/samples/binding-select-optgroup/_config.js
- test/runtime/samples/binding-select-optgroup/main.html
This fixes #915, though due to JSDOM quirks the test has to be skipped
> don't use innerHTML for options inside optgroups

- package.json
Inspired by the recent change in Rollup - Adds a `prepare` npm script so that with npm5+ you'll be able to directly install from a git branch. You can test this now with `npm install sveltejs/svelte#install-from-git`.
> use prepare npm script to support installing from git

- src/server-side-rendering/register.js
- test/server-side-rendering/index.js
- test/server-side-rendering/samples/component-with-different-extension/Widget.svelte
- test/server-side-rendering/samples/component-with-different-extension/_expected.html
- test/server-side-rendering/samples/component-with-different-extension/main.svelte
Provides a dual way of registering node extensions:
- The normal one the registers '.html' `require('svelte/ssr/register')`
- The extended one that registers an array of extensions and deregisters the default one `require('svelte/ssr/register')(['.html', '.svelte'])`
> Add support for intercepting more file extensions in ssr.

- src/validate/html/a11y.ts
This PR adds `current` to the list of aria attributes, so that Svelte doesn't give a `A11y: Unknown aria attribute 'aria-current'` warning when [aria-current is used](https://tink.uk/using-the-aria-current-attribute/).
> Add 'current' to the list of aria attributes

- src/generators/Generator.ts
- src/generators/dom/visitors/Element/addTransitions.ts
- test/runtime/samples/binding-input-checkbox-group-outside-each/_config.js
- test/runtime/samples/binding-input-checkbox-group/_config.js
- test/runtime/samples/binding-input-radio-group/_config.js
- test/runtime/samples/transition-js-parameterised/_config.js
- test/runtime/samples/transition-js-parameterised/main.html
- yarn.lock
Fixes #962. I managed to break parameterised transitions in #924 😬
> allow parameterised transitions

- store.js
- test/store/index.js
Something @adamhaile spotted yesterday (thanks for the eagle eye!) — when `Store` re-sorts its computed properties, it doesn't bother to mark which ones it's already seen, so in a situation like this...
```js
store.compute('b', ['a'], a => a * 2);
store.compute('c', ['b'], b => b * 3);
store.compute('d', ['b'], b => b * 4);
```
...where both `c` and `d` depend on a computed value, it would end up thinking it had as many as 5 things to recompute on each state change, rather than a maximum of 3.
I also added some cyclical dependency detection, so that this...
```js
store.compute('a', ['b'], b => b + 1);
store.compute('b', ['a'], a => a + 1);
```
...results in a helpful 'Cyclical dependency detected — a computed property cannot indirectly depend on itself' error, rather than a stack …
> prevent cyclical store computations, and computation duplication

- src/generators/Generator.ts
- test/runtime/samples/component-data-static-boolean-regression/Link.html
- test/runtime/samples/component-data-static-boolean-regression/_config.js
- test/runtime/samples/component-data-static-boolean-regression/main.html
> prevent boolean attributes breaking shapes inside estree-walker

- src/generators/dom/visitors/Element/addTransitions.ts
- test/runtime/samples/transition-js-parameterised-with-state/_config.js
- test/runtime/samples/transition-js-parameterised-with-state/main.html
fixes the regression in #962 that would fail on bidirectional transitions that referenced state
> don't transform bidi transitions twice

- src/index.ts
- src/interfaces.ts
- test/preprocess/index.js
If the options object passed to `svelte.preprocess()` contains a `filename` property it'll be passed along to all the hooks so they can make file-system aware transformations.
Fixes #983
> feat: Pass filename option to preprocess hooks

- package.json
- src/parse/read/script.ts
- test/parser/samples/dynamic-import/input.html
- test/parser/samples/dynamic-import/output.json
- yarn.lock
> support dynamic import

- src/utils/CompileError.ts
- test/parser/index.js
This bug actually breaks most of the test cases in svelte-loader, when svelte's version is updated to the current one.
> Properly override toString in CompileError

- src/generators/nodes/Element.ts
- src/generators/nodes/Text.ts
- src/generators/nodes/shared/Node.ts
- test/runtime/samples/component-slot-empty/Nested.html
- test/runtime/samples/component-slot-empty/_config.js
- test/runtime/samples/component-slot-empty/main.html
> allow components without slots to have whitespace as only child

- src/generators/Generator.ts
- src/generators/nodes/Text.ts
- test/runtime/samples/computed-values-deconflicted/_config.js
- test/runtime/samples/computed-values-deconflicted/main.html
This fixes #1012, but you'll have to take my word for it — because the tests manipulate names to ensure that we're not accidentally hardcoding stuff, the regression doesn't actually show up when you're testing. I suppose if we wanted to be super-rigorous we could test both ways, but I'm lazy. This'll do for now
> deconflict computed properties with arguments to _recompute

- src/generators/Generator.ts
- src/generators/dom/index.ts
- src/generators/server-side-rendering/index.ts
- src/validate/js/propValidators/index.ts
- src/validate/js/propValidators/preload.ts
- test/js/samples/ssr-no-oncreate-etc/expected-bundle.js
- test/js/samples/ssr-no-oncreate-etc/expected.js
- test/js/samples/ssr-no-oncreate-etc/input.html
- test/runtime/samples/preload/_config.js
- test/runtime/samples/preload/main.html
> implement preload

- src/generators/server-side-rendering/index.ts
- test/runtime/index.js
- test/runtime/samples/store-root/Nested.html
- test/runtime/samples/store-root/_config.js
- test/runtime/samples/store-root/main.html
- test/server-side-rendering/index.js
For `store()` to work in SSR mode, we need to add it to `options.store`
> get store() to work with nested components in SSR compiler

- README.md
I'm not sure how sapper handles routing, but there seems to be an issue right now with trailing `/` characters. This PR just side steps the issue until it can be addressed. Below is a screenshot of the error when following the original link.
[Link with the trailing slash](https://svelte.technology/blog/frameworks-without-the-framework/)
[Link without the trailing slash](https://svelte.technology/blog/frameworks-without-the-framework)
> Side step a blog routing issue

- src/utils/isThisGetCallExpression.ts
- src/utils/walkThroughTopFunctionScope.ts
- src/validate/js/propValidators/computed.ts
- src/validate/js/propValidators/helpers.ts
- test/validator/samples/computed-purify-check-no-this/errors.json
- test/validator/samples/computed-purify-check-no-this/input.html
- test/validator/samples/computed-purify-check-this-get/errors.json
- test/validator/samples/computed-purify-check-this-get/input.html
I was going through the source code to learn how it works and I noticed a TODO for missing validation in the `computed` functions section, I even tried to use `this` there some time ago. Hopefully this helps a little :)
> Check against `this` usage in computed functions

- src/generators/nodes/Element.ts
- test/runtime/samples/option-without-select/_config.js
- test/runtime/samples/option-without-select/main.html
fixes #1022 and hopefully #1035
> allow options outside <select> elements

- src/generators/Generator.ts
According to [Node.Green](http://node.green/#ES2015-built-in-extensions-Object-static-methods-Object-setPrototypeOf), `Object.setPrototypeOf` has been supported since 0.12, longer ago than I would have thought. It's probably better then to use that rather than assigning to `__proto__`.
> use Object.setPrototypeOf instead of __proto__

- src/generators/dom/index.ts
- test/custom-elements/index.js
- test/custom-elements/samples/nested/Counter.html
- test/custom-elements/samples/nested/main.html
- test/custom-elements/samples/nested/test.js
- test/js/samples/css-shadow-dom-keyframes/expected-bundle.js
- test/js/samples/css-shadow-dom-keyframes/expected.js
This feels like a bit of a cheeky hack, but it a) works and b) is fairly unobtrusive. Fixes #1063.
> prevent main fragment being created twice

- src/validate/html/a11y.ts
- test/validator/samples/a11y-anchor-in-svg-is-valid/input.html
- test/validator/samples/a11y-anchor-in-svg-is-valid/warnings.json
An attempt to close https://github.com/sveltejs/svelte/issues/1008
I thought of checking whether given node is inside of an svg but that wouldn't be too good performance-wise.
I'm wondering if this should be used together with the `legacy` flag due to: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href#Browser_compatibility
I'm open to suggestions as usual :) thanks
> Allow xlink:href attribute

- src/generators/nodes/Attribute.ts
- test/runtime/samples/attribute-casing/_config.js
- test/runtime/samples/attribute-casing/main.html
> be more relaxed about attribute casing

- src/generators/server-side-rendering/visitors/Element.ts
Oversight in my PR for #1082. We should also make sure to cover this in #1087 once that test is working.
> fix escaping of sigils in SSR non-top-level <script> and <style>

- src/generators/server-side-rendering/index.ts
- test/runtime/samples/store-nested/Nested.html
- test/runtime/samples/store-nested/_config.js
- test/runtime/samples/store-nested/main.html
This fixes issue #1107 where supplying a store in a nested component would error with `TypeError: options.store._init is not a function` if the parent didn't have a store, or it would use the parent store, ignoring the one passed to the nested component.
> Fix passing a store to nested components on server side

- src/validate/html/index.ts
- src/validate/html/validateElement.ts
- src/validate/html/validateHead.ts
- test/validator/samples/a11y-not-on-components/input.html
- test/validator/samples/a11y-not-on-components/warnings.json
Fixes #1110. Moved the `isComponent` logic out into `src/validate/html/index.ts`. Made the `a11y` validator only get called when the element is not a component. Added a unit test, which also checks that children of component elements still do get a11y-validated.
> do not run a11y validation on child component elements

- src/generators/server-side-rendering/visitors/Element.ts
- test/runtime/samples/attribute-boolean-false/_config.js
- test/runtime/samples/attribute-boolean-false/main.html
- test/runtime/samples/attribute-boolean-true/_config.js
- test/runtime/samples/attribute-boolean-true/main.html
There was an extra layer to this that I wasn't thinking of because I somehow forgot that we need to output code that outputs HTML, not just directly output HTML 😅
What I settled on was: If this is a known boolean attribute, and its value is exactly one non-Text chunk, then emit code that displays or doesn't display the bare attribute name as appropriate. Other situations are handled as before.
> fix handling of boolean attributes in SSR (#1109)

- src/generators/Generator.ts
- test/runtime/samples/event-handler-custom-each-destructured/_config.js
- test/runtime/samples/event-handler-custom-each-destructured/main.html
Fixes #1139 
I also rewrote a little chunk that had a variable that wasn't being used anywhere anymore.
> Add destructured context container to usedContexts

- src/generators/nodes/AwaitBlock.ts
- test/runtime/samples/await-set-simultaneous/_config.js
- test/runtime/samples/await-set-simultaneous/main.html
> prevent await blocks using stale state

- src/generators/server-side-rendering/visitors/shared/stringifyAttributeValue.ts
- test/runtime/samples/attribute-dynamic-quotemarks/_config.js
- test/runtime/samples/attribute-dynamic-quotemarks/main.html
Opening this up instead of #1142. (Thanks @tav!) I'm fairly certain that all we need to escape are the same things that `__escape` already escapes. In particular, we do not need to worry about the IE behavior where attribute values can be enclosed in backticks because we are already going to be enclosing everything in double quotes - so the browser will see that first, before any potential backtick.
> escape attribute values in SSR

- src/generators/nodes/Element.ts
- src/generators/server-side-rendering/visitors/Element.ts
- src/generators/server-side-rendering/visitors/Text.ts
- src/parse/state/tag.ts
- test/runtime/samples/non-root-style-interpolation/_config.js
- test/runtime/samples/non-root-style-interpolation/main.html
- test/runtime/samples/script-style-non-top-level/_config.js
- test/runtime/samples/script-style-non-top-level/main.html
In practical terms, this fixes hydration of non-root <script> and <style>, and also fixes tag interpolation in non-root <style> (#1147). This supersedes other previous PRs I'd opened.
This switches non-root <script> and <style> back to being parsed as regular elements containing one child Text node (in the case of <script>) and one or more Text or Tag nodes (in the case of <style>). There are also some other changes to make sure we don't escape HTML special characters in DOM or SSR mode for the Text nodes inside non-root <script> and <style> elements.
> Rework handling of non-root <script> and <style>

- src/generators/nodes/Element.ts
- test/runtime/samples/noscript-removal/_config.js
- test/runtime/samples/noscript-removal/main.html
Should fix #1108 - but we probably should still document this behavior somewhere. Not sure where in the guide is the best place to do that.
> remove <noscript> elements in DOM mode (#1108)

- src/generators/dom/index.ts
- test/custom-elements/index.js
- test/custom-elements/samples/no-missing-prop-warnings/_config.js
- test/custom-elements/samples/no-missing-prop-warnings/main.html
- test/custom-elements/samples/no-missing-prop-warnings/test.js
> prevent erroneous missing data warnings for custom elements

- src/generators/server-side-rendering/visitors/Component.ts
- src/generators/server-side-rendering/visitors/Text.ts
- src/generators/server-side-rendering/visitors/shared/stringifyAttributeValue.ts
- src/utils/stringify.ts
- test/runtime/samples/escape-template-literals/Widget.html
- test/runtime/samples/escape-template-literals/_config.js
- test/runtime/samples/escape-template-literals/main.html
- test/runtime/samples/sigil-component-attribute/Widget.html
- test/runtime/samples/sigil-component-attribute/_config.js
- test/runtime/samples/sigil-component-attribute/main.html
In SSR mode, sigils aren't being correctly escaped in the static text portion of component attribute values if they also contain a dynamic portion.
> SSR: more sigil and template string escaping fixes

- src/generators/dom/index.ts
- test/custom-elements/assert.js
- test/custom-elements/index.js
- test/custom-elements/samples/oncreate/main.html
- test/custom-elements/samples/oncreate/test.js
I think this is the correct solution to #1117 — basically, whenever the element is first mounted, flush initial `oncreate` (and before/after create) hooks.
> in custom elements, call oncreate in connectedCallback

- test/parser/samples/error-comment-unclosed/error.json
- test/parser/samples/error-comment-unclosed/input.html
- test/parser/samples/error-each-blocks-empty/error.json
- test/parser/samples/error-each-blocks-empty/input.html
- test/parser/samples/error-each-blocks-keyed-whitespace/error.json
- test/parser/samples/error-each-blocks-keyed-whitespace/input.html
- test/parser/samples/error-each-blocks-whitespace/error.json
- test/parser/samples/error-each-blocks-whitespace/input.html
Here the `error-each-blocks-empty` behaves as expected. It throws a ParseError.
I can't get the whitespace errors to repro in the tests. They're easily seen
here: https://svelte.technology/repl?version=1.51.0&gist=b53b31b1c18ef80ff35067e02a9e7199
If you uncomment each section in sequence it demonstrates the behavior. I can't
quite figure out why my examples don't work.
> Empty Each Blocks should have consistent behavior.

- package.json
- src/parse/read/directives.ts
- src/parse/read/expression.ts
- src/parse/read/script.ts
- yarn.lock
There are a few different places where we're parsing with Acorn. I *think* it makes sense to parse as ES2018 in each place apart from `src/generators/dom/index.ts` which I think has to do with shared helpers. It might make sense to abstract this out somewhere so we don't have to remember to update as many places each year.
> upgrade acorn and parse as ES2018

- src/validate/index.ts
- test/validator/index.js
The current 'is the component name capitalized?' check disregards the possibility of the first character being `_` or `$`. The upcoming version of Sapper has components with names like `_4xx` and `_5xx`, so this PR checks that the first character isn't `a-z` rather than checking that it *is* `A-Z`. I *think* that's a sensible fix
> fix capitalize warning

- store.js
- test/store/index.js
This change fixes Issue #1177 where the scope of the cancel() function was not bound correctly and thus when attempting to call cancel() a type error of this._changeHandlers is undefined was created.
> this._changeHandlers was undefined when calling cancel()

- README.md
Wondered if you could add my npm package to the README? It allows you to use the Redux Dev Tools browser extension to view the contents and state changes of a svelte store.
I know this is a bit shameless but I just though it might be useful to other people, as it has helped me recently when working with the svelte store on a new app.
> Add link to svelte-dev-store to the README

- src/css/Stylesheet.ts
- test/css/samples/supports-query/_config.js
- test/css/samples/supports-query/expected.css
- test/css/samples/supports-query/input.html
with the `cascade: false` option, CSS in `@supports` blocks was getting removed
```html
<div class='maybe-grid'>something with a nice layout</div>
<style>
@supports (display: grid) {
.maybe-grid {
display: grid;
}
}
</style>
```
You would expect to get the code within the block e.g.
```css
@supports (display: grid) {.maybe-grid[svelte-xyz]{display:grid}}
```
but you would get 
```css
@supports (display: grid) {}
```
> process code in @supports queries with cascade: false

- src/generators/nodes/EachBlock.ts
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
- test/runtime/samples/each-block-array-literal/_config.js
- test/runtime/samples/each-block-array-literal/main.html
This fixes #1206. A neater solution would determine that the click handler only needed the `animal` value and didn't need to get it in a convoluted way, so we could just pass that around instead of the array and the index. (See also #1187.) But the priority is obviously to fix the bug
> add each_value to contextProps

- src/generators/nodes/Attribute.ts
- src/generators/nodes/Element.ts
- src/server-side-rendering/register.js
- test/runtime/samples/svg-with-style/_config.js
- test/runtime/samples/svg-with-style/main.html
- test/server-side-rendering/index.js
> allow SVG elements to have scoped CSS

- src/css/Selector.ts
- src/css/Stylesheet.ts
- src/generators/Generator.ts
- src/generators/nodes/Attribute.ts
- src/generators/nodes/Element.ts
- src/generators/server-side-rendering/visitors/Element.ts
- test/css/samples/cascade-false-nested/_config.js
- test/css/samples/cascade-false-nested/expected.css
- test/css/samples/cascade-false-nested/expected.html
- test/css/samples/cascade-false-nested/input.html
(Based on the #1223 branch to also get its unit test.)
A couple of issues still remain here:
- This breaks the `unused-selector-ternary` test because `attributeMatches` bails when `attr.value.length > 1`, which it now is, because there's the ternary part and the `svelte-xyz` class part. Not sure how to best handle this. Would it be practical to make the AST modifications after all the `Selector#apply` stuff?
- The `Element#addCssClass` logic could use some more thought. I'm not sure how to handle when the class attribute's `value` is `true` (this would mean that there is a bare `class` attribute, what the heck do we do with that?); and TypeScript is also still complaining about `classAttribute.value.length`, not sure whether it needs appeasing there or what.
> Apply CSS scoping classes directly to AST (WIP)

- src/generators/nodes/Element.ts
- test/css/samples/cascade-false-nested/_config.js
- test/css/samples/cascade-false-nested/expected.css
- test/css/samples/cascade-false-nested/expected.html
- test/css/samples/cascade-false-nested/input.html
fixes #1223. Admittedly it's a bit hacky — @Conduitry's idea of modifying the AST directly probably makes more sense.
> add CSS scoping classes when stringifying child nodes

- src/parse/read/directives.ts
- src/parse/state/tag.ts
- test/parser/samples/error-binding-mustaches/error.json
- test/parser/samples/error-binding-rvalue/error.json
- test/parser/samples/error-event-handler/error.json
This removes the copy-pasta for directive parsing and removes the need for special if-else cases for each directive. Future directives (if any) will benefit from this cleanup as well.
> Refactor directive parsing for code reuse

- src/parse/read/directives.ts
- test/parser/samples/error-binding-rvalue/error.json
- test/parser/samples/error-event-handler/error.json
- test/parser/samples/error-ref-value/error.json
- test/parser/samples/error-ref-value/input.html
small tweak to #1242 — also fixes the over-specific regex.
Also disallows `ref:foo='bar'` etc — unlike other directives, refs don't have a value
> don't treat :foo as a directive

- src/generators/nodes/EachBlock.ts
- src/shared/transitions.js
- test/helpers.js
- test/runtime/samples/each-block-keyed-random-permute/_config.js
https://github.com/sveltejs/svelte/issues/588
> Speed up keyed swap rows benchmark by moving existing DOM elements instead of creating new elements

- src/generators/nodes/EachBlock.ts
- src/shared/_build.js
- src/shared/index.js
- src/shared/keyed-each.js
- test/runtime/samples/each-block-keyed-random-permute/_config.js
This is a follow-up to both #1249 that starts to make good on the promise of #1173. It moves the logic for updating a keyed each block into a shared function.
While this does mean that a standalone component with a keyed each block will become slightly larger (because the function needs to accommodate e.g. blocks with and without transitions), there are substantial benefits in return: an app with two or more keyed each blocks will shrink (in terms of filesize, startup time and memory usage), and performance should improve because the function will warm up quicker if it's called from multiple places. 
Granted, this is all fairly obvious from the point of view of a traditional framework.
An equally big win, in my view, is that the codebase itself becomes somewhat simpler and easier to …
> [WIP] move keyed each diffing into a shared helper

- tsconfig.json
Two issues here - one is that the `target` option actually belongs inside `compilerOptions` in `tsconfig.json`, and so TypeScript was actually using its default target of ES3, not ES5. And then also there's not really a reason to target ES5 as far as I can tell anyway. This shaves 9% off the bundle size.
> set typescript target to ES6

- src/generators/dom/index.ts
- test/runtime/samples/initial-state-assign/_config.js
- test/runtime/samples/initial-state-assign/main.html
Fixes a regression from #1282. It's _possible_ that it would be nicer to move the reduce function to some common location and use that instead of composing `@assign` manually, but for now I just wanted to address the regression.
cc @lukeed @stalkerg
> fix assembly of initial state object

- src/generators/Generator.ts
- src/utils/nodeToString.ts
- src/validate/js/index.ts
- src/validate/js/propValidators/namespace.ts
- src/validate/js/propValidators/props.ts
- src/validate/js/propValidators/tag.ts
- test/runtime/samples/svg-child-component-declared-namespace-backtick-string/Rect.html
- test/runtime/samples/svg-child-component-declared-namespace-backtick-string/_config.js
- test/runtime/samples/svg-child-component-declared-namespace-backtick-string/main.html
- test/validator/samples/properties-props-must-be-an-array/errors.json
- test/validator/samples/properties-props-must-be-an-array/input.html
- test/validator/samples/properties-props-must-be-array-of-strings/errors.json
- test/validator/samples/properties-props-must-be-array-of-strings/input.html
Failing test for #1284
Fixes #1284
> Fix backtick string literals not being recognized in the svg/tag/props properties

- src/shared/transitions.js
Styles are stringified differently between browsers; this fix should be reliable. I can't think of a good way to test it, though, so we might have to just let this one through.
> remove transition styles in Firefox

- src/generators/nodes/Element.ts
- test/js/samples/event-handlers-custom/expected-bundle.js
- test/js/samples/event-handlers-custom/expected.js
- test/runtime/samples/dev-warning-custom-event-destroy-not-teardown/_config.js
- test/runtime/samples/dev-warning-custom-event-destroy-not-teardown/main.html
Deprecate custom event `teardown`, and start supporting `destroy`.
This brings custom events API inline with the rest of the API.
For example `component.destroy()` and `action.destroy`
> closes #531

- src/generators/nodes/EachBlock.ts
- src/shared/keyed-each.js
- test/runtime/samples/each-block-keyed-siblings/_config.js
- test/runtime/samples/each-block-keyed-siblings/main.html
> ensure correct order of DOM insertions with neighbouring keyed each blocks

- src/generators/nodes/Component.ts
- test/runtime/samples/component-events-console/Widget.html
- test/runtime/samples/component-events-console/_config.js
- test/runtime/samples/component-events-console/main.html
fixes #1278. Bit of a lazy PR — should really refactor stuff so that we're not duplicating code — but I have a larger refactor in mind so it'd probably be wasted effort
> treat component events the same as element events

- src/generators/dom/index.ts
- src/validate/js/propValidators/methods.ts
- test/js/samples/event-handlers-custom/expected-bundle.js
- test/js/samples/event-handlers-custom/expected.js
- test/js/samples/setup-method/expected-bundle.js
- test/js/samples/setup-method/expected.js
Necessary to move `observe` into svelte-extras
> allow overwritten observe method

- src/generators/server-side-rendering/index.ts
Fixes #1349. Didn't bother writing tests or figuring out why this wasn't already getting caught, as any of that work is going to get clobbered in the real v2 quite soon.
> fix computed properties in SSR mode with v2 syntax

- src/generators/nodes/Component.ts
- src/generators/nodes/Element.ts
- src/utils/flattenReference.ts
- test/runtime/samples/spread-each-component/Nested.html
- test/runtime/samples/spread-each-component/_config.js
- test/runtime/samples/spread-each-component/main.html
- test/runtime/samples/spread-each-element/_config.js
- test/runtime/samples/spread-each-element/main.html
> Update spread props in each blocks

- src/generators/Generator.ts
- src/generators/wrapModule.ts
- src/interfaces.ts
- test/runtime/samples/component-shorthand-import/Widget.html
- test/runtime/samples/component-shorthand-import/_config.js
- test/runtime/samples/component-shorthand-import/main.html
> Add support for shorthand imports of components

- src/generators/nodes/Component.ts
- test/runtime/samples/component-event-not-stale/Button.html
- test/runtime/samples/component-event-not-stale/_config.js
- test/runtime/samples/component-event-not-stale/main.html
fixes #1353
Tests will likely fail as for some reason they're never completing (probably because I just updated dependencies — something must have broken). Looking into it
> prevent stale state in component event handlers

- src/compile/nodes/AwaitBlock.ts
- test/runtime/samples/await-in-each/_config.js
- test/runtime/samples/await-in-each/main.html
> preserve outer context for await blocks

- src/compile/Compiler.ts
- src/compile/dom/index.ts
- src/compile/ssr/index.ts
- src/validate/js/propValidators/computed.ts
- test/runtime/samples/computed-state-object/_config.js
- test/runtime/samples/computed-state-object/main.html
> implement full-state computed properties

- src/compile/nodes/EachBlock.ts
- src/parse/state/mustache.ts
- src/shared/keyed-each.js
- test/parser/samples/each-block-keyed/output.json
- test/runtime/samples/each-block-keyed-non-prop/_config.js
- test/runtime/samples/each-block-keyed-non-prop/main.html
> allow arbitrary expressions in each block keys

- src/compile/nodes/EachBlock.ts
- src/shared/keyed-each.js
- test/js/samples/deconflict-builtins/expected-bundle.js
- test/js/samples/deconflict-builtins/expected.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
Shaves a few bytes off, and should make things slightly more efficient.
One thing I'd also like to experiment with, after this PR, is using `Object.create` instead of `assign` for creating child contexts. It might be quicker and more memory-efficient than duplicating parent properties for many child contexts.
Fixes #1287.
> Deduplicate each block context generation

- src/compile/dom/Block.ts
- src/compile/nodes/Binding.ts
- src/compile/nodes/Component.ts
- src/compile/nodes/EachBlock.ts
- src/compile/nodes/Fragment.ts
- src/parse/read/context.ts
- src/parse/state/mustache.ts
- src/utils/unpackDestructuring.ts
- src/validate/html/index.ts
- test/js/samples/deconflict-builtins/expected-bundle.js
- test/js/samples/deconflict-builtins/expected.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
- test/parser/samples/each-block-destructured/output.json
- test/parser/samples/each-block-else/output.json
- test/parser/samples/each-block-indexed/output.json
- test/parser/samples/each-block-keyed/output.json
- test/parser/samples/each-block/output.json
- test/parser/samples/unusual-identifier/output.json
- test/runtime/samples/each-block-destructured-array-sparse/_config.js
- test/runtime/samples/each-block-destructured-array-sparse/main.html
- test/runtime/samples/each-block-destructured-object-binding/_config.js
- test/runtime/samples/each-block-destructured-object-binding/main.html
- test/runtime/samples/each-block-destructured-object/_config.js
- test/runtime/samples/each-block-destructured-object/main.html
This updates the existing `destructuredContexts` mechanism to support arbitrary destructuring forms, so that you can do this sort of thing:
```html
{#each things as { x: [y, z] } }
<p>{z}</p>
{/each}
```
More realistically, you could use it for simple object pattern destructuring, but I didn't see any reason to arbitrarily restrict the patterns you could use. For now it *doesn't* support assignment patterns — we'll see if those turn out to be necessary. (They're a little finicky to parse.)
TODO
> Destructuring

- src/compile/nodes/EventHandler.ts
- test/runtime/samples/event-handler-each-this/_config.js
- test/runtime/samples/event-handler-each-this/main.html
> only overwrite this in event handlers for custom events

- src/compile/nodes/EachBlock.ts
- test/runtime/samples/dev-warning-missing-data-each/_config.js
- test/runtime/samples/dev-warning-missing-data-each/main.html
> evaluate each block key in child scope

- src/compile/nodes/Component.ts
- test/runtime/samples/spread-component-dynamic-undefined/_config.js
- test/runtime/samples/spread-component-dynamic-undefined/main.html
> Always declare spread levels

- src/compile/dom/Block.ts
- src/compile/nodes/AwaitBlock.ts
- src/shared/await-block.js
- src/shared/index.js
- src/shared/utils.js
- test/runtime/samples/await-then-catch-static/_config.js
- test/runtime/samples/await-then-catch-static/main.html
Trying to tidy some of this stuff up in order to tackle #956. Will try and fix #1417 in this PR as well.
It results in slightly more code if you have one `await` block in an app, but less if you have two or more.
> Handle await block promises in a shared helper

- src/compile/dom/Block.ts
- src/compile/nodes/Element.ts
just something that had been annoying me
> simpler code for case where there is only one outro in a block

- src/compile/nodes/EachBlock.ts
- test/js/samples/deconflict-builtins/expected-bundle.js
- test/js/samples/deconflict-builtins/expected.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
This results in slightly better performance and lower memory usage when creating large lists
> use Object.create for each block child contexts

- src/compile/nodes/Component.ts
- test/runtime/samples/event-handler-shorthand-dynamic-component/Widget.html
- test/runtime/samples/event-handler-shorthand-dynamic-component/_config.js
- test/runtime/samples/event-handler-shorthand-dynamic-component/main.html
Fixes use of `on:eventname` shorthand bubbling syntax in `<svelte:component>`.
cc @Kiho
> fix handling of shorthand event handler in dynamic components

- src/compile/dom/Block.ts
- src/compile/nodes/AwaitBlock.ts
- src/compile/nodes/EachBlock.ts
- src/compile/nodes/Element.ts
- src/compile/nodes/IfBlock.ts
- src/shared/transitions.js
- test/runtime/samples/transition-js-aborted-outro-in-each/_config.js
- test/runtime/samples/transition-js-aborted-outro-in-each/main.html
- test/runtime/samples/transition-js-aborted-outro/_config.js
- test/runtime/samples/transition-js-aborted-outro/main.html
> Abort outro if block is recreated

- src/validate/html/a11y.ts
This PR adds the new ARIA attributes and roles as defined in <https://www.w3.org/TR/wai-aria-1.1/>.
I found which attr/roles had changed via:
- <https://www.levelaccess.com/differences-aria-1-0-1-1-deprecations-additions/>
- <https://www.levelaccess.com/differences-aria-1-0-1-1-additions-role/>
Originally I just wanted to use the new `aria-role=switch` in one of my components but as it turns out there's a bunch of new additions worth adding.
> Add new ARIA 1.1 attributes and roles

- src/parse/state/tag.ts
- test/runtime/samples/attribute-dynamic-reserved/_config.js
- test/runtime/samples/attribute-dynamic-reserved/main.html
Fixes #1445. We were already correctly handling this when things like `{ class }` appeared as a regular HTML tag but not when it appeared in an attribute value.
> allow spaces around reserved words used in tags in attributes

- README.md
Update the result of "svelte.compile" from "Example usage" section, replacing `{ code, map }` to `{ js, css, ast }`
> Update "Example usage" in readme

- src/Stats.ts
fixes #1487. Have confirmed it does indeed now run in a worker, though I can't think of a great way to test it in Node. In lieu of that we can fix magic-string and use the REPL as a canary: https://github.com/sveltejs/svelte.technology/blob/2f1f84d49d8f11d503fbbcf2db2e8115ae2d7da5/routes/repl/_worker.js#L1
> replace window with self

- src/compile/nodes/Element.ts
- src/css/Selector.ts
- src/css/Stylesheet.ts
- test/css/samples/refs-qualified/expected.css
- test/css/samples/refs-qualified/expected.html
- test/css/samples/refs/expected.css
- test/css/samples/refs/expected.html
Implements #1230. Rather than calling the class `.svelte-ref-foo-xyz` (as mentioned in the issue description), this just calls it `.svelte-ref-foo` (like the attribute currently is), and also keeps the `.svelte-xyz` class.
> use CSS classes for ref:* selectors

- src/compile/nodes/AwaitBlock.ts
- src/compile/nodes/EachBlock.ts
- src/compile/nodes/IfBlock.ts
- test/runtime/samples/nested-transition-detach-each/_config.js
- test/runtime/samples/nested-transition-detach-each/main.html
- test/runtime/samples/nested-transition-detach-if-false/Folder.html
- test/runtime/samples/nested-transition-detach-if-false/_config.js
- test/runtime/samples/nested-transition-detach-if-false/main.html
fixes #1497. For some reason I can't seem to create a test for this that failed previously, even though both the REPL reproductions are fixed by this. 
There's another case that isn't fixed by this, involving nested each blocks — going to look into that now
> detach outroing blocks correctly

- src/compile/nodes/Title.ts
- src/parse/state/mustache.ts
- src/validate/html/validateElement.ts
- src/validate/html/validateHead.ts
- test/server-side-rendering/samples/styles-nested/One.html
- test/validator/samples/title-no-children/errors.json
Mostly just comments, but some error/warning messages as well. Leaves [this](https://github.com/sveltejs/svelte/blob/54799736b8b03da41b7110a321dca8a3d880ed32/src/parse/read/directives.ts#L143) one alone for now, because it's still pending what we're going to do with that leftover syntax.
> update some stray references to v1 syntax

- src/compile/nodes/Window.ts
Fixes #1502. Adds lines to set and then clear again the `_updatingReadonlyProperty` flag before and after updating the bound property.
> fix bind:online in dev mode

- src/compile/nodes/EventHandler.ts
- test/js/samples/event-handlers-custom/expected-bundle.js
- test/js/samples/event-handlers-custom/expected.js
Reverts  sveltejs/svelte#1557. After thinking this through a bit more, it feels like a design mistake — the motivating use case is to allow custom event definitions to have app-specific side-effects, which isn't what they're for (an event is just 'this thing happened', and anything that happens in *response* to that event should happen in the handler). Instead, we should return once more to #779.
> Revert "Fix for #1553"

- src/compile/Compiler.ts
- src/compile/nodes/Component.ts
- src/compile/nodes/EachBlock.ts
- src/compile/nodes/IfBlock.ts
- src/shared/_build.js
- src/shared/await-block.js
- src/shared/transitions.js
- test/js/samples/each-block-keyed-animated/expected-bundle.js
- test/runtime/samples/transition-js-dynamic-component/A.html
- test/runtime/samples/transition-js-dynamic-component/B.html
- test/runtime/samples/transition-js-dynamic-component/_config.js
- test/runtime/samples/transition-js-dynamic-component/main.html
ref #1568. This doesn't add the `switch` directive (that can wait), but it causes components to outro if `nestedTransitions` is true (as it will by default in v3).
~~Adding `transitionManager.groupOutros` does cause the whole of `transitionManager` to be included regardless of whether the component has outros, which is a longer-standing issue that needs resolving.~~
> outro when <svelte:component> switches - 

- src/compile/nodes/Component.ts
- test/runtime/samples/component-binding-invalid-identifier/Counter.html
- test/runtime/samples/component-binding-invalid-identifier/_config.js
- test/runtime/samples/component-binding-invalid-identifier/main.html
- test/runtime/samples/component-invalid-identifier/Widget.html
- test/runtime/samples/component-invalid-identifier/_config.js
- test/runtime/samples/component-invalid-identifier/main.html
This fixes #887 by quoting name of attributes if those are invalid JS identifiers when passing data to nested components, so something like [this](https://svelte.technology/repl?version=2.8.0&gist=f9fc679ecfbaac72e859150fbd12149e) would compile and run successfully.
Please note that this does not add support for acessing these attributes directly on the component code, but only adds support for passing that data to the nested component. I think a valid idea here is to let the user use a computed property on the nested component returning the whole state (like `state`, maybe?) to access the data on template tags using `{ state["b-c"] }`, for example.
I'll add tests tonight, by the way, so this is still a WIP. But feel free to test and comment about the idea. =)
> Quote name of attribute to nested components

- src/compile/nodes/Element.ts
- src/shared/transitions.js
- test/runtime/samples/transition-js-destroyed-before-end/_config.js
- test/runtime/samples/transition-js-destroyed-before-end/main.html
This is an alternative fix for #1561 — rather than checking to see if a node's parent exists before detaching it, it aborts any in-progress outro when a node is detached. This seems like a more complete fix that would prevent any related bugs from cropping up in future — for example, it prevents `outro.end` events erroneously firing after a component has been destroyed.
> abort transition on detach

- src/compile/nodes/Element.ts
- test/runtime/samples/template/_config.js
- test/runtime/samples/template/main.html
fixes #1571. Turns out that `<template>` is weird — its `innerHTML` reflects `template.content`, *not* the contents of the template itself. Seems dappy but what do I know.
Made some minor tidy-ups while I was at it.
> use template.content in place of template where appropriate

- src/compile/nodes/Element.ts
- test/runtime/samples/attribute-dynamic-no-dependencies/_config.js
- test/runtime/samples/attribute-dynamic-no-dependencies/main.html
Fixes #1581. I'm pretty sure there aren't other cases like this to worry about. This makes it so that attributes cause their elements to opt out of `.innerHTML` whenever they contain a dynamic tag, not merely when they have something that's been determined to be a dependency. See source issue for more information in the form of a meandering monologue.
> fix determing whether an attribute should prevent innerHTML optimization

- src/parse/state/mustache.ts
- test/runtime/samples/await-then-catch-no-values/_config.js
- test/runtime/samples/await-then-catch-no-values/main.html
#1507. The compiler seems to behave fine when then or catch blocks have no bound identifier for the resolution/rejection value, so update the parser to not require them.
> allow {:then}/{:catch} to have no bound identifier

- src/shared/dom.js
- test/js/samples/bind-width-height/expected-bundle.js
This happens because `cancel` is called before the `onload` event is fired on line 208.
This PR just checks for the existence of `win` before trying to remove the listener
> closes #1600

- src/compile/Compiler.ts
- src/shared/ssr.js
- test/server-side-rendering/samples/attribute-escaped-quotes-spread/_expected.html
- test/server-side-rendering/samples/attribute-escaped-quotes-spread/main.html
- test/server-side-rendering/samples/attribute-escaped-quotes/_expected.html
- test/server-side-rendering/samples/attribute-escaped-quotes/main.html
Fixes vulnerability CVE-2018-6341 described in https://reactjs.org/blog/2018/08/01/react-v-16-4-2.html
> Sanitize spread attributes in SSR

- src/css/Selector.ts
- test/css/samples/local-inside-global/expected.css
- test/css/samples/local-inside-global/input.html
> encapsulate local styles inside global ones

- src/compile/Compiler.ts
- src/compile/dom/index.ts
- src/shared/utils.js
- src/utils/annotateWithScopes.ts
- test/runtime/samples/object-rest/_config.js
- test/runtime/samples/object-rest/main.html
Alright, let's fix #1540 once and for all. This adds support for rest elements in computed properties. It does so in a way that avoids the `props.props.props.props` thing we discovered — in a case like this...
```js
computed: {
foo: ({ x, ...y }) => y
}
```
...`foo` will be excluded from the object passed in. This might seem slightly magical, but I think it matches people's intuitions of how this should work.
> handle rest elements in computed properties

- src/validate/html/validateComponent.ts
- src/validate/html/validateElement.ts
- test/validator/samples/reference-must-be-valid-name/errors.json
- test/validator/samples/reference-must-be-valid-name/input.html
Issue Reference: https://github.com/sveltejs/svelte/issues/1613
When having html like `<div ref:foo-bar></div>` an error would get thrown, `Assigning to rvalue`, but it was non specific and actually a default error from acorn, see https://github.com/acornjs/acorn/blob/a2f254ab2d4b4431543e0ffe374751c296ab670d/src/lval.js and search for `rvalue`.
Added a similar validation check that `computed` properties have with a suggestion output.
> [WIP] Adds error for #1613

- src/compile/nodes/Attribute.ts
- src/shared/dom.js
- test/custom-elements/samples/props/main.html
- test/custom-elements/samples/props/my-widget.html
- test/custom-elements/samples/props/test.js
This changes the behaviour of attributes on custom elements — previously, data would always be passed to custom elements using `setAttribute`, which only works for strings.
Now, it uses a simple heuristic: if the prop exists on the custom element, it is set as a prop, otherwise it's an attribute. (This is similar to what Preact does.)
So in this case...
```html
<fancy-list items={things}/>
```
...as long as `items` is the name of a property on a `FancyList` instance (whether or not it had previously been set), the value of `items` inside the component will be an array rather than the dreaded `"[object Object]"`.
Typically, custom elements use accessors for properties that their consumers should be able to read and write...
```js
class FancyList extends HTMLElement {
...
get items() {
// …
```
> use props when passing data to custom elements (#875)

- src/compile/nodes/DebugTag.ts
- test/js/samples/debug-foo-bar-baz-things/expected-bundle.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected-bundle.js
- test/js/samples/debug-foo/expected.js
Follow-up to #1640 — with a little trickery, we can get source mappings:
> add sourcemaps to debug tags

- src/parse/read/context.ts
Just adds a couple of properties that I needed when trying to print the svelte ast to string using [astring](https://github.com/davidbonnet/astring) for the javascript parts (it would error as it expected `kind` to be defined)
> Add some properties to ObjectPattern Property nodes

- src/compile/nodes/Component.ts
- test/cli/samples/amd/expected/Main.js
- test/runtime/samples/dynamic-component-destroy-null/_config.js
- test/runtime/samples/dynamic-component-destroy-null/main.html
Fixes one of the bugs in #1660 (the one not covered by #1662)
> Allow non-existent dynamic components to be destroyed

- src/parse/read/directives.ts
- test/runtime/samples/action-ternary-template/_config.js
- test/runtime/samples/action-ternary-template/main.html
Allow any expression to pass data to an action. Added a test for a ternary statement and a string template.
Fixes #1676
> Allows actions to use any expression type

- src/shared/index.js
- src/shared/transitions.js
- src/shared/utils.js
- test/runtime/samples/transition-js-context/_config.js
- test/runtime/samples/transition-js-context/main.html
> run transitions in context of component

- src/shared/dom.js
> Set style attribute correctly when spread attr present

- src/compile/nodes/DebugTag.ts
- src/shared/ssr.js
- test/js/samples/debug-ssr-foo/_config.js
- test/js/samples/debug-ssr-foo/expected-bundle.js
- test/js/samples/debug-ssr-foo/expected.js
- test/js/samples/debug-ssr-foo/input.html
fixes #1659. Since `debugger` doesn't really make sense in SSR mode, this just logs out the requested values (or all of them, if none are specified) to the console, along with location information for the tag itself.
> support debug tag in SSR mode

- package.json
[compiler/svelte.js.map](https://unpkg.com/svelte@2.12.1/compiler/svelte.js.map) is more than half of the size of the package. It seems a bit unnecessary. Any objections to removing it? It's only really useful when we're developing the compiler itself.
> remove sourcemaps from package

- src/compile/nodes/Binding.ts
- test/js/samples/input-files/expected-bundle.js
- test/js/samples/input-files/expected.js
- test/js/samples/input-range/expected-bundle.js
- test/js/samples/input-range/expected.js
- test/js/samples/input-without-blowback-guard/expected-bundle.js
- test/js/samples/input-without-blowback-guard/expected.js
- test/js/samples/media-bindings/expected-bundle.js
- test/js/samples/media-bindings/expected.js
Fixes #1699
I originally started adding new conditions to [the array in `Elements.ts`](https://github.com/sveltejs/svelte/blob/63276479497a2255c8cc8be535455a0366164700/src/compile/nodes/Element.ts#L499), but once I figured out where to get the dependencies from, it seemed to make more sense to do it in `Bindings.ts` to keep from exposing anything more from the `munge` method.
I didn't add any new tests, I updated/was guided by the existing test suite.  I could add a new test if someone can think of an appropriate one.
> Only update inputs when the value changed

- src/compile/nodes/Element.ts
- src/css/Selector.ts
- test/runtime/samples/class-shortcut/_config.js
- test/runtime/samples/class-shortcut/main.html
When no expression is used in a class directive the class name will be used to evaluate whether the class should be added/removed.
E.g. the following will add the class "active" when you call `component.set({ active });`.
```html
<div class:active></div>
```
Also, classes added this way are encapsulated in the stylesheet.
Old
```html
<div class="{active ? 'active' : ''}"></div>
<style>
.active {
/* Will be removed from the stylesheet since the compiler can't know it is used */
}
</style>
```
New
```html
<div class:active="active"></div>
<style>
.active {
/* Will be kept and encapsulate styles */
}
</style>
```
> Adds class directive shortcut and encapsulate styles

- src/compile/nodes/EachBlock.ts
- test/runtime/samples/transition-js-each-block-outro/_config.js
- test/runtime/samples/transition-js-nested-each-delete/_config.js
- test/runtime/samples/transition-js-nested-each-delete/main.html
Unkeyed each blocks end up with trailing `null` values that prevent the whole from being outroed. This fixes it so the null values are removed before outroing the remaining blocks.
Fixes #1617
> Fix for each-blocks preventing outros from completing

- src/compile/nodes/Binding.ts
Just small cleanup to avoid TypeScript errors and not used arguments.
> Small cleanup event handler in bindings to avoid TS errors.

- src/compile/nodes/Element.ts
- test/runtime/samples/binding-input-checkbox-with-event-in-each/_config.js
- test/runtime/samples/binding-input-checkbox-with-event-in-each/main.html
This small change fix #1732 . If we have binding inside each we always should set local ctx during an update. Previous logic skip this if we have an event on an element. 
Regards,
> Fix binding input with event in each and add test case.

- src/compile/index.ts
- src/compile/wrapModule.ts
- src/index.ts
- src/interfaces.ts
- src/utils/deprecate.ts
- test/parser/index.js
fixes #1745. we'll want to update svelte-loader and rollup-plugin-svelte etc before releasing this
> deprecate onerror

- src/parse/read/directives.ts
Fixes #1788. Instead of prefixing the directive value with spaces to put it at the index into the string that it is in the template (which obviously breaks line numbers in error messages), just use the portion of the template string itself up to the end of the directive value. This also means we don't have to maintain the directive's value in a string as we march over it - we're just looking for the end of the attribute so we can trim everything after that off so as to not upset Acorn.
> adjust parsing of directives to preserve line/column info

- src/compile/render-dom/wrappers/Fragment.ts
- test/runtime/samples/if-block-first/_config.js
- test/runtime/samples/if-block-first/main.html
This PR fix my issue https://github.com/sveltejs/svelte/issues/1778 .
The main problem this we shouldn't change the link to the next element after remove first when we have forward motion it's actual for reverse motion only. 
By current code logic next state:
elem1 -> elem2
elem2 -> elem3
elem3 -> null
changed to:
elem2 -> null
elem3 -> null
(we removed first element and for second element set next link as null)
> Fix removing next link during strip whitespaces for first element.

- src/compile/render-dom/wrappers/IfBlock.ts
- test/runtime/samples/each-block-in-if-block/_config.js
- test/runtime/samples/each-block-in-if-block/main.html
subj. Looks like it was just typo problem.
> fix #1780 just start use parent instead parent.parent in IfBlock wrapper

- src/compile/render-dom/wrappers/Element/index.ts
- src/compile/render-ssr/handlers/Element.ts
- test/runtime/samples/class-in-each/_config.js
- test/runtime/samples/class-in-each/main.html
- test/runtime/samples/event-handler-each-context/_config.js
- test/runtime/samples/event-handler-each-context/main.html
> recognise dependencies in class directives

- store.d.ts
This adds some missing types to the Store's declaration file.
`set`'s `void` return type is optional but there are compiler options that make it required, so it doesn't hurt to provide it for users.
`compute`'s third argument was missing and I had a couple of options: either go with the simpler `(...deps: any[]) => any` or fiddle a bit with TypeScript.... I don't think it went _completely_ overboard:
```typescript
interface Tuple<T extends any, L extends number> extends Array<T> {
0: T;
length: L;
}
declare function compute<L extends number>(
key: string,
dependencies: Tuple<string, L>,
fn: (...dependencies: Tuple<any, L>) => any,
): void;
```
This has the benefit of reporting errors when the function's prototype doesn't match the specified dependencies. [See error reporting in …
> Add missing types to store.d.ts

- src/compile/nodes/Document.ts
- src/compile/nodes/shared/mapChildren.ts
- src/compile/render-dom/wrappers/Document.ts
- src/compile/render-dom/wrappers/Fragment.ts
- src/compile/render-ssr/Renderer.ts
- src/parse/state/tag.ts
- test/runtime/samples/document-event/_config.js
- test/runtime/samples/document-event/main.html
This is alternative to #1506, addressing #1484. Adding `<svelte:document>` basically just for `mouseenter` and `mouseleave` events does *seem* like a lot, but @acstll's comment [here](https://github.com/sveltejs/svelte/issues/1484#issuecomment-392586533) is valid. This feels less surprising and more future-proof.
> add a <svelte:document> tag

- package-lock.json
- package.json
- test/helpers.js
We had `chalk` installed for tests only – replaced it for the runtime variant.
> FWIW, `rfc-1` is failing on my machine with no changes
> Trim Duplicate Dependency

- src/shared/dom.js
In IE11 the second argument to `classList.toggle` is not respected.  This leads to the class always being added as its initial state and toggled thereafter.
> Small update to allow class directives to work in IE11

- src/compile/render-dom/wrappers/AwaitBlock.ts
- test/runtime/samples/await-then-catch-order/_config.js
- test/runtime/samples/await-then-catch-order/main.html
- test/runtime/samples/transition-js-await-block/_config.js
Added a failing test for async blocks getting out of order in some situations as shown in #1440.
> Fixes #1440 await blocks gets out of order

- src/shared/dom.js
At the moment it is not possible to set an attribute of a custom element to zero, as the setCustomElementData function removes every attribute whose element evaluates to false (false, 0, "", null, undefined, NaN). I would propose to just filter out undefined and null or to remove this if closure completely as this behaviour should already be covered by the setAttribute() function.
> Fixes setting custom element data to zero

- src/cli/index.ts
I noticed as I was testing that the CLI supported the --customElement option, but it was not part of the help command. This just adds a simple explanation of what the option does.
> Update cli spec to include --customElement option

- test/helpers.js
- test/runtime/samples/onupdate-after-concreate-using-bind-offsetWidth/_config.js
- test/runtime/samples/onupdate-after-concreate-using-bind-offsetWidth/main.html
Failing test for #1743. I had to add global.getComputedStyle and global.navigator to test/helpers.js to get [addResizeListener](https://github.com/sveltejs/svelte/blob/1f79099d2f6a542cceaa04b5916e63bee4a3b2c7/src/shared/dom.js#L210) working under test.
> Failing test for #1743

- src/compile/Component.ts
- src/compile/nodes/shared/Expression.ts
- src/compile/render-dom/index.ts
- src/compile/render-ssr/index.ts
- src/internal/ssr.js
- src/internal/utils.js
- test/runtime/samples/store-auto-subscribe-in-each/_config.js
- test/runtime/samples/store-auto-subscribe-in-each/main.html
- test/runtime/samples/store-auto-subscribe-in-reactive-declaration/_config.js
- test/runtime/samples/store-auto-subscribe-in-reactive-declaration/main.html
- test/runtime/samples/store-auto-subscribe/_config.js
- test/runtime/samples/store-auto-subscribe/main.html
- test/runtime/samples/store-dev-mode-error/_config.js
- test/runtime/samples/store-dev-mode-error/main.html
- test/runtime/samples/store-prevent-user-declarations/_config.js
- test/runtime/samples/store-prevent-user-declarations/main.html
> store auto-subscriptions

- package.json
- store.js
- test/store/index.js
Started replying to @marvinhagemeister on https://github.com/sveltejs/rfcs/pull/5 but got side-tracked by trying to see if we could make our reactive stores glitch-free (i.e. if a derived store depends on `a` and `b`, and `b` is also a derived store that depends on `a`, don't recalculate when `a` changes until `b` is also up-to-date).
I *think* this works? But would appreciate a sanity check if anyone is familiar with this problem space...
Explanation: each store's `subscribe` method now takes an optional second `invalidate` method:
```js
store.subscribe(
value => console.log(`the value is`, value),
() => console.log(`here comes a new value... I wonder what it will be?`)
);
```
When a store's value changes, it should call all the invalidate functions and *then* call the main callback. …
> Glitch free reactive stores

- site/src/routes/guide/index.html
- src/compile/render-dom/wrappers/Element/index.ts
- src/internal/Component.js
- src/internal/scheduler.js
well i feel silly
(in dev mode, fragments' `i` method becomes `i: intro`, so `intro.enabled` was shadowed)
closes #1881
> fix dev mode transitions

- .gitignore
- easing.mjs
- rollup.config.js
- transition.mjs
This adds four transitions — `fade`, `fly`, `draw` and `slide` — into the Svelte repo itself. It also adds the family of easing equations that are recommended for use with transitions, animations and `tween`.
The module matches the name of the directive:
```html
<script>
import { fade } from 'svelte/transition';
let visible = false;
</script>
<label>
<input type="checkbox" bind:checked={visible}>
visible
</label>
{#if visible}
<div transition:fade>
fades in and out
</div>
{/if}
```
> add integrated transitions

- site/src/routes/repl/_components/Output/index.html
- site/src/routes/repl/_components/Repl.html
- site/src/routes/repl/embed.html
Slightly less DRY than ideal. An alternative was to have the compiler output pane be `<SplitPane type="vertical" pos={embedded ? 100 : 67}>` but that seemed slightly weirder (and also potentially more confusing, if a user bumps into this strange hidden expandable section).
> do not display compiler options in embedded REPL

- src/compile/Component.ts
- src/compile/css/Stylesheet.ts
- src/compile/index.ts
- src/compile/wrapModule.ts
- src/interfaces.ts
- test/css/index.js
- test/validator/index.js
> always use stats.warn instead of options.onwarn

- src/compile/render-dom/index.ts
- src/utils/globalWhitelist.ts
- test/runtime/index.js
- test/runtime/samples/globals-accessible-directly-process/_config.js
- test/runtime/samples/globals-accessible-directly-process/main.html
- test/server-side-rendering/index.js
fixes #1894. Realised `process` is probably a bit of a special case, and should always be treated as a global.
Now that I've implemented it though, I'm not sure if we *do* want to fall back to globals for other names. It's more generated code for a somewhat rare situation. Maybe we're better off just whitelisting stuff and saying 'if you need more control, add a `<script>` tag'?
> whitelist process, and fallback to globals

- src/compile/Component.ts
- src/compile/render-dom/index.ts
- src/compile/render-ssr/index.ts
- test/runtime/samples/prop-without-semicolon/_config.js
- test/runtime/samples/prop-without-semicolon/main.html
One of the downsides of using magic-string instead of the traditional AST/codegen approach — it's very sensitive to the order of operations. In the case of #1931, inserted code was being unceremoniously removed, because it was attached to thin air instead of a (removal-proof) semi-colon.
Fixed by ensuring that instrumentation happens before props are rewritten, since the `{ ` and ` } = $$props` inserts will always need to go on the outside.
> rewrite props after instrumentation

- src/compile/Component.ts
- src/compile/nodes/Animation.ts
- src/compile/nodes/shared/Expression.ts
- src/compile/render-dom/index.ts
- src/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/animation-js-easing/_config.js
- test/runtime/samples/animation-js-easing/easing.js
- test/runtime/samples/animation-js-easing/main.html
Fixes #1933. There were actually a couple of different bugs here. Firstly, animation functions weren't being correctly 'qualified', so references could be incorrect. Secondly, functions that depend on imported values (and no local values) weren't being hoisted out of the instance definition.
> fix hoisting of functions that reference imported values

- src/compile/render-dom/index.ts
- src/compile/render-ssr/index.ts
- test/runtime/samples/store-auto-subscribe-implicit/_config.js
- test/runtime/samples/store-auto-subscribe-implicit/main.html
fixes #1883. This is the minimal fix, that just removes props with a leading `$`; it doesn't change anything in `stats` since that'll presumably get a larger overhaul separately
> prevent duplicate declaration of store values

- site/content/examples/parallax/App.html
It’s very common for http: URLs not to load in https: page now. These images are served on https: also, so use that.
Another note on this example: the lack of an `alt` tag is causing a11y warnings. I haven’t taken any action on *that*.
> Update parallax example to use https: URLs

- src/preprocess/index.ts
- test/preprocess/index.js
This just always preserves attributes when passing components through `.preprocess` (#1873). It doesn't provide any way to control these attributes. I think we should see how well we do with this. We can always add the ability to adjust the attributes later post-3.0.
> preserve attributes during preprocess

- site/README.md
- site/package.json
Brings over and updates the helpful bits from svelte.technology's readme. Also tidies a couple of things in site/package.json, including a new `npm run update` (not thrilled with this name) that calls `update_template.sh` and `get-contributors.js` and going forward anything else we only really need to do once after cloning and then right before deploying.
> site: update readme and tidy package.json

- site/content/guide/06-special-components.md
- src/compile/nodes/Body.ts
- src/compile/nodes/shared/mapChildren.ts
- src/compile/render-dom/wrappers/Body.ts
- src/compile/render-dom/wrappers/Fragment.ts
- src/compile/render-ssr/Renderer.ts
- src/parse/state/tag.ts
- test/parser/samples/error-svelte-selfdestructive/error.json
- test/runtime/samples/document-event/_config.js
- test/runtime/samples/document-event/main.html
Fixes #1846. `<svelte:body>` is a _little_ confusing in that it seems to maybe indicate that we will be placing things inside the body. (That sort of feature could always be added later though.)
> replace <svelte:document> with <svelte:body>

- src/compile/render-dom/Block.ts
- src/compile/render-dom/wrappers/Slot.ts
- src/utils/CodeBuilder.ts
- test/js/samples/if-block-no-update/expected.js
- test/js/samples/if-block-simple/expected.js
- test/js/samples/use-elements-as-anchors/expected.js
- test/runtime/samples/component-slot-used-with-default-event/Nested.html
- test/runtime/samples/component-slot-used-with-default-event/_config.js
- test/runtime/samples/component-slot-used-with-default-event/main.html
This adds a little step to slot rendering that makes event handlers render inside a conditional for the slot default content, which fixes #1977, but...
There's an issue with code builder that causes some weird end of block `}`s to get misplaced with stacked `addConditional` and `pushCondition`s, generating invalid code in the destroy handler. I got a little lost trying to track the stringy handling in the code builder, so I wimpled out and rewrote it as a tree of collected statements that handle stringification in the `toString` method. This may totally not be a direction anybody wants to take, but it simplified the management of statements quite a bit. The stringification is a little complex, but it is all bundled together in one relatively readable chunk.
If it's a reasonable approach, …
> Render default slot content event handlers conditionally (with bonus) - #1977

- src/compile/render-dom/wrappers/Element/Binding.ts
- src/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/binding-this-with-context/_config.js
- test/runtime/samples/binding-this-with-context/main.html
This may be way off base (especially based on #1927), as it was my first look at the svelte v3 code. It takes contextual deps in a member expression for this bindings and passes them through to the generated binding function. It also adds an update handler for this bindings such that they will unregister in an old position and reregister at a new position, but only if they are the registered node at the old position.
If this is a sane approach, would it also need a test for keyed iteration?
> Attempt at #1916, including update handling

- src/compile/nodes/shared/TemplateScope.ts
- test/runtime/samples/mutation-tracking-across-sibling-scopes/_config.js
- test/runtime/samples/mutation-tracking-across-sibling-scopes/main.html
This sets deps of a reference as mutated along with the reference so that update code is not skipped for the reference deps if they also happen to appear in an adjacent scope.
This is an area that could probably use a little bit of improvement down the road. Right now, deps on any given expression don't really indicate which parts are affected by mutation e.g. in `{#each foo[bar] as whatever}<button on:click={() => whatever.sure += 'yes'}>mutate foo, but not bar</button>{/each}`. With this PR, `bar` will also be flagged as mutated, which isn't exactly ideal, as it's not in this case.
> Fix adjacent tracking across adjacent scopes - #1985

- src/compile/Component.ts
- test/js/samples/hoisted-let/expected.js
- test/js/samples/hoisted-let/input.html
- test/js/samples/if-block-no-update/expected.js
- test/js/samples/if-block-simple/expected.js
- test/js/samples/instrumentation-template-if-no-block/expected.js
- test/js/samples/use-elements-as-anchors/expected.js
This addresses the second part of #1952 — `let x = 1` and `const x = 1` are both treated the same way if `x` is never reassigned, which can result in slightly less code.
> hoist vars and lets that don't change

- site/src/routes/repl/embed.html
- site/src/routes/repl/index.html
- site/src/routes/repl/local.js
- site/static/workers/bundler.js
- site/static/workers/compiler.js
There's still some weirdness surrounding navigation/history API that I wasn't able to track down. If you are on a given example with `version=local` and then you navigate to another example and then press 'Back', you will end up on the first example with the latest alpha version, and I have no idea why. I don't know where else popstate is being handled.
> repl: implement version=local

- src/compile/Component.ts
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/runtime/samples/reactive-values-readonly/_config.js
- test/runtime/samples/reactive-values-readonly/main.html
fixes #1920. Specifically, `$: doubled = a * 2` will run when *either* `a` or `doubled` are dirty, meaning that as soon as you write to it, it changes back to the correct value.
> prevent writing to reactive values

- src/compile/nodes/shared/Expression.ts
- src/compile/nodes/shared/TemplateScope.ts
- test/runtime/samples/each-block-scope-shadow/_config.js
- test/runtime/samples/each-block-scope-shadow/main.html
- test/runtime/samples/module-context-with-instance-script/_config.js
- test/runtime/samples/module-context-with-instance-script/main.html
I think this is pretty straightforward - a name must be flagged as hoistable at the component level _and_ be referring to a name in the root template scope in order to not require `ctx.` for access. See #2002.
> Make sure a hoistable name is not also shadowed when rendering and expr - #2002

- src/compile/render-dom/wrappers/Element/Binding.ts
- src/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/binding-store-deep/_config.js
- test/runtime/samples/binding-store-deep/main.html
- test/runtime/samples/binding-store/_config.js
- test/runtime/samples/binding-store/main.html
fixes #1997. I've come around to the idea that it should be possible to bind to store values, even though there are some caveats around which stores are suitable. Maybe a documentation question more than anything?
One thing you can't do: bind to a nested property, e.g. `bind:value={$user.name}`. That's because stores check referential equality (i.e. they expect immutable data), and there's no way to create a clone of `user` with the new `name` property without making certain assumptions about what `user` is. It will currently throw an error instead. Suggestions for better alternatives welcome.
> bind to store values in simple cases

- package-lock.json
- src/compile/index.ts
- test/css/index.js
- test/helpers.js
- test/hydration/index.js
- test/runtime/index.js
- test/server-side-rendering/index.js
Still trying to fix a weird bug exposed by the Sapper test suite, and hoping that this will somehow help. As a bonus, it means that bundler integrations no longer need to [generate a name themselves](https://github.com/rollup/rollup-plugin-svelte/blob/22d834558a6ef0bc00fc771d899d7151dfa93602/index.js#L230), and that fewer components will unhelpfully be called `<Index>` when debugging.
Though I've just realised we need to sanitise the name as well...
> get name based on filename

- package.json
- src/compile/nodes/Attribute.ts
- src/compile/nodes/Element.ts
- src/compile/nodes/shared/Expression.ts
- src/compile/render-dom/index.ts
- src/compile/render-dom/wrappers/DebugTag.ts
- src/compile/render-dom/wrappers/Element/index.ts
- src/compile/render-dom/wrappers/InlineComponent/index.ts
- src/compile/render-dom/wrappers/Slot.ts
- src/parse/state/tag.ts
Encountering a truly bizarre issue where `[...thing]` is getting compiled by... *something?* to `thing.slice()`, which is incorrect in the case where `thing` is a non-Array iterable. My attempts to figure out where it's failing have stalled, so i'm just going to do this instead
> avoid spread pattern, it causes some problems with some setups somehow???

- index.mjs
- src/internal/scheduler.js
- test/runtime/samples/lifecycle-next-tick/_config.js
- test/runtime/samples/lifecycle-next-tick/main.html
I think this is an improvement — it allows this sort of thing...
```js
import { nextTick } from 'svelte';
async function indentTextarea() {
const { value, selectionStart, selectionEnd } = indent(textarea);
// trigger update
code = value;
// wait until update has occurred
await nextTick();
// do DOM manipulation that would otherwise be clobbered
textarea.selectionStart = selectionStart;
textarea.selectionEnd = selectionEnd;
}
```
...as opposed to putting the post-update stuff in a callback. One question: should the callback style still be supported?
> Return promise from nextTick

- site/src/routes/repl/_components/Output/Viewer.html
- site/src/routes/repl/_utils/replProxy.js
- site/static/repl-runner.js
- don't bind props until after component is created
- remove debug spam
- destroy replproxy event listener on component destroy
- all replproxy commands now return a value
- more sandbox restrictions lifted (only remaining is is origin protection)
> repl improvements

- src/compile/Component.ts
- test/stats/samples/duplicate-globals/_config.js
- test/stats/samples/duplicate-globals/input.html
- test/stats/samples/duplicate-non-hoistable/_config.js
- test/stats/samples/duplicate-non-hoistable/input.html
- test/stats/samples/duplicate-vars/_config.js
- test/stats/samples/duplicate-vars/input.html
fixes #2036. Turns out to be less complicated than i thought — since the dupe check was only an internal sanity check during the recent factor, and since instance variables naturally take precedence over module variables (because the module context is analysed first), all we need to do is remove the dupe check.
Smuggled in a couple of other fixes while I was at it.
> remove unnecessary dupe check

- package-lock.json
- src/compile/render-dom/index.ts
- test/cli/samples/custom-element/expected/Main.js
- test/custom-elements/index.js
- test/custom-elements/samples/initial-props/main.html
- test/custom-elements/samples/initial-props/test.js
- test/js/samples/css-shadow-dom-keyframes/expected.js
There is kind of a race condition when loading a Svelte custom element. `customElements.define` seems to synchronously mount all existing matching elements and calls `attributeChangedCallback` which ends up calling `this._recompute` which is undefined at that point.
This happens in several cases, see => #2049.
> Fix "this._recompute is not a function"

- site/src/routes/repl/_components/Output/Viewer.svelte
This adds allow-modal to the iframe sandbox allowing the use of `alert` from components. Fixes some demos including the 7guis-flight-booker
> Allow repl to use alert

- site/src/routes/blog/rss.xml.js
Fixes #2085.
All we have for the blog posts is a day, so I'm generating dates at noon UTC on that day. Plus also fixed stray commas between each `<item>`, and some other tidying.
With these changes, the W3 feed validator still has a couple of other 'best practices' notes about the feed (which I didn't look at too closely), but it does now say it is valid.
> fix invalid blog rss feed

- src/compile/nodes/shared/Expression.ts
- test/runtime/samples/store-contextual/_config.js
- test/runtime/samples/store-contextual/main.svelte
Ref #2016. Contextual stores present some difficulties, and I think it'd be better to figure those out in a 3.1 release rather than hold up 3.0
> error on contextual stores, for now

- src/internal/dom.js
- src/internal/lifecycle.js
- src/internal/transitions.js
This is one possible solution to #2018. It penalises non-IE11 users, which I don't like, but I'm not sure there's a clean alternative that doesn't involve polyfilling (which is a nuisance, even if the polyfill is small and simple).
Also, maybe it's better *not* to use `legacy` for this, since the other two places where it's used (for try-catching `input.type = type`, and replacing `element.dataset.foo = bar` with `element.setAttribute('data-foo', bar)`) are for IE9 (I think?), and it'd be nice if Svelte supported IE11 *without* the legacy flag since a lot of people are still in the unfortunate position of supporting it.
Any strong feelings either way?
> Use initCustomEvent instead of new CustomEvent

- site/src/routes/repl/_components/Repl.svelte
The REPL save crashes on broken code because the bundle is null. 
The save and fork features only use the `components` and `values` properties, so I have just made it put an empty imports if bundle is not defined. 
This solves the immediate problem of not being able to fork or save when there is a bug in svelte compiler or the code. The downside is that downloads will work but will not have the imports applied. I thought about maybe caching the last valid bundle.imports and using that in case of error, but decided to leave that alone.
> Fix REPL save and fork when code doesn't compile

- site/static/workers/compiler.js
- src/compile/Component.ts
- test/vars/samples/implicit/_config.js
- test/vars/samples/template-references/_config.js
1. Makes the `vars` output from the compiler also include implicit vars in script-less components (so that these vars will appear in the REPL props editor)
2. Makes the props editor only display `writable` vars, so exported constants and methods will not appear
> Some fixes for REPL props editor

- src/compile/nodes/Action.ts
- src/compile/nodes/Animation.ts
- src/compile/nodes/Transition.ts
- test/vars/index.js
- test/vars/samples/actions/_config.js
- test/vars/samples/actions/input.svelte
- test/vars/samples/animations/_config.js
- test/vars/samples/animations/input.svelte
- test/vars/samples/transitions/_config.js
- test/vars/samples/transitions/input.svelte
Fixes #2133, using the last method I commented about in that issue. I'm not completely confident that this is the way to fix it, it seems to work and doesn't seem to break any other tests.
> Fix vars `referenced` for actions/animations/transitions in non-DOM generate mode

- site/src/routes/tutorial/[slug]/index.svelte
- site/src/routes/tutorial/index.json.js
Add an "Improve this Tutorial" link at the bottom of the tutorial sidebar. Links to the section+chapter's text.md file (currently explicitly to the restructure-docs branch).
Also redid the display of "Show Me" / "Next" links as flexbox instead of floats so the div height is right.
Example:
> Add 'Improve this Tutorial' link

- src/compile/Component.ts
I _think_ this fixes https://github.com/sveltejs/svelte/issues/2127. I don't fully understand the magic string stuff, but it looks like declarations below a _subscribable_ were being grouped with declarations above it, and that caused it to overwrite part of the declaration for the subscribable.
I am not sure how to add test cases yet, but with this change the [example component](https://v3.svelte.technology/repl?version=3.0.0-beta.8&gist=9e08a9527c9fe70db79681d9f0d46a78) in #2127 compiles correctly, if not optimally in all cases.
```js
function instance($$self, $$props, $$invalidate) {
let $b;
let { a } = $$props;
let { b } = $$props; subscribe($$self, b, $$value => { $b = $$value; $$invalidate('$b', $b) });
let { c } = $$props;
$$self.$set = $$props => {
if ('a' in $$props) …
```
> subscribable declarations trigger a new group (#2127)

- store.mjs
- test/store/index.js
Resolves #2060. There have been a few people asking for some nice way to get a store's current value (in contexts where autosubscription is not possible). This simply exposes the existing function in `svelte/internal` as `get` in `svelte/store`. I'm not positive this is a good idea, but it's definitely a better idea than requiring a `.get()` as part of the store contract or blessing such a method by having it be part of the default `readable` and `writable` stores.
> expose get() from svelte/store

- src/compile/Component.ts
- test/runtime/samples/mixed-let-export/_config.js
- test/runtime/samples/mixed-let-export/main.svelte
Forces a new declaration if the next variable is not exported.
```js
let a, b
export { a }
```
Becomes:
```js
let { a } = $$props; let b;
```
Fixes https://github.com/sveltejs/svelte/issues/2165
> Fix code generation for non-exported vars after an export

- site/content/tutorial/06-bindings/05-textarea-inputs/text.md
The textarea tutorial example code was missing a `>` at the end.
> Fix textarea tutorial example code

- src/compile/Component.ts
- test/runtime/samples/prop-exports/_config.js
- test/runtime/samples/prop-exports/main.svelte
Hopefully the last one of these for a while! A few other edge cases came up in discord where subtle ordering of exports, or single-line exports with stores would cause svelte to generate invalid code. I tried to cover these all, as well as other valid [export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) syntaxes that weren't supported before.
This set of changes simplifies code generation for exports/props a little; there should be fewer edge cases around stores with the `if variable.subscribable` conditional inlined with the rest of the logic instead of branching around it.
The declaration grouping is a little different here too - instead of treating stores as their own group, and creating a new group after every store, stores are now added to the …
> more export codegen fixes

- src/compile/render-dom/wrappers/Element/Binding.ts
- store.mjs
- test/runtime/samples/binding-store-deep/_config.js
- test/store/index.js
Fixes #2171. TODO implement deep bindings
> Stores accept mutable data

- package-lock.json
- package.json
- test/custom-elements/index.js
Nightmare is unmaintained AFAICT. Puppeteer is newer, faster, and actively supported. The custom element tests run a lot faster with this PR
> swap out nightmare for puppeteer

- site/src/components/Repl/Output/Viewer.svelte
- site/static/workers/bundler.js
If the main App in the REPL has named module exports, Rollup complains about bundling to IIFE and puts the default export under `.default` in the IIFE's return value. This passes the `output.exports = 'named'` option to Rollup so that it doesn't complain and will instead always include the default export under `.default` regardless of whether there are other named exports - and then it uses `new SvelteComponent.default()` rather than `new SvelteComponent()` when instantiating the component.
> repl: deal with named module exports from main App

- src/compile/Component.ts
- test/js/samples/reactive-values-non-writable-dependencies/expected.js
- test/validator/samples/reactive-declaration-no-deps/errors.json
- test/validator/samples/reactive-declaration-no-deps/input.svelte
Fixes #2173. As a bonus, also produces nicer output in [this case](https://github.com/sveltejs/svelte/pull/2228/files#diff-4824807d0852d37b0cb95a3c50b4ecc4R24).
> Only include writable vars in reactive declaration dependencies

- package-lock.json
- package.json
- src/compile/Component.ts
Works around #2214 for the time being. Also upgrades Acorn so that `export { some_undeclared_global };` is a parsing error.
> Disallow `export ... from` statements

- src/internal/transitions.js
- test/runtime/samples/transition-js-events/_config.js
- test/runtime/samples/transition-js-events/main.svelte
fixes #2158. Turned out the event was firing, but it was firing *during* the component's flushing cycle (instead of triggering a new one), which has no effect.
> dispatch transition events inside render callback

- src/compile/Component.ts
- src/compile/nodes/shared/Expression.ts
- src/compile/render-dom/index.ts
- src/compile/render-ssr/index.ts
- test/runtime/samples/store-auto-subscribe-missing-global/_config.js
- test/runtime/samples/store-auto-subscribe-missing-global/main.svelte
Per [discussion](https://github.com/sveltejs/svelte/issues/2139#issuecomment-467885387) on #2139, this is an alternative to #2155. If a component has `{$foo}` and `foo` is undefined, Svelte issues the 'foo is not declared' warning as usual, but still compiles, on the assumption that `foo` is a global store. If it's not, then it errors at runtime.
> Subscribe to global stores

- src/compile/nodes/shared/Expression.ts
Fix #2139
Should there be a test for this?
> Throw descriptive error when 'subscribable' of undefined

- site/content/examples/08-motion/01-spring/App.svelte
- src/motion/spring.js
Ref #2167. Fixes:
* `precision` is now configurable, and defaults to 0.001 rather than 0.000001
* the `threshold` derived from `precision` applies to both delta and velocity
* only the promise from the most recent `set`/`update` call will resolve, if those functions are called again before the spring has completed (previously, when the spring settled it would resolve many promises simultaneously, helping no-one)
> various spring fixes

- src/compile/Component.ts
- test/runtime/samples/prop-const/Nested.svelte
- test/runtime/samples/prop-const/_config.js
- test/runtime/samples/prop-const/main.svelte
> prevent overwriting export consts

- src/compile/render-dom/wrappers/Slot.ts
Fixes https://github.com/sveltejs/svelte/issues/2122.
As far as I can tell (I might be wrong in my analysis), a slot will call the `.p()` update method of the slotted block, not caring whether the slotted block has or hasn't an update method. Compile-time checks of `block.hasUpdateMethod` only give information about the slot itself, not the slotted block (in other words, https://github.com/IvanSanchez/svelte/commit/14d2651e0aa4c6f194a004df23a7d1154776190b just doesn't fix the issue).
An alternative solution would be to put a `noop` update method in all blocks susceptible of ever being slotted.
> Check if slotted component has an update function during runtime

- src/compile/Component.ts
- src/compile/index.ts
- src/interfaces.ts
- src/parse/index.ts
Ref #2025. Probably some rough edges, and also no new unit tests yet.
This adds validation to `options.customElement` - if present, it must be `true` or an object containing optional `tag` (which must be a valid tag name) and/or `props` keys, and no additional keys.
I saw some conflicting stuff in the code and docs about whether we wanted to also allow options.customElement to be a string, which would be the same as passing that as options.customElement.tag. **Do we want to support this?**
If the user requests compilation to a custom element (by passing either `true` or an object to `options.customElement`) but does not specify `options.customElement.tag` or `<svelte:options tag='...'/>`, we throw an error.
When compiling, `this.tag` comes first from from …
> update options.customElement/<svelte:options tag='...'> handling

- src/compile/Component.ts
- src/compile/render-dom/index.ts
- test/runtime/samples/renamed-instance-exports/_config.js
- test/runtime/samples/renamed-instance-exports/main.svelte
Fixes #2253.
There's a lot of other extraneous stuff going on in my comments on the issue, which I think boils down to `const` exports not being present unless `accessors: true` is specified, which I don't think is the intended behavior. I'll open a separate issue for that.
> fix renamed instance exports

- src/compile/Component.ts
- src/compile/render-dom/index.ts
- test/runtime/samples/store-assignment-updates-reactive/_config.js
- test/runtime/samples/store-assignment-updates-reactive/main.svelte
Fixes #2119, sort of. 'Sort of' because it doesn't (and can't) reorder statements based on what function calls they make, but it makes it possible to use the idiomatic `$store = value` form which *can* cause statements to be reordered.
(I'm ok with topological ordering failing in these pathological cases, since the fix is simple — manually order them correctly. In most cases I suspect people will naturally do that anyway. So this PR just takes us from 99% to 99.9%.)
> Handle store assignments in reactive statements

- src/compile/Component.ts
- src/compile/index.ts
- src/compile/nodes/Text.ts
- src/compile/render-dom/wrappers/Text.ts
- src/interfaces.ts
- src/internal/dom.js
- test/helpers.js
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/js/samples/do-use-dataset/expected.js
- test/js/samples/dont-use-dataset-in-legacy/expected.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/event-modifiers/expected.js
- test/js/samples/inline-style-unoptimized/expected.js
- test/js/samples/instrumentation-script-if-no-block/expected.js
- test/js/samples/instrumentation-script-x-equals-x/expected.js
- test/js/samples/instrumentation-template-if-no-block/expected.js
- test/js/samples/instrumentation-template-x-equals-x/expected.js
- test/js/samples/non-imported-component/expected.js
- test/js/samples/use-elements-as-anchors/expected.js
- test/runtime/samples/binding-input-checkbox/_config.js
- test/runtime/samples/component-data-dynamic/_config.js
- test/runtime/samples/custom-method/_config.js
Sort of a last-minute thing but the prevalence of strings like `"\n\n\t\t\t"` in the generated code is a frequent complaint. This PR introduces a `preserveWhitespace` compiler option — if it's not `true`, and a given text node isn't inside a `<pre>`, those strings will be replaced with `space()`.
There are almost certainly other things we can do to reduce the need even for these — #189 — but this seems like an obvious starting point.
> collapse consecutive whitespace characters

- src/compile/nodes/Element.ts
Fixes #2300. This fixes and tidies a couple of the validation error messages related to binding - most notably directing people toward 'group' binding when they try to use 'checked' binding on radio inputs.
> tidy some binding validation messages

- site/content/tutorial/06-bindings/09-media-elements/app-a/App.svelte
- site/content/tutorial/06-bindings/09-media-elements/app-b/App.svelte
Nothing too complicated here. These assets only work when loaded via https on the [tutorial page](https://v3.svelte.technology/tutorial/media-elements).
> Fix media element tutorial

- src/parse/state/tag.ts
- test/runtime/samples/dynamic-component-ref/main.svelte
Fixes #2284.
I'm not sure what the `// TODO post v2, treat this just as any other attribute` comment here is referring to. It looks like this was added just before the v1 -> v2 switch, but I don't think there's anything we want to change here. I've removed the comment, but can put it back in if there's something still pending here.
> find this= in <svelte:component> in presence of bind:this=

- store.mjs
- test/store/index.js
fixes #2296. This is a **breaking change** for anyone using `readable` in the current beta versions.
> update readable signature to match writable

- src/compile/Component.ts
- src/compile/nodes/Binding.ts
- test/validator/samples/binding-invalid-value-global/errors.json
- test/validator/samples/binding-invalid-value-global/input.svelte
- test/validator/samples/undefined-value-global/input.svelte
- test/validator/samples/undefined-value-global/warnings.json
Fixes #2295. An exception and a warning about global variables were not raised when the variable was also referenced in the script. A couple of checks for presence in `var_lookup` have also been augmented to check whether the variable has `global` equal to true.
> Fix exception and warning for global variables

- package-lock.json
- package.json
- site/src/routes/repl/_components/AppControls/index.svelte
- site/src/routes/repl/index.svelte
- site/src/routes/tutorial/[slug]/index.svelte
Latest svelte-repl removes the Mapbox stuff in favour of being able to pass through a `setup` prop containing code you need to run before the REPL initialises.
Plus a style fix
> More REPL stuff

- src/preprocess/index.ts
- test/preprocess/samples/partial-names/_config.js
- test/preprocess/samples/partial-names/input.svelte
- test/preprocess/samples/partial-names/output.svelte
The current regexes for script and style tags for preprocessing match too much - after `<script` or `<style` we need there to either be whitespace or `>`.
> don't preprocess tags whose names begin with script/style

- site/content/tutorial/08-stores/03-readable-stores/app-a/stores.js
- site/content/tutorial/08-stores/03-readable-stores/app-b/stores.js
- site/content/tutorial/08-stores/03-readable-stores/text.md
The argument order for readable stores was changed to keep it consistent with writable. As a result the tutorial stopped working. This fixes that, which is discussed in #2330
> reverse readable stores arg order in tutorial, fixes #2330

- src/compile/nodes/Element.ts
- src/compile/render-dom/wrappers/Element/Attribute.ts
- src/compile/render-dom/wrappers/Element/Binding.ts
- src/compile/render-dom/wrappers/Element/index.ts
- test/js/samples/media-bindings/expected.js
- test/js/samples/media-bindings/input.svelte
- test/runtime/samples/binding-audio-currenttime-duration-volume/_config.js
- test/runtime/samples/binding-audio-currenttime-duration-volume/main.svelte
I naively applied the behaviour of volume/volumechange to playbackRate/ratechange.
I'm unsure about the tests. 
Compilation tests fails (for all lines) eventhough the expected and actual js seem to be the same. maybe line-endings?
For the runtime test, I realised there is a skip parameter set to true in there, so not sure if this is even needed.
> Add playbackrate as binding (and property) for media elements, fixes #2202

- site/content/tutorial/06-bindings/11-bind-this/app-a/App.svelte
- site/content/tutorial/06-bindings/11-bind-this/app-b/App.svelte
> Remove unused r variable in bind-this tutorial.

- src/compile/Component.ts
- test/runtime/samples/function-hoisting/_config.js
- test/runtime/samples/function-hoisting/main.svelte
Top-level functions that are hoistable, but referenced by other functions, were not being hoisted because of this `!checked.has(node)`. If the referencing function was defined first, it would be hoisted, leaving the referenced function inside the instance scope and causing a reference error.
Fixes https://github.com/sveltejs/svelte/issues/2278
> hoist all hoistable functions

- src/internal/dom.js
Only update the text node if the text node's value is not equal. This fix is for contenteditable usage where text content may change outside of Svelte's control in order to preserve text composition.
Accomplishes the same thing as #2341 without the added API.
> Update text.data only when necessary

- src/compile/Component.ts
- test/runtime/samples/prop-exports/_config.js
- test/runtime/samples/prop-exports/main.svelte
Non-renamed exports initialized with a literal were being hoisted, leading to a `$$props` reference outside the component instance.
```js
let name = 'world';
export { name };
```
> $$props is not defined
Fixes https://github.com/sveltejs/svelte/issues/2347
> Don't hoist non-renamed exports

- src/compile/render-dom/wrappers/Element/Attribute.ts
- test/runtime/samples/contextual-callback-b/_config.js
- test/runtime/samples/contextual-callback-b/main.svelte
Fixes #2348. Same issue as in #2115.
> Pass block to the render of an expression in an attribute

- site/content/docs/02-template-syntax.md
- site/content/docs/03-run-time.md
I originally started this PR because the link `[stores](tutorial/writable-stores)`
renders as http://localhost:3000/tutorial/writable-stores on https://v3.svelte.technology/docs#svelte-store.
No idea why because the rest of the relative links in content/ have the same format.
> API docs: remove an absolute URL

- site/content/docs/03-run-time.md
- store.mjs
- test/store/index.js
As discussed briefly in chat, this adds a third argument `initial_value` to derived stores to be used in async stores.
It also updates the API docs - I don't _think_ there's any other documentation we need to update.
> add initial_value argument to derived store

- src/compile/Component.ts
- src/compile/render-dom/index.ts
- src/compile/render-ssr/index.ts
- src/compile/utils/get_object.ts
- src/compile/utils/scope.ts
- src/compile/utils/unwrap_parens.ts
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/js/samples/instrumentation-script-if-no-block/expected.js
- test/js/samples/reactive-values-non-topologically-ordered/expected.js
- test/js/samples/reactive-values-non-writable-dependencies/expected.js
- test/runtime/samples/reactive-values-implicit-destructured/_config.js
- test/runtime/samples/reactive-values-implicit-destructured/main.svelte
- test/runtime/samples/reactive-values-implicit-self-dependency/_config.js
- test/runtime/samples/reactive-values-implicit-self-dependency/main.svelte
- test/runtime/samples/reactive-values-no-dependencies/_config.js
- test/runtime/samples/reactive-values-no-dependencies/main.svelte
- test/validator/samples/reactive-declaration-no-deps/errors.json
- test/validator/samples/reactive-declaration-no-deps/input.svelte
fixes #2285. Would be nice if we could eliminate any `$$invalidate(...)` calls at the top level, but I think that would require an extra pass, so going to ignore that for now
> allow reactive declarations without dependencies

- site/src/routes/blog/_posts.js
- site/src/routes/docs/_sections.js
- site/src/routes/tutorial/[slug]/index.json.js
- site/src/utils/markdown.js
This PR solves the problem when external links in Tutorial, Docs and Blog are open in the same browser tab. 
I added `link_renderer` for Marked, that looking for links with hrefs which started from "http" and adding `target="_blank"` attribute to them.
> add link_renderer to handle external links

- transition.mjs
A few small tweaks to the built-in transitions:
* the `fly` transition now accepts an `opacity` parameter between 0 and 1, which defaults to 0. If 1, the opacity is unchanged during the transition
* the `scale` transition respects any existing opacity
* the `draw` transition's `duration` parameter can be a `path_length => milliseconds` function instead of a `milliseconds` number. There's also an alternative `speed: n` parameter which is the same as `duration: len => len / n`
> better transitions

- src/compile/render-dom/wrappers/InlineComponent/index.ts
- src/internal/Component.js
- src/internal/scheduler.js
- test/runtime/samples/component-binding-blowback-d/One.svelte
- test/runtime/samples/component-binding-blowback-d/Two.svelte
- test/runtime/samples/component-binding-blowback-d/_config.js
- test/runtime/samples/component-binding-blowback-d/main.svelte
- test/runtime/samples/component-binding-blowback-e/One.svelte
- test/runtime/samples/component-binding-blowback-e/Two.svelte
- test/runtime/samples/component-binding-blowback-e/_config.js
- test/runtime/samples/component-binding-blowback-e/main.svelte
- test/runtime/samples/component-binding-blowback-f/One.svelte
- test/runtime/samples/component-binding-blowback-f/Two.svelte
- test/runtime/samples/component-binding-blowback-f/_config.js
- test/runtime/samples/component-binding-blowback-f/main.svelte
I hate these kinds of bugs. So far this PR fixes the simple case (where values are primitives) by only firing the binding callback when values have changed. It gets a little trickier with non-primitives
> Prevent infinite loops with chained bindings

- site/content/tutorial/02-reactivity/04-updating-arrays-and-objects/app-a/App.svelte
- site/content/tutorial/02-reactivity/04-updating-arrays-and-objects/app-b/App.svelte
- site/content/tutorial/02-reactivity/04-updating-arrays-and-objects/text.md
> add tutorial chapter for mutations

- .gitignore
- animate.mjs
- rollup.config.js
- transition.mjs
Ref #2241.
Not sure if these are ready to be promoted to built-in functions yet. I'm encountering occasional hard-to-reproduce positioning bugs, and `crossfade` doesn't handle changes in size (but maybe that's ok given its intended use? I think we *can* accommodate size changes, it just involves `style.transformOrigin` and some arithmetic).
Also, if you look really closely the `crossfade` opacity isn't quite right — since one side goes from 0 to 1 and the other goes from 1 to 0, in the middle they're both 0.5 which results in a total opacity of 0.75, when you really want the total opacity to stay at 1 throughout. Unfortunately the only way to achieve that is to use [this blending formula](https://github.com/Rich-Harris/ramjet/blob/master/src/interpolators/opacity.js) which requires that …
> add crossfade and flip functions

- site/src/components/Repl/ReplWidget.svelte
- site/src/routes/repl/embed.svelte
- site/src/routes/repl/index.svelte
- site/src/routes/tutorial/[slug]/index.svelte
It makes sense to be explicit about this (and not just point to `latest`) so that we don't break things for people visiting the v3 REPL anew once v4 comes out. This is actually causing a problem on the v2 REPL right now, I'll open an issue over there.
> site: update REPL from svelte@beta to svelte@3

- site/src/routes/blog/[slug].svelte
- site/src/routes/blog/index.svelte
- site/src/routes/docs/index.svelte
- site/src/routes/examples/index.svelte
- site/src/routes/index.svelte
- site/src/routes/repl/embed.svelte
- site/src/routes/repl/index.svelte
- site/src/routes/tutorial/[slug]/index.svelte
this should improve our lighthouse score, which is currently being penalised in the SEO section
> add regular <meta> tags

- README.md
We have a problem with loading picture in the readme. Just threw it on imgur.
> Banner fix

- site/Dockerfile
This just uses the latest Node docker image. 
I saw message in Discord about it solving the `node-gyp` stderr output, but it doesn't solve it.
Oh well, might as well use latest Node version.
> Chore: Deploy with Node 11.14

- site/package-lock.json
- site/package.json
- site/src/server.js
The site has a lot of unspecified Cache-Control values for _many_ files.
For example, all images, SVGs, and fonts had no caching declared. There were also some straggler `.json` and `.css|js` files that had no values.
It seemed like 10m was the preferred value elsewhere in the site, so I used that as the default value.
To change a file or mark it as not cacheable, you'd set a value elsewhere, ([example](https://github.com/sveltejs/svelte/blob/b1312175bc8a803b4a5236decfd7731b0186f8bb/site/src/routes/blog/%5Bslug%5D.json.js#L16)).
I also verified that the `service-worker.js` maintains its `no-cache, no-store, must-revalidate` setting.
> Site: Default Cache-Control value

- site/.dockerignore
- site/.gcloudignore
- site/Dockerfile
- site/Makefile
A few changes here:
- the Makefile now uses `gcloud builds submit` to build the image (remotely) rather than locally with Docker and then pushing it
- there's now a `.dockerignore` which whitelists only the files needed by the Sapper app
- there's a `.gcloudignore` that just points to that `.dockerignore` (the reason for having both is so that the old `docker build` will continue to work nicely if so desired)
- the `Dockerfile` now only copies the `package[-lock].json` files to the first container before installing deps, and then copies the installed packages and every (non-ignored) file in the directory to the second and final container (this is to avoid a little bit of extra copying of the app itself to the first container, which isn't really necessary)
- installation of npm packages is …
> site: use gcloud CLI to build Docker image

- site/content/tutorial/01-introduction/03-dynamic-attributes/text.md
Alternatively, `alt="A man dancing"` could also be removed with no detrimental side effects IMO.
> Update alt text in 01.03 to clarify "shorthand attributes"

- site/src/routes/index.svelte
there's a 404 link to https://svelte.dev/TODO-blog-post-on-css-in-js on the homepage which I believe should link to this blog post instead: https://svelte.dev/blog/svelte-css-in-js
> Fix broken link to CSS in JS blog post

- site/src/components/TopNav.svelte
- Listens to hashchange event
- Changes only the visibilty when not triggered by hashchange
Resolves #2456
> Don't show/hide nav when clicking in docs sidebar

- src/internal/scheduler.js
- Scheduling an update no longer allocates two new promises, only one via `then`.
- The `tick` method was really returning an empty, resolved promise, so just reusing the same promise (`resolved_promise`) there as well. It was a little confusing because it _looked_ like it would return a promise to when the flush had completed, but in fact it was returning a promise that would resolve before the flush completed, as it was the promise that was "thenned" for the flush.
@Rich-Harris I tried to follow your coding conventions, hopefully it's adequate.
> perf: Reuse the same promise instance in the scheduler

- src/compile/Component.ts
- test/runtime/samples/export-function-hoisting/_config.js
- test/runtime/samples/export-function-hoisting/main.svelte
For exported function declarations, the child declaration is the node that gets added to the `walking` set, so we have to check that too to detect a cycle in this case
Closes https://github.com/sveltejs/svelte/issues/2542
> Fix is_hoistable cycle

- src/compile/utils/scope.ts
- test/runtime/samples/reactive-value-mutate/_config.js
- test/runtime/samples/reactive-value-mutate/main.svelte
Fixes #2510 and #2514. Any reactive assignment where the LHS was a mutation causes an exception currently.
>  handle unknown nodes in extract_identifiers

- site/content/docs/02-template-syntax.md
This answers the immediate question I had when I first saw the `class:foo` syntax.
> add multiple class toggles example

- src/compile/render-dom/wrappers/Element/Binding.ts
https://github.com/sveltejs/svelte/issues/2506
Adding additional check for input type "text" on input's value is already the same as a new value.
> Fixing issue with cursor jumping in Safari #2506

- site/src/routes/examples/_TableOfContents.svelte
- site/src/routes/examples/index.svelte
- site/static/icons/loading.svg
Add a loading icon I made in SVG: it uses SMIL animation so it might not be well supported on IE/Edge but I think Edge will be powered by Chromium pretty soon.
Also set the REPL orientation based on the width as discussed in #2466
Closes #2527
> Site examples: add a cache and show a loading icon

- site/src/routes/docs/_GuideContents.svelte
- site/src/routes/docs/index.svelte
Currently, the mobile docs sidebar is unusable in mobile (white on white background) : 
- Puts the text color in mobile to var(--second)
- Fixes the scroll shadow on scrollbar
- Better size handling
> Fix unusable docs sidebar in mobile

- site/content/tutorial/05-events/03-event-modifiers/text.md
*E.g.* is an English language idiom that can be said in a plainer way, easier for non-native speakers to understand.
Personal preference is to use plainer language when possible, but I wouldn't be offended if this were rejected.
> Change use of "e.g." to "for example"

- site/content/tutorial/06-bindings/09-media-elements/text.md
The assets are not loading when copy/pasting it in the editor, due to protocol mismatch.
> Update tutorial video chapter assets URLs with HTTPS

- src/internal/utils.js
There is a bit of excitement in the RxJS community about Svelte.
- It seems like the rest of Svelte "just works™" with RxJS!
- **BUT** The danger is that unwary users will figure out how smooth this API is and accidentally create nasty memory leaks if the returned RxJS Subscriptions are not handled. Fortunately the required change is small.
NOTE: I am not entirely sure how to test this change. The goal here is to make sure that whenever you would normally teardown your store subscriptions, it is also tearing down these RxJS-shaped subscriptions. This is most commonly something you want in a component scenario. Say you have a timer component in your app that you show and remove with an `{#if}` block, when the `{#if}` block hides the component, you'd want to tear down the underlying …
> fix: Ensure RxJS users don't create memory leaks

- site/content/docs/03-run-time.md
This PR documents how `component.$on` returns a function that removes the event listener when called.
> Site: Document how to remove a component.$on listener

- site/content/docs/02-template-syntax.md
Just a small typo fix for the docs here https://svelte.dev/docs#Slots
> Site: Fix slot typo in docs

- site/src/routes/examples/index.svelte
- site/src/routes/repl/index.svelte
Applying this fix to make the site accessible on mobile again,
will remove when https://github.com/sveltejs/svelte-repl/issues/8 gets fixed and published
Fixes #2499 #2550
> Site: REPL temp fix for touch devices

- site/README.md
- site/src/server.js
It was a bit out of date (no mention of scopes as of today when we create an app on github) and pointed out the readme
> Update the message in the popup we get when we login in the REPL

- site/content/docs/02-template-syntax.md
- site/content/docs/03-run-time.md
Documents `createEventDispatcher`. I don't know if all of this information should be here but the `on` directive is pretty sparse and just links to this part of the docs, so I included information about listening and the `payload` as well.
I was also unsure about the function signature for this, I couldn't see anything quite like it.
#2533
> Site: Document createEventDispatcher.

- site/content/docs/03-run-time.md
Documents `svelte/animate`. Only one function `flip`. I changed the section heading as it was incorrect.
I don't know if the duration as function was intended to be part of the API but I assumed so. This was more confusing than I expected. Do with it as you will.
Would be nice to have an interactive widget here to show what this function does.
#2536 
Edit: `crossfade` lives in `svelte/transition`.
> Site: Document svelte/animate - flip.

- site/static/global.css
This PR narrows down the catch-all checkbox `:before`/`:after` transitions to just the background and left offset to remove flicker.
Fixes https://github.com/sveltejs/svelte/issues/2614.
> Narrow down checkbox transitions to background and left

- site/content/tutorial/01-introduction/01-basics/text.md
The current documentation mentions "to the right" which is not accurate for people reading the tutorial on narrow-viewport devices.
I changed it to "the code editor", but this may be improved upon to match other more common references.
> improve referencing to code editor for mobile readers

- src/parse/state/mustache.ts
By removing the parsing code for the old v1 each block key notation, we can get rid of the current error message when trying to use it ([REPL](https://svelte.dev/repl?version=3.1.0&gist=99d4394b54f093c2b69d683ebff4678c)):
```
(svelte plugin) TypeError: Cannot read property '1' of null
src/App.svelte
TypeError: Cannot read property '1' of null
1   at parts.forEach (…/svelte/compiler.js:14336:42)
```
And get a more descriptive parsing error instead:
```
(svelte plugin) ParseError: Expected }
src/App.svelte
6: </script>
7:
8: {#each items as item @id}
^
9:   <div>{item.name}</div>
10: {/each}
```
> Remove v1 each key parsing

- site/content/docs/02-template-syntax.md
Added a brief mention of `intro: true` in the transition directive section. I didn't actually know this option made it into v3 and there is no mention of it around the transition section. I felt it was worth a brief mention and a link just to highlight it.
> Site: Briefly mention intro:true in the transition directive section.

- site/content/tutorial/01-introduction/06-html-tags/text.md
When reading this part of the tutorial I was a bit suprised, I made this doc change to clarify the intents in my eyes. Maybe I'm wrong in this change (I don't know svelte that long yet), but from what I see in that tutorial step the normal `{string}` does escape for html context.
> Clarify when sanitization is done and when not

- src/utils/names.ts
Adding `alert`, `confirm`, and `prompt` to `globals` makes is so Svelte doesn't warn when using it in an inlined event handler.
Closes https://github.com/sveltejs/svelte/issues/2648
> Add alert, confirm, and prompt to globals

- src/compile/render-dom/index.ts
- test/runtime/samples/store-increment-updates-reactive/_config.js
- test/runtime/samples/store-increment-updates-reactive/main.svelte
Fixes #2625. Also dries up the invalidation code a bit. It was in fact an imperfect mirroring of the `AssignmentExpression` branch in the `UpdateExpression` branch that was causing this bug.
~~Possible future optimization: Also allow `UpdateExpression`s to get the `single` treatment here if they are `prefix: true` or if we can safely convert them to `prefix: true` because their value is currently discarded.~~ Never mind, we're further from this than I thought. `$foo += 42;` also does not currently get optimized this way. Maybe someday.
> fix invalidating stores with UpdateExpression

- src/compile/render-dom/index.ts
- test/runtime/samples/reactive-values-fixed/_config.js
- test/runtime/samples/reactive-values-fixed/main.svelte
`injected` and `fixed_reactive_declarations` are currently only checked if `reactive_declarations` has any elements, which makes it so reactive values derived from non-writable values will not end up in the rendered code unless there is at least one reactive value derived from writable values in the component.
By checking `injected` and `fixed_reactive_declarations` independently from `reactive_declarations` it works as expected.
Closes https://github.com/sveltejs/svelte/issues/2285
> Check 'injected' and 'fixed_reactive_declarations' independently

- src/compile/render-dom/index.ts
- test/runtime/samples/store-resubscribe-b/_config.js
- test/runtime/samples/store-resubscribe-b/main.svelte
Fixes #2435, hopefully. I _think_ that all that's necessary here is to skip the optimization that was added as part of #2398 when we're invalidating a variable that is subscribable and reassigned. The stuff in `pending_assignments` will later all get run through `component.invalidate` which will generate the appropriate code.
> fix resubscriptions inside script block

- src/internal/spread.js
- test/runtime/samples/component-slot-spread-props/Nested.svelte
- test/runtime/samples/component-slot-spread-props/_config.js
- test/runtime/samples/component-slot-spread-props/main.svelte
This PR makes is so the `$$scope` property of the `$$props` object will not be included in a spread update to avoid errors like `DOMException: Failed to execute 'setAttribute' on 'Element': '$$scope' is not a valid attribute name.`
By setting `$$scope` as accounted for straight away in `get_spread_update` it will not be part of the update.
Fixes https://github.com/sveltejs/svelte/issues/2520
> Remove the $$scope key from $$props when calculating spread

- src/internal/dom.js
This PR defaults the second argument of `insertBefore` to `null`, so that environments that require that the anchor is either a node or `null` won't throw an error when the anchor is `undefined`.
Fixes https://github.com/sveltejs/svelte/issues/2573
> Make null the default anchor of insertBefore

- site/content/docs/04-compile-time.md
- src/index.ts
- src/interfaces.ts
- src/parse/index.ts
I am currently working on making the `prettier-plugin-svelte` compatible with Svelte 3. I noticed that `compile` has to be called to get the AST. This leads to errors in some tests, because they cannot be compiled.
For example, the following test: https://github.com/UnwrittenFun/prettier-plugin-svelte/blob/master/test/printer/samples/binding-shorthand.html
**Error: `value is not declared`**
But regardless of my use case, I think it makes sense to get the AST without a compilation step.
> Expose `parse` to the public

- src/compile/render-dom/wrappers/Element/Attribute.ts
Using this we treat `form` as if it doesn't have a property on element, since that one is read only.
This should generate the wanted behavior, without generating an exception.
Closes #1742
> Applying read only property form onto elements using `attr` instead

- src/compile/nodes/EachBlock.ts
- src/compile/render-dom/wrappers/EachBlock.ts
- src/compile/utils/tail.ts
- src/internal/dom.js
- src/parse/read/context.ts
- test/runtime/samples/each-block-destructured-object-rest/_config.js
- test/runtime/samples/each-block-destructured-object-rest/main.svelte
- test/validator/samples/each-block-destructured-object-rest-comma-after/errors.json
- test/validator/samples/each-block-destructured-object-rest-comma-after/input.svelte
This PR adds support for the object-rest syntax in the destructuring part of `{#each}` blocks.
Closes https://github.com/sveltejs/svelte/issues/2647
> Add support for object-rest in each destructuring

- src/compile/nodes/EachBlock.ts
- src/parse/read/context.ts
- test/parser/samples/each-block-destructured/input.svelte
- test/parser/samples/each-block-destructured/output.json
Inspired by #2647, I've been messing about with the parser code to integrate array destructuring.
Might be of use for somebody working on that issue. 
This should allow something like:
```html
{#each sequence as [first, ...rest]}
<b>{first}</b><i>{rest}</i>
{/each}
> each-block array destructuring

- src/motion/spring.js
Use verlet-style integration for spring animations. Rather than keeping track of "value" and velocity over time, keep track of value and previous-value, and derive velocity from the delta every tick. This has a few benefits, including greater stability (position and velocity can't drift) and simplifying signature of tick_spring (no need to pass velocity back up).
Pulling "settled" flag out of the return signature as well means return value is just "next value", simplifying code mapping over objects and arrays, and eliminating duplicated code across get_initial_velocity, get_threshold and tick_spring.
Refactored "threshold" calcs, extremely inexpensive to do inline in tick_spring rather than create a parallel structure. Also fixes a rare pathological case where springs will never settle …
> Subtle tweaks to spring animations

- site/content/docs/01-component-format.md
Just adding a bit of extra example code to clarify that an exported const is read only externally, to avoid confusion.
> Exported properties let vs const clarification

- src/compile/Component.ts
- test/validator/samples/module-script-reactive-declaration/input.svelte
- test/validator/samples/module-script-reactive-declaration/warnings.json
- test/validator/samples/reactive-declaration-non-top-level/input.svelte
- test/validator/samples/reactive-declaration-non-top-level/warnings.json
This PR makes it so a warning is raised when a reactive declaration is used in a module script, or when it is used at a non-top-level in an instance script.
Closes https://github.com/sveltejs/svelte/issues/2176.
> Warn on improper use of reactive declarations

- site/content/examples/14-composition/04-modal/App.svelte
I think most newcomers would expect an example that initially & always shows a button for launching the modal, and then shows the modal after clicking on the button.  
I was originally confused by the modal showing up first, and essentially swapping spots with the button.  It misled me to wonder if there was logic that needed to be moved into the Modal component.
> Make modal example more obvious

- src/utils/names.ts
To prevent the following warning message:
```
(!) svelte plugin: 'window' is not defined
src/templates/Share.svelte
20: </script>
21:
22: {#if window.navigator.share}
^
23:   <button class="icon-share2" on:click="{shareNatively}" title="Share"></button>
24: {:else}
```
Related PR: #2649
> Add `window` and `document` to globals

- src/compile/Component.ts
- test/runtime/samples/reactive-value-function-hoist/_config.js
- test/runtime/samples/reactive-value-function-hoist/main.svelte
This PR makes it so functions dependent on injected reactive declaration variables are not hoisted out of the instance.
Closes https://github.com/sveltejs/svelte/issues/2687
> Don't hoist functions dependent on injected reactive variables

- src/compile/render-dom/wrappers/Slot.ts
> Initialize `get_slot_changes` to null when not needed

- src/internal/Component.js
To be sure that we won't have any hidden behavior related to a prototype: https://davidwalsh.name/object-create-null
> Make component.$$.dirty just a dictionary

- site/content/docs/01-component-format.md
Inspired by https://github.com/sveltejs/svelte/issues/98#issuecomment-491586072 , I wanted to make it a bit more explicit that the `$:` label was actual JS syntax.
> Link to label syntax page on MDN

- site/content/tutorial/06-bindings/01-text-inputs/text.md
> Pluralize elements

- site/content/docs/03-run-time.md
- store.mjs
- test/store/index.js
fixes #2553. This makes it trivial to do things like this...
```js
import { writable, derived } from 'svelte/store';
const hz = writable(60);
const heartbeat = derived(hz, ($hz, set) => {
const interval = setInterval(() => {
set(Date.now());
}, 1000 / $hz);
return () => clearInterval(interval);
});
```
...or, more practically, poll a URL for data where the variables can change. It doesn't attempt to fix your race conditions, but that's easy enough to do in userland.
> allow derivers to return cleanup functions

- site/content/docs/02-template-syntax.md
This PR documents animations (animate directives). Animations are very similar to transitions, so I drew inspiration from that section. 
They are pretty straightforward but you might want to take a look at some of the wording. The bit about the `from` and `to` properties might need making a little clearer, I *think* it makes sense but I know what they are so other perspectives would be good. I included a link to the MDN `DOMRect` article but I don't know if you wnat to keep that in. I also included the DOMRect signature along with the other signatures at the top of the section.
The example I included for `tick` is pretty bad, I really couldn't think of anything. We could probably do with a better example there.
I also included a link to the `flip` function since this is how animate will …
> Site: Document animations. #2532

- site/content/docs/03-run-time.md
This is a new PR, I did something with the other one and I don't know what.
I didn't want crossfade to hold up the 'regular' transition docs any longer because I'm struggling with that one.
> Document svelte/transition - fade, fly, slide, scale, draw.

- src/parse/state/tag.ts
- test/validator/samples/attribute-expected-equals/errors.json
- test/validator/samples/attribute-expected-equals/input.svelte
This PR excludes quotation marks and apostrophes when reading an attribute name to [comply with the HTML 5 parser spec](https://stackoverflow.com/questions/925994/what-characters-are-allowed-in-an-html-attribute-name#answer-926136), and also raises `ParseError: Expected =` if a quotation mark or apostrophe is found after an attribute name instead of an equals sign.
Closes https://github.com/sveltejs/svelte/issues/1513
> Add error for missing equals after attribute name

- src/compile/Component.ts
- src/compile/render-dom/index.ts
- test/runtime/samples/reactive-value-mutate-const/_config.js
- test/runtime/samples/reactive-value-mutate-const/main.svelte
By taking mutated non-writable variables into consideration when looking for reactive declaration dependencies, reactive declarations using them will be run again when they are mutated.
Closes https://github.com/sveltejs/svelte/issues/2728
> Set mutated const variables as reactive dependencies

- src/compile/render-dom/wrappers/Element/StyleAttribute.ts
- test/runtime/samples/attribute-url/_config.js
- test/runtime/samples/attribute-url/main.svelte
Everything in the `style` attribute after the opening quote mark in `url('...` is included in the chunk text. This PR sets `quote_mark` to `null` when the closing quote mark is found.
Closes https://github.com/sveltejs/svelte/issues/2715
> Set quote_mark to null when closing quote mark is found

- src/compile/Component.ts
- src/compile/render-dom/index.ts
- test/custom-elements/index.js
- test/custom-elements/samples/no-tag-warning/_config.js
- test/custom-elements/samples/no-tag-warning/main.svelte
- test/custom-elements/samples/no-tag-warning/test.js
- test/custom-elements/samples/no-tag/_config.js
- test/custom-elements/samples/no-tag/main.svelte
- test/custom-elements/samples/no-tag/test.js
FIX #2417
* warning given on compile if tag is absent
* no warning if tag is set to `null`
> Allows custom element to be defined without a tag

- src/compile/render-dom/wrappers/Element/StyleAttribute.ts
- Remove the `result` not null chekcing since it's always an object.
- ~~Remove the `super.render(block)` since `style_props` won't be falsy.~~
> refactor: remove unnecessary return null in style attribute

- package-lock.json
Fix vulnerabilities from `js-yaml` and `handlebars`
<details><summary>Audit Report</summary>
<p>
=== npm audit security report ===                        
Moderate        Denial of Service                                             
Package         js-yaml                                                       
Dependency of   codecov [dev]                                                 
Path            codecov > js-yaml                                             
More info       https://nodesecurity.io/advisories/788                        
Moderate        Denial of Service                                             
Package         js-yaml                                                       
Dependency of   eslint [dev]                                                  
Path …
> chore(npm): fix vulnerabilities from npm audit

- src/compile/render-dom/wrappers/Element/Attribute.ts
- test/runtime/samples/attribute-dataset-without-value/_config.js
- test/runtime/samples/attribute-dataset-without-value/main.svelte
> fix: 🐛 data attributes without value outputting as "true"

- src/store.ts
The docstrings are visualized in VS Code when using the api.
> Add docstrings to store

- site/content/docs/01-component-format.md
Current docs give the impression that functions can not be default values for props. Suggestion to make the distinction between expressions and declarations clearer.
> Docs: Exporting function expression vs declaration

- src/compile/Component.ts
- test/custom-elements/samples/no-svelte-options/_config.js
- test/custom-elements/samples/no-svelte-options/main.svelte
- test/custom-elements/samples/no-svelte-options/test.js
Fix for #2821 where no `<svelte:options />` are declared and compiler configured with `customElement: true`
> Allow custom element to be declared with no tag and no options

- site/content/examples/19-7guis/05-7guis-crud/App.svelte
Currently, the first name and last name inputs fields can't be edited without the changes immediately being overwritten back to the selected person's first name and last name. This change will make it so that the input fields only get overwritten with the selected person's first name and last name when the selected person is changed.
Issue:
https://github.com/sveltejs/svelte/issues/2852
Current version (not working):
https://svelte.dev/repl/783f270559c64b2d95253088acd97f26?version=3.4.2
Proposed version (working):
https://svelte.dev/repl/65d2dbc9b60f4a9e9c9fdc6abc8a831c?version=3.4.2
> Fix CRUD example to allow changing input values.

- src/compile/render-dom/index.ts
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/runtime/samples/dev-warning-unknown-props/Foo.svelte
- test/runtime/samples/dev-warning-unknown-props/_config.js
- test/runtime/samples/dev-warning-unknown-props/main.svelte
#2174: checks for any props which have been passed to the component on create that do not match it's writable props and, when detected, emits a warning such as the following:
```
<X> was created with unknown attribute 'y'
```
> check for unknown props when creating component

- src/parse/state/tag.ts
- src/parse/state/text.ts
- test/parser/samples/attribute-escaped/output.json
- test/parser/samples/convert-entities-in-element/output.json
- test/parser/samples/convert-entities/output.json
- test/parser/samples/nbsp/output.json
Adds a `raw` property to text nodes with decoded html entities set to the original data.
> Fixes #2714: Provide non-decoded text to `parse` consumers

- src/compile/nodes/Binding.ts
- src/compile/nodes/shared/Node.ts
- src/compile/render-dom/wrappers/Element/Binding.ts
- src/compile/render-ssr/handlers/Element.ts
- test/server-side-rendering/samples/bindings-readonly/_expected.html
- test/server-side-rendering/samples/bindings-readonly/main.svelte
Fixes #2339 by:
* moving `is_readonly` into the common `Binding` AST class
* preventing the following bindings from being emitted into the SSR code:
* `bind:clientWidth`
* `bind:clientHeight`
* `bind:offsetWidth`
* `bind:offsetHeight`
* `bind:duration`
* `bind:buffered`
* `bind:seekable`
* `bind:played`
* `bind:value` (only for  `input` with `type=file`)
> Omits readonly attributes from SSR code

- site/src/routes/examples/index.svelte
Addresses #2898 
The `offset` property was being overwritten to `1` every time `offset` changed, so the viewport wasn't being set to anything else. It looks like the issue was present in all browsers.
FYI, I'm new to svelte, so if there's a more idiomatic way to do this, let me know. Thanks!
> Issue #2898 -- Fix overwrite of 'offset' value in reactive statement

- src/compiler/interfaces.ts
I was reading the source and noticed this typo. (assuming this to be one :P)
> Fix `expresion` typo in `MustacheTag` interface

- src/runtime/internal/transitions.ts
- test/runtime/samples/transition-js-events-in-out/_config.js
- test/runtime/samples/transition-js-events-in-out/main.svelte
> * If your pull request implements a new feature, please raise an issue to discuss it before sending code. In many cases features are absent for a reason.
1. Its not a new feature. Its a missed functionality, I guess.
> * This message body should clearly illustrate what problems it solves. If there are related issues, remember to reference them.
2. Specific transition events (`introstart, introend, outrostart, outroend`) work just with using `transition` directive, but not in the case of `in:fade` or `out:fade` ( #2655 )
> * Ideally, include a test that fails without this PR but passes with it. PRs will only be merged once they pass CI. (Remember to `npm run lint`!)
3. Test added
> Fix for #2655 - adding introstart...outroend events to in-out transition

- register.js
```js
path.parse(filename).name
// is same result and better
path.basename(filename)
.slice(0, -path.extname(filename).length)
```
Why better:
- Faster: You can check [here](https://repl.it/@Hongarc/test-parse-name)
- Easy to understand
> refactor: better parsing name of file

- site/package-lock.json
- site/package.json
- site/src/routes/repl/local/[...file].js
The mate to https://github.com/sveltejs/svelte-repl/pull/27
This endpoint was turned into a spread to support requesting files down in directories. The old regex check `/^[a-z.]+$/` has also been removed because it's now too restrictive. Hopefully this won't be too much of a security risk, as this endpoint is only allowed to run in development. This could still be tightened up if desired though.
> site: support new folder structure in REPL

- site/content/docs/02-template-syntax.md
While `cart.empty` could be passed around, it is undefined on first render and results in an error being thrown. The example here was broken and needed fixing.
> Fix component binding example

- src/runtime/store/index.ts
- test/store/index.ts
This solves the problem described in #2660 (I thought it had been fixed in #1882, but that solution was too naive; it only invalidated direct children, whereas invalidations should actually flow through the entire graph).
Could maybe use a bit of tidying up and DRYing out, but thought I'd leave it here anyway
> solve diamond dependencies

- site/content/tutorial/01-introduction/03-dynamic-attributes/text.md
Added a period at the end of the alt text example, recently learned that it improves UX for screen-reader users as it provides a pause.
> Ending alt text with a period

- src/compiler/compile/render-ssr/handlers/Element.ts
- test/runtime/samples/binding-textarea/_config.js
- test/server-side-rendering/samples/text-area-bind/_expected.html
- test/server-side-rendering/samples/text-area-bind/main.svelte
This was a bit of a mess, In short:
-This fixes #2915
-An old test at test/runtime/samples/binding-textarea was causing problems so I changed it too, took me a while to figure out.
> ssr-textarea-bind-fix

- src/compiler/compile/nodes/InlineComponent.ts
- src/compiler/compile/render-dom/wrappers/InlineComponent/index.ts
- src/runtime/internal/utils.ts
- test/runtime/samples/component-event-handler-modifier-once/Button.svelte
- test/runtime/samples/component-event-handler-modifier-once/_config.js
- test/runtime/samples/component-event-handler-modifier-once/main.svelte
- test/validator/samples/component-event-modifiers-invalid/errors.json
- test/validator/samples/component-event-modifiers-invalid/input.svelte
> support once modifier on component events, fail on others

- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/render-dom/wrappers/Element/Binding.ts
- src/compiler/compile/render-dom/wrappers/Element/index.ts
- src/compiler/compile/render-ssr/handlers/Element.ts
- test/runtime/samples/contenteditable-html/_config.js
- test/runtime/samples/contenteditable-html/main.svelte
- test/runtime/samples/contenteditable-text/_config.js
- test/runtime/samples/contenteditable-text/main.svelte
- test/validator/samples/contenteditable-dynamic/errors.json
- test/validator/samples/contenteditable-dynamic/input.svelte
- test/validator/samples/contenteditable-missing/errors.json
- test/validator/samples/contenteditable-missing/input.svelte
Fixes #310
Adds a special :text and :html bindings for contenteditable elements.
> Add bind:text and bind:html support for contenteditable elements

- scripts/create-stubs.js
For reasons that I won't begin to try and understand, when webpack imports something like `svelte/internal` from (say) `svelte/store`, it ignores the `resolve.mainFields` and `resolve.extensions` that the developer has explicitly specified in `webpack.config.js`, and only respects the `main` property of the package.json.
Luckily, we can omit the file extension for `main` and it will basically work *as if* that weren't the case. Hopefully it doesn't break anything else in the meantime.
> Change package.json stubs to work with webpack's module resolution

- appveyor.yml
Follow up to #2970, also make sure we support node v8+ on Windows.
> Update Appveyor's configuration

- site/content/examples/19-7guis/05-7guis-crud/App.svelte
This example could delete the incorrect person when a filter was applied. Just an example, but the behavior was confusing when I played with it, so I thought it worth fixing.
> Fix 7 GUIs crud example for delete when filtered

- scripts/create-stubs.js
Hi, 
I created this branch to reproduce the error https://github.com/pyoner/svelte-ts-template/tree/3.5.1
I got error
```bash
svelte-ts-template git:(3.5.1) ✗ npm run build
> svelte-ts-app@1.0.0 build /home/jungle/repo/svelte-ts-template
> rollup -c
src/main.ts → public/bundle.js...
node_modules/svelte/internal/index.d.ts:1:15 - error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing '../types/runtime/internal/index' instead.
1 export * from '../types/runtime/internal/index.d.ts';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/svelte/store/index.d.ts:1:15 - error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing '../types/runtime/store/index' instead.
1 export * from '../types/runtime/store/index.d.ts'; …
```
> fix(create-stubs): An import path cannot end with a '.d.ts' extension.

- src/runtime/internal/utils.ts
This fixes: https://github.com/sveltejs/svelte/issues/2933
Issue has been in place since 3.4.3 and later, 3.4.2 is working as expected.
Reproduction of the issue can be found here:
[![Edit icy-grass-vv0y6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-grass-vv0y6?fontsize=14)
Check the console of the browser to see the error mentioned.
Basically the requestAnimationFrame is extracted from the window, which gives it the wrong context when triggered during animation time. The context when triggering a requestAnimationFrame should always be the window. So binding it when reassigning it fixes this issue.
I haven't added tests to cover for this change. I'm not sure how to approach that, anyone that can help me and figure that out?
> Fix request animation frame context

- src/runtime/ambient.ts
- src/runtime/index.ts
Currently, TypeScript will complain about `.svelte` files with `Cannot find module './App.svelte'.ts(2307)`.
If we include an ambient declaration with svelte's types, these will go away and instead users will get a generic svelte component. They won't see their specific accessors or named exports, but at least they won't get an error out of the box.
> Add ambient types for `*.svelte` files

- site/content/docs/02-template-syntax.md
I found it hard to use parts of the docs because their headlines did not remind me of the syntax they describe. Especially “Actions”, which is called `use` in code. While I was at it I added short syntax examples to a number of other headlines as well. Hopefully this makes it easier to get an overview of the syntax and to lookup documentation for code you may not be 100% sure what it does, without relying on ⌘F.
Fair warning: I did this PR from my phone, so autocorrect might have snuck in a typo somewhere.
> Clearer headlines with syntax examples

- src/compiler/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/script-style-non-top-level/_config.js
- test/runtime/samples/script-style-non-top-level/main.svelte
Fixes #2745, and also fixes another bug I discovered while looking at that one. The .innerHTML representation of 'raw' (non-top-level script and style) tags wasn't escaping the character it needed to for use in string templates.
> fix text nodes in .innerHTML-optimized output

- src/runtime/internal/keyed-each.ts
- test/runtime/samples/each-block-keyed-shift/Nested.svelte
- test/runtime/samples/each-block-keyed-shift/_config.js
- test/runtime/samples/each-block-keyed-shift/main.svelte
This should fix #3055. This PR prevents `outro_and_destroy_block` from calling `block.d()` in the `transition_out` callback, since `transition_out` already calls `block.d()`.
> Fix each blocks not unmounting components correctly

- site/content/tutorial/16-special-elements/04-svelte-window-bindings/app-a/App.svelte
- site/content/tutorial/16-special-elements/04-svelte-window-bindings/app-b/App.svelte
Hey,
I've just improved the code of the [tutorial](https://svelte.dev/tutorial/svelte-window-bindings) a little bit. As I understand, someone forgot to do it earlier.
> Site: Reuse `layers` variable in window bindings tutorial

- site/content/docs/01-component-format.md
- site/content/docs/02-template-syntax.md
Closes #2676
Also completed the substitution of the code blocks language from `html` to `sv` where applicable.
> Docs: document rest in array/object destructuring in each blocks

- site/content/docs/02-template-syntax.md
Fixes #3061
See the discussion at https://github.com/sveltejs/svelte/pull/3062
> Use consistent tag closing for <svelte:*> elements

- src/compiler/compile/render-dom/wrappers/InlineComponent/index.ts
- src/compiler/compile/utils/flatten_reference.ts
- test/runtime/samples/binding-this-component-computed-key/Foo.svelte
- test/runtime/samples/binding-this-component-computed-key/_config.js
- test/runtime/samples/binding-this-component-computed-key/main.svelte
- test/runtime/samples/binding-this-component-each-block-value/Foo.svelte
- test/runtime/samples/binding-this-component-each-block-value/_config.js
- test/runtime/samples/binding-this-component-each-block-value/main.svelte
- test/runtime/samples/binding-this-component-each-block/Foo.svelte
- test/runtime/samples/binding-this-component-each-block/_config.js
- test/runtime/samples/binding-this-component-each-block/main.svelte
This PR fixes #2333 by allowing flatten_reference to handle computed properties.
> Fix binding this to a computed property

- src/compiler/compile/render-dom/index.ts
- test/runtime/samples/binding-using-props/TextInput.svelte
- test/runtime/samples/binding-using-props/_config.js
- test/runtime/samples/binding-using-props/main.svelte
This PR fixes #2725.
The issue was that the code generated for `$set` references the wrong variable when `$$props` is present.
> Fix code generation when $$props is present

- src/compiler/parse/utils/html.ts
- test/parser/samples/attribute-escaped/input.svelte
- test/parser/samples/attribute-escaped/output.json
- test/runtime/samples/html-entities/_config.js
Attributes are not properly decoded, see sveltejs/sapper#759
This PR makes it a little better, but is still not perfect. For example `&#123abcd;` will be interpreted as `&#123` while throwing away `abcd;`. That code is invalid so I wouldn't worry about it.
More info: https://mathiasbynens.be/notes/ambiguous-ampersands
Fix sveltejs/sapper#759
> Fix ambiguous entities

- site/README.md
* Change the local install instructions to be able to use the local repl out of the box
This avoids potential confusion in setting the website up for local use. The instructions will not use the “thinnest” setup possible, so if you want that separated into a different set of installation instructions let me know.
* Add sections for Testing and Building
* Add a note that the local REPL will only work for the development page
> Update site README for local REPL

- src/runtime/internal/Component.ts
- test/runtime/samples/ondestroy-deep/A.svelte
- test/runtime/samples/ondestroy-deep/B.svelte
- test/runtime/samples/ondestroy-deep/C.svelte
- test/runtime/samples/ondestroy-deep/_config.js
- test/runtime/samples/ondestroy-deep/destroyed.js
- test/runtime/samples/ondestroy-deep/main.svelte
> always run onDestroy functions

- site/content/docs/01-component-format.md
- site/content/docs/02-template-syntax.md
This documents the fact that you can squelch the undefined prop warning by adding `= undefined`, and tidies up a few other bits as well
> tweak docs a bit

- src/compiler/compile/render_dom/index.ts
One of the changes in #2963 was to throw an error when decoding a `@` sigil that wasn't actually exported from `svelte/internal`. This causes a problem when we neglect to properly escape this elsewhere, like what was happening in the debug filename. When the filename included, for example, `@sapper`, this would throw an error. We're now properly escaping the sigil.
> escape `@` sigils in debug filename

- site/content/docs/03-run-time.md
Fixes a small issue in the example for derived stores.
In the example, the callback function attempts to read the value of the store `frequency` using `frequency` instead of `$frequency`.
> Fix error in derived store docs example

- site/content/tutorial/06-bindings/12-bind-this/text.md
**Summary**
Remove confusing change to canvas size on the `binding:this` section of the tutorial
**Summary**
In the documentation tutorial, the `binding:this` page shows how to bind a reference to an element. The helper text also shows a change to the canvas size attributes without any further explanation. The show me example does not mimic the `256` resolution of the canvas that is displayed in the help section.
**Notes**
- If we do want to show the relationship between the canvas element and referencing `canvas.width` then maybe we can change `app-b/App.svelte` to include the new dimensions that are shown in the help side panel.
- If we do want to change the resolution to show the binding, instead of changing the canvas from `32` to `256` which causes my mac book pro to whistle a …
> documentation - binding this remove 256 canvas size

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/compiler/compile/render_dom/wrappers/shared/bind_this.ts
- src/runtime/internal/scheduler.ts
- test/runtime/samples/binding-this-each-block-property-component/Foo.svelte
- test/runtime/samples/binding-this-each-block-property-component/_config.js
- test/runtime/samples/binding-this-each-block-property-component/main.svelte
- test/runtime/samples/binding-this-each-block-property/_config.js
- test/runtime/samples/binding-this-each-block-property/main.svelte
Extends https://github.com/sveltejs/svelte/pull/3099 by adding tests, DRYing out the `bind:this` code, and fixing the parallel case where the target is an element rather than a component
> DRY out bind:this code

- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/compiler/compile/render_dom/wrappers/Slot.ts
- src/compiler/compile/render_dom/wrappers/shared/is_dynamic.ts
- test/runtime/samples/component-slot-let-e/Nested.svelte
- test/runtime/samples/component-slot-let-e/_config.js
- test/runtime/samples/component-slot-let-e/main.svelte
This is an alternative to #3122. Rather than adding hoisted values to the context, it prevents them from being shadowed in the function that generates the slot context.
While I was in there, I optimised a few other things: it's more conservative about updating slots generally, and DRYs out the logic for determining if a variable is 'dynamic'.
> Pass hoisted values through to slots

- site/content/docs/03-run-time.md
`tweened` actually accepts `interpolate`, not `interpolator`. It was correctly shown in the code example (and tutorial), but not in the API docs.
Not sure if doing a full build of the site is necessary or desired for things like this, so I've just kept this change to the markdown file for now.
> Site: Change tweened docs to show "interpolate" option

- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/compiler/compile/render_dom/wrappers/shared/bind_this.ts
- src/runtime/internal/scheduler.ts
- test/runtime/index.js
- test/runtime/samples/binding-this-element-reactive-b/_config.js
- test/runtime/samples/binding-this-element-reactive-b/main.svelte
- test/runtime/samples/transition-js-if-block-outro-timeout/_config.js
This fixes #2034 by using `binding_callbacks` when setting the `foo` in `bind:this={foo}` to `null` as well as when setting it to an element reference. Otherwise, the invalidation has no effect.
We still need to null out references before setting new ones, in order to avoid glitches when lists are reordered. This is done by unshifting to `binding_callbacks` the functions that need to run later, as those functions are run in reverse order.
> update bind:this references when setting to null

- src/compiler/compile/nodes/Action.ts
- src/compiler/compile/nodes/Animation.ts
- src/compiler/compile/nodes/EventHandler.ts
- src/compiler/compile/nodes/Transition.ts
- src/compiler/compile/nodes/shared/Expression.ts
- test/js/samples/action-custom-event-handler/expected.js
- test/runtime/samples/reactive-function-inline/_config.js
- test/runtime/samples/reactive-function-inline/main.svelte
- test/runtime/samples/reactive-function/_config.js
This fixes #2693 by drawing a distinction between dependencies that are 'lazy' — e.g., in an event handler like `on:click={e => doThing(item)}`, we don't need to re-evaluate anything when `doThing` or `item` change because we only care about their values when the click event happens — and those that are not, such as in `{tags}`.
> distinguish between lazy and non-lazy expressions

- src/compiler/compile/css/Stylesheet.ts
- test/css/samples/unknown-at-rule-with-following-rules/expected.css
- test/css/samples/unknown-at-rule-with-following-rules/input.svelte
Fixes #3135.
When exiting an Atrule node, the broken code assumes that the next value in the stack is an Atrule, which is not always the case.
> Correctly restore current_atrule when leaving an Atrule node

- src/compiler/preprocess/index.ts
- test/preprocess/samples/attributes-with-equals/_config.js
- test/preprocess/samples/attributes-with-equals/input.svelte
- test/preprocess/samples/attributes-with-equals/output.svelte
Another weird edge case that I did not actually bump into, but thought of while looking at the code I borrowed for the ESLint plugin.
> preprocess: fix handling of attribute values containing `=`

- site/content/blog/2019-04-15-setting-up-your-editor.md
This PR adds instructions for setting the filetype in Vim for `*.svelte` files to HTML. This will enable syntax highlighting if the user has it enabled, along with any other settings the user has configured for HTML files.
Feel free to edit my language as you see fit, or to add or remove sections. I believe the vast majority of vim users will set this up in their `init.vim` once and not think about it again.
> Add instructions for setting filetype in Vim

- src/compiler/compile/nodes/shared/Expression.ts
- test/runtime/samples/function-expression-inline/_config.js
- test/runtime/samples/function-expression-inline/main.svelte
The instrumentation was wonky for two reasons:
* it was inserting code before semi-colons that should have gone *after* semi-colons
* it was tracking which assignments needed instrumentation on the way 'down' the AST, meaning they were getting applied prematurely if a suitable place (i.e. the next expression statement it found) was found further in. now, it tracks those assignments on the way 'up'
fixes #3038
> Fix assignments inside inline function expressions

- src/compiler/compile/render_dom/Block.ts
> escape `@` sigils in block comments

- src/runtime/transition/index.ts
Just thought it would be cool if the crossfade transition also scales the element to its new size
> make crossfade scale the element to target rect

- src/runtime/internal/ssr.ts
- src/runtime/store/index.ts
- test/store/index.ts
> handle rxjs-style observables with get_store_value

- src/runtime/internal/dom.ts
Fixes #3206 by adding tabIndex = -1 to the resize listener `<object>` element.
> make resize listener object element unfocusable

- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
fix cursor jumping when input type="email" or type="password" for Safari 12.1 and iOS Safari
> fixed #3199

- src/runtime/internal/transitions.ts
- test/runtime/samples/each-block-keyed-nested/Child.svelte
- test/runtime/samples/each-block-keyed-nested/_config.js
- test/runtime/samples/each-block-keyed-nested/main.svelte
- test/runtime/samples/head-detached-in-dynamic-component/A.svelte
- test/runtime/samples/head-detached-in-dynamic-component/B.svelte
- test/runtime/samples/head-detached-in-dynamic-component/_config.js
- test/runtime/samples/head-detached-in-dynamic-component/main.svelte
This fixes the second bug in #2086, in which nested keyed each blocks could create a situation in which outro callbacks got corrupted. Also brings a test over from #3159
> Prevent outro callback corruption

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/questions-and-help.md
- .github/PULL_REQUEST_TEMPLATE.md
As per my earlier PR on sveltejs/sapper
This PR provides templates for Bugs/Feature Requests/PRs opened against Svelte. The goal of this is noise reduction, as there are now 180 open issues and as Svelte grows, the number of unclosed/abandoned issues does too. This PR:
Auto labels issues according to their type when opened.
Asks for specific details regarding bugs, to allow them to be investigated more easily.
Provides links to the discord chat for support issues.
These are completely borrowed from https://github.com/metabase/metabase since having raised an issue there, I thought their system was fantastic.
Hope this helps!
> update issue templates to new format and add more detail

- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
Svelte can potentially produce `destroy_component(form, );`
which will fail parsing and to ES7.
This fixes it
> Fixes #3255

- site/content/examples/05-bindings/04-textarea-inputs/App.svelte
The [example](https://svelte.dev/examples#textarea-inputs) uses a variable called `value` and a shorthand binding notation `<textarea bind:value>`. I think the example is simpler, and more consistent with other binding examples, if it doesn't rely on the reader knowing about the shorthand notation. For example, I was confused when I renamed the `value` variable to `text`, and it didn't work:
```js
<script>
let text = `Some words are *italic*, some are **bold**`;
</script>
<textarea bind:text></textarea>
```
This commit uses a variable named `text`, rather than `value`, and avoids the shorthand binding form.
> Don't use shorthand binding in textarea example

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_ssr/handlers/Element.ts
- test/runtime/samples/class-with-dynamic-attribute-and-spread/_config.js
- test/runtime/samples/class-with-dynamic-attribute-and-spread/main.svelte
- test/runtime/samples/class-with-spread/_config.js
- test/runtime/samples/class-with-spread/main.svelte
Currently, if there is any spread prop along with a dynamic `class` prop on the element, the `class:` directives stop working once the value of the variable that `class` was dependent on changes. This is because it sets the `class` prop of the DOM element directly, removed the class attached by the `class:` directive. And since the variable affecting the directive hasn't changed, a class for it is not applied again.
This should not happen, and `class:` directive should work just fine with spread props.
I have added tests in this PR as well, which were failing with `v3.6.7`, but are fixed with the succeeding commits.
[REPL](https://svelte.dev/repl/70b4e4245520495194168acff6bc0cd0?version=3.6.7)
`WithoutSpread.svelte`
```js
p(changed, ctx) {
if (default_slot && default_slot.p && …
```
> [v3] Fix issue where class directives wouldn't work with spread props and class prop

- src/compiler/compile/css/Selector.ts
- test/css/samples/css-vars/expected.css
- test/css/samples/css-vars/input.svelte
- the change in #1705 introduced a small bug for users who were relying on assigning global CSS variables via the :root selector
- this change adds a small exemption to avoid prefixing the `:root` pseudo-selector with the random prefix that svelte adds
here is a screenshot that illustrates the bug (pre 3.6.3 [working], post 3.6.3 [broken]), and the corresponding source in my `App.svelte` component file:
```css
<style>
:root {
--unchecked-box: '\02610';
--checked-box: '\02611';
--snowman: '\02603';
}
</style>
```
> bugfix: exempt the :root psuedo-selector from the random css prefix

- site/content/docs/02-template-syntax.md
On the docs page, clicking on the 'keyed each block' link in the animate section did nothing before, now it takes you to the each blocks section like it's supposed to.
(This is my first open source pull request, let me know if you have any feedback for me, thanks!)
> Fixes 'Keyed each block' broken link in Docs

- site/content/docs/03-run-time.md
- site/content/tutorial/15-context/01-context-api/text.md
Is this enough? Is this the right place?
I put it in both so that it is clear regardless of where you are looking. I don't think we need an example of passing store into context since it is just another value but maybe I'm wrong.
Closes #3271.
> Document that context is not reactive.

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/js/samples/input-files/expected.js
Fixes #3226, hopefully. It seems that `change` fires on all browsers when the uploaded files change, while `input` does not fire on Safari.
> use `change` event for `bind:files`

- src/compiler/compile/render_dom/index.ts
- src/runtime/internal/ssr.ts
- src/runtime/internal/utils.ts
- src/runtime/store/index.ts
- test/runtime/samples/store-resubscribe-observable/_config.js
- test/runtime/samples/store-resubscribe-observable/main.svelte
Fixes #3304.
This also refactors stuff a little bit. The `subscribe` helper is now called `component_subscribe` (for lack of a better name), and there's a new `subscribe` helper that _just_ does subscription and returns the unsubscription function, whether this is a Svelte store or an RxJS observable. This new helper is now used in `component_subscribe`, `get_store_value`, and in the store reassignment/resubscription handling code.
> Support RxJS Observables in reassigned stores

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-alt-text/input.svelte
> fix erroneous a11y warning with input type='image'

- src/compiler/compile/nodes/shared/Expression.ts
- test/runtime/samples/event-handler-async/_config.js
- test/runtime/samples/event-handler-async/main.svelte
Fixes #3179. I don't know when generators would come up, but we ought to be able to correctly hoist those as well.
> preserve async/generator-ness of hoisted function expressions

- src/compiler/compile/css/Selector.ts
- test/css/samples/attribute-selector-bind/expected.css
- test/css/samples/attribute-selector-bind/input.svelte
Fixes #3281. I went ahead with my second idea, of `bind:foo` always matching `[foo]`. This feels tidier and potentially more future proof. Hopefully it doesn't get us into trouble.
> use bindings when matching attribute selector against element

- site/content/tutorial/15-context/01-context-api/text.md
Readers unfamiliar with the concept of object equality in Javascript may have a hard time understanding why using keys as a reference is safe. So I elaborated a little on it.
Also, I changed the "context is not reactive" part into a section of its own, deleting the word "Remember" from the opening. I couldn't remember it from previously on this page or in the tutorial, so I think it may be a leftover from a previous version of the tutorial.
> Elaborate on key equality

- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- test/runtime/samples/innerhtml-interpolated-literal/_config.js
- test/runtime/samples/innerhtml-interpolated-literal/main.svelte
fixes #3341, but only the first part (interpolated constants still cause Svelte to bail out of the `innerHTML` optimisation)
> prevent commas in attributes

- site/content/tutorial/15-context/01-context-api/text.md
I had a problem understanding why you would want to use a context when you can just use a store. This is what I've gathered after reading a bit about them.
> Explain difference between contexts and stores

- site/content/docs/02-template-syntax.md
- src/compiler/compile/Component.ts
- src/compiler/compile/nodes/Comment.ts
- src/compiler/compile/nodes/shared/map_children.ts
- test/validator/samples/ignore-warning/input.svelte
- test/validator/samples/ignore-warning/warnings.json
- test/validator/samples/ignore-warnings-cumulative/input.svelte
- test/validator/samples/ignore-warnings-cumulative/warnings.json
- test/validator/samples/ignore-warnings-newline/input.svelte
- test/validator/samples/ignore-warnings-newline/warnings.json
- test/validator/samples/ignore-warnings-stacked/input.svelte
- test/validator/samples/ignore-warnings-stacked/warnings.json
- test/validator/samples/ignore-warnings/input.svelte
- test/validator/samples/ignore-warnings/warnings.json
This is an alternative to #1861 with more specificity.
The idea is that you can add a comment like this...
```svelte
```
...and it will ignore any `a11y-missing-attribute` warnings on *the next non-text, non-comment node* (and any of its children). That includes `{#if ...}` etc and components.
So in a case like this...
```svelte
<div>
<marquee>
</marquee>
</div>
```
...we'd get an accessibility warning for the first `<img>` but not the second or third, and we'd get a separate warning for the `<marquee>`.
Multiple codes can be passed at once:
```svelte
<div>
<marquee>
</marquee>
</div>
```
They can be separated by newlines:
```svelte
<div>
<marquee>
</marquee>
</div>
```
They can be stacked:
```svelte
<div>
<marquee>
</marquee>
</div>
```
And they accumulate (i.e. earlier ignores are not …
> disable validation with magic comments

- site/content/tutorial/06-bindings/01-text-inputs/text.md
Performed pluralization via the `s` operator (non recursively for optimum performance).
> Fix typo (tutorial)

- site/content/tutorial/05-events/03-event-modifiers/text.md
- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/render_dom/wrappers/shared/add_event_handlers.ts
- src/runtime/internal/dom.ts
- test/runtime/samples/event-handler-modifier-self/_config.js
- test/runtime/samples/event-handler-modifier-self/main.svelte
- test/validator/samples/event-modifiers-invalid/errors.json
Added support for a `self` modifier.
The `self` modifier only triggers the handler if event.target is the element itself.
Added and updated the tests, and documentation.
I don't know if the ESlint plugin derives the allowed modifiers from this project so I haven't done anything in that regard, but I'll gladly take care of that if needed.
> #3372 Added a `self` event modifier

- src/compiler/compile/render_dom/wrappers/shared/Tag.ts
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/deconflict-builtins/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/js/samples/each-block-array-literal/expected.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/each-block-keyed-animated/expected.js
- test/js/samples/each-block-keyed/expected.js
- test/js/samples/hoisted-const/expected.js
- test/js/samples/hoisted-let/expected.js
- test/js/samples/instrumentation-script-x-equals-x/expected.js
- test/js/samples/instrumentation-template-x-equals-x/expected.js
- test/runtime/samples/reactive-value-coerce/_config.js
- test/runtime/samples/reactive-value-coerce/main.svelte
fixes #2290. It's unfortunate that this means adding `+ ""` in a bunch of places, but I'm not sure there's a way to guarantee correct behaviour otherwise (though if we were ambitious we might be able to determine statically if we were dealing with primitive values)
> coerce tag values to string

- src/compiler/index.ts
- src/compiler/preprocess/index.ts
Solves issue #3397 by removing external lib references from definition files. In one case (`estree-walker`), it seems to be unnecessary. In the other, as the `map` property apparently is not used by Svelte, it seemed reasonable not to force any specific type on the property.
This PR also refactors code to make better use the interface `Processed` and make it public.
> Remove external dependencies from exported files

- site/content/docs/04-compile-time.md
According to the definition in svelte/src/compiler/preprocess/index.ts, Preprocessor is defined as:
```
export type Preprocessor = (options: {
content: string;
attributes: Record<string, string | boolean>;
filename?: string;
}) => { code: string; map?: SourceMap | string; dependencies?: string[] };
```
The api doc mentioned `source` instead of `content` which conflicts with the implementation (also conflicts with the example right below the definition doc).
> Correct preprocessor api doc

- src/compiler/preprocess/index.ts
Solves issue #3396 by specifying that a preprocessor function can either return a `Processed` or a `Promise` of `Processed`.
> Change type of preprocessor functions to include Promise

- site/content/examples/05-bindings/10-bind-this/App.svelte
Removes the `let ctx` declaration in the scope outside the `loop` since it is shadowed by the `const ctx` declaration inside it.
> Examples: Remove unused variable

- site/content/docs/03-run-time.md
Their might have been a typo in the `transition` -> `draw` -> `speed` parameter description. According to it, half the speed halves the duration and double the speed doubles it (which doesn't make sense physicaly speaking). Let's try the other way around. :)
> Possible typo on transition speed description - Update 03-run-time.md

- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/runtime/internal/dom.ts
- test/custom-elements/samples/extended-builtin/_config.js
- test/custom-elements/samples/extended-builtin/fancy-button.js
- test/custom-elements/samples/extended-builtin/main.svelte
- test/custom-elements/samples/extended-builtin/test.js
fixes #3182. This is an alternative to #3184
> support is attribute, with a warning.

- src/runtime/internal/await_block.ts
- src/runtime/internal/lifecycle.ts
- test/runtime/samples/context-in-await/Child.svelte
- test/runtime/samples/context-in-await/_config.js
- test/runtime/samples/context-in-await/main.svelte
fixes #2443 with the patch @Conduitry proposed, with a minor tweak (resetting the current component to `null` immediately afterwards)
> set context in await blocks

- site/content/tutorial/04-logic/05-keyed-each-blocks/text.md
The name of the prop is current, not value. With value, fails
> Fix small typo in tutorial

- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/deconflict-builtins/expected.js
- test/js/samples/each-block-array-literal/expected.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/each-block-keyed-animated/expected.js
- test/js/samples/each-block-keyed/expected.js
While looking at the generated code of `each` blocks, I noticed that there were some wild inconsistencies:
* some blocks had proper braces and indentations, others didn’t
* some loops used `var`, others used `let`
* some loops were missing either, which was super confusing
To clean this up, I:
* changed all (expect one) case to use braces and indentations
* changed all loops to use `let`
* I added a comment explaining whats going on for the one case where a loop was relying on a *previous* value.
> Make generated `each` code more consistent

- src/compiler/compile/Component.ts
- src/compiler/compile/utils/checkGraphForCycles.ts
- test/runtime/samples/reactive-values-non-cyclical-declaration-order-independent/_config.js
- test/runtime/samples/reactive-values-non-cyclical-declaration-order-independent/main.svelte
- test/validator/samples/reactive-declaration-cyclical/errors.json
- fixes #3459
- uses DFS traversal to inspect reactive declarations for cycles
- returns the cycle detected (e.g.; `a → b → a`) for error messaging
> fix reactive declaration cycle detection + clearer error on cycle

- site/content/docs/02-template-syntax.md
Adds a note that `{@html}` directives cannot be used to surround markup with additional tags.
Also corrected the grammar in the descriptive text to remove dangling fragment.
See issue: #3456
@pngwn, is this what you had in mind?
I was going to include an example of what not to do, but then I thought people wouldn't read the description and just copy the wrong way into their code.
> site: docs: {@html} clarifications

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/runtime/internal/dom.ts
- test/runtime/samples/svg-spread/_config.js
- test/runtime/samples/svg-spread/main.svelte
fixes #3522. Not sure why it took so long for this solution to occur to me (apologies if anyone had already suggested it) — all we need to do is guarantee that SVG spread attributes are only ever set with `setAttribute`, and we're good.
The test here is harmless, but also useless — JSDOM doesn't error when you try to set readonly properties, and I can't be bothered to raise an issue.
> only use setAttribute with SVG spread props

- src/compiler/compile/render_dom/Block.ts
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
- test/runtime/samples/store-each-binding-destructuring/_config.js
- test/runtime/samples/store-each-binding-destructuring/main.svelte
- test/runtime/samples/store-each-binding/_config.js
- test/runtime/samples/store-each-binding/main.svelte
Fixes #3455. Preserves some additional info from the each block binding in order to generate a store mutation instead of a normal assignment expression.
> Fix store bindings in each blocks

- src/compiler/compile/Component.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/utils/invalidate.ts
- src/runtime/internal/Component.ts
- src/runtime/internal/utils.ts
- test/js/samples/action-custom-event-handler/expected.js
- test/js/samples/dynamic-import/expected.js
- test/js/samples/event-handler-no-passive/expected.js
- test/js/samples/instrumentation-template-if-no-block/expected.js
- test/js/samples/instrumentation-template-x-equals-x/expected.js
- test/runtime/samples/invalidation-in-if-condition/_config.js
- test/runtime/samples/invalidation-in-if-condition/main.svelte
- test/runtime/samples/store-resubscribe/_config.js
fixes #3512. This is an alternative to #3532 — it's definitely not as elegant, as PRs go, but it means we can eliminate a decent chunk of code, and should handle some funky edge cases around destructuring assignments.
Still a bit of tidying up to do — it should be possible to remove some more lines of code, as there's currently some duplication between `Expression.ts` and `render_dom/index.ts`.
> inline $$invalidate calls

- test/hydration/samples/dynamic-text-nil/_after.html
- test/hydration/samples/dynamic-text-nil/_before.html
- test/hydration/samples/dynamic-text-nil/_config.js
- test/hydration/samples/dynamic-text-nil/main.svelte
This is only a failing test for inconsistent server vs client side behavior for `null` children. For `undefined` both server and client stringify them but for `null` only the server stringifies them. The client removes children if it encounters `null`.
Would like to fix those but I would need to know who's at fault here: client, server or user and where a good starting point for fixing this would be.
> Add failing test for null hydration

- site/content/examples/10-animations/00-animate/App.svelte
A fix for #3541 
This replaced `add(this)` with `add(event.target)` to bring it in line with the [corresponding tutorial](https://svelte.dev/tutorial/animate).
> Fix animate example

- CHANGELOG.md
- src/compiler/compile/css/Selector.ts
- test/css/samples/weird-selectors/expected.css
- test/css/samples/weird-selectors/input.svelte
Fixes #1710. Using regular expressions when matching selectors to elements was causing a number of problems, which are discussed in the issue.
> rework attribute selector matching to not use regexes

- site/src/template.html
This adds a fullscreen banner that will activate tomorrow (20 Sep) to encourage people to take part in the [Digital Climate Strike](https://digital.globalclimatestrike.net/). The idea is to show solidarity with people striking IRL, and to encourage people — if they can — to do something other than be on a computer, since computers are a major factor in our impending doom (fun fact: data centres have a worse carbon footprint than the airline industry).
Of course, people can hide the banner iframe with devtools if they really need to access https://svelte.dev. But I think this is a movement worth supporting, however symbolically, and one that's aligned with Svelte's 'spend less time writing code and let browsers spend less time running code' goals.
> add digital climate strike banner

- site/content/docs/03-run-time.md
Fix an incorrect reference under the "draw" section of the API docs that self-references that section as scale.
Closes https://github.com/sveltejs/svelte/issues/3602.
> Fix minor error in API docs of draw

- src/compiler/compile/Component.ts
- test/runtime/samples/reactive-compound-operator/_config.js
- test/runtime/samples/reactive-compound-operator/main.svelte
- test/runtime/samples/reactive-update-expression/_config.js
- test/runtime/samples/reactive-update-expression/main.svelte
Adds 2 sets of tests, one for the compound assignment operators (x += y) that did not actually work yet, and one for the update expressions (x--, y++) which already worked but did not have specific tests.
I haven't figured out yet why the update expressions just work, but the test will at least ensure they won't randomly break anymore.
One thing I wasn't exactly sure about is if the way I'm detecting a compound assignment operator is the best way to do it. This should work because I basically took all the operators in the `AssignmentOperator` type except actual assignment and put them in a list. But if ever another operator is added this will have to be added in that list as well which is not optimal.
> Fix #3634 compound operators in reactive statement

- src/runtime/internal/lifecycle.ts
I read the [tutorial](https://svelte.dev/tutorial/component-events) and it says 
```
createEventDispatcher must be called when the component is first instantiated, — you can't do it later inside e.g. a setTimeout callback.
```
however it does not show error if i use it in a `setTimeout` callback. 
I only see an obscure error `Uncaught TypeError: Cannot read property '$$' of undefined` later on when I tried to dispatch an event.
Should I make this a compile time warning? or a runtime error?
> should throw error if createEventDispatch is used after instantiation

- src/runtime/internal/await_block.ts
- test/runtime/samples/await-set-simultaneous-reactive/_config.js
- test/runtime/samples/await-set-simultaneous-reactive/main.svelte
- test/runtime/samples/await-set-simultaneous-reactive/promise.js
Fix #3660
Added a test that would fail otherwise (test/runtime/samples/await-set-simultaneous-reactive/)
When flushing changes after promise, the newly attached block is not updated.
This is more obvious, when the newly attached block props takes value from a reactive declared variables, because their value only changed right before patching the dom
> fix reactive updates not reflected when handle promise

- site/content/tutorial/07-lifecycle/03-update/app-a/App.svelte
- site/content/tutorial/07-lifecycle/03-update/app-b/App.svelte
Hi,
I fixed the lifecycle update example overflow problem.
Before:
After:
URL: https://svelte.dev/tutorial/update
> Fix: lifecycle update example overflow problem

- src/runtime/internal/Component.ts
Fix HTMLElement class extending problem for iOS 8 and 9, described in this issue: #3608 
`class extends HTMLElement` fails on iOS 8 and 9, because the type of HTMLElement is object rather than function on these OS versions. The now existing `if (typeof HTMLElement !== 'undefined')` guard won't work in this case.
> Change HTMLElement type check

- src/runtime/animate/index.ts
In animate/index.ts was a open TODO which is solved with this PR.
To no create a breaking change, the AnimationConfig extends the TransitionConfig to keep the naming. Now it would also possible that the AnimationConfig could have more props that the TransitionConfig.
Also resolved an implicit any in this file :)
> Resolve TODO in animate

- CHANGELOG.md
- src/runtime/internal/dom.ts
- test/runtime/samples/spread-element-readonly/_config.js
- test/runtime/samples/spread-element-readonly/main.svelte
- test/server-side-rendering/samples/spread-attributes/_expected.html
- test/server-side-rendering/samples/spread-attributes/main.svelte
Fixes #3681.
When spreading props we were previously doing a `key in obj` check when deciding to assign to the property or set the attribute. This fails when the property exists but the setter is `undefined` which is the case with some (all?) read-only properties.
This PR changes that behaviour and instead uses `Object.getOwnPropertyDescriptor(el.__proto__, key)` and, if it exists, checks that the `set` property exists as well. It is important to provide two checks, one for the descriptors (or the key itself) and one for the actual `set` property of the descriptor, to prevent throwing errors when trying to access `set` of undefined.
I also needed to add `//@ts-ignore` when accessing `node.__proto__` since [the TS people don't think valid properties should be on the node interface if they …
> Prevent element property set from throwing errors for readonly properties.

- site/content/tutorial/06-bindings/11-dimensions/app-a/App.svelte
- site/content/tutorial/06-bindings/11-dimensions/app-b/App.svelte
Hi,
I fixed the dimensions example overflow problem.
Before:
After:
URL: https://svelte.dev/tutorial/dimensions
> Fix: dimensions example overflow problem

- site/content/blog/2019-04-15-setting-up-your-editor.md
- site/src/routes/blog/_posts.js
- site/src/routes/docs/_sections.js
- site/src/routes/tutorial/[slug]/index.json.js
- site/src/utils/highlight.js
It'd been bugging me for a while that unknown (or even missing) code block languages in markdown would crash the site. And then yesterday I merged a change which included one. So, here we go, finally addressing that.
This extracts some shared highlighting code into a common utility, and also makes it not die if the code block doesn't have a known language or doesn't have one at all.
> Site: Handle unknown syntax highlighting languages

- src/compiler/compile/nodes/shared/Expression.ts
- test/runtime/samples/globals-shadowed-by-each-binding/_config.js
- test/runtime/samples/globals-shadowed-by-each-binding/main.svelte
Fix #3674
If using globals, check for template_scope for bindings as well.
> globals shadowed by scope

- src/runtime/store/index.ts
The derived store callback type currently has an optional `set` argument, but it should be marked as a regular required argument:
```ts
fn: (values: StoresValues<S>, set?: Subscriber<T>) => T | Unsubscriber | void,
```
So `set?:` is changed to `set:`.
- a non-null `set` is already always provided as the second argument: https://github.com/sveltejs/svelte/blob/565931dff957545bf1b8a9ea57cfc097ed1a7e83/src/runtime/store/index.ts#L142 https://github.com/sveltejs/svelte/blob/565931dff957545bf1b8a9ea57cfc097ed1a7e83/src/runtime/store/index.ts#L154
- the change fixes type errors for consumers that have strict null checks enabled
- this change breaks nothing, and causes no errors when callers provide a function that omits the `set` argument, in the same way you can pass `Array.map` a function …
> fix type of derived store callback function

- src/runtime/internal/dom.ts
Before setting an attribute it checks if the value is different.
If you look at the network log in the developer console you will notice that if you render SSR, then hydrate, it will reset the `src` attribute, and then re-download the image.
Usually the image is cached so the time to load it is very fast. However it still flickers when doing this.
---
I think the merits of this approach should be debated but it's useful in my project and the tests still pass.
---
I'm not sure how to check for image re-downloads in the tests. Sorry!
> Prevent image flicker and reloading by checking attribute before setting it

- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- test/js/samples/inline-style-unoptimized/expected.js
Follow-up to #3579. Not certain off the top of my head why there's special logic for `<select value>` attributes, so have left that untouched for now.
> don't cache attribute values

- test/runtime/index.js
Currently, the compiled output did not shown when the error message asserts failed.
> [unit-test] show generated output if the error message does not match

- src/compiler/parse/state/tag.ts
feels like this should have been `slug` instead of `name.slice(7)`, consistent with the following else case
> [parser] reuse slug for parser error

- test/runtime/samples/each-block-keyed-iife/_config.js
- test/runtime/samples/each-block-keyed-iife/main.svelte
This adds a regression test for #3436, which was fixed by #3539.
> add each-block-keyed-iife test against regression

- site/src/server.js
Arrived in https://github.com/sveltejs/svelte/commit/84b0e865830a2f4cc943975c2683342ea651069f 
This mounted the `authenticate` function itself, which itself isn't a middleware.
> fix(site): invoke `authenticate` factory

- src/compiler/compile/Component.ts
- src/compiler/compile/render_dom/index.ts
- test/runtime/samples/store-resubscribe-export/_config.js
- test/runtime/samples/store-resubscribe-export/main.svelte
Fixes #3662
If subscribing props, make sure to unsubscribe if the prop changed.
> resubscribe props if reassigned

- src/compiler/parse/state/mustache.ts
- test/parser/samples/await-catch/input.svelte
- test/parser/samples/await-catch/output.json
- test/parser/samples/error-catch-without-await/error.json
- test/parser/samples/error-catch-without-await/input.svelte
- test/parser/samples/error-then-without-await/error.json
- test/parser/samples/error-then-without-await/input.svelte
fix:
- `{:then}` block and `{:catch}` block can be used without `{#await}` ([repl for the bug](https://svelte.dev/repl/319a171f525d4d65a4eb378f4ad7e655?version=3.12.1))
- allow `{:catch}` block be used without `{:then}` block.
- i guess theres use case for showing error only when promise resolve, like input validation?
> then and catch block expect await, optional then block

- CHANGELOG.md
- src/compiler/compile/Component.ts
- test/runtime/samples/binding-this-store/_config.js
- test/runtime/samples/binding-this-store/main.svelte
Fixes #3591, using the change I mentioned in that issue. The change isn't specifically related to `bind:this` at all, but when I took a sweep through instances of `.invalidate` in the code, it looks like `bind:this` is probably the only thing this was affecting for now.
> fix `bind:this` binding to a store

- src/compiler/compile/render_dom/index.ts
- test/runtime/samples/store-imported/_config.js
Fixes #3735. It was just a slight `code-red` misuse typo.
> Fix store validation code generation

- src/compiler/compile/Component.ts
I don't really know what sort of test to write for this besides a js sample one, and I'm not really sure what I'd say in the changelog, but this should fix #3607.
> hoist globals even if they are mentioned in a script block

- src/compiler/compile/nodes/shared/Expression.ts
I don't feel completely confident that this is safe, but it would certainly resolve #3708. I don't _see_ any reason why we need to be checking for this here, and removing this doesn't break any tests.
> don't consult known globals when walking Expression nodes

- src/compiler/compile/render_dom/Block.ts
- test/js/samples/debug-no-dependencies/expected.js
- test/js/samples/deconflict-builtins/expected.js
- test/js/samples/each-block-array-literal/expected.js
- test/js/samples/each-block-keyed-animated/expected.js
- test/js/samples/each-block-keyed/expected.js
- test/runtime/samples/deconflict-builtins-2/_config.js
- test/runtime/samples/deconflict-builtins-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/3724
> deconflict with builtins

- site/content/docs/03-run-time.md
This aims to improve the documentation on server-side rendering.
As discussed in #3008, the API docs on server-side rendering are a bit confusing since they don't include the use of `svelte/register`.
Fixes #3008.
> Fix #3008: Better SSR docs

- CHANGELOG.md
- src/compiler/compile/nodes/Attribute.ts
- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_ssr/handlers/Element.ts
- src/runtime/internal/dom.ts
- src/runtime/internal/ssr.ts
- test/runtime/samples/attribute-boolean-case-insensitive/_config.js
- test/runtime/samples/attribute-boolean-case-insensitive/main.svelte
- test/runtime/samples/attribute-boolean-with-spread/_config.js
- test/runtime/samples/attribute-boolean-with-spread/main.svelte
- test/runtime/samples/spread-element-removal/_config.js
- test/runtime/samples/spread-element-removal/main.svelte
Fixes #3764, with the assumption that #3750 may mean that it would become even more impractical to ship attribute-to-property tables along with the runtime.
In short:
- For each boolean attribute (more precisely, for each attribute with `attribute_lookup` metadata) given for a node that has at least one spread, the compiler will emit the appropriate property key in the object in the spread arrays. For example, `{ readOnly: whatever }` instead of `{ readonly: whatever }`.
- In SSR mode, the corresponding object in the spread array now contains `{ readonly: whatever || null }` instead of `{readonly: whatever }` for boolean attributes, to ensure that the `spread()` function does not serialize falsy attributes.
Bonus SSR bugs I bumped into and fixed while addressing this:
- `{...{ foo: null …
> Fix boolean attributes in presence of spread attributes

- src/runtime/store/index.ts
This improves the types of derived stores by using overloads in order to achieve this kind of type-checking for users:
> Improve derived store typing for users

- site/content/docs/03-run-time.md
Small documentation fix since the anchor link was broken
> Fixed anchor link in documentation

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/spread-element-class/_config.js
- test/runtime/samples/spread-element-class/main.svelte
Fixes #3421. This works by updating `ElementWrapper#add_classes()` to put unconditional `toggle_class()` calls into the update block when this element has spread attributes. We can't tell at compile time whether these could have been clobbered by `set_attributes()`, so we always need to include them.
> Don't lose `class:` directive classes on an element with `{...spread}` attributes when updating

- test/runtime/samples/class-with-spread-and-bind/_config.js
- test/runtime/samples/class-with-spread-and-bind/main.svelte
This PR introduces a failing test for the issue described in #2707. It's not mergeable in its current state since the tests are by definition failing, but I'm hoping this will be a starting point for me (or somebody else) to pick up and fix the issue.
> Add failing test for missing class on elem with bind and spread

- src/compiler/compile/Component.ts
- test/validator/samples/missing-custom-element-compile-options/input.svelte
- test/validator/samples/missing-custom-element-compile-options/warnings.json
currently using `<svelte:options tag="foo-bar" />` without `compileOptions.customElement = true` is a noop.
Warn to remind about missing `customElement` flag.
> warn if using svelte:options tag without compile_options.customElement

- CHANGELOG.md
- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_ssr/handlers/Element.ts
- src/runtime/internal/ssr.ts
- test/runtime/samples/spread-element-class/main.svelte
- test/runtime/samples/spread-element-scope/_config.js
- test/runtime/samples/spread-element-scope/main.svelte
Fixed #3790 (which also fixes #2721 in a better way than I mentioned on that ticket).
In DOM mode for elements that need the scoping class and have spread attributes, this adds `toggle_class(node, "svelte-xyz", true);` calls to the hydrate and update blocks, rather than trying to add or update a `class=` attribute in the element's AST. This prevents the scoping class and the spread class from clobbering one another.
In SSR mode for elements that need the scoping class and/or have `class:` directives and have spread attributes, this combines the scoping class and/or the `class:` directives into a string of classes that need to be added to the element after all of the spreading. This string is passed as a new second argument to `spread()`, which uses it to update or set the `class` …
> Fix handling of style scoping and `class:` with spread scopes

- CHANGELOG.md
- src/compiler/compile/render_ssr/handlers/Element.ts
- src/compiler/compile/render_ssr/handlers/shared/boolean_attributes.ts
- src/runtime/internal/ssr.ts
- test/server-side-rendering/samples/attribute-boolean/_expected.html
- test/server-side-rendering/samples/attribute-boolean/main.svelte
- test/server-side-rendering/samples/spread-attributes-boolean/_expected.html
- test/server-side-rendering/samples/spread-attributes-boolean/main.svelte
Fixes #2916. This introduces a runtime dependency on the list of boolean attributes for SSR code, which seems unavoidable if we want to do this approximately correctly.
As a bonus, it also fixes some problems with the list of boolean attributes, and brings it more in line with the DOM changes from some months ago.
> Fix SSR spread with boolean attributes

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/MustacheTag.ts
- src/compiler/compile/render_dom/wrappers/shared/Tag.ts
- test/js/samples/hoisted-const/expected.js
- test/js/samples/hoisted-let/expected.js
- test/js/samples/non-mutable-reference/expected.js
- test/js/samples/unchanged-expression/expected.js
- test/js/samples/unchanged-expression/input.svelte
- test/runtime/index.js
- test/runtime/samples/lifecycle-render-order-for-children/_config.js
if the mustache tag expression do not change, can use `innerHtml`.
For a [this hello world example](https://svelte.dev/repl/420902799e8d479b9635b1e0df1b8d55?version=3.12.1), saved 361 bytes without minified:
- without this PR (1650 bytes)
- with this PR (1289 bytes)
> feat: allow innerHtml if no dynamic dependencies

- site/content/examples/15-composition/04-modal/Modal.svelte
This is a basic accessibility requirement for key access
* Escape key closes the modal
* Tab key does not cycle round focusable elements in background
* Close key gets focus
I'm fast 'n' playing loose with the check list as its an update to one of the examples
> Add Key handling to modal example

- src/compiler/utils/names.ts
Add `Event` to the list of globals.
When trying to create `new Event()`, the compiler complains that `Event is not defined`.
Relates to #3805 
-  [x] Run the tests tests with `npm test` or `yarn test`
There are at least more events that could be added and possibly even more things, but I figured I'd start with this one at least.
> Add Event to globals list

- site/content/docs/03-run-time.md
- src/runtime/motion/spring.ts
- src/runtime/motion/tweened.ts
- test/motion/index.js
> allow spring/tweened values to be initially undefined

- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/compiler/compile/render_dom/wrappers/RawMustacheTag.ts
- src/compiler/compile/render_dom/wrappers/Slot.ts
- src/compiler/compile/render_dom/wrappers/shared/Tag.ts
- src/compiler/compile/render_dom/wrappers/shared/Wrapper.ts
- test/js/samples/hoisted-const/expected.js
- test/js/samples/hoisted-let/expected.js
- test/js/samples/non-mutable-reference/expected.js
- test/js/samples/unchanged-expression/expected.js
- test/runtime/samples/unchanged-expression-xss/_config.js
- test/runtime/samples/unchanged-expression-xss/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/3813
Added a new concept here, `is_static_content` besides the `can_use_innerhtml`
to differentiate cases where we can use `innerHtml`:
- no mustache tags
- logic blocks, `if`, `each`, etc
and cases where the content is static:
- no dynamic dependencies
- only mount, will not need to handle changes.
> use textContent instead of innerHtml, preventing XSS

- test/hydration/index.js
- test/preprocess/index.js
- test/runtime/index.js
- test/server-side-rendering/index.js
some test suites rely on test samples folder name to end with `.solo` for run only the test, but some rely on `config.solo`.
This change make sure that `.solo` in the test sample folder name is always respected.
> look for test folder name for solo mode as well

- package-lock.json
- package.json
- src/compiler/parse/read/style.ts
- test/css/samples/empty-value/expected.css
- test/css/samples/empty-value/input.svelte
Fix #3801 
If the value is empty, will cause compile error down the road.
Remove it upfront, will be able to treat it as empty rule, if there's no other declaration for the rule.
> remove empty value declaration from style tree

- test/runtime/index.js
- test/server-side-rendering/index.js
while fixing bugs, found out that for `runtime` and `server-side-rendering` test suite, the `expected` and `actual` for errors are swapped out.
> swapped out expected and actual for asserts in error

- test/helpers.js
- test/runtime/samples/binding-select-in-each-block/_config.js
- test/runtime/samples/binding-select-in-each-block/main.svelte
- test/runtime/samples/binding-select-multiple/_config.js
- test/runtime/samples/binding-select-optgroup/_config.js
- test/runtime/samples/window-bind-scroll-update/_config.js
- test/runtime/samples/window-binding-resize/_config.js
- test/runtime/samples/window-binding-scroll-store/_config.js
- test/runtime/samples/window-event/_config.js
- test/runtime/samples/window-event/main.svelte
While working on #3835, i realised there's quite some test skipped due to JSDOM 11, but we are using JSDOM 15 now. So I tried to reenable these tests.
Note:
- Patched `window.scrollTo` for window scrolling test cases
- Added a simple implementation of mock timer, as scrolling uses timeout to flush the scroll position.
> reenable skipped test due to jsdom

- src/compiler/compile/render_dom/Block.ts
Fixes #3854. Writing a test for this seems fiddly, since the bug is only present in dev mode, so I'm going to just hope this reappear, which does seem unlikely.
> deconflict `block` var used in dev mode

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/utils/stringify.ts
- test/runtime/samples/attribute-static-quotemarks/_config.js
- test/runtime/samples/attribute-static-quotemarks/main.svelte
when using `innerHtml`, the quotemarks in the attribute are not escaped
> escape html quotes in `.innerHtml` statement

- src/compiler/compile/nodes/Element.ts
- test/js/samples/bindings-readonly-order/expected.js
- test/js/samples/bindings-readonly-order/input.svelte
Should fix #3828 
If type attribute is declared after the binding, evaluating `parent.get_static_attribute_value('type')` in `Binding` returns `null` because type hasn't been pushed to the attributes list. As a result, `type` is null and `type === 'file'` is false, which is used to determine whether it's readonly and to prevent assigning `input.files`.
Forcing all `Attribute`s and `Spread`s  to be evaluated before `Binding` can fix the issue, and I suppose it does not create any kind of side effect. Let me know if there's any problem may arise that I'm not aware of.
Really appreciate for your review!
> fix input binding fails if type declared last

- src/compiler/compile/render_dom/Block.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/runtime/internal/Component.ts
- src/runtime/internal/scheduler.ts
- test/js/samples/component-static-array/expected.js
- test/js/samples/component-static-immutable/expected.js
- test/js/samples/component-static-immutable2/expected.js
- test/js/samples/component-static-var/expected.js
- test/js/samples/component-static/expected.js
- test/js/samples/component-store-file-invalidate/expected.js
- test/js/samples/computed-collapsed-if/expected.js
- test/js/samples/deconflict-globals/expected.js
- test/js/samples/dynamic-import/expected.js
- test/js/samples/empty-dom/expected.js
- test/js/samples/empty-dom/input.svelte
- test/js/samples/non-imported-component/expected.js
- test/js/samples/reactive-values-non-topologically-ordered/expected.js
- test/js/samples/reactive-values-non-writable-dependencies/expected.js
- test/js/samples/setup-method/expected.js
- test/runtime/samples/empty-dom/_config.js
- test/runtime/samples/empty-dom/main.svelte
Fix https://github.com/sveltejs/svelte/issues/2200
> Dont create a fragment at all for DOM-less component

- src/compiler/compile/css/Selector.ts
- test/css/samples/unused-selector-string-concat/_config.js
- test/css/samples/unused-selector-string-concat/expected.css
- test/css/samples/unused-selector-string-concat/input.svelte
- test/css/samples/unused-selector-ternary-bailed/_config.js
- test/css/samples/unused-selector-ternary-bailed/expected.css
- test/css/samples/unused-selector-ternary-bailed/input.svelte
- test/css/samples/unused-selector-ternary-concat/_config.js
- test/css/samples/unused-selector-ternary-concat/expected.css
- test/css/samples/unused-selector-ternary-concat/input.svelte
- test/css/samples/unused-selector-ternary-nested/_config.js
- test/css/samples/unused-selector-ternary-nested/expected.css
- test/css/samples/unused-selector-ternary-nested/input.svelte
Fix https://github.com/sveltejs/svelte/issues/1698
> feat unused css selector that understands string concatenation

- src/runtime/transition/index.ts
Add easing param to fade transition, using linear as default to keep the previous behaviour.
> Add easing param to fade transition

- site/content/tutorial/06-bindings/12-bind-this/app-a/App.svelte
- site/content/tutorial/06-bindings/12-bind-this/app-b/App.svelte
**Minor fix for a broken path.**
In the tutorial in chapter 6-bindings section *this* the path for the logo mask was broken. So I guessed it was `svelte-logo-mask.svg` instead. 
I've changed both in the exercise and in the solution.
Not a big deal but I hope that it could be appreciated!
> fix: svelte-logo-mask correct file name

- src/compiler/compile/utils/get_name_from_filename.ts
Should fix a bug in #3846 whereby the `\` Windows path separator was being treated as a funky character
> encode parts of filename, not entire string

- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/css/samples/undefined-with-scope/expected.css
- test/css/samples/undefined-with-scope/expected.html
- test/css/samples/undefined-with-scope/input.svelte
Fixed https://github.com/sveltejs/svelte/issues/3067#issuecomment-515207718 where scoped css causes a string concatenation and ended up with `undefined` class name.
- I've combined the computation of `value` in both `(dependencies.length > 0)` if and else case, to make them consistent. for example, this bug was fixed in the `if (dependencies.length > 0)` case but not the `else` case. [see repl](https://svelte.dev/repl/48755756aa5d42b58d584cac73429262?version=3.12.1)
- I've tried to moved the `get_value(block)` of `src/compiler/compile/nodes/Attribute.ts` to `src/compiler/compile/render_dom/wrappers/Element/Attribute.ts`, but apparently is still being used by `InlineCompiler`, which would take a bigger change, and I don't want to touch it for now.
> fix undefined class with scoped-css

- site/content/examples/12-svg/05-svg-transitions/App.svelte
solves #2467
It was quite a simple fix. Decided to take a stab at it while going around the issues.
The new logotype uses a semi-bold `Overpass` font-weight while the old one used to use the light version by means of a `font-weight: 100`.
> ✏️ outdated logotype on svg-transition example

- site/content/blog/2019-04-15-setting-up-your-editor.md
Issue #3889
Added instructions on how to associate `.svelte` files with HTML in VSCode, WebStorm and Sublime Text 3.
Also made some small tweaks like separating "Coming soon" to the other line and highlighting it.
> Site: add editor file association instructions

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/binding-input-range-change-with-max/_config.js
- test/runtime/samples/binding-input-range-change-with-max/main.svelte
Should fix #3857 
This bug is caused by html input range where setting `value` outside the `min` and `max` will fallback to the nearest valid value. In this case, it will be the `max`.
In `ElementWrapper`, adding bindings happened before adding attributes, which means `value` is updated before `max` when updating at the same cycle. I think the issue can be solved by reordering adding attributes to be first.
However, I can't seem to reproduce the input range behaviour in test. I think there's something missing in input range validation in jsdom, so I put a note there. I hope it's okay.
Really appreciate for your review!
> fix range input if max is changed at same time as value

- src/runtime/internal/lifecycle.ts
fixes #3877. we should probably fix up all the other lifecycle types, but this is the only one that's unforgiving (since there's an optional argument)
> add type info for createEventDispatcher

- site/content/docs/04-compile-time.md
- src/compiler/compile/Component.ts
- src/compiler/compile/index.ts
- src/compiler/interfaces.ts
- src/runtime/internal/dev.ts
- test/js/samples/loop-protect/_config.js
- test/js/samples/loop-protect/expected.js
- test/runtime/samples/loop-protect/_config.js
Fix https://github.com/sveltejs/svelte/pull/3887
- Added `loopGuardTimeout` compile options
- Updated API docs
> add loopGuardTimeout options

- src/compiler/compile/render_dom/wrappers/Element/index.ts
User `let` instead `var` for loop index to prevent naming collisions with top-level scope.
To reproduce: https://svelte.dev/repl/33152732e43049cfaf171bc6f10fd88f?version=3.13.0
> Use `let` instead of `var` for loop index

- src/compiler/compile/render_dom/index.ts
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
Fixes #3914. We can't use `.includes` or `.startsWith`, because those need to be polyfilled on IE.
> Use IE-compatible js to check for unknown prop warnings

- src/compiler/preprocess/index.ts
- test/preprocess/samples/comments/_config.js
- test/preprocess/samples/comments/input.svelte
- test/preprocess/samples/comments/output.svelte
Fix https://github.com/sveltejs/svelte/issues/3047#issuecomment-552340079
need to skip html comments when `regexp`ing `<script>` and `<style>` tag.
> skip comments for preprocessors

- CONTRIBUTING.md
- test/css/index.js
- test/helpers.js
- test/hydration/index.js
- test/js/index.js
- test/parser/index.js
- test/server-side-rendering/index.js
- while switching between branches, the test runner will run test that was created in the other branch. that's because `_actual.*` file is git ignored, and therefore still preserves the folder when switching branches.
- if `input.svelte` does not exists, skip the test.
- when changing `render_*` code, may break more than 1 test. it's cumbersome to update them one by one after reviewing the changes.
- Provide a `--update` flag for test to update the `expected.*` file automatically.
> improve testing experience

- src/compiler/compile/nodes/Binding.ts
- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/js/samples/media-bindings/expected.js
- test/js/samples/media-bindings/input.svelte
This adds read-only bindings for [`seeking`](https://html.spec.whatwg.org/multipage/media.html#dom-media-seeking) and [`ended`](https://html.spec.whatwg.org/multipage/media.html#dom-media-ended) to `<audio>` and `<video>` elements.
These can be used to build a custom video UI, similar to [the media elements example](https://svelte.dev/examples#media-elements). For example:
* The `ended` property can be used to show a replay button instead of a regular play/pause button:
```svelte
<button on:click={() => paused = !paused}>
{#if ended}
Replay
{:else if paused}
Play
{:else}
Pause
{/if}
</button>
```
* The `seeking` property can be used to show a loading spinner while the media element is seeking.
---
I also noticed that the current compiler would generate code for `bind:volume` like this: …
> Add more bindings for media element properties

- src/runtime/animate/index.ts
- divide the getBoundingClientRect dimensions by clientHeight or clientWidth
- this gives us the element's scaled values as scaleX and scaleY
- divide the "dx" and "dy" by the "scaleX" and "scaleY"
This aims to fix #3555 by using the node's un-scaled width/height to
calculate the amount it has been scaled. Then dividing the distance by
this scale factor removes the janky start position which was shown in
the test case. 
- [repl before fix](https://svelte.dev/repl/765bdee52e9d4537bbe78f3f7835d154?version=3.12.1)
- [repl after fix](https://svelte.dev/repl/67052a761c214c1a8247f4521ddfaa06?version=3.12.1)
resolves #3555
> Fix #3555 ; scale elements in FLIP animations

- src/compiler/compile/nodes/EventHandler.ts
- test/runtime/samples/event-handler-dynamic-expression/_config.js
- test/runtime/samples/event-handler-dynamic-expression/main.svelte
https://github.com/sveltejs/svelte/pull/3836 fixed the case if the event handler is an Identifier expression.
but it doesn't work for cases like
```html
<button on:click={foo ? bar : baz} />
```
This PR will fix this.
> fix dynamic event handler expression

- CHANGELOG.md
- src/runtime/internal/dom.ts
- test/runtime/samples/binding-width-height-a11y/_config.js
- test/runtime/samples/binding-width-height-a11y/main.svelte
Adds `aria-hidden="true"` to objects generated by `add_resize_listener. This removes them from the accessibility API completely, ensuring that these objects will not interfere with assistive software.
Is this the only place we are creating objects in this manner? Are there any other compiler-generated elements that exist for functional rather than structural purposes?
I assume we're still doing the chanelog thing so I threw one in there.
Fixes #3948.
> Add `aria-hidden=true` to resize-listeners

- site/content/examples/13-actions/01-adding-parameters-to-actions/App.svelte
- site/content/examples/13-actions/01-adding-parameters-to-actions/longpress.js
- site/content/tutorial/12-actions/02-adding-parameters-to-actions/app-a/App.svelte
- site/content/tutorial/12-actions/02-adding-parameters-to-actions/app-a/longpress.js
- site/content/tutorial/12-actions/02-adding-parameters-to-actions/app-b/App.svelte
- site/content/tutorial/12-actions/02-adding-parameters-to-actions/app-b/longpress.js
- site/content/tutorial/12-actions/02-adding-parameters-to-actions/text.md
Fixed the problem when user hold the button less than duration time but `longpress` event will fire anyway.
> fix 'action with param' example and tutorial

- site/package-lock.json
- site/package.json
Closes #3968
Needed a PR because we install from package-lock file.
Also bumped to `sirv@next` because
A) we were using two different `@polka/url` versions
B) upcoming `sirv` has some of its own fixes
> chore(site): bump polka deps

- src/compiler/compile/Component.ts
- test/runtime/samples/module-context-export/Foo.svelte
- test/runtime/samples/module-context-export/_config.js
- test/runtime/samples/module-context-export/main.svelte
sorry, my bad for causing this regression bug.
Fix https://github.com/sveltejs/svelte/issues/3983
unknowingly, `module_js` and `instance_js` uses the same `var_lookup`. and `instance_js` var will overwrite `module_js` after traversing it's ast.
previously it works because, the module_js ast is traversed and extract exports. before traversing instance ast (which overwrites the module_js's vars)
> fix context export not working if conflicts with instance variable

- src/compiler/compile/nodes/Binding.ts
- test/runtime/samples/bindings-global-dependency/_config.js
- test/runtime/samples/bindings-global-dependency/main.svelte
Fix https://github.com/sveltejs/svelte/issues/3992
Since @Conduitry changes in https://github.com/sveltejs/svelte/pull/3746/files, we don't skip marking known global as dependencies. Meaning, known globals could be a dependency.
In Binding, we mark dependency variable as mutated, and because it was never defined within the component, we get setting 'mutated' of undefined error
In this change, we skip over setting 'mutated' for variable that we cannot find.
> fix handle marking global variable as dependency

- test/runtime/samples/each-block-after-let/Child.svelte
- test/runtime/samples/each-block-after-let/_config.js
- test/runtime/samples/each-block-after-let/main.svelte
Resolves #3966 by adding a regression test. The bug itself was fixed already, presumably as part of the bitmask/context changes.
> add regression test against #3966

- src/compiler/compile/render_dom/wrappers/Element/EventHandler.ts
Somehow the order of the `stopPropagation` and `preventDefault` arguments to the `listen_dev` function got reversed.
> Fix listen_dev argument order

- .eslintrc.js
- src/runtime/internal/loop.ts
- test/runtime/index.js
`requestAnimationFrame`'s argument is better suited to time animations since browsers can account for the frame's actual rendering time.
There's been a lot of movement in browsers so I haven't kept up with which one's _do_ pass in the time the frame's going to be rendered or not, but the worst they could do is just pass the current time, which would be the same behavior as the current one.
> Use raf's time for smoother transitions

- site/content/tutorial/02-reactivity/02-reactive-declarations/text.md
This change re-words some of the prose so that the label syntax is spoken of in _unfamiliar_ terms rather than _alien_ as it is valid syntax and not some svelte-specific feature/functionality. IMO this clarifies what `$:` is with a little note for those that are curious, given that labels are rarely used in the JavaScript ecosystem.
> Document $: in the tutorial

- CONTRIBUTING.md
Changed
"The [Open Source Guides](https://opensource.guide/) website has a collection of resources for individuals, communities, and companies who want to learn how to run and contribute to an open source project."
To
"The [Open Source Guides](https://opensource.guide/) website has a collection of resources for individuals, communities, and companies. These resources help people who want to learn how to run and contribute to open source projects."
First sentence contained two 'ands', so I split the sentence into two. 
Other changes are minor grammar fixes.
> Minor text fixes to CONTRIBUTING.md

- site/content/blog/2017-12-31-sapper-towards-the-ideal-web-app-framework.md
The link to the realworld app [changed](https://github.com/sveltejs/realworld/commit/c4f895c02f2ac583dc0cc4874f4def4414f71679) from [svelte-realworld.now.sh](https://svelte-realworld.now.sh/) to [realworld.svelte.dev](https://realworld.svelte.dev).
> site: fix link to realworld demo in blogpost

- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- test/runtime/samples/await-then-no-context/main.svelte
Fixes #4022. It seems the most correct to me to just not generate the `#child_ctx[${value_index}] = ${info}.resolved;` lines when we don't have a `then` variable.
> fix child context in await blocks with no `then` variable

- src/compiler/compile/Component.ts
- test/validator/samples/missing-component-global/input.svelte
- test/validator/samples/missing-component-global/warnings.json
Fixes #4070.
Currently `<String/>` compiles and results in a runtime error.
Do not check in globals for definitions of `InlineComponent` nodes in `warn_if_undefined`:
```javascript
if (globals.has(name) && node.type != 'InlineComponent') return;
```
> Skip JS globals for InlineComponent nodes in warn_if_undefined.

- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- test/runtime/samples/await-then-if/_config.js
- test/runtime/samples/await-then-if/main.svelte
Fix https://github.com/sveltejs/svelte/issues/4044
in `IfBlockBranch` will call `expression.manipulate(block)` in the `constructor`. which is called before adding the `value` and `error` into context dependencies.
> fix: if inside bind await block contextual dependencies

- site/src/routes/repl/[id]/index.svelte
Partially fix for https://github.com/sveltejs/svelte/issues/4045#issue-531999258
not sure what would be the alternative share image.
> REPL share title should use the repl title

- src/compiler/compile/render_dom/Renderer.ts
- test/runtime/samples/bitmask-overflow-2/_config.js
- test/runtime/samples/bitmask-overflow-2/main.svelte
Fix https://github.com/sveltejs/svelte/issues/4037
- bitmask array could be an empty array, because the dirty `names` are not in context.
- now return `dirty & 0` to match the current output.
- cached the `bitmask` array, the dirty `Expression#type` could have been accessed multiple times, causing the bitmask to be re-calculated more than once.
- but a better fix should be a better lazy creation through `getter` indirection
> fix: bitmask overflow better handle global

- src/compiler/compile/render_dom/Renderer.ts
- test/runtime/samples/bitmask-overflow-3/_config.js
- test/runtime/samples/bitmask-overflow-3/main.svelte
Fixes #4077. I had intended to just reopen #4084, but apparently if you force-push a branch while a PR is closed, you can't do that. This moves down the computation of `context_overflow` as discussed, and adds a test.
> fix bitmask overflow when using slotted components

- src/compiler/compile/Component.ts
- test/js/samples/component-store-access-invalidate/expected.js
- test/vars/samples/store-referenced/_config.js
> compiler: tag auto-subscribe stores as referenced in vars

- README.md
Currently Travis CI is not used, so I replaced it with the Github Actions badge.
> docs: correct build status badge

- site/src/routes/index.svelte
With 691211aeba94c2cefaebc059c432a6ca20b51192, it isn't possible anymore to copy paste the npx degit link:
> docs: selectable npx degit link

- src/runtime/internal/scheduler.ts
- test/runtime/samples/store-invalidation-while-update-1/_config.js
- test/runtime/samples/store-invalidation-while-update-1/main.svelte
- test/runtime/samples/store-invalidation-while-update-2/_config.js
- test/runtime/samples/store-invalidation-while-update-2/main.svelte
Fix https://github.com/sveltejs/svelte/issues/4098
the dirty bitmask passed into the `p` function will be a snapshot of the dirty accumulated so far.
reset the dirty bitmask before running `p` function, any `$$invalidate` call within the `p` function will schedule another update function.
> fix invalidate while update

- site/src/routes/examples/_TableOfContents.svelte
This PR adds a link to the REPL from the examples page to the left of the arrow in the list. I couldn't find anything in the issues list, I might have missed it though.
This is how it looks:
> adds link to REPL from example page.

- test/validator/index.js
- test/validator/samples/tag-custom-element-options-missing/input.svelte
- test/validator/samples/tag-custom-element-options-missing/warnings.json
- test/validator/samples/tag-custom-element-options-true/_config.js
- test/validator/samples/tag-custom-element-options-true/input.svelte
This PR updates the validator test harness to allow config to control `customElement` .
This enables newly added test cases to exercise both code paths during component compile:
1. `<svelte:options tag='custom-element'>` is present and `customElement` is false (or missing).
2. `<svelte:options tag='custom-element'>` is present and `customElement` is true.
See this issue for more information: #4132.
> CI: tests: validator: add support for customElement compile option + test cases

- src/compiler/compile/render_dom/wrappers/shared/get_slot_definition.ts
- test/runtime/samples/component-slot-let-destructured-2/Nested.svelte
- test/runtime/samples/component-slot-let-destructured-2/_config.js
- test/runtime/samples/component-slot-let-destructured-2/main.svelte
Fix https://github.com/sveltejs/svelte/issues/2751
- in the `get_slot_changes` fn, the dirty bit is passed in, so destructuring it will cause bug.
- object destructuring is still okay, because it would be accessing property on `number`, but array destructuring will have error, because `number` is not iterable.
so, i changed the slot_change function from this:
```js
({ value: [a, b], data: foo }) => (a ? 64 : 0) | (b ? 128 : 0) | (foo ? 256 : 0)
```
into this:
```js
({ value: a_b$, data: foo }) => (a_b$ ? 64 : 0) | (a_b$ ? 128 : 0) | (foo ? 256 : 0)
```
> fix destructuring in slot let binding

- src/compiler/compile/render_dom/wrappers/Text.ts
- test/runtime/samples/svg-tspan-preserve-space/_config.js
- test/runtime/samples/svg-tspan-preserve-space/main.svelte
Fixes #3998 and adds a run-time test to make sure it stays fixed.
Note that I chose to nest the `if` statements because I have a feeling we'll need to fix other svg stuff in the future.
> compiler: text util: preserve space after svg <tspan> tags

- src/compiler/compile/nodes/EventHandler.ts
- test/runtime/samples/event-handler-dynamic-bound-var/Nested.svelte
- test/runtime/samples/event-handler-dynamic-bound-var/_config.js
- test/runtime/samples/event-handler-dynamic-bound-var/main.svelte
in `EventHandler` we are setting the `reassigned` in `constructor`, which may run first before other template components set the `reassigned` property for the dependencies variable.
- the `reassigned` should be evaluated during "render", after template traversal.
> fix dynamic event handler for bind variables

- src/compiler/compile/render_dom/wrappers/Element/EventHandler.ts
- test/js/samples/event-handler-dynamic/expected.js
- test/runtime/samples/event-handler-dynamic-hash/_config.js
- test/runtime/samples/event-handler-dynamic-hash/main.svelte
- test/runtime/samples/event-handler-dynamic-invalid/_config.js
- test/runtime/samples/event-handler-dynamic-invalid/main.svelte
- test/runtime/samples/event-handler-dynamic-modifier-once/_config.js
- test/runtime/samples/event-handler-dynamic-modifier-once/main.svelte
- test/runtime/samples/event-handler-dynamic-modifier-prevent-default/_config.js
- test/runtime/samples/event-handler-dynamic-modifier-prevent-default/main.svelte
- test/runtime/samples/event-handler-dynamic-modifier-self/_config.js
- test/runtime/samples/event-handler-dynamic-modifier-self/main.svelte
- test/runtime/samples/event-handler-dynamic-modifier-stop-propagation/_config.js
- test/runtime/samples/event-handler-dynamic-modifier-stop-propagation/main.svelte
- test/runtime/samples/event-handler-dynamic-multiple/_config.js
- test/runtime/samples/event-handler-dynamic-multiple/main.svelte
- test/runtime/samples/event-handler-dynamic/_config.js
Fixes #4087, #4090.
**Background**
Dynamic events are callbacks that reside in a variable instead of directly pointing to a function and are emitted by the compiler when the variable is mutated or assigned in some way.
I noticed in #4087 that the dynamic event handler test case was throwing exceptions, but still passing.
Further investigation uncovered an issue where we were not properly handling exceptions in the run-time during testing. This led to filing #4090 after the root cause of the exception turned out to the lack of callback validation inside the proxy function used for dynamic events.
This pull request addresses both of these issues along with adding much more coverage for dynamic events.
> compiler/tests: dynamic events: validate handler before executing

- site/src/routes/examples/_TableOfContents.svelte
This PR relates to Issue #4197. Prior to this change,  anchor tags in the exmaple's Table of Contents would shift or bounce when a link is hovered. This appeared to be caused by a component from @svelte/site-kit, Nav.svelte. Apon hovering, the anchor tags has its padding set to 0, causing all elements below to shift up by 1 pixel. 
All tests still pass and no other elements are effected by this change.
> fixed sidebar link bounce (Issue #4197)

- rollup.config.js
- src/runtime/internal/dev.ts
Includes the compiler version in all dev events. As the compiler internals change having the version number to test against should make things much simpler.
fixes #4047
> Pass compiler version in dev events

- site/content/blog/2019-04-15-setting-up-your-editor.md
Added instruction to use plugins instead of treating svelte as html since a language plugin is available now.
Plugin URL: https://plugins.jetbrains.com/plugin/12375-svelte/
> Updated instruction for jetbrains IDEs

- site/content/docs/02-template-syntax.md
fix #4172
The API documentation about `<slot>` contains the following example that does not work.
```
<Widget>
<p>this is some child content</p>
</Widget>
<div>
<slot>
this will be rendered if someone does <Widget/>
</slot>
</div>
```
This fix, as explained by @antony, makes the example more verbose but more clear.
> Doc (#4172): Fixing the unclear slot with fallback content example

- CHANGELOG.md
- src/compiler/compile/Component.ts
- test/runtime/samples/reactive-values-no-implicit-member-expression/_config.js
- test/runtime/samples/reactive-values-no-implicit-member-expression/main.svelte
Fixes #4212. In DOM mode, we were declaring the variable automatically, which is almost certainly never going to be helpful (and broke stuff like using it to update `document.title`). In SSE mode, we were writing actually invalid code (`let document.title = ...`). This simply skips the automatic declaration of the variable when the LHS of the assignment is a MemberExpression.
> fix when LHS of a reactive assignment is a member expression

- CHANGELOG.md
- src/runtime/internal/Component.ts
- test/runtime/samples/reactive-values-store-destructured-undefined/_config.js
- test/runtime/samples/reactive-values-store-destructured-undefined/main.svelte
Fixes #4170. I investigated swapping the second and third arguments to `$$invalidate` but that ran into complications because the `ret` argument actually contains the assignment, and needs to be evaluated before the `value` argument. So, ultimately, I just used a `...rest` argument, and `value` is getting manually set to `rest.length ? rest[0] : ret`.
> fix $$invalidate getting confused by an undefined third argument (#4170)

- site/content/docs/02-template-syntax.md
Inspired by az8 in chat:
> I figured out with a proxy object that a #each call requires the length property and indexed accessing. But im not sure where in the docs i could have found this info
> Explain how each blocks work a bit more

- site/content/docs/01-component-format.md
- site/content/docs/03-run-time.md
I've been scratching my head trying to understand the ins and outs of the store contract, and how to implement custom stores. This PR is a suggestion for how to improve the documentation.
1. I've expanded the `svelte/store` intro to be much more explicit about the store contract documentation.
2. I've reorganized the section in `01-component-format.md` to describe the syntax first (which is what the headline promises) and the contract second.
3. I put the specifics of what you need to fulfil to implement a store in a numbered list, to make it super clear.
4. I've added a tiny example of how to wrap `location.hash` and the `hashchange` event in a custom store. I'm not sure if this is the best example, but it is small. It might be better to include an example of, say, RxJS, but I'm probably …
> Clearer documentation of store contract

- src/compiler/compile/Component.ts
- test/validator/samples/unreferenced-variables/warnings.json
It feels a bit awkward to see the quoted prop in the console since you can't copy and paste even though it looks like the suggested solution.
> remove quotes from code suggestion

- CHANGELOG.md
- src/compiler/compile/render_dom/Block.ts
- test/js/samples/action-custom-event-handler/expected.js
- test/js/samples/action/expected.js
- test/js/samples/bind-online/expected.js
- test/js/samples/bind-open/expected.js
- test/js/samples/bindings-readonly-order/expected.js
- test/js/samples/capture-inject-dev-only/expected.js
- test/js/samples/component-static-var/expected.js
- test/js/samples/component-store-reassign-invalidate/expected.js
- test/js/samples/dont-invalidate-this/expected.js
- test/js/samples/event-handler-dynamic/expected.js
- test/js/samples/event-handler-no-passive/expected.js
- test/js/samples/event-modifiers/expected.js
- test/js/samples/input-files/expected.js
- test/js/samples/input-no-initial-value/expected.js
- test/js/samples/input-range/expected.js
- test/js/samples/input-value/expected.js
- test/js/samples/input-without-blowback-guard/expected.js
- test/js/samples/instrumentation-script-if-no-block/expected.js
- test/js/samples/instrumentation-script-x-equals-x/expected.js
- test/js/samples/instrumentation-template-if-no-block/expected.js
- test/js/samples/instrumentation-template-x-equals-x/expected.js
- test/js/samples/media-bindings/expected.js
- test/js/samples/video-bindings/expected.js
- test/js/samples/window-binding-online/expected.js
- test/js/samples/window-binding-scroll/expected.js
- test/runtime/samples/action-receives-element-mounted/_config.js
- test/runtime/samples/action-receives-element-mounted/main.svelte
Fix https://github.com/sveltejs/svelte/issues/4166
moved listeners to `mount` phase.
> fix actions has no access to parent nodes

- src/runtime/internal/ssr.ts
- test/server-side-rendering/samples/spread-attributes-white-space/_expected.html
- test/server-side-rendering/samples/spread-attributes-white-space/main.svelte
Fixes #4240.
In `ssr.ts`, `JSON.stringify` was being used to encode the values of attributes. This was causing actual JavaScript/JSON escape values to be written into the HTML. This fix changes it so it concatenates double quotes before and after `String(value)` instead.
-  [X] Run the tests tests with `npm test` or `yarn test`)
> Issue 4240

- CHANGELOG.md
- site/content/docs/03-run-time.md
- site/content/docs/04-compile-time.md
- src/compiler/compile/render_ssr/handlers/Element.ts
- src/compiler/compile/render_ssr/handlers/Title.ts
- test/helpers.js
- test/runtime/index.js
- test/server-side-rendering/index.js
- test/server-side-rendering/samples/head-meta-hydrate-duplicate/_config.js
- test/server-side-rendering/samples/head-multiple-title/_expected-head.html
- test/server-side-rendering/samples/head-title/_expected-head.html
Fixes #4258. The tests also had to be rearranged a bit to support custom compiler options during `server-side-rendering` tests, and I've tidied up a couple of things there.
> only attach SSR head markers when hydratable=true

- CHANGELOG.md
- src/compiler/compile/nodes/Element.ts
- test/runtime/samples/component-slot-let-g/A.svelte
- test/runtime/samples/component-slot-let-g/_config.js
- test/runtime/samples/component-slot-let-g/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4173
> fix allow let scoped to root element

- src/compiler/utils/names.ts
It came up in discord that `setTimeout` used outside of `script` triggers a warning; e.g. `<button on:click={() => setTimeout(...)}>`. I also added `setInterval` and a couple of other common globals.
> Add more globals

- src/compiler/compile/nodes/Binding.ts
- src/compiler/compile/nodes/shared/TemplateScope.ts
- test/validator/samples/binding-await-catch/errors.json
- test/validator/samples/binding-await-catch/input.svelte
- test/validator/samples/binding-await-then-2/errors.json
- test/validator/samples/binding-await-then-2/input.svelte
- test/validator/samples/binding-await-then/errors.json
- test/validator/samples/binding-await-then/input.svelte
Fixes: https://github.com/sveltejs/svelte/issues/4012
> disallow binding variables declared in await and catch

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/Body.ts
- src/compiler/compile/render_dom/wrappers/Element/EventHandler.ts
- src/compiler/compile/render_dom/wrappers/shared/add_event_handlers.ts
- test/runtime/samples/event-handler-modifier-body-once/_config.js
- test/runtime/samples/event-handler-modifier-body-once/main.svelte
Fixes #4278 by making `<svelte:body>` events use the same `listen()` helper used elsewhere. This required a little rejiggering elsewhere, making the event target also allowed to be an Expression (`document.body`) instead of just a string.
> apply event modifiers to <svelte:body> events

- CHANGELOG.md
- src/compiler/compile/css/Selector.ts
- test/css/samples/attribute-selector-word-arbitrary-whitespace/expected.css
- test/css/samples/attribute-selector-word-arbitrary-whitespace/input.svelte
Fixes #4242, which I broke in #3552.
> fix '~=' and class selectors with arbitrary whitespace

- CHANGELOG.md
- src/runtime/internal/dom.ts
- test/hydration/samples/element-attribute-removed/_before.html
Fixes #1733. `node.attributes` is a live list that was being updated as we called `node.remoteAttribute()`, and so we were skipping over and neglecting to check any attribute that occurred after one we did remove.
> fix removing attributes during hydration

- CHANGELOG.md
- src/runtime/internal/utils.ts
- src/runtime/store/index.ts
- test/store/index.js
Fixes #4298. I'm not convinced this is the best way to handle this though. Making the `subscribe` helper accept a `...` rest param might not be worth it just to make the code slightly more DRY.
> fix deriving from RxJS observables

- CHANGELOG.md
- src/compiler/compile/render_ssr/handlers/Title.ts
- test/hydration/samples/head-meta-hydrate-duplicate/_before_head.html
- test/server-side-rendering/samples/head-meta-hydrate-duplicate/_expected-head.html
Fixes #4310. Tested with the repro in that ticket. No new unit test though because I couldn't get the existing `head-meta-hydrate-duplicate` test to acknowledge that the `<title>` was currently getting removed. Possibly a JSDOM limitation, but I didn't look into it too hard.
> fix hydration of <title>

- CHANGELOG.md
- src/runtime/internal/utils.ts
- test/runtime/samples/store-auto-subscribe-nullish/_config.js
- test/runtime/samples/store-auto-subscribe-nullish/main.svelte
Resolves #2181.
This adds a _very_ slight cost in terms of per-app bytes (and adds an extra `== null` test each time we subscribe to a component via the `subscribe()` helper) - and it's possible that this will mask genuine bugs or logic errors in components - but I still think we're better off with this.
With this PR, you're allowed to have autosubscribed stores that don't immediately have values, which, in addition to what's described in #2181, also lets you more easily use a series of reactive declarations to grab something from nested stores.
If this is merged, we should probably also document the new behavior somewhere beyond the changelog, but I'm not sure where.
> make autosubscribing to a nullish store a no-op

- .github/workflows/ci.yml
- src/compiler/compile/utils/__test__.ts
While implementing #3311 (and adding some unit tests for some new util functions I wrote), I noticed that the existing unit tests:
- are broken (specifically this case).
- are never run on CI / anywhere.
This ticket fixes the first item by making the test more valuable and testing the real case that it was meant to catch (for Windows filenames -- see https://github.com/sveltejs/svelte/pull/3862).
It addresses the second issue by adding unit testing to the CI tasks. Not sure if this is actually something we want seeing as we're only testing one module (for now). 
I hope that this encourages more unit testing in the future (although I think the integration/other tests are probably solid enough already). In general I think unit tests are pretty cheap, but one thing they are good for …
> [Internals] Improve unit tests

- site/content/docs/00-introduction.md
As noted on the Discord chat, the docs are more complete now.
So I removed the WIP message, but I kept the reference to Discord, since it's important to lead people to the chat for an active community.
Signed-off-by: Wolfr <johan.ronsse@gmail.com>
> [site] Remove WIP message, but still reference the chat room.

- CHANGELOG.md
- src/compiler/compile/css/Selector.ts
- test/css/samples/global-with-unused-descendant/_config.js
- test/css/samples/global-with-unused-descendant/input.svelte
Resolves #4314.
Note that this doesn't actually fix what's described in the OP (which isn't a bug), but rather what I described in my comment - namely, that selectors like `:global(.foo) .bar` aren't getting correctly marked as unused if nothing matched `.bar`.
I'm a little concerned that the fix might not be as simple as this PR is making it out to be, but I'm hoping it is.
> fix detection of unused partially global CSS selectors

- site/src/routes/blog/index.svelte
Fixes #4338 for feed readers that can't resolve the relative URL properly.
> site: use absolute href to blog feed

- CHANGELOG.md
- src/compiler/parse/state/tag.ts
- test/parser/samples/attribute-unique-binding-error/error.json
- test/parser/samples/attribute-unique-binding-error/input.svelte
- test/parser/samples/attribute-unique-shorthand-error/error.json
- test/parser/samples/attribute-unique-shorthand-error/input.svelte
Fixes #4325 by making such code a compile-time error. `foo`, `{foo}`, and `bind:foo` are now mutually exclusive, on elements or components.
Note that `bind:this` and `this` _are_ allowed to co-exist, as `<svelte:component bind:this={foo} this={bar}/>` is perfectly valid.
> disallow simultaneous foo / {foo} / bind:foo

- site/content/docs/04-compile-time.md
Hopefully this is clear enough to resolve #4337.
> site: clarify preserveWhitespace

- CHANGELOG.md
- src/compiler/compile/render_dom/Renderer.ts
- test/runtime/samples/module-context-bind/_config.js
- test/runtime/samples/module-context-bind/main.svelte
Fixes #4086. I looked a bit into the other optimizations I mentioned in that issue, but I don't think they're worth the effort for now, especially since binding to module-level variables is kind of a weird and niche thing to be doing anyway.
> fix binding to module-level variables

- CHANGELOG.md
- package-lock.json
- package.json
- src/compiler/compile/render_dom/Renderer.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_dom/invalidate.ts
- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/MustacheTag.ts
- src/compiler/compile/render_dom/wrappers/RawMustacheTag.ts
- src/compiler/compile/render_ssr/handlers/AwaitBlock.ts
- src/compiler/compile/render_ssr/handlers/Element.ts
- src/compiler/compile/render_ssr/handlers/Head.ts
- src/compiler/compile/render_ssr/handlers/Title.ts
Fixes #4384 by updating code-red, and also fixes a bunch of usage issues that were revealed by code-red being stricter with parsing expressions.
> fix arrow function precedence

- package-lock.json
`npm audit` lists two high vulnerabilities related to _https-proxy-agent_ during install (of this repo). 
```
npm install
...
found 2 high severity vulnerabilities
```
`npm audit fix` updates https-proxy-agent from version 2.2.2 to 2.2.4.
```
npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Machine-In-The-Middle                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ https-proxy-agent                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ codecov [dev]                                                │ …
```
> npm audit fix related to https-proxy-agent

- src/runtime/internal/scheduler.ts
We noticed that there was a large amount of memory being created as part of the flush method, which seems to be due to some array optimizations in old JS engines. This seems to be easily fixed by changing to a simple for loop instead of a while loop that modifies the array during iteration. This is the same pattern that is used for the `render_callbacks`.
> Avoid using shift in flush

- CHANGELOG.md
- src/compiler/compile/render_dom/invalidate.ts
- test/runtime/samples/instrumentation-update-expression/_config.js
- test/runtime/samples/instrumentation-update-expression/main.svelte
Fixes #4393. The optimization we're doing where we don't pass the invalidated value in as a third argument to `$$invalidate` in certain cases is incorrect in `++foo.bar` because this sets `foo` to the new value of `foo.bar`.
> fix invalidation in ++foo.bar

- CHANGELOG.md
- src/compiler/compile/nodes/EventHandler.ts
- test/runtime/samples/event-handler-dynamic-2/_config.js
- test/runtime/samples/event-handler-dynamic-2/main.svelte
Fixes #4388. The existing `EventHandler#reassigned` logic was buggy because there would be no `node_for_declaration` for automatically declared reactive assignments (or for store autosubscriptions).
I initially changed it to checking `this.component.var_lookup.get(node.name)`, but this didn't work for stores. I added a special case for `node.name[0] === '$'`, and that did work.
But then I realized we probably didn't need this logic at all, and that we could just use the `this.expression.dynamic_dependencies().length > 0` check for everything that wasn't a function, regardless of whether it was an identifier. This seemed to work, and didn't break any existing tests, and was simpler as a bonus.
> fix event handlers that are dynamic via reactive declarations or stores

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/runtime/internal/dom.ts
- test/runtime/samples/binding-indirect-spread/_config.js
- test/runtime/samples/binding-indirect-spread/main.svelte
Fixes #3680. On indirectly bound values, what's important is the custom `__value` property on the element. This makes the combined object of props/attrs used in spreads include `__value` instead of `value` in cases where there is an indirect binding - and also updates the `set_attributes` helper to include a special case for `__value`, which we would otherwise try to set as an attribute since it's not a valid property on the prototype.
This does not address #4397, which I split off as a separate issue, and looks to be unrelated to the spread.
It also does not address #4392, which is less of a related issue than I had hoped it would be.
> fix indirect bindings on elements with spreads

- site/content/docs/04-compile-time.md
This just adds `await` in front of `svelte.preprocess` examples to indicate that it returns a Promise. Otherwise, the examples would throw an error.
> docs: add await in front of preprocess examples

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/js/samples/each-block-keyed-animated/expected.js
- test/js/samples/each-block-keyed/expected.js
- test/runtime/samples/component-binding-blowback-c/main.svelte
- test/runtime/samples/each-block-keyed-dynamic-2/_config.js
- test/runtime/samples/each-block-keyed-dynamic-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4373
> feat: dirty check before update keyed each block

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- test/validator/index.js
- test/validator/samples/component-dynamic/input.svelte
- test/validator/samples/component-dynamic/options.json
- test/validator/samples/component-dynamic/warnings.json
Fixes https://github.com/sveltejs/svelte/issues/4331
> feat: warn if component is expected to be reactive
