- site/content/blog/2019-04-16-svelte-for-new-developers.md
The commands used in the tutorial can't work on Windows with the command prompt, so I specify PowerShell instead of it
> Blog: Update default shell to use on Windows

- site/content/docs/02-template-syntax.md
I've rewritten a sentence to avoid using the word "outroing". I came here thinking it was a typo of "outgoing", but discovered it is a term used internally with Svelte. I think the term is confusing and does not help people to learn Svelte.
Thanks!
> Suggest not using the word "outroing"

- site/src/routes/repl/[id]/index.svelte
When reloading a saved project in the REPL with a file containing multiple dots (like `example.store.js`), the file will be reload with an uncomplete name (=> `example.store`) and imports will break.
Example REPL generating this error : https://svelte.dev/repl/e16ae6e77ec94412b296dc7af897ac85?version=3.18.2 
This error can be fix by using the last dot in filename for splitting (`lastIndexOf('.')`)  instead of `let [name, type] = file.name.split('.');` :blush:
> repl: multiple dots in filename not supported when reloading a saved project in REPL

- site/content/docs/02-template-syntax.md
In the first example, "item" is used to describe three logically
distinct objects: (1) the name of the slot's property; (2) the JS
variable used within FancyList.svelte's {#each} block; and (3) the JS
variable used within App.svelte. To make it clearer that these are
three different objects, give them different names.
The second example can continue reusing the same name for all of the
objects to demonstrate there's no collision between them. But we can
also simplify the example to take further advantage of shorthand
rules.
> site: clearer examples for <slot let:name>

- CHANGELOG.md
- src/runtime/internal/dev.ts
- test/runtime/samples/each-block-string/_config.js
- test/runtime/samples/each-block-string/main.svelte
Fixes #4450. `'length' in str` is a runtime error, so we now check whether it's a string _or_ a truthy object with a `length` key. I can't think of a case where we might want to allow another value type, like `function` for example.
> fix dev mode each block validation when using strings

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- test/runtime/samples/deconflict-contextual-bind/Widget.svelte
- test/runtime/samples/deconflict-contextual-bind/_config.js
- test/runtime/samples/deconflict-contextual-bind/main.svelte
> deconflict `value` parameter in contextual bindings

- CHANGELOG.md
- src/compiler/compile/render_dom/invalidate.ts
Fixes #4368. No tests, and I think I want to kick the can on what actually should happen when writing to `$$props` (should it be a compile-time error?). At the very least, treating it as a subscription to `$props` was definitely wrong.
> don't treat $$-names as stores during invalidation

- src/compiler/compile/render_dom/index.ts
- test/js/samples/loop-protect/expected.js
Fixes #4463. As luck would have it, we already have an unrelated test that contains a global (`console`), and so captures the behaviour. I suppose this is good enough for this?
> exclude global variables from $capture_state

- site/content/docs/04-compile-time.md
#3802 introduced `referenced_from_script` as part of a fix, and also exposes it in `vars` but didn't document it.
> docs: referenced_from_script var value

- README.md
- src/compiler/compile/Component.ts
- src/compiler/compile/nodes/Let.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/render_dom/index.ts
This pr fixes the compile errors in https://github.com/sveltejs/svelte/issues/4482
> fix https://github.com/sveltejs/svelte/issues/4482

- site/content/docs/02-template-syntax.md
This adds a brief explanation on how falsy values for boolean attributes and nullish values for other attributes work.
Resolves #4440 and possibly others as well.
> docs: describe falsy and nullish attribute behavior

- CHANGELOG.md
- src/compiler/compile/nodes/Text.ts
- src/compiler/compile/render_dom/wrappers/Fragment.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/compiler/compile/render_dom/wrappers/Text.ts
- src/compiler/compile/render_ssr/handlers/Element.ts
- src/compiler/compile/render_ssr/handlers/InlineComponent.ts
- src/compiler/compile/render_ssr/handlers/utils/remove_whitespace_children.ts
- src/compiler/utils/link.ts
- test/runtime/samples/component-slot-fallback-empty/Nested.svelte
- test/runtime/samples/component-slot-fallback-empty/_config.js
- test/runtime/samples/component-slot-fallback-empty/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4092
If the slot is rendering white space, (most likely get trimmed and will not render anything if the white space is due to formatting), render the slot fallback content instead.
> fix render fallback slot content due to white space

- CHANGELOG.md
- src/compiler/compile/render_dom/Block.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/runtime/internal/dev.ts
- test/js/samples/capture-inject-state/expected.js
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/debug-hoisted/expected.js
- test/js/samples/debug-no-dependencies/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/js/samples/loop-protect/expected.js
- test/runtime/samples/component-slot-warning/Nested.svelte
- test/runtime/samples/component-slot-warning/_config.js
- test/runtime/samples/component-slot-warning/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/1020, Fixes https://github.com/sveltejs/svelte/issues/1447
Failed test case will be fixed by https://github.com/sveltejs/svelte/pull/4500
Not sure the warning message is clear enough.
> warn if passing slot not defined into Component

- CHANGELOG.md
- src/compiler/compile/render_dom/Renderer.ts
- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- src/compiler/compile/render_dom/wrappers/shared/get_slot_definition.ts
- test/runtime/samples/bitmask-overflow-if/_config.js
- test/runtime/samples/bitmask-overflow-if/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4263
the initial dirty value needs to be depend on whether bitmask context overflow
> fit bitmask overflow initial dirty value

- CHANGELOG.md
- src/compiler/parse/state/tag.ts
- test/parser/samples/error-self-reference/error.json
- test/runtime/samples/self-reference-component/Countdown.svelte
- test/runtime/samples/self-reference-component/_config.js
- test/runtime/samples/self-reference-component/main.svelte
Related: https://github.com/sveltejs/svelte/issues/2798
> allow <svelte:self> to be part of a slot

- CHANGELOG.md
- src/runtime/internal/Component.ts
- test/hydration/samples/top-level-cleanup-2/_after.html
- test/hydration/samples/top-level-cleanup-2/_before.html
- test/hydration/samples/top-level-cleanup-2/_config.js
- test/hydration/samples/top-level-cleanup-2/main.svelte
- test/hydration/samples/top-level-cleanup/_after.html
- test/hydration/samples/top-level-cleanup/_before.html
- test/hydration/samples/top-level-cleanup/_config.js
- test/hydration/samples/top-level-cleanup/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4542
Explanation: https://github.com/sveltejs/svelte/issues/4542#issuecomment-598527674
> fix hydrating top level content

- src/compiler/compile/render_dom/Block.ts
- src/compiler/compile/render_dom/Renderer.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/compiler/compile/render_dom/wrappers/Slot.ts
- remove slot template fragment block
- in https://github.com/sveltejs/svelte/pull/4500 we do not use the fragment block if it is empty, but we still render the fragment block code.
- remove empty slot fallback block
- if the slot fallback has no content, remove it.
> remove unneeded fragment block

- .gitignore
-  [X] Run the tests tests with `npm test` or `yarn test`)
fixed #4594 
When I saved some files, it was changed automatically due to vscode setting.
vscode default setting value of typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions is true
And I use this setting value all of my workspaces.
But it seems like svelte project is using false.
I want to try to join this project, but I couldn't change default settings for only this project.
Because my other projects are using true.
So I set some setting values and don't want to commit, because other people don't need this value.
I thought I would commit my `.vscode/settings.json`, but you might not want it.
So I commit only `.gitignore` 😃
> add '.vscode' to .gitignore (#4594)

- site/content/docs/03-run-time.md
There is a small typo in site/content/docs/03-run-time.md.
Should read `specify` rather than `specificy`.
> docs: Fix simple typo, specificy -> specify

- src/runtime/internal/globals.ts
> feat(internal): Support globalThis in modern environments

- site/content/examples/21-miscellaneous/01-hacker-news/Item.svelte
- site/content/examples/21-miscellaneous/01-hacker-news/Summary.svelte
Before, the link for items of type `ask` would be `https://svelte.dev/item?id=22792829` (which returns a 404), and with this change, the correct URL `https://news.ycombinator.com/item?id=22792829` is generated.
> fix(examples): use correct URL for Ask HN posts

- site/content/examples/21-miscellaneous/01-hacker-news/Item.svelte
This commit introduces a null-undefined check against the domain of the HN items in the Hacker News example.
---
Note that it still works fine on items with correct domain
---
> fix(examples): hide "undefined" domain in HN example

- src/compiler/compile/Component.ts
`seen` is reassigned a new Set that is added items but not used anywhere
> remove unused variable

- site/content/examples/03-logic/04-keyed-each-blocks/App.svelte
Change `grip-gap` to the intended `grid-gap`.
Fixes #4680.
> Fix #4680 - CSS typo in example

- site/content/docs/02-template-syntax.md
Based on the confusion in #4681, clarify behavior around blocks containing outroing elements.
-  [X] Run the tests tests with `npm test` or `yarn test`)
> Clarify that all elements in an outroing block remain until the transition finishes

- site/scripts/get-example-thumbnails/index.js
The `if` conditional was checking the same condition twice. The code
appears to intend to check both the height and width. I found this alert
on LGTM.com:
https://lgtm.com/projects/g/sveltejs/svelte/alerts/?mode=list
> Fix: make condition check height in addition to width

- src/compiler/parse/read/script.ts
- test/sourcemaps/samples/script-after-comment/input.svelte
- test/sourcemaps/samples/script-after-comment/test.js
- test/sourcemaps/samples/two-scripts/input.svelte
- test/sourcemaps/samples/two-scripts/test.js
Fixes issue #3906.  Sourcemaps line numbers for every `<script>` start at line 1, even when the script is lower in the file.  E.g.
```
<script>
...
</script>
```
and
```
<script context="module">
// correct sourcemap
...
</script>
<script>
// incorrect sourcemap
...
</script>
```
The two examples above are (approximately) the two tests included in this PR.  Both tests fail prior to applying the fix and pass afterwards.
> fix misaligned line number in sourcemap (#3906)

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-anchor-is-valid/input.svelte
- test/validator/samples/a11y-anchor-is-valid/warnings.json
`href="javascript:void(0)"` is not recommended for a11y and maybe it would be great if svelte can warn about it.
Besides, would it be great to warn about something like:
```svelte
<a href={null}></a>
<a href={undefined}></a>
<a href={`javascript:void(0)`}></a>
```
as well? If so I'm willing to help or have an issue about this.
> a11y: warn about href="javascript:void(0)"

- site/content/docs/03-run-time.md
I noticed the current link to transitions wasn't going anywhere. Let me know if this is correct or not :+1:
~~- [x] It's really useful if your PR relates to an outstanding issue, so please reference it in your PR, or create an explanatory one for discussion. In many cases features are absent for a reason.~~
~~- [x] This message body should clearly illustrate what problems it solves. If there are related issues, remember to reference them.~~
~~- [x] Ideally, include a test that fails without this PR but passes with it. PRs will only be merged once they pass CI. (Remember to `npm run lint`!)~~
~~-  [x] Run the tests tests with `npm test` or `yarn test`~~
I don't  think the requirements above apply here :slightly_smiling_face:
> Update link to transitions section

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-anchor-is-valid/input.svelte
- test/validator/samples/a11y-anchor-is-valid/warnings.json
As stated in #4697, the <a> tag should not issue a warning when it contains the `name` and` id` attributes
> fix: removing warnings in <a name> (#4697)

- src/compiler/compile/Component.ts
- test/runtime/samples/loop-protect-generator-opt-out/_config.js
- test/runtime/samples/loop-protect-generator-opt-out/main.svelte
Fixes #4698
This PR will allow us to use loops within generator functions in the REPL without it throwing an incorrect "Infinite loop" error. This is done by opting out of `loop_protect` if the loop is inside a generator function
I have used `generator_count` rather than a simple boolean to make sure it works for nested generators also
I'm very new to both ASTs and the Svelte codebase so if there's a better way to do this I'd love to hear it!
Thanks
> Opt out of loop protection if inside generator

- site/content/tutorial/03-props/02-default-values/text.md
Target page: https://svelte.dev/tutorial/default-values
I was stuck by this instruction for a while, and I think maybe we can make it more clear.
Related issue: #4521
> [Tutorial] Make the instruction of default values more clear

- site/content/examples/06-lifecycle/02-update/App.svelte
- site/content/examples/06-lifecycle/03-tick/App.svelte
- site/content/examples/10-animations/00-animate/App.svelte
- site/content/tutorial/07-lifecycle/03-update/app-a/App.svelte
- site/content/tutorial/07-lifecycle/03-update/app-b/App.svelte
- site/content/tutorial/07-lifecycle/04-tick/app-a/App.svelte
- site/content/tutorial/07-lifecycle/04-tick/app-b/App.svelte
- site/content/tutorial/10-transitions/08-deferred-transitions/app-a/App.svelte
- site/content/tutorial/10-transitions/08-deferred-transitions/app-b/App.svelte
- site/content/tutorial/11-animations/01-animate/app-a/App.svelte
- site/content/tutorial/11-animations/01-animate/app-b/App.svelte
- site/src/routes/repl/[id]/_components/AppControls/index.svelte
- test/runtime/samples/action-custom-event-handler-this/_config.js
- test/runtime/samples/action-custom-event-handler-this/main.svelte
- test/runtime/samples/window-event-custom/_config.js
- test/runtime/samples/window-event-custom/main.svelte
Fixes #4755 -- Tutorials use `event.which`, which is deprecated in favor of `event.key`.
I also converted the other instances of event.which: two tests and one line in the REPL code. I tested the REPL by adding a temporary console.log inside the key handler and checking that it triggered when I pressed Cmd+s.
- [NA] Ideally, include a test that fails without this PR but passes with it. PRs will only be merged once they pass CI. (Remember to `npm run lint`!)
-  [X] Run the tests tests with `npm test` or `yarn test`)
> Use event.key instead of event.which

- src/runtime/motion/tweened.ts
- test/motion/index.js
Fixes #4399
This is something I recently needed again, I wanted to immediately set the store to a new value from the authoritative source and then start a tween based on the given rate of change of the value towards the min/max (depending on direction of change). I was getting weird numbers using the `{ duration : 1 }` hack until I made the tweened `.set()` call live in a rAF which just seemed silly.
Now, if you call `.set(<value>, { duration : 0 })` it'll just set immediately and as a bonus do way less work! Added a test that fails w/o this PR (though it fails due to node not having `requestAnimationFrame`, *not* due to the value not setting instantly).
> feat: instant-set for zero duration

- site/content/docs/01-component-format.md
The store contract documentation states that the subscribe method "must return an unsubscribe function", but its signature suggested that it instead took a second, unit argument then returned `void`. This PR adds parentheses to reflect the intended meaning. 
I haven't given a name to the unit argument to the unsubscribe function.
> docs: fix store contract type signature

- src/compiler/compile/render_dom/wrappers/shared/bind_this.ts
- test/runtime/samples/binding-this-each-object-props/_config.js
- test/runtime/samples/binding-this-each-object-props/main.svelte
- test/runtime/samples/binding-this-each-object-spread/_config.js
- test/runtime/samples/binding-this-each-object-spread/main.svelte
Fix #4686
Code from issue
```
{#each entries as { itemId, entry } (itemId)}
<div bind:this={items1[itemId]} />
<div bind:this={items2[itemId]} />
{/each}
```
Adding dependecies only use single variable name (`itemId`), but it can be too hard to detect what array `items1[itemId]` and `items2[itemId]` are different.
If you use it carefully, there will be no problems. Also, detecting different variable names can be bypassed by using variable reference (something like `let items1 = []; let items2 = items1;`)
Also i add two tests (one with object props, and one with spread)
PS: also i look to issue #4636, but this is another issue that is not directly related to this one
> Fix: bind:this in each with objects\array

- site/content/docs/04-compile-time.md
Partially addresses https://github.com/sveltejs/svelte/issues/4816
If you Google 'svelte typescript' you're taken to closed issues without much explanation as to the current state of TypeScript support. It's nearly impossible to figure out and took me a couple days of research. I included the text "TypeScript" in the hope that people can find it using Ctrl+F and that it comes up first on Google. PostCSS, SCSS, and Less are also widely used enough that it seemed worth a singular mention in the docs. I tried to mirror the existing reference to "webpack" that appears earlier in the docs for consistency
Note that this depends on https://github.com/sveltejs/integrations/pull/33 being merged first
> Link to list of community preprocessors

- src/runtime/motion/tweened.ts
Fixes #4846
Now when the early-out branch is taken for a `duration` of 0 it will do two things that were missing in the first implementation:
1. It will cancel any tweens that are in-progress so the value doesn't keep changing after snapping to the specified value.
2. It will cache off the `value` correctly, so that later tweens use the correct starting point.
Is there a better way to test this within the current suite? The mocha tests don't have access to any browser globals so you can't actually test any tweens and given how broken this was after #4766 the lack of test coverage makes me nervous.
> fix: cache value & cancel tween for instant-set

- src/runtime/internal/dom.ts
There's a bug where when `<input bind:value={sampleVar} />` and `sampleVar` is updated to undefined (`sampleVar = undefined`), then the input displays "undefined" (despite the input initally showing up correctly empty when initialized to undefined).
This issue has been documented since September 14, 2019 https://github.com/sveltejs/svelte/issues/3569
I'm new to Svelte, but this seems to fix this problem.
> Fix input with bind:value displaying "undefined"

- src/runtime/internal/dom.ts
Fixes #4752 by not attempting to call `.removeEventListener` if the `iframe.contentWindow` no longer exists.
Also now calls `unsubscribe()` w/o checking in the cross-origin case because it is set synchronously for that codepath.
I wasn't able to write a test for this, unfortunately, but it does work in our svelte app in Chrome as well as our goofy custom browser that exhibited the issue from #4752.
> fix: Don't attempt to unsub if the iframe is destroyed

- site/content/docs/01-component-format.md
- site/content/docs/02-template-syntax.md
- site/content/docs/03-run-time.md
- site/package-lock.json
- site/package.json
- site/src/utils/highlight.js
This PR adds proper syntax highlighting to svelte code blocks via [prism-svelte](https://github.com/pngwn/prism-svelte).
It works for big old code blocks like this:
And also for those signatures we have like this:
If some helpful folk could take a look over the svelte blocks to make sure nothing is amiss, that would be great.
The svelte grammar extends the markup grammar so the addition of a new `sv` tag wasn't strictly necessary (all valid HTML should be highlighted correctly too) but I felt it was better to be explicit.
> svelte syntax highlighting via prism

- src/compiler/compile/render_dom/wrappers/Slot.ts
- src/runtime/internal/utils.ts
- test/runtime/samples/bitmask-overflow-slot-6/Slotted.svelte
- test/runtime/samples/bitmask-overflow-slot-6/_config.js
- test/runtime/samples/bitmask-overflow-slot-6/main.svelte
Fixes: https://github.com/sveltejs/svelte/issues/4624
without specifying any `let:` , the `slot_changes` would be undefined. this may cause issue when context overflow, where we access the `slot_changes` as array.
> fix slot with context overflow + without let

- README.md
- site/content/faq/300-is-svelte-dev-down.md
It was pointed out in https://github.com/sveltejs/svelte/pull/4823#issuecomment-632147491 that if svelte.dev is down you won't be able to get to the FAQ to get this information, so it should probably live elsewhere
> Move info from FAQ to Readme

- site/content/docs/03-run-time.md
Only a minor edit: `blur` was missing from the list of `svelte/transition` exports.
> API / Docs: include blur

- site/content/docs/02-template-syntax.md
Fixes #4808
Note that when using `bind:group`, setting `value` via spread attributes doesn't work. 
e.g.  `<input type="radio" bind:group={v} {...props}>`
> docs: `value` can not be set via spread attribute when using bind:group

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
- test/runtime/samples/binding-select-late-2/_config.js
- test/runtime/samples/binding-select-late-2/main.svelte
Fixes: https://github.com/sveltejs/svelte/issues/1764
reselect `<select>` when option value changed.
> fix select bind:value when option value change

- site/content/docs/03-run-time.md
The current time should be stored by the callback when the first subscriber comes, and not when the readable is first created
> Small tweaks to readable store example

- .github/workflows/ci.yml
https://github.com/sveltejs/svelte/pull/4886 suggested that there were issues running the tests on Windows. I added this to check it, but did not run into any problems myself
Feel free to close if this isn't valuable or there's some kind of limit to the number of tests we can run on GitHub actions. It was mostly in service of investigating the possible Windows issues, which I don't see being reproduced here
> Run unit tests on Windows

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/js/samples/select-dynamic-value/expected.js
- test/runtime/samples/spread-element-input-seelct-multiple/_config.js
- test/runtime/samples/spread-element-input-seelct-multiple/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4392
> set select multiple value with spread

- CHANGELOG.md
- src/compiler/compile/nodes/Binding.ts
- test/runtime/samples/reactive-function-called-reassigned/_config.js
- test/runtime/samples/reactive-function-called-reassigned/main.svelte
Fixes: https://github.com/sveltejs/svelte/issues/4879
- when binding to a variable within `{#each}` context, the dependency of the variable is mutated, not reassigned.
> called reactive functions for reassignments

- site/content/examples/05-bindings/08-media-elements/App.svelte
> Fix mixed content

- src/compiler/compile/render_dom/wrappers/Element/index.ts
I noticed some places in this file were already using `namespaces.svg`. This looked like another place that could as well
> Use namespaces.svg constant

- site/content/faq/500-what-about-typescript-support.md
Closes https://github.com/sveltejs/svelte-preprocess/issues/144
Syntax is based off the discussion in https://github.com/sveltejs/svelte/issues/4965 and https://github.com/sveltejs/svelte/issues/4518
> Document how to declare reactive variable type

- site/content/docs/02-template-syntax.md
I noticed a few slight discrepancies in the docs. This just a slight reordering of content for media element bindings and having it matched in the code snippet.
> minor revision to docs

- src/compiler/parse/read/style.ts
- test/parser/samples/error-css-global-without-selector/error.json
- test/parser/samples/error-css-global-without-selector/input.svelte
Fixes #4930 
Prevent a compiler crash when `:global` appears by itself in a CSS selector by adding an extra check when walking the style AST. If a node meets the following conditions:
- `type` is `'PseudoClassSelector'`,
- `name` is `'global'`, and
- `children` is `null`,
then the parser reports an error: `:global() must contain a selector, cannot be used on its own`.
Long-time user, first-time contributor -- please forgive any naive errors in putting together this PR. In particular, I wasn't quite sure of the right way to report the location of the error. In the file I touched, `src/compiler/parse/read/style.ts`, one of the existing checks uses the node's `loc.start.offset` property, while the other uses the `start` property. The former seemed to make the most sense with the test case I …
> Provide parser error when :global appears without selector in CSS

- src/runtime/internal/dom.ts
Because EdgeHTML does not actually remove the `value` attribute from an `HTMLInputElement`, the prior implementation would generate an infinite loop. By making this two passes, we are a bit less memory efficient but avoid the nasty edge cases when DOM elements don't fully respect the API.
I believe the existing tests, if they were to run against Edge, would suffer from this case. I was unable to do so as the harness is not configured in a way to make that easy, however, it does fix the case I discovered this with in situ.
> Separate the identification and removal of attributes

- site/src/routes/_layout.svelte
This removes the Black Lives Matter grayscale filter while leaving the banner, as discussed.
> site: remove BLM filter, but leave banner

- CHANGELOG.md
- src/compiler/compile/nodes/shared/Expression.ts
- test/runtime/samples/this-in-function-expressions/_config.js
- test/runtime/samples/this-in-function-expressions/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/5033
We assumed object of `MemberExpression` to be `Identifier` only, `ThisExpression` does not have `.name`, causing `.name[0]` to be `accessing property 0 of undefined`
> fix extract names from ThisExpression

- site/content/docs/03-run-time.md
Fixes https://github.com/sveltejs/svelte/issues/4927
> clarify onMount return functions when combined with non-synchronous handlers

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-contenteditable-element-without-child/errors.json
- test/validator/samples/a11y-contenteditable-element-without-child/input.svelte
Address #5020 as per @Conduitry's comments.
> fix(5020): skip child content a11y check on html/textContent binding

- site/src/routes/tutorial/[slug]/_TableOfContents.svelte
Since the anchor tags only contain svg icons it makes these navigational elements not accessible by screen readers.
> aria-label. Providing a descriptive text label lets a user distinguish the link from links in the Web page that lead to other destinations and helps the user determine whether to follow the link. In some assistive technologies the aria-label value will show in the list of links instead of the actual link text.
https://www.w3.org/WAI/GL/wiki/Using_aria-label_for_link_purpose
> [a11y] Make anchor tag tutorial nav accessible

- site/rollup.config.js
Fixes #5056 
Adding a check in the rollup config to see if the Mapbox access token is present when generating a production build.
> fix(5019): check if mapbox key is added before generating the production build.

- site/content/blog/2017-12-31-sapper-towards-the-ideal-web-app-framework.md
This PR address a minor typo in the blog post: `2017-12-31-sapper-towards-the-ideal-web-app-framework.md`
> typo: blog

- .github/workflows/ci.yml
Not sure if we pay any bills for CI, but some builds get stuck for half a day. This will stop that.
> make builds time out after a reasonable period

- src/runtime/animate/index.ts
- src/runtime/transition/index.ts
I've marked the properties of parameters that have default values as optional (`x: number` to `x?: number`)
The current situation marks the properties of the interface as required, which cause errors when properties are omitted:
> Argument of type '{ x: number; }' is not assignable to parameter of type 'FlyParams'.
Type '{ x: number; }' is missing the following properties from type 'FlyParams': delay, duration, easing, y, opacity
> fix: Parameters with default values are optional

- src/compiler/preprocess/index.ts
- test/preprocess/samples/script-self-closing/_config.js
- test/preprocess/samples/script-self-closing/input.svelte
- test/preprocess/samples/script-self-closing/output.svelte
- test/preprocess/samples/style-self-closing/_config.js
- test/preprocess/samples/style-self-closing/input.svelte
- test/preprocess/samples/style-self-closing/output.svelte
Implements #5080
- Extends the regex that is used to identify `script` / `style` tags during preprocessing
- Added two tests: One with a self-closing `script` tag and one with a self-closing `style` tag
- If a self-closing tag doesn't have any attributes it will still be ignored
-  [X] Run the tests with `npm test` or `yarn test`)
> Preprocess self closing style

- src/runtime/internal/dev.ts
- src/runtime/internal/dom.ts
- test/runtime/samples/component-event-handler-contenteditable/_config.js
- test/runtime/samples/component-event-handler-contenteditable/main.svelte
This PR addresses #5018.
Instead of comparing the input with data property on the Text Node, I've changed it to wholeText.
> fix(5018): compare wholeText instead of data

- site/content/faq/401-how-do-i-document-my-components.md
- site/content/faq/450-how-do-i-document-my-components.md
Adds a FAQ entry on how to write documentation for your components: Both at component and JS level. Works in both JS/TS, so long as you have an editor with the LSP that was released in the last week.
Based on @fnune's work in the language tools
- https://github.com/sveltejs/language-tools/pull/282
- https://github.com/sveltejs/language-tools/pull/285
> Adds a FAQ entry for how to document a svelte component

- site/content/examples/05-bindings/07-each-block-bindings/App.svelte
CSS usage could be avoided here, the same effect can be achieved with a `disabled` attribute binding.
-  [ ] Run the tests with `npm test` or `yarn test`)
> Simplify each block bindings example

- site/content/blog/2016-11-26-frameworks-without-the-framework.md
surge.sh provides SSL certificates for free, so why not to give an https version.
-  [ ] Run the tests with `npm test` or `yarn test`)
> Change http to https in 2016-11-26-frameworks-without-the-framework.md

- CHANGELOG.md
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/runtime/internal/utils.ts
- test/runtime/samples/props-reactive-only-with-change/Comp.svelte
- test/runtime/samples/props-reactive-only-with-change/_config.js
- test/runtime/samples/props-reactive-only-with-change/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4993
Fixes https://github.com/sveltejs/svelte/issues/5118
> invalidate $$props or $$restProps only when there's changes

- site/src/routes/repl/[id]/_components/AppControls/index.svelte
Fixes the issue mentioned in #5153 about the wrapping of controls in Safari Mobile.
> Fixes #5153 - Wrapping of buttons in REPL (.app-controls)

- site/README.md
Updates README with steps for working with and updating site-kit components.
> site: explain how to use `site-kit` and `site-repl`

- site/content/blog/2017-12-31-sapper-towards-the-ideal-web-app-framework.md
`sapper.svelte.technology` has moved to `sapper.svelte.dev`. The old URLs redirect to the `.dev` site, but updating the links will avoid the need for each browser to follow a redirect before getting to the site. Additionally, the fragment id in the link to the description of the Sapper name has changed from `#why-the-name-` to `#Why_the_name`. I've updated that as well, so that following the link will scroll to the appropriate section of the page.
> Update old `.technology` links in the Sapper intro blog post

- site/src/routes/blog/rss.xml.js
Fix #5209  by escaping strings that possibly contain HTML which will break the RSS feed.
Currently https://svelte.dev/blog/rss.xml is broken without this fix.
> fix site broken RSS feed

- site/content/tutorial/16-special-elements/01-svelte-self/text.md
Hey! This is a small documentation change which I feel helps make super clear that "file" is really referencing to the `Folder.svelte` component file, not the `<File/>` component.
> Clarify noun regarding svelte-self example

- src/runtime/internal/lifecycle.ts
Adds a type parameter to `setContext` and `getContext` to make it easier to type context values.
Given an interface:
```ts
interface ContextValue {
register: (args: {
id: number;
name: string;
content: string;
type: string;
}) => void;
active: Writable<boolean | number>;
}
```
This becomes possible:
```ts
setContext<ContextValue>(key, {
register: ({ id, name, content, type }) => {
files.update((s) => s.set(id, { name, content, type }));
if (!$active) active.set(id);
},
active,
});
```
and this
```ts
const ctx = getContext<ContextValue>(key)
```
> Add type param to setContext and getContext

- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/runtime/samples/transition-js-each-else-block-intro-outro/_config.js
- test/runtime/samples/transition-js-each-else-block-intro-outro/main.svelte
- test/runtime/samples/transition-js-each-else-block-intro/_config.js
- test/runtime/samples/transition-js-each-else-block-intro/main.svelte
- test/runtime/samples/transition-js-each-else-block-outro/_config.js
- test/runtime/samples/transition-js-each-else-block-outro/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4970.
This PR builds on the work started in https://github.com/sveltejs/svelte/pull/4987. This one deals with outro transitions (only when necessary) and adds more tests similar to those of each-block (i.e. tests for intro, intro-outro, and outro, separately)
*PD: The concern raised in the last comment of https://github.com/sveltejs/svelte/pull/4987 is not a breaking change - that's how each-else works by design. The REPL from the issue adds the else block on top, while the "if" approach adds it to the bottom. That's because each-else shares the same anchor while in each-if both blocks have different anchors.*
This is my first PR. I'm open for any feedback!
> Fix transitions triggering for each-else blocks

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-label-has-associated-control/input.svelte
- test/validator/samples/a11y-label-has-associated-control/warnings.json
For #820  
Because [label-has-for](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md) has been deprecated I have instead implemented [label-has-associated-control](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md).
> fix(820): label has associated control

- site/content/faq/500-what-about-typescript-support.md
This gets asked a lot. I'm not quite sure why Svelte has this additional restriction over normal TypeScript, but it'd be good to mention it up front
> Mention "import type" in TypeScript FAQ

- src/compiler/compile/css/Stylesheet.ts
- test/css/samples/empty-class/_config.js
- test/css/samples/global-with-unused-descendant/_config.js
- test/css/samples/omit-scoping-attribute-descendant/_config.js
- test/css/samples/unused-selector-leading/_config.js
- test/css/samples/unused-selector-string-concat/_config.js
- test/css/samples/unused-selector-ternary-concat/_config.js
- test/css/samples/unused-selector-ternary-nested/_config.js
- test/css/samples/unused-selector-ternary/_config.js
- test/css/samples/unused-selector/_config.js
This pr fixes #5252 . It seems as if the tests are working, but not all of them are running. I don't know exactly how this works. Any help would be appreciated. Thanks
> Fixes #5252

- src/runtime/internal/lifecycle.ts
Makes it possible to explicitly type which events can be dispatched like so:
```ts
const bla2 = createEventDispatcher<{click: boolean}>();
bla2('click', ''); // error, type string not assignable to type boolean
bla2('qwd', true); // error, "qwd" not assignable to "click"
```
#5211
> Typings for createEventDispatcher

- rollup.config.js
This PR provides a first solution to #4806, allowing the compiler to be built to ESM
> Allow using the compiler as an ESM module

- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- src/runtime/internal/await_block.ts
- test/runtime/samples/await-without-catch/_config.js
- test/runtime/samples/await-without-catch/main.svelte
Fixes #5129 , 
When there is no catch block present in an await, it should throw an error 
The change is done as suggested in the issue. I had to pass the hasCatch field since there was no way I could infer whether a catch block was present or not from existing values (I thought of and tried using `info.error` and similar fields, but they will fail for the case when the catch block has no value or is empty.
> Await: re-throw error when there is no catch block and promise is rejected 

- site/content/blog/2020-07-17-svelte-and-typescript.md
It's `// @ts-check` instead of `// @check-js`
> Fix blog JS type checking suggestion

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/spread-element-input-value-undefined/_config.js
- test/runtime/samples/spread-element-input-value-undefined/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/5270
this caused by the difference between `setAttribute` vs setting the property using `propertyName`.
not really sure is this the right way of handling it? if so, should we also handle all the other attribute that has a custom propertyName in https://github.com/sveltejs/svelte/blob/402106330530965ff5a1a5f05fc6529403486328/src/compiler/compile/render_dom/wrappers/Element/Attribute.ts#L291 ?
> handle undefined input value with spread

- CHANGELOG.md
- src/compiler/compile/render_dom/Block.ts
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/runtime/samples/store-each-binding-deep/_config.js
- test/runtime/samples/store-each-binding-deep/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/5286
> each binding with store props

- src/compiler/interfaces.ts
This allows for tighter compile-time checking
> More specific type for CompleOptions.generate

- site/package.json
- site/scripts/copy-workers.js
This hopefully makes it cross-platform compatible. I don't have a Windows machine to test it on, but see that this is the pattern the other scripts follow
> Add a script for copy-workers

- site/content/tutorial/13-classes/01-classes/app-a/App.svelte
- site/content/tutorial/13-classes/01-classes/app-b/App.svelte
- site/content/tutorial/13-classes/01-classes/text.md
[Tutorial 13a](https://svelte.dev/tutorial/classes) shows how to dynamically add and remove classes, including the special class directive like this:
```
<button class:active="{current === 'foo'}">foo</button>
```
I got a bit mixed up the first time I read this because I thought that `:active` was a [CSS `:active` pseudo-selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:active). I thought it might be a bit clearer to pick an example class name that does not coincide with any pseudo-class, so I've opened this PR to replace `active` with `selected`.
I have spun up the site locally and made sure that the example code still works, before and after clicking the 'Show me' button.
> site: Replace "active" with "selected" as an example class name

- site/content/docs/02-template-syntax.md
Addresses #5350 
Adds example of case where `$$props` can be useful. 
Adds similar optimization warning as `$$props` to `$$restProps`.
No tests, just docs.
> update docs for `$$props` and `$$restProps`

- src/runtime/internal/scheduler.ts
- test/runtime/samples/onmount-get-current-component/_config.js
- test/runtime/samples/onmount-get-current-component/main.svelte
Fixes #4899
Fixes #4259
This PR clears the current component after the update.  This has two effects:
* The lifecycle functions now raise an error when used outside of Svelte code (eg. in a setTimeout handler).  Previously, they operated on the last-updated component, which may not even be in a stable state.
* The lifecycle functions now raise an error when used inside onMount and afterUpdate.  If this is undesirable, we would need to explicitly call set_current_component in flush() again when calling the render callbacks.
This is essentially the same change as #4864, but that PR's unit test did not work correctly and left Svelte in an invalid state, causing many other unit tests to fail.
If any other unit tests or changes are needed, let me know and I'd be happy to work on them.
Closes …
> Fix current component not being cleared after component update

- src/runtime/internal/dom.ts
- test/runtime/samples/binding-input-number/_config.js
Fix #1701
Redo tests, but this case it cant be direct tested, only warning in browsers.
You can check this warnings in browser via [REPL](https://svelte.dev/repl/442cfd6a0b144afa92df765357c0911f?version=3.22.1)
If you set string or undefined to input-type-number binded variable browser show warning in devtools console. You need set number and then other "wrong" value to repeat warning
To check usecase, check [REPL](https://svelte.dev/repl/922cb0532c56400a94d95e8d4536e322) from 1701 issue, but look not to repl console, but browser console.
> Fix: input type number warning in browsers

- site/Makefile
- site/README.md
- site/package.json
It drives me crazy that the command is `npm run sapper` because it's different than all the other Sapper sites (the template, my own projects, the example projects), so my muscle memory always fails me.
> Standardize site building command

- site/content/tutorial/03-props/03-spread-props/text.md
Changed to "onto" because it is standard and more easily readable.
> Changed "on to" to "onto" in tutorial 03

- CHANGELOG.md
- src/compiler/compile/Component.ts
- src/compiler/compile/render_dom/Renderer.ts
- src/compiler/compile/render_dom/invalidate.ts
- test/runtime/samples/reactive-assignment-in-complex-declaration-with-store/_config.js
- test/runtime/samples/reactive-assignment-in-complex-declaration-with-store/main.svelte
- test/runtime/samples/reactive-assignment-in-declaration/main.svelte
- test/runtime/samples/reactive-assignment-in-for-loop-head/main.svelte
- test/runtime/samples/store-resubscribe-c/_config.js
- test/runtime/samples/store-resubscribe-c/main.svelte
Fixes #5388
Root cause: from https://github.com/sveltejs/svelte/pull/4069, we skip `$$invalidate` calls if the assignment happen at the main execution context, this skips the `subscribe_store` instrumentation as well.
> fix destructuring to get multiple stores

- CHANGELOG.md
- src/runtime/internal/await_block.ts
- test/runtime/samples/await-without-catch/_config.js
Fixes https://github.com/sveltejs/svelte/issues/5401
> await stuck indefinitely without catch

- site/src/routes/_layout.svelte
- site/src/routes/repl/[id]/index.svelte
#5325 an attempt to solve the Partially Obscured Scrollbar issue on svelte.dev
> Scrollbar fix

- site/content/blog/2019-04-15-setting-up-your-editor.md
Now that we have `Svelte for VS Code` we should mention it in the old blog post.
> Update editor recommendations of old blog post

- CHANGELOG.md
- src/compiler/compile/render_dom/invalidate.ts
- test/runtime/samples/reactive-assignment-in-complex-declaration-with-store-2/_config.js
- test/runtime/samples/reactive-assignment-in-complex-declaration-with-store-2/main.svelte
- test/runtime/samples/reactive-assignment-in-complex-declaration-with-store/main.svelte
Fixes #5449
disabled the test for SSR, which will be fixed via #5419
> handle destructure to a store value

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/runtime/samples/each-block-keyed-dyanmic-key/_config.js
- test/runtime/samples/each-block-keyed-dyanmic-key/main.svelte
> update keyed each when key expression changes

- CHANGELOG.md
- site/content/docs/02-template-syntax.md
- site/content/tutorial/05-events/03-event-modifiers/text.md
- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/render_dom/wrappers/Element/EventHandler.ts
- test/js/samples/event-modifiers/expected.js
- test/js/samples/event-modifiers/input.svelte
- test/validator/samples/event-modifiers-invalid-nonpassive/errors.json
- test/validator/samples/event-modifiers-invalid-nonpassive/input.svelte
- test/validator/samples/event-modifiers-invalid/errors.json
- Fixes #2068
- Fixes #5438
built on top of https://github.com/sveltejs/svelte/pull/5287
TODO:
> nonpassive event modifier

- src/runtime/internal/transitions.ts
To reproduce: Toggle Checkbox multiple times within a second
https://svelte.dev/repl/61d6a8c1cf8a4a819d40e44037617f44?version=3.24.1
- Current Behavior
When `running_program == null && pending_program != null` (This happens because `pending_program` has a delay) and **new program** comes, **new program** is assigned to `running_program` and old `pending_program` remains what it was. Eventually, **new program** will be stopped by `pending_program`. Notice that `pending_program` comes before **new program** but it intercepts new one.
- Solution
If `pending_program != null` and **new program** comes, `pending_program` should be assigned as **new program**
> fix: #4954 Delayed bidirectional transition prevents components from unmounting

- src/runtime/internal/utils.ts
The new typing for get_store_value introduced in 3.29.0 doesn't work and generates multiple ` Object is of type 'unknown'.` errors in our codebase.
See the `.D.TS` tab in [playground](https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAysD2AnCAeAKgPigXigbwCgooBnYAQ2AgC4o0CBfAgMwFcA7AY2AEt52oAcwjA4lVGgA0sKBAAeVdgBMSsBMnQYMAChK0YASlpp8RKMmCtEAkgDoy4xgU78ypdTTVJU7VgFsAIwhELFw8d3FaAEYAJgBmKCYXdjcHKhwhETEqXQ8DKAB6Aoj0nlUOAGt2eAB3AR4UqnIlKHhmKGAAC2h5SG4IFt9A4KA) to see that typescript thinks the return value is `unknown`.
Demo of the fix: [playground](https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAysD2AnCAeAKgPigXigbwCgooBnYAQ2AgC4o0CBfAgMwFcA7AY2AEt52oAcwjA4lVJgAUJWnCQSMASlpp8RKMmCtEAkgDoy4xgU78ypBMlmXU7VgFsARhERZceC+NoBGAEwBmKCZTdnNDKhwhETEqaRtFKAB6RM8InhIoOycXKAAdeESgA)
> fix: typing get svelte/store

- src/compiler/parse/state/tag.ts
- test/parser/samples/style-inside-head/input.svelte
- test/parser/samples/style-inside-head/output.json
If a `style` tag was not at the top level, the `end` property of it was empty. This is because the line `element.end = parser.index;` was missing for the `style` case in that changed code.
This fixes sveltejs/language-tools#586 and (very likely) fixes sveltejs/prettier-plugin-svelte#149
> Style tags that were not at top level were missing end attribute

- site/src/routes/index.svelte
Adds a svelte summit banner with a link to the youtube page. This banner only appears on the index page so as not to conflict with the REPL, etc. Should be relatively unobtrusive.
> site: add svelte summit banner with link

- src/compiler/compile/nodes/interfaces.ts
The link in the comment pointed to an anchor which didn't exist on the page, so I did a search on the anchor and found out the information had moved to a separate page.
- The manual test would be to go to the old link and see that it doesn't contain information about discriminating unions (fail) and then going to the new link and seeing that it does contain information about discriminating unions (success).
> Fixed outdated typescriptlang.org link in comment

- test/runtime/samples/this-in-function-expressions/_config.js
Fixed the last unused variable warning in the code. It will make lint fail when sveltejs/eslint-config#10 is merged.
> Preparing for adding unused warning to eslint config

- site/content/tutorial/04-logic/06-await-blocks/app-a/App.svelte
- site/content/tutorial/04-logic/06-await-blocks/app-b/App.svelte
The way the example is currently presented requires that the user have an understanding of how Javascript hoists functions. 
By moving the function declaration before the function reference, the order of the code becomes more clear to the reader, which I think is valuable here. 
I think it's more important that this material clearly teach the behavior of Svelte, rather than the nuances of Javascript.
> Move function declaration before reference

- .github/ISSUE_TEMPLATE/bug_report.md
Adds a big headline to stop people from submitting or asking svelte@next questions/bug reports. Not at all sure about the wording but I feel like it's probably a good idea to have something to the effect in there?
> Add svelte@next caveat to bug report template

- src/compiler/compile/render_dom/wrappers/shared/create_debugging_comment.ts
- test/runtime/samples/component-slot-slot/Component.svelte
- test/runtime/samples/component-slot-slot/Forward.svelte
- test/runtime/samples/component-slot-slot/_config.js
- test/runtime/samples/component-slot-slot/main.svelte
Fixed issue #5475 but is related to recently opened issue #5535 
The problem behind this was the create_debugging_comment function never finished in this case, for this reason the compiler never finished.
> Fixed issue 5475

- src/runtime/internal/lifecycle.ts
Changing the parameter of `onMount` etc to take a function rather than `any`. I accidentally passed an evaluated function rather than the function itself in my TypeScript Sapper project and that gave a runtime rather than a compile-time error.
If I understand it right, `types.d.ts` is created from this file which in turn is used by the Sapper type definitions.
> Only allow passing functions to lifecycle methods like onMount.

- src/compiler/compile/Component.ts
- src/compiler/compile/nodes/Binding.ts
- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/compiler/parse/index.ts
- src/compiler/parse/read/script.ts
- src/compiler/parse/state/mustache.ts
- src/compiler/utils/fuzzymatch.ts
- src/runtime/motion/spring.ts
- test/hydration/index.ts
Adds curly braces for multi-line statements
> Curly braces linting fixes

- package-lock.json
- package.json
The code changes were already checked in via https://github.com/sveltejs/svelte/pull/5585, so this just bumps the package to enforce the change
> Bump eslint-config to 5.5.0

- site/content/blog/2020-11-01-whats-new-in-svelte-november-2020.md
- new features & impactful bug fixes
- Svelte Summit Summary
- showcase
Feel free to comment with any feedback! Also, if folks have an opinion on how we should email this post, I'm happy to deprecate svelte.substack.com in favor of a more official mailing list (I can import my 200 or so subscribers 😄 ). See: https://github.com/sveltejs/svelte/issues/5578
> "What's new in Svelte" November newsletter

- README.md
Per the conversation [here](https://discord.com/channels/457912077277855764/750401468569354431/771757850178355230) this PR adds discord chat badge with the number of people online on discord.
Preview
> Update README.md: discord badge with members online

- src/compiler/compile/nodes/Animation.ts
- src/compiler/compile/nodes/EachBlock.ts
- test/validator/samples/animation-not-in-each/errors.json
- test/validator/samples/animation-not-in-keyed-each/errors.json
- test/validator/samples/animation-siblings/errors.json
This error message has a typo:
`An element that use the animate directive must be the immediate child of a keyed each block`
It should instead be 
`An element that uses the animate directive must be the immediate child of a keyed each block`
or maybe 
`Elements that use the animate directive must be the immediate child of a keyed each block`.
I decided on the former.
I'm not sure if this is worth the PR but it was bugging me
> fixed minor typo in each loop animation error

- site/content/docs/03-run-time.md
I also checked the other names of easing functions but found no other link to remove.
Thank you all for svelte !
<details>
<summary>PR checks (not applicable)</summary>
</details>
> docs: broken link to easing function

- site/content/blog/2019-04-16-svelte-for-new-developers.md
The link to the Svelte package was originally pointing to the npm home page; this change fixes it. 🙂
> Fix link to Svelte package on npm

- package.json
This PR is to fix the error that occurs when trying to `require ('svelte/register')` which was introduced when the exports field was added recently. The issue can be found at https://github.com/sveltejs/svelte/issues/5670
> Add register to exports

- site/static/prism.css
This partially resolves one of the Axe Accessibility violations listed in #5678: [Elements must have sufficient color contrast](https://dequeuniversity.com/rules/axe/4.0/color-contrast?application=AxeChrome) (2018 count). 
This reduces the number of color contrast violations from 2018 to 228. The colors for the syntax highlighting tokens were below the WCAG AA threshold of 4.5. This meant that people with low vision could have difficulty reading the text. Below is a list of contrast ratios for each token, before and after the change.
- base: was 4.26, now 7.21
- comment: was 2.8, now 5.23
- keyword: was 4.1, now 4.54
- function: was 4.31, now 4.5
- string: was 3.49, now 4.65
- number: was 2.84, now 4.89
Before:
After:
I adapted some of the colors from Eric Bailey's [accessible syntax …
> docs: increase syntax highlighting color contrast

- site/content/tutorial/06-bindings/12-bind-this/app-a/App.svelte
- site/content/tutorial/06-bindings/12-bind-this/app-b/App.svelte
The `callback` called via `requestAnimationFrame(callback)` already contains the timestamp in the first argument, calling `performance.now()` inside raf is not required.
> tutorial: remove unnecessary call performance.now() inside raf

- site/content/docs/03-run-time.md
The documentation implied `onDestroy` callbacks were run _after_ unmount, which is incorrect
https://github.com/sveltejs/svelte/blob/7c1e6a6ce7cce68f41a7628d6b59340673e05046/src/runtime/internal/Component.ts#L79-L81
https://svelte.dev/repl/504565b53a114603beaaa3680dc645f2?version=3.29.4
> Correct `onDestroy` behavior description

- src/compiler/utils/string_with_sourcemap.ts
Looks like the last PR had a `lint` issue because a new rule was added since the PR was originally created
> Fix eslint issue

- rollup.config.js
This PR adds the missing `walk` type to the `compiler.d.ts` file.
> fix: add mising type in compiler.d.ts

- site/content/docs/03-run-time.md
- src/runtime/internal/lifecycle.ts
Provides a safe way to check whether a key has been assigned in the context
> Add hasContext lifecycle function

- src/runtime/internal/transitions.ts
The compiler usually skips the last two arguments of `transition_out`
https://svelte.dev/repl/4d97f6be1ef14dc7b814903790d49afc?version=3.29.4
> Make unused `transition_out` parameters optional

- src/compiler/preprocess/index.ts
- test/sourcemaps/samples/source-map-generator/_config.js
- test/sourcemaps/samples/source-map-generator/input.svelte
- test/sourcemaps/samples/source-map-generator/test.js
> add: import decoded sourcemaps from SourceMapGenerator

- site/content/blog/2020-12-01-whats-new-in-svelte-december-2020.md
- new features & impactful bug fixes across svelte and sapper
- link to the "what's up with sveltekit" post
- showcase
Feel free to comment with any feedback! Still waiting on a 👍 to transition to a more official/community email service: https://github.com/sveltejs/svelte/issues/5578
> "What's new in Svelte" December newsletter

- site/content/blog/2017-08-07-the-easiest-way-to-get-started.md
The erstwhile service named 'ZEIT now' is now called 'Vercel'. This rename would make this quickstart more accurate. Source: https://vercel.com/blog/zeit-is-now-vercel
> Renamed 'Now' to 'Vercel'

- site/content/tutorial/04-logic/05-keyed-each-blocks/app-a/App.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/app-b/App.svelte
The Svelte tutorial is very well written but I was stumped in one particular chapter: [Keyed each blocks](https://svelte.dev/tutorial/keyed-each-blocks). Here it explains Svelte's behaviour when looping through an array of objects using an each block.
This was a bit tricky to understand for beginners and the hex colour codes did not make things easy, so I looked for the nearest named colours to the hex code present in the tutorial, this would enable new learners to visualize and understand the reactive behaviour here. 
For instance `#0d0887` being removed from the UI is hard to track for humans, whereas  understanding `indigo` being removed from the UI is exponentially easier.
I hope this fixes #5760  to some extent.
> Changing hex codes to colour names to improve readability of the tutorial.

- site/content/examples/03-logic/04-keyed-each-blocks/App.svelte
As discussed in PR #5761 , using colour names instead of hex codes improves readability of these examples.
It is easier to visualize gold, it isn't as easy to visualize `#fca636`, hence this minor fix.
> changed to colour names instead of hex codes for readability

- site/content/docs/02-template-syntax.md
The sentence, "`@debug` accepts a comma-separated list of variable names (not arbitrary expressions)" is repeated a few lines below, where it's accompanied by an example showing how variable names are accepted but expressions are not. Since they're back to back, it reads as redundant (imo).
> Remove duplicate sentence

- package-lock.json
- package.json
Just a bit of housekeeping. Sticking with the 3.x series for now
> Bump TypeScript version

- site/src/server.js
Not sure that we have any tests for `/site` aside from the slugger.
- Closes #5820
> fix(site): ensure "text/plain" on error response

- site/content/examples/12-svg/02-bar-chart/App.svelte
- site/content/examples/12-svg/03-area-chart/App.svelte
This changes the formatMobile function to account for the aughts in the two "chart" SVG examples (I mistakenly called them graphs in my branch name. I'm not sure I actually know the difference.) In the current version '2000' and '2005' are abbreviated to '0 and '5 instead of '00 and '05. Not the most pressing issue, but this is my first open source pull request so I was excited.
> Fix formatMobile to account for aughts

- site/src/routes/blog/index.svelte
- site/src/routes/docs/index.svelte
- site/src/routes/examples/index.svelte
- site/src/routes/index.svelte
- site/static/global.css
This resolves one of the Axe accessibility violations listed in #5678: [Page must contain a level-one heading](https://dequeuniversity.com/rules/axe/4.0/page-has-heading-one?application=AxeChrome)
Several pages on the site were missing h1 elements. Without this element, it's more difficult for screen readers to jump to the main content of the page.
In order to not affect how the page looks, I applied a class to the headings to hide them visually but still allow them to be accessed by assistive tech.
> site a11y: add missing h1s

- site/content/blog/2021-01-01-whats-new-in-svelte-january-2021.md
- notes on the svelte + sapper changelogs since the last newsletter
- a reminder about sveltekit development progress and how to try it
- showcase (lots of awesome stuff this month)
Feel free to comment with any feedback! If you've got opinions on how best to integrate these posts into a more official/community email service, check out this issue: https://github.com/sveltejs/svelte/issues/5578
> "What's new in Svelte" January newsletter

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/js/samples/each-block-keyed-animated/expected.js
- test/js/samples/each-block-keyed/expected.js
- test/runtime/samples/transition-js-each-outro-cancelled/_config.js
- test/runtime/samples/transition-js-each-outro-cancelled/main.svelte
Fixes #5829
~~- [] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs~~
> keep each block value

- CHANGELOG.md
- src/compiler/compile/nodes/Action.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/nodes/shared/is_contextual.ts
- src/compiler/compile/render_dom/wrappers/shared/add_actions.ts
- test/runtime/samples/deconflict-contextual-action/_config.js
- test/runtime/samples/deconflict-contextual-action/main.svelte
- test/runtime/samples/deconflict-contextual-action/util.js
> deconflict variable for action and each block

- site/content/blog/2017-08-07-the-easiest-way-to-get-started.md
- site/src/routes/index.svelte
Info about TypeScript has been added to:
- start page (/)
- quick staret guide (/blog/the-easiest-way-to-get-started)
> Make TypeScript integration more visible

- .gitattributes
linguist scans the repository and selects the programming language to display.
This PR advises linguist to not look into `/site` and `/test`.
Now linguist selects TypeScript.
resolves issue #4284
Test: https://github.com/baslr?tab=repositories&q=svelte&type=&language= https://github.com/baslr/svelte
> change detected language to TypeScript

- src/compiler/preprocess/index.ts
- src/compiler/utils/string_with_sourcemap.ts
- test/sourcemaps/index.ts
- test/sourcemaps/samples/attached-sourcemap/_config.js
- test/sourcemaps/samples/attached-sourcemap/input.svelte
- test/sourcemaps/samples/attached-sourcemap/test.js
solve issue https://github.com/sveltejs/svelte-preprocess/issues/286
allow preprocessors to return sourcemaps not only in `result.map`
but also attached to `result.code` as 'magic comment' in script or style
```js
var code = 'here';
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW ... vgICB9XG4iXX0= */
```
or in script
```js
var code = 'here';
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW ... vgICB9XG4iXX0=
```
the attached sourcemap is removed, so the browser does not double-parse the sourcemap
that was the original problem in issue 286
this removal is asserted by the test
for now, support only one sourcemap, either in `result.map` or attached to `result.code`, not both --> fatal error
also for now, this works only for `script` and `style` preprocessors
in …
> add: parse attached sourcemap from preprocessor

- src/compiler/compile/Component.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/preprocess/decode_sourcemap.ts
- src/compiler/preprocess/index.ts
- src/compiler/preprocess/replace_in_code.ts
- src/compiler/preprocess/types.ts
- src/compiler/utils/mapped_code.ts
I found the code in the `preprocess` package a bit tangled. There was mutation happening in unexpected places and it was hard to see the data flow and dependencies.  The `index.ts` was 300 lines which felt like too much. I found some of the variable and function names confusing.
I renamed a lot of stuff and restructured many of the functions. The `process` function now has a fairly clear structure and the mutations are all in `PreprocessResult`. I broke out everything related to search-and-replace with sourcemaps into `replace_in_code.ts` to reduce the length of `index.ts` to around 200 lines.
The diff is hard to read; it's probably better to just jump into the `preprocess` package and read it.
There should be no changes in behavior from these changes.
(the original impetus here was …
> Refactored preprocess for readability

- site/content/docs/02-template-syntax.md
I had a slightly difficult time following the slot documentation because it used a component and then later defined it. I think it'd be clearer to first show the component and then show it being used
> docs: define component before demonstrating usage

- src/runtime/store/index.ts
**Before**
- Using `derived(store, (value, set) => {})` fails to infer the parameters of the second function (it infers them as `any` which seems to indicate it picked the simpler signature where the function only has one parameter)
- All other forms compile fine, even the one with the set param and a start value.
**After**
- All combinations compile and infer properly.
I just swapped the order of the two declarations, now forcing TS to consider the more complex signature first.
PS: Have you considered progressively rewriting the tests in typescript to catch these kinds of issues?
Cheers
> Swap the order of the two derived store signatures to fix TS inference

- src/compiler/parse/state/tag.ts
- test/parser/samples/error-empty-classname-binding/error.json
- test/parser/samples/error-empty-classname-binding/input.svelte
Fixes #5858: Class binding name cannot be empty
Includes a test that fails without this patch.
---
@tanhauhau I completely messed up when pushing the review patch to the last PR, so I closed it, and re-forked svelte completely. The changes you requested are included in this PR.
> Fixes #5858: Class binding name cannot be empty

- CHANGELOG.md
- src/runtime/animate/index.ts
- src/runtime/transition/index.ts
They are not needed for most of the functions and should be marked as optional accordingly to make TypeScript users happy.
Fixes https://github.com/sveltejs/language-tools/issues/785
> Make animation/transition params optional

- CHANGELOG.md
- src/runtime/internal/dev.ts
Add `$$events_def` and `$$slot_def` so that TS users can do
```
let el: SvelteComponent;
<SomeComponent bind:this={el} />
```
Without type errors.
Without this change, TS complains that `$$events_def` and `$$slot_def` is missing from `SvelteComponentDev` and therefore cannot be assigned to it.
> More forgiving SvelteComponentDev typings

- CHANGELOG.md
- src/compiler/compile/render_ssr/index.ts
- test/runtime/samples/reactive-assignment-in-complex-declaration-with-store-3/_config.js
- test/runtime/samples/reactive-assignment-in-complex-declaration-with-store-3/main.svelte
- test/runtime/samples/reactive-assignment-in-complex-declaration-with-store-3/store.js
- test/server-side-rendering/index.ts
> fix remove extra store subscription statement

- site/src/routes/_error.svelte
The colour on broken pages have `#da106e` and is not a part of `theme-default` in [site-kit](https://github.com/sveltejs/site-kit/blob/master/base.css#L33).
Also `#676778` is easy on the eyes.
Before
After
> Change color on 404 page; Update to _error.svelte

- CHANGELOG.md
- src/compiler/compile/css/Selector.ts
- test/css/samples/host/_config.js
- test/css/samples/host/expected.css
- test/css/samples/host/input.svelte
- test/css/samples/siblings-combinator-global/_config.js
- test/css/samples/siblings-combinator-global/expected.css
- test/css/samples/siblings-combinator-global/input.svelte
Another poke on fixing css scoping issues:
Fixes #5499, Fixes #5946
> fix :host and :global css scoping

- .editorconfig
I removed not needed rule from editorconfig. Indent size is not overwritten anywhere so there is no need to repeat this line for configuration files like
> remove unnecessary indent_size rule from .editorconfig

- check_publish_env.js
- package.json
This is a horrible solution but I don't know what else to do now that will maintain the `prepare` script, maintain the separate quick build and bundled/REPL-compatible for-publishing build, and also work on Windows.
This adds another step to `prepublishOnly` which ensures that `PUBLISH` is already set. If you set it yourself, then it will still be inherited by the extra `prepare`-triggered build, and so the good build we want to publish won't be clobbered by a bad build.
Works around #5662, but I would want to keep that issue open even if this were merged.
> work around publishing issue with npm v7

- CHANGELOG.md
- src/compiler/compile/Component.ts
- test/runtime/samples/store-shadow-scope-declaration/_config.js
- test/runtime/samples/store-shadow-scope-declaration/main.svelte
This PR fix for the following error:
```svelte
<script>
function test(store) {
// should not error when declaring the parameter as `$store`
return derived(store, $store => {
});
}
</script>
```
> no warning on contextual-store if declaring it as a parameter / variable

- CHANGELOG.md
- src/compiler/compile/nodes/AwaitBlock.ts
- src/compiler/compile/nodes/EachBlock.ts
- src/compiler/compile/nodes/shared/Context.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/render_dom/Block.ts
- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/runtime/samples/each-block-destructured-default-before-initialised/_config.js
- test/runtime/samples/each-block-destructured-default-before-initialised/main.svelte
- test/runtime/samples/each-block-destructured-default-binding/_config.js
- test/runtime/samples/each-block-destructured-default-binding/main.svelte
- test/runtime/samples/each-block-destructured-default/_config.js
- test/runtime/samples/each-block-destructured-default/main.svelte
Fixed #5066
Continued from https://github.com/sveltejs/svelte/pull/5230, added support to refer to other variables, besides destructured params, and more tests
> allow destructured defaults to refer to variables

- site/content/docs/04-compile-time.md
- src/compiler/compile/Component.ts
- src/compiler/compile/css/Stylesheet.ts
- src/compiler/compile/index.ts
- src/compiler/interfaces.ts
- test/css/samples/custom-css-hash/_config.js
- test/css/samples/custom-css-hash/expected.css
- test/css/samples/custom-css-hash/input.svelte
#4377, with [this change](https://github.com/sveltejs/svelte/pull/4377#issuecomment-786042286)
> add cssHash option

- site/content/faq/110-where-can-i-get-support.md
Related to the discussion in #6035
> Add "Where can I get support?" to FAQ

- site/content/blog/2021-03-01-whats-new-in-svelte-march-2021.md
Ready to review! Lots of awesome stuff this month :)
> "What's new in Svelte" March newsletter

- site/content/examples/20-7guis/01-7guis-counter/App.svelte
- site/content/examples/20-7guis/02-7guis-temperature/App.svelte
- site/content/examples/20-7guis/03-7guis-flight-booker/App.svelte
Some of the links in the 7GUIs examples were pointing to an outdated wiki page. This PR updates those links and moves them to the top of the file for consistency.
The timer, CRUD, and circles examples were already pointing to the correct location.
> docs: update 7GUIs example links

- site/content/faq/700-is-there-a-component-library.md
Currently the FAQ points to the older, unmaintained Svelte Community site for help finding UI libraries.
This PR links the new Svelte Society site and changes the wording slightly to imply you can also find standalone components there.
> Link  Svelte Society instead of old Community site

- src/runtime/store/index.ts
close https://github.com/sveltejs/eslint-plugin-svelte3/issues/102
> chore: mark nest method `this: void` for destructing safely

- src/runtime/motion/spring.ts
- src/runtime/motion/tweened.ts
Closes issue 'Export Spring interface #6070' by exporting Spring and Tweened.
> Export interfaces Spring and Tweened

- src/runtime/transition/index.ts
Just adds a bit of convenience when you want to define a custom transition, you could simply import `EasingFunction` to use as the type of the `easing` parameter of your transition function if you have one, rather than having to duplicate it in your own code.
> Export the EasingFunction type

- src/runtime/transition/index.ts
TypeScript interfaces for transitions params are currently not exported. This PR exports them.
I couldn't find any tests related to this, so I've not made any changes to the tests.
This closes #5207.
> Export interfaces for transition params

- CHANGELOG.md
- src/compiler/compile/Component.ts
- src/compiler/compile/nodes/Binding.ts
- src/compiler/compile/nodes/shared/Context.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/utils/clone.ts
- test/parser/samples/slotted-element/input.svelte
- test/parser/samples/slotted-element/output.json
- test/parser/samples/textarea-children/output.json
This fixes #6066. It has as a casualty the normalization in the returned AST of `<textarea>foo</textarea>` => `<textarea value='foo'/>` which seems like an acceptable loss.
> fix missing slotted elements in AST

- site/src/routes/tutorial/[slug]/index.svelte
Before | After
-------|-------
I think it goes mostly unnoticed as it's of low contrast with the grey surroundings but it sure is out of place.
> Tutorial: remove outline on scrollbar thumb

- .github/workflows/ci.yml
Many CI workflows have been failing because they timeout. This PR adds cache to the CI.
However this only caches ~/.npm and not node_modules as *it's not recommended* (https://github.com/actions/cache/blob/main/examples.md#node---npm). That includes the main culprit which is Chromium being downloaded on each run.
None of my test runs, that used cache, failed due to timeout.
If this gets merged, it should probably also be ported to Sapper.
> ci: cache npm directory

- CHANGELOG.md
- site/content/docs/03-run-time.md
- src/runtime/internal/Component.ts
- src/runtime/internal/ssr.ts
- src/runtime/tsconfig.json
- test/runtime/samples/constructor-pass-context/Component.svelte
- test/runtime/samples/constructor-pass-context/_config.js
- test/server-side-rendering/index.ts
This allows passing in context through the Svelte Component Constructor API
```js
import Component from './Component.svelte';
const context = new Map();
map.set('a', 123);
map.set('b', 456);
new Component({
target: document.body,
context: context,
});
```
> allow passing in context in constructor

- site/content/blog/2021-04-01-whats-new-in-svelte-april-2021.md
Mentions SvelteKit + Slots. Would love some help writing these descriptions, since slots are still pretty confusing to me xD
> "What's new in Svelte" April newsletter

- src/runtime/store/index.ts
Add an additional overload for `derived` to allow explicitly setting an initial value for non-async derived stores.
After a long overdue svelte version update, I started getting some type errors on any non-async derived store that I had explicitly set an initial value. For example, 
```ts
export const isSlow = derived(delta, ($delta) => $delta > 300, false);
```
Perhaps the correct way to handle the initial value is through the initial values of the stores that it is derived from, but I guess it feels safer to me to also explicitly set it on the derived store.
Assuming that this usage is acceptable then the additional overload keeps typescript happy. 😄 
> Add additional function overload for derived

- site/content/docs/02-template-syntax.md
This PR updates the [docs](https://svelte.dev/docs#svelte_self) for `<svelte:self>` to mention that it can also be placed in a component's slot.
This was merged as part of #4532 but it doesn't look like the docs were updated.
> docs: mention that <svelte:self> can be in a slot

- .github/workflows/ci.yml
After submitting my first two PRs, I noticed that Github Checks sometimes breaks because of a timing issue.
Most of the time, this is due to one this two jobs:
- `CI / Tests (8, windows-latest) (pull_request)`
- `CI / Unit (macOS-latest) (pull_request)`
This is frustrating because you never know if you breaks something or if it's a timing issue.
Increase the timing on Github Actions.
I added 5 minutes to both `Tests` and `Unit` jobs.
I also increased `Lint` to set the timeout at `5` to be sure that we will never run into this issue with this job.
Are you OK with these new timings?
Thanks
> ci: increase timeouts to avoid random breaks

- CHANGELOG.md
- src/runtime/internal/Component.ts
- src/runtime/internal/dom.ts
Closes https://github.com/sveltejs/svelte/pull/5623. This is that PR rebased with logging removed. Thanks to @jonatansberg for paving the way on this!
This PR improves SSR hydration performance through minimizing DOM mutations during hydration by avoiding de- and reattaching nodes during hydration. This should fix #1067, fix #4308, fix #5108, and fix #4975.
In order for this to work I added a new new "hydration mode". This way it's possible to maintain the detach by default behavior during hydration without modifying the generated component output. There might be better ways to do this if we reconsider fragment creation (as suggested in #3898 and #4219) but that would be a significant undertaking.
The existing append, insert and detached methods have been modified to track which nodes are …
> Improve SSR hydration performance

- site/content/tutorial/05-events/06-dom-event-forwarding/app-a/CustomButton.svelte
- site/content/tutorial/05-events/06-dom-event-forwarding/app-b/CustomButton.svelte
The color contrast between the current `CustomButton`'s `background-color` (#aaa) and `color`/`border-color` (#f1c40f) does not meet the minimum WCAG criteria. It fails the WCAG AA Standard with a contrast ratio of 1.4.
Since it's kind of hard to meet the contrast ratio standard by keeping a vibrant yellow color (similar to the current one) and a light background, I consider it better to switch the yellow color for an orange/tan color (similar to the Svelte color) and a lighter background color, so it passes WCAG AA.
> fix custombutton colors for a11y contrast

- CHANGELOG.md
- src/runtime/internal/dev.ts
Added missing "context" typing on `SvelteComponentDev` and `SvelteComponentTyped` options
```javascript
new Component({
target:parent,
context: { // throws error on typescript
key: value
}
})
```
> Add "context" typing on SvelteComponent options

- src/compiler/compile/nodes/Element.ts
- test/runtime/samples/attribute-casing-foreign-namespace-compiler-option/_config.js
- test/runtime/samples/attribute-casing-foreign-namespace-compiler-option/main.svelte
Prevents unwanted namespace change inside of foreign namespaces for element names matching those in svg's namespace  #6257 
which breaks svelte-nodegui
> Don't auto change to svg namespace when in foreign namespace

- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- src/runtime/internal/await_block.ts
- test/runtime/samples/await-with-update-catch-scope/_config.js
- test/runtime/samples/await-with-update-catch-scope/main.svelte
Fix await block scope issue during update (#6173). During the update, the `child_ctx` passed into await block branch is mutated no matter the state of the await block. This normally won't cause any issue. But when the `error` or the `value` of the await block is shadowing some instance variable. It would cause a scope issue. 
For example, in this [repo](https://svelte.dev/repl/8aa621af75574acd8d4c041517dee038?version=3.37.0)
The error variable is overridden by the resolved result.
As for the error in #6173, It is because the error variable has also been overridden. Thus it would try to render the non-exist if block.
The solution I come up with is to only update `child_ctx` with the index of the current await …
> Fix await block scope issue when update

- src/compiler/compile/nodes/InlineComponent.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/compiler/compile/render_ssr/handlers/InlineComponent.ts
- test/helpers.ts
- test/runtime-puppeteer/assert.js
- test/runtime-puppeteer/index.ts
- test/runtime-puppeteer/samples/component-css-custom-properties-dynamic/Slider.svelte
- test/runtime-puppeteer/samples/component-css-custom-properties-dynamic/_config.js
- test/runtime-puppeteer/samples/component-css-custom-properties-dynamic/main.svelte
- test/runtime-puppeteer/samples/component-css-custom-properties/Slider.svelte
- test/runtime-puppeteer/samples/component-css-custom-properties/_config.js
- test/runtime-puppeteer/samples/component-css-custom-properties/main.svelte
- test/server-side-rendering/index.ts
Fixes #5628
Unable to test the runtime using JSDOM, because JSDOM does not apply css custom properties (ref: https://github.com/jsdom/jsdom/issues/1895), so I added the runtime test case using puppeteer.
I created a `runtime-puppeteer` folder for runtime test case to be run with puppeteer. The test samples follow the format of the `runtime` tests, ie: configurable via the `_config.js` file
> Implement RFC 13 Passing CSS custom properties to components

- src/runtime/internal/dom.ts
- test/custom-elements/samples/props/main.svelte
- test/custom-elements/samples/props/my-widget.svelte
- test/custom-elements/samples/props/test.js
Fixes #5951 
When given a standalone boolean attribute on a custom element, the compiler was setting the corresponding property to empty string, which is falsy. This made it seem as the property was not being applied.
For example, using the following in a Svelte template sets the `raised` property of the mwc-button custom element to `''`. Instead, it should be set to `true`. 
```html
<mwc-button raised />
```
With this change, the compiler will set boolean properties on custom elements to true when no value is provided.
> Properly set boolean attributes on custom elements

- src/runtime/transition/index.ts
It would be nice to mark the `fallback` param of the `crossfade` function from `"svelte/transition"` as optional to avoid passing an empty function when no fallback is desired.
before:
``` ts
const [send, receive] = crossfade({
duration: 600,
fallback: () => ({}),
});
```
after:
``` ts
const [send, receive] = crossfade({ duration: 600 });
```
I think this was also intended by the author because there is already a null check for `fallback`.
`return fallback && fallback(node, params, intro);`
> make crossfade fallback param optional

- src/runtime/internal/dom.ts
- test/hydration/samples/claim-text/Component.svelte
- test/hydration/samples/claim-text/Layout.svelte
- test/hydration/samples/claim-text/_after.html
- test/hydration/samples/claim-text/_before.html
- test/hydration/samples/claim-text/main.svelte
> fix claim_text

- site/content/blog/2021-05-01-whats-new-in-svelte-may-2021.md
"Working toward SvelteKit 1.0 and a showcase full of SvelteKit sites!"
I left a "draft" section at the top for "Svelte Compiler Updates" since there's a few changes in the changelog that I'm not sure will make it in a release by May 1. Happy to remove it, if that's the case :)
> "What's new in Svelte" May newsletter

- site/content/tutorial/19-next-steps/01-congratulations/text.md
Maybe this is intentional and the Svelte team prefers to wait until the stable v1.0 version is released, I'm just opening this PR to keep track of this as I haven't found any existing issue or PR mentioning it.
Haven't run any tests as it's just a simple markdown change.
> [Tutorial] Update Chapter 19 to reference Svelte Kit

- site/content/tutorial/16-special-elements/07-svelte-options/text.md
<svelte:options> is not the last lesson in "Special Elements". So, I removed the word "Lastly" and changed the copy to reflect that.
> Update <svelte:options> copy

- site/content/tutorial/06-bindings/10-media-elements/text.md
Fix typo in instructions on https://svelte.dev/tutorial/media-elements
Video element is not on line 116, it's on line 58 - looks like instructions don't reflect changes to previous .svelte refactor
> [ Typo] Tutorial instructions refer to wrong line number in code

- site/scripts/get-contributors.js
The GitHub contributors API appends `[bot]` to the login of bot users. This caused Dependabot to be linked as https://github.com/dependabot[bot] instead of https://github.com/dependabot in the contributors list. Because normal users cannot have `[bot]` in their name, it can just be removed entirely.
> site: filter out bot contributors

- site/content/docs/02-template-syntax.md
This confusion comes up from time to time, most recently in #6346 . This tries to clarify that `@html` is not some magic on-the-fly compiler.
> Docs: Clarify that `@html` does not compile Svelte code

- site/content/tutorial/04-logic/05-keyed-each-blocks/app-a/App.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/app-a/Thing.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/app-b/App.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/app-b/Thing.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/text.md
Fixes #6357 
The Tutorial page for Keyed Each Blocks was quite a challenge to parse, and I’m coming from React and Vue, where Keys are already a familiar concept. I genuinely thought the Svelte tutorial was trying to describe some other issue. I suspect that somebody using Svelte as their first framework would be confused too.
**In brief,   I think the demo is not good at illustrating the bug (and consequently, the need to use Keys).**
I've left more info in the issue description.
My solutions in this PR:
1. Make something closer to a real-world use case, so Expected Behaviour will be more intuitive. For example, deriving a variable from a prop by using a lookup, rather than directly reassigning it.
2. Use a clear sequence of objects (e.g. alphabetized words)
3. Make an intuitive match …
> docs: update Keyed Each Blocks tutorial

- site/content/docs/02-template-syntax.md
This PR adds an extra clarification to `<svelte:window>`, `<svelte:head>` and `<svelte:body>` that these elements can only appear at the top level of the component.  (see the contrast with `<svelte:self>` which **should not** appear as a top level element).
> Clarify that certain special elements have to be top level

- site/content/docs/02-template-syntax.md
I think the title of this section is a bit confusing, since `<slot let:name={value} />` is not actually the correct syntax
> Docs: Rename slot let section

- site/content/tutorial/06-bindings/09-each-block-bindings/text.md
The chapter highlights event binding in `each` block which is missing within the snippet. Thus it seems reasonable to include it within the description snippet block.
> Tutorial: Description fix - each block bindings

- CHANGELOG.md
- src/runtime/internal/dev.ts
A recent refactoring commit where the constructor definition was moved to an interface disconnected the props relationship of the props that are passed in the constructor and the instance props
> Fix generic props relationship in SvelteComponentTyped

- site/src/components/ScreenToggle.svelte
Going through the Svelte tutorial, I noticed that on mobile devices the buttons `Tutorial/Input/Output` buttons didn't have the proper text alignment on them.
This PR intends to fix that by providing the same `line-height` as the `button height` and changing the `padding` so slightly so we have the same room above and below the `text`.
Closes #6393 
| Before 😞 | After 🤯 |
| - | - |
| <img width="338" alt="Screenshot 2021-06-09 at 19 33 00" src="https://user-images.githubusercontent.com/30603437/121411266-5c23f780-c95b-11eb-9f7a-a9b6243fcf70.png"> | <img width="336" alt="Screenshot 2021-06-09 at 19 33 25" src="https://user-images.githubusercontent.com/30603437/121411284-5f1ee800-c95b-11eb-8537-575cb72860d0.png"> | 
-  [x] Run the tests with `npm test` and lint the project with `npm run …
> [Site:Tutorial] On mobile devices, the text on the tutorial buttons isn't properly aligned with the buttons' box

- site/content/blog/2016-11-26-frameworks-without-the-framework.md
- site/content/blog/2017-12-31-sapper-towards-the-ideal-web-app-framework.md
- site/content/blog/2019-04-22-svelte-3-rethinking-reactivity.md
- site/content/blog/2020-10-01-whats-new-in-svelte-october-2020.md
- site/content/blog/2020-11-01-whats-new-in-svelte-november-2020.md
- site/content/blog/2020-12-01-whats-new-in-svelte-december-2020.md
- site/content/blog/2021-01-01-whats-new-in-svelte-january-2021.md
- site/content/blog/2021-02-01-whats-new-in-svelte-february-2021.md
- site/content/blog/2021-03-01-whats-new-in-svelte-march-2021.md
- site/content/blog/2021-04-01-whats-new-in-svelte-april-2021.md
Some of the blog posts have invalid YAML in their frontmatter. `:` has special meaning in YAML. This was not a problem in the past because we were parsing the YAML ourselves and our 'parser' did not care. This is a problem for a full YAML parser.
It is fixed in this PR.
> docs: make yaml frontmatter in blogs valid

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/RawMustacheTag.ts
- src/compiler/compile/render_ssr/handlers/Element.ts
- src/compiler/compile/render_ssr/handlers/HtmlTag.ts
- src/runtime/internal/dom.ts
- test/js/samples/each-block-changed-check/expected.js
- test/runtime/index.ts
- test/runtime/samples/attribute-boolean-indeterminate/_config.js
- test/runtime/samples/attribute-casing-foreign-namespace-compiler-option/_config.js
- test/runtime/samples/attribute-casing-foreign-namespace/_config.js
- test/runtime/samples/attribute-dynamic-type/_config.js
- test/runtime/samples/binding-this-each-block-property-2/_config.js
- test/runtime/samples/component-namespaced/_config.js
- test/runtime/samples/component-namespaced/components.js
- test/runtime/samples/component-namespaced/components.svelte
- test/runtime/samples/component-namespaced/main.svelte
- test/runtime/samples/deconflict-builtins-2/_config.js
- test/runtime/samples/deconflict-builtins-2/main.svelte
- test/runtime/samples/each-block-keyed-dyanmic-key/_config.js
- test/runtime/samples/if-block-conservative-update/_config.js
- test/runtime/samples/if-block-else-conservative-update/_config.js
- test/runtime/samples/lifecycle-render-order-for-children/_config.js
- test/runtime/samples/lifecycle-render-order/_config.js
- test/runtime/samples/noscript-removal/_config.js
- test/runtime/samples/ondestroy-deep/_config.js
- test/runtime/samples/raw-anchor-first-child/_config.js
- test/runtime/samples/raw-mustaches/_config.js
- test/runtime/samples/reactive-function-called-reassigned/_config.js
- test/runtime/samples/store-unreferenced/_config.js
When running runtime (hydration) test, we are expecting the component to create the DOM while failing to claim elements from HTML.
This may fail to surface bugs such as hydrated DOM different from client rendered DOM.
Fixes:
- claiming `HtmlTag` element
- hydrating extra attributes from SSR
Not fixed for now:
- claiming `HtmlTag` in head
> Use SSR rendered as initial html for runtime hydration test

- src/runtime/internal/Component.ts
- src/runtime/internal/dom.ts
- test/hydration/samples/head-meta-hydrate-duplicate/_after_head.html
(Hopefully) Closes #4308.
I am new to working with Svelte so I apologize for any errors beforehand.
I tried to improve https://github.com/sveltejs/svelte/pull/6204 based on the thread #4308. I personally had problems with elements with CSS animations flickering due to hydration detaching and reattaching nodes (implicitly by re-inserting them) as described in the thread. The page that I was having problems with was almost entirely static, so seeing all the static nodes refresh went against my intuition as to how hydrate would work. So I looked into how this situation could be improved.
_Edit:_ The algorithm has been improved significantly. See https://github.com/sveltejs/svelte/pull/6395#issuecomment-858543236 for the new algorithm
During hydration, this new implementation tries to pick a …
> Improve hydration by reordering optimally

- src/compiler/compile/css/Selector.ts
- test/validator/samples/css-invalid-global-placement-2/errors.json
- test/validator/samples/css-invalid-global-placement-2/input.svelte
Hi,
in PR, https://github.com/sveltejs/svelte/pull/6223/files#diff-145a1fa56c966be609d17f4af6eb9c2a0a97cd2f1c9c86bf64841595f254f51dR597, an additional check was introduced to make sure the number of selectors is equal to 1, however this also covers pseudo elements which in turn break some of the existing capabilities as describe in https://github.com/sveltejs/svelte/issues/6306
```
.container :global(section) > :global(*):first-child {
color: red;
}
```
```global(*):first-child``` is no longer considered as a global where previously it was considered.
Thus, adding a negation check that if there is a ```ClassSelector```, it should be excluded from ```global``` check.
cc: @tanhauhau (PR https://github.com/sveltejs/svelte/pull/6223 author)
> fix: global with pseudo element should be considered as global

- site/content/docs/04-compile-time.md
…, which is used since 3.30
additional thoughts:
- The markup example is altered for brevity (replaces first occurence of foo instead of all), is that ok?
- should the style example be updated with map support too? (and maybe simplified to a generic example given that sass is covered by svelte-preprocess)
cc @dummdidumm, @kaisermann
> docs: update documentation for preprocessor sourcemap output

- site/content/docs/05-accessibility-warnings.md
List out all the accessibility warnings there is currently available.
I copied most of the description from https://github.com/jsx-eslint/eslint-plugin-jsx-a11y
Seemed to be useful to include [accessibility guidelines from WCAG](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/alt-text.md#accessibility-guidelines), should we add that too?
> list out all accessibility warnings in the docs

- site/content/docs/01-component-format.md
Fixes #6269
This PR adds documentation for the newly-implemented compound :global selector, e.g. `p:global(.red)`. I followed how `div :global(strong)` was documented and updated the code block in the docs.
Let me know if you think this change needs more documentation, or if the code block is enough.
> Add docs for compound :global selector

- src/runtime/internal/dev.ts
- src/runtime/internal/dom.ts
This is a small change to allow svelte events emitted in dev mode to bubble. In Svelte DevTools adding the listener to document before any svelte code executes is challenging. The current approach, while it works most of the time, fails in some cases such as when the svelte bundle is especially small. Having the events bubble allows me to add the listener to window instead of document which can happen much soon in the page life cycle.
In short: this change allows the Svelte DevTools bootstrapping code to be simpler and more robust.
> Bubble svelte dev events

- site/content/tutorial/15-context/01-context-api/text.md
> doc: Add notes to stress call-during-initialisation

- site/content/tutorial/06-bindings/14-component-this/app-a/App.svelte
- site/content/tutorial/06-bindings/14-component-this/app-a/InputField.svelte
- site/content/tutorial/06-bindings/14-component-this/app-b/App.svelte
- site/content/tutorial/06-bindings/14-component-this/app-b/InputField.svelte
- site/content/tutorial/06-bindings/14-component-this/text.md
Adds a tutorial step related to using `bind:this` with component instances as described in #5008
> Add tutorial for component binding

- site/content/tutorial/02-reactivity/01-reactive-assignments/app-b/App.svelte
- site/content/tutorial/02-reactivity/01-reactive-assignments/text.md
Replacing "handleX" with a more specific name that describes what the function does. This is to follow the "clean coding" best practice of naming functions by what they do.  In this case "incrementCount". It is much cleaner to know what a function does, and not relevant to know what triggered it to run.
For example, if later on I want another method to trigger this function
```js
function verifyIncrementAndSubmitCount () {
ensureCountIsAccurate();
handleClick();
submitCount();
}
```
In this case `handleClick` is confusing. It's telling me the original event that it was written to be called by, but now it is being called from two places. It would be easier to understand had it always had a descriptive name to begin with.
```js
function verifyIncrementAndSubmitCount () { …
```
> Docs: Accurately name function

- site/src/server.js
No need to specify a default of `3000`. It will get it as the default anyway (not quite sure where it's coming from though)
Adds some validation. I tried to build the site and it complained my mapbox key was missing, so I created an .env file and stuck a fake key in there to get the site to build for testing. Then I tried `npm run dev` again and the server would no longer start, but I didn't connect it to having created an `.env` file. I hadn't looked at the other fields and didn't realize there was a `PORT` in there. It took me quite awhile to figure out what was happening. Hopefully this will help others who might run into this
> site: fix falling back to default port

- site/content/docs/01-component-format.md
Was personally unaware how readonly props can be accessed until I found [this stackoverflow answer](https://stackoverflow.com/questions/58287729/how-can-i-export-a-function-from-a-svelte-component-that-changes-a-value-in-the) through some googling recently. Does not seem to be mentioned anywhere in the docs.
> clarified readonly prop access

- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/render_dom/wrappers/Element/EventHandler.ts
- src/runtime/internal/dom.ts
- test/runtime/samples/event-handler-modifier-trusted/_config.js
- test/runtime/samples/event-handler-modifier-trusted/main.svelte
- test/validator/samples/event-modifiers-invalid/errors.json
Fixes #6137
Adding a trusted modifier to make events not be dispatchable by console/sourcecode.
Useful to prevent injected code to automatically dispatch event for preventing botting
> Add trusted modifier

- src/runtime/internal/Component.ts
- src/runtime/internal/transitions.ts
- src/runtime/internal/utils.ts
> add typescript def for transitions

- src/compiler/compile/render_dom/index.ts
- test/js/samples/capture-inject-state/expected.js
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/debug-hoisted/expected.js
- test/js/samples/debug-no-dependencies/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/js/samples/loop-protect/expected.js
Repl with error: https://svelte.dev/repl/421c409d2bca424b97d18791f4af4c08?version=3.35.0
When you use slot property on component you get wrong warning.
> Fix wrong "slot" property warning (runtime)

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-mouse-events-have-key-events/input.svelte
- test/validator/samples/a11y-mouse-events-have-key-events/warnings.json
Fixes `mouse-events-have-key-events` of #820 
> check if mouse events are accompanied by key events

- src/compiler/compile/render_ssr/handlers/Comment.ts
- test/helpers.ts
- test/js/samples/ssr-preserve-comments/expected.js
- test/server-side-rendering/index.ts
- test/server-side-rendering/samples/comment-preserve/_config.js
- test/server-side-rendering/samples/comment-preserve/_expected.html
- test/server-side-rendering/samples/comment-preserve/main.svelte
Fixes #4730 
Should I create a test in `server-side-rendering/samples` or the existing one in `js/samples/ssr-preserve-comments` is enough?
Adding the test in server-side-rendering will require an extra config flag to not use `assert.htmlEqual` on that specific test, as it removes comments.
> Fix perserveComments on ssr (#4730)

- .gitignore
- package.json
- rollup.config.js
- src/runtime/ssr.ts
> expose svelte/ssr which have noop for lifecycle events

- site/content/blog/2021-07-01-whats-new-in-svelte-july-2021.md
Ready to review! Still holding off on highlighting "starters". Didn't find many "Apps & Sites" either. Mostly just personal blogs posted in the showcase locations this month. If folks saw some interesting new sites that I missed, feel free to contribute!
I'm not sure where to find the best list of changes for SvelteKit. I used the closed PRs for the month, but I'm sure there's commits to the mainline branch that I might have missed. @benmccann you had a [great list from last month](https://github.com/sveltejs/svelte/pull/6356#discussion_r639066206), not sure were you found those ;)
> [docs] "What's new in Svelte" July newsletter

- site/content/tutorial/08-stores/02-auto-subscriptions/text.md
Update of tutorial/stores/auto-subscriptions/text.md to explicitly say that subscription method returns an unsubscribe fn #6448
> [docs] Update auto-subscriptions tutorial to explicitly say that subscribe returns unsubscribe

- site/content/docs/05-accessibility-warnings.md
This PR adds a missing warning to the a11y docs and tweaks some of the wording. It also adds a disclaimer that Svelte won't catch all issues and further action by the developer is needed.
- Add disclaimer that Svelte won't catch all a11y issues
- Correct aria-hidden syntax
- Screenreader -> screen reader for consistency
- Add more details around some of the checks
- Add docs on a11y-mouse-events-have-key-events (https://github.com/sveltejs/svelte/pull/5938)
- Other wording tweaks
- ~[ ] Ideally, include a test that fails without this PR but passes with it.~
-  ~[ ] Run the tests with `npm test` and lint the project with `npm run lint`~
> [docs] update a11y docs with new warning and tweak wording

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-media-has-caption/input.svelte
- test/validator/samples/a11y-media-has-caption/warnings.json
Related to #5967 . Closes https://github.com/sveltejs/svelte/pull/6157
This PR removes the a11y warning for missing `<track kind="captions">` on audio elements.
- [Browsers ignore tracks within audio elements](https://www.iandevlin.com/blog/2015/12/html5/webvtt-and-audio/)
- The [corresponding axe-core rule](https://github.com/dequelabs/axe-core/pull/1071) the original check was based on has been deprecated
- The [corresponding Lighthouse audit](https://web.dev/audio-caption/) has been deprecated
The associated test has also been updated.
Merging this PR should not close the associated issue -- the intent of the issue was to remove the warning for audio and video, but there was some debate. Since there was clear agreement in removing the warning for audio elements, I thought to go for the …
> Remove misleading a11y caption warning on <audio>

- site/README.md
Fixed typo in `site/README.md`: `site-repl` -> `svelte-repl`.
Also made a minor change to a sentence's structure (used to look like a list of 4, when really it's a list of 2).
> [docs] Fixed typo 'site-repl' -> 'svelte-repl'

- src/compiler/compile/Component.ts
- src/compiler/compile/compiler_errors.ts
- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/css/Selector.ts
- src/compiler/compile/css/Stylesheet.ts
- src/compiler/compile/nodes/Animation.ts
- src/compiler/compile/nodes/Binding.ts
- src/compiler/compile/nodes/EachBlock.ts
- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/nodes/Head.ts
- src/compiler/compile/nodes/InlineComponent.ts
- src/compiler/compile/nodes/Let.ts
- src/compiler/compile/nodes/Slot.ts
- src/compiler/compile/nodes/SlotTemplate.ts
- src/compiler/compile/nodes/Title.ts
- src/compiler/compile/nodes/Transition.ts
- src/compiler/compile/nodes/Window.ts
- src/compiler/compile/nodes/shared/AbstractBlock.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- tsconfig.json
This organizes all compiler errors and warnings into separate files. This should help discoverability of those and know where to look them up in a distinct place. It also reduced some duplication.
> [chore] move compiler warnings/errors to dedicate files

- src/runtime/internal/dom.ts
- test/runtime/samples/each-block-keyed-changed/_config.js
- test/runtime/samples/each-block-keyed-changed/main.svelte
> [fix] fix insert function

- src/compiler/compile/css/Selector.ts
- test/validator/samples/css-invalid-global-selector-5/errors.json
- test/validator/samples/css-invalid-global-selector-5/input.svelte
- test/validator/samples/css-invalid-global-selector-6/errors.json
- test/validator/samples/css-invalid-global-selector-6/input.svelte
- test/validator/samples/css-invalid-global-selector/input.svelte
Fixes https://github.com/sveltejs/svelte/issues/6477
do not throw error for cases like:
```css
div, :global(a, b), div { }
:global(a, b) { }
```
- ~~[ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs~~
> [fix] standalone :global() with multiple selectors shouldn't be treated as error

- CHANGELOG.md
- src/runtime/store/index.ts
With this fix, doing
```
const stores= [writable(0), writable(1)]
derived(stores, ([a,b,c]) => {});
```
works without type errors. The propblem with the previous type signature was that it's too strict for TypeScript's suboptimal inference of the value `stores` in that example, which is `Array<Readable<any>>`, which does not convey the info "at least one element", which the old Stores signature required.
Runtime-wise, it's no problem passing an empty array to derived.
The new signature is only appended to, not replaced, because the old signature is able to correctly infer the values of each array entry: For `derived([writable(0), writable('foo')], ([a, b]) => {});` the parameters `a` and `b` are correctly inferred as `number` and `string`. If the type would be changed to `type Stores = …
> [fix] relax store derived function signature

- src/compiler/compile/render_ssr/handlers/Element.ts
- src/compiler/compile/render_ssr/handlers/shared/get_attribute_value.ts
- test/runtime/samples/attribute-prefer-expression/_config.js
- test/runtime/samples/binding-indirect-spread/_config.js
- test/runtime/samples/binding-input-checkbox-group-outside-each/_config.js
- test/runtime/samples/binding-input-checkbox-group/_config.js
- test/runtime/samples/binding-input-group-each-1/_config.js
- test/runtime/samples/binding-input-group-each-2/_config.js
- test/runtime/samples/binding-input-group-each-3/_config.js
- test/runtime/samples/binding-input-group-each-4/_config.js
- test/runtime/samples/binding-input-group-each-5/_config.js
- test/runtime/samples/binding-input-group-each-6/_config.js
- test/runtime/samples/binding-input-radio-group/_config.js
- test/server-side-rendering/samples/bindings-group/_expected.html
- test/server-side-rendering/samples/bindings-group/main.svelte
This PR implements server-rendering for group bindings. I noticed this TODO comment and attempted to add the feature.
https://github.com/sveltejs/svelte/blob/aa3dcc06d6b0fcb079ccd993fa6e3455242a2a96/src/compiler/compile/render_ssr/handlers/Element.ts#L116
This commit covers the following cases
- **group value is a string:** checked if value strict equals group value
- **group value is an array:** checked if value is included in group value array
I didn't see any other data structures for group bindings in docs so I hope this covers everything.
> add ssr for group bindings

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/Text.ts
- test/sourcemaps/samples/decoded-sourcemap/_config.js
- test/sourcemaps/samples/external/_config.js
- test/sourcemaps/samples/markup/input.svelte
- test/sourcemaps/samples/markup/test.js
- test/sourcemaps/samples/sourcemap-basename/_config.js
- test/sourcemaps/samples/sourcemap-offsets/_config.js
> [feat] sourcemap markup

- site/content/docs/02-template-syntax.md
> docs: mention usage of regexp literal in text expressions

- src/compiler/compile/render_ssr/handlers/Element.ts
- test/runtime/samples/apply-directives-in-order/_config.js
- test/runtime/samples/binding-circular/_config.js
- test/runtime/samples/binding-select-implicit-option-value/_config.js
- test/runtime/samples/binding-select-in-each-block/_config.js
- test/runtime/samples/binding-select-initial-value/_config.js
- test/runtime/samples/binding-select-late-2/_config.js
- test/runtime/samples/binding-select-multiple/_config.js
- test/runtime/samples/binding-select/_config.js
- test/runtime/samples/bindings-global-dependency/_config.js
- test/runtime/samples/component-binding-computed/_config.js
- test/runtime/samples/component-binding-store/_config.js
- test/runtime/samples/component-slot-fallback-6/_config.js
- test/runtime/samples/component-slot-spread-props/_config.js
- test/runtime/samples/each-block-destructured-default-binding/_config.js
- test/runtime/samples/store-invalidation-while-update-1/_config.js
- test/runtime/samples/store-invalidation-while-update-2/_config.js
- test/server-side-rendering/samples/bindings-empty-string/_expected.html
- test/server-side-rendering/samples/bindings-empty-string/main.svelte
- test/server-side-rendering/samples/bindings-zero/_expected.html
- test/server-side-rendering/samples/bindings-zero/main.svelte
Fixes #4551
- add "value" attribute for `bind:value` even when value is `0` or `""`
- remove "value" attribute for `<select bind:value>` as it is not a valid attribute for `<select>`
> [fix] input value 0 for ssr

- src/compiler/compile/render_dom/index.ts
I saw this as a warning in another PR. Seemed easy enough to fix
> [chore] fix duplicate import of periscopic

- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/runtime/internal/dom.ts
- src/runtime/internal/utils.ts
- test/hydration/samples/head-meta-hydrate-duplicate/_after_head.html
- test/js/samples/hydrated-void-element/expected.js
- test/js/samples/src-attribute-check/expected.js
This PR tries to address some issues that were not addressed by https://github.com/sveltejs/svelte/pull/6395 and issues pointed out by @benmccann and @ankitstarski
- An img element's src value should only be set if it is not the expected value. This check existed, but failed to account for relative paths which were returned as absolute paths when checking `img.src`.
- Existing nodes under `<head>` that are not claimed but also not detached should be ignored by `init_hydrate`. These nodes have `node.claim_order === undefined`
- The function `claim_html_tag` should also set `claim_order`.
Edit:
- Add a fast path to `init_hydrate` for when most of the nodes are on the longest increasing subsequence.
- Improve claims for text nodes: There are many cases where we try to only claim a prefix of …
> [fix] hydration improvements

- src/compiler/compile/Component.ts
- test/runtime/samples/store-auto-subscribe-in-reactive-declaration-2/App.svelte
- test/runtime/samples/store-auto-subscribe-in-reactive-declaration-2/_config.js
- test/runtime/samples/store-auto-subscribe-in-reactive-declaration-2/main.svelte
> [fix] store reactivity in reactive declarations

- src/compiler/utils/mapped_code.ts
- test/sourcemaps/samples/decoded-sourcemap/_config.js
- test/sourcemaps/samples/external/_config.js
- test/sourcemaps/samples/preprocessed-no-map/_config.js
- test/sourcemaps/samples/sourcemap-basename/_config.js
- test/sourcemaps/samples/sourcemap-offsets/_config.js
When source maps are combined and the leading map is empty, sources is not set. Add the filename to the empty array in this case. This _may_ be an [upstream issue](https://github.com/ampproject/remapping/issues/116) (but maybe it's also intended, let's see) but either way for our cases it's necessary to set `sources` even for empty maps.
They were not added before this change so I adjusted the tests. The `js.map` output now is closer to what it would be like if there was no preprocessing and there's no JS - in that case Svelte outputs an empty map with `sources` set which looks like this
```
{
version: 3,
names: [],
sources: [ '..path/to/$layout.svelte' ],
sourcesContent: [ '<p>asd</p>\r\n' ],
mappings: ';;;;;;;'
}
```
Related https://github.com/sveltejs/kit/issues/424
-  [x] Run the …
> Add filename to combined source map if needed

- src/runtime/internal/transitions.ts
> [fix] tracking whether transition has started

- src/compiler/compile/render_dom/Block.ts
- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/autofocus/_config.js
- test/runtime/samples/autofocus/main.svelte
Fixes #4995. Supersedes initial implementation in #5070.
This ensures element's with `autofocus={foo}` will focus the element if `foo` is true and **on mount only**. If `foo` changes from false to true, it will not trigger a re-focus as I don't think it's a desired behavior.
> [fix] dynamic autofocus

- site/content/docs/01-component-format.md
Because this is a common recurring question, this PR adds a touch more information in regards to reactivity and arrays.  More specifically the need for an assignment after array manipulation.
This is already covered in the tutorial, but it seems good to also include it as an example directly in the docs themselves.
> [docs] Add clarification about reactivity and arrays

- site/content/tutorial/06-bindings/07-multiple-select-bindings/text.md
`control` will allow to select several options. `shift` will select a range from the first to the last (starting from either top or bottom).
If we click on `Cookies and cream` and then on `Raspberry ripple` while holding `shift`, all of the 3 checkboxes will be selected (from the 1st **to** the 3rd).
If you hold `control`, this will properly select the 1st **and** the 3rd.
An example can be seen here: https://html.com/attributes/select-multiple/
> [docs] replace shift by the correct key to hold: control

- src/runtime/internal/dom.ts
- src/runtime/internal/style_manager.ts
- test/runtime/samples/target-dom-detached/App.svelte
- test/runtime/samples/target-dom-detached/_config.js
- test/runtime/samples/target-dom-detached/main.svelte
- test/runtime/samples/target-dom/App.svelte
- test/runtime/samples/target-dom/_config.js
- test/runtime/samples/target-dom/main.svelte
- test/runtime/samples/target-shadow-dom/App.svelte
- test/runtime/samples/target-shadow-dom/_config.js
- test/runtime/samples/target-shadow-dom/main.svelte
> [fix] no root node for detached dom node

- src/runtime/internal/utils.ts
- test/runtime/samples/store-assignment-updates-destructure/_config.js
- test/runtime/samples/store-assignment-updates-destructure/main.svelte
> [fix] destructuring store assignment

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/transition-css-in-out-in-with-param/_config.js
- test/runtime/samples/transition-css-in-out-in-with-param/main.svelte
- test/runtime/samples/transition-css-in-out-in/_config.js
Fixes #6505 
Already I discussed how to solve this issue at #6505 .
And regarding the test, in this case, I can re-use `transition-css-in-out-in`,
So just I changed the existing case. (I think I don't need to add a new case)
In this PR, I removed `if (!${intro_name})`.
So I checked why this IF statement is implemented.
Then according to git log, 
The process about `in transition` is added on 14 Jan 2019.
And since this time, the IF statement is there.
https://github.com/sveltejs/svelte/commit/0ea384004626bab8c86104a9a907460b72aa7c7f
So I think the author doesn't consider that programmers can manage `in:fly` params if they use state or local variable or something at least that time.
Thank you!🧐
> [fix] create in transition even if intro is initialized

- src/compiler/compile/render_dom/wrappers/Slot.ts
- src/runtime/internal/utils.ts
- test/runtime/samples/transition-js-slot-2/_config.js
- test/runtime/samples/transition-js-slot-4-cancelled/Nested.svelte
- test/runtime/samples/transition-js-slot-4-cancelled/_config.js
- test/runtime/samples/transition-js-slot-4-cancelled/main.svelte
- test/runtime/samples/transition-js-slot-5-cancelled-overflow/Nested.svelte
- test/runtime/samples/transition-js-slot-5-cancelled-overflow/_config.js
- test/runtime/samples/transition-js-slot-5-cancelled-overflow/main.svelte
- test/runtime/samples/transition-js-slot-6-spread-cancelled/Nested.svelte
- test/runtime/samples/transition-js-slot-6-spread-cancelled/Nested2.svelte
- test/runtime/samples/transition-js-slot-6-spread-cancelled/_config.js
- test/runtime/samples/transition-js-slot-6-spread-cancelled/main.svelte
- test/runtime/samples/transition-js-slot-7-spread-cancelled-overflow/Nested.svelte
- test/runtime/samples/transition-js-slot-7-spread-cancelled-overflow/_config.js
- test/runtime/samples/transition-js-slot-7-spread-cancelled-overflow/main.svelte
> fix slot data for cancelled transition

- site/content/blog/2021-08-01-whats-new-in-svelte-august-2021.md
Sorry this is coming in so late this month. I hope I caught everything!
If not, feel free to add any changes before merging. Totally cool if this doesn't get merged before August 1 :) I can send out the newsletter late, if y'all need time to review.
> [docs] "What's new in Svelte" August newsletter

- src/compiler/compile/Component.ts
- test/sourcemaps/samples/sourcemap-basename-without-outputname/_config.js
- test/sourcemaps/samples/sourcemap-basename-without-outputname/input.svelte
- test/sourcemaps/samples/sourcemap-basename-without-outputname/test.js
sveltekit issue for vite printing warnings about wrong sourcemap paths: https://github.com/sveltejs/kit/issues/2029
and vite issue here: https://github.com/vitejs/vite/issues/4423#issuecomment-889308451
also this PR/discussion if a change should be reverted that could also fix it: https://github.com/sveltejs/svelte/pull/6572
note while i did test that with this change vite no longer logs that warning in kit, i'm not 100% sure that this fix is 100% correct. I'm confused why there were 3 different ways to handle it before and it may very well have been on purpose.
cc @dummdidumm  @tanhauhau
> [fix] use consistent relative source filename for js sourcemaps

- site/content/docs/02-template-syntax.md
- site/content/tutorial/05-events/03-event-modifiers/text.md
Fixes https://github.com/sveltejs/svelte/issues/6595. See issue for details!
> [docs] Fix property name typo for event.isTrusted

- src/runtime/internal/dom.ts
- test/runtime/samples/key-block-post-hydrate/_config.js
- test/runtime/samples/key-block-post-hydrate/main.svelte
(Hopefully) Fixes #6561 (issue with keyed each block) ~~and fixes 6463 (hydration duplicates elements in `head`)~~
Fix for issue #6561 is in the `append_hydration` function where an append operation was omitted in a case where `node.parentNode === target` but `node.nextSibling !== null`. The corresponding test is `runtime/samples/key-block-post-hydrate`.
~~Fix for issue #6463 is based on the comment https://github.com/sveltejs/svelte/issues/6463#issuecomment-889430684. The corresponding test is `hydration/samples/head-html`.~~
> [fix] hydration append issue

- site/content/docs/02-template-syntax.md
This makes a number of stylistic changes to the template syntax section of the documentation, and fixes at least one typo.
Probably most significantly, in the section about CSS var props, it removes a reference to the version number and RFC and issue where this feature was added (since this is not something we're doing anywhere else), and removes the caniuse link for `display: contents` because, as discussed in the RFC for this feature, enough of this CSS feature is supported in all browsers that support CSS variables, which are required for this feature to function at all.
> [docs] various adjustments to template syntax docs

- site/src/routes/_components/WhosUsingSvelte.svelte
Image scale effect is now a little less eminent, but it does not shifts page layout anymore. Tested in Chrome and Firefox.
Fixes: #6576.
> [fix] Prevent layout shifting on hovering "Who's using Svelte?"

- site/content/blog/2020-07-17-svelte-and-typescript.md
- site/content/blog/2020-10-01-whats-new-in-svelte-october-2020.md
We must not skip heading levels. This is bad for accessibility and our tooling doesn't like it.
> docs: fix heading levels

- site/content/tutorial/19-next-steps/01-congratulations/app-a/App.svelte
Disable text select in the span element to improve the illusion of falling emojis.
> [docs] Disable text select

- site/content/blog/2021-04-01-whats-new-in-svelte-april-2021.md
- site/content/blog/2021-05-01-whats-new-in-svelte-may-2021.md
- site/content/blog/2021-08-01-whats-new-in-svelte-august-2021.md
- site/content/docs/04-compile-time.md
- site/content/tutorial/01-introduction/07-making-an-app/text.md
I'd like to replace https://github.com/sveltejs/integrations with https://sveltesociety.dev and retire the former. It's confusing to have this information spread across two sources right now and there's much more info on the latter. I also think that a full-featured webpage is a better format for this stuff because you can do things like sort templates by number of Github stars, automatically remove archive and unmaintained templates, etc. I don't especially want to be in the business of judging whether a template is high enough quality to add to sveltejs/integrations. Having a directory that can be sorted by stars means anyone can add theirs and if it's not popular it will fall to the bottom and if it goes unmaintained we can detect that there's been no commits for some very extended …
> Replace sveltejs/integrations with sveltesociety.dev

- site/content/tutorial/06-bindings/07-multiple-select-bindings/text.md
On MacOS, control-clicking an element is the same as right-clicking an element in Windows.
The correct way of multiple selection under MacOS is using the option key ('⌘').
Svelte's [tutorial documentation](https://svelte.dev/tutorial/multiple-select-bindings) is incomplete here.
> docs: Selecting multiple elements in <select multiple> on MacOS with command key

- site/content/examples/99-embeds/20181225-blog-svelte-css-in-js/styles.js
The REPL embed on the [Using CSS-in-JS with Svelte](https://svelte.dev/blog/svelte-css-in-js) blog post is currently broken.
This PR updates the import so it works again. In addition, I pinned the emotion version so that further updates to the package won't break the example.
Result:
-  [ ] ~Run the tests with `npm test` and lint the project with `npm run lint`~
> [docs] fix css in js embed

- src/runtime/animate/index.ts
> [fix] better flip animation

- src/runtime/internal/dom.ts
- test/runtime/samples/binding-select-initial-value-undefined/_config.js
- test/runtime/samples/binding-select-unmatched/_config.js
- test/runtime/samples/binding-select-unmatched/main.svelte
Previously, when the bound value of a select element was set to `null` or any other value not matching one of the options, the first option would appear selected. So even if the select element was `required`, users could submit the form and end up sending a different value than what it appeared they were submitting.
With this change, if a select element is bound to a value that doesn't match one of its options, then none of the options will appear selected. This helps catch bugs during development when the bound value inadvertently doesn't match an option. It also makes it possible to bind a `required` select element to `null`, and cause the browser to require users to explicitly select an option before the form can be submitted.
Resolves #6126.
With this change Svelte will match the …
> [fix] Set selectedIndex to -1 when no option matches bound select value

- src/runtime/ssr.ts
Via #6416, lifecycle hooks became noops for SvelteKit. But onDestroy is said to be called suring SSR according to the docs.
Fixes #6676
This PR goes this "fix" route of #6676 . Whether we switch that to "works as designed" for SvelteKit is up for discussion, therefore marking this PR as draft for now.
> [fix] call onDestroy in SSR

- site/content/docs/01-component-format.md
fix: #6681 
> The https://svelte.dev/docs#Component_format docs currently present the example snippet in script-style-markup order. But the default order used by prettier-plugin-svelte is script-markup-style (technically options-script-markup-style, but the https://svelte.dev/docs#Component_format docs don't show options), and my subjective impression is that script-markup-style order is more common in real-world code than script-style-markup. (I haven't done any kind of formal survey). I suspect most people write Svelte code in that order because in most components, the markup is tied to the script, and the style is tied closely to the markup, but the style is not closely tied to the script. And so for those …
> [docs] update docs/Component-format script-markup-style order

- site/content/faq/425-is-there-a-tool-to-automaticly-format.md
I wanted to find a tool to reformat my svelte files. Both the FAQ and stackoveflow were unhelpful. I eventually stumbled upon prettier-plugin-svelte. Since this kind of question is off-topic on stackoveflow ("Questions asking us to recommend or find a book, tool, software library, tutorial or other off-site resource are off-topic for Stack Overflow" [quoted from here](https://stackoverflow.com/help/on-topic)) we should add this to the FAQ
> [docs] Promote prettier-plugin-svelte

- site/content/blog/2021-09-01-whats-new-in-svelte-september-2021.md
I feel like there's more SvelteKit changes I missed...
Pretty packed showcase! Feel free to edit the list down if y'all think it's too long.
> [docs] "What's new in Svelte" September newsletter

- site/content/tutorial/06-bindings/12-bind-this/app-a/App.svelte
- site/content/tutorial/06-bindings/12-bind-this/app-b/App.svelte
To calculate y coordinate of `imageData`, we should divide the index with
`canvas.width` not with `canvas.height`. The current code works because the
shape of canvas is square.
> [docs] Fix a minor bug in binding tutorial

- site/content/docs/02-template-syntax.md
Fixes a small typo: "be a present in"->"be present in"
> [docs] Fix typo in $$slots docs

- site/content/docs/02-template-syntax.md
I'm not sure when this was added, but I discovered that's it's possible to bind to the `open` state of a `<details>` element. This PR updates the docs accordingly.
Should there be a new tutorial section for this as well?
- ~[ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs~
- ~[ ] Ideally, include a test that fails without this PR but passes with it.~
> [docs] document details binding

- src/compiler/compile/Component.ts
- test/runtime/samples/destructured-assignment-pattern-with-object-pattern/_config.js
- test/runtime/samples/destructured-assignment-pattern-with-object-pattern/main.svelte
fix #6699 
Hi team!  
There is a lack of consideration in handling `export` props with destructure assignment. 
In transforming the left of destructure assignment with AssignmentPattern (such as `let { bar = "hoge"  }` in `let { bar = "hoge" } = {}`) , compiler handle only the case declaration's type is Identifier, but declaration's type in destructuring assignment with AssignmentPattern could be ObjectPattern, RestElement, ArrayPattern, AssignmentPattern. This lack of consideration caused #6699 error because such a pattern was handled as Identifier.
I fixed it (and add the test about it).
> [fix] handle AssignmentPattern with ObjectPattern in rewrite_identifier

- src/compiler/preprocess/index.ts
- test/preprocess/samples/empty-sourcemap/_config.js
- test/preprocess/samples/empty-sourcemap/input.svelte
- test/preprocess/samples/empty-sourcemap/output.svelte
Fixes https://github.com/sveltejs/svelte-preprocess/issues/412
Handles preprocessors that return empty sourcemaps like `{ mappings: '' }`, which is valid per [rollup documentation](https://rollupjs.org/guide/en/#source-code-transformations).
cc @dominikg 
> [fix] handle preprocess with empty sourcemaps

- package.json
Credit to @benmccann for the idea. This prevents the need for bundlers to bundle external dependencies that imports `svelte` in order to resolve them to `svelte/ssr`.
> [feat] export svelte/ssr in node

- src/runtime/internal/Component.ts
- src/runtime/internal/ssr.ts
- test/runtime/samples/constructor-prefer-passed-context/ChildComponent.svelte
- test/runtime/samples/constructor-prefer-passed-context/_config.js
- test/runtime/samples/constructor-prefer-passed-context/main.svelte
- test/server-side-rendering/samples/constructor-prefer-passed-context/ChildComponent.svelte
- test/server-side-rendering/samples/constructor-prefer-passed-context/_expected.html
- test/server-side-rendering/samples/constructor-prefer-passed-context/main.svelte
This fixes #6753 and also fixes it for SSR so that the passed `context` is preferred, even when we have a `parent_component`. Browser and SSR are implemented as separate tests, because the process of synchronously creating a child component outside of Svelte's jurisdiction is rather different in the two cases.
> [fix] prefer context from constructor options

- site/content/blog/2020-11-05-whats-the-deal-with-sveltekit.md
modify the link protocol of rollup from http to https
> [docs] update link to rollup.org to use https

- site/content/blog/2018-04-18-version-2.md
[docs] update links to babeljs.io and buble.surge.sh to use https
> [docs] update links to babeljs.io and buble.surge.sh to use https

- .github/workflows/ci.yml
- src/compiler/compile/render_ssr/handlers/AwaitBlock.ts
- test/hydration/index.ts
- test/hydration/samples/event-handler/main.svelte
- test/runtime/index.ts
Fixes #6789. I haven't looked yet at how reasonable they would be to write. We aren't running any tests in Node 16 in CI, but I'm a little surprised that none of the tests involving SSR and `{#await}` are currently failing for me when running them locally. I'm not sure how else I'd cause a breakage that I could then demonstrate was fixed by this PR.
> [fix] handle promise rejections for {#await} in SSR

- site/content/docs/02-template-syntax.md
I was looking at https://github.com/sveltejs/kit/issues/2520 and was a bit unclear on how `{#await}` works exactly. @Conduitry filled me in on some missing details that helped elucidate things. I thought they could be useful to add to the docs
> [docs] what is rendered when for #await

- site/src/routes/_components/WhosUsingSvelte.svelte
In the "Who’s using Svelte ?" part, on the Svelte’s website using Safari, images overflowing.
Add a `min-with: 0`  🤷
---
> [fix] Fix img overflow in "Who’s using Svelte ?" on Safari

- site/src/routes/index.svelte
Closes https://github.com/sveltejs/svelte/issues/6791
First link goes to the Stack Overflow developer survey results and the second goes to the State of JS survey results. This would make the homepage diverge slightly from pngwn's branch, but we can copy it over there pretty easily if this gets merged
> Update homepage with survey results

- site/content/examples/05-bindings/04-textarea-inputs/App.svelte
- site/content/tutorial/06-bindings/05-textarea-inputs/app-a/App.svelte
- site/content/tutorial/06-bindings/05-textarea-inputs/app-b/App.svelte
Fixes #6892. We need to use the named export from `marked` that Marked 4 now has.
Question: Should we make these examples use `marked@4` to reduce future issues like this?
> [docs] use new export import for marked 4 in examples

- site/src/routes/repl/index.svelte
The legacy `/repl` page wasn't correctly updated for SvelteKit - it was assuming that `query` was an object of keys and values, rather than a `URLSearchParams` instance.
I'm not sure why one of the redirects is a 301 and the other is a 302, but that seems to predate the SvelteKit conversion. This also means that anyone who get an invalid redirect to the new REPL (rather than to the old v2 site) will have a bad redirect stuck in their cache. There's nothing we can do about that now, but maybe it would make sense to make these both be 302s?
> [docs] fix redirects from legacy /repl page

- site/content/docs/04-compile-time.md
Original preprocessor link is dead github repo that points to https://sveltesociety.dev/. I thought the link should just take you there  and to the relevant section.  Instead of the dead repo
> [docs] Update compile.md preprocessor link.

- site/content/faq/900-is-there-a-router.md
- removed "router for business software" as it doesn't add a lot
- listed `universal-router` since it's one of the more popular and actively maintained framework-agnostic routers
- mentioned that there's some similarity between Routify and SvelteKit
> [docs] update router FAQ

- package.json
fixes: #6877
This will allow electron renderers to avoid loading `ssr.mjs` when importing `svelte` and instead load `index.mjs` like a normal browser would.  Electron renderers are like normal browsers, but they also can access node functions, which is why both the "node", and "browser" conditionals are present when resolving module names using package.json's "exports" feature.
> [fix] added "browser" conditional to "exports" in package.json

- site/content/docs/02-template-syntax.md
Closes #6197
After reading the maitainers' views on #5166, I think a simple note like this would be sufficient.
on: and bind: have separate sections for components and elements but from a beginner's perspective this seems like the most natural place to have it.
I'm not sure what, if anything would need to be added in any of the tutorials, I'd appreciate some comments on that.
> [docs] Document the effect of the order of bind: and on:

- site/content/faq/900-is-there-a-router.md
I was semi-investigating making the router pluggable in SvelteKit. It's important to know which routers have SSR support in that context. Thought I would share the results of my research here
> [docs] clarify which routers have SSR support

- src/compiler/preprocess/index.ts
- src/compiler/preprocess/types.ts
Fix preprocessor types:
- Allow `Preprocessor` to return void
- Make `MarkupPreprocessor` `filename` arg optional (always has been optional)
Refactor `src/compiler/preprocess/index.ts` too ensuring `filename` is nullable.
> [fix] update preprocessor types

- src/compiler/utils/patterns.ts
- src/compiler/utils/trim.ts
- test/utils/index.ts
---
I made the `trim` utils more readable and performant. I've also included their tests to make sure they're working correctly.
> [refactor] refactor trim utils and write tests

- CHANGELOG.md
- src/runtime/transition/index.ts
People with "noUncheckedIndexedAccess" set to true in their tsconfig would get false errors when accessing the return type because without this specific tuple typing, TS infers this as being an array of functions, not a tuple of functions.
Fixes #6926
> [fix] more specific return type for crossfade

- CHANGELOG.md
- package.json
This will be needed when TS adds the new node module resolution algorithm. It also solves https://github.com/microsoft/TypeScript/issues/46860 on our end.
> [fix] add types field to exports

- src/compiler/utils/names.ts
[`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams): it's a real thing!
I couldn't get the tests running locally, so I didn't go looking for a test to change to motivate this, but I saw that the last addition to the list didn't come with a test either, so I decided I was fine with it.
> [fix] Add URLSearchParams to list of globals

- site/content/docs/04-compile-time.md
https://sveltesociety.dev/tooling was incorrect. https://sveltesociety.dev/tools is the correct link.
> [fix] Incorrect link for Svelte Society community-maintained tools in docs

- site/content/tutorial/10-transitions/07-local-transitions/text.md
I was confused while reading the tutorial about local transitions. The tutorial talks about removing items and words the transition in those terms, which makes the transition block a parent. BUT... then it talks about the local directive, which belongs to the block with the transition itself.
To avoid confusion I have pretty much copied the wording from the docs verbatim (https://svelte.dev/docs, search for "Local transitions only play"), since I find the wording in the docs very clear.
I have not created an issue. Please let me know if this would still be helpful or is still needed.
> [docs] clarified definition of "local transition" in tutorial

- site/content/tutorial/06-bindings/14-component-this/text.md
If I just add the code on the sidebar the console says that the field variable is undefined, so I've included a reference with the variable in  the initial code block as to make it clear to the user.
> [docs] A reference of the field variable is missing in the sidebar

- site/package-lock.json
- site/package.json
- site/src/routes/__error.svelte
This adds a `rel=external` to the Discord chat link, which is necessary now that endpoints are no longer handled by the client-side router. It also adds a "the".
> [docs] fix chat link

- site/src/routes/repl/[id]/_components/AppControls/index.svelte
Improvement of https://github.com/sveltejs/svelte/issues/6797
Honestly, I also took time to know I can edit a title of REPL.
So I tried to improve it according to the issue.
**[Current Version]**
https://svelte.dev/repl/hello-world?version=3.43.1
**[After Improvement]**
https://user-images.githubusercontent.com/19153718/135877687-d2f386dc-dd01-48ec-b69d-68bbafb05817.mp4
--- 
Thank you!
> [chore] Make changing the name of a REPL obvious

- site/package-lock.json
- site/package.json
- site/src/routes/repl/[id]/_components/AppControls/index.svelte
- site/src/routes/repl/[id]/index.svelte
Fixes sveltejs/svelte-repl#117
If a user has unsaved changes in the REPL and navigates away, all changes are lost. This has bit me quite a few times. 
This PR adds a warning "There are unsaved changes" to prevent any the data loss.
This change is in conjunction with sveltejs/svelte-repl#156.
I'm opening this PR so that we can discuss if this method is correct or if we should a different path. 
> [feat] Track unsaved files in REPL

- site/content/blog/2021-05-01-whats-new-in-svelte-may-2021.md
- site/content/blog/2021-06-01-whats-new-in-svelte-june-2021.md
- site/content/blog/2021-07-01-whats-new-in-svelte-july-2021.md
- site/content/blog/2021-08-01-whats-new-in-svelte-august-2021.md
- site/content/blog/2021-09-01-whats-new-in-svelte-september-2021.md
- site/content/blog/2021-10-01-whats-new-in-svelte-october-2021.md
- site/content/blog/2021-11-01-whats-new-in-svelte-november-2021.md
- site/content/blog/2021-12-01-whats-new-in-svelte-december-2021.md
> fix: use correct yaml syntax in blog posts

- site/content/tutorial/02-reactivity/03-reactive-statements/app-b/App.svelte
- site/content/tutorial/02-reactivity/03-reactive-statements/text.md
Coming from python JS template literal syntax was new to me. This part of the otherwise fantastic tutorial threw me off, because I did not immediately notice the backticks. Like: "Oh, that's an interesting concept. But it doesn't work. Bummer."
Took me a while to figure.
> [docs] simplify template literals to string primitives

- site/content/tutorial/01-introduction/07-making-an-app/text.md
First time I ever looked through the tutorial the wording here made it seem like the only way to get a great IDE/Svelte tooling experience was with VS Code. Because of that I just didn't bother learning Svelte at the time.
Always good to be as inclusive as possible!
> [docs] Clarify that VS Code isn't the only supported IDE

- src/compiler/compile/Component.ts
- test/runtime/samples/loop-protect-async-opt-out/_config.js
- test/runtime/samples/loop-protect-async-opt-out/main.svelte
- test/runtime/samples/loop-protect-generator-opt-out/main.svelte
Fixes #6945
- opt-out loopguard for async loops
- fix the test for opt-out loopGuard for generators (it wasn't throwing error without the fix)
> [feat] opt-out loopGuard for async loops

- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- test/js/samples/input-value/expected.js
- test/js/samples/input-value/input.svelte
> [fix]: prevent cursor jump for all text inputs

- site/content/blog/2017-09-06-the-zen-of-just-writing-css.md
- site/content/blog/2018-12-27-virtual-dom-is-pure-overhead.md
- site/content/blog/2020-07-17-svelte-and-typescript.md
- site/content/examples/05-bindings/11-bind-this/App.svelte
- site/content/tutorial/06-bindings/12-bind-this/app-a/App.svelte
- site/content/tutorial/06-bindings/12-bind-this/app-b/App.svelte
Final remaining relative urls that hasn't been converted, looks like I missed checking some reference to the static assets.
Closes #7047 
> [docs] absolute assets links

- site/content/blog/2021-03-01-whats-new-in-svelte-march-2021.md
- site/content/docs/03-run-time.md
The docs had a broken link, pointing to `/examples#easing` instead of `/examples/easing`.
> [docs] Updated link to the ease visualizer in the docs

- site/content/examples/20-7guis/02-7guis-temperature/App.svelte
small correction about using the proper symbol for Celsius and Fahrenheit
> [docs] use proper symbol for Celsius and Fahrenheit

- site/content/tutorial/15-context/01-context-api/text.md
The [Context API](https://svelte.dev/tutorial/context-api) Tutorial gives instructions to import a couple of dependencies in `Map.svelte`. The example code has `onMount` as one of the existing dependencies of `Map.svelte`, however, the actual code is importing `onDestroy` instead of `onMount` (see screenshot below). This PR fixes the inconsistency.
> [docs] Fixed typo in Context API Tutorial

- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-no-redundant-roles/input.svelte
- test/validator/samples/a11y-no-redundant-roles/warnings.json
This solves one task on the list in #820. My first PR so probably a lot going on wrong here but I would be very appreciative for feedback and guidance on contributing.
> [feat] a11y-no-redundant-roles

- site/content/examples/05-bindings/09-media-elements/App.svelte
- site/content/tutorial/06-bindings/10-media-elements/app-a/App.svelte
- site/content/tutorial/06-bindings/10-media-elements/app-b/App.svelte
The [media elements bindings section](https://svelte.dev/tutorial/media-elements) of the tutorial has a couple of broken attribution links to Blender Open Projects, which has been renamed to Blender Studio and moved to a different url.
> [docs] Update links to Blender Studio

- package.json
- test/custom-elements/index.ts
- test/helpers.ts
- test/runtime-puppeteer/index.ts
- test/runtime/index.ts
- test/server-side-rendering/index.ts
I solved several issues of flaky tests.
Sometimes `EXC_BAD_ACCESS (SIGSEGV)` occurred in Chrome.
To fix this, maybe I need to fix the Chrome code, but that need too much work, so I added the retry process.
Only when Chrome crashes will re-run the tests.
And this problem seems to occur mainly when calling `browser.newPage()`. The cause is probably that there are too many tabs.
Closing the tabs at the end of a test seems to have stopped this error.
In other words, it reduces the error rate and stabilizes the test by retrying when an error occurs.
On GitHub actions with Windows, sometimes shows `Windows shows Terminate batch job (Y/N)?` and CI is not completed. 
So to handle it, I added [--exit](https://mochajs.org/) options to `mocha`.
(`--exit` option means `Force Mocha to quit after tests …
> [chore] fix test flakiness

- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- test/runtime/samples/if-block-else-update/_config.js
- test/runtime/samples/if-block-else-update/main.svelte
Fixing the bug in https://stackoverflow.com/questions/70439099/svelte-else-if-block-condition-not-evaluated-after-if-block-condition-changes
> [fix] else if value cached

- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/shared/bind_this.ts
- test/runtime/samples/binding-input-member-expression-update/_config.js
- test/runtime/samples/binding-input-member-expression-update/main.svelte
- test/runtime/samples/binding-this-each-key/_config.js
- test/runtime/samples/binding-this-each-key/main.svelte
- test/runtime/samples/binding-this-member-expression-update/_config.js
- test/runtime/samples/binding-this-member-expression-update/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/6921
Previously when binding a member expression `a[b][c]`, Svelte will invalidate all `a`, `b`, `c` whenever the bound value changes.
with the fix, Svelte will only invalidate `a`.
> [fix] binding member expression should only invalidate the object, not the member property

- src/compiler/compile/nodes/AwaitBlock.ts
- src/compiler/compile/nodes/EachBlock.ts
- src/compiler/compile/nodes/shared/Context.ts
- test/validator/samples/unreferenced-variables-each/input.svelte
- test/validator/samples/unreferenced-variables-each/warnings.json
Fixes #6964 
Marked default values as referenced when destructuring contexts
> [feat] add referenced for default values in destructuring context

- site/content/docs/04-compile-time.md
We'll add a feature to look at the AST in the REPL with a banner that the AST is not public API, so we should add the same note to the existing docs.
> [docs] add note about the AST not being public API

- src/runtime/internal/dom.ts
- test/hydration/samples/raw-with-empty-line-at-top/_after.html
- test/hydration/samples/raw-with-empty-line-at-top/_before.html
- test/hydration/samples/raw-with-empty-line-at-top/main.svelte
fixes https://github.com/sveltejs/svelte/issues/7115
After executing this line from Kit, `nodes` contains (maybe unexpected) `#text` node at the top and end.
https://github.com/sveltejs/svelte/blob/03ef0e46e9bf86ca2fe3800b9accef19070fea44/src/runtime/internal/Component.ts#L161
In this case, `start_index` is more than 0 (mostly 1).
And the second argument of `splice` is delete_count.
Therefore it will splice more than expected.
https://github.com/sveltejs/svelte/blob/03ef0e46e9bf86ca2fe3800b9accef19070fea44/src/runtime/internal/dom.ts#L504
If `start_index` is possibly more than 0, I think it should be modified to look like this PR.
On the other hand, should we prevent containing unexpected `#text` nodes at the top and end?
I think we can not control it because a template file containing …
> [fix] hydrate correct elements when using `@html`

- src/runtime/internal/dom.ts
- src/runtime/internal/style_manager.ts
**fixes animations with multiple independent Svelte apps running at the same time.**
This is an alternative approach to #7107.
Closes #7107
Fixes #7026
Instead of storing the style information directly on the `node` via a random property name, here the information get's stored inside a locale varable within the `style_manager`.
> [fix] ensure style manager instances don't conflict with each other

- site/content/docs/02-template-syntax.md
Closes #2724
The initial value of `bind:scrollX={x}` (and `scrollY`) will not be automatically scrolled on initial bound, which makes sense as to not interfere with potential router behaviour. Fixing it might also cause a breaking change. Note this in the docs instead.
> [docs] explain initial value for bind scroll

- src/runtime/animate/index.ts
Fixes #7103 
Make the `FlipParams` interface importable from "svelte/animate."
> [feat] export FlipParams interface from "svelte/animate"

- test/runtime/index.ts
- test/server-side-rendering/index.ts
https://github.com/sveltejs/svelte/pull/7076 is too good that it doesn't even has error with failed tests
when using async callback with test case, need to call the `done(err)` with error to fail the test.
ref: https://mochajs.org/#asynchronous-code
> fix: test cases should fail when it should fail

- site/content/tutorial/15-context/01-context-api/app-a/mapbox.js
- site/content/tutorial/15-context/01-context-api/app-b/mapbox.js
- site/content/tutorial/15-context/01-context-api/text.md
Closes #6870
In the section "[Context API](https://svelte.dev/tutorial/context-api)" of the official tutorial, it's recommended to use empty object literals as context keys since they are guaranteed to be unique, which will prevent any conflict that could otherwise occur if different components use the same string value, for example, as context key.
However, as was explained in the linked issue above, [JavaScript symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) are a more semantically correct construct to use in this case, as cases like this are exactly what symbols are for.
> [docs] Use symbols instead of empty object literals for context keys in tutorial

- src/compiler/compile/Component.ts
- src/compiler/compile/compiler_errors.ts
- src/compiler/compile/nodes/Action.ts
- src/compiler/compile/nodes/Animation.ts
- src/compiler/compile/nodes/InlineComponent.ts
- src/compiler/compile/nodes/Transition.ts
- src/compiler/compile/nodes/shared/Context.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/render_dom/Renderer.ts
- test/validator/samples/illegal-variable-declaration/errors.json
- test/validator/samples/illegal-variable-declaration/input.svelte
fix: https://github.com/sveltejs/svelte/issues/7090
> [fix] Raise compile error if variable name is same as imported variable name

- site/content/examples/17-special-elements/03-svelte-window-bindings/App.svelte
The #each should use the layers as defined in the <script> section so that the parallax works correctly when the layers array is changed
> [docs] fix `#each` in window-bindings example

- CHANGELOG.md
- package-lock.json
- package.json
- src/compiler/compile/css/Stylesheet.ts
- src/compiler/compile/nodes/shared/map_children.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- src/compiler/utils/mapped_code.ts
- src/compiler/utils/push_array.ts
Part of #4694
Also related: https://github.com/Rich-Harris/code-red/pull/71
Alternative to/closes #6716
> [fix] prevent maximum call stack size exceeded error on large pages

- site/content/docs/01-component-format.md
- site/content/docs/02-template-syntax.md
- site/content/docs/03-run-time.md
Fix a few docs links that were using the incorrect fragment.
> [docs] fix broken links

- src/compiler/interfaces.ts
**Description**
Parsing a Svelte component with only markup will return `undefined` for `css`, `instance`, and `module`.
Currently, all properties in the `Ast` interface are required, which can cause type errors.
https://github.com/sveltejs/svelte/blob/d1b3f462a5cfc29283963ad13741f8ef87ea3631/src/compiler/interfaces.ts#L132-L137
**Repro**
```ts
// parser.ts
import { parse } from "svelte/compiler";
const ast = parse("");
console.log(ast.instance.start);
// TypeError: Cannot read properties of undefined (reading 'start')
```
> [fix] mark css/instance/module `Ast` properties as optional

- site/content/faq/450-how-do-i-document-my-components.md
- site/content/faq/500-what-about-typescript-support.md
The code blocks in the FAQ were either missing languages or had the incorrect language (the API used to parse the markdown [requires](https://github.com/sveltejs/action-deploy-docs/blob/42d39f22a94353de238f9e2382645458e1ebb99f/src/format/code.ts#L18) `sv` for Svelte).
https://github.com/sveltejs/sites/pull/297 should be merged and released first so that the correct styles are applied.
See https://github.com/sveltejs/kit/pull/3794#issuecomment-1033963412 for context
> [docs] set language on FAQ code blocks

- site/content/faq/100-im-new-to-svelte.md
Fixed the seemingly erroneous capitalization of "tutorial" in `faq/100-im-new-to-svelte.md`.
Tutorial -> tutorial.
> [doc] fixed seemingly erroneous capitalization of noun

- site/content/tutorial/06-bindings/09-each-block-bindings/text.md
This PR makes a small correction to the ["each block bindings" tutorial](https://svelte.dev/tutorial/each-block-bindings). I believe this PR is in line with the contribution guidelines, but I'm new here, so apologies if anything's off.
I'm working through the Svelte tutorial -- which is great, by the way! -- and noticed a small inconsistency between the displayed example code and the "after" code state that's intended. This PR updates the example code to match the expected result. 
In the previous commit on this file, the missing `{#each}` tags were restored to this example code, which is helpful -- but it left out the `<div>` that wraps the `<input>`s. If a reader were copying from the example into the workspace, they would notice the styles breaking as a result. This change is intended …
> [docs] Add missing parent <div> element to code example in each block bindings tutorial

- .gitignore
- package.json
- src/runtime/action/index.ts
> [feat] action types

- CONTRIBUTING.md
- src/runtime/action/index.ts
> chore: typo

- src/compiler/compile/Component.ts
- test/validator/samples/unreferenced-variables/input.svelte
- test/validator/samples/unreferenced-variables/warnings.json
Fixes #7055
I think this might be the best way to fix the linked issue, and I think it's a reasonable change. Since code inside `<script context="module">` is basically just regular JS, warnings like this can be delegated to userland tools--I don't think it needs to be the Svelte compiler's business especially when these compiler warnings cannot be ignored inline.
> [fix] do not generate unused-export-let inside <script context="module">

- src/compiler/compile/css/Stylesheet.ts
- test/css/samples/css-vars/expected.css
- test/css/samples/css-vars/input.svelte
Fixes #7152, see also #7288
`--foo:;` used to be an invalid CSS custom property value, while `-foo: ;` was valid. By collapsing the whitespace in these declaration values, we were breaking scenarios where an empty custom property was desired.
Note that the spec was updated to [trim whitespace](https://www.w3.org/TR/css-variables-1/#changes-20151203) and treat these values identically, but Chromium browsers still treat `--foo;` as invalid. This was recently [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=1220149) and will be released in Chrome 99, but this would still be a good fix to maintain backwards compatibility.
> [fix] do not collapse whitespace-only css vars

- src/runtime/internal/ssr.ts
- test/server-side-rendering/samples/attribute-escaped-quotes/_expected.html
- test/server-side-rendering/samples/attribute-escaped-quotes/main.svelte
Fixes #7327 and a related security issue.
Attribute values were being `JSON.stringify`ed after being escaped, resulting in escaped characters like `\\` and `\n` to show up in the HTML. The browser _doesn't_ `JSON.parse` attribute values, so the attributes end up with the wrong value.
Succinctly: `<el attr={'\\'}>` renders `<el attr="\\">` gives `el.getAttribute('attr') === '\\\\'`.
The security issue is that objects, on the other hand, were rendered directly to attribute values as unescaped strings. This means an object with a custom `toString()` can result in raw html injection.
See modified tests for more details.
> [fix] attribute values are incorrectly escaped during ssr

- site/content/blog/2017-08-07-the-easiest-way-to-get-started.md
- site/content/blog/2019-04-16-svelte-for-new-developers.md
Default port is now 8080, instead of 5000.
Resolves #7354 
> [docs] Correct default port on blog posts

- CHANGELOG.md
- package.json
The new Action types released in `v3.46.5` (#6538) aren't actually being published to npm, this fixes that
> [fix] include action in package.files

- site/content/blog/2022-04-01-whats-new-in-svelte-april-2022.md
Pretty sure I caught most of the changes in SvelteKit this time... we'll see what @benmccann thinks 😉 
Also decided to leave out all the new icon-wrapper libraries that popped up this month. It was crowding the tools/libraries section.
Note that I'm assuming the current unreleased changes in Svelte are going to be on a minor release. If that's not the case, I'll need to update the version number before posting.
> [docs] "What's new in Svelte" April newsletter

- site/content/blog/2022-04-01-whats-new-in-svelte-april-2022.md
Very nice read btw. Great to see how much is happening all around Svelte.
> Fix typos in `whats-new-in-svelte-april-2022.md`

- site/content/blog/2017-08-07-the-easiest-way-to-get-started.md
See #7412 for backstory.
This PR:
- Explains what REPL means
- Removes incorrect wording about REPL letting you choose from examples
- Adds a link to the examples page
> [docs] #7412: Fix getting started instructions for new users to point at examples and define REPL

- site/content/docs/04-compile-time.md
- mention `vite-plugin-svelte`
- mention SvelteKit and the `package` command. didn't go as far as recommending it yet, but didn't recommend against it either
- update link to point to the relevant portion of tools page
- don't link separately to `rollup-plugin-svelte` and `svelte-loader` as they're already linked to on the SvelteSociety page
> [docs] update bundler documentation

- site/content/docs/02-template-syntax.md
Changed the wording to be more consistent between `<svelte:window>`, `<svelte:body>` and `<svelte:head>`.
Chose "may only appear" over "has to appear" as the latter could be misinterpreted as a compulsory element
> [docs] Change top level requirement wording

- src/compiler/compile/nodes/shared/Expression.ts
- test/runtime/samples/const-tag-each-const/_config.js
- test/runtime/samples/const-tag-each-const/main.svelte
- test/runtime/samples/const-tag-each-duplicated-variable1/_config.js
- test/runtime/samples/const-tag-each-duplicated-variable1/main.svelte
- test/runtime/samples/const-tag-each-duplicated-variable2/_config.js
- test/runtime/samples/const-tag-each-duplicated-variable2/main.svelte
- test/runtime/samples/const-tag-each-duplicated-variable3/_config.js
- test/runtime/samples/const-tag-each-duplicated-variable3/main.svelte
- test/runtime/samples/const-tag-each-function/_config.js
- test/runtime/samples/const-tag-each-function/main.svelte
- test/runtime/samples/const-tag-shadow-2/_config.js
- test/runtime/samples/const-tag-shadow-2/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7206
In addition to https://github.com/sveltejs/svelte/issues/7206, I added support for various more edge cases.
I have tried to cover as much as possible, but please let me know if there are any omissions.
I noticed that the process of `{@const}` is similar to `{#if}`. I looked for a way to completely reuse the processing of `{if}`, but I couldn't implement it.
If you have any ideas on how to do this, I would appreciate your comments.
> [fix] Fix rvalue error when using arrow functions in {@const}

- src/compiler/compile/nodes/SlotTemplate.ts
- test/runtime/samples/const-tag-component-without-let/Component.svelte
- test/runtime/samples/const-tag-component-without-let/_config.js
- test/runtime/samples/const-tag-component-without-let/main.svelte
> [fix] const declared without let: binding get ignored

- site/content/faq/1200-how-do-i-do-hmr.md
Change link for Webpack-loader from svelte-loader-hot, which is deprecated, to official svelte-loader.
> [docs] Fix link to webpack-loader

- site/content/blog/2019-04-15-setting-up-your-editor.md
- site/content/tutorial/01-introduction/07-making-an-app/text.md
With commit bbef991 this blog-entry was marked as a draft, which prevents the page from getting rendered in the svelte-blog. However, over time many contributors added the missing content. Since some pages, e.g. [chapter 1: "Making an app" from the tutorial](https://svelte.dev/tutorial/making-an-app), references to this page, there is a broken link. 
This commit removes the draft-marking which should make the page visible and thus fix the broken links.
> [docs] Remove draft status of setting-up-your-editor blog-entry to fix broken link

- src/compiler/compile/render_dom/wrappers/KeyBlock.ts
- test/runtime/samples/key-block-transition-local/_config.js
- test/runtime/samples/key-block-transition-local/main.svelte
When adding `|local` to a transition inside a {#key} block, only the outro was triggered not the intro.
This PR fixes #5950
(The `@transition_in` was missing the local argument inside the generated "key was changed" code)
> [fix] Local transitions from #key blocks

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/template/_config.js
- test/runtime/samples/template/main.svelte
fix inconsistent rendering of template tags, where text only content is not inserted in the fragment (`.content`) 
elements directly under a template element is non standard, and may break some functionality
for example  `$(template).innerHTML` will be empty when elements are not part of the fragment.
```html
A)<template>123</template>
B)<template>1+2={1+2}</template>
C)<template><b>inside</b></template>
```
for `A`, `B` content is not part of the template fragment(`.content`)
> [fix] textContent should not be set for <template> element.

- site/content/tutorial/01-introduction/05-nested-components/text.md
While going through the tutorial, I didn't notice the 2nd file to edit in the tutorial or the way that Svelte directly uses a component and by this stage in the tutorial had forgot what exactly components themselves are. (They are only mentioned in the intro basics at the very bottom).  Repetition is the key to reinforcement learning, so let's repeat what components are at this critical point of learning.
This fixes all 3 issues and importantly reaffirms what components are.
> [docs] Improve clarity of 2 files to edit and improve learning

- test/runtime/samples/dynamic-element-animation-2/_config.js
- test/runtime/samples/if-block-else-update/_config.js
- test/runtime/samples/inline-style/_config.js
- test/runtime/samples/key-block-component-slot/_config.js
I noticed a lint error in some files at master so fixed it.
> [chore] fix lint

- src/compiler/compile/render_dom/wrappers/RawMustacheTag.ts
- src/runtime/internal/dom.ts
- test/js/samples/each-block-changed-check/expected.js
- test/runtime/samples/svg-html-tag/_config.js
- test/runtime/samples/svg-html-tag/main.svelte
- test/runtime/samples/svg-html-tag2/_config.js
- test/runtime/samples/svg-html-tag2/main.svelte
- test/runtime/samples/svg-html-tag3/_config.js
- test/runtime/samples/svg-html-tag3/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7450, https://github.com/sveltejs/svelte/issues/7002
> [fix] Specify svg namespace if {@html} is used in svg

- site/content/docs/02-template-syntax.md
> If the tag is changed, the children will be preserved unless there's a transition attached to the element.
Child elements are always regenerated when tag is changed. So I removed this sentence.
> If `this` has a nullish value, a warning will be logged in development mode.
Now the warning is not showing. nullish value is officially supported.
So I updated the sentence.
> [docs] fix sentence of `<svelte:element>`

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/dynamic-element-attribute-boolean/_config.js
- test/runtime/samples/dynamic-element-attribute-boolean/main.svelte
- test/runtime/samples/dynamic-element-attribute-spread/_config.js
- test/runtime/samples/dynamic-element-attribute-spread/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7478
> [fix] always use `set_attributes` for attribute of `<svelte:element>`

- site/content/docs/02-template-syntax.md
- src/compiler/compile/compiler_errors.ts
- src/compiler/compile/nodes/ConstTag.ts
- src/compiler/compile/nodes/ElseBlock.ts
- src/compiler/compile/nodes/IfBlock.ts
- src/compiler/compile/nodes/interfaces.ts
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- src/compiler/compile/render_ssr/handlers/EachBlock.ts
- src/compiler/compile/render_ssr/handlers/IfBlock.ts
- test/runtime/samples/const-tag-each-else/_config.js
- test/runtime/samples/const-tag-each-else/main.svelte
- test/runtime/samples/const-tag-if-else-if/_config.js
- test/runtime/samples/const-tag-if-else-if/main.svelte
- test/runtime/samples/const-tag-if-else-outro/_config.js
- test/runtime/samples/const-tag-if-else-outro/main.svelte
- test/runtime/samples/const-tag-if-else/_config.js
- test/runtime/samples/const-tag-if-else/main.svelte
- test/runtime/samples/const-tag-if/_config.js
- test/runtime/samples/const-tag-if/main.svelte
- test/validator/samples/const-tag-placement-1/errors.json
- test/validator/samples/const-tag-placement-2/errors.json
- test/validator/samples/const-tag-placement-2/input.svelte
- test/validator/samples/const-tag-placement-3/errors.json
- test/validator/samples/const-tag-placement-3/input.svelte
Fixes https://github.com/sveltejs/svelte/issues/7241
> [feat] support const tag for if block

- site/content/blog/2022-05-01-whats-new-in-svelte-may-2022.md
let me know if I missed anything!
> [docs] "What's new in Svelte" May newsletter

- site/content/tutorial/01-introduction/03-dynamic-attributes/text.md
1. Noticed the awkward sentence "Just like you can use curly braces to control text, you can use them to control element attributes". Changed it to a sentence easier to understand
2. `src` is an attribute and when the doc referred to attributes, it always puts '~ attribute', so added the 'attribute' description after `src`
3. Removed unnecessary spaces
> [docs] Update introduction/dynamic-attributes

- site/content/docs/02-template-syntax.md
Turns out I kinda lied in #6887 (oops). The order of definition only affects things when the binding is based on the same event (see #7212). Hopefully it should be clear enough now.
Caveat: according to [this SO thread](https://stackoverflow.com/a/9512645), it'll not hold true in old (pre IE8) browsers, but we don't really have to care about that do we?
> [docs] Fix statement about the order of bind: and on:

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/dynamic-element-class-directive/Link.svelte
- test/runtime/samples/dynamic-element-class-directive/_config.js
- test/runtime/samples/dynamic-element-class-directive/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7521
I have checked that the bug has been fixed for all of the REPLs provided by all three people through the issue.
> [fix] Apply class directive for `<svelte:element>` properly

- CHANGELOG.md
https://github.com/sveltejs/svelte/issues/7571 is already fixed by https://github.com/sveltejs/svelte/pull/7531 .
So  I just updated the changelog because this is before release.
> [chore] update changelog

- src/runtime/internal/ssr.ts
- test/server-side-rendering/samples/attribute-escaped-quotes-spread/_expected.html
- test/server-side-rendering/samples/attribute-escaped-quotes-spread/main.svelte
Upon reviewing #5701 I noticed we don't escape attributes when using objects during SSR. This introduces a (small) vulnerability where objects with a custom `toString()` implementation turn seemingly safe components into an XSS vector:
```svelte
<script>
export let attr = undefined;
export let attrs = {};
const safe_attrs = {
foo: 'foo',
bar: 'bar'
};
</script>
{#if attr !== undefined}
Variant 1: <div {...safe_attrs} {attr}/>
{:else}
Variant 2: <div {...attrs}/>
{/if}
<script>
import ActuallyVulnerable from './SeeminglySafe.svelte';
export let untrusted = '"><script>alert("xss")<\/script>';
const model = {
data: untrusted,
// I'm so helpful! Don't you _love_ OOP?
toString() {
return this.data.toString();
}
};
</script>
<ActuallyVulnerable attr={model} />
<ActuallyVulnerable attrs={{ foo: …
```
> [fix] harden attribute escaping during ssr

- site/content/faq/1000-how-can-i-update-my-v2-components.md
And as such the file may as well be removed since probably nobody even remembers v2
Clean up for other v2 references wanted as well?
> [docs] FAQ: The v2 -> v3 converter seems dead

- site/content/tutorial/01-introduction/07-making-an-app/text.md
to have a consistency with what's shown at https://kit.svelte.dev/ like below
```
npm create svelte my-app
cd my-app
npm install
npm run dev -- --open
```
also it feels more natural with `create` than `init`
> Update text.md on site/content/tutorial/01-introduction/07-making-an-app

- src/compiler/compile/css/Stylesheet.ts
- test/css/samples/at-layer/expected.css
- test/css/samples/at-layer/input.svelte
This should resolve #7504. I added a check for `this.node.name === 'layer'` inside the `apply` method of `AtRule`.
Let me know if there's anything else I should do. Thanks!
> [fix]: support `@layer`

- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-no-abstract-roles/input.svelte
- test/validator/samples/a11y-no-abstract-roles/warnings.json
This PR adds an accessibility check on abstract roles. See the [wai-aria 1.1 specification](https://www.w3.org/TR/wai-aria-1.1/#abstract_roles) for more informations. #820 
> [feat] add a11y check on abstract roles

- site/content/tutorial/02-reactivity/02-reactive-declarations/text.md
The sentence "Often, some parts of a component's state need to be computed from other parts (such as a fullname derived from a firstname and a lastname), and recomputed whenever they change." was very confusing and also grammatically incorrect because "and recomputed whenever they change" is a dependent clause.
According to Grammarly, "A dependent clause is a clause that cannot stand as a sentence in its own right, such as before I left the parking lot. When a complex sentence contains a dependent clause like this one, a comma is not used unless the dependent clause comes before the independent clause."
https://www.grammarly.com/blog/comma-in-complex-sentences/#:~:text=A%20dependent%20clause%20is%20a,comes%20before%20the%20independent%20clause.
-  [ ] Run the tests with `npm test` and …
> [docs] update intro sentence of reactive declarations tutorial

- README.md
Just some oversight, the readme still tells users the site is part of the package itself, while it is not in it's own repository.
> Link to sites repository in README.md

- README.md
> [docs] link content to site directory

- src/runtime/internal/dom.ts
- src/runtime/internal/style_manager.ts
- test/runtime/samples/style_manager-cleanup/_config.js
- test/runtime/samples/style_manager-cleanup/main.svelte
- https://github.com/sveltejs/svelte/issues/4801
- https://github.com/sveltejs/svelte/issues/7164
The `style_manager` "cleaned up" the stylesheets it made by only clearing their rules. After clearing them, it removed them from its internal map by running `managed_styles.clear()`. This cleanup was not optimal - it left the style elements empty in the dom.
The proposed change is to remove style-elements created by `style_manager`, instead of making them empty and letting them stay in the DOM without any references. I also refactored some of the methods from the `runtime/internal/dom.ts` file that were only used by the `style_manager` or in the `dom.ts file` itself.
If you want to reverse-engineer this bug …
> [fix] Removal of empty stylesheets created from transitions

- site/content/blog/2019-04-16-svelte-for-new-developers.md
> [docs] update port in "Svelte for new developers" blog.

- src/compiler/compile/compiler_errors.ts
- src/compiler/compile/css/Selector.ts
- test/validator/samples/css-invalid-combinator-selector-1/errors.json
- test/validator/samples/css-invalid-combinator-selector-1/input.svelte
- test/validator/samples/css-invalid-combinator-selector-2/errors.json
- test/validator/samples/css-invalid-combinator-selector-2/input.svelte
- test/validator/samples/css-invalid-combinator-selector-3/errors.json
- test/validator/samples/css-invalid-combinator-selector-3/input.svelte
- test/validator/samples/css-invalid-combinator-selector-4/errors.json
- test/validator/samples/css-invalid-combinator-selector-4/input.svelte
> [fix] error when using combinator incorrectly

- generate-type-definitions.js
- src/runtime/internal/dev.ts
This extends the convenience types of #6770 with
- `ComponentEvents` to get all events of a component
use-case: wrapping a component and re-declaring its events
https://github.com/ivanhofer/sveltekit-typescript-showcase/blob/main/src/03-events/04-%24%24Events/Component.svelte
- `ComponentEvent` to get the type of a single event of a component
use-case: typing an event handler
https://github.com/ivanhofer/sveltekit-typescript-showcase/blob/main/src/03-events/02-typed-event-details/Usage.svelte
- `ComponentSlots` to get all slots of a component
use-case: none, that I currently can think of, but it makes sense to also provide this type helper
> [feat] add convenience type for `ComponentEvents`

- package-lock.json
- package.json
> [chore] upgrade source-map

- src/compiler/preprocess/types.ts
This PR adds a utility to type Svelte preprocessors. It aims to improve the DX for authors writing Svelte preprocessors using TypeScript. It was inspired by https://github.com/sveltejs/svelte/pull/7121, which added a utility `Action` type to strongly type Svelte actions.
**Current DX**
The current workflow is to use the `PreprocessorGroup` type.
```ts
import type { PreprocessorGroup } from "svelte/types/compiler/preprocess";
function preprocessor(): Pick<PreprocessorGroup<"markup">> {
return {
markup({ content }) {
return { code: content };
},
};
}
```
However, since a preprocessor is usually a function that returns a function to allow user-provided options, it would be more concise for a utility type to select from the various groups (markup/style/script) and optionally add a generic …
> [feat] add `SveltePreprocessor` utility type

- site/content/docs/02-template-syntax.md
simple typo. this transition is just a fade.
> [fix] typo in transition docs

- src/runtime/internal/dom.ts
Fixes #7723.
This is for a simple legacy browsers compatibility (specifically, IE11).
> [fix] use `Node.parentNode` instead `Node.parentElement` in `dom.ts`.

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/class-shortcut-with-transition/_config.js
- test/runtime/samples/class-shortcut-with-transition/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7764
Class attributes were reset if outro existed and element had not yet been destroyed.
But class directive was not like that.
This PR fixed this issue.
> [fix] Apply class directive after half way transition

- src/compiler/compile/render_ssr/index.ts
- src/compiler/parse/index.ts
close #7675
This PR uses `trimRight()` instead of `replace(/\s+$/, '')` to improve parsing performance.
See the https://github.com/sveltejs/svelte/issues/7675#issuecomment-1179995722 for issues with the original regex.
If you know how to add a test to check performance, please let me know.
I ran the following test locally and I checked that it would improve performance.
```js
import { parse } from '../../compiler.js';
describe('improve performance', () => {
it('parse', () => {
parse(`<div>${' '.repeat(1000000)}</div>`);
});
});
```
> [fix] Improve performance by using trimRight() instead of regex replace

- src/runtime/action/index.ts
Allows a way to tell language tools which additional attributes and events the action brings to the HTML element
Related https://github.com/sveltejs/language-tools/pull/1553
> [feat] enhance action typings

- site/content/faq/900-is-there-a-router.md
I figured we didn't need to mention the RC as it'd just be one more thing to update when we get to the final version
We should probably update the homepage as well, but that lives in the `sites` repo and would have to be a separate PR
> [docs] remove beta label from SvelteKit mention

- src/compiler/compile/render_dom/wrappers/Head.ts
- src/compiler/compile/render_ssr/handlers/Element.ts
- src/compiler/compile/render_ssr/handlers/Head.ts
- src/runtime/internal/dom.ts
- test/hydration/samples/head-html-and-component/HeadNested.svelte
- test/hydration/samples/head-html-and-component/Nested.svelte
- test/hydration/samples/head-html-and-component/_after_head.html
- test/hydration/samples/head-html-and-component/_before_head.html
- test/hydration/samples/head-html-and-component/main.svelte
- test/hydration/samples/head-meta-hydrate-duplicate/_after_head.html
- test/hydration/samples/head-meta-hydrate-duplicate/_before_head.html
- test/server-side-rendering/samples/head-html-and-component/HeadNested.svelte
- test/server-side-rendering/samples/head-html-and-component/Nested.svelte
- test/server-side-rendering/samples/head-html-and-component/_expected-head.html
- test/server-side-rendering/samples/head-html-and-component/_expected_head.html
- test/server-side-rendering/samples/head-html-and-component/main.svelte
- test/server-side-rendering/samples/head-meta-hydrate-duplicate/_expected-head.html
Fixes `@html` (#7444, #6463) expressions and nested components (#4533) duplication in a `svelte:head` tag on hydration.
- Problem
Adding a `@html` expression or `<Component />` within a `<svelte:head>` ends up duplicated after hydration.
- Why?
Attribute `data-svelte="head_id"` was added only to nearest child elements and hydration claim was based exclusively on getting elements with that attribute. `@html`expressions and components were left without any `data-svelte` attribute and could not be found by the claim logic and end up recreated.
- Solution
Deprecate `data-svelte` attribute for nearest child elements and wrap the whole head content with 2 comments:
*  ``
*  ``
Inspired by @hbirler [comment](https://github.com/sveltejs/svelte/issues/6463#issuecomment-889430684) `HTML_TAG_X` …
> [fix] Fix hydration duplicate `svelte:head` tag issue with `@html` expressions and nested components

- src/runtime/internal/dev.ts
- test/runtime/samples/dynamic-element-void-with-content-1/_config.js
- test/runtime/samples/dynamic-element-void-with-content-2/_config.js
- test/runtime/samples/dynamic-element-void-with-content-3/_config.js
- test/runtime/samples/dynamic-element-void-with-content-5/_config.js
- test/runtime/samples/dynamic-element-void-with-content-5/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7566
I tried to add check logic for the issue but I didn't get a good idea.
I think the issue is an actual use case, so for now, throwing a warning instead of an error is a reasonable solution.
If you have any ideas, please share us.🙏
> [fix] throw warning instead of error if <svelte:element> is void tag and content exists

- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/nodes/AwaitBlock.ts
- src/compiler/compile/nodes/Binding.ts
- src/compiler/compile/nodes/ConstTag.ts
- src/compiler/compile/nodes/EachBlock.ts
- src/compiler/compile/nodes/shared/Context.ts
- src/compiler/compile/render_dom/wrappers/shared/mark_each_block_bindings.ts
- test/validator/samples/rest-eachblock-binding-2/input.svelte
- test/validator/samples/rest-eachblock-binding-2/warnings.json
- test/validator/samples/rest-eachblock-binding-3/input.svelte
- test/validator/samples/rest-eachblock-binding-3/warnings.json
- test/validator/samples/rest-eachblock-binding/input.svelte
- test/validator/samples/rest-eachblock-binding/warnings.json
Fixes: https://github.com/sveltejs/svelte/issues/6860
> [fix]: Warn user when binding rest operator

- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties-dynamic/Slider.svelte
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties-dynamic/_config.js
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties-dynamic/main.svelte
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties/Slider.svelte
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties/Slider1.svelte
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties/Slider2.svelte
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties/_config.js
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties/main.svelte
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties2/Slider1.svelte
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties2/Slider2.svelte
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties2/_config.js
- test/runtime-puppeteer/samples/svelte-component-css-custom-properties2/main.svelte
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties-dynamic/Slider.svelte
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties-dynamic/_config.js
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties-dynamic/main.svelte
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties/Slider1.svelte
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties/Slider2.svelte
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties/_config.js
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties/main.svelte
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties2/Slider1.svelte
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties2/Slider2.svelte
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties2/_config.js
- test/runtime-puppeteer/samples/svelte-self-css-custom-properties2/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7461
I needed duplicate code for implementing this, so I did refactoring in the last commit for removing it.
Question: Do we need to update the document?
> [feat] support `--style-props` for `<svelte:component>`

- site/content/docs/05-accessibility-warnings.md
- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/utils/a11y.ts
- test/validator/samples/a11y-click-events-have-key-events/input.svelte
- test/validator/samples/a11y-click-events-have-key-events/warnings.json
Implements click-events-have-key-events lint rule from #820.
> feat(a11y): add click-events-have-key-events rule

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/runtime/internal/dom.ts
- test/runtime-puppeteer/samples/dynamic-element-custom-element/_config.js
- test/runtime-puppeteer/samples/dynamic-element-custom-element/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7733
> [fix] call attribute bindings for custom element if <svelte:element> render custom element

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/js/samples/svelte-element-svg/expected.js
- test/runtime/samples/dynamic-element-svg/_config.js
- test/runtime/samples/dynamic-element-svg/main.svelte
And...
https://github.com/sveltejs/svelte/pull/7766 broke a test what https://github.com/sveltejs/svelte/pull/7695 added.
I think https://github.com/sveltejs/svelte/pull/7695 tests should move to runtime dir for maintainability.
So I moved it.
> [feat] skip custom element check if <svelte:element> uses under svg

- site/content/blog/2022-10-01-whats-new-in-svelte-october-2022.md
Let me know if I missed anything! Especially SvelteKit features/breaking changes... there was a lot of breaking changes - not all of them seemed important, though
>  [docs] "What's new in Svelte" October newsletter

- .github/workflows/ci.yml
- .github/workflows/docs.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- site/content/docs/02-component-format.md
Based on the fact that multiple issues were opened related to a perceived bug on the reactive variables, I thought it would be good to add a clarification on the docs. Part of the text is taken from [this comment](https://github.com/sveltejs/svelte/issues/7818#issuecomment-1230374639) that I found super useful.
> [docs] Add clarification on how reactivity works

- src/compiler/compile/render_dom/index.ts
- test/js/samples/capture-inject-state/expected.js
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/runtime/samples/dev-warning-missing-data-component-bind/Foo.svelte
- test/runtime/samples/dev-warning-missing-data-component-bind/_config.js
- test/runtime/samples/dev-warning-missing-data-component-bind/main.svelte
Fixes #4457 
have to move the warning to `onmount`, as the binding happens after the component is instantiated.
> [fix] do not warn about missing props for bindings

- src/runtime/internal/lifecycle.ts
The runtime functions `onMount` etc. have no inline documentation. To improve the DX, I added inline documentation from the (website) docs. VSCode and other IDEs show an explanation of those functions directly in the IDE now. 
**Before**
**After**
> [docs] add inline documentation to svelte runtime functions

- site/content/docs/01-getting-started.md
Fix typo and tweak getting started docs.
@benmccann made this suggestion in https://github.com/sveltejs/svelte/pull/7812#discussion_r957772699, but doesn't look like it made it in.
> [docs] fix typo in getting started

- site/content/docs/06-accessibility-warnings.md
- src/compiler/compile/compiler_warnings.ts
- test/validator/samples/a11y-no-nointeractive-tabindex/warnings.json
This is a minor grammar change. I believe ["noninteractive"](https://www.merriam-webster.com/dictionary/noninteractive) is more common when using it as an adjective. It's also consistent with the a11y warning name (`a11y-no-noninteractive-tabindex`).
> [fix] "not interactive" -> "noninteractive"

- .github/workflows/ci.yml
I've noticed you are using old versions of `actions/*` actions. Let's bump them.
> [chore] Bump actions' versions

- src/compiler/compile/render_ssr/handlers/Head.ts
- test/server-side-rendering/index.ts
- test/server-side-rendering/samples/head-meta-hydrate-duplicate/_config.js
In the server-side-rendering test, we did not assert compare for the comments
so even though the generated comments looks different, the test didnt fail.
the bug arises when using 
```js
x`'foo_${variable}_something'`
```
the generated code dropped what comes after `${variable}`.
leading to
```js
x`'foo_xxx'
```
this is obviously a code-red bug, but this PR is a temporary workaround the issue
> [fix] duplicate meta tags during hydration

- .github/workflows/ci.yml
- .mocharc.unit.js
- package.json
- scripts/skip_in_ci.js
- updates the CI script
- runs a `Setup` job which prebuilds the svelte compiler before running the tests on each node version
- specify `SKIP_PREPARE=true` in `install` commands, since we already pre-build.
- as it will run `prepare` to build again
- previously tried `--ignore-scripts` but that will ignore all scripts, including the `postinstall` in the dependencies, as such the browser tests failed as `puppeteer` uses `postinstall` to download the browser
- fix the `test:unit` script
- I am assuming the script is meant to just run the unit tests, therefore it is run as a separate pipeline as the `Test` job
- however the command also runs the `Tests`, that's because it is sharing the same `.mocharc.js`
- removes `pretest` that does `npm run build`
- since `test` is mainly 
- run by CI …
> [feat] pre-build before testing in CI

- .github/workflows/ci.yml
related: https://github.com/sveltejs/svelte/pull/7933
- Use latest `actions/checkout` and `actions/setup-node`.
- Use `actions/upload-artifact` instead of `actions/cache`.
- Less lines to implement
- There is no need to worry about cache capacity limitations
- There is no need to worry about cache corruption (Rarely cache is broken)
- Add branches filter (This is not related to #7933, but stopping needless CI is environmentally friendly)
> [chore] Improve CI

- site/content/examples/15-composition/03-slot-props/App.svelte
Fixes the browser-quirk-related issue described in #6520 and #7867, based on a [suggestion](https://github.com/sveltejs/svelte/issues/7867#issuecomment-1248993436) by @Prinzhorn.
Tested in the editable example area on the Svelte site: https://svelte.dev/examples/slot-props
> [docs] ensure `onmouseleave` event fires in hoverable example

- site/content/docs/02-component-format.md
Fix the typo "bellow" to "below"
> [docs] Fix typo in 02-component-format.md

- src/runtime/internal/dom.ts
Fixes #6037 
As mentioned here: https://github.com/sveltejs/svelte/issues/6037#issuecomment-928093190
This bug was fixed in prior versions (https://github.com/sveltejs/svelte/issues/2086#issuecomment-490989491) but brought back when it was caught in a revert (https://github.com/sveltejs/svelte/commit/6d16e9260642b1fcc70fa4a24be9fd49985112d1).
I encountered this bug when trying to write a wrapper over Maplibre-GL, where as a part of the components lifecycle, slots would get cleaned up by the library before svelte unmounted the component, thus throwing this error.
> [fix] check parentNode exists before removing child

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/security-anchor-rel-noreferrer/input.svelte
fixes #7994 
~~this always logs the warning for dynamic rel values, if that includes noreferrer, users have to disable the warning with a comment or onwarn handler~~
Alternative would be to only log for static values but that leaves some users unaware if they don't have it in their dynamic value.
edit: switched to warning for static only, see below.
> [fix] only read static value for rel attribute validation

- CHANGELOG.md
- src/compiler/compile/index.ts
> [fix] don't emit deprecation warning for now

- package-lock.json
- package.json
- rollup.config.js
this is needed for running the Svelte compiler in the browser again. Some package requires the builtin 'node' package which isn't bundled but also not available in the browser, so the REPL is broken. This slipped in through some dependency bump I guess.
Fixes #8010
I decided against using `rollup-plugin-node-builtins` because that one's quite outdated and ships a bunch of stuff we don't need
> [fix] util polyfill to make compiler self-contained

- site/content/blog/2022-12-01-whats-new-in-svelte-december-2022.md
First draft only includes Svelte and Kit changes. I couldn't find any other `svelte/*` changes and am a bit behind due to the US holiday.
I wanted to push this in case I missed anything while I work on the showcase over the next day or two.
Thanks!
Dani
> [docs] "What's new in Svelte" December newsletter

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-aria-role/input.svelte
- test/validator/samples/a11y-aria-role/warnings.json
Right now, multiple aria roles separated by space on the same element will throw a `a11y-unknown-role` warning.
I didn't find a test for success - so I adapted the existing.
For example, `role="row button"` will throw a warning for the unknown role `row button` - but should actually validate `row` and `button` individually.
The `role` attribute is a set of [space separated tokens](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#space-separated-tokens). If the first token is not accessibility supported (or valid), the next one will be used for determining the semantic role of the element, and so forth.
Reference: #8044 
> [fix] a11y - allow fallback roles

- src/compiler/compile/utils/a11y.ts
- test/validator/samples/a11y-no-nointeractive-tabindex/input.svelte
- test/validator/samples/a11y-no-nointeractive-tabindex/warnings.json
[This comment](https://github.com/sveltejs/svelte/pull/6693#issuecomment-1277580534) on the original PR for the feature explains the issue. Elements with the role `tabpanel` are a special exception to the rule of noninteractive elements having a positive tab index. It is recommended that tab panels have a positive tabindex when their first element is not focusable. 
- [Link to relevant section in Aria docs](https://w3c.github.io/aria-practices/#keyboard-interaction-21)
- [This Example](https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-automatic) in the Aria Authoring guides also recommends allowing a positive tabindex for tab panels. 
Adding this will get rid of annoying error for people who are trying to implement accessible tab panels in their code.
- Updated the unit test for …
> [fix] Update A11y no noninteractive element with positive tabindex warning to ignore tabpanel role.

- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/runtime/internal/Component.ts
- test/runtime/samples/binding-no-unnecessary-invalidation/Tab.svelte
- test/runtime/samples/binding-no-unnecessary-invalidation/_config.js
- test/runtime/samples/binding-no-unnecessary-invalidation/main.svelte
Fixes part of #7032
Fixes #6298
I'm honestly not sure how this didn't cause a "variable defined in parent component gets set to undefined by child" bug previously - does this hint at a deeper problem?
While testing I noticed another infinite loop, which happens when I add `<div bind:this={row.div}>foo</div>` to the each loop in [this reproducible](https://svelte.dev/repl/86b8b83f2e2b475e8e92aaa4df9c7da2?version=3.44.3). The problem is the bind this binding invalidating the component, causing another flush, causing another each-loop traversal, causing another binding invalidation, etc. I don't know how to fix this right now so I left that out.
> [fix] don't run binding init unnecessarily

- site/content/tutorial/09-motion/02-spring/app-b/App.svelte
This fixes an inconsistency I found in the svelte/motion spring tutorial where app-a has `margin: -8px` on the svg but app-b doesn't.
> [docs] fix inconsistent margin in svelte/motion spring tutorial

- site/content/docs/03-template-syntax.md
fix https://github.com/sveltejs/svelte/issues/7825
fix https://github.com/sveltejs/svelte/issues/7454
fix https://github.com/sveltejs/svelte/issues/7657
> [docs] add explanation about property binding order

- site/content/docs/01-getting-started.md
We're seeing many of our students trip up because Svelte Getting Started guide only generates applications that require NodeJS on the server.
This PR adds a line in the "Getting Started" section about how to generate frontend-only sites/apps while using NodeJS and Svelte for local development.
> [docs] Add comment about generating a Svelte project without Kit

- site/content/tutorial/01-introduction/07-making-an-app/text.md
The Svelte [_Tutorial > Introduction > Making an app_](https://svelte.dev/tutorial/making-an-app) page implies SvelteKit is still pre-1.0. Now that SvelteKit 1.0 has been released, this should be updated.
-  [ ] N/A - Run the tests with `npm test` and lint the project with `npm run lint`
> [docs] update outdated SvelteKit release info

- site/content/docs/03-template-syntax.md
It's "both", not "bidirectional" (see #8068).
"bidirectional" was suggested as an alternative, but the implementation uses "both".
> [docs] fix transition direction options

- .github/workflows/ci.yml
- test/custom-elements/index.ts
- test/runtime-puppeteer/index.ts
Last few months, CI on Linux is broken.
I checked the reason and I found that Puppeteer can not run properly with Node8 on Linux.
I couldn't find a way to run it properly, therefore I stop to run Puppeteer tests with Node8 on Linux.
Also after updating Puppeteer, still it doesn't run properly with Node10 on Linux, so I did the same way for Node10 also.
> [chore] Fix CI

- site/content/docs/06-accessibility-warnings.md
- src/compiler/compile/compiler_warnings.ts
- test/validator/samples/a11y-no-nointeractive-tabindex/warnings.json
`a11y-no-noninteractive-tabindex` says "noninteractive element cannot have positive tabIndex value" but denies a tabIndex value of zero, and zero is not positive. "Nonnegative" (or similar) is more correct wording.
> [fix] say "nonnegative" instead of "positive" tabIndex

- src/runtime/transition/index.ts
Signed-off-by: Gus Wezerek <gustav.wezerek@nytimes.com>
closes [#6816](https://github.com/sveltejs/svelte/issues/6816):
**Describe the bug**
When the stroke-linecap is set to something other than "butt," a small dot is visible at the beginning of a path. This is only visible when applying a delay to the transition. This can be a problem if you have multiple paths and want them to be displayed one after the other.
**Proposed solution**
(tested locally) The transition could instead rely on stroke-dashoffset.
Reproduction
https://svelte.dev/repl/5b62eb46687d4e219b970b38154705fa
> [fix] Fix bug with transition draw when delay is passed

- sites/svelte.dev/package-lock.json
- sites/svelte.dev/package.json
- sites/svelte.dev/src/config.js
- sites/svelte.dev/src/routes/(authed)/repl/[id]/+page.svelte
- sites/svelte.dev/src/routes/(authed)/repl/[id]/AppControls.svelte
- sites/svelte.dev/src/routes/+layout.svelte
- sites/svelte.dev/src/routes/_components/Demo.svelte
- sites/svelte.dev/src/routes/_components/Section.svelte
- sites/svelte.dev/src/routes/_components/Supporters/index.svelte
- sites/svelte.dev/src/routes/_components/WhosUsingSvelte/index.svelte
- sites/svelte.dev/src/routes/blog/+page.svelte
- sites/svelte.dev/src/routes/blog/[slug]/+page.svelte
- sites/svelte.dev/src/routes/examples/[slug]/+page.svelte
- sites/svelte.dev/src/routes/examples/[slug]/_TableOfContents.svelte
- sites/svelte.dev/src/routes/tutorial/[slug]/+page.svelte
- sites/svelte.dev/src/routes/tutorial/[slug]/_TableOfContents.svelte
Fixes all elements for dark mode
> feat: Proper dark mode

- site/content/docs/03-template-syntax.md
There was a small typo in the docs animation docs, where there's a semi-colon mid-way through the object, causing an error (`Expected "}" but found ";"`). This PR corrects that, by replacing it with the expected comma.
For reference, this was in the docs, [here](https://svelte.dev/docs#template-syntax-element-directives-animate-fn-custom-animation-functions) - under Template Syntax --> Element Directives --> animate:fn --> Custom animation functions
> docs: corrects syntax error in transition code sample

- elements/index.d.ts
Corresponding changes for data-sveltekit-replacestate addition within SvelteKit: https://github.com/sveltejs/kit/pull/9019
Also related: https://github.com/sveltejs/language-tools/pull/1865
> feat: Add -replacestate/-keepfocus to SvelteKit anchor tag props

- site/content/docs/04-run-time.md
The PR is intended to fix the fly transition definition. It was stated that:
> `in` transitions animate from an element's current (default) values to the provided values, passed as parameters. `out` transitions animate from the provided values to an element's default values.
and 
> * `x` (`number`, default 0) - the x offset to animate out to and in from
> * `y` (`number`, default 0) - the y offset to animate out to and in from
> * `opacity` (`number`, default 0) - the opacity value to animate out to and in from
which are both incompatible. I reversed the definition to:
> `in` transitions animate **from the provided values, passed as parameters to the element's default values**. `out` transitions animate **from the element's default values to the provided values**.
-  [ ] Run the tests …
> docs: fix `fly` animation description

- site/content/examples/15-composition/05-modal/App.svelte
- site/content/examples/15-composition/05-modal/Modal.svelte
The [modal](https://svelte.dev/examples/modal) example is based on `<div>` elements.
Since the `<dialog>` element is now [widely supported](https://caniuse.com/dialog), I propose a rewrite.
The following features are supported. Please check the [demo](https://svelte.dev/repl/bbe203121c094add9de669f3e5d35d8b?version=3.55.1).
- close modal by clicking on the modal's backdrop
- focus on the `show modal` button when closed
- press `esc` key to close modal - `<dialog>` feat.
- keep tab focus inside the modal - `<dialog>` feat.
- (optional) show animation on `.showModal()`
> docs: update dialog example

- src/compiler/compile/css/Selector.ts
- test/css/samples/unused-selector-empty-attribute/_config.js
- test/css/samples/unused-selector-empty-attribute/expected.css
- test/css/samples/unused-selector-empty-attribute/expected.html
- test/css/samples/unused-selector-empty-attribute/input.svelte
Long time user, first time contributor
The following code doesn't report a "Unused CSS selector" warning:
```svelte
<style>
img[alt=""] {
border: 1px solid red;
}
</style>
```
Fixes: https://github.com/sveltejs/svelte/issues/8042
> fix: empty value attribute selector doesn't produce "Unused CSS selector" warning

- site/content/tutorial/16-special-elements/08-svelte-options/app-a/Todo.svelte
- site/content/tutorial/16-special-elements/08-svelte-options/app-b/Todo.svelte
Use button instead of non-interactive element (div).
(Removes a Svelte a11y warning.)
> docs: Fix accessibility of options tutorial.

- src/compiler/parse/index.ts
- src/compiler/parse/read/script.ts
- src/compiler/parse/read/style.ts
- src/compiler/parse/state/mustache.ts
- src/compiler/parse/state/tag.ts
- fast path for attribute quote marks common case
- all regexes exclusively passed into read or match_regex which are only successful if matched at the beginning are altered so that the regex has this condition built in, preventing it from searching past the start index
closes #7663 - huge thanks to @MathiasWP for starting this thought process. the changes in there are not necessary to that extent to get the perf improvements, it's enough to handle the common case of quote marks and having a regex with the additional `^` condition.
> chore: improve parser performance

- site/content/docs/06-accessibility-warnings.md
- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-aria-activedescendant/input.svelte
- test/validator/samples/a11y-aria-activedescendant/warnings.json
Hey everyone, I have added the aria-activedescendant-has-tabindex rule, currently not implemented yet, mentioned in the A11y post (#820). 
Please let me know if you have any improvements, edits, suggestions, etc. Thank you and you all have a good time!
> feat: implement a11y `aria-activedescendant-has-tabindex`

- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
Fixes  #7027 
https://user-images.githubusercontent.com/25841814/148650013-427af183-6db1-4ab2-8f5f-bfa14c8465a5.mov
when typing with IME (used for some lang like Chinese, Japanese, Korean), it'd trigger updating more than once (see video above). 
this PR is for adding input value comparison for search & url input
however, it's hard to test IME behavior. so it's no testing for IME in this PR (but current testing're all passed)
> [fix] Prevent Duplicate updating for input with IME

- site/content/tutorial/06-bindings/05-textarea-inputs/text.md
I am not a good developer, and I spent a long time trying to figure out the difference between the code with and without the bind. It probably seems clear that I should've figured it out, but adding a statement to show how to invoke the changes might help another person like me. A prompt to type in the DOM could help somebody more quickly pass this level.
> docs: describe that `bind:value` creates a two-way binding

- package-lock.json
- package.json
- src/compiler/preprocess/decode_sourcemap.ts
`sourcemap-codec` has been archived in favor of `@jridgewell/sourcemap-codec`
As follow-ups, we will also need to merge:
- https://github.com/Rich-Harris/code-red/pull/74
And upgrade:
- @ampproject/remapping (causes `generate-type-definitions` to fail - may need to happen as part of Svelte 4?)
- magic-string (causes a sourcemap test to fail - better to do this separately to investigate)
> chore: switch to @jridgewell/sourcemap-codec

- site/content/docs/03-template-syntax.md
close: https://github.com/sveltejs/svelte/issues/8056
close: https://github.com/sveltejs/svelte/pull/8057
According to the https://github.com/sveltejs/svelte/pull/8057#issuecomment-1336118413, I updated the document.
> docs: Add way to use regular `<slot>` element

- src/shared/boolean_attributes.ts
- test/runtime/samples/attribute-boolean-indeterminate/_config.js
It's only existing as a boolean property
cleanup of #7944
> fix: remove indeterminate from boolean attributes

- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/debug-no-dependencies/expected.js
- test/js/samples/deconflict-builtins/expected.js
- test/js/samples/each-block-array-literal/expected.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/each-block-keyed-animated/expected.js
- test/js/samples/each-block-keyed/expected.js
- test/runtime/samples/component-binding-each-remount-keyed/Child.svelte
- test/runtime/samples/component-binding-each-remount-keyed/InnerChild.svelte
- test/runtime/samples/component-binding-each-remount-keyed/_config.js
- test/runtime/samples/component-binding-each-remount-keyed/main.svelte
- test/runtime/samples/component-binding-each-remount-unkeyed/Child.svelte
- test/runtime/samples/component-binding-each-remount-unkeyed/InnerChild.svelte
- test/runtime/samples/component-binding-each-remount-unkeyed/_config.js
- test/runtime/samples/component-binding-each-remount-unkeyed/main.svelte
fix: https://github.com/sveltejs/svelte/issues/8282
----------------------------------
Bug can be seen in console https://svelte.dev/repl/1c3da5d4744c4820a1e9187f23fc6bbe?version=3.48.0
In my case, Firefox says `TypeError: can't access property "m", each_blocks[i] is null`
Several conditions and steps required:
* There must be UNKEYED each block with component binding
* Later on an array should be updated with lesser length, so holes would be produced
* Somehow remount children, e.g. wrap all with keyed each and update it
* This produces the code `each_blocks[i].m(...)`  without "is not null" check and it fails
* I've added 2 test cases, one with keyed each (passes on master) and similar without key (fails on …
> fix: check each_blocks is empty on mount

- site/content/docs/04-run-time.md
- src/runtime/transition/index.ts
First of all: this is my first ever PR and I have to thank all the developers of svelte for sparking my passion when it comes to WebDevelopment. Because .svelte files really embrace the basic web-technologies, it made frameworks so much more accessible! I was always deterred from becoming a web-developer due to (perceived) complexity, but svelte finally opened up this possibility for me! Thank you!
Because I am relatively new, please make sure to double check my code for bad practices or coding errors!
Please point out to me if I made any formal errors with this PR besides the test cases I was to inexperienced to write.
I created an issue for this feature request myself earlier today: #6182 . 
Basically, I am proposing to expand the parameters the slide transition takes in, in order to …
> [feat] Introduce parameter to allow for horizontal slide transition

- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-aria-activedescendant/input.svelte
- test/validator/samples/a11y-click-events-have-key-events/input.svelte
- test/validator/samples/a11y-no-noninteractive-tabindex/input.svelte
- test/validator/samples/a11y-no-noninteractive-tabindex/warnings.json
- test/validator/samples/a11y-role-has-required-aria-props/input.svelte
- test/validator/samples/a11y-scope/input.svelte
- test/validator/samples/a11y-scope/warnings.json
Some a11y warnings only work on specific tags, which results in potential false positives for `<svelte:element>` tags - silence those closes #7939
> fix: hide some a11y warnings for `<svelte:element>` tags

- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- src/compiler/utils/extract_svelte_ignore.ts
- test/validator/samples/component-dynamic/input.svelte
Fixes #8082, where svelte-ignore somehow does not pick up the reactive-component warning.
The issue on this problem is that the `map_children` function suppresses warnings and errors while traversing AST nodes as `src/compiler/compile/nodes` classes. However, the `reactive-component` warning is called in `src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts`, and its warnings are not suppressed in `map_children`. Thus, we need to extract ignores and suppress here separately.
> fix: svelte-ignore doesn't work with reactive-component 

- src/compiler/compile/compiler_errors.ts
- src/compiler/compile/css/Selector.ts
- test/validator/samples/css-invalid-global-placement-4/errors.json
- test/validator/samples/css-invalid-global-placement-4/input.svelte
fixes: https://github.com/sveltejs/svelte/issues/6272
add some simple validations to not allow type or universal selector to appear ```:global(...)``` unless if ```:global(...)``` is the first
> [fix] add global compound selector validations

- site/content/docs/06-accessibility-warnings.md
Convert recommended events to use Svelte syntax, and include deprecation warning re https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event
> fix: Update 06-accessibility-warnings.md

- src/compiler/compile/render_dom/Block.ts
- src/compiler/compile/render_dom/Renderer.ts
- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/runtime/internal/dom.ts
- src/runtime/internal/keyed_each.ts
- test/runtime/samples/binding-input-group-each-10/_config.js
- test/runtime/samples/binding-input-group-each-10/main.svelte
- test/runtime/samples/binding-input-group-each-11/_config.js
- test/runtime/samples/binding-input-group-each-11/main.svelte
- test/runtime/samples/binding-input-group-each-12/_config.js
- test/runtime/samples/binding-input-group-each-12/main.svelte
- test/runtime/samples/binding-input-group-each-13/_config.js
- test/runtime/samples/binding-input-group-each-13/main.svelte
- test/runtime/samples/binding-input-group-each-8/_config.js
- test/runtime/samples/binding-input-group-each-8/main.svelte
- test/runtime/samples/binding-input-group-each-9/_config.js
- test/runtime/samples/binding-input-group-each-9/main.svelte
Fixes #7633, Fixes #6112, Fixes #7884
- `bind:group` depends on keeping an array of `<input>` element references, such that at any point of time, we can sync the bound variable to the DOM / DOM to the bound variable.
- however when using `bind:group` with `{#each}` loops and `bind:group` to each item, we need a list of arrays, to separate the each group of inputs. with nested `{#each}` loops, we have a matrix of arrays.
- to reference to the input array, we use the `{#each}` index as path. eg:
```svelte
{#each array_1 as item_1, index_1}
{#each array_2 as item_2, index_2}
<input bind:group={item_2} />
<input bind:group={item_2} />
{/each}
{/each}
``` 
we reference to the binding_groups via `$$binding_groups[index_1][index_2]`
- however this may cause issue when we update the each loop by …
> feat: improve `bind:group` behavior

- package-lock.json
- package.json
- src/compiler/compile/css/Selector.ts
- src/compiler/compile/css/Stylesheet.ts
- test/sourcemaps/samples/compile-option-dev/test.js
Version 0.25.5 makes the existing tests fail
> chore: upgrade magic-string

- package-lock.json
- package.json
- src/compiler/compile/Component.ts
Modern ESM-only version that replaces `sourcemap-codec` with `@jridgewell/sourcemap-codec`
> chore: upgrade to code-red 1.0

- src/runtime/internal/scheduler.ts
This should appease Agadoo's treeshaking test, by marking `Promise.resolve()` as pure, so Rollup can shake it out. It might also have a miniscule benefit for people who are using Rollup to bundle their app but aren't using this promise.
This should fix the local build failure that is currently blocking cutting a new release. I don't think this warrants a changelog entry.
> chore: mark Promise.resolve() as pure to appease Agadoo

- src/runtime/store/index.ts
- test/store/index.ts
Fixes https://github.com/sveltejs/svelte/issues/8364
When a derived store was unsubscribed from another store sharing a common ancestor, the ancestors update loop would restart the store after it had already been stopped. This PR renames the existing `inited` boolean to `started` to be more clear about its function and resets it to `false` once the store has been stopped so `sync()` isn't  run on a cold store.
> fix: derived store restarting when unsubscribed from another store with a shared ancestor

- src/compiler/compile/nodes/shared/Context.ts
- test/runtime/samples/await-then-destruct-number-props/_config.js
- test/runtime/samples/await-then-destruct-number-props/main.svelte
- test/runtime/samples/await-then-destruct-string-props/_config.js
- test/runtime/samples/await-then-destruct-string-props/main.svelte
- test/runtime/samples/const-tag-await-then-destructuring-literals/_config.js
- test/runtime/samples/const-tag-await-then-destructuring-literals/main.svelte
- test/runtime/samples/const-tag-each-destructure-literals/_config.js
- test/runtime/samples/const-tag-each-destructure-literals/main.svelte
- test/runtime/samples/each-block-destructured-array-as-object/_config.js
- test/runtime/samples/each-block-destructured-array-as-object/main.svelte
- test/runtime/samples/each-block-destructured-object-literal-props/_config.js
- test/runtime/samples/each-block-destructured-object-literal-props/main.svelte
- test/runtime/samples/each-block-destructured-object-literal-rest/_config.js
- test/runtime/samples/each-block-destructured-object-literal-rest/main.svelte
Part of #6609.
In [each blocks](https://svelte.dev/docs#template-syntax-each), [await then/catch blocks](https://svelte.dev/docs#template-syntax-await), and [`@const` tags](https://svelte.dev/docs#template-syntax-const), we are allowed de-structure objects, like so: 
```{#each array as [first, second, ..rest]}```
```
{#await promise}
{:then { prop1, prop2, ...rest} }
{/await}
```
```{@const { firstProp, secondProp } = obj}```
The `Not implemented Empty` error happens because the compiler doesn't pick up properties in de-structured objects in those blocks that are not identifiers, like literals `{@const { "prop-in-quotes": propInQuotes } = obj}`, and computed props, like `{@const { [var1 + var2]: computedProp } = obj}`
Right now, I don't know how best to fix the computed property case, so …
> fix: object destructring picks up literal properties

- src/compiler/compile/render_dom/wrappers/Element/index.ts
**The issue**
1. When the block.i (intro) is called it registers a callback (via add_render_callback)
2. Then the block.o (outro) is called and start the outro and adds a callback to detach on outroend
3. The render callback from the intro is executed, starts the intro and cancels the outro animation
This causes components that should've been destroyed to stay on the page.
#6152
#6812 
**The fix in this PR**
Inside the intro render callback it checks if it is still `current` and if it isn't (because an outro was triggered) it won't start the intro animation.
> [fix] When intro was triggered before the outro, that outro was canceled

- site/content/docs/04-run-time.md
- src/runtime/internal/utils.ts
- src/runtime/transition/index.ts
- test/utils/index.ts
For the `fly` transition, the x & y are passed as numbers and are used are pixel values (px)
This limits the range of what fly can do.
This PR adds support for passing the x & y as strings that can contain CSS units:
You can create an animation that are relative:
```html
<div class="box" in:fly={{x: '100%'}} />
```
`'100%'` is based on the width of the box.
Or based on the viewport:
```html
<div class="modal" in:fly={{y: '50vh'}} />
```
Other units are also supported, we use `rem` a lot,
currently we are calculating the px value or accept that the animation doesn't scale.
With this PR we would be able to write:
```html
<h1 class="title" in:fly={{y: '3rem'}} />
```
As a guideline for the regex I looked at css notation.  
'100%' ✅  
'100 %' ❌
If no unit is provided it falls back to using …
> feat: css units in fly & blur transitions

- site/content/tutorial/16-special-elements/06-svelte-document/app-a/App.svelte
Fixed showing <svelte:body /> where <svelte:document /> topic was  the current subjet.
> docs: Tutorial body had <svelte:body /> even though <svelte:document /> was the subject

- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- src/shared/boolean_attributes.ts
- test/runtime/samples/attribute-boolean-hidden/_config.js
- test/runtime/samples/attribute-boolean-hidden/main.svelte
- test/runtime/samples/attribute-boolean-itemscope/_config.js
- test/runtime/samples/attribute-boolean-itemscope/main.svelte
- test/runtime/samples/attribute-microdata/_config.js
- test/runtime/samples/attribute-microdata/main.svelte
> **Note** Referenced Issue: #8413 
Microdata are a strange set of attributes which are **ONLY** defined in markup, and have no relationship to the underlying Document Object Model node. As such programmatically defining an element and setting a property on it with a given Microdata attribute will not work:
https://codepen.io/iambrosius/full/jOvXBBG
One can read more about microdata here: https://developer.mozilla.org/en-US/docs/Web/HTML/Microdata
When an attribute is declared in the set of `boolean_attributes`: https://github.com/sveltejs/svelte/blob/aa4d0fc2643bdf968dbd72bceda1cce8bdfb5306/src/shared/boolean_attributes.ts#L1
And here: https://github.com/sveltejs/svelte/blob/aa4d0fc2643bdf968dbd72bceda1cce8bdfb5306/src/compiler/compile/render_dom/wrappers/Element/Attribute.ts#L340
The …
> fix: Regression `itemscope` as `boolean_attribute`

- src/compiler/parse/read/css-tree-cq/css_tree_parse.ts
- src/compiler/parse/read/css-tree-cq/node/index.ts
- src/compiler/parse/read/css-tree-cq/node/lookahead_is_range.ts
- src/compiler/parse/read/css-tree-cq/node/media_query.ts
- src/compiler/parse/read/css-tree-cq/node/query_feature.ts
- src/compiler/parse/read/css-tree-cq/node/query_feature_range.ts
- test/css/samples/media-query/expected.css
- test/css/samples/media-query/input.svelte
Closes #5876. As discussed there, `css-tree` is not updated for the latest CSS syntax including the ability to use [single value functions (calc, etc.)](https://chromestatus.com/feature/5643732019838976) in media queries. `css-tree` also does not yet support [media query range syntax](https://developer.chrome.com/blog/media-query-range-syntax/) that is part of the media query level 4 specification. 
This PR broadly helps the entire Svelte ecosystem including SvelteKit.
Given the acceptance of the container query PR (#8275) to extend `css-tree` to support container queries I was able to refactor this extension support repurposing the range syntax support to apply to both container & media queries. At the same time the single value function support implemented for container queries also …
> feat: media query range syntax & single value function support via css-tree extension

- site/content/docs/04-compiler-and-api/01-svelte-compiler.md
This moves all code snippets to imports rather than the current require. Only exception is svelte/register
> docs(site-2): CJS to ESM for code snippets

- package-lock.json
- package.json
Fixes compatibility with TypeScript 3, which we still use
> chore: bump @jridgewell/sourcemap-codec

- src/runtime/internal/dom.ts
- test/runtime/samples/spread-width-height-attributes/_config.js
- test/runtime/samples/spread-width-height-attributes/main.svelte
fixes #6752
@Conduitry please have a closer look at this - seems like there's some history with this stuff, and you might have reservations about introducing some kind of lookup table
> fix: special-case width/height attribute during spread

- .github/workflows/ci.yml
- package.json
- scripts/skip_in_ci.js
The `Setup` job was to work around old Node versions, which we no longer have to support :tada:
> chore: simplify Svelte 4 CI

- .github/workflows/ci.yml
We probably don't need to run on every combination of Node version and OS. This cuts the number of test jobs down from 9 to 5 while still making sure that every Node version and OS is tested
> chore: run fewer CI jobs

- src/compiler/compile/render_dom/wrappers/Element/Attribute.ts
- test/js/samples/select-dynamic-value/expected.js
- test/runtime/samples/binding-select-null-placeholder/_config.js
- test/runtime/samples/binding-select-null-placeholder/main.svelte
Null and undefined `value` bindings should always be set to an empty string. This allows native browser validation of `required` fields to work as expected with placeholder options.
Placeholder options bound to `null` are necessary in components where the field is conditionally required, and the bound value will be posted to an API endpoint which requires it to be a nullable number or object rather than a string.
Resolves #8312
> fix: bind null option and input values consistently

- test/runtime-puppeteer/index.ts
related: https://github.com/sveltejs/svelte/pull/8482
> chore: remove Node 8 and 10 check logic

- src/compiler/index.ts
> chore: ensure version is typed as string instead of the literal `"__VERSION__"`

- src/runtime/store/index.ts
It (ab)used the Subscriber type to represent the signature of the set function and the Unsubscriber to represent the cleanup callback. But the names of the types made their purpose confusing to comprehend.
> docs: fix type signature for StartStopNotifier

- site/content/docs/02-component-format.md
I was initially confused what was meant by "whenever a prop is removed by the consumer", and had to read the PR that added this sentence (PR https://github.com/sveltejs/svelte/pull/4460, a response to Issue https://github.com/sveltejs/svelte/issues/4442).
> docs: clarify statement about initial values for props

- CHANGELOG.md
- rollup.config.mjs
Now that we only support newer versions of Node we can simply rely on `exports`.
This is a breaking change because it requires bundlers to be able to handle the `exports` field. This is the case for
- Vite 3/4
- Rollup 2/3 (using `@rollup/plugin-node-resolve`)
- Webpack 5
If you're relying on a bundler that does not know how to deal with export maps, you need to update its version to one that supports it (like webpack 4->5) or switch to another bundler.
> breaking: remove legacy package.json files

- CHANGELOG.md
- elements/index.d.ts
- src/runtime/internal/dev.ts
`SvelteComponent` now has the same capabilities as `SvelteComponenTyped`, which is therefore now deprecated. Use `SvelteComponent` where you've used `SvelteComponentTyped` previously:
```diff
- import { SvelteComponentTyped } from 'svelte';
+ import { SvelteComponent } from 'svelte';
- export class Foo extends SvelteComponentTyped<{ aProp: string }> {}
+ export class Foo extends SvelteComponent<{ aProp: string }> {}
```
In case you've used `SvelteComponent` previously to type "I expect a Svelte component constructor here" by using `typeof SvelteComponent`, you'll now likely get a somewhat opaque TypeScript error.
Code:
```ts
import type { SvelteComponent } from 'svelte';
const a: typeof SvelteComponent = SomeSvelteComponentWithAProp;
```
Error:
```
Type 'typeof …
```
> breaking: deprecate SvelteComponentTyped, add generics to SvelteComponent

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-no-redundant-roles/input.svelte
Deals with the `no-redundant-roles` part of #8529
There was an erroneous check which compares the element name with the current role. This fix brings `no-redundant-roles` closer to the original [implementation](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/rules/no-redundant-roles.js)
> fix: match `no-redundant-roles` implementation closer to `jsx-eslint`

- .github/workflows/ci.yml
@Conduitry with his eagle eyes noticed that the CI jobs aren't running on the specified Node versions: https://github.com/sveltejs/svelte/pull/8528#issuecomment-1519388031
> chore: fix CI setup for unit tests

- .github/workflows/ci.yml
I think on Node20, we need to use pnpm@8.3.1.
> chore: fix CI on Node 20

- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/nodes/shared/Context.ts
- test/runtime/samples/await-then-destruct-array-nested-rest/_config.js
- test/runtime/samples/await-then-destruct-array-nested-rest/main.svelte
- test/runtime/samples/const-tag-await-then-destructuring-nested-rest/_config.js
- test/runtime/samples/const-tag-await-then-destructuring-nested-rest/main.svelte
- test/runtime/samples/const-tag-each-destructure-nested-rest/_config.js
- test/runtime/samples/const-tag-each-destructure-nested-rest/main.svelte
- test/runtime/samples/each-block-destructured-array-nested-rest/_config.js
- test/runtime/samples/each-block-destructured-array-nested-rest/main.svelte
- test/validator/samples/rest-eachblock-binding-2/warnings.json
- test/validator/samples/rest-eachblock-binding-3/warnings.json
- test/validator/samples/rest-eachblock-binding-nested-rest/input.svelte
- test/validator/samples/rest-eachblock-binding-nested-rest/warnings.json
- test/validator/samples/rest-eachblock-binding/warnings.json
> fix: array rest destructuring in markup

- src/compiler/compile/css/Selector.ts
- src/compiler/compile/nodes/Slot.ts
- test/css/samples/general-siblings-combinator-former-element-in-slot/expected.css
- test/css/samples/general-siblings-combinator-former-element-in-slot/input.svelte
- test/css/samples/general-siblings-combinator-nested-slots-flattened/expected.css
- test/css/samples/general-siblings-combinator-nested-slots-flattened/input.svelte
- test/css/samples/general-siblings-combinator-nested-slots/expected.css
- test/css/samples/general-siblings-combinator-nested-slots/input.svelte
- test/css/samples/general-siblings-combinator-selects-slot-fallback/expected.css
- test/css/samples/general-siblings-combinator-selects-slot-fallback/input.svelte
- test/css/samples/general-siblings-combinator-slots-between/expected.css
- test/css/samples/general-siblings-combinator-slots-between/input.svelte
- test/css/samples/siblings-combinator-former-element-in-slot/expected.css
- test/css/samples/siblings-combinator-former-element-in-slot/input.svelte
- test/css/samples/siblings-combinator-nested-slots-flattened/expected.css
- test/css/samples/siblings-combinator-nested-slots-flattened/input.svelte
- test/css/samples/siblings-combinator-nested-slots/expected.css
- test/css/samples/siblings-combinator-nested-slots/input.svelte
- test/css/samples/siblings-combinator-selects-slot-fallback/expected.css
- test/css/samples/siblings-combinator-selects-slot-fallback/input.svelte
- test/css/samples/siblings-combinator-slots-between/expected.css
- test/css/samples/siblings-combinator-slots-between/input.svelte
- test/validator/samples/general-siblings-combinator-in-custom-element-selects-slot-fallback/_config.js
- test/validator/samples/general-siblings-combinator-in-custom-element-selects-slot-fallback/input.svelte
- test/validator/samples/general-siblings-combinator-in-custom-element-selects-slot-fallback/warnings.json
- test/validator/samples/siblings-combinator-in-custom-element-selects-slot-fallback/_config.js
- test/validator/samples/siblings-combinator-in-custom-element-selects-slot-fallback/input.svelte
- test/validator/samples/siblings-combinator-in-custom-element-selects-slot-fallback/warnings.json
Fixes #8284.
The problem is that the `<slot>` element is treated as an actual element, and for this purpose, we have to treat them as if they don't exist. More specifically, we treat all slot fallback children nodes on the same level as the slot's non-slot siblings.
[edit: I wasn't aware of the `<slot>` element in web components before, so I added a check that if the node belongs to a web component, we still treat slots as if they exist.]
> fix: CSS adjacent and general sibling combinator treats slots as if they don't exist

- CHANGELOG.md
- src/compiler/compile/compiler_warnings.ts
- src/compiler/compile/nodes/Element.ts
- src/compiler/compile/utils/a11y.ts
- test/validator/samples/a11y-autocomplete-valid/input.svelte
- test/validator/samples/a11y-autocomplete-valid/warnings.json
> fix: Handle dynamic values in `a11y-autocomplete-valid`

- .github/workflows/ci.yml
- CHANGELOG.md
- package.json
> fix: set verison to 4, remove engines.pnpm and bump engines.node to >=16

- .github/workflows/ecosystem-ci-trigger.yml
see https://github.com/vitejs/vite/blob/main/.github/workflows/ecosystem-ci-trigger.yml for comparison. same thing, just replaced vitejs/vite with sveltejs/svelte
> feat: add workflow to trigger ecosystem-ci from svelte PRs

- sites/svelte.dev/src/lib/server/markdown/index.js
marked 5.0 would throw up a million warnings on dev and build time. Tweaked option to remove those, shouldn't affect us at all
> fix(site-2): Remove marked warnings

- documentation/content/docs/01-getting-started/01-introduction.md
- documentation/content/faq/900-is-there-a-router.md
I'm not sure we should mention Routify and Elder.js as we usually avoid endorsing non-official projects and I believe Elder.js is no longer maintained or looking to be handed over to someone else. We do have a routing FAQ that folks can refer to
I also wanted to change the first sentence which sounds a bit like you should use Vite without SvelteKit if you want to do something simple, but I hope SvelteKit would be the simpler option for most folks as it avoids them having to answer questions like how to do routing.
> docs: update SvelteKit alternatives section

- test/css/css.test.js
- test/helpers.js
- test/hydration/hydration.test.js
- test/runtime/runtime.shared.js
- test/runtime/runtime_base.test.js
- test/server-side-rendering/ssr-1.test.js
- test/server-side-rendering/ssr-2.test.js
> chore(test): use esm output for svelte files

- package.json
- pnpm-lock.yaml
credit to @Conduitry for noticing this
looks like it was previously used only in the tests
> chore: remove unused source-map-support depedency

- CHANGELOG.md
- src/runtime/internal/transitions.js
- test/runtime/samples/transition-inert/_config.js
- test/runtime/samples/transition-inert/main.svelte
That way they are invisible to assistive technology and can't be interacted with, which makes sense since the element is already "dead" and only transitioning out at this point. Strictly speaking that's a breaking change, so it's marked as such.
closes #8445
> feat: apply inert to outroing elements

- CHANGELOG.md
- site/content/docs/03-template-syntax.md
- src/compiler/compile/nodes/Transition.js
- src/compiler/compile/render_dom/wrappers/Element/index.js
- test/js/samples/transition-local/input.svelte
- test/js/samples/transition-repeated-outro/input.svelte
- test/runtime/samples/dynamic-element-transition/main.svelte
- test/runtime/samples/transition-js-await-block-outros/main.svelte
- test/runtime/samples/transition-js-await-block/main.svelte
- test/runtime/samples/transition-js-each-block-intro/main.svelte
- test/runtime/samples/transition-js-each-block-keyed-intro-outro/main.svelte
- test/runtime/samples/transition-js-each-block-keyed-intro/main.svelte
- test/runtime/samples/transition-js-if-block-in-each-block-bidi/main.svelte
- test/runtime/samples/transition-js-if-else-block-intro/main.svelte
- test/runtime/samples/transition-js-intro-enabled-by-option/main.svelte
- test/runtime/samples/transition-js-local-and-global/main.svelte
- test/runtime/samples/transition-js-local/main.svelte
- test/runtime/samples/transition-js-nested-await/main.svelte
- test/runtime/samples/transition-js-nested-each-keyed/main.svelte
- test/runtime/samples/transition-js-nested-each/main.svelte
- test/runtime/samples/transition-js-nested-if/main.svelte
This means that transitions are not played when they are nested within control flow blocks and a parent control flow block, not its immediate block, makes the element go away.
```svelte
{#if x}
{#if y}
<p transition:fade>
fades in and out only when y changes
</p>
<p transition:fade|global>
fades in and out when x or y change
</p>
{/if}
{/if}
```
This solves a common gotcha with transitions interfering with page navigations.
To make them global, add the `|global` modifier:
```diff
-<div transition:fade>foo</div>
+<div transition:fade|global>foo</div>
```
closes #6686
> feat: make transitions local by default

- packages/svelte/CHANGELOG.md
these versions have compatible ranges in `peerDependencies`
> docs: update changelog with required version of vite-plugin-svelte

- packages/svelte/src/compiler/compile/render_dom/invalidate.js
- packages/svelte/src/compiler/preprocess/index.js
- packages/svelte/src/runtime/internal/Component.js
- packages/svelte/src/runtime/internal/dev.js
- packages/svelte/src/runtime/internal/dom.js
- packages/svelte/src/runtime/internal/transitions.js
- packages/svelte/src/runtime/motion/tweened.js
- packages/svelte/src/runtime/store/index.js
- packages/svelte/src/runtime/store/public.d.ts
> fix: store types and some other internal types that got lost in the conversion

- packages/svelte/package.json
@Conduitry suggested earlier that we shouldn't remove it (https://github.com/sveltejs/svelte/pull/8609#issuecomment-1557050720), but I think that it doesn't work anyway now that `svelte` lives within a subdirectory of this repository
This will possibly fix our release issues as well: https://github.com/sveltejs/svelte/actions/runs/5215485544/jobs/9413074053
> chore: remove prepare script

- .changeset/stale-cougars-wink.md
- packages/svelte/src/compiler/compile/index.js
> warn on boolean compilerOptions.css

- packages/svelte/src/runtime/internal/Component.js
Since the custom element class waits one tick before instantiating the `$$component` field, it's possibly undefined when `attributeChangedCallback` is called. This PR fixes that error by optionally chaining the `$$set` call on `$$component`.
> fix: don't break in `attributeChangedCallback` if `$$component` does not exist yet

- packages/playground/start.js
- site/content/docs/04-run-time.md
closes #8686
also includes a drive-by-playground-windows-fix
> docs: note limitations of not using shadow root

- packages/svelte/package.json
- pnpm-lock.yaml
`locate-character` version 2 is still pulled in as a `devDependency` until there's a new release of `dts-buddy` with https://github.com/Rich-Harris/dts-buddy/commit/25fc187109377d4be3699d5dffab1fb9e022725a
However, this is enough to get the new version as a production `dependency`, which will make learn.svelte.dev load ever so slightly faster since the new version of `locate-character` is ESM-only.
> chore: update locate-character

- packages/svelte/src/compiler/compile/utils/a11y.js
- packages/svelte/test/validator/samples/a11y-no-interactive-element-to-noninteractive-role/input.svelte
- packages/svelte/test/validator/samples/a11y-no-interactive-element-to-noninteractive-role/warnings.json
- packages/svelte/test/validator/samples/a11y-no-noninteractive-element-to-interactive-role/input.svelte
- packages/svelte/test/validator/samples/a11y-no-noninteractive-element-to-interactive-role/warnings.json
closes #8728
Turns out all the removed previous test failures are indeed correct to be removed, according to the test adjustments in https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/937
> chore: a11y tests cleanup

- packages/svelte/src/runtime/internal/lifecycle.js
- packages/svelte/src/runtime/internal/private.d.ts
- packages/svelte/test/types/on-mount.ts
Building off #8136, the current type `onMount` definition is a bit unfriendly in VS Code tooltip. There was also an additional concern by dummdidumm prior to it being merged: https://github.com/sveltejs/svelte/issues/8136#issuecomment-1508921417
> If you return any from onMount, it's an error.
This updated type definition solves both of these concerns:
- VS Code now shows the following onMount type signature:
```ts
function onMount<T>(
fn: () => NotFunction<T> | Promise<NotFunction<T>> | (() => any)
): void
```
This is a lot more readable for humans compared to the previous one, since it's clearer what type we're trying to exclude.
- Any async function that returns any is no longer a type error.
This does also mean that explicitly typecasting a `function` into `any` will be allowed, but …
> fix: update onMount type to allow async to return any

- .changeset/odd-wasps-smoke.md
- documentation/docs/05-misc/04-v4-migration-guide.md
- packages/svelte/src/runtime/internal/dom.js
> breaking: use `CustomEvent` constructor instead of deprecated `createEvent` method

- sites/svelte.dev/src/routes/+layout.svelte
- sites/svelte.dev/src/routes/+page.svelte
- sites/svelte.dev/src/routes/_components/Supporters/index.svelte
- sites/svelte.dev/src/routes/_components/Try.svelte
I wanted to experiment with the footer design. The Svelte balls image is super cool, but has always felt a bit disconnected from the rest of the design to me. I think we should definitely make use of it prominently though. E.g. we should probably switch out the header image on https://twitter.com/sveltejs/ for the Svelte balls.
**master**
**this PR**
> site: alternate footer design

- documentation/docs/05-misc/01-faq.md
- packages/svelte/scripts/generate-version.js
- sites/svelte.dev/src/lib/server/markdown/renderer.js
- sites/svelte.dev/src/routes/+layout.svelte
- sites/svelte.dev/src/routes/_components/Hero.svelte
- sites/svelte.dev/src/routes/nav.json/+server.js
As discussed, replaces links to tutorial with learn.svelte.dev.
Also makes sure the output `version.js` has matching documentation
> fix(site): update tutorial links

- documentation/docs/02-template-syntax/07-special-elements.md
- documentation/docs/03-runtime/02-svelte-store.md
- documentation/docs/04-compiler-and-api/01-svelte-compiler.md
- pnpm-lock.yaml
- sites/svelte.dev/package.json
- sites/svelte.dev/src/lib/server/renderer.js
- sites/svelte.dev/src/routes/docs/+page.svelte
Adapts to renderer's new kit-friendly heading slug mechanism
> fix(site): renderer new link format

- .changeset/smart-kangaroos-tell.md
- packages/svelte/rollup.config.js
Removes a level of indentation inside the UMD wrapper. It's not much but -40KiB unpacked and about -6KiB gzipped (lol)
> chore: deindent cjs output for compiler

- .changeset/silly-ladybugs-marry.md
- .prettierrc
- packages/svelte/package.json
- packages/svelte/src/compiler/compile/Component.js
- packages/svelte/src/compiler/compile/render_dom/Renderer.js
- packages/svelte/src/compiler/compile/render_dom/wrappers/Element/index.js
- packages/svelte/test/runtime/samples/element-source-location-preprocessed/_config.js
- packages/svelte/test/runtime/samples/element-source-location-preprocessed/main.svelte
- pnpm-lock.yaml
We need to use a different method for getting the meta info because `locate` is used to help construct the source map that references the preprocessed Svelte file. If we would now add source maps to that `locate` function it would go the the original source directly which means skipping potentially intermediate source maps which we would need in other situations.
Also adds a new dependency, cc @benmccann that might affect the blog post
fixes #8360
closes #8362
TODO:
> fix: account for sourcemap in meta info

- packages/svelte/src/compiler/Stats.js
By replacing conditional logic with `performance.now()`, this patch ensures improved compatibility across other environments. It avoids unnecessary polyfills triggered by seeing global `process` being used in code by other bundlers/CDN that don't know if they are optional or not, leading to cleaner code.
`performance.now()` exist in all env.
> chore: Remove the need for `node:process`

- documentation/blog/2023-06-22-svelte-4.md
- documentation/docs/05-misc/04-v4-migration-guide.md
Cache busting. 
closes https://github.com/sveltejs/kit/issues/10229
> docs: use @latest on the migrate command

- documentation/docs/02-template-syntax/02-basic-markup.md
- documentation/docs/02-template-syntax/05-element-directives.md
The current documentation has an example saying "These are equivalent" but shows the same line of code twice.
I made a small change to actually show the two lines I believe are ment to be there.
> docs: fix attribute example in basic markup

- documentation/tutorial/04-logic/05-keyed-each-blocks/app-a/Thing.svelte
- documentation/tutorial/04-logic/05-keyed-each-blocks/app-b/Thing.svelte
Fixes of white text on white bg in examples [Docs](https://svelte.dev/tutorial/keyed-each-blocks)
Color changed from white to black (#333333).
Issue Number : #8816
> docs: fix white text on white BG in examples(docs)

- documentation/docs/05-misc/03-typescript.md
The dispatched event name should match the type declaration.
> docs: Fix TypeScript event name typos

- packages/svelte/README.md
Minor DX feedback. When looking for the link to the changelog in the `svelte` [README](https://www.npmjs.com/package/svelte), I was not expecting it to direct to the changelog for SvelteKit.
I think this is a typo since the [link for SvelteKit](https://www.npmjs.com/package/@sveltejs/kit) points to the same location.
> docs: fix link to changelog

- documentation/examples/04-events/00-dom-events/App.svelte
- documentation/examples/04-events/01-inline-handlers/App.svelte
- documentation/examples/08-motion/01-spring/App.svelte
- documentation/examples/09-transitions/06-deferred-transitions/App.svelte
- documentation/examples/11-easing/00-easing/Controls.svelte
- documentation/examples/15-composition/03-slot-props/Hoverable.svelte
- documentation/examples/15-composition/05-modal/Modal.svelte
- documentation/examples/17-special-elements/00-svelte-self/Folder.svelte
- documentation/examples/20-7guis/06-7guis-circles/App.svelte
- documentation/examples/21-miscellaneous/02-immutable-data/App.svelte
- documentation/examples/21-miscellaneous/02-immutable-data/ImmutableTodo.svelte
- documentation/examples/21-miscellaneous/02-immutable-data/MutableTodo.svelte
Fixes all warnings in examples page.
> fix: warnings in examples page

- README.md
I’ve changed the readme so that it no longer says that the compiler uses Typescript, but JS with JSDoc.
> fix: change Typescript to JSDoc in Readme.md

- documentation/docs/05-misc/03-typescript.md
The docs currently recommend using type assertions with `as` as a means of assigning types to reactive declarations in lieu of being able to add type annotations directly. 
Given the docs are suggesting the alternative to using type annotations, to me it makes sense to only recommend the type annotation approach using `let variable: Type`.
Generally speaking it's also good practice to use type annotations over assertions where possible as well, as assertions provide weaker type checking.
For example:
```ts
type Person = {
firstName: string;
lastName: string;
}
let person1: Person = {
firstName: 'Erlich',
lastName: 'Bachman',
occupation: 'Chief Evangelist Officer',
//  ^❌ Type '{ firstName: string; lastName: string; occupation: string; }' is not assignable to type 'Person'. Object literal …
```
> docs: Don't recommend TypeScript type assertions for reactive declarations

- .changeset/neat-feet-accept.md
- packages/svelte/src/compiler/compile/render_dom/wrappers/Element/index.js
> fix: apply transition_in/out to svelte:element with local transition

- .changeset/pretty-tools-whisper.md
- packages/svelte/src/compiler/compile/nodes/Element.js
- packages/svelte/test/validator/samples/a11y-no-redundant-roles/input.svelte
- packages/svelte/test/validator/samples/a11y-no-redundant-roles/warnings.json
> fix: relax a11y "no redundant role" rule for li, ul, ol

- .changeset/long-humans-dress.md
- documentation/docs/05-misc/03-typescript.md
- documentation/docs/05-misc/04-v4-migration-guide.md
- packages/svelte/src/runtime/action/public.d.ts
- packages/svelte/src/runtime/internal/public.d.ts
- packages/svelte/test/types/actions.ts
- packages/svelte/test/types/create-event-dispatcher.ts
fixes #8860
This contains a small but unfortunately unavoidable breaking change: If you used `never` to type that the second parameter shouldn't be set (which the docs recommended for a short time), then you need to change that to `null`:
```diff
const dispatch = createEventDispatcher<{
-  noParameter: never;
+  noParameter: null;
}>();
```
Same for `ActionReturn` - use `undefined` instead of `never`:
```diff
- function action(el: HTMLElement): ActionReturn<never> {
+ function action(el: HTMLElement): ActionReturn<undefined> {
// ..
}
```
> fix: ensure createEventDispatcher works with types from generics

- .changeset/proud-cycles-hunt.md
- packages/svelte/package.json
This PR allows the built-in nodejs resolver (18.x) to lookup `internal/disclose-version`, otherwise it yields:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/disclose-version' is not defined by "exports" in /Users/lab/Projects/plasmo/examples/with-svelte/node_modules/svelte/package.json
```
The call looks like this:
```
const filePath = require.resolve("svelte/internal", {
paths: [""]
})
```
> chore: adding default for disclose version

- .changeset/six-teachers-divide.md
- packages/svelte/src/compiler/compile/render_dom/wrappers/Element/Attribute.js
- packages/svelte/src/runtime/internal/utils.js
- packages/svelte/test/utils/utils.test.js
fixes #8838
@benmccann could you test if this fixes the issue?
> fix: check srcset when hydrating to prevent needless requests

- sites/svelte.dev/README.md
Ran into some small bumps in the svelte.dev instructions while trying to investigate another issue; this PR fixes them.
> chore: update svelte.dev README

- .changeset/pretty-trees-prove.md
- packages/svelte/src/compiler/compile/render_dom/wrappers/RawMustacheTag.js
- packages/svelte/test/runtime/samples/svg-html-tag3/_config.js
- packages/svelte/test/runtime/samples/svg-html-tag3/main.svelte
fixes https://github.com/sveltejs/kit/issues/10245
@benmccann this might be another one for your testing - this might give better lighthouse scores as a result since html is not removed and reappended anymore if everything matches.
> fix: use non-destructive hydration for all `@html` tags

- .changeset/happy-cows-warn.md
- packages/svelte/src/runtime/internal/Component.js
- use shorter class property names as they are not minified
- reuse some dom helper methods
#8826
> fix: shrink custom element baseline a bit

- documentation/tutorial/05-events/02-inline-handlers/text.md
The quote marks were removed in db2d07f2360191b68022ba3e64a86401edd15296
If they aren't coming back, then this text is out-of-date and confusing.
> docs: Remove old redundant text

- .changeset/early-lizards-decide.md
- packages/svelte/src/runtime/internal/utils.js
- packages/svelte/test/utils/utils.test.js
> fix: handle falsy srcset values

- .changeset/curvy-lobsters-decide.md
- packages/svelte/src/runtime/internal/dom.js
- packages/svelte/test/hydration/samples/raw-svg/_after.html
- packages/svelte/test/hydration/samples/raw-svg/_before.html
- packages/svelte/test/hydration/samples/raw-svg/_config.js
- packages/svelte/test/hydration/samples/raw-svg/main.svelte
- packages/svelte/test/hydration/samples/raw/_after.html
- packages/svelte/test/hydration/samples/raw/_before.html
- packages/svelte/test/hydration/samples/raw/_config.js
- packages/svelte/test/hydration/samples/raw/main.svelte
- packages/svelte/test/runtime/samples/raw-svg/_config.js
- packages/svelte/test/runtime/samples/raw-svg/main.svelte
> fix: claim svg tags in raw mustache tags correctly

- .changeset/spicy-ladybugs-return.md
- packages/svelte/.prettierignore
- packages/svelte/src/runtime/internal/dom.js
- packages/svelte/test/hydration/samples/raw-repair/_after.html
- packages/svelte/test/hydration/samples/raw-repair/_before.html
- packages/svelte/test/hydration/samples/raw-repair/inner.svelte
- packages/svelte/test/hydration/samples/raw-repair/main.svelte
When the HTML that is coming from raw html is invalid, the browser reshuffles things. Bail in that case to try to repair more often. Should help with https://github.com/withastro/astro/issues/7557
> fix: repair invalid raw html content during hydration

- documentation/tutorial/10-transitions/09-key-blocks/text.md
In the discussion there's a hint-- a bit of code that, when added to the existing code, gives the solution to the problem. The bit of code in the hint does not match the pre-existing code or the solution in these ways: 1) different variable name-- number vs. value
2) what transition to use
3) whether to use  the transition attribute or the in attribute I have just changed the markup so that the suggested code matches what needs to be added to most quickly arrive at the solution. Otherwise the learner has to also fix/grapple with these other differences.
> Hint matches existing structure and solution

- .changeset/funny-bags-occur.md
- packages/svelte/scripts/generate-dts.js
Fix regression introduced in svelte 4. https://github.com/sveltejs/language-tools/issues/1767. This is because the type definition is now generated from the source, and TypeScript will ignore nullable types when `strictNullCheck` isn't enabled. 
Since the types aren't in source control. Manually create a diff between before and after for record and review. 
```diff
--- a/packages/svelte/types/index.d.ts
+++ b/packages/svelte/types/index.d.ts
@@ -110,7 +110,7 @@ declare module 'svelte' {
$destroy(): void;
-		$on<K extends Extract<keyof Events, string>>(type: K, callback: (e: Events[K]) => void): () => void;
+		$on<K extends Extract<keyof Events, string>>(type: K, callback: ((e: Events[K]) => void) | null | undefined): () => void;
$set(props: Partial<Props>): void;
}
@@ -772,8 +772,8 @@ …
```
> fix: generate type definition with nullable types

- documentation/examples/12-svg/03-area-chart/App.svelte
tried a middle color that seems to work for both dark and light theme.
not sure if this is better, or we should specify different colors for different dark / light theme
before:
after:
relates to https://github.com/sveltejs/sites/issues/493
~~- [ ] Ideally, include a test that fails without this PR but passes with it.~~
~~- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint`~~
> docs: choose a color that looks great on both dark and light theme

- documentation/examples/05-bindings/12-component-bindings/App.svelte
fixing the contrast for the component binding example
before:
after:
relates to https://github.com/sveltejs/sites/issues/493
~~- [ ] Ideally, include a test that fails without this PR but passes with it.~~
~~- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint`~~
> docs: fix contrast for component-binding example

- packages/svelte/src/compiler/Stats.js
- packages/svelte/src/compiler/compile/Component.js
- packages/svelte/src/compiler/compile/compiler_warnings.js
- packages/svelte/src/compiler/compile/create_module.js
- packages/svelte/src/compiler/compile/index.js
- packages/svelte/src/compiler/compile/nodes/Attribute.js
- packages/svelte/src/compiler/compile/nodes/Binding.js
- packages/svelte/src/compiler/compile/nodes/Body.js
- packages/svelte/src/compiler/compile/nodes/CatchBlock.js
- packages/svelte/src/compiler/compile/nodes/ConstTag.js
- packages/svelte/src/compiler/compile/nodes/Document.js
- packages/svelte/src/compiler/compile/nodes/EachBlock.js
- packages/svelte/src/compiler/compile/nodes/Element.js
- packages/svelte/src/compiler/compile/nodes/EventHandler.js
- packages/svelte/src/compiler/compile/nodes/Head.js
- packages/svelte/src/compiler/compile/nodes/InlineComponent.js
- packages/svelte/src/compiler/compile/nodes/Slot.js
- packages/svelte/src/compiler/compile/nodes/SlotTemplate.js
- packages/svelte/src/compiler/compile/nodes/StyleDirective.js
- packages/svelte/src/compiler/compile/nodes/ThenBlock.js
- packages/svelte/src/compiler/compile/nodes/Title.js
- packages/svelte/src/compiler/compile/nodes/Window.js
- packages/svelte/src/compiler/compile/nodes/shared/Expression.js
- packages/svelte/src/compiler/compile/nodes/shared/TemplateScope.js
- packages/svelte/src/compiler/compile/nodes/shared/get_const_tags.js
- packages/svelte/src/compiler/compile/nodes/shared/map_children.js
- packages/svelte/src/compiler/parse/read/context.js
- packages/svelte/src/runtime/internal/dom.js
I'm not 100% sure these descriptions are right especially for `dependencies` and `contextual_dependencies`. You really only need to review the first commit: https://github.com/sveltejs/svelte/pull/8940/commits/2b646f075c9439cd128a5374d82a7707ba9897fa. The rest is cleanup from the transition from `.ts` to `.js` removing unnecessary casts to `any` causing us to lose type information
> docs: add a couple internal JSDocs and cleanup from TS migration

- packages/svelte/test/parser/update.js
It looks like we missed doing this when we converted everything to ESM
> chore: fix broken script for generating parser tests

- documentation/docs/02-template-syntax/02-basic-markup.md
Example should show that unquoted values work, but shows example with a quote 😄
> docs: Make "unquoted" example actually unquoted

- documentation/tutorial/11-animations/01-animate/app-a/App.svelte
- documentation/tutorial/11-animations/01-animate/app-b/App.svelte
Tutorial page for animate directive (https://svelte.dev/tutorial/animate) renders the todos weird on Chrome:
- Without `display: block;`
- With `display: block;`
> site: todos in `animate` tutorial render weird on chrome

- .changeset/clever-ghosts-laugh.md
- packages/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.js
- packages/svelte/test/runtime/samples/dynamic-component-evals-props-once/Comp1.svelte
- packages/svelte/test/runtime/samples/dynamic-component-evals-props-once/Comp2.svelte
- packages/svelte/test/runtime/samples/dynamic-component-evals-props-once/_config.js
- packages/svelte/test/runtime/samples/dynamic-component-evals-props-once/main.svelte
> fix: svelte:component evaluates props once

- package.json
- packages/svelte/package.json
- packages/svelte/test/hydration/hydration.test.js
- pnpm-lock.yaml
- sites/svelte.dev/package.json
renovate won't do it because semver
> chore: upgrade vitest

- documentation/docs/05-misc/04-v4-migration-guide.md
> docs: update migration guide bundler conditions section

- documentation/blog/2022-12-01-whats-new-in-svelte-december-2022.md
- documentation/docs/05-misc/03-typescript.md
Hey :wave:,
This PR will fix :
1 typo in `documentation/blog/2022-12-01-whats-new-in-svelte-december-2022.md`
1 typo in `documentation/docs/05-misc/03-typescript.md`
Best!
> docs: fix typos

- documentation/docs/04-compiler-and-api/01-svelte-compiler.md
The removed paragraph appears twice in the same section, first occurence is line 87.
I thought it should be removed.
> docs: remove compiler duplicate paragraph

- documentation/tutorial/10-transitions/08-deferred-transitions/app-a/App.svelte
- documentation/tutorial/10-transitions/08-deferred-transitions/app-b/App.svelte
In lessons 8 - H it's appear to be missing style, the disturbing list harm the comprehension of the lesson.
Current Display:
Solution proposed:
> fix: styling - fix on documentation for lesson 8-h

- documentation/tutorial/10-transitions/09-key-blocks/text.md
In `Transitions / Key blocks` the documentation showed a fade transition and this was not in sync with the tutorial which used a fly transition.
> fix: Changed fade to fly to match the tutorial

- .changeset/ten-gifts-design.md
- packages/svelte/src/compiler/compile/render_dom/index.js
In dev mode, Svelte creates a setter to throw an error noting that you can't set that readonly prop, which resulted in the accessor getting applied twice to the custom element wrapper, causing an error
fixes #8971
> fix: don't add accessor twice

- documentation/docs/05-misc/03-typescript.md
This just fixes a small mistake in the example for typing Events.
> docs: fix typo inside example in 03-typescript.md

- documentation/examples/09-transitions/06-deferred-transitions/App.svelte
Svelte 4 uses `local` for transitions by default. [changelog](https://github.com/sveltejs/svelte/blob/master/packages/svelte/CHANGELOG.md#patch-changes-6). Therefore, the deferred transition example doesn't work. I fixed it
https://github.com/sveltejs/svelte/assets/76736580/4363217d-ed5c-487a-a772-a1057b389474
https://github.com/sveltejs/svelte/assets/76736580/5089b5c0-8d8f-4cfe-a81a-da1e75932239
> docs: Make transition global in Deferred transition example

- documentation/docs/02-template-syntax/02-basic-markup.md
Fixes #9022 
While not majorly important it could be mildly confusing for people just starting out. As pointed out by [this issue](https://github.com/sveltejs/prettier-plugin-svelte/issues/393) and obviously the text above when using literal notation you need parenthesis or svelte will fail to parse the expression.
> docs: add parenthesis back to regex literal example

- .changeset/twelve-suits-drive.md
- packages/svelte/elements.d.ts
> fix: Add data-* to svg attributes

- packages/svelte/test/helpers.js
For some bizarre reason, Node 16.17.0 is complaining that `fileURLToPath` is getting passed an instance of `URL` when it expects an instance of `URL`. I don't know what this could be caused by other than https://github.com/nodejs/node/pull/47179, but that's still entirely mysterious. To get the tests working again, I'm instead just getting an uncontroversial string to pass to `fileURLToPath` to do with as it pleases.
> chore: fix tests on Node 18.17.0

- documentation/docs/02-template-syntax/02-basic-markup.md
I wonder if there's also something here around whether innerHTML can be used to optimize HTML creation? @dummdidumm may know...
> docs: clarify performance concerns around props and restProps

- documentation/docs/02-template-syntax/06-component-directives.md
- it was difficult to understand the `on:eventname` section because it didn't give an example of event forwarding
- describe the difference between `bind:prop` and regular prop reactivity
- move note about `cart.empty` to come after the code example it's referring to instead of before it
> docs: update component directives page

- .changeset/nine-houses-flow.md
- packages/svelte/src/compiler/compile/nodes/Element.js
- packages/svelte/test/runtime/samples/slot-in-dynamic-element/_config.js
- packages/svelte/test/runtime/samples/slot-in-dynamic-element/main.svelte
> fix: allow child element with slot attribute within svelte:element

- .changeset/slimy-dingos-call.md
- documentation/docs/05-misc/03-typescript.md
- packages/svelte/package.json
- packages/svelte/svelte-html.d.ts
For https://github.com/sveltejs/language-tools/issues/2109. This file is currently in the language-tools repo and ships with svelte2tsx, but the problem is that TypeScript will load the `svelte/elements` version that comes with the svelte-language-server. Moving this to the Svelte core makes TypeScript always resolve it to the user-installed/workspace version of Svelte. Making it resolve to the user version also fixes the problem with the declaration merging of `declare module "svelte/elements"`. This allows the user/library to add custom types with it. For example:
```ts
// app.d.ts
import { HTMLButtonAttributes } from 'svelte/elements'
declare module 'svelte/elements' {
export interface SvelteHTMLElements {
'custom-button': HTMLButtonAttributes;
}
export interface HTMLButtonAttributes { …
```
> fix: move svelteHTML to load the correct svelte/element

- documentation/docs/02-template-syntax/02-basic-markup.md
The code example is inconsistent with the text:
> An expression might include characters that would cause syntax highlighting to fail in regular HTML, so quoting the value is permitted. The quotes do not affect how the value is parsed: [...]
But the attribute in the code example is not quoted at all:
```
<button disabled={number !== 42}>...</button>
```
This small PR fixes the code example by placing back missing quotation marks.
It is a regression, as the docs before site redesign explain it correctly; see https://github.com/sveltejs/svelte/blob/v3.59.2/site/content/docs/03-template-syntax.md.
---
- [v] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: …
> docs: Fix a regression for a quoted-attribute example

- sites/svelte.dev/src/routes/tutorial/+layout.svelte
- sites/svelte.dev/static/robots.txt
TIL https://github.com/sveltejs/sites/pull/533#issuecomment-1684185471
> site: fix removal of tutorial from search engines

- .changeset/eighty-poems-deliver.md
- packages/svelte/src/compiler/utils/mapped_code.js
fixes #6714
code-red will fail on such cases too, but that codepath doesn't seem to be hit by Svelte currently, if the error pops up again that'd be the place to look
> fix: css sourcemap generation with unicode filenames

- .changeset/tame-tomatoes-warn.md
- packages/svelte/src/runtime/internal/Component.js
- packages/svelte/test/runtime-browser/custom-elements-samples/reflect-attributes-add-remove/main.svelte
- packages/svelte/test/runtime-browser/custom-elements-samples/reflect-attributes-add-remove/test.js
> fix: custom element reflected attribute remove fails when attribute and props property have different values

- .changeset/stale-terms-sing.md
- packages/playground/start.js
- packages/svelte/src/compiler/compile/render_ssr/index.js
- packages/svelte/test/server-side-rendering/samples/head-no-duplicates-with-binding/Foo.svelte
- packages/svelte/test/server-side-rendering/samples/head-no-duplicates-with-binding/_expected-head.html
- packages/svelte/test/server-side-rendering/samples/head-no-duplicates-with-binding/main.svelte
fixes https://github.com/sveltejs/svelte/issues/7879
fixes #4982
> fix: head duplication when binding is present

- pnpm-lock.yaml
- sites/svelte.dev/package.json
- sites/svelte.dev/src/app.d.ts
- sites/svelte.dev/src/routes/+layout.svelte
- sites/svelte.dev/src/routes/blog/+layout.svelte
- sites/svelte.dev/src/routes/blog/+page.svelte
- sites/svelte.dev/src/routes/blog/[slug]/+page.svelte
This PR adds view transitions to the site (see https://github.com/sveltejs/svelte/pull/9162)
https://github.com/sveltejs/svelte/assets/4992896/99484850-bdf2-4e37-807a-cf05b5c4b587
> site: add view transitions and transition blog title

- documentation/blog/2023-08-31-view-transitions.md
New blog post talking about `onNavigate` and view transitions.
Depends on https://github.com/sveltejs/assets/pull/6
> site: add view transitions blog post

- documentation/docs/05-misc/01-faq.md
I finally sat down and wrote this. It may not stem the tide of feature requests, but it would be helpful to have a single thing to point at. I'd love some feedback on the wording here.
> docs: add FAQ about why you can't keep unused styles

- documentation/docs/05-misc/01-faq.md
This FAQ seems outdated now that we have https://svelte.dev/docs/typescript. I was initially worried about trying to redirect https://svelte.dev/docs/faq#what-about-typescript-support to the new location at https://svelte.dev/docs/typescript, but I've found very few pages linking to it and the new page is already coming up on Google.
> docs: remove typescript FAQ

- .changeset/famous-news-perform.md
- packages/svelte/src/compiler/compile/render_dom/wrappers/shared/is_dynamic.js
- packages/svelte/test/js/samples/reactive-class-optimized/expected.js
- packages/svelte/test/js/samples/reactive-class-optimized/input.svelte
closes https://github.com/sveltejs/svelte/issues/5943
> fix: do not add module declared variables as dependencies

- .changeset/ten-poems-remember.md
- packages/svelte/elements.d.ts
- [X ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ X] Prefix your PR title with `feat:`, `fix:`, `chore:`, or `docs:`.
- [ X] This message body should clearly illustrate what problems it solves.
- [ X] Ideally, include a test that fails without this PR but passes with it.
- [X ] Run the tests with `pnpm test` and lint the project with `pnpm lint`
Fixes #9176. This adds `indeterminate` to the list of `HTMLAttributes` so that one can use it without receiving an error.
> fix: This makes the indeterminate HTML attribute available for use. Fixes #9176.

- packages/svelte/src/runtime/internal/Component.js
closes #7200
The internal types aren't exposed as a public API and shouldn't be relied on but figured it'd be nice to document these anyway just so no one forgets what these are when we context switch to the next major
A few left to do still as I couldn't quite describe them, feel free to make suggestions as review comments or push
> chore: document init parameters

- .changeset/tricky-planets-rush.md
- packages/svelte/src/compiler/compile/nodes/Element.js
- packages/svelte/test/runtime/samples/select-options-spread-attributes/_config.js
- packages/svelte/test/runtime/samples/select-options-spread-attributes/main.svelte
fixes #9107
Apart from the problem with the option the same happens with the textarea.
> fix: spreading attributes on option value attribute get's replaced by option's inner text

- pnpm-lock.yaml
- sites/svelte.dev/package.json
- sites/svelte.dev/src/routes/(authed)/repl/[id]/+page.svelte
- sites/svelte.dev/src/routes/+layout.svelte
- sites/svelte.dev/src/routes/blog/+page.svelte
- sites/svelte.dev/src/routes/docs/+layout.svelte
- sites/svelte.dev/src/routes/examples/[slug]/+page.svelte
- sites/svelte.dev/src/routes/tutorial/[slug]/+page.svelte
The issue of overlapping runes bottom banner on the REPL has been resolved.
> fix(repl): runes bottom banner overlapping fixed

- packages/svelte/src/runtime/action/public.d.ts
`HTMLDiveElement` > `HTMLDivElement`
> docs: Fix small typo in ts documentation

- sites/svelte.dev/scripts/get_contributors.js
- sites/svelte.dev/scripts/get_donors.js
This small change fixes an issue when attempting to run the svelte.dev site locally on a windows machine:
```
Error: ENOENT: no such file or directory, mkdir '/C:/somepath/svelte/sites/svelte.dev/src/routes/_components/Supporters'
```
Notice the leading `/` in the path above, which comes from using `.pathname` directly instead of `fileURLToPath`.
> fix: svelte.dev site scripts filepath generation

- .changeset/sour-rats-laugh.md
- packages/svelte/package.json
- packages/svelte/test/sourcemaps/samples/compile-option-dev/test.js
- pnpm-lock.yaml
Fixes the sourcemap test that @dominikg and I were banging our heads against forever. Big thank you to bmeurer for diagnosing the issue (https://github.com/Rich-Harris/magic-string/issues/248) and sapphi-red for the fix (https://github.com/Rich-Harris/magic-string/pull/261)!
> chore: upgrade `magic-string`

- .changeset/seven-cars-drum.md
- packages/svelte/src/compiler/compile/render_dom/wrappers/Element/Attribute.js
- packages/svelte/src/runtime/internal/dom.js
- packages/svelte/test/runtime/samples/attribute-casing-custom-element/_config.js
- packages/svelte/test/runtime/samples/attribute-casing-custom-element/main.svelte
- packages/svelte/test/runtime/samples/attribute-custom-element-inheritance/_config.js
- packages/svelte/test/runtime/samples/attribute-custom-element-inheritance/main.svelte
- packages/svelte/vitest.config.js
while attributes are case insensitive, properties are not. to not introduce a breaking change, the lowercased variant is checked first. fixes #9325
> fix: support camelCase properties on custom elements

- documentation/docs/02-template-syntax/03-logic-blocks.md
Fixes sveltejs/svelte#9323.
Wording could probably be better, feel free to fix my mediocre English.
> docs: mention `{#await}` on non-Promise values short-circuiting to the fullfilled branch

- packages/svelte/elements.d.ts
```
<rect
x="10"
y="10"
width="10"
height="10"
transform="scale(2)"
transform-origin="10 10"
/>
```
gives the following error in VS Code 
```
Argument of type '{ x: string; y: string; width: string; height: string; transform: string; "transform-origin": string; }' is not assignable to parameter of type 'HTMLProps<"rect", SVGAttributes<any>>'.
Object literal may only specify known properties, and '"transform-origin"' does not exist in type 'HTMLProps<"rect", SVGAttributes<any>>'. js(2345)
```
`transform-origin` can be set as a presentational attribute but it's missing in the `SVGAttributes`.
See:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform-origin
https://www.w3.org/TR/SVG2/styling.html#PresentationAttributes (missing in the original spec, I guess it was forgotten) …
> fix: Add transform-origin to SVGAttributes

- .changeset/slimy-comics-switch.md
- packages/svelte/elements.d.ts
As it was mentioned in #9181 contenteditable property was incomplete and missing 'plaintext-only'. This PR actually add this value to type.
> fix: Add missing plaintext-only value to contenteditable type

- .changeset/thirty-steaks-dream.md
- packages/svelte/src/compiler/compile/render_dom/invalidate.js
- packages/svelte/src/compiler/utils/nodes_match.js
- packages/svelte/test/runtime/samples/comment-effect-on-reactivity/SomeComponent.svelte
- packages/svelte/test/runtime/samples/comment-effect-on-reactivity/_config.js
- packages/svelte/test/runtime/samples/comment-effect-on-reactivity/main.svelte
related to issue https://github.com/sveltejs/svelte/issues/9088
it doesn't solve the main problem of dependencies getting invalidated whenever value of a variable gets changed.  
but it fixes the behavior difference between the code with and without comments
the problem is demonstrated in this repl: https://svelte.dev/repl/81bdbbbb88694b4a80d2619bd2dbfc2e?version=4.2.0
> fix: ignore comments while comparing nodes in node_match

- documentation/tutorial/04-logic/03-else-if-blocks/app-a/App.svelte
- Fix https://github.com/sveltejs/svelte/issues/9335
- Fixed `Show me` button is not showing on `/tutorial/else-if-blocks`
- https://learn.svelte.dev/tutorial/else-if-blocks was referred for fix.
- Go to `/tutorial/else-blocks` 
- Check `Show me`/`Reset` buttons are working properly
(I had a problem QAing on Chrome. It should work on Firefox)   
> fix: else-if-blocks on tutorial

- packages/svelte/src/compiler/compile/render_dom/invalidate.js
- packages/svelte/src/compiler/utils/nodes_match.js
- sites/svelte.dev/src/app.html
- sites/svelte.dev/src/routes/(authed)/+layout.server.js
it seems that https://github.com/sveltejs/svelte/pull/9197 was merged with the lint CI failing against it
> chore: fix failing format linting

- .changeset/light-hounds-complain.md
- documentation/docs/05-misc/02-accessibility-warnings.md
- packages/svelte/src/compiler/compile/compiler_warnings.js
- packages/svelte/test/validator/samples/a11y-click-events-have-key-events/warnings.json
- packages/svelte/test/validator/samples/slot-warning/warnings.json
- packages/svelte/test/validator/samples/slot-warning2/warnings.json
fixes https://github.com/sveltejs/svelte/issues/8001
closes https://github.com/sveltejs/svelte/issues/8273
it's longer message, but at least it's useful now
> fix: improve a11y-click-events-have-key-events message

- documentation/blog/2023-09-20-runes.md
People continue to be confused by this section
We've had an FAQ about this forever, but not everyone who reads the blog post will see the FAQ
https://svelte-5-preview.vercel.app/docs/faq#breaking-changes-and-migration-which-things-will-be-deprecated-in-svelte-5
> docs: clarify "obsolete" in runes blog post

- documentation/blog/2023-11-01-whats-new-in-svelte-november-2023.md
> docs: "What's new in Svelte" November newsletter

- documentation/examples/10-animations/00-animate/App.svelte
This PR makes the text in labels visible when seeing the documentation in dark mode:
New version:
Original:
> docs: update text color in animate example

- sites/svelte.dev/src/lib/db/client.js
- sites/svelte.dev/src/lib/db/gist.js
- sites/svelte.dev/src/lib/db/session.js
- sites/svelte.dev/src/lib/server/docs/index.js
- sites/svelte.dev/src/lib/server/examples/index.js
- sites/svelte.dev/src/lib/server/examples/types.d.ts
- sites/svelte.dev/src/lib/server/tutorial/index.js
- sites/svelte.dev/src/lib/server/tutorial/types.d.ts
- sites/svelte.dev/src/lib/time.js
- sites/svelte.dev/src/lib/utils/events.js
- sites/svelte.dev/src/lib/utils/examples.js
- sites/svelte.dev/src/routes/(authed)/apps/+page.server.js
- sites/svelte.dev/src/routes/(authed)/repl/+page.js
- sites/svelte.dev/src/routes/(authed)/repl/[id]/AppControls.svelte
- sites/svelte.dev/src/routes/(authed)/repl/[id]/downloadBlob.js
- sites/svelte.dev/src/routes/(authed)/repl/api/[id].json/+server.js
- sites/svelte.dev/src/routes/auth/callback/+server.js
- sites/svelte.dev/src/routes/auth/login/+server.js
- sites/svelte.dev/src/routes/blog/rss.xml/+server.js
- sites/svelte.dev/src/routes/content.json/content.server.js
This fixes about 1/3 of the errors when enabling `strict` mode. The rest live in the `.svelte` files. I thought I'd break it up though since there are so many of them
> site: fix type errors in JS files

- .changeset/moody-owls-cry.md
- packages/svelte/src/internal/client/render.js
- packages/svelte/tests/runtime-runes/samples/event-listener-spread/Button.svelte
- packages/svelte/tests/runtime-runes/samples/event-listener-spread/_config.js
- packages/svelte/tests/runtime-runes/samples/event-listener-spread/main.svelte
> fix: exclude internal props from spread attributes

- sites/svelte-5-preview/src/lib/CodeMirror.svelte
- sites/svelte-5-preview/src/lib/Input/ModuleEditor.svelte
- sites/svelte-5-preview/src/lib/Output/Compiler.js
- sites/svelte-5-preview/src/lib/Output/Output.svelte
- sites/svelte-5-preview/src/lib/Repl.svelte
- sites/svelte-5-preview/src/lib/types.d.ts
- sites/svelte-5-preview/src/lib/workers/compiler/index.js
This updates how the diagnostics work in the playground — rather than being driven by the bundler, they're driven by the compiler directly, meaning we get diagnostics even for things that aren't yet in the module graph. (It's also just much simpler this way)
I was slightly lazy with the types because I'm under the cosh. And there's definitely more tidying up that can be done here, but it's a job for future us
> Fix diagnostics

- sites/svelte-5-preview/src/lib/Input/ComponentSelector.svelte
- sites/svelte-5-preview/src/lib/Input/RunesInfo.svelte
- sites/svelte-5-preview/src/lib/Repl.svelte
- sites/svelte-5-preview/src/lib/types.d.ts
> fix runes mode indicator

- documentation/blog/2023-02-21-streaming-snapshots-sveltekit.md
- sites/svelte.dev/src/lib/server/blog/index.js
- sites/svelte.dev/src/lib/server/blog/types.d.ts
- sites/svelte.dev/src/routes/blog/[slug]/+page.svelte
Opened against the `svelte-4` branch since I think that's the only one where site deploys work, but lmk if it should be `main` instead.
This PR allows specifying multiple authors on a blog post by adding comma separation in the frontmatter, e.g.
```
---
title: Streaming, snapshots, and other new features since SvelteKit 1.0
description: Exciting improvements in the latest version of SvelteKit
author: Geoff Rich, Rich Harris
authorURL: https://geoffrich.net, https://twitter.com/Rich_Harris
---
```
Updated the streaming blog post from earlier this year to give credit to Rich, since he wrote the "how does this work" section.
> site: allow multiple blog authors

- .changeset/tall-shrimps-worry.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/src/compiler/phases/3-transform/server/transform-server.js
- packages/svelte/src/internal/client/validate.js
- packages/svelte/tests/runtime-runes/samples/snippet-validation-error/_config.js
> add snippet symbol to children prop

- documentation/docs/03-runtime/07-svelte-action.md
The event listener must be registered before the event is dispatched in order for this code snippet to work.
Redone with correct branch as requested by @dummdidumm here:
https://github.com/sveltejs/svelte/pull/9399#issuecomment-1807714247
> docs: incorrect order of directives

- packages/svelte/src/transition/index.js
Closes https://github.com/sveltejs/svelte/issues/9402
This PR adds back transitions that got lost in migration: `blur`, `fly`, `scale`, and `draw`, along with utility functions `cubic_in_out` and `split_css_unit`. Svelte v4 version for reference: https://github.com/sveltejs/svelte/blob/svelte-4/packages/svelte/src/runtime/transition/index.js
> chore: add missing svelte/transition functions

- .changeset/eight-steaks-shout.md
- packages/svelte/src/internal/client/render.js
When looking through the each block code, it occurred to me the index is always a number and never a signal. Not sure why this was constructed this way, but this likely will cause overhead in keyed updates.
> fix: correct each block update index type

- .changeset/quiet-camels-mate.md
- .github/PULL_REQUEST_TEMPLATE.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/src/internal/client/reconciler.js
- packages/svelte/src/internal/client/render.js
With Svelte 5, we load both each block reconciliation functions, making it impossible to tree shake one or the other if you don't use them. This PR changes that, ensuring we can treeshake them respectfully by breaking the compiled function into either `$.each_keyed` or `$.each_indexed`.
> chore: split $.each into $.each_keyed/$.each_indexed

- .changeset/khaki-mails-draw.md
- .github/PULL_REQUEST_TEMPLATE.md
- packages/svelte/src/compiler/phases/3-transform/client/utils.js
- packages/svelte/src/internal/client/operations.js
- packages/svelte/src/internal/client/reconciler.js
- packages/svelte/src/internal/client/render.js
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/tests/runtime-runes/samples/class-state-constructor-closure-private/_config.js
- packages/svelte/tests/runtime-runes/samples/class-state-constructor-closure-private/main.svelte
- packages/svelte/tests/runtime-runes/samples/class-state-constructor-closure/_config.js
- packages/svelte/tests/runtime-runes/samples/class-state-constructor-closure/main.svelte
- packages/svelte/tests/runtime-runes/samples/effect-cleanup/_config.js
- packages/svelte/tests/runtime-runes/samples/effect-cleanup/main.svelte
This PR addresses several issues relating to the runtime:
- When updating state inside a class constructor (from within a closure) ensure the state updates correctly. Fixes https://github.com/sveltejs/svelte/issues/9407.
- When reading a derived from within an effect's cleanup, ensure that value is accessible. Fixes https://github.com/sveltejs/svelte/issues/9409.
- Ensure that `$effect.pre` triggers an error when called outside of having an active effect parent. Fixes https://github.com/sveltejs/svelte/issues/9410.
- I also fixed the `__` properties in operations, which were pointing to the wrong prototype.
> fix: address runtime effect issues

- sites/svelte-5-preview/src/lib/Output/Output.svelte
- sites/svelte-5-preview/src/lib/Repl.svelte
- sites/svelte-5-preview/src/lib/workers/compiler/index.js
- sites/svelte-5-preview/src/routes/+page.svelte
I wanted to see the AST when I do something for ESLint plugin.
> chore: Show AST on Svelte5 Playground

- .changeset/lucky-schools-hang.md
- packages/svelte/src/compiler/phases/2-analyze/index.js
- packages/svelte/tests/runtime-runes/samples/dynamic-style-attr/_config.js
- packages/svelte/tests/runtime-runes/samples/dynamic-style-attr/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9403. We weren't taking into account the containment of call expressions logic before.
> fix: support dynamic attributes containing call expressions

- .changeset/honest-icons-change.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/tests/runtime-legacy/samples/keyed-each-index-same/_config.js
- packages/svelte/tests/runtime-legacy/samples/keyed-each-index-same/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9408. Ensures that if we have a key that matches the index, that we fallback to using an indexed each block.
> fix: ensure keyed fallback to indexed

- documentation/blog/2023-06-29-svelte-dev-overhaul.md
Fixes a small typo in: https://svelte.dev/blog/svelte-dev-overhaul ❤️
> blog: fix typo in 'svelte.dev: A complete overhaul' blog entry

- documentation/blog/2023-06-29-svelte-dev-overhaul.md
merged in `main` already. copying it over to `version-4`
> blog: fix typo in 'svelte.dev: A complete overhaul' blog entry (#9438)

- .changeset/funny-wombats-argue.md
- packages/svelte/src/compiler/errors.js
- packages/svelte/src/compiler/phases/1-parse/state/element.js
- packages/svelte/tests/compiler-errors/samples/self-reference/_config.js
This closes #9436 however i'm not entirely sure we should do this.
On one hand is reasonable to be able to render <svelte:self /> inside a snippet that is than passed to a component even without an if block. On the other this remove a safe security pin against infinite loops if i do something like
```svelte
{#snippet infinite()}
<svelte:self />
{/snippet}
{@render infinite()}
```
at the same time this is still doable by doing this
```svelte
{#snippet infinite()}
{#if true}
<svelte:self />
{/if}
{/snippet}
{@render infinite()}
```
For the moment i've opened this PR but i leave this to the wise minds of the maintainers to decide what's best to do.
P.s. i did not include a test to check for this behavior because i didn't see tests to check that svelte:self is allowed inside the other …
> fix: allow svelte:self in snippets

- sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
Related to https://github.com/sveltejs/svelte/issues/9437
I considered allowing event attributes by strings, but I think it was better to mark it as a breaking change because it’s easy to avoid by the following code.
```svelte
<script>
window.foo = () => console.log("hi!")
const foo = window.foo;
</script>
<button onclick="{foo}">Hi!</button>
```
> docs: Update Breaking changes section

- .changeset/sour-rules-march.md
- packages/svelte/src/compiler/phases/3-transform/server/transform-server.js
- packages/svelte/tests/runtime-runes/samples/component-prop-unescaped/Child.svelte
- packages/svelte/tests/runtime-runes/samples/component-prop-unescaped/_config.js
- packages/svelte/tests/runtime-runes/samples/component-prop-unescaped/main.svelte
> fix: only escape attribute values for elements, not components

- .changeset/tiny-kings-whisper.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/src/compiler/phases/3-transform/server/transform-server.js
closes #9455. this code is very weird, it must have been left over from something. not worried about it regressing so i'm not bothering to clutter the test suite
> treat `slot` the same as other props

- .changeset/nasty-clocks-exercise.md
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/tests/runtime-runes/samples/runes-before-after-update/Child.svelte
- packages/svelte/tests/runtime-runes/samples/runes-before-after-update/_config.js
- packages/svelte/tests/runtime-runes/samples/runes-before-after-update/main.svelte
This PR addresses a bug with before/after update and adds a test case for the problem
> fix: address bug in before/after update

- .changeset/fresh-weeks-trade.md
- packages/svelte/src/internal/client/operations.js
- packages/svelte/src/internal/client/render.js
Rather than having the operations eager, we can make them lazy instead. This should fix issues with running the logic on the server and hopefully fix any failures with treeshaking.
> chore: make DOM operations lazily init

- .gitignore
- .vscode/settings.json
QOL change that means search results aren't duplicated when you use `Cmd-P` to quickly open files.
This means that VSCode settings are checked in, which prevents people having their own personal per-workspace settings. Which is probably fine, since personal settings probably belong outside the workspace, but maybe others feel differently?
> chore: configure search.exclude

- .changeset/curly-lizards-dream.md
- packages/svelte/src/internal/client/render.js
This is one of two possible solutions to the following problem: when hydrating, we check to see if `value` is identical to the value of `getAttribute(name)`, but `value` might not be a string. As a result, in cases like this...
```svelte
<div aria-current={some_boolean}>
```
...we unnecessarily call `setAttribute`. Worse (and unrelated to hydration), calling `setAttribute` with a non-string value causes an inexplicable slowdown.
The alternative fix is to coerce values before the `attr` function is called. Doing so would result in fewer `typeof` checks (since in some cases we already know the attribute is a string), but would result in larger output.
> fix: stringify attribute values before comparison

- .changeset/cuddly-pianos-drop.md
- packages/svelte/src/internal/client/render.js
- packages/svelte/src/internal/client/transitions.js
This PR improves the codesize of each blocks and general transition stuff by moving it to either be lazy or shared.
> Code golf each transitions

- .changeset/lazy-spiders-think.md
- packages/svelte/src/internal/client/render.js
- packages/svelte/tests/runtime-legacy/samples/binding-select-initial-value-undefined-3/_config.js
- packages/svelte/tests/runtime-legacy/samples/binding-select-initial-value-undefined-3/main.svelte
- packages/svelte/tests/runtime-legacy/samples/binding-select-unmatched-2/_config.js
- packages/svelte/tests/runtime-legacy/samples/binding-select-unmatched-2/main.svelte
when options are added later, we need to ensure the select value still stays in sync
fixes #9412
> fix: handle dynamic selects with falsy select values

- playgrounds/sandbox/run.js
small fix for easier debugging
> chore: add AST output to sandbox

- .changeset/soft-geese-learn.md
- packages/svelte/src/compiler/phases/bindings.js
- packages/svelte/tests/runtime-browser/samples/binding-files/_config.js
- packages/svelte/tests/runtime-browser/samples/binding-files/main.svelte
fixes https://github.com/sveltejs/svelte/issues/9419
Equivalent of https://github.com/sveltejs/svelte/pull/9080 which is for Svelte 4
> fix: allow setting `files` binding for `<input type="file" />` (Svelte 5)

- .changeset/clean-eels-beg.md
- packages/svelte/src/compiler/errors.js
- packages/svelte/src/compiler/phases/2-analyze/validation.js
- packages/svelte/tests/compiler-errors/samples/runes-no-derived-binding/_config.js
- packages/svelte/tests/compiler-errors/samples/runes-no-derived-binding/main.svelte
> fix: emit useful error on invalid binding to derived state

- .changeset/sharp-gorillas-impress.md
- packages/svelte/src/compiler/phases/2-analyze/index.js
- packages/svelte/tests/runtime-runes/samples/module-context-export/_config.js
- packages/svelte/tests/runtime-runes/samples/module-context-export/main.svelte
closes #9499. will merge once green as this is a blocker for #9482 
> fix: only treat instance context exports as accessors

- packages/svelte/src/compiler/phases/1-parse/state/element.js
just an idea. It's slightly more code on paper, but I think it's a clearer separation — top-level `<script>` and `<style>` can't have directives, spread, shorthand etc and this better reflects that IMHO
> chore: separate static attribute logic out into its own function

- sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
Fixes a small typo in https://svelte-5-preview.vercel.app/docs/breaking-changes#more-recent-browser-required
> docs: fix typo in Svelte 5 preview docs

- .changeset/afraid-moose-matter.md
- packages/svelte/src/compiler/phases/1-parse/state/element.js
- packages/svelte/src/compiler/preprocess/index.js
- packages/svelte/tests/parser-legacy/samples/script-attribute-with-curly-braces/input.svelte
- packages/svelte/tests/parser-legacy/samples/script-attribute-with-curly-braces/output.json
- packages/svelte/tests/preprocess/samples/attributes-with-closing-tag/_config.js
- packages/svelte/tests/preprocess/samples/attributes-with-closing-tag/input.svelte
- packages/svelte/tests/preprocess/samples/attributes-with-closing-tag/output.svelte
Related to sveltejs/language-tools#2204 / sveltejs/language-tools#2039
The Svelte 5 version of #9486 and #9498
> fix: tweak script/style tag parsing/preprocessing logic

- .changeset/ten-ducks-jump.md
- packages/svelte/src/compiler/parse/state/tag.js
- packages/svelte/test/parser/samples/script-attribute-with-curly-braces/input.svelte
- packages/svelte/test/parser/samples/script-attribute-with-curly-braces/output.json
Related to https://github.com/sveltejs/language-tools/issues/2204 / https://github.com/sveltejs/language-tools/issues/2039
> fix: ignore expressions in top level script/style tag attributes

- .changeset/wicked-doors-train.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/tests/runtime-runes/samples/bind-state-property/CheckBox.svelte
- packages/svelte/tests/runtime-runes/samples/bind-state-property/_config.js
- packages/svelte/tests/runtime-runes/samples/bind-state-property/main.svelte
Not sure how we missed this one, but we were never visiting binding assignments? Just noticed it by chance when looking into improving  `serialize_set_binding` usage. Fixes https://github.com/sveltejs/svelte/issues/9478
> fix: ensure we visit assignments during compilation

- .changeset/shiny-shrimps-march.md
- packages/svelte/src/internal/client/transitions.js
- packages/svelte/tests/runtime-legacy/samples/key-block-transition-global/_config.js
- packages/svelte/tests/runtime-legacy/samples/key-block-transition-global/main.svelte
There was a bug with how we propagate global intro transitions – otherwise we end up never clearing down the effects and content gets duplicated. This fixes that.
> fix: handle intro global transition propagation correctly

- .changeset/thirty-ghosts-fix.md
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/src/internal/client/types.d.ts
We can improve some areas of the signals runtime, credit to @localvoid for pointing these out to me. :)
> chore: tune signals for better runtime perf

- .changeset/hungry-dots-fry.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/global.js
- packages/svelte/src/internal/client/render.js
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/src/internal/client/transitions.js
- packages/svelte/src/internal/client/types.d.ts
- packages/svelte/tests/snapshot/samples/class-state-field-constructor-assignment/_expected/client/index.svelte.js
Rather than having a single monomorphic signal object, it can be just as fast two have two object shapes. This also reduces memory usage as the source signal shape can be cheaper.
> chore: more signal fine-tuning

- .changeset/odd-needles-joke.md
- packages/svelte/src/internal/client/render.js
- packages/svelte/src/internal/client/transitions.js
- packages/svelte/tests/runtime-legacy/samples/transition-js-each-block-intro-outro/_config.js
- packages/svelte/tests/runtime-legacy/samples/transition-js-if-else-block-intro/_config.js
Follow up to https://github.com/sveltejs/svelte/pull/9515. After getting feedback, we need to keep `intro` transition propagating but instead we need to clear them down accordingly in if blocks, like we do in other blocks. This was trickier to deal with as it turned out we had some tests that needed updating to reflect this behavior.
> fix: address intro transition bugs

- .changeset/early-ads-tie.md
- packages/svelte/src/internal/client/block.js
- packages/svelte/src/internal/client/reconciler.js
- packages/svelte/src/internal/client/render.js
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/src/internal/client/transitions.js
- packages/svelte/src/internal/client/types.d.ts
- packages/svelte/src/internal/server/index.js
- packages/svelte/src/main/main-client.js
This changes all our internal object properties to single characters. This improves code-size, parse time and also improves runtime performance across the board. It just makes the coder harder to read, so I've added comments throughout that labels what they are in most cases. I've likely missed some obvious ones though as there's so many properties going on here.
This saves 0.7kb min+gzip and improves parse time on the default SvelteKit app startup by 4ms!
> chore: rename internal object properties

- .changeset/kind-deers-lay.md
- packages/svelte/src/internal/client/block.js
- packages/svelte/src/internal/client/render.js
- packages/svelte/src/internal/client/transitions.js
- packages/svelte/src/internal/client/types.d.ts
Let's get them bytes down! This PR makes If block transitions lazy and also does a bunch in other areas to reduce code size around transitions.
> chore: more transition code-golfing

- packages/svelte/src/internal/client/reconciler.js
- packages/svelte/src/internal/client/render.js
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/src/internal/client/transitions.js
- packages/svelte/src/internal/client/utils.js
- packages/svelte/src/internal/common.js
- packages/svelte/tests/hydration/test.ts
> chore: shave off more bytes

- .changeset/khaki-turkeys-hunt.md
- packages/svelte/src/compiler/parse/state/tag.js
- packages/svelte/src/compiler/preprocess/index.js
- packages/svelte/test/parser/samples/script-context-module-unquoted/input.svelte
- packages/svelte/test/parser/samples/script-context-module-unquoted/output.json
a `+` was missing
Fixes https://github.com/sveltejs/vite-plugin-svelte/issues/804
> fix: adjust static attribute regex

- .changeset/gentle-spies-cover.md
- packages/svelte/src/compiler/compile/render_dom/wrappers/Element/index.js
- packages/svelte/src/runtime/internal/dom.js
- packages/svelte/test/runtime/samples/spread-from-import/_config.js
- packages/svelte/test/runtime/samples/spread-from-import/main.svelte
- packages/svelte/test/runtime/samples/spread-from-import/spread.js
Previously, if a part of the template was determined be be optimizable using innerHTML, it would error if there's a spread on an attribute.
I escaped the attribute values just to be extra sure although these can only be coming from purely static content anyway.
Discovered this while working on image optimization in SvelteKit.
> fix: handle spreads within static strings

- sites/svelte-5-preview/src/routes/docs/content/01-api/02-runes.md
- sites/svelte-5-preview/src/routes/docs/content/02-examples/02-fine-grained-reactivity.md
~~don't merge yet, it looks like there's a bug (we still reference `this.#foo.value` rather than `this.#foo.v` after #9532)~~ nvm, i just hadn't rebuilt the compiler locally
> document class state fields

- sites/svelte.dev/src/routes/auth/login/+server.js
- sites/svelte.dev/src/routes/docs/[slug]/+page.svelte
- sites/svelte.dev/src/routes/tutorial/[slug]/+page.svelte
> fix edit links

- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/src/internal/client/render.js
- packages/svelte/tests/runtime-legacy/samples/binding-select-initial-value-undefined-2/_config.js
- packages/svelte/tests/runtime-legacy/samples/binding-select-null-placeholder-2/_config.js
- packages/svelte/tests/runtime-legacy/samples/binding-select-null-placeholder-2/main.svelte
Resolves #9545
Also corrected misspellings and significantly streamlined the select binding code.
This does not address #9517. For that to work it seems like some kind of hook which runs after options are removed from the DOM will be necessary. I'm not yet familiar enough with Svelte 5 internals to know how best to implement this.
> fix: select enabled option with null value when it matches bound value

- .changeset/thirty-impalas-repair.md
- packages/svelte/src/compiler/phases/2-analyze/index.js
- packages/svelte/tests/runtime-legacy/samples/event-handler-mutation-scope/_config.js
- packages/svelte/tests/runtime-legacy/samples/event-handler-mutation-scope/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9561.
> Fix delegation bug

- .changeset/shiny-baboons-play.md
- packages/svelte/src/compiler/phases/1-parse/acorn.js
- packages/svelte/src/compiler/phases/1-parse/ambient.d.ts
- packages/svelte/src/main/public.d.ts
- packages/svelte/tests/types/snippet.ts
- packages/svelte/tsconfig.json
Intended usage is something like this:
```ts
let { banner } = $props<{ banner: Snippet<boolean> }>();
```
Language tools will adjust its output to type all snippets as a `Snippet<..>` variable, which guards against people passing in regular functions to snippet props.
related to #9447
> feat: add Snippet type

- playgrounds/sandbox/run.js
small thing — this generates the AST first in the sandbox, in case `parse` succeeds but `compile` fails
> chore: generate AST first when running sandbox

- .changeset/new-boats-wait.md
- packages/svelte/package.json
- pnpm-lock.yaml
- sites/svelte-5-preview/package.json
> chore: bump esrap

- packages/svelte/src/compiler/phases/2-analyze/validation.js
- packages/svelte/src/compiler/warnings.js
- packages/svelte/tests/validator/samples/inline-new-class-2/warnings.json
- packages/svelte/tests/validator/samples/inline-new-class-4/warnings.json
- packages/svelte/tests/validator/samples/inline-new-class/warnings.json
https://github.com/sveltejs/svelte/pull/9583#issuecomment-1823216240
no changeset because #9583 wasn't released yet
> chore: put nested class warning on the declaration, not the usage site

- .changeset/popular-mangos-rest.md
- packages/svelte/src/compiler/phases/2-analyze/validation.js
- packages/svelte/src/compiler/phases/3-transform/client/visitors/javascript-runes.js
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/src/compiler/phases/3-transform/server/transform-server.js
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/src/internal/index.js
- packages/svelte/tests/runtime-runes/samples/effect-active/_config.js
- packages/svelte/tests/runtime-runes/samples/effect-active/main.svelte
This adds the `$effect.active` rune, which returns a `boolean` to indicate if an effect is active. 
This gives us the ability to set up subscriptions when a value is read (in an effect, or in the template) but also read values without creating subscriptions, and without creating memory leaks.
> feat: add $effect.active rune

- packages/svelte/src/compiler/phases/2-analyze/index.js
- packages/svelte/src/compiler/phases/scope.js
- packages/svelte/src/compiler/utils/ast.js
i don't totally understand this logic, but i'm like 80% sure we can simplify it
> chore: remove get_callee_name

- packages/svelte/src/main/public.d.ts
language tools checks that a function passed to `{@render ..}` is returning a type that adheres to the `Snippet` return type. When it does not, the error message is pretty useless without this additional info text.
Before:
After:
No changelog because the Snippet type wasn't released yet.
> chore: better error message for not using snippet type

- .changeset/forty-comics-invent.md
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/tests/runtime-legacy/samples/event-handler-undefined/_config.js
- packages/svelte/tests/runtime-legacy/samples/event-handler-undefined/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9610.
> fix: handle undefined bubble events

- .changeset/odd-schools-wait.md
- packages/svelte/src/internal/client/validate.js
I missed this when implementing the validation logic in DEV.
> chore: untrack keyed validation logic

- .changeset/dirty-garlics-design.md
- packages/svelte/src/main/ambient.d.ts
I noticed that `$effect.active` was increasing when I was working on something else. I wanted to add a type to `svelte-eslint-parser`, but noticed that there was no type definition.
> feat: add type of `$effect.active`

- sites/svelte-5-preview/src/routes/docs/content/01-api/02-runes.md
I found a few typos when I working on `svelte-eslint-parser`.
> docs: fix typos of runes docs

- .changeset/moody-frogs-exist.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/tests/runtime-runes/samples/member-mutation/_config.js
- packages/svelte/tests/runtime-runes/samples/member-mutation/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9546.
> fix: improve member expression mutation logic

- .changeset/chilled-pumas-invite.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
Missed this is a recent refactor of each blocks.
> fix: apply keyed validation only for keyed each

- .changeset/lovely-rules-eat.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/tests/runtime-runes/samples/each-bind-this-member/_config.js
- packages/svelte/tests/runtime-runes/samples/each-bind-this-member/main.svelte
fixes #9629
Not sure if this catches all cases that matter. Maybe we need `() => exposable(..))` and then do `expose(binding())` in `bind_this` instead.
> fix: omit this bind this arg if we know it's not a signal

- playgrounds/demo/package.json
- playgrounds/demo/scripts/App.template.svelte
- playgrounds/demo/scripts/create-app-svelte.js
- playgrounds/demo/vite.config.js
- pnpm-lock.yaml
to exclude svelte from being optimized and generate an App.svelte so first run doesn't throw
> chore: update playgrounds/demo 

- .changeset/polite-pumpkins-guess.md
- packages/svelte/src/compiler/phases/2-analyze/a11y.js
- packages/svelte/src/compiler/warnings.js
- packages/svelte/tests/validator/samples/a11y-click-events-have-key-events/input.svelte
- packages/svelte/tests/validator/samples/a11y-click-events-have-key-events/warnings.json
- packages/svelte/tests/validator/samples/a11y-interactive-supports-focus/warnings.json
- packages/svelte/tests/validator/samples/a11y-mouse-events-have-key-events/warnings.json
- packages/svelte/tests/validator/samples/slot-warning/warnings.json
- packages/svelte/tests/validator/samples/slot-warning2/warnings.json
also adjusted the warning messages slightly so they make sense for both variants of event handlers
fixes #9654
> fix: take event attributes into account when checking a11y

- .changeset/slimy-clouds-talk.md
- packages/svelte/src/internal/client/render.js
- packages/svelte/tests/hydration/samples/ignore-mismatched-href/_before.html
- packages/svelte/tests/hydration/samples/ignore-mismatched-href/_config.js
- packages/svelte/tests/hydration/samples/ignore-mismatched-href/main.svelte
Putting this up for discussion. Currently, a SvelteKit app will often render HTML with relative paths, which are replaced with absolute paths upon hydration. (This behaviour is intentional — it means that the HTML is more portable and resilient, for example if it ends up on the Internet Archive or on IPFS. It will likely be the default for all base-relative paths in SvelteKit 2.0.)
The cost is that something like `<a href="{paths.base}/whatever">` will differ between SSR and CSR:
- `<a href="../whatever">`
- `<a href="https://example.com/foo/bar/whatever">`
As a result, Svelte updates the attribute during hydration, even though it resolves to the same URL.
For `src` and `srcset` attributes, we always skip hydration, on the assumption that the resolved value will be unchanged. (In dev, we …
> feat: ignore href when hydrating

- .changeset/friendly-lies-camp.md
- packages/svelte/src/compiler/phases/2-analyze/index.js
- packages/svelte/src/compiler/phases/scope.js
- packages/svelte/src/compiler/types/index.d.ts
- packages/svelte/src/compiler/warnings.js
- packages/svelte/tests/validator/samples/runes-referenced-nonstate/_config.js
- packages/svelte/tests/validator/samples/runes-referenced-nonstate/input.svelte
- packages/svelte/tests/validator/samples/runes-referenced-nonstate/warnings.json
- packages/svelte/tests/validator/samples/runes-state-rune-not-mutated/warnings.json
> Warn on referenced mutated nonstate

- .changeset/thin-foxes-lick.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/src/internal/client/render.js
- packages/svelte/tests/snapshot/samples/svelte-element/_config.js
- packages/svelte/tests/snapshot/samples/svelte-element/_expected/client/index.svelte.js
- packages/svelte/tests/snapshot/samples/svelte-element/_expected/server/index.svelte.js
- packages/svelte/tests/snapshot/samples/svelte-element/index.svelte
- doesn't add `spread_dynamic_element_attributes` when there are no attributes — #9646 (TODO: why are we using this instead of the normal mechanism for setting attributes? Seems weird to always deopt to spread attributes. we can leave that issue open for now)
- skips the child render function altogether if there is nothing to do
> chore: improve output for `<svelte:element>`

- .changeset/seven-ravens-check.md
- .changeset/slimy-clouds-talk.md
I noticed we didn't mention that this applies to `src` and `srcset` as well, which I thought was important to mention. Not sure about the patch/ minor level. Feel free to keep that as patch if more appropriate
> chore: tweak changeset

- .changeset/rare-pears-whisper.md
- packages/svelte/src/compiler/errors.js
- packages/svelte/src/compiler/phases/2-analyze/validation.js
- packages/svelte/src/compiler/phases/3-transform/client/visitors/javascript-runes.js
- packages/svelte/src/compiler/phases/constants.js
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/src/internal/index.js
- packages/svelte/src/main/ambient.d.ts
- packages/svelte/tests/runtime-runes/samples/effect-root/_config.js
- packages/svelte/tests/runtime-runes/samples/effect-root/main.svelte
- sites/svelte-5-preview/src/routes/docs/content/01-api/02-runes.md
The `$effect.root` rune is an advanced feature that creates a non-tracked scope that doesn't auto-cleanup. This is useful for nested effects that you want to manually control. This rune also allows for creation of effects outside of the component initialisation phase.
```svelte
<script>
let count = $state(0);
const cleanup = $effect.root(() => {
console.log(count);
});
return () => {
console.log('effect root cleanup');
};
});
</script>
```
> feat: add $effect.root rune

- .changeset/twelve-onions-juggle.md
- packages/svelte/src/compiler/phases/2-analyze/index.js
- packages/svelte/src/compiler/phases/2-analyze/validation.js
- packages/svelte/src/compiler/phases/3-transform/client/visitors/javascript-runes.js
- packages/svelte/src/compiler/phases/3-transform/server/transform-server.js
- packages/svelte/src/compiler/utils/ast.js
- packages/svelte/tests/runtime-runes/samples/typescript-as-expression/_config.js
- packages/svelte/tests/runtime-runes/samples/typescript-as-expression/main.svelte
- packages/svelte/tests/runtime-runes/samples/typescript-non-null-expression/_config.js
- packages/svelte/tests/runtime-runes/samples/typescript-non-null-expression/main.svelte
related to #9639
I hope this isn't the start of an exhausting game of whack-a-mole. If anyone has better ideas how to handle this at one central location that doesn't require any further maintenance, that would be great. Maybe it's fine though, this is only really relevant when inspecting a handful of declarations AFAIK.
> fix: handle ts expressions when dealing with runes

- .changeset/kind-eagles-join.md
- packages/svelte/elements.d.ts
Add this here so that libraries doing `$props<HTMLButtonAttributes>()` don't need a separate interface
fixes #https://github.com/sveltejs/language-tools/issues/2218
> fix: add children to element typings

- .changeset/famous-knives-sneeze.md
- packages/svelte/src/compiler/phases/3-transform/server/transform-server.js
- packages/svelte/tests/runtime-runes/samples/snippet-dynamic-children/Button.svelte
- packages/svelte/tests/runtime-runes/samples/snippet-dynamic-children/_config.js
- packages/svelte/tests/runtime-runes/samples/snippet-dynamic-children/main.svelte
place anchors around render tags, not snippet tags
fixes #9678
closes #9675
> fix: ensure implicit children snippet renders correctly

- .changeset/sour-forks-stare.md
- packages/svelte/src/internal/client/hydration.js
- packages/svelte/src/internal/client/render.js
Turns out we don't need to set `$$fragment` to `undefined` anymore. Also noticed some suspect code just below it that should probably be fixed too.
> chore: remove redundant hydration code

- .changeset/hungry-tips-unite.md
- packages/svelte/src/internal/client/custom-element.js
- packages/svelte/tests/runtime-browser/custom-elements-samples/set-property-before-mounted/_config.js
- packages/svelte/tests/runtime-browser/custom-elements-samples/set-property-before-mounted/main.svelte
> fix: port over props that were set prior to initialization

- .changeset/swift-ravens-hunt.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/src/compiler/phases/3-transform/server/transform-server.js
- packages/svelte/src/internal/server/index.js
- packages/svelte/tests/runtime-runes/samples/event-attribute-template/_config.js
- packages/svelte/tests/runtime-runes/samples/event-attribute-template/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9694.
> fix: improve template text node serialization

- .changeset/lemon-geese-drum.md
- .changeset/two-dragons-yell.md
- packages/svelte/src/internal/client/runtime.js
- packages/svelte/src/main/ambient.d.ts
- packages/svelte/tests/runtime-runes/samples/inspect-derived/_config.js
- packages/svelte/tests/runtime-runes/samples/inspect-derived/main.svelte
> fix: correctly inspect derived values

- .changeset/selfish-tools-hide.md
- packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js
- packages/svelte/tests/runtime-runes/samples/props-derived/Child.svelte
- packages/svelte/tests/runtime-runes/samples/props-derived/_config.js
- packages/svelte/tests/runtime-runes/samples/props-derived/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9751. Ensures computed props that contain call expressions are cached in derived signals.
> fix: ensure computed props are cached with derived

- .changeset/serious-socks-cover.md
- packages/svelte/src/compiler/phases/2-analyze/index.js
- packages/svelte/src/compiler/phases/scope.js
- packages/svelte/src/compiler/types/index.d.ts
- packages/svelte/tests/runtime-runes/samples/event-arguments-2/_config.js
- packages/svelte/tests/runtime-runes/samples/event-arguments-2/main.svelte
- packages/svelte/tests/runtime-runes/samples/event-arguments/_config.js
- packages/svelte/tests/runtime-runes/samples/event-arguments/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9690. Fixes https://github.com/sveltejs/svelte/issues/9689.
> fix: ensure event handlers containing arguments are not hoisted
