site/content/docs/02-template-syntax.md, src/compiler/compile/nodes/Body.ts, src/compiler/compile/render_dom/wrappers/Body.ts, src/compiler/compile/render_dom/wrappers/shared/add_actions.ts, src/compiler/interfaces.ts, test/runtime/samples/action-body/_config.js, test/runtime/samples/action-body/main.svelte
Fixes #3163
should we explicitly mention that actions can be applied on svelte:body as well in https://svelte.dev/docs#svelte_body?
=> [feat] allow action applied on svelte:body

.github/workflows/docs.yml
Adds a workflow to publish docs changes to the API when merged into master.
=> docs: set up docs workflow

CHANGELOG.md, site/content/blog/2020-12-01-whats-new-in-svelte-december-2020.md, site/content/docs/04-compile-time.md, test/sourcemaps/samples/attached-sourcemap/test.js
Tiny spelling fixes.  Thanks for your work.
=> docs: small spelling fixes in docs and comments

site/content/tutorial/02-reactivity/04-updating-arrays-and-objects/text.md
I am just following along with the tutorial, and if I understand everything correctly (which is not a given!) this change improves the  clarity of the wording around reactivity.
=> [docs] clarify reactivity tutorial text

src/compiler/utils/names.ts
=> Add `BigInt` as known global

src/runtime/transition/index.ts
As discussed in https://github.com/sveltejs/svelte/pull/6195/files#r706326069
=> [fix] deduplicate getComputedStyle call

CHANGELOG.md, src/compiler/preprocess/types.ts
Is only used internally, shouldn't be exposed. Fixes #6622
=> [fix] make Source type in preprocess private

site/content/docs/03-run-time.md
=> [docs] clarify readable callback timing

site/content/blog/2021-10-01-whats-new-in-svelte-october-2021.md
Feeling pretty good about this month's edition. As usual, @benmccann (or anyone else), feel free to correct me on my interpretation of the SvelteKit changelog.
Happy 1 year anniversary of the "What's new in Svelte" posts on the Svelte blog!
=> [docs] "What's new in Svelte" October newsletter

site/content/examples/16-context/00-context-api/Map.svelte, site/content/tutorial/15-context/01-context-api/app-a/Map.svelte, site/content/tutorial/15-context/01-context-api/app-b/Map.svelte
=> [docs] use on directives for link load 

site/content/examples/03-logic/03-each-blocks/App.svelte
The `03-each-blocks` instance has been made more readable and the EOL problem has been fixed.
https://svelte.dev/examples#each-blocks
=> [docs] update 03-each-blocks sample for readable

site/content/tutorial/01-introduction/07-making-an-app/text.md
=> [fix] broken tutorial link to community-maintained tools

site/content/docs/02-template-syntax.md
=> [docs] Fix a typo in 02-template-syntax.md

site/content/docs/03-run-time.md
=> [docs] Fix a typo in 03-run-time.md

site/package-lock.json, site/package.json, site/svelte.config.js
Hoping to boost our Google Page Speed score
=> site: disable Vite vendor chunk

README.md
Looks like it was missed in #6811. Should it be more specific that the site was first in Sapper then later migrated to SvelteKit?
=> [chore] Reflect migration of site to SvelteKit in readme

site/scripts/get_contributors.js, site/scripts/get_donors.js, site/src/routes/_components/Contributors.svelte, site/src/routes/_components/Donors.svelte, site/src/routes/index.svelte
This takes us another step closer to [the proposed design changes](https://www.figma.com/file/f87psJnCeqMbUPAQABmCrN/svelte?node-id=19%3A176)
=> [site] only show 20 avatars instead of current massive wall

site/src/routes/blog/_posts.js, site/src/routes/docs/_sections.js, site/src/routes/faq/_faqs.js, site/src/routes/tutorial/[slug]/index.json.js
can't deploy to production currently. this should fix it
=> [fix] allow site to run again after marked upgrade

site/content/blog/2020-12-01-whats-new-in-svelte-december-2020.md, site/content/blog/2021-03-01-whats-new-in-svelte-march-2021.md, site/content/blog/2021-04-01-whats-new-in-svelte-april-2021.md, site/content/docs/01-component-format.md, site/content/docs/02-template-syntax.md, site/content/docs/03-run-time.md, site/content/tutorial/01-introduction/07-making-an-app/text.md, site/content/tutorial/08-stores/04-derived-stores/text.md
Fixes https://github.com/sveltejs/sites/issues/116
---
For reference, this was the script I used (the imported `slug.js` is [this file](https://github.com/sveltejs/action-deploy-docs/blob/157729fa4697d7d319e47091836dc40dbfa17372/src/format/slug.ts)):
```js
import fs from 'fs';
import glob from 'tiny-glob/sync.js';
import { make_session_slug_processor as make_old_slug_processor } from '@sveltejs/site-kit/utils/slug.js';
import { make_new_slug_processor } from './slug.js';
const make_old_slug = make_old_slug_processor({
preserve_unicode: false,
separator: '_'
});
const make_new_slug = make_new_slug_processor({
preserve_unicode: false,
separator: '-'
});
// step 1 — create map
const map = new Map();
for (const file …
```
=> [docs] fix hash fragments

site/content/examples/00-introduction/01-dynamic-attributes/App.svelte, site/content/tutorial/01-introduction/03-dynamic-attributes/app-a/App.svelte, site/content/tutorial/01-introduction/03-dynamic-attributes/app-b/App.svelte
Fixes the second issue noted in https://github.com/sveltejs/sites/issues/229
=> [docs] fix path to /tutorial/image.gif

site/content/blog/2022-01-01-whats-new-in-svelte-january-2022.md
Great month, this month! Please let me know if I missed anything :) Happy new year!
=> [docs] "What's new in Svelte" January newsletter

src/compiler/utils/namespaces.ts, test/js/samples/src-attribute-check-in-foreign/expected.js
=> [fix] foreign namespace hash link

src/compiler/compile/render_dom/wrappers/Element/index.ts, test/runtime/samples/inline-style-directive-string-variable-kebab-case/_config.js, test/runtime/samples/inline-style-directive-string-variable-kebab-case/main.svelte
This fixes #7122 and includes a new test as well
=> [fix] kebab case style directives with template causes syntax error

src/compiler/compile/render_dom/wrappers/Element/index.ts, test/runtime/samples/inline-style-directive-shorthand/_config.js, test/runtime/samples/inline-style-directive-shorthand/main.svelte
=> fix: style directive in each loop non-reactive

src/compiler/compile/nodes/shared/Expression.ts, test/runtime/samples/const-tag-each-arrow/_config.js, test/runtime/samples/const-tag-each-arrow/main.svelte
fix: https://github.com/sveltejs/svelte/issues/7134
=> [fix] fix crash when using arrow functions in {@const}

site/content/docs/05-accessibility-warnings.md
=> [docs] add docs for a11y-no-redundant-roles

src/compiler/utils/names.ts
[`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) is real
=> [fix] add `FormData` as a known global

src/compiler/compile/compiler_errors.ts, src/compiler/compile/nodes/InlineComponent.ts, test/validator/samples/component-invalid-style-directive/errors.json, test/validator/samples/component-invalid-style-directive/input.svelte
This is for the feature request #7177 . Passes all the tests, fails with 2 lint errors that are unrelated to my changes. I've added one test.
=> [feat] Error message for inline component style directive

site/content/blog/2022-02-01-whats-new-in-svelte-february-2022.md
I'm pretty sure I missed a few SvelteKit changes. Otherwise, a pretty blog-link heavy showcase (with quite a bit of web3 going on). 
Feel free to cut anything that feels a bit too far off-topic. This month, I stayed away from starters unless they demonstrated something really different than what we usually see.
=> [docs] "What's new in Svelte" February newsletter

site/content/blog/2021-03-23-sveltekit-beta.md, site/content/blog/2021-05-01-whats-new-in-svelte-may-2021.md, site/content/blog/2021-09-01-whats-new-in-svelte-september-2021.md, site/content/blog/2022-02-01-whats-new-in-svelte-february-2022.md
Updates all links referencing kit site to the new multi-page docs links, especially needed for the most recent blog post as that's going to be the one most people read.
=> [docs] update to multi-page docs links

CONTRIBUTING.md
Updated CONTRIBUTING.md to update the link with the correct label.
=> [docs] Fix feature request link

site/content/blog/2022-03-01-whats-new-in-svelte-march-2022.md
Might be a bit early to capture the changes to Svelte core in this post... please feel free to add any relevant changes as the month goes by :)
I'll do another pass at the Svelte and SvelteKit changelog toward the end of the month. Just wanted to get ahead on a holiday weekend (in the US)
=> [docs] "What's new in Svelte" March newsletter

site/content/blog/2022-03-01-whats-new-in-svelte-march-2022.md
=> [docs] add `-` to the beginning of the line

site/content/tutorial/17-module-context/02-module-exports/text.md
=> [docs] fix small typo in tutorial

package.json
This PR updates svelte homepage on npm.
=> [docs] update homepage

src/compiler/utils/names.ts
=> [fix] add Symbol to globals

site/content/faq/800-how-do-i-test-svelte-apps.md
vitest is newish but works great for vite+svelte apps (and should even work with the old standard template). Link it here.
=> [docs] add link to vitest svelte example to test faq

site/content/docs/03-run-time.md, site/content/tutorial/09-motion/02-spring/text.md
Fixes https://github.com/sveltejs/svelte/issues/4256
- Add more code examples for the spring store
- Add link from tutorial to the docs
=> [docs] add more examples on the spring store API docs

site/content/tutorial/07-lifecycle/01-onmount/app-b/App.svelte
Fixes https://github.com/sveltejs/svelte/issues/6233
=> [docs] use own api to replace jsonplaceholder.typicode.com

src/compiler/compile/render_dom/wrappers/Element/index.ts
Hi
I have fixed a typo error: a double semicolon at the end of line
ciao
matteo
- [ x] Prefix your PR title with `[feat]`, `[fix]`, `[chore]`, or `[docs]`.
=> [fix] remove duplicate semicolon

site/content/blog/2019-04-16-svelte-for-new-developers.md, site/content/tutorial/01-introduction/07-making-an-app/text.md
Companion to https://github.com/sveltejs/sites/pull/349
=> [docs] update getting started info

.gitignore, package.json
It appears that forgot to remove config related to nyc in this commit.
https://github.com/sveltejs/svelte/commit/f1ca1cc0983ddf68c89f596776f54717c4075ede
=> [chore] remove nyc stuff

site/content/blog/2022-08-01-whats-new-in-svelte-august-2022.md
Covered the upcoming changes to `load` in the intro.
=> [docs] "What's new in Svelte" August newsletter

site/content/blog/2020-12-01-whats-new-in-svelte-december-2020.md, site/content/blog/2021-02-01-whats-new-in-svelte-february-2021.md, site/content/blog/2021-03-01-whats-new-in-svelte-march-2021.md, site/content/blog/2021-09-01-whats-new-in-svelte-september-2021.md, site/content/blog/2021-10-01-whats-new-in-svelte-october-2021.md, site/content/blog/2021-11-01-whats-new-in-svelte-november-2021.md, site/content/blog/2022-04-01-whats-new-in-svelte-april-2022.md, site/content/tutorial/14-composition/04-optional-slots/app-a/App.svelte, site/content/tutorial/14-composition/04-optional-slots/app-b/App.svelte
=> [docs] fix spellings error

site/content/docs/01-component-format.md
@dummdidumm and I were both unaware of some of the finer points, so I thought I'd clarify the docs. I did a review of the whole section to make things clearer
=> [docs] clarify reactivity rules

site/content/tutorial/16-special-elements/04-svelte-window/app-a/App.svelte, site/content/tutorial/16-special-elements/04-svelte-window/app-b/App.svelte
use KeyboardEvent.code instead of deprecated KeyboardEvent.keyCode
=> [docs] use KeyboardEvent.code

CHANGELOG.md
I closed https://github.com/sveltejs/svelte/issues/7240 by misunderstanding.
I will be careful not to make the same mistake.
And thank you for the reporting @Prinzhorn 🙏
=> [chore] fix wrong changelog

src/compiler/compile/css/Selector.ts, test/css/samples/dynamic-element-tag/_config.js, test/css/samples/dynamic-element-tag/expected.css, test/css/samples/dynamic-element-tag/expected.html, test/css/samples/dynamic-element-tag/input.svelte
=> [fix] apply class for dynamic elements

src/runtime/internal/Component.ts, test/runtime/samples/component-events-nullish/Widget.svelte, test/runtime/samples/component-events-nullish/_config.js, test/runtime/samples/component-events-nullish/main.svelte
=> [feat] allow nullish values for component event handlers

src/runtime/internal/Component.ts
=> [fix] fix ctx and dirty type

site/content/docs/03-template-syntax.md, src/compiler/compile/nodes/InlineComponent.ts, src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts, src/compiler/compile/render_ssr/handlers/InlineComponent.ts, src/compiler/utils/namespaces.ts, test/runtime-puppeteer/samples/component-css-custom-properties-dynamic-svg/Svg.svelte, test/runtime-puppeteer/samples/component-css-custom-properties-dynamic-svg/_config.js, test/runtime-puppeteer/samples/component-css-custom-properties-dynamic-svg/main.svelte
=> [feat] Support style props for SVG component

src/runtime/internal/Component.ts, src/runtime/internal/await_block.ts, src/runtime/internal/transitions.ts, src/runtime/internal/types.ts, test/runtime/samples/await-mount-and-unmount-immediately/Component.svelte, test/runtime/samples/await-mount-and-unmount-immediately/_config.js, test/runtime/samples/await-mount-and-unmount-immediately/main.svelte
=> [fix] call on_destroy if unmounted called immediately before on_mount

src/compiler/parse/errors.ts, src/compiler/parse/state/tag.ts, test/validator/samples/html-block-in-attribute/errors.json, test/validator/samples/html-block-in-attribute/input.svelte, test/validator/samples/html-block-in-textarea/errors.json, test/validator/samples/html-block-in-textarea/input.svelte, test/validator/samples/logic-block-in-attribute/errors.json, test/validator/samples/logic-block-in-attribute/input.svelte, test/validator/samples/logic-block-in-textarea/errors.json, test/validator/samples/logic-block-in-textarea/input.svelte
=> [feat] better error message for invalid logic block placement

site/content/docs/01-getting-started.md
looks like this place didn't get update with the others since it was in a pending PR and I missed it when merging the PR
=> [docs] update SvelteKit status

site/content/docs/03-template-syntax.md
=> [docs] Improve grammar

site/content/examples/03-logic/03-each-blocks/App.svelte
When running the example, at the bottom of the page a warning message is displayed.
```
Security: Anchor with "target=_blank" should have rel attribute containing the value "noreferrer" (14:3)
```
[Example Link](https://svelte.dev/examples/each-blocks)
=> [docs] fix warning caused by recently added check

site/content/blog/2022-11-01-whats-new-in-svelte-november-2022.md
Big one this month. Let me know if I missed anything!
=> [docs] "What's new in Svelte" November newsletter

CONTRIBUTING.md
*Updated the link to the feature request issue template
=> [chore] Update link to feature request template

site/content/blog/2022-11-01-whats-new-in-svelte-november-2022.md
=> [docs] fix link in November newsletter

site/content/faq/800-how-do-i-test-svelte-apps.md
WebdriverIO v8 comes with component testing capabilities with presets for Svelte apps. I believe it should be added as alternative solution as it is the only framework that uses a web standard for automation and tests in real browser.
=> [docs] Add WebdriverIO as alternative testing solution

.gitignore, package.json
=> chore: add eslintcache

.github/workflows/ci.yml
https://github.com/nodejs/release#release-schedule
Node.js 18 has been LTS now, and 16 is Maintenance.
=> [ci]: upgrade node to 18

src/compiler/compile/nodes/shared/Expression.ts, test/runtime/samples/const-tag-invalidate/_config.js, test/runtime/samples/const-tag-invalidate/main.svelte
=> [fix] allow invalidating variables from @const declared function

src/runtime/internal/ssr.ts, test/runtime/samples/css-vars-escape/Sub.svelte, test/runtime/samples/css-vars-escape/_config.js, test/runtime/samples/css-vars-escape/main.svelte, test/runtime/samples/inline-style-directive-escape/_config.js, test/runtime/samples/inline-style-directive-escape/main.svelte
fix: https://github.com/sveltejs/svelte/issues/8085
=> [fix] escape style attribute for SSR

site/content/docs/01-getting-started.md
closes https://github.com/sveltejs/svelte/issues/8091
=> [docs] add some basic docs about bundler plugins

src/runtime/internal/utils.ts, test/runtime/samples/await-function-promise/_config.js, test/runtime/samples/await-function-promise/main.svelte
I wrongly closed https://github.com/sveltejs/svelte/pull/7790 and I have no idea how to reopen this.
So I created one more PR.
@Vilsol I'm so sorry for closing your PR🙏
I cherry-picked your commit. So your name will register to the commit log.
=> [fix] correctly handle promises that are of function type (add License)

src/compiler/compile/render_dom/wrappers/RawMustacheTag.ts
I found a import statement can be shortened in file `src/compiler/render_dom/wrappers/RawMustacheTag.ts`
=> [chore] shorten `import` statement

elements/index.d.ts
=> [fix] Adding part HTML attribute to typings, fixing #8181

site/content/tutorial/02-reactivity/04-updating-arrays-and-objects/text.md
=> [fix] just a typo

src/compiler/compile/render_dom/index.ts, test/js/samples/css-shadow-dom-keyframes/expected.js
Fixes https://github.com/sveltejs/svelte/issues/8134
=> feat: `trusted-types` CSP compatibility for Web Components

site/content/docs/02-component-format.md
=> docs: Missing semicolon at the end of the statement

CHANGELOG.md, src/compiler/compile/compiler_errors.ts, src/compiler/compile/nodes/Binding.ts, src/compiler/compile/nodes/Element.ts, test/js/samples/capture-inject-state/expected.js, test/js/samples/capture-inject-state/input.svelte
This PR just fixes a few random typos.
=> fix: correct typos in variable names

site/content/tutorial/04-logic/05-keyed-each-blocks/app-a/Thing.svelte, site/content/tutorial/04-logic/05-keyed-each-blocks/app-b/Thing.svelte
To clarify the logic of `each` block, a log was added of which `<Thing>` component has been destroyed.
=> docs: update Keyed Each Blocks tutorial

src/runtime/transition/index.ts
closes #4344
fixes #4111
no test because none of these built-ins have them, and because it's likely completely overhauled later anyway. Confirmed the fix (and no regression) through manual testing
=> fix: compute rect directly before crossfading

package-lock.json, src/compiler/compile/render_dom/wrappers/Element/Attribute.ts, src/shared/boolean_attributes.ts, test/runtime/samples/attribute-boolean-indeterminate/_config.js, test/runtime/samples/attribute-boolean-inert/_config.js, test/runtime/samples/attribute-boolean-inert/main.svelte, test/runtime/samples/attribute-boolean-itemscope/_config.js, test/runtime/samples/attribute-boolean-itemscope/main.svelte
Add tests for https://github.com/sveltejs/svelte/pull/7931
=> fix: better handling of inert attribute (add tests)

site/content/docs/03-template-syntax.md, src/compiler/compile/nodes/Element.ts, src/compiler/compile/render_dom/wrappers/Element/EventHandler.ts, src/runtime/internal/dev.ts, src/runtime/internal/dom.ts, test/js/samples/event-modifiers/expected.js, test/js/samples/event-modifiers/input.svelte, test/runtime/samples/event-handler-modifier-stop-immediate-propagation/_config.js, test/runtime/samples/event-handler-modifier-stop-immediate-propagation/main.svelte, test/validator/samples/event-modifiers-invalid/errors.json
Reopened https://github.com/sveltejs/svelte/pull/5086
Fixes https://github.com/sveltejs/svelte/issues/5085
The fork from the original PR has been deleted by the author
=> feat: add stopImmediatePropagation to event modifier

src/compiler/compile/css/Selector.ts, test/validator/samples/css-invalid-global-placement-5/errors.json, test/validator/samples/css-invalid-global-placement-5/input.svelte
looking at https://github.com/sveltejs/svelte/pull/6322 again, i realised the check isn't correct
=> fix: validation for global compound selector

src/compiler/compile/render_dom/Block.ts, src/compiler/compile/render_dom/Renderer.ts, src/compiler/compile/render_dom/wrappers/Element/Binding.ts, src/runtime/internal/dom.ts, test/runtime-puppeteer/index.ts, test/runtime/samples/binding-input-group-if-gh-8372-1/_config.js, test/runtime/samples/binding-input-group-if-gh-8372-1/main.svelte, test/runtime/samples/binding-input-group-if-gh-8372-2/_config.js, test/runtime/samples/binding-input-group-if-gh-8372-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/8372
=> fix: binding group with if block

src/compiler/utils/get_code_frame.ts
just a small thing I noticed while reading through the code
=> chore: rename variable to follow coding style

sites/svelte.dev/README.md, sites/svelte.dev/src/routes/blog/+page.svelte
Updates the readme to specify content structure, processing paths, etc
Closes #8451
=> docs(site-2): Update readme

CHANGELOG.md, package.json
we missed this in https://github.com/sveltejs/svelte/pull/8482
=> chore: bump engines field

sites/svelte.dev/package-lock.json, sites/svelte.dev/package.json, sites/svelte.dev/src/lib/components/PreloadingIndicator.svelte, sites/svelte.dev/src/lib/components/ReplWidget.svelte, sites/svelte.dev/src/routes/(authed)/apps/+page.svelte, sites/svelte.dev/src/routes/(authed)/repl/[id]/+page.svelte, sites/svelte.dev/src/routes/(authed)/repl/[id]/AppControls.svelte, sites/svelte.dev/src/routes/(authed)/repl/[id]/UserMenu.svelte, sites/svelte.dev/src/routes/(authed)/repl/embed/+page.svelte, sites/svelte.dev/src/routes/+error.svelte, sites/svelte.dev/src/routes/+page.svelte, sites/svelte.dev/src/routes/_components/Demo.svelte, sites/svelte.dev/src/routes/_components/Example.svelte, sites/svelte.dev/src/routes/_components/Hero.svelte, sites/svelte.dev/src/routes/_components/Section.svelte, sites/svelte.dev/src/routes/blog/+page.svelte, sites/svelte.dev/src/routes/blog/[slug]/+page.svelte, sites/svelte.dev/src/routes/examples/[slug]/+page.svelte, sites/svelte.dev/src/routes/examples/[slug]/TableOfContents.svelte, sites/svelte.dev/src/routes/faq/+page.svelte, sites/svelte.dev/src/routes/tutorial/[slug]/+page.svelte, sites/svelte.dev/tsconfig.json
This removes old site-kit variables and switches to site-kit v5
=> feat(site-2): Remove legacy site-kit stuff

.github/workflows/ci.yml
Sent against the v4 branch to reduce merge conflicts
=> chore: run CI tests on Node 20

src/runtime/internal/dom.ts, test/runtime/samples/inline-style-become-undefined/_config.js, test/runtime/samples/inline-style-become-undefined/main.svelte
closes: https://github.com/sveltejs/svelte/issues/8462
call removeProperty when style value become undefined.
=> fix: inline style value become undefined

sites/svelte.dev/package-lock.json, sites/svelte.dev/package.json, sites/svelte.dev/vite.config.js
We can finally delete the worker hack code 🎉
=> chore(site-2): Upgrade vite 4.3

elements/index.d.ts, site/content/docs/03-template-syntax.md, src/compiler/compile/nodes/Window.ts, src/compiler/compile/render_dom/wrappers/Window.ts, test/runtime/samples/window-binding-resize/_config.js, test/runtime/samples/window-binding-resize/main.svelte, test/validator/samples/window-binding-invalid/errors.json
closes: https://github.com/sveltejs/svelte/issues/8285
add window bind devicePixelRatio support, change devicePixelRatio on window resize.
=> feat: add window bind devicePixelRatio support

.github/workflows/release.yml, package.json
=> fix: changeset scripts

sites/svelte.dev/src/routes/_components/Try.svelte, sites/svelte.dev/svelte.config.js
the centering doesn't look good on mobile, and the `<h2>` isn't actually centered. plus there's a huge amount of unnecessary whitespace beneath it (it's also unbalanced on wider screens). i think this works better
=> fix terminal

package.json, sites/svelte.dev/package.json
Avoid duplicating work and logs clutter from warnings in ecosystem CI
=> chore: exclude sites from build script

documentation/blog/2019-04-22-svelte-3-rethinking-reactivity.md, sites/svelte.dev/package.json, sites/svelte.dev/scripts/type-gen/index.js, sites/svelte.dev/src/app.html, sites/svelte.dev/src/lib/server/docs/index.js, sites/svelte.dev/src/routes/docs/[slug]/+page.server.js
=> chore(site): fix build

pnpm-lock.yaml, sites/svelte.dev/package.json, sites/svelte.dev/src/routes/+page.svelte, sites/svelte.dev/src/routes/_components/Hero.svelte
- No scale on hero button
- Copyright footer is in one line on mobile
- Backdrop blur is more pronounced
=> fix(site): Style fixes

documentation/blog/2023-02-21-streaming-snapshots-sveltekit.md, documentation/docs/03-runtime/01-svelte.md, documentation/docs/03-runtime/07-svelte-action.md, documentation/docs/05-misc/04-v4-migration-guide.md
- link to createEventDispatcher typings
- svelte action type error fix
- migration guide tweak
- [add back blog post that has gone missing](https://github.com/sveltejs/svelte/pull/8798/commits/d88c64843eaa6334ec0126e5fd5cb6db0b4d141b)
=> docs: tweaks

sites/svelte.dev/src/config.js, sites/svelte.dev/src/routes/tutorial/[slug]/+page.svelte
=> fix: Use version 4 for examples and tutorial

packages/svelte/CHANGELOG.md
Fix misformatted links in 4.0.0 changelog
=> docs: fix misformatted links in 4.0.0 changelog

sites/svelte.dev/src/routes/tutorial/[slug]/+page.svelte
=> docs: fix tutorial edit link

documentation/docs/02-template-syntax/05-element-directives.md
=> docs: fix style directive with important modifier typo

documentation/examples/15-composition/03-slot-props/App.svelte
=> Fix: #8828

documentation/docs/02-template-syntax/07-special-elements.md
I figured out there is duplicate note in 02-template-syntax/07-special-elements.md so I removed it.
=> docs: Remove duplicate note

documentation/tutorial/14-composition/05-slot-props/app-a/App.svelte, documentation/tutorial/14-composition/05-slot-props/app-b/App.svelte
=> docs: Make white text on white background visible.

sites/svelte.dev/src/routes/docs/[slug]/+page.svelte
=> chore: fix docs "edit this page" link

documentation/blog/2023-07-01-whats-new-in-svelte-july-2023.md
Moved from https://github.com/sveltejs/sites/pull/499
=> docs: "What's new in Svelte" July newsletter

.changeset/gold-tips-roll.md, packages/svelte/src/runtime/internal/Component.js, packages/svelte/test/runtime-browser/custom-elements-samples/reflect-attributes/main.svelte, packages/svelte/test/runtime-browser/custom-elements-samples/reflect-attributes/test.js
=> fix: reflect all custom element prop updates back to attribute

sites/svelte.dev/static/robots.txt
I just copied the one from kit.svelte.dev. This gets our lighthouse SEO score up from 92 to 100
=> site: add a robots.txt

documentation/docs/05-misc/04-v4-migration-guide.md
=> docs: preprocessor migration details

documentation/examples/21-miscellaneous/01-hacker-news/App.svelte, documentation/examples/21-miscellaneous/01-hacker-news/Summary.svelte
before:
after:
relates to https://github.com/sveltejs/sites/issues/493
~~- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint`~~
=> docs: hackernews example link colors contrast in dark mode

sites/svelte.dev/static/robots.txt
closes https://github.com/sveltejs/svelte/issues/8919
=> site: block tutorial from search engines

sites/svelte.dev/scripts/get_contributors.js
=> chore: fix contributors image file name

documentation/docs/05-misc/03-typescript.md
Current link was broken. Would it be preferred to use a hashed permalink?
=> docs: update Typescript elements link

documentation/examples/12-svg/05-svg-transitions/App.svelte, sites/svelte.dev/src/lib/components/ReplWidget.svelte
=> docs: update svg transition example for v4

sites/svelte.dev/package.json, sites/svelte.dev/src/lib/db/session.js, sites/svelte.dev/src/routes/_components/Hero.svelte, sites/svelte.dev/src/routes/_components/Supporters/index.svelte, sites/svelte.dev/src/routes/_components/WhosUsingSvelte/index.svelte, sites/svelte.dev/svelte.config.js
This fixes a performance warning we're getting from lighthouse and makes sure prettier is being run
=> site: specify width/height and fix prettier

pnpm-lock.yaml, sites/svelte.dev/package.json
=> chore: REPL 0.5.0

documentation/examples/06-lifecycle/02-update/App.svelte
Dir path : [02-update](https://github.com/sveltejs/svelte/blob/master/documentation/examples/06-lifecycle/02-update/App.svelte)
Before:
After:
=> fix: css in examples directory.

sites/svelte.dev/scripts/get_contributors.js, sites/svelte.dev/scripts/get_donors.js, sites/svelte.dev/src/routes/_components/Supporters/index.svelte
=> fix(site): Optimise contributors donors images

.changeset/heavy-wasps-give.md, packages/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.js, packages/svelte/test/runtime/samples/dynamic-component-spread-props/Comp1.svelte, packages/svelte/test/runtime/samples/dynamic-component-spread-props/Comp2.svelte, packages/svelte/test/runtime/samples/dynamic-component-spread-props/_config.js, packages/svelte/test/runtime/samples/dynamic-component-spread-props/main.svelte
fix #9003, amend https://github.com/sveltejs/svelte/pull/8946#issuecomment-1643348835
=> fix: `svelte:component` spread props change not picked up

packages/svelte/src/compiler/compile/nodes/Element.js
=> chore: remove duplicate condition in `if` statement

documentation/blog/2023-08-01-whats-new-in-svelte-august-2023.md
=> docs: "What's new in Svelte" August newsletter

packages/svelte/src/compiler/utils/fuzzymatch.js
=> chore: refactor return statement in `_distance` function

pnpm-lock.yaml, sites/svelte.dev/package.json, sites/svelte.dev/src/routes/+page.svelte
=> chore: Sitekit footer

documentation/blog/2023-08-01-whats-new-in-svelte-august-2023.md
Fixes a small typo: Svelde -> [sveld](https://github.com/carbon-design-system/sveld)
=> docs: fix typo in August newsletter

documentation/docs/05-misc/03-typescript.md
=> docs: fix typo

documentation/docs/05-misc/03-typescript.md
=> docs: note ambient module info

packages/playground/start.js
=> chore: render head output in playground

documentation/examples/11-easing/00-easing/App.svelte, documentation/examples/11-easing/00-easing/Controls.svelte
closes https://github.com/sveltejs/sites/issues/487
=> docs: fix easings example glitch

playgrounds/basic/compile.js
=> chore: fix another playground path

documentation/docs/01-getting-started/01-introduction.md
- [-] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [-] Ideally, include a test that fails without this PR but passes with it.
- [X Run the tests with `pnpm test` and lint the project with `pnpm lint`
As suggested in the ambassador channel, the docs to generate a Svelte project with Vite should be updated to `npm create vite@latest` to avoid using a locally cached version of `create-vite` that is outdated.
=> chore: updated vite template to latest

documentation/blog/2023-09-01-whats-new-in-svelte-september-2023.md
=> docs: "What's new in Svelte" September newsletter

sites/svelte.dev/src/routes/+layout.svelte
=> fix(site): Scroll restoration

.changeset/shiny-mugs-tie.md, packages/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.js
=> fix: false reactive component warning

documentation/blog/2023-10-01-whats-new-in-svelte-october-2023.md
=> docs: "What's new in Svelte" October newsletter

documentation/blog/2023-10-01-hacktoberfest.md
Add the hacktoberfest announcement blog post
=> Add Hacktoberfest Blog

CONTRIBUTING.md
The PR simply updates the location of the `LICENSE.md` file which was changed in PR #6239.
=> fix: update link to `LICENSE.md`

pnpm-lock.yaml
=> fix: repair pnpm lock to deduplicate packages and make repl working again

sites/svelte.dev/src/routes/+layout.svelte, sites/svelte.dev/src/routes/search/+page.svelte
Hi, a minor accessibility improvement has been made by adding `type="search"` to the input tag.
=> site: add `type="search"` to search input

pnpm-lock.yaml, sites/svelte.dev/package.json, sites/svelte.dev/src/routes/+layout.svelte
will fix 404s sometimes being returned as 500s as discussed in https://github.com/sveltejs/svelte/pull/9116#issuecomment-1771281004
=> site: fix 404 page by upgrading SvelteKit and avoiding null reference

documentation/blog/2023-11-01-whats-new-in-svelte-november-2023.md
This fixes a typo in the [What's new in Svelte: November 2023](https://svelte.dev/blog/whats-new-in-svelte-november-2023) blog post.
=> docs: fix typo in blog

.changeset/config.json, .github/workflows/ci.yml, .github/workflows/release.yml, CONTRIBUTING.md
(main for a few in contributing; doesn't exist yet but will, soon)
=> chore: rewire some master occurences

sites/svelte-5-preview/src/lib/Output/CompilerOptions.svelte, sites/svelte-5-preview/src/lib/Repl.svelte, sites/svelte-5-preview/src/lib/workers/bundler/index.js, sites/svelte-5-preview/src/lib/workers/compiler/index.js, sites/svelte-5-preview/src/lib/workers/jsconfig.json
=> enable dev mode for preview repl

packages/svelte/src/transition/index.js, packages/svelte/tsconfig.json, sites/svelte-5-preview/src/routes/docs/content/01-api/03-functions.md
=> fix tsconfig.json

.changeset/thirty-flowers-sit.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/validation.js
stumbled upon this while doing something else
=> fix: support class exports

.changeset/eighty-bikes-camp.md, packages/svelte/src/compiler/phases/2-analyze/validation.js
fix: https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE2WOywqDMBBFf2VIF7ZQdK-2ULrpPzRdSIw0oknIjH0g-fcapSrtbu7lcub0rFKNRJZee6aLVrKUnaxle0ZvGwI-ZENyyGg6J0KTo3DK0pFrTqq1xhH0cDadptI8NXionGkhihPx7eIJEtcYZVznyQLQFzWgW1OqSsmSpeQ66fezyS9h0apxrSRfo4ZoCsSVSh8UN0jSZuESRuPwQJBx21DupgEnuiuMxx0cYJ574NrDv97NfwAO2LqkNAEAAA==
I wanted to add a test with `svelte.js` but could not figure out how. Perhaps I need to update test runner, is that correct?
=> fix: Added missing context of `svelte.js` for validation

packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/src/compiler/preprocess/index.js, packages/svelte/tests/parser-legacy/samples/script-context-module-unquoted/input.svelte, packages/svelte/tests/parser-legacy/samples/script-context-module-unquoted/output.json
=> fix: adjust static attribute regex

packages/svelte/src/compiler/phases/1-parse/read/context.js, packages/svelte/tests/parser-modern/samples/snippets/output.json
not adding a changeset because this falls under #9482 which hasn't been released yet
=> set expression end to typeAnnotation end where appropriate

packages/svelte/src/compiler/phases/1-parse/read/context.js, packages/svelte/tests/runtime-runes/samples/typescript-each-indexed/_config.js, packages/svelte/tests/runtime-runes/samples/typescript-each-indexed/main.svelte
skipping changeset for same reason as #9566
=> Typescript each indexed

.changeset/wicked-clouds-exercise.md, packages/svelte/src/compiler/phases/1-parse/index.js
would error on non-quoted attributes with more than one character
=> fix: adjust regex

packages/svelte/src/compiler/phases/2-analyze/validation.js, packages/svelte/tests/compiler-errors/samples/class-state-field-static/_config.js, packages/svelte/tests/compiler-errors/samples/class-state-field-static/main.svelte
=> fix: disallow static state fields

.changeset/few-mugs-fail.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/internal/client/render.js, packages/svelte/tests/snapshot/samples/function-prop-no-getter/_expected/client/index.svelte.js
#9589. We can definitely take this idea further, but this is a base to iterate from.
=> chore: reuse common templates

.changeset/dirty-tips-add.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/internal/client/render.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-legacy/samples/binding-this-multiple/_config.js, packages/svelte/tests/runtime-legacy/samples/binding-this-multiple/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9616.
=> fix: correctly assign bind:this with multiples

.changeset/serious-zebras-scream.md, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/runtime-runes/samples/snippet-scope/Component.svelte, packages/svelte/tests/runtime-runes/samples/snippet-scope/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-scope/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9600.
=> fix: apply correct snippet scope

.changeset/seven-deers-jam.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/src/compiler/phases/constants.js, packages/svelte/src/constants.js, packages/svelte/src/internal/client/render.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-runes/samples/attribute-spread-casing/_config.js, packages/svelte/tests/runtime-runes/samples/attribute-spread-casing/main.svelte, packages/svelte/tests/snapshot/samples/dynamic-attributes-casing/_expected/client/main.svelte.js, packages/svelte/tests/snapshot/samples/dynamic-attributes-casing/_expected/server/main.svelte.js, packages/svelte/tests/snapshot/samples/dynamic-attributes-casing/main.svelte
- don't lowercase attributes on svg and custom element elements, fixes #9605
- better lowercasing + property alias checking for spreads, fixes #9305
=> fix: better attribute casing logic

.changeset/lovely-items-turn.md, packages/svelte/src/compiler/phases/2-analyze/validation.js, packages/svelte/tests/validator/samples/no-runes-mode/_config.js, packages/svelte/tests/validator/samples/no-runes-mode/input.svelte
=> fix: dont error on stores looking like runes when runes explicitly turned off

.changeset/thirty-wombats-relax.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/runtime-legacy/samples/keyed-each-index-same-2/_config.js, packages/svelte/tests/runtime-legacy/samples/keyed-each-index-same-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9636 and https://github.com/sveltejs/svelte/issues/9629.
=> fix: improve each block index handling

.changeset/stale-comics-look.md, packages/svelte/package.json, pnpm-lock.yaml, sites/svelte-5-preview/package.json
Fixes #9630 — [demo](https://svelte-5-preview-git-gh-9630-svelte.vercel.app/#H4sIAAAAAAAAE42PTWrDMBCFrzKZTdpibBqychxD6KY36KLKwtjjWCBrhDQuKSF3j-SAA-mmq2F-3nvfXLDXhgKW3xe0zUhY4sE5zFB-XWrCDxmh2AeefJsmVWi9dlIrq0SPjr3AB8dqyUoGb9AE6BppoPc8wjovlmV-91rvojJqW7aBDeWGTy9JkMug7elV2ap4JNhqkUNRR4yRO91r6rAUP9E1W6iXu3-wQ8wWOsteJb_JkML5HTrP7yQygRkH9rDd7J6Zhvf6k4xh-GJvulVVxMFftuP1Bt83bqldAQAA)
=> chore: bump esrap

.github/workflows/ci.yml
=> chore: run CI tests on Node 21

packages/svelte/src/internal/client/render.js, sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
- mention createRoot first, explain difference to mount
- mentiond bind:this change
- sub headings
- adjust createRoot type that missed the events property
=> docs: enhance breaking change section

.changeset/odd-shoes-cheat.md, packages/svelte/src/compiler/phases/1-parse/state/tag.js
=> fix: tweak const tag parsing

documentation/blog/2023-12-01-whats-new-in-svelte-december-2023.md
Reopening https://github.com/sveltejs/svelte/pull/9693 with the right base branch
=> docs: "What's new in Svelte" December newsletter

.changeset/cool-ants-leave.md, packages/svelte/src/internal/client/proxy/proxy.js, packages/svelte/tests/runtime-runes/samples/proxy-array-length/_config.js, packages/svelte/tests/runtime-runes/samples/proxy-array-length/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9781
=> fix: ensure proxied array length is updated

.changeset/unlucky-boxes-obey.md, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/runtime-runes/samples/slot-static/Child.svelte, packages/svelte/tests/runtime-runes/samples/slot-static/_config.js, packages/svelte/tests/runtime-runes/samples/slot-static/main.svelte
=> fix: correctly apply scope on component children

.changeset/old-mails-sneeze.md, packages/svelte/src/internal/client/render.js
Fixes https://github.com/sveltejs/svelte/issues/9843. Surprised we missed this!
=> fix: ensure action function returns object

sites/svelte-5-preview/src/routes/docs/content/03-appendix/01-faq.md
am I right to send this to `main`?
=> docs: update FAQ regarding Svelte 5 release date

.changeset/purple-dragons-peel.md, packages/svelte/src/internal/client/proxy/proxy.js
Fixes https://github.com/sveltejs/svelte/issues/9870.
=> fix: improve unstate type definition

.changeset/dull-mangos-wave.md, packages/svelte/src/compiler/phases/3-transform/utils.js, packages/svelte/tests/runtime-runes/samples/snippet-whitespace/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-whitespace/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9804.
=> fix: improve whitespace handling

.changeset/four-flies-hammer.md, packages/svelte/src/internal/client/each.js, packages/svelte/tests/runtime-runes/samples/each-fallback/_config.js, packages/svelte/tests/runtime-runes/samples/each-fallback/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9908.
=> fix: improve each block fallback handling

.changeset/wild-foxes-wonder.md, packages/svelte/src/internal/client/each.js, packages/svelte/tests/runtime-legacy/samples/animation-flip-2/_config.js, packages/svelte/tests/runtime-legacy/samples/animation-flip-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9909
=> fix: cleanup each block animations on destroy

.changeset/real-guests-do.md, packages/svelte/src/compiler/phases/1-parse/utils/html.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/tests/runtime-legacy/samples/store-reference/_config.js, packages/svelte/tests/runtime-legacy/samples/store-reference/main.svelte
Likely, the last PR from me for the year. So putting up one to fix three issues in one go.
Fixes https://github.com/sveltejs/svelte/issues/9928, fixes https://github.com/sveltejs/svelte/issues/9927 and fixes https://github.com/sveltejs/svelte/issues/9926.
=> fix: improve event delegation handler hoisting

packages/svelte/CHANGELOG.md
Not sure if any other files have to be fixed or just this .md
=> docs: fix typo in release notes

sites/svelte.dev/src/routes/content.json/content.server.js
=> fix(site): Search

documentation/blog/2024-01-01-whats-new-in-svelte-january-2024.md
Let me know if I missed anything
=> docs: "What's new in Svelte" January newsletter

documentation/blog/2024-01-01-whats-new-in-svelte-january-2024.md
=> docs: spelling mistake in January newsletter

LICENSE.md
=> Update copyright year to 2024

.changeset/itchy-terms-guess.md, packages/svelte/src/internal/client/each.js
Fixes https://github.com/sveltejs/svelte/issues/10110.
=> fix: apply key animations on proxied arrays

.changeset/clever-chefs-relate.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/src/internal/client/transitions.js, packages/svelte/tests/runtime-runes/samples/if-transition-undefined/_config.js, packages/svelte/tests/runtime-runes/samples/if-transition-undefined/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/9934 and fixes https://github.com/sveltejs/svelte/issues/10115.
=> fix: allow transition undefined payload + microtask queue handling

sites/svelte-5-preview/src/lib/Output/Viewer.svelte
=> chore(repl): hide repl globals

.github/ISSUE_TEMPLATE/feature_request.yml
i don't think this is particularly useful
=> remove 'alternatives considered' from feature request template

.changeset/big-cars-serve.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/tests/runtime-legacy/samples/binding-store/_config.js, packages/svelte/tests/runtime-legacy/samples/binding-store/main.svelte
=> fix: transform textarea and contenteditable binding expressions

.changeset/fair-pianos-talk.md, packages/svelte/src/internal/client/render.js
Fixes https://github.com/sveltejs/svelte/issues/10215
=> fix: correctly apply event.currentTarget

.changeset/witty-steaks-dream.md, packages/svelte/src/internal/client/proxy/proxy.js, packages/svelte/tests/runtime-runes/samples/inspect-new-property/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-new-property/main.svelte
=> fix: ensure proxy is updated before notifying listeners

.changeset/kind-rings-flash.md, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/tests/runtime-runes/samples/class-state-deep-update/_config.js, packages/svelte/tests/runtime-runes/samples/class-state-deep-update/main.svelte
=> fix: handle deep assignments to `$state()` class properties correctly

packages/svelte/src/compiler/interfaces.d.ts, packages/svelte/types/index.d.ts
#10274, but for the `svelte-4` branch
=> update discloseVersion docs

.changeset/great-fans-unite.md, packages/svelte/src/internal/client/runtime.js
=> chore: cleanup derived destruction

packages/svelte/src/compiler/phases/1-parse/utils/fuzzymatch.js
=> chore: _distance return refactor

sites/svelte-5-preview/src/routes/docs/content/01-api/02-runes.md
https://github.com/sveltejs/svelte/pull/10002#issuecomment-1911276049
=> docs: clarify that `$state` works deeply

packages/svelte/tests/motion/test.ts, packages/svelte/tsconfig.json
these got lost in the migration
=> add missing motion tests

packages/svelte/src/internal/client/proxy.js
a few small tweaks off the back of #10384
=> small tidy up

.changeset/stupid-insects-help.md, documentation/blog/2023-09-20-runes.md, sites/svelte-5-preview/src/routes/docs/content/02-examples/06-more-examples.md, sites/svelte-5-preview/src/routes/docs/content/03-appendix/01-faq.md
=> docs: rename svelte 5 discord channel

packages/svelte/src/internal/client/custom-element.js
fix for https://github.com/sveltejs/svelte/issues/10454
=> fix: additional check for component

.changeset/spicy-jeans-deliver.md, packages/svelte/src/internal/client/runtime.js
Fixes https://github.com/sveltejs/svelte/issues/10461
=> fix: ensure inspect fires on prop changes

.changeset/gentle-dolls-juggle.md, packages/svelte/src/internal/client/transitions.js, packages/svelte/tests/runtime-runes/samples/dynamic-if-component-transition/Component.svelte, packages/svelte/tests/runtime-runes/samples/dynamic-if-component-transition/_config.js, packages/svelte/tests/runtime-runes/samples/dynamic-if-component-transition/main.svelte
Follow up to https://github.com/sveltejs/svelte/pull/10469.
=> fix: improve global transition outro handling

sites/svelte-5-preview/src/lib/Output/Viewer.svelte, sites/svelte-5-preview/src/lib/workers/bundler/index.js
=> chore: fix preview site

packages/svelte/tests/runtime-runes/samples/store-subscribe-effect-init/main.svelte
see https://github.com/sveltejs/svelte/pull/10535#discussion_r1494529156 — in general I think it's worth writing tests as hygienically and idiomatically as possible, since test code tends to get copied around a bit and it's important for it to have as little cognitive overhead as possible (I often find myself reverse engineering the intent of a particular test)
=> simplify test

.changeset/twelve-worms-jog.md, packages/svelte/src/internal/client/runtime.js
Fix https://github.com/sveltejs/svelte/issues/10567
=> fix: correct context applied to batch_inspect

.changeset/khaki-cooks-develop.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/inspect-derived-2/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-derived-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/10583.
=> fix: improve $inspect handling of derived objects

.changeset/spotty-turkeys-sparkle.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/validation.js, packages/svelte/tests/validator/samples/contenteditable-dynamic/errors.json, packages/svelte/tests/validator/samples/contenteditable-dynamic/input.svelte
=> fix: allow boolean `contenteditable` attribute

.changeset/yellow-taxis-double.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-runes/samples/event-attribute-import/_config.js, packages/svelte/tests/runtime-runes/samples/event-attribute-import/event.js, packages/svelte/tests/runtime-runes/samples/event-attribute-import/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/10585
=> fix: improve import event handler support

.changeset/rotten-experts-relax.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-legacy/samples/head-script/_config.js, packages/svelte/tests/runtime-legacy/samples/head-script/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/10586
=> fix: permit whitespace within template scripts

.changeset/rude-ghosts-tickle.md, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
Further fixes to https://github.com/sveltejs/svelte/pull/10605
=> fix: correctly handle proxied signal writes before reads

packages/svelte/tests/runtime-runes/samples/date/main.svelte
this is just a slight change for the test because it was failing for me locally because of the timezone difference.
=> chore: account for timezone difference in #10622

.changeset/unlucky-steaks-warn.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-legacy/samples/action-component/_config.js, packages/svelte/tests/runtime-legacy/samples/action-component/main.svelte, packages/svelte/tests/runtime-legacy/samples/action-component/sub.svelte
=> fix: deduplicate generated props and action arg names

.changeset/popular-ligers-perform.md, packages/svelte/src/compiler/phases/1-parse/read/context.js, packages/svelte/src/compiler/phases/1-parse/state/tag.js, packages/svelte/tests/runtime-runes/samples/snippet-optional-arguments/main.svelte, packages/svelte/tests/runtime-runes/samples/snippet-typescript/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-typescript/main.svelte
=> fix: handle TypeScript's optional parameter syntax in snippets

packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/internal/client/render.js
going to try and whittle down #10594 to something more manageable, because it's killing me. starting small, with a couple of drive-by aesthetic fixes
=> minor aesthetic tweaks

.changeset/seven-masks-end.md, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/tests/runtime-runes/samples/each-updates-4/_config.js, packages/svelte/tests/runtime-runes/samples/each-updates-4/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/10685
=> fix: adjust keyed each block equality handling

.changeset/spotty-houses-search.md, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/tests/runtime-runes/samples/each-updates-5/_config.js, packages/svelte/tests/runtime-runes/samples/each-updates-5/main.svelte
Follow up to https://github.com/sveltejs/svelte/pull/10699. Forgot to handle indexed each blocks!
=> fix: improve indexed each equality

sites/svelte-5-preview/src/lib/Output/Viewer.svelte, sites/svelte-5-preview/src/lib/workers/bundler/index.js
I had to fix this once and for all.
=> fix: untrack console.log calls on REPL

packages/svelte/tests/runtime-runes/samples/date/_config.js, packages/svelte/tests/runtime-runes/samples/date/main.svelte
=> fix: use toDateString occur error when use pnpm run test in China

.changeset/rotten-rules-invite.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/global.js, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/src/compiler/phases/3-transform/server/types.d.ts, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-runes/samples/class-state-derived-3/_config.js, packages/svelte/tests/runtime-runes/samples/class-state-derived-3/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/10751
=> fix: improve derived output for ssr

packages/svelte/src/internal/client/reactivity/store.js
=> chore: remove unused function

.changeset/smooth-rings-rush.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/if-dependency-order-2/Seo.svelte, packages/svelte/tests/runtime-runes/samples/if-dependency-order-2/_config.js, packages/svelte/tests/runtime-runes/samples/if-dependency-order-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/10741.
=> fix: improve internal render effect sequencing

packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/src/internal/client/render.js
=> move props code

.changeset/orange-yaks-protect.md, packages/svelte/src/reactivity/set.js, packages/svelte/src/reactivity/set.test.ts
https://github.com/sveltejs/svelte/pull/10791#issuecomment-1994644505
=> fix: make `set.has(...)` granular for existing properties

.changeset/serious-needles-joke.md, packages/svelte/scripts/generate-types.js, packages/svelte/src/reactivity/date.js, packages/svelte/types/index.d.ts
=> fix: add types for svelte/reactivity

.changeset/ten-eels-move.md, packages/svelte/src/internal/client/dom/elements/events.js, packages/svelte/tests/runtime-runes/samples/event-attribute-delegation-7/_config.js, packages/svelte/tests/runtime-runes/samples/event-attribute-delegation-7/log.js, packages/svelte/tests/runtime-runes/samples/event-attribute-delegation-7/main.svelte
=> fix: ensure capture events don't call delegated events

.changeset/dull-pots-add.md, packages/svelte/src/legacy/legacy-client.js
=> fix: don't override instance methods during legacy class creation

.changeset/olive-mice-fix.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-3/_config.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-3/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/10836
=> fix: improve handling of unowned derived signals

.changeset/mighty-cooks-scream.md, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/runtime-legacy/samples/component-slot-let-scope-4/Nested.svelte, packages/svelte/tests/runtime-legacy/samples/component-slot-let-scope-4/Nested2.svelte, packages/svelte/tests/runtime-legacy/samples/component-slot-let-scope-4/_config.js, packages/svelte/tests/runtime-legacy/samples/component-slot-let-scope-4/main.svelte
=> fix: adjust scope parent for named slots

.changeset/smart-turkeys-tell.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/internal/client/dom/elements/bindings/select.js, packages/svelte/tests/runtime-legacy/samples/binding-select-late-2/_config.js, packages/svelte/tests/runtime-legacy/samples/binding-select-late-3/_config.js, packages/svelte/tests/runtime-legacy/samples/binding-select-unmatched-3/_config.js, packages/svelte/tests/runtime-legacy/samples/select-lazy-options/_config.js, packages/svelte/tests/runtime-legacy/samples/select-lazy-options/main.svelte, packages/svelte/tests/runtime-legacy/samples/select-one-way-bind-object-multiple/_config.js, packages/svelte/tests/runtime-legacy/samples/select-one-way-bind-object-multiple/main.svelte
Follow up to feedback in https://github.com/sveltejs/svelte/pull/10846
=> fix: more robust select element logic

packages/svelte/scripts/check-treeshakeability.js
not sure when this broke, but this fixes it
=> chore: fix treeshaking check

.changeset/lovely-houses-own.md, .changeset/stale-fans-rest.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/hydration/samples/element-attribute-removed/_expected.html, packages/svelte/tests/hydration/samples/element-attribute-removed/main.svelte, packages/svelte/tests/snapshot/samples/dynamic-attributes-casing/_expected/client/main.svelte.js
=> fix: remove if blocks around attribute updates

.changeset/itchy-bulldogs-tan.md, packages/svelte/src/internal/client/dom/elements/actions.js, packages/svelte/tests/runtime-runes/samples/action-state-arg-deep/Task.svelte, packages/svelte/tests/runtime-runes/samples/action-state-arg-deep/_config.js, packages/svelte/tests/runtime-runes/samples/action-state-arg-deep/log.js, packages/svelte/tests/runtime-runes/samples/action-state-arg-deep/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/10961
=> fix: improve action support for nested $effect

packages/svelte/src/internal/client/dom/legacy/lifecycle.js, packages/svelte/src/internal/common.js, packages/svelte/src/store/index.js
=> move some code

sites/svelte-5-preview/src/routes/docs/content/01-api/02-runes.md
Fixes the hash link generated for $bindable rune.
=> docs: fix $bindable hash link

.changeset/curvy-flies-exercise.md, packages/svelte/src/internal/client/dom/elements/actions.js, packages/svelte/tests/runtime-runes/samples/action-context/_config.js, packages/svelte/tests/runtime-runes/samples/action-context/log.js, packages/svelte/tests/runtime-runes/samples/action-context/main.svelte
=> fix: ensure correct context for action update/destroy functions

sites/svelte-5-preview/src/lib/CodeMirror.svelte
Fixes https://github.com/sveltejs/svelte/issues/11017
=> fix: improve $effect.active REPL autocomplete

packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/reactivity/effects.js
=> Revert "chore: apply each block controlled teardown optimization"

.changeset/three-rice-tie.md, packages/svelte/package.json, packages/svelte/src/compiler/types/css.d.ts, packages/svelte/src/compiler/types/index.d.ts, packages/svelte/types/index.d.ts, pnpm-lock.yaml
Side-note: we should probably have some typechecking on the generated `index.d.ts`, to prevent regressions on this sort of thing.
Fixes #10839
=> fix: bundle CSS types

.changeset/young-masks-refuse.md, packages/svelte/src/reactivity/set.js
Fixes https://github.com/sveltejs/svelte/issues/11118
=> fix: addresses reactive Set bug in certain engines

.changeset/light-badgers-glow.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js
fixes https://github.com/sveltejs/svelte/issues/11124
=> fix: use correct meta property for hmr key

.changeset/breezy-rules-beg.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js
Hopefully fixes https://github.com/sveltejs/svelte/issues/11124.
=> fix: further improvements to hmr component key generation

.changeset/fresh-dots-destroy.md, packages/svelte/src/compiler/phases/2-analyze/validation.js, packages/svelte/tests/compiler-errors/samples/attribute-sequence-expression-2/_config.js, packages/svelte/tests/compiler-errors/samples/attribute-sequence-expression-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/11071
=> fix: add validation around disallowed sequence expressions to elements

packages/svelte/src/internal/client/dev/hmr.js, sites/svelte-5-preview/src/lib/Output/Viewer.svelte
Fixes https://github.com/sveltejs/svelte/issues/11146
=> fix: improve REPL console method wrapping

sites/svelte-5-preview/src/routes/docs/content/01-api/02-runes.md
Added the missing variables in the `$effect` example code.
=> docs: update runes $effect example

.changeset/few-teachers-know.md
=> add missing changeset for #11155

.changeset/shy-fishes-drive.md, packages/svelte/src/reactivity/map.js, packages/svelte/src/reactivity/set.js, packages/svelte/src/reactivity/utils.js, packages/svelte/tests/runtime-runes/samples/reactive-to-string/_config.js, packages/svelte/tests/runtime-runes/samples/reactive-to-string/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/11152
=> fix: fix string name of reactive map and set iterator

.changeset/calm-pandas-vanish.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/internal/client/dev/ownership.js, playgrounds/demo/package.json, pnpm-lock.yaml, sites/svelte-5-preview/package.json, sites/svelte.dev/package.json
=> fix: make ownership validation work with HMR

packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/shared/utils.js
leftover from earlier iterations of #11183
=> chore: remove unused code

packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/validator/samples/js-scope-catch-clause/input.svelte
=> fix: catch clause scope

.changeset/tender-rocks-walk.md, packages/svelte/src/internal/client/dev/hmr.js
fixes #11228
No test because not sure how
=> fix: preserve getters/setters in HMR mode

packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/dom/template.js
small tweak that would otherwise have been a noisy drive-by fix on a different PR
=> chore: tweak `push_template_node` types

packages/svelte/src/compiler/phases/2-analyze/index.js
fixes #11306. there might be a more elegant solution but given the glaringness of the bug i'm inclined to quickly get this in
=> chore: fix playground

packages/svelte/messages/client-errors/effects.md, packages/svelte/messages/client-errors/lifecycle.md, packages/svelte/messages/client-warnings/warnings.md, packages/svelte/messages/compile-errors/attributes.md, packages/svelte/messages/compile-errors/bindings.md, packages/svelte/messages/compile-errors/compiler_options.md, packages/svelte/messages/compile-errors/components.md, packages/svelte/messages/compile-errors/const_tag.md, packages/svelte/messages/compile-errors/css.md, packages/svelte/messages/compile-errors/elements.md, packages/svelte/messages/compile-errors/legacy_reactivity.md, packages/svelte/messages/compile-errors/parse.md, packages/svelte/messages/compile-errors/runes.md, packages/svelte/messages/compile-errors/slots.md, packages/svelte/messages/compile-errors/special_elements.md, packages/svelte/messages/compile-errors/variables.md, packages/svelte/messages/compile-warnings/a11y.md, packages/svelte/messages/compile-warnings/attributes.md, packages/svelte/messages/compile-warnings/block.md, packages/svelte/messages/compile-warnings/components.md, packages/svelte/messages/compile-warnings/css.md, packages/svelte/messages/compile-warnings/legacy.md, packages/svelte/messages/compile-warnings/misc.md, packages/svelte/messages/compile-warnings/options.md, packages/svelte/messages/compile-warnings/performance.md, packages/svelte/messages/compile-warnings/runes.md, packages/svelte/messages/compile-warnings/state.md, packages/svelte/messages/shared-warnings/warnings.md, packages/svelte/scripts/process-messages/index.js
see #11305 — this is a precursor to implementing overloads and detailed descriptions for docs pages
=> chore: put messages in blockquotes

.changeset/fast-penguins-matter.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-legacy/samples/event-handler-modifier-bubble/_config.js, packages/svelte/tests/runtime-legacy/samples/event-handler-modifier-bubble/button.svelte, packages/svelte/tests/runtime-legacy/samples/event-handler-modifier-bubble/main.svelte
=> fix: apply modifiers to bubbled events

.changeset/swift-knives-tie.md, packages/svelte/package.json, pnpm-lock.yaml, sites/svelte-5-preview/package.json
fixes code generation for `(x) => ({ x } || x)`
=> fix: bump esrap

documentation/blog/2024-04-30-svelte-5-release-candidate.md
[preview](https://svelte-dev-git-rc-announcement-svelte.vercel.app/blog/svelte-5-release-candidate)
=> release candidate blog post

.changeset/cool-actors-tan.md, packages/svelte/src/compiler/phases/1-parse/read/options.js, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/src/compiler/phases/3-transform/utils.js, packages/svelte/src/compiler/phases/constants.js, packages/svelte/src/compiler/types/template.d.ts, packages/svelte/src/constants.js, packages/svelte/src/internal/client/dom/blocks/html.js, packages/svelte/src/internal/client/dom/elements/class.js, packages/svelte/src/internal/client/dom/template.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-legacy/samples/namespace-html/_config.js, packages/svelte/tests/runtime-legacy/samples/namespace-html/main.svelte, packages/svelte/tests/runtime-runes/samples/mathml-namespace-infer/Wrapper.svelte, packages/svelte/tests/runtime-runes/samples/mathml-namespace-infer/_config.js, packages/svelte/tests/runtime-runes/samples/mathml-namespace-infer/main.svelte, packages/svelte/tests/validator/samples/namespace-invalid/errors.json, packages/svelte/tests/validator/samples/namespace-non-literal/errors.json, packages/svelte/types/index.d.ts, sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
This PR adds support for MathML within Svelte. Fixing https://github.com/sveltejs/svelte/issues/6582
=> feat: MathML support

documentation/blog/2024-05-01-whats-new-in-svelte-may-2024.md
Svelte 5 Release Candidate and all the other highlights from Svelte Summit Spring
=> docs: "What's new in Svelte" May newsletter

.changeset/violet-mugs-behave.md, packages/svelte/src/internal/client/dev/inspect.js, packages/svelte/tests/runtime-runes/samples/inspect-deep/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-deep/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/11409
=> fix: ensure $inspect untracks inspected object

FUNDING.json
Updating wallet address to Open Source Collective-owned wallet in order to claim project.
=> Update Drips claim wallet address

packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/dom/elements/misc.js
Looks like we can use it in more areas.
=> chore: use clear_text_content in more areas

packages/svelte/src/internal/client/runtime.js
=> chore: deduplicate code

.changeset/strong-apricots-destroy.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/tests/runtime-runes/samples/props-alias-weird/Child.svelte, packages/svelte/tests/runtime-runes/samples/props-alias-weird/_config.js, packages/svelte/tests/runtime-runes/samples/props-alias-weird/main.svelte
=> fix: handle falsy prop aliases correctly

sites/svelte-5-preview/src/lib/Message.svelte
=> fix: improve REPL error button styling

.changeset/lazy-bats-turn.md, packages/svelte/src/internal/client/dom/elements/actions.js
=> Revert "fix: ensure Svelte action destroy effects are untracked"

.changeset/good-roses-argue.md, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-legacy/samples/inline-style-directive-falsy-value/_config.js, packages/svelte/tests/runtime-legacy/samples/inline-style-directive-falsy-value/main.svelte
=> fix: correctly handle falsy values of style directives in SSR mode

.changeset/long-owls-eat.md, packages/svelte/src/runtime/internal/ssr.js, packages/svelte/test/runtime/samples/inline-style-directive-falsy-value/_config.js, packages/svelte/test/runtime/samples/inline-style-directive-falsy-value/main.svelte
=> fix: correctly handle falsy values of style directives in SSR mode (Svelte 4)

playgrounds/sandbox/run.js
=> chore: update run.js to include dev mode on compileModule

sites/svelte-5-preview/src/lib/Output/srcdoc/index.html
Fixes https://github.com/sveltejs/svelte/issues/11563.
=> fix: improve REPL stringify logic

packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/tests/validator/samples/unknown-code/warnings.json
They were the wrong way around
fixes #11612
=> fix: adjust unknown code warning offset

packages/svelte/src/internal/client/dev/equality.js
Hopefully this fixes https://github.com/sveltejs/svelte/issues/11625
=> fix: cleanup array prototype monkeypatching

sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
Related to #11400
closes #11590
=> docs: document more breaking changes

packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/src/internal/client/dom/elements/events.js
=> Revert "chore: ensure we use event system code paths throughout"

.changeset/fresh-beds-wash.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-legacy/samples/component-prop-object/Child.svelte, packages/svelte/tests/runtime-legacy/samples/component-prop-object/_config.js, packages/svelte/tests/runtime-legacy/samples/component-prop-object/main.svelte
fixes #11648
Also deduplicates the code a bit
=> fix: use coarse-grained updates for derived expressions in legacy mode

packages/svelte/tests/css/samples/global-with-data-attribute/expected.css, packages/svelte/tests/css/samples/global-with-data-attribute/input.svelte
=> chore: add css regression test

.changeset/thin-years-rhyme.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/tests/migrate/samples/svelte-element/input.svelte, packages/svelte/tests/migrate/samples/svelte-element/output.svelte, packages/svelte/tests/migrate/test.ts
=> feat: migrate `<svelte:element this="div">`

packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/dom/blocks/svelte-head.js, packages/svelte/src/internal/client/dom/hydration.js, packages/svelte/src/internal/client/dom/operations.js, packages/svelte/src/internal/client/render.js
Reverts sveltejs/svelte#11694. I found this resulted in slower hydration
=> Revert "chore: consistent nextSibling usage"

packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/tests/compiler-errors/samples/attribute-unique-binding/_config.js, packages/svelte/tests/compiler-errors/samples/attribute-unique-shorthand/_config.js, packages/svelte/tests/compiler-errors/samples/attribute-unique/_config.js, pnpm-lock.yaml, sites/svelte-5-preview/package.json, sites/svelte-5-preview/src/lib/CodeMirror.svelte, sites/svelte-5-preview/src/lib/Input/ModuleEditor.svelte, sites/svelte-5-preview/src/lib/theme.js
The first of a bunch of PRs to overhaul the playground a bit, as parts of it are a bit ropey.
Before:
After:
Light mode:
=> better tooltips in playground

.changeset/tame-dots-battle.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-8/_config.js, packages/svelte/tests/runtime-runes/samples/derived-unowned-8/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/11710
=> fix: improve handling of unowned derived signal

packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/internal/client/dom/template.js, packages/svelte/src/internal/client/index.js
minor tweak to reduce the size of #11690
=> chore: DRY out namespace template code

packages/svelte/tests/html_equal.js, packages/svelte/tests/runtime-legacy/samples/noscript-removal/_config.js
extracting another part of #11690 into a separate PR, to make it easier to understand what's going on there
=> chore: update noscript test

packages/svelte/src/internal/client/dom/blocks/css-props.js, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/src/internal/client/dom/blocks/svelte-element.js
more drive-by changes from #11690 that can be extracted out. will self-merge once green to unblock
=> chore: more non-essential changes from #11690

packages/svelte/src/internal/client/dev/elements.js
another #11690 follow-up — we can avoid creating a bunch of arrays here, and it will allow us to remove the `find_nodes_between` stuff from #11690
=> chore: simplify add_locations

packages/svelte/src/internal/client/dom/blocks/svelte-element.js
=> chore: remove some unnecessary code

packages/svelte/src/internal/client/dev/elements.js
=> chore: tweak add_locations

packages/svelte/src/internal/client/dom/elements/bindings/input.js, packages/svelte/src/internal/client/dom/elements/bindings/media.js, packages/svelte/src/internal/client/dom/elements/bindings/navigator.js, packages/svelte/src/internal/client/dom/elements/bindings/select.js, packages/svelte/src/internal/client/dom/elements/bindings/size.js, packages/svelte/src/internal/client/dom/elements/bindings/this.js, packages/svelte/src/internal/client/dom/elements/bindings/window.js, packages/svelte/src/internal/client/dom/elements/events.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-legacy/samples/binding-input-group-each-7/_config.js, packages/svelte/tests/runtime-legacy/samples/binding-input-number-2/_config.js
Takes some changes from https://github.com/sveltejs/svelte/pull/11810 that are only cleanup/renaming.
=> chore: break out cleanup event changes

packages/svelte/src/internal/client/dom/elements/events.js
I noticed that we spend a lot of time dealing with a recursive function when propagating events. Let's avoid that overhead and move back to a much faster while loop. We can also stack the errors and throw them at the end.
=> chore: improve event error handling

packages/svelte/src/internal/client/dom/blocks/each.js
We can make each blocks do slightly less work when nothing gets removed.
=> chore: tweak each block runtime logic

packages/svelte/src/internal/client/dom/blocks/each.js
More performance tweaks to each block.
=> chore: tweak pause_effects more

documentation/blog/2024-06-01-whats-new-in-svelte-june-2024.md
Lemme know if I missed anything
=> docs: "What's new in Svelte" June newsletter

.changeset/lovely-zebras-own.md, packages/svelte/src/reactivity/map.js, packages/svelte/src/reactivity/map.test.ts
Fixes https://github.com/sveltejs/svelte/issues/11871
=> fix: address map reactivity regression

.changeset/tidy-fans-relax.md, packages/svelte/src/internal/client/proxy.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/class-state-frozen/_config.js, packages/svelte/tests/runtime-runes/samples/class-state-frozen/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/11887
=> fix: ensure frozen objects in state are correctly skipped

sites/svelte-5-preview/src/routes/docs/content/03-appendix/01-faq.md
This pr updates the FAQs section of the Svelte 5 preview site to include information on how to correctly configure the svelte language server for formatting.
=> docs: Update svelte 5 preview faqs to include lsp formatting

.changeset/cyan-bears-refuse.md, packages/svelte/src/compiler/preprocess/index.js
=> chore: speed up regex

packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte
=> fix: handle TypeScript parameter properties

.changeset/thin-spoons-float.md, packages/svelte/src/reactivity/set.js, packages/svelte/tests/runtime-runes/samples/reactive-set/_config.js, packages/svelte/tests/runtime-runes/samples/reactive-set/main.svelte
=> Revert "fix: lazily create sources for Set"

.changeset/spotty-crabs-give.md, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/snapshot/samples/dynamic-attributes-casing/_expected/server/main.svelte.js, packages/svelte/tests/snapshot/samples/state-proxy-literal/_expected/server/index.svelte.js
=> feat: more efficient output for attributes in SSR

playgrounds/demo/src/entry-client.ts
=> chore: remove setTimeout

.changeset/dull-pens-pay.md, packages/svelte/src/index.d.ts, packages/svelte/types/index.d.ts
=> docs: remove `createRoot` references

packages/svelte/scripts/process-messages/index.js, packages/svelte/src/internal/client/errors.js, packages/svelte/src/internal/client/warnings.js, packages/svelte/src/internal/server/errors.js, packages/svelte/src/internal/shared/errors.js, packages/svelte/src/internal/shared/warnings.js
totally unnecessary change but it took 5 minutes and soothes my OCD
=> chore: tidier generated message code

.changeset/slow-ligers-enjoy.md, packages/svelte/src/ambient.d.ts, packages/svelte/types/index.d.ts
See https://github.com/sveltejs/language-tools/commit/026111228b5814a9109cc4d779d37fb02955fb8b for more info We can probably remove this after a few weeks
fixes #12066
=> fix: adjust module declaration to work around language tools bug

.changeset/hot-rivers-punch.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/utils/ast.js, packages/svelte/tests/runtime-runes/samples/event-on-3/_config.js, packages/svelte/tests/runtime-runes/samples/event-on-3/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12074
=> fix: improve compiler attribute validation logic

packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/runtime.js
=> chore: remove deadcode

packages/svelte/elements.d.ts
=> chore: document oninput type for elements.d.ts

benchmarking/benchmarks/mol_bench.js, benchmarking/run.js, benchmarking/tsconfig.json, benchmarking/utils.js, package.json, pnpm-lock.yaml
=> chore: add a benchmarking tool + single benchmark

.github/workflows/ci.yml, benchmarking/benchmarks/kairo/kairo_avoidable.js, benchmarking/benchmarks/kairo/kairo_broad.js, benchmarking/benchmarks/kairo/kairo_deep.js, benchmarking/benchmarks/kairo/kairo_diamond.js, benchmarking/benchmarks/kairo/kairo_mux.js, benchmarking/benchmarks/kairo/kairo_repeated.js, benchmarking/benchmarks/kairo/kairo_triangle.js, benchmarking/benchmarks/kairo/kairo_unstable.js, benchmarking/benchmarks/kairo/util.js, benchmarking/benchmarks/mol_bench.js, benchmarking/run.js, benchmarking/utils.js
Adds more benchmarks, along with assertions to ensure we don't break the benchmarks. Hooks it up to CI too.
=> chore: add more benchmarks

.changeset/sweet-bottles-check.md, packages/svelte/src/internal/client/runtime.js
This has a significant impact on our single benchmark.
=> chore: improve signal runtime perf

.changeset/twenty-gifts-develop.md, packages/svelte/src/internal/client/render.js
=> fix: remove document event listeners on unmount

.gitignore, benchmarking/benchmarks.js, benchmarking/compare.js, benchmarking/compare/index.js, benchmarking/compare/runner.js, benchmarking/run.js, package.json
Super-crude but we can iterate on it. Allows us to easily compare branches
=> chore: add `pnpm bench:compare` script

.changeset/gorgeous-boxes-design.md, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/global.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-runes/samples/state-update/_config.js, packages/svelte/tests/runtime-runes/samples/state-update/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12103
=> fix: ensure state update expressions are serialised correctly

package.json, packages/svelte/package.json, pnpm-lock.yaml
Removing 2,000 lines from our lockfile feels good!
The credit goes to @bluwy for this!
=> chore: remove hundreds of devDependencies

.changeset/wicked-ways-reply.md, packages/svelte/src/internal/client/dom/elements/bindings/select.js, packages/svelte/tests/runtime-runes/samples/snippet-select/Select.svelte, packages/svelte/tests/runtime-runes/samples/snippet-select/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-select/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12152.
=> fix: improve select handling of dynamic value with placeholders

playgrounds/demo/server.js
we broke this with the switch from express to polka
=> chore: fix playground SSR

sites/svelte-5-preview/src/routes/docs/content/01-api/02-runes.md
=> docs: rename `$effect.active` to `$effect.tracking` in REPL example

.changeset/lovely-ravens-crash.md, packages/svelte/src/compiler/public.d.ts, packages/svelte/types/index.d.ts
used by vite-plugin-svelte and exported in svelte4 too
=> fix(types): export CompileResult and Warning

package.json, pnpm-lock.yaml
=> chore: drop 31 deps via eslint dependencies

.changeset/dry-parrots-bathe.md, packages/svelte/src/internal/client/dom/elements/bindings/universal.js, packages/svelte/tests/runtime-runes/samples/contenteditable-state/Test.svelte, packages/svelte/tests/runtime-runes/samples/contenteditable-state/_config.js, packages/svelte/tests/runtime-runes/samples/contenteditable-state/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/11653
=> fix: support contenteditable binding undefined fallback

playgrounds/sandbox/package.json, playgrounds/sandbox/run.js, pnpm-lock.yaml
please test. I have not tested this because I did not see any documentation for how to run and use the playground
=> chore: remove a couple of dependencies

packages/svelte/tests/signals/test.ts
=> chore: add unowned signals test

.changeset/dry-ghosts-prove.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/tests/runtime-runes/samples/event-store-no-hoisting/_config.js, packages/svelte/tests/runtime-runes/samples/event-store-no-hoisting/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12288.
=> fix: bail out of event hoisting when referencing store subscriptions

.changeset/long-carrots-sneeze.md, package.json, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/tests/runtime-runes/samples/each-updates-frozen/_config.js, packages/svelte/tests/runtime-runes/samples/each-updates-frozen/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12302.
I couldn't figure out how to make the test force DEV to be false though :(
=> fix: ensure each blocks properly handle $state.frozen objects in prod

.changeset/eleven-cows-judge.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/internal/client/dom/blocks/await.js, packages/svelte/src/internal/client/dom/blocks/css-props.js, packages/svelte/src/internal/client/dom/blocks/html.js, packages/svelte/src/internal/client/dom/blocks/snippet.js, packages/svelte/src/internal/client/dom/blocks/svelte-element.js, packages/svelte/src/internal/server/dev.js, packages/svelte/tests/runtime-legacy/samples/inline-style-directive-shorthand-declaration-only/_config.js, packages/svelte/tests/runtime-runes/samples/invalid-html-ssr/_config.js
couple of drive-by fixes extracted from #12335
=> chore: tidy up

.changeset/plenty-clouds-reply.md, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/snapshot/samples/svelte-element/_expected/server/index.svelte.js
Another tiny change extracted from #12335 to make that PR smaller in size — will merge once green
=> feat: better `<svelte:element>` SSR output

.changeset/mean-numbers-cry.md, packages/svelte/src/compiler/phases/2-analyze/css/css-prune.js, packages/svelte/tests/css/samples/global-nested-block/_config.js, packages/svelte/tests/css/samples/global-nested-block/expected.css, packages/svelte/tests/css/samples/global-nested-block/input.svelte
=> fix: handle nested `:global(...)` selectors

.changeset/sour-tomatoes-knock.md, packages/svelte/messages/client-errors/errors.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/compiler/phases/3-transform/server/transform-server.js, packages/svelte/src/compiler/types/index.d.ts, packages/svelte/src/compiler/validate-options.js, packages/svelte/src/internal/client/dom/legacy/misc.js, packages/svelte/src/internal/client/errors.js, packages/svelte/tests/runtime-legacy/samples/binding-this-legacy-component-api/_config.js, packages/svelte/tests/runtime-runes/samples/legacy-class-transformation/_config.js, packages/svelte/types/index.d.ts, sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md, sites/svelte-5-preview/svelte.config.js
alternative to #12295. closes #12112
=> breaking: rename `legacy.componentApi` to `compatibility.componentApi`

.changeset/tall-dragons-switch.md, packages/svelte/src/compiler/legacy.js, packages/svelte/tests/parser-legacy/samples/if-block-elseif/input.svelte, packages/svelte/tests/parser-legacy/samples/if-block-elseif/output.json
https://github.com/sveltejs/svelte-ecosystem-ci/actions/runs/9868483385/job/27250591383#step:8:1032
=> fix: handle empty else if block in legacy AST

.changeset/grumpy-insects-sleep.md, packages/svelte/messages/shared-errors/errors.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/src/internal/shared/errors.js, packages/svelte/src/internal/shared/validate.js, packages/svelte/tests/runtime-legacy/shared.ts, packages/svelte/tests/runtime-runes/samples/snippet-slot-let-error/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-slot-let-error/inner.svelte, packages/svelte/tests/runtime-runes/samples/snippet-slot-let-error/main.svelte
=> fix: disallow using `let:` directives with component render tags

.changeset/wicked-bikes-matter.md, packages/svelte/src/internal/client/dom/elements/bindings/input.js
closes #12402. no test because it would be impractical to test the current failure mode
=> fix: optimize `bind:group`

packages/svelte/src/legacy/legacy-client.js
#12348 introduced a non-relative import, which _might_ be harmless but is discouraged nonetheless
=> chore: fix non-relative import

packages/svelte/tests/signals/test.ts
Added a test after seeing Ryan's latest video on the topic of reactivirty.
=> chore: add signal test

packages/svelte/messages/compile-errors/template.md, packages/svelte/src/compiler/errors.js, packages/svelte/src/compiler/phases/2-analyze/validation.js, packages/svelte/tests/compiler-errors/samples/snippet-rest-args/_config.js, packages/svelte/tests/compiler-errors/samples/snippet-rest-args/main.svelte
closes #12464
We even had an error code for that already, but we didn't actually use it for some reason
=> fix: error on snippet rest parameters

.changeset/popular-cups-bathe.md, packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/tests/runtime-runes/samples/event-import-no-param-hoisting/Component.svelte, packages/svelte/tests/runtime-runes/samples/event-import-no-param-hoisting/_config.js, packages/svelte/tests/runtime-runes/samples/event-import-no-param-hoisting/main.svelte, packages/svelte/tests/runtime-runes/samples/event-import-no-param-hoisting/state.svelte.js
=> fix: don't add imports to hoisted event parameters

packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-runes/samples/bind-this-order/_config.js, packages/svelte/tests/runtime-runes/samples/bind-this-order/main.svelte
No test yet because I'm in a hurry, should fix [this bug](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE01QW47bMAy8CldBkRaIE2f7-HAcAz1FP6p-KBEVCyuTgsS8YPjuhZxstxBAkcPHDDkq5wNm1fweFZkBVaN-xqhWSu6xBPmCQVCtVOZzOhakPZxFmIDpGPzxbT9-_gL7DnLPV9jDS_mnTvh0CthuHrWdJk3jwru5atKkpX2pKrCMmZYCV05vaxj4gnDwZBvpfYYDOk4IkgxlL54JhMH5G1RVpwmgJXP5L9u4cN-P462B7C0eTFqzcxnll7fSr4CjOXq5N7BdgT0nM7fA17qepg_O_fjsnWYGgB5D4CIv2JlyQ-bSaRo33pUtqM3H5KN0mvwQOQmMLtwncIkHWD5Ot_mQuNQUUN4v5UzIWIbM2IN3p6nd_JtZ5ss9YKep7DoWCZGf65ZToN0VTDg2UM9u8qde3oMeH9G2rj_NQDTWejo18Lp-TTjAtph6_SPhMOcPnCymKqArXfEGmYO3sDDGPPO3KvfG8rWB6lu8QQ3FLtz38naapln_U7NaqYGtdx6taiSdcfoz_QVKg8CfbwIAAA==)
=> fix: ensure `bind:this` happens before transitions and animations

.changeset/shiny-starfishes-cross.md, packages/svelte/src/internal/client/proxy.js, packages/svelte/tests/runtime-runes/samples/proxy-set-accessor/_config.js, packages/svelte/tests/runtime-runes/samples/proxy-set-accessor/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12499
=> fix: ensure $state proxy invokes set accessor if present

.changeset/tender-suns-love.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/tests/snapshot/samples/hmr/_expected/client/index.svelte.js
the non-controversial part of #12542
=> fix: correctly set filename on HMR wrappers

.changeset/small-planets-destroy.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/src/constants.js, packages/svelte/src/internal/client/dev/hmr.js, packages/svelte/src/internal/client/index.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/snapshot/samples/hmr/_expected/client/index.svelte.js
alternative to #12537 and #12542
=> fix: update original source in HMR update

.changeset/chilled-ladybugs-invite.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-runes/samples/dynamic-hof-delegated-event/_config.js, packages/svelte/tests/runtime-runes/samples/dynamic-hof-delegated-event/main.svelte
Alternative to https://github.com/sveltejs/svelte/pull/12524, fixes https://github.com/sveltejs/svelte/issues/12520.
=> fix: dynamic event delegation for stateful call expressions

packages/svelte/src/compiler/phases/3-transform/client/visitors/template.js, packages/svelte/tests/runtime-runes/samples/dynamic-element-event-handler/_config.js, packages/svelte/tests/runtime-runes/samples/dynamic-element-event-handler/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12520.
=> fix: improve dynamic event handling

playgrounds/demo/ssr-dev.js
embarrassingly simple fix. instamerging
=> chore: fix playground HMR

.changeset/long-coats-fry.md, packages/svelte/src/internal/client/dev/hmr.js
alternative to #12568. fixes #12417. No test at present, I think we'd need a new suite
=> fix: correctly set anchor inside HMR block

playgrounds/demo/index.html
not having this causes things like emojis to look messed up until hydration
=> chore: add <meta charset> to playground

sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
=> docs: note hydration comments change

.changeset/slow-gorillas-yawn.md, packages/svelte/src/internal/client/render.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/hydration/test.ts, packages/svelte/tests/runtime-browser/driver.js, packages/svelte/tests/runtime-runes/samples/hydrate-modified-input-group/_config.js, packages/svelte/tests/runtime-runes/samples/hydrate-modified-input/_config.js
Reverts sveltejs/svelte#12587 — this appears to have broken https://svelte-5-preview.vercel.app/
=> Revert "breaking: avoid flushing queued updates on mount/hydrate"

documentation/docs/02-template-syntax/09-special-elements.md
=> docs: mention xmlns attribute for `<svelte:element>`

documentation/docs/02-template-syntax/09-special-elements.md
=> chore: tweak xmlns docs

documentation/docs/02-template-syntax/02-basic-markup.md
=> chore: tweak event delegation docs

documentation/docs/05-misc/02-testing.md
- explain component and rune testing using Vitest
- explain e2e testing using Playwright
closes #10244
closes #10650
=> docs: add testing section

documentation/blog/2019-04-15-setting-up-your-editor.md, documentation/blog/2019-04-16-svelte-for-new-developers.md, documentation/blog/2021-01-01-whats-new-in-svelte-january-2021.md, documentation/blog/2021-02-01-whats-new-in-svelte-february-2021.md, documentation/blog/2021-03-01-whats-new-in-svelte-march-2021.md, documentation/blog/2021-10-01-whats-new-in-svelte-october-2021.md, documentation/blog/2023-02-01-whats-new-in-svelte-february-2023.md, documentation/blog/2023-03-09-zero-config-type-safety.md, documentation/docs/05-misc/03-typescript.md
via https://github.com/sveltejs/svelte/pull/12600#discussion_r1693636234 — apparently it's VS Code not VSCode. my whole life is a lie
=> chore: VSCode -> VS Code

.changeset/loud-news-deliver.md, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/tests/runtime-legacy/samples/rest-props-delete/App.svelte, packages/svelte/tests/runtime-legacy/samples/rest-props-delete/_config.js, packages/svelte/tests/runtime-legacy/samples/rest-props-delete/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12727
=> fix: allow deletion of $$restProps properties

.changeset/smooth-windows-explain.md, packages/svelte/src/compiler/phases/2-analyze/visitors/Attribute.js, packages/svelte/tests/runtime-browser/custom-elements-samples/host-rune/_config.js, packages/svelte/tests/runtime-browser/custom-elements-samples/host-rune/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12771
=> fix: ensure event handlers referencing $host are not hoisted

playgrounds/sandbox/run.js
small QOL thing extracted from #12780
=> chore: print compiler warnings when using sandbox

.github/workflows/release.yml, packages/svelte/package.json
Set provenance environment variable in the workflow file which will work for future packages as well (https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools)
=> chore: configure provenance env var

packages/svelte/src/internal/client/reactivity/props.js
introduced a bug at the very end of #12808, which didn't get caught because github actions went AWOL
=> fix: only proxy stuff in runes mode

packages/svelte/src/compiler/phases/3-transform/client/visitors/EachBlock.js, packages/svelte/src/constants.js
=> chore: remove unused EACH_KEYED constant

.changeset/six-vans-add.md, packages/svelte/elements.d.ts
The `crossorigin` attribute is enumerated: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
The `wrap` attribute also: https://html.spec.whatwg.org/#attr-textarea-wrap
=> fix: A few type adjustments

.changeset/happy-planets-rest.md, packages/svelte/elements.d.ts
=> fix: remove remaining Sapper stuff

packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/fragment.js
wanted to have a crack at https://github.com/sveltejs/svelte/pull/12855#issuecomment-2291534183, this is just a trivial tidy up before i get started
=> chore: minor tidy up

.changeset/unlucky-points-clap.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/utils.js, packages/svelte/tests/runtime-runes/samples/text-multiple-nullish-expression/_config.js, packages/svelte/tests/runtime-runes/samples/text-multiple-nullish-expression/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/12896.
=> fix: ensure nullish expressions render empty text

.changeset/flat-moose-arrive.md, packages/svelte/src/internal/client/reactivity/sources.js
Let's avoid doing unnecessary work.
=> fix: avoid extra work in mark_reactions

packages/svelte/src/compiler/phases/2-analyze/visitors/CallExpression.js
=> fix: compile error for incorrectly place `$state.link` or wrong argument count

packages/svelte/src/internal/client/dom/blocks/each.js
hopefully I got this roughly correct. feel free to update to be more accurate if I was a bit off
=> docs: add a jsdoc description for reconcile

documentation/docs/03-runes/02-side-effects.md, sites/svelte-5-preview/src/routes/docs/content/01-api/02-runes.md
=> docs: add note on when effects re-run

.changeset/light-tigers-smoke.md, packages/svelte/src/internal/client/reactivity/props.js, packages/svelte/tests/runtime-legacy/samples/rest-props-delete/App.svelte
=> fix: allow deleting non-existent `$$restProps` properties

packages/svelte/src/compiler/phases/1-parse/read/script.js
https://github.com/sveltejs/svelte/pull/12948#discussion_r1725796624
=> chore: remove temporary code

.changeset/olive-llamas-warn.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/tests/runtime-runes/samples/destructure-derived-by/_config.js, packages/svelte/tests/runtime-runes/samples/destructure-derived-by/main.svelte
=> fix: properly transform destructured `$derived.by` declarations

packages/svelte/src/compiler/phases/3-transform/client/utils.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/AssignmentExpression.js, packages/svelte/src/compiler/phases/3-transform/client/visitors/ClassBody.js
=> chore: update proxy reassignment code

.changeset/wet-donkeys-fry.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/shared/fragment.js, packages/svelte/tests/runtime-runes/samples/comment-separated-text/_config.js, packages/svelte/tests/runtime-runes/samples/comment-separated-text/main.svelte
=> fix: join text nodes separated by comments

packages/svelte/src/internal/client/dom/blocks/snippet.js, packages/svelte/src/internal/client/render.js, packages/svelte/src/internal/server/dev.js, packages/svelte/src/internal/server/index.js, packages/svelte/tests/runtime-legacy/samples/store-dev-mode-error/main.svelte, packages/svelte/tests/runtime-legacy/samples/transition-js-destroyed-before-end/_config.js, packages/svelte/tests/runtime-legacy/shared.ts, packages/svelte/tests/runtime-runes/samples/event-global-hydration-error-cleanup/_config.js, packages/svelte/tests/runtime-runes/samples/invalid-html-ssr/_config.js, packages/svelte/tests/server-side-rendering/samples/invalid-nested-svelte-element/_config.js, packages/svelte/tests/server-side-rendering/test.ts
tidies up the test output a bit
=> chore: squelch a warning

.changeset/few-walls-check.md, packages/svelte/src/internal/client/dom/elements/transitions.js
closes #13047. no test because life is too short and i'm too tired
=> fix: prevent div/0 when generating transition keyframes

.changeset/angry-weeks-design.md, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/tests/runtime-legacy/samples/store-updated-in-reactive-statement/Child.svelte, packages/svelte/tests/runtime-legacy/samples/store-updated-in-reactive-statement/_config.js, packages/svelte/tests/runtime-legacy/samples/store-updated-in-reactive-statement/main.svelte, packages/svelte/tests/runtime-legacy/samples/store-updated-in-reactive-statement/state.js
=> fix: ensure reactive graph is fully traversed in the marking phase for non-runes mode

documentation/docs/05-misc/03-typescript.md
=> docs: updated import for SvelteKit 2

.changeset/itchy-oranges-behave.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/tests/runtime-runes/samples/empty-class-attribute-template/_config.js, packages/svelte/tests/runtime-runes/samples/empty-class-attribute-template/main.svelte
=> fix: remove unnecessary update assignments

packages/svelte/elements.d.ts
Was missing from #12754 where we made the tag optional
fixes #13161
=> fix: make custom element tag optional in typings

sites/svelte-5-preview/src/routes/docs/content/03-appendix/02-breaking-changes.md
=> docs: note event attributes in breaking changes

packages/svelte/src/compiler/phases/2-analyze/visitors/IfBlock.js, packages/svelte/tests/validator/samples/if-block-whitespace-runes/errors.json, packages/svelte/tests/validator/samples/if-block-whitespace-runes/input.svelte
=> fix: correctly validate nested if block tags

documentation/docs/02-template-syntax/08-bindings.md
=> docs: adjust `bind:files` section

packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/slots/input.svelte, packages/svelte/tests/migrate/samples/slots/output.svelte
Mentioned in https://github.com/sveltejs/kit/pull/12519#issuecomment-2344826143
=> fix: migrate `$$slots.default` correctly

.changeset/hot-grapes-destroy.md, packages/svelte/src/compiler/phases/3-transform/client/transform-client.js, packages/svelte/tests/runtime-runes/samples/derived-shadowed/_config.js, packages/svelte/tests/runtime-runes/samples/derived-shadowed/main.svelte
=> fix: delete transformers shadowed by unreassigned state

.changeset/old-spoons-pull.md, packages/svelte/messages/compile-warnings/template.md, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteSelf.js, packages/svelte/src/compiler/warnings.js, packages/svelte/tests/validator/samples/attribute-quoted/input.svelte, packages/svelte/tests/validator/samples/attribute-quoted/warnings.json, packages/svelte/tests/validator/samples/svelte-self-deprecated/input.svelte, packages/svelte/tests/validator/samples/svelte-self-deprecated/warnings.json
=> feat: deprecate `<svelte:self>` in runes mode

.changeset/cool-yaks-run.md, packages/svelte/src/animate/index.js
closes #13351. no test because adding tests for this sort of thing is prohibitively difficult
=> fix: only use getComputedStyle with elements

.changeset/unlucky-baboons-greet.md, packages/svelte/src/internal/client/dom/blocks/each.js, packages/svelte/tests/runtime-runes/samples/transition-each/_config.js, packages/svelte/tests/runtime-runes/samples/transition-each/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13302.
=> fix: improve reconciliation of inert each block rows

.changeset/good-vans-bake.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/src/compiler/phases/1-parse/state/element.js, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteComponent.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/migrate/samples/svelte-component/input.svelte, packages/svelte/tests/migrate/samples/svelte-component/output.svelte
Closes #13418 
As usual this kinda opened a can of ~worms~edge cases so i had to go through multiple hops for something and there might be better ways to do it but it should work decently (you can see the transform from the output of the test)
=> feat: support migration of `svelte:component`

pnpm-lock.yaml, sites/svelte.dev/package.json, sites/svelte.dev/src/routes/+layout.svelte
This will allow us to get an idea of traffic. Generally we're quite analytics-resistant people, but this has minimal footprint and doesn't use cookies
=> add vercel analytics

.changeset/real-camels-pay.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/self-closing-elements/input.svelte, packages/svelte/tests/migrate/samples/self-closing-elements/output.svelte
=> feat: support migration of self closing tags

.changeset/real-timers-complain.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/svelte-component/input.svelte, packages/svelte/tests/migrate/samples/svelte-component/output.svelte
=> fix: various `svelte:component` migration bugs

.changeset/seven-wombats-retire.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/accessors/output.svelte
=> fix: exclude type-only props from instance exports when migrating

.changeset/wet-hats-peel.md, packages/svelte/src/internal/client/render.js, packages/svelte/tests/runtime-runes/samples/array-to-string/_config.js, packages/svelte/tests/runtime-runes/samples/array-to-string/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/13054 and fixes https://github.com/sveltejs/svelte/issues/13525
=> fix: ensure set_text applies coercion to objects before diff

documentation/docs/02-template-syntax/01-component-fundamentals.md, documentation/docs/02-template-syntax/02-basic-markup.md, documentation/docs/02-template-syntax/04-snippets.md, documentation/docs/02-template-syntax/05-styles-and-classes.md, documentation/docs/02-template-syntax/06-transitions-and-animations.md, documentation/docs/02-template-syntax/07-actions.md, documentation/docs/02-template-syntax/08-bindings.md, documentation/docs/02-template-syntax/09-special-elements.md, documentation/docs/03-runes/01-state.md, documentation/docs/03-runes/02-side-effects.md, documentation/docs/04-runtime/01-stores.md, documentation/docs/04-runtime/02-context.md, documentation/docs/04-runtime/03-lifecycle-hooks.md, documentation/docs/05-misc/01-debugging.md, documentation/docs/05-misc/02-testing.md, documentation/docs/05-misc/03-typescript.md
=> docs: annotate notes as such

documentation/docs/02-template-syntax/01-component-fundamentals.md
another adjustment for the new site
=> docs: fix titles

.changeset/spotty-kings-hug.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/props-rest-props-ts/input.svelte, packages/svelte/tests/migrate/samples/props-rest-props-ts/output.svelte, packages/svelte/tests/migrate/samples/props-rest-props/output.svelte, packages/svelte/tests/migrate/samples/slots-with-$$props/output.svelte, packages/svelte/tests/migrate/samples/svelte-component/output.svelte, packages/svelte/tests/migrate/samples/svelte-self-name-conflict/output.svelte, packages/svelte/tests/migrate/samples/svelte-self/output.svelte
=> fix: migrating rest props type includes props types

.changeset/smooth-apes-shave.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/reactive-statements-inner-block/input.svelte, packages/svelte/tests/migrate/samples/reactive-statements-inner-block/output.svelte
Fixes https://github.com/sveltejs/svelte/issues/13664
=> fix: migrate reactive statements with inner blocks

.changeset/silver-beans-hear.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/named-slots/input.svelte, packages/svelte/tests/migrate/samples/named-slots/output.svelte
Fixes https://github.com/sveltejs/svelte/issues/13666.
=> fix: ensure migrate correctly handles named slots

.github/PULL_REQUEST_TEMPLATE.md
time to remove the Svelte 5 note
=> chore: cleanup PR template

.changeset/gorgeous-vans-sparkle.md, packages/svelte/src/internal/client/dom/elements/attributes.js
fixes #13691
fixes #13414
fixes #13726
no test because impossible, but I verified it works for Firefox via the reproduction in #13691
=> fix: add more robust check for `Element` prototype

.changeset/five-dingos-push.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/slot-usages/input.svelte, packages/svelte/tests/migrate/samples/slot-usages/output.svelte
=> fix: migrate default slots to children snippet

documentation/docs/01-introduction/02-getting-started.md, documentation/docs/03-template-syntax/06-snippet.md, documentation/docs/07-misc/07-v5-migration-guide.md, documentation/docs/07-misc/99-faq.md
updates some out of date links
=> docs: make links internal

documentation/docs/03-template-syntax/06-snippet.md
=> fix: typo in the snippet closing tag

documentation/docs/07-misc/03-typescript.md
=> docs: fix generic props type

documentation/docs/07-misc/07-v5-migration-guide.md
=> docs: Remove redundant angle brackets, fix typo.

documentation/docs/99-legacy/40-legacy-component-api.md
backporting from https://github.com/sveltejs/svelte.dev/pull/546
=> docs: fix code example

documentation/docs/01-introduction/02-getting-started.md
This pull request enhances the installation steps by:
1. Specifying the code block language in the markdown for better syntax highlighting, aligning with the corresponding section in SvelteKit.
2. Adding the `npm install` step to ensure dependencies are installed before running `npm run dev`, preventing potential errors.
=> docs: specify script language and add `npm install` step to installation guide

.changeset/dull-wolves-judge.md
looking at https://github.com/sveltejs/svelte/pull/13757 it's a bit odd that one doesn't match the rest
=> chore: one of these is not like the others

packages/svelte/src/index.d.ts, packages/svelte/types/index.d.ts
=> docs: fix ComponentProps info

.changeset/curvy-beds-cover.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/tests/runtime-legacy/samples/each-block-ref-import/_config.js, packages/svelte/tests/runtime-legacy/samples/each-block-ref-import/main.svelte, packages/svelte/tests/runtime-legacy/samples/each-block-ref-import/utils.js
Fixes https://github.com/sveltejs/svelte/issues/13876
=> fix: ensure each block references to imports are handled correctly

.github/workflows/pkg.pr.new.yml
=> chore: setup `pkg.pr.new`

.changeset/cold-owls-do.md
Adds a changeset for https://github.com/sveltejs/svelte/pull/13884
=> chore: add missing changeset

documentation/docs/02-runes/04-$effect.md
Fixes #13902. Does not address #13903, which we're now leaning toward fixing by changing the behavior rather than changing the docs.
=> docs: fix outdated $effect.tracking() demo

documentation/docs/03-template-syntax/12-use.md
A full stop or colon, we must choose.
---
=> docs: fix small typo in `use:`

sites/svelte.dev/package.json
=> chore: fix docs deployment

.changeset/wild-oranges-promise.md, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/utils.js, packages/svelte/src/compiler/phases/scope.js, packages/svelte/tests/migrate/samples/import-type-$-prefix/input.svelte, packages/svelte/tests/migrate/samples/import-type-$-prefix/output.svelte
=> fix: properly migrate imports types prefixed with $

documentation/docs/05-special-elements/06-svelte-options.md
=> docs: mark deprecated options as such

.changeset/small-bobcats-add.md, packages/svelte/src/internal/client/timing.js
for https://github.com/sveltejs/svelte/pull/14026
=> chore: add changeset and comment

package.json, pnpm-lock.yaml
As of #13794, we no longer need this override.
=> chore: remove xml2js override

.changeset/rotten-cups-float.md, packages/svelte/src/index.d.ts, packages/svelte/tests/types/component.ts, packages/svelte/types/index.d.ts
Reverts sveltejs/svelte#13441 — we decided to go a different route
=> Revert "feat: add `ComponentExports` utility type"

.changeset/nice-peas-lay.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js, packages/svelte/tests/runtime-runes/samples/snippet-ref/_config.js, packages/svelte/tests/runtime-runes/samples/snippet-ref/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14068 and fixes https://github.com/sveltejs/svelte/issues/14071.
=> fix: ensure compiler statements are correctly included

.changeset/modern-adults-lay.md, packages/svelte/src/compiler/phases/2-analyze/index.js, packages/svelte/src/compiler/phases/2-analyze/visitors/TransitionDirective.js, packages/svelte/tests/runtime-runes/samples/transition-static-subtree/_config.js, packages/svelte/tests/runtime-runes/samples/transition-static-subtree/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14073
=> fix: ensure transitions are applied to nested elements

.changeset/silly-bulldogs-rest.md, packages/svelte/src/legacy/legacy-client.js
fixes #13832
no test because it feels a bit silly for a legacy-one-liner
=> fix: pass along `anchor` in legacy class wrappers

.changeset/polite-timers-tell.md, packages/svelte/src/compiler/phases/2-analyze/visitors/SvelteElement.js, packages/svelte/tests/runtime-legacy/samples/dynamic-element-svg-options-namespace/_config.js, packages/svelte/tests/runtime-legacy/samples/dynamic-element-svg-options-namespace/main.svelte, packages/svelte/tests/runtime-legacy/samples/dynamic-element-svg-options-namespace/rect.svelte
We were checking it for nested elements, but not root elements
fixes #13875
=> fix: check options namespace for top level `svelte:element`s

documentation/docs/06-runtime/03-lifecycle-hooks.md
The code snipped doesn't compile.
=> docs: fix compilation error

.github/workflows/docs-preview-create-request.yml, .github/workflows/docs-preview-delete-request.yml, documentation/docs/01-introduction/01-overview.md
this will, in theory, result in preview deployments for PRs that change the docs
=> chore: setup docs previews

.changeset/silent-tigers-lay.md, packages/svelte/src/compiler/migrate/index.js, packages/svelte/tests/migrate/samples/shadowed-forwarded-slot/input.svelte, packages/svelte/tests/migrate/samples/shadowed-forwarded-slot/output.svelte
=> fix: prevent migrated snippet from shadow snippet prop

.github/workflows/pkg.pr.new-comment.yml, .github/workflows/pkg.pr.new.yml
Apparently main is very well locked down 😄
=> fix: use both correct paths

.github/workflows/pkg.pr.new-comment.yml
=> fix: we are getting there...this should be it

.changeset/dull-laws-end.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-runes/samples/typescript/_config.js, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte
=> fix: ignore `as` type expressions on property definitions

documentation/docs/07-misc/02-testing.md
Rewrote sentence with possible incorrect syntax in section on E2E testing.
=> docs: Update 02-testing.md

.changeset/good-laws-sin.md, packages/svelte/src/internal/client/dev/ownership.js, packages/svelte/tests/runtime-runes/samples/mutate-state-in-context-dev/_config.js, packages/svelte/tests/runtime-runes/samples/mutate-state-in-context-dev/main.svelte
=> fix: account for mutations in script module in ownership check

documentation/docs/06-runtime/01-stores.md
closes https://github.com/sveltejs/svelte/issues/13879
=> docs: add example to "state instead of stores"

.changeset/shy-starfishes-type.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte
=> fix: strip exported TypeScript function overloads

.changeset/sixty-kings-learn.md, packages/svelte/package.json, pnpm-lock.yaml, sites/svelte-5-preview/package.json
=> fix: generate correct code when encountering object expression statement

.changeset/gentle-bulldogs-heal.md, packages/svelte/package.json, packages/svelte/tests/runtime-browser/test.ts, pnpm-lock.yaml
closes https://github.com/sveltejs/svelte/issues/14465
=> fix: upgrade to esm-env 1.2.1 to fix issues with non-Vite setups

documentation/docs/05-special-elements/01-svelte-boundary.md
not sure if there's a better way to present this
=> docs: note when boundaries were added

.changeset/wild-islands-help.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte
=> fix: ignore TypeScript generics on variables

packages/svelte/src/index.d.ts, packages/svelte/types/index.d.ts
=> chore: fix typo

documentation/docs/03-template-syntax/06-snippet.md
=> docs: note requirement on 5.5.0 to export snippets

documentation/docs/02-runes/02-$state.md
Small typo in the docs noticed in #14528
=> fix: docs typo in `$state`

.changeset/itchy-cooks-yawn.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/remove-spreaded-handlers/_config.js, packages/svelte/tests/runtime-runes/samples/remove-spreaded-handlers/main.svelte
=> fix: remove spreaded event handlers when they become nullish

packages/svelte/src/index-client.js, packages/svelte/src/index.d.ts, packages/svelte/types/index.d.ts
these look terrible at the moment
=> fix deprecation notices

documentation/docs/06-runtime/01-stores.md, documentation/docs/06-runtime/02-context.md
See #14566 & also [this](https://stackoverflow.com/q/79258088/546730).
=> docs: Import .svelte.js files with explicit extension.

packages/svelte/types/index.d.ts
i _think_ the fact that this was missing caused the release action to fail. fingers crossed
=> chore: regenerate types

.changeset/green-pandas-study.md, packages/svelte/src/compiler/phases/2-analyze/visitors/BindDirective.js, packages/svelte/tests/runtime-runes/samples/bind-getter-setter/_config.js, packages/svelte/tests/runtime-runes/samples/bind-getter-setter/main.svelte
=> fix: mark subtree dynamic for bind with sequence expressions

.changeset/olive-pillows-fetch.md, packages/svelte/src/compiler/phases/3-transform/css/index.js, packages/svelte/tests/css/samples/global-with-root/expected.css, packages/svelte/tests/css/samples/global-with-root/input.svelte
=> fix: account for global block in `is_empty`

.changeset/strong-pandas-provide.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/runtime-runes/samples/binding-interop-derived/Comp.svelte, packages/svelte/tests/runtime-runes/samples/binding-interop-derived/_config.js, packages/svelte/tests/runtime-runes/samples/binding-interop-derived/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14684.
=> fix: avoid mutation validation for invalidate_inner_signals

.changeset/sour-jeans-talk.md
=> bump changeset to minor

LICENSE.md
Happy new year, love your project <3
=> chore: update copyright year

.changeset/real-onions-confess.md, packages/svelte/src/compiler/phases/2-analyze/visitors/RegularElement.js, packages/svelte/src/compiler/phases/3-transform/utils.js, packages/svelte/tests/runtime-runes/samples/svg-namespace-if-block-3/_config.js, packages/svelte/tests/runtime-runes/samples/svg-namespace-if-block-3/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/14814
=> fix: ensure logic blocks keep consistent namespacing

documentation/docs/02-runes/03-$derived.md
alternative to #14931
closes #14772
=> docs: add section on update propagation

.changeset/sour-pots-wonder.md, packages/svelte/src/internal/client/dom/elements/bindings/media.js, packages/svelte/tests/runtime-runes/samples/bind-current-time-remove-listener/_config.js, packages/svelte/tests/runtime-runes/samples/bind-current-time-remove-listener/main.svelte
=> fix: remove listener on `bind_current_time` teardown

.changeset/happy-ants-grin.md, packages/svelte/src/internal/client/dom/elements/bindings/input.js
Closes #15054
No test because i'm not sure how we could test this if you have ideas I can implement them 😄
=> fix: initialize `files` bind on hydration

packages/svelte/src/internal/client/render.js
Here, neither null or undefined again
=> fix: optimize the assign expression

.changeset/blue-sheep-joke.md, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/reactivity/effects.js, packages/svelte/src/internal/client/runtime.js
This code is not used, so best to save some bytes.
=> chore: remove unused code from signal logic

documentation/docs/07-misc/07-v5-migration-guide.md
=> docs: enhance migration docs about accessors

playgrounds/sandbox/package.json, pnpm-lock.yaml
this broke stuff 🤷 
Reverts sveltejs/svelte#15199
=> Revert "chore(deps-dev): bump vite from 5.4.14 to 6.0.9"

package.json
See also https://github.com/sveltejs/kit/pull/13442 and https://github.com/sveltejs/svelte.dev/pull/1155
=> chore: allow pnpm 10

documentation/docs/02-runes/06-$bindable.md
=> docs(bindable): fix `file:` annotation for App.svelte

.changeset/lovely-chairs-compete.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/AssignmentExpression.js, packages/svelte/tests/runtime-runes/samples/store-reassign-object/_config.js, packages/svelte/tests/runtime-runes/samples/store-reassign-object/main.svelte
=> fix: prevent writable store value from becoming a proxy when reassigning using $-prefix

README.md
A miniature PR that updates the "alt" tag for the license badge in the readme from "license" to "License". This is to match the second badge which has the name "Chat"
=> docs: update casing

packages/svelte/src/internal/client/dom/task.js, packages/svelte/src/internal/client/reactivity/deriveds.js, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/snapshot/_config.js
=> chore: remove some unused exports

packages/svelte/src/compiler/phases/2-analyze/visitors/BindDirective.js, packages/svelte/src/compiler/phases/2-analyze/visitors/shared/utils.js
=> chore: DRY out assignment validation

.changeset/fast-pants-decide.md, packages/svelte/src/compiler/phases/1-parse/read/style.js, packages/svelte/tests/css/samples/double-hyphen/expected.css, packages/svelte/tests/css/samples/double-hyphen/input.svelte
=> fix: allow double hyphen css selector names

.changeset/proud-poems-brake.md, packages/svelte/src/internal/client/runtime.js, packages/svelte/tests/signals/test.ts
=> fix: correctly set `is_updating` before flushing root effects

benchmarking/compare/index.js, benchmarking/compare/runner.js
these are broken currently. will self-merge to unblock other stuff
=> fix benchmarks

documentation/docs/02-runes/04-$effect.md
follow-up to https://github.com/sveltejs/svelte/pull/15564#issuecomment-2741849603
=> docs: add note on effect-local state

documentation/docs/07-misc/99-faq.md
=> docs: add a reference to the official hash router

.changeset/lovely-windows-hang.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte
=> fix: support TS type assertions

.changeset/smooth-mugs-grin.md, packages/svelte/src/internal/server/index.js
fixes #15543
No test because this is a one-liner in a stable part of the code-base, also it can only happen within legacy mode when using bindings which is not getting any new updates at this point
=> fix: make sure CSS is preserved during SSR with bindings

documentation/docs/06-runtime/02-context.md
use `const` for key variable and assign it a symbol instead of empty of object.
=> docs:Update 02-context.md

playgrounds/sandbox/run.js
small QOL thing that makes `sandbox/output` way less cluttered when you have a bunch of files
=> nicer sandbox output

.github/workflows/pkg.pr.new.yml
=> use pnpm/action-setup

packages/svelte/src/internal/client/reactivity/sources.js, packages/svelte/src/internal/client/runtime.js
=> chore: remove some unused code

.changeset/wicked-cheetahs-juggle.md, packages/svelte/src/compiler/phases/2-analyze/visitors/RegularElement.js, packages/svelte/tests/validator/samples/invalid-self-closing-tag/input.svelte, packages/svelte/tests/validator/samples/invalid-self-closing-tag/warnings.json
=> fix: allow self-closing tags within math namespace

.changeset/quick-cougars-fly.md
oops, missed changeset in #15785
=> chore: add missing changeset for #15785

.changeset/wild-bulldogs-move.md, packages/svelte/src/compiler/phases/1-parse/utils/html.js
fixes #15821
Source: https://en.wikipedia.org/wiki/Plane_(Unicode)#Supplementary_Special-purpose_Plane
=> fix: allow characters in the supplementary special-purpose plane

packages/svelte/src/internal/client/runtime.js
equivalent code to what we have now, but IMHO a bit neater
=> chore: tweak flushSync implementation

packages/svelte/src/compiler/types/index.d.ts, packages/svelte/types/index.d.ts
=> chore: add `@since` tag to fragments option

.github/workflows/ci.yml
=> ci: use Node.js 24

.changeset/hip-penguins-unite.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js, packages/svelte/tests/runtime-runes/samples/destructure-state-from-props/Child.svelte, packages/svelte/tests/runtime-runes/samples/destructure-state-from-props/_config.js, packages/svelte/tests/runtime-runes/samples/destructure-state-from-props/main.svelte
=> fix: visit expression when destructuring state declarations

.changeset/three-steaks-wash.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/ClassBody.js, packages/svelte/tests/runtime-runes/samples/inspect-trace-class/_config.js, packages/svelte/tests/runtime-runes/samples/inspect-trace-class/main.svelte
quick follow to #16060 — will self-merge once green to unblock other stuff (and because it's a regression)
=> fix: correctly tag private class state fields

.changeset/neat-lemons-occur.md, packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js, packages/svelte/tests/runtime-runes/samples/typescript/main.svelte
=> fix: prune typescript class field declarations

.changeset/curvy-carrots-prove.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-runes/samples/select-spread-option-selected/_config.js, packages/svelte/tests/runtime-runes/samples/select-spread-option-selected/main.svelte
=> fix: account for mounting when `select_option` in `attribute_effect`

documentation/docs/02-runes/02-$state.md
=> docs: add note about proxying state proxies

packages/svelte/knip.json, packages/svelte/src/compiler/phases/scope.js, packages/svelte/src/internal/client/context.js, packages/svelte/src/internal/server/abort-signal.js, packages/svelte/src/internal/shared/validate.js, packages/svelte/src/utils.js
removes some unused exports and imports, removes some redundant entries from our knip config
=> chore: tidy up some stuff

.changeset/soft-moles-work.md, packages/svelte/src/internal/client/reactivity/batch.js
file this under 'things that don't matter at all in the real world but matter a great deal in benchmarks'
=> fix: avoid microtask in flushSync

.changeset/four-kings-drum.md, packages/svelte/src/internal/client/reactivity/batch.js, packages/svelte/tests/runtime-runes/samples/dependencyless-abort-signal/Component.svelte, packages/svelte/tests/runtime-runes/samples/dependencyless-abort-signal/_config.js, packages/svelte/tests/runtime-runes/samples/dependencyless-abort-signal/main.svelte
=> fix: keep effect in the graph if it has an abort controller

documentation/docs/98-reference/21-svelte-action.md
Closes #16471
AFAICT we can't reorder the docs for individual exports, so this is probably the best we can do.
=> docs: add note about attachments to `svelte/action` docs

.changeset/afraid-carrots-study.md, packages/svelte/src/internal/client/dom/elements/attributes.js, packages/svelte/tests/runtime-legacy/samples/attribute-after-property/_config.js, packages/svelte/tests/runtime-legacy/samples/attribute-after-property/main.svelte
=> fix: reset attribute cache after setting corresponding property

.github/workflows/release.yml
to use oidc publish
requires npm package config first, draft until that is set up
=> refactor(release): run with node24 and remove NPM_TOKEN 

packages/svelte/src/internal/client/dom/operations.js, packages/svelte/src/internal/client/dom/template.js, packages/svelte/src/internal/client/reactivity/batch.js
=> chore: extract a couple of drive-by fixes from other branch

.changeset/silly-walls-fail.md, packages/svelte/src/compiler/phases/3-transform/client/visitors/TitleElement.js, packages/svelte/tests/runtime-runes/samples/title-nullish/_config.js, packages/svelte/tests/runtime-runes/samples/title-nullish/main.svelte
Closes https://github.com/sveltejs/kit/issues/14548
=> fix: coerce nullish `<title>` to empty string

.changeset/poor-flies-serve.md, packages/svelte/src/compiler/phases/3-transform/server/visitors/SvelteBoundary.js, packages/svelte/tests/server-side-rendering/samples/async-svelte-boundary/_expected.html, packages/svelte/tests/server-side-rendering/samples/async-svelte-boundary/main.svelte
Fix: #16856
I referred #16817, but to sure if it is correct.
=> fix: allow await in svelte boundary without pending
