sveltejs/svelte

- compiler/parse/read/script.js
- test/parser/script-comment-only/input.html
- test/parser/script-comment-only/output.json
- test/parser/script-comment-trailing-multiline/input.html
- test/parser/script-comment-trailing-multiline/output.json
- test/parser/script-comment-trailing/input.html
- test/parser/script-comment-trailing/output.json
> handle trailing comments in script tags

- compiler/generate/visitors/MustacheTag.js
- compiler/generate/visitors/Text.js
- test/compiler/each-block-text-node/_config.js
- test/compiler/each-block-text-node/main.html
> remove text nodes when removing iterations of each block

- compiler/generate/index.js
- compiler/generate/visitors/EachBlock.js
- compiler/generate/visitors/attributes/addElementAttributes.js
- test/test.js
> prevent compiler from generating ES2015+ code

- compiler/generate/index.js
- compiler/generate/visitors/EachBlock.js
- compiler/generate/visitors/IfBlock.js
- compiler/generate/visitors/MustacheTag.js
- compiler/generate/visitors/Text.js
* avoid teardown for nested textnodes
* avoid detaching children of a nested each
> various optimizations

- README.md
https://github.com/shinnn/gulp-svelte
https://www.npmjs.com/package/gulp-svelte
https://github.com/shinnn/metalsmith-svelte
https://www.npmjs.com/package/metalsmith-svelte
> Add links to gulp and Metalsmith plugins

- compiler/parse/state/tag.js
- test/parser/convert-entities/input.html
- test/parser/convert-entities/output.json
Fixes the bug discovered in #85.
> Convert character entities correctly

- compiler/generate/index.js
- compiler/generate/visitors/EachBlock.js
- compiler/generate/visitors/Element.js
- compiler/generate/visitors/IfBlock.js
* fix some code style issues
* refactor around createMountStatement
* fix non-toplevel if blocks and elements being detached
> various refactorings & fixes

- README.md
Seems like it is public API: https://github.com/sveltejs/svelte/blob/master/compiler/index.js#L8.
> Correct README to use onwarn

- compiler/generate/visitors/EachBlock.js
- compiler/parse/state/mustache.js
- test/compiler/each-block-else/_config.js
- test/compiler/each-block-else/main.html
- test/parser/each-block-else/input.html
- test/parser/each-block-else/output.json
> Support {{#each}}-{{else}}

- compiler/generate/visitors/Element.js
- test/compiler/svg-multiple/_config.js
- test/compiler/svg-multiple/main.html
> allow multiple SVGs

- compiler/generate/visitors/Text.js
- compiler/generate/visitors/attributes/addElementAttributes.js
- compiler/parse/state/tag.js
- test/compiler/svg-no-whitespace/_config.js
- test/compiler/svg-no-whitespace/main.html
- test/compiler/svg-xmlns/_config.js
- test/compiler/svg-xmlns/main.html
- test/parser/error-multiple-styles/error.json
- test/parser/error-multiple-styles/input.html
> don't render whitespace text nodes inside SVG elements

- rollup.config.main.js
- rollup.config.ssr.js
- src/generate/index.js
- src/index.js
- src/server-side-rendering/compile.js
- src/server-side-rendering/register.js
> add a compiler option to output SSR code

- src/generate/index.js
- test/generator/computed-function/_config.js
- test/generator/computed-function/main.html
- test/generator/default-data-function/_config.js
- test/generator/default-data-function/main.html
> allow functions in data/computed

- src/server-side-rendering/compile.js
- test/server-side-rendering/directives/_actual.html
- test/server-side-rendering/directives/_expected.html
- test/server-side-rendering/directives/main.html
> omit attributes for SSR

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Ref #151 – adapted from the templates we use for Rollup
> issue and PR templates

- src/generators/shared/utils/getIntro.js
> remove extensions from AMD dependencies

- .github/ISSUE_TEMPLATE.md
It makes a red squiggly line show up when people hit "new issue" :-x
> Typo in issue template

- package.json
- rollup/rollup.config.main.js
- src/index.js
> add VERSION property

- src/generators/dom/visitors/attributes/addElementAttributes.js
- test/generator/svg-class/_config.js
- test/generator/svg-class/main.html
> dont use properties when setting <svg> element attributes

- src/generators/server-side-rendering/visitors/Component.js
Original Issue: #234
Original PR: #235 
The SSR code should probably be ran under the same tests as the client code..
> Fix partial numbers being detected as numbers but in SSR code

- src/generators/dom/index.js
- src/generators/dom/visitors/EachBlock.js
- src/generators/dom/visitors/IfBlock.js
- src/generators/dom/visitors/YieldTag.js
- src/shared/dom.js
- test/generator/attribute-dynamic-multiple/_config.js
- test/generator/binding-input-text-contextual/_config.js
- test/generator/binding-input-text-deep-contextual/_config.js
- test/generator/component-yield-parent/_config.js
- test/generator/each-block-indexed/_config.js
- test/generator/each-block/_config.js
- test/generator/each-blocks-expression/_config.js
- test/generator/each-blocks-nested-b/_config.js
- test/generator/each-blocks-nested/_config.js
- test/generator/event-handler-removal/_config.js
- test/generator/event-handler/_config.js
- test/generator/if-block-widget/_config.js
- test/generator/if-block/_config.js
> Use empty comments as anchors

- src/generators/dom/index.js
- src/generators/dom/visitors/attributes/binding/index.js
- test/generate.js
- test/generator/component-binding-conditional-b/Bar.html
- test/generator/component-binding-conditional-b/Baz.html
- test/generator/component-binding-conditional-b/Foo.html
- test/generator/component-binding-conditional-b/_config.js
- test/generator/component-binding-conditional-b/main.html
- test/generator/component-binding-conditional/Bar.html
- test/generator/component-binding-conditional/Baz.html
- test/generator/component-binding-conditional/Foo.html
- test/generator/component-binding-conditional/_config.js
- test/generator/component-binding-conditional/main.html
> Don't trigger bindings for torn-down components

- src/generators/dom/visitors/attributes/addElementAttributes.js
- test/generator/select/_config.js
- test/generator/select/main.html
Fix for issue mentioned here (#291)
> fix select option value issue

- src/generators/dom/visitors/Component.js
- src/generators/dom/visitors/attributes/binding/index.js
- test/generator/component-binding-each-nested/Widget.html
- test/generator/component-binding-each-nested/_config.js
- test/generator/component-binding-each-nested/main.html
- test/generator/component-binding-each/Widget.html
- test/generator/component-binding-each/_config.js
- test/generator/component-binding-each/main.html
Two-way binding doesn't work with components in `{{#each ...}}` blocks — the code is being generated incorrectly.
> [WIP] failing tests for second bug in #290

- src/generators/dom/visitors/Element.js
- src/generators/dom/visitors/attributes/binding/index.js
- test/generator/binding-select-initial-value/_config.js
- test/generator/binding-select-initial-value/main.html
Fixes #301. Unfortunately it's not possible to add a non-skipped test right now due to a quirk in JSDOM, but I've tested it locally.
> Initialise <select> elements with two-way binding

- src/generators/Generator.js
- test/generator/destructuring/_config.js
- test/generator/destructuring/main.html
> handle shorthand properties in expressions

- src/generators/dom/index.js
> prevent duplicate imports

- src/generators/shared/processCss.js
> Support keyframes with scoping

- src/generators/Generator.js
- src/generators/annotateWithScopes.js
- test/generate.js
- test/generator/function-in-expression/_config.js
- test/generator/function-in-expression/main.html
> allow [arrow] function expressions inside tags 

- src/generators/dom/visitors/Element.js
- src/generators/dom/visitors/attributes/binding/index.js
- test/generator/binding-select-multiple/_config.js
- test/generator/binding-select-multiple/main.html
> two-way binding with <select multiple>

- src/generators/server-side-rendering/visitors/Element.js
- src/parse/state/tag.js
- src/utils/isVoidElementName.js
- src/utils/voidElementNames.js
> accept DOCTYPE element in any case

- src/parse/state/tag.js
- test/parser/error-multiple-styles/error.json
> only process special tags (script, style) when they are top-level

- src/parse/patterns.js
- test/generator/nbsp/_config.js
- test/generator/nbsp/main.html
- test/parser/nbsp/input.html
- test/parser/nbsp/output.json
> differentiate between nbsp and other whitespace

- src/generators/dom/visitors/attributes/binding/index.js
- src/generators/server-side-rendering/visitors/Component.js
- test/generator/samples/component-binding-each-object/Widget.html
- test/generator/samples/component-binding-each-object/_config.js
- test/generator/samples/component-binding-each-object/main.html
> fix two-way binding for components inside each-blocks

- README.md
> Add more formal documentation for API options

- src/generators/dom/visitors/attributes/addElementBinding.js
- test/generator/samples/binding-input-radio-group/_config.js
- test/generator/samples/binding-input-radio-group/main.html
> implement bind:group for radio input groups

- src/generators/Generator.js
- src/generators/annotateWithScopes.js
- src/generators/dom/index.js
- src/generators/dom/visitors/Component.js
- src/generators/dom/visitors/EachBlock.js
- src/generators/dom/visitors/Element.js
- src/generators/dom/visitors/attributes/addComponentAttributes.js
- src/generators/dom/visitors/attributes/addComponentBinding.js
- src/generators/dom/visitors/attributes/addElementAttributes.js
- src/generators/dom/visitors/attributes/binding/getSetter.js
- src/generators/server-side-rendering/index.js
- src/generators/server-side-rendering/visitors/Component.js
- src/generators/server-side-rendering/visitors/EachBlock.js
- src/generators/server-side-rendering/visitors/Element.js
- src/generators/shared/utils/counter.js
- src/parse/state/tag.js
- src/validate/js/propValidators/computed.js
- src/validate/js/propValidators/data.js
- src/validate/js/propValidators/methods.js
- src/validate/js/utils/checkForDupes.js
Split off as a separate more easily understood part of #400 / #401.
> Use maps and sets in many places instead of plain objects

- src/generators/dom/visitors/attributes/addComponentBinding.js
- test/generator/samples/component-binding-infinite-loop/A.html
- test/generator/samples/component-binding-infinite-loop/B.html
- test/generator/samples/component-binding-infinite-loop/C.html
- test/generator/samples/component-binding-infinite-loop/_config.js
- test/generator/samples/component-binding-infinite-loop/main.html
> prevent infinite loops caused by pathological component bindings

- package.json
- rollup/rollup.config.main.js
- rollup/rollup.config.ssr.js
> bundle magic-string

- src/generators/dom/visitors/attributes/lookup.js
- test/generator/samples/select-one-way-bind/_config.js
- test/generator/samples/select-one-way-bind/main.html
> Make <select> elements use .value prop to update value

- src/parse/read/expression.js
- test/generator/samples/attribute-prefer-expression/_config.js
- test/generator/samples/attribute-prefer-expression/main.html
> Prefer parsing as js expressions

- src/parse/read/directives.js
- test/parser/samples/error-binding-mustaches/error.json
- test/parser/samples/error-binding-mustaches/input.html
> better error for bind:value="{{foo}}"

- src/generators/dom/visitors/attributes/addElementBinding.js
- test/generator/samples/binding-input-number/_config.js
- test/generator/samples/binding-input-number/main.html
- test/generator/samples/binding-input-range/_config.js
- test/generator/samples/binding-input-range/main.html
> read values from range/number inputs as numbers

- src/generators/dom/visitors/Component.js
> dont generate intermediate data objects for components unnecessarily

- src/shared/methods.js
- test/generator/index.js
- test/generator/samples/observe-deferred/_config.js
- test/generator/samples/observe-deferred/main.html
> reverse pre and post to fix deferred observers

- src/generators/Generator.js
- src/generators/dom/visitors/Component/Component.js
- src/generators/dom/visitors/Element/EventHandler.js
- src/generators/dom/visitors/Element/meta/Window.js
- test/helpers.js
- test/runtime/index.js
Ref #465. Still a few tests to work through
> [WIP] catch hardcoded names that should be aliases

- src/generators/dom/visitors/Element/Attribute.js
- test/runtime/samples/attribute-namespaced/_config.js
- test/runtime/samples/attribute-namespaced/main.html
> replace all invalid characters in attribute names when creating variables

- src/generators/dom/visitors/Element/Element.js
- test/runtime/samples/binding-select-late/_config.js
- test/runtime/samples/binding-select-late/main.html
> update select value bindings at the end of the cycle

- src/generators/dom/visitors/Element/Element.js
- test/runtime/samples/binding-input-with-event/_config.js
- test/runtime/samples/binding-input-with-event/main.html
> ensure binding event handlers precede normal ones

- src/generators/Generator.js
- src/shared/dom.js
- test/runtime/samples/dev-warning-helper/_config.js
- test/runtime/samples/dev-warning-helper/main.html
> Don't treat helpers as dependencies

- test/runtime/samples/select-bind-array/_config.js
- test/runtime/samples/select-bind-array/main.html
just creating a PR out of this test so I can merge it into taylorzane:hotfix/initialize-select-element, and can't figure out how to do it on the command line... my git-fu is weak
> add failing test for bound select elements

- src/generators/dom/visitors/Component/Binding.js
- src/generators/dom/visitors/Element/Binding.js
- src/generators/dom/visitors/shared/binding/getSetter.js
- test/runtime/samples/binding-input-text-deconflicted/_config.js
- test/runtime/samples/binding-input-text-deconflicted/main.html
> Deconflict variable names used in binding event handlers

- src/generators/dom/visitors/Element/Binding.js
- test/runtime/samples/binding-input-checkbox-group-outside-each/_config.js
- test/runtime/samples/binding-input-checkbox-group-outside-each/main.html
> Correctly group checkbox inputs together

- src/generators/dom/visitors/EachBlock.js
- test/runtime/samples/each-block-dynamic-else-static/_config.js
> null out else block references when they are destroyed

- src/generators/dom/visitors/Element/Element.js
- test/runtime/samples/element-invalid-name/_config.js
- test/runtime/samples/element-invalid-name/main.html
> Replace invalid characters in element names when creating variables

- src/validate/html/validateElement.js
- test/runtime/samples/event-handler-destroy/_config.js
- test/runtime/samples/event-handler-destroy/main.html
- test/validator/samples/method-nonexistent-helper/errors.json
- test/validator/samples/method-nonexistent/errors.json
> include destroy as valid built-in method for event handlers

- src/generators/dom/preprocess.js
- test/runtime/samples/component-yield-follows-element/Foo.html
- test/runtime/samples/component-yield-follows-element/_config.js
- test/runtime/samples/component-yield-follows-element/main.html
Possibly not the most elegant fix possible, but it's short and it works.
> fix for #524

- src/validate/html/validateElement.js
- test/validator/samples/binding-input-checked/errors.json
- test/validator/samples/binding-input-checked/input.html
Will add a test for this later, just wanted to quickly get a PR up before I forget about it
> Provide second argument to validator.error with bind:checked errors

- src/generators/dom/index.js
- test/js/samples/collapses-text-around-comments/expected.js
> Always check whether we need to add CSS

- src/generators/dom/visitors/Element/addTransitions.js
- src/shared/transitions.js
- test/runtime/samples/transition-js-each-block-intro-outro/_config.js
- test/runtime/samples/transition-js-each-block-intro-outro/main.html
> abort intros before restarting them

- src/validate/html/validateElement.js
- src/validate/index.js
- src/validate/js/index.js
- test/validator/samples/transition-duplicate-in-transition/errors.json
- test/validator/samples/transition-duplicate-in-transition/input.html
- test/validator/samples/transition-duplicate-in/errors.json
- test/validator/samples/transition-duplicate-in/input.html
- test/validator/samples/transition-duplicate-out-transition/errors.json
- test/validator/samples/transition-duplicate-out-transition/input.html
- test/validator/samples/transition-duplicate-out/errors.json
- test/validator/samples/transition-duplicate-out/input.html
- test/validator/samples/transition-duplicate-transition-in/errors.json
- test/validator/samples/transition-duplicate-transition-in/input.html
- test/validator/samples/transition-duplicate-transition-out/errors.json
- test/validator/samples/transition-duplicate-transition-out/input.html
- test/validator/samples/transition-duplicate-transition/errors.json
- test/validator/samples/transition-duplicate-transition/input.html
- test/validator/samples/transition-missing/errors.json
- test/validator/samples/transition-missing/input.html
> validate transition directives

- src/shared/utils.js
Applies `for-loop` "tricks" for V8 -- although, I'm pretty sure this is also beneficial in other engines.
> Improve `utils.assign` performance

- src/generators/dom/visitors/EachBlock.ts
- test/js/samples/each-block-changed-check/_actual-bundle.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
> Fixed each block elements in wrong order after change. Fixes #610.

- src/generators/dom/visitors/Element/Binding.ts
- src/shared/dom.js
- test/runtime/samples/binding-input-number/_config.js
> coerce empty string in number/range inputs to undefined

- src/generators/dom/visitors/Element/EventHandler.ts
- test/runtime/samples/event-handler-sanitize/_config.js
- test/runtime/samples/event-handler-sanitize/main.html
> Sanitize event name in handler function name

- src/validate/html/validateElement.ts
- test/validator/samples/missing-component/input.html
- test/validator/samples/missing-component/warnings.json
This address #623, but we can leave the issue open so we don't forget to upgrade it to an error in v2
> warn on missing component

- src/generators/dom/visitors/Element/Attribute.ts
- src/validate/html/validateElement.ts
- test/runtime/samples/attribute-dynamic-type/_config.js
- test/runtime/samples/attribute-dynamic-type/main.html
- test/validator/samples/binding-input-static-type/errors.json
- test/validator/samples/binding-input-static-type/input.html
> only enforce static type if input is bound

- src/generators/dom/index.ts
- src/utils/deindent.ts
- test/runtime/samples/empty-style-block/_config.js
- test/runtime/samples/empty-style-block/main.html
> correctly handle empty <style> tag

- src/generators/dom/visitors/IfBlock.ts
- test/js/samples/if-block-no-update/expected-bundle.js
- test/js/samples/if-block-no-update/expected.js
- test/runtime/samples/component-nested-deeper/Level1.html
- test/runtime/samples/component-nested-deeper/Level2.html
- test/runtime/samples/component-nested-deeper/Level3.html
- test/runtime/samples/component-nested-deeper/_config.js
- test/runtime/samples/component-nested-deeper/main.html
See https://github.com/sveltejs/svelte/pull/644#issuecomment-309044521
> #643 redux

- src/generators/shared/processCss.ts
- test/css/samples/cascade-false-pseudo-element/_config.js
- test/css/samples/cascade-false-pseudo-element/expected.css
- test/css/samples/cascade-false-pseudo-element/input.html
> put attribute selector before pseudo-class selector

- src/generators/dom/visitors/IfBlock.ts
- test/runtime/samples/transition-js-if-block-in-each-block-bidi/_config.js
- test/runtime/samples/transition-js-if-block-in-each-block-bidi/main.html
> only run create() for new if blocks

- src/generators/dom/visitors/IfBlock.ts
- test/runtime/samples/transition-js-if-block-in-each-block-bidi-2/_config.js
- test/runtime/samples/transition-js-if-block-in-each-block-bidi-2/main.html
Fixes #667. Test is probably a bit more involved than it needs to be, but never mind
> pass params to get_block

- src/generators/dom/visitors/IfBlock.ts
- test/runtime/samples/transition-js-if-block-in-each-block-bidi-3/_config.js
- test/runtime/samples/transition-js-if-block-in-each-block-bidi-3/main.html
Fixes another weird transition bug
> don't recreate if_blocks incorrectly

- src/generators/Generator.ts
- src/generators/dom/index.ts
- src/generators/server-side-rendering/index.ts
- src/validate/index.ts
- test/helpers.js
- test/runtime/samples/deconflict-self/_config.js
- test/runtime/samples/deconflict-self/main.html
- test/runtime/samples/deconflict-self/nested/main.html
- test/runtime/samples/self-reference/_config.js
- test/server-side-rendering/index.js
> deconflict name with imports

- src/generators/dom/index.ts
- test/runtime/samples/transition-js-initial/_config.js
- test/runtime/samples/transition-js-initial/main.html
> run intro transitions on initial render

- src/generators/dom/index.ts
- test/runtime/index.js
> add dev mode hydration error

- package-lock.json
- package.json
- src/css/Stylesheet.ts
- test/helpers.js
- test/sourcemaps/index.js
- test/sourcemaps/samples/css-cascade-false/_config.js
- test/sourcemaps/samples/css-cascade-false/input.html
- test/sourcemaps/samples/css-cascade-false/output.css
- test/sourcemaps/samples/css-cascade-false/output.css.map
- test/sourcemaps/samples/css-cascade-false/test.js
Quick fix to improve the resolution of CSS sourcemaps
> better CSS sourcemaps

- src/generators/dom/preprocess.ts
- test/runtime/samples/whitespace-each-block/_config.js
- test/runtime/samples/whitespace-each-block/main.html
- test/runtime/samples/whitespace-normal/main.html
> don't strip whitespace at the end of an each block

- src/generators/dom/visitors/Element/Binding.ts
- test/js/samples/css-media-query/expected-bundle.js
- test/runtime/samples/select-bind-in-array/_config.js
- test/runtime/samples/select-bind-in-array/main.html
After fixing this [issue](https://github.com/sveltejs/svelte/issues/711) was broken binding in "each" block. This PR avoid new behavior for "each" block. 
New [issue](https://github.com/sveltejs/svelte/issues/724).
> Fix binding in each block

- src/generators/dom/visitors/Element/Ref.ts
- test/runtime/samples/ondestroy-before-cleanup/Top.html
- test/runtime/samples/ondestroy-before-cleanup/_config.js
- test/runtime/samples/ondestroy-before-cleanup/main.html
> clear refs in destroy, not unmount, so that refs are populated in ondestroy

- src/generators/dom/visitors/EachBlock.ts
- test/runtime/samples/each-block-static/_config.js
- test/runtime/samples/each-block-static/main.html
> call create() on new iterations of static each blocks

- src/css/Stylesheet.ts
- test/css/samples/media-query-word/expected.css
- test/css/samples/media-query-word/input.html
> preserve space before non-parenthesized media query expression

- src/generators/dom/visitors/Element/Binding.ts
- test/runtime/samples/binding-input-range-change/_config.js
- test/runtime/samples/binding-input-range-change/main.html
> bind to change events for range inputs, as well as input events

- src/css/Selector.ts
- src/css/Stylesheet.ts
- test/css/samples/cascade-false-keyframes-from-to/_config.js
- test/css/samples/cascade-false-keyframes-from-to/expected.css
- test/css/samples/cascade-false-keyframes-from-to/input.html
> smarter handling of keyframes

- src/generators/dom/index.ts
- src/generators/dom/visitors/Element/Attribute.ts
- src/interfaces.ts
- src/shared/dom.js
- test/js/index.js
- test/js/samples/legacy-input-type/_config.js
- test/js/samples/legacy-input-type/expected-bundle.js
- test/js/samples/legacy-input-type/expected.js
- test/js/samples/legacy-input-type/input.html
> add legacy option, use it for setInputType

- src/generators/dom/index.ts
- test/js/samples/collapses-text-around-comments/expected-bundle.js
- test/js/samples/collapses-text-around-comments/expected.js
- test/js/samples/computed-collapsed-if/expected-bundle.js
- test/js/samples/computed-collapsed-if/expected.js
- test/js/samples/css-media-query/expected-bundle.js
- test/js/samples/css-media-query/expected.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/event-handlers-custom/expected-bundle.js
- test/js/samples/event-handlers-custom/expected.js
- test/js/samples/if-block-no-update/expected-bundle.js
- test/js/samples/if-block-no-update/expected.js
- test/js/samples/if-block-simple/expected-bundle.js
- test/js/samples/if-block-simple/expected.js
- test/js/samples/legacy-input-type/expected-bundle.js
- test/js/samples/legacy-input-type/expected.js
- test/js/samples/non-imported-component/expected-bundle.js
- test/js/samples/non-imported-component/expected.js
- test/js/samples/onrender-onteardown-rewritten/expected-bundle.js
- test/js/samples/onrender-onteardown-rewritten/expected.js
- test/js/samples/setup-method/expected-bundle.js
- test/js/samples/setup-method/expected.js
- test/js/samples/use-elements-as-anchors/expected-bundle.js
- test/js/samples/use-elements-as-anchors/expected.js
> add `anchor` as an optional config param for initializing a component

- src/css/Stylesheet.ts
- test/css/samples/unused-selector-leading/_config.js
- test/css/samples/unused-selector-leading/expected.css
- test/css/samples/unused-selector-leading/expected.html
- test/css/samples/unused-selector-leading/input.html
> remove leading selectors safely

- src/validate/html/validateElement.ts
- test/validator/samples/transition-on-component/errors.json
- test/validator/samples/transition-on-component/input.html
> error if component has transition

- src/css/Stylesheet.ts
- test/css/samples/css-vars/expected.css
- test/css/samples/css-vars/input.html
> handle css vars in <style> tags

- src/css/Selector.ts
- test/css/samples/attribute-selector-unquoted/_config.js
- test/css/samples/attribute-selector-unquoted/expected.css
- test/css/samples/attribute-selector-unquoted/input.html
> handle unquoted attribute values

- src/generators/server-side-rendering/index.ts
- src/generators/server-side-rendering/interfaces.ts
- src/generators/server-side-rendering/visitors/Component.ts
- src/generators/server-side-rendering/visitors/Element.ts
- test/runtime/samples/component-slot-nested-component/Inner.html
- test/runtime/samples/component-slot-nested-component/Outer.html
- test/runtime/samples/component-slot-nested-component/_config.js
- test/runtime/samples/component-slot-nested-component/main.html
> stack up append targets so that slotted content in nested components works in SSR mode

- src/generators/dom/visitors/Component.ts
- test/runtime/samples/observe-binding-ignores-unchanged/Nested.html
- test/runtime/samples/observe-binding-ignores-unchanged/_config.js
- test/runtime/samples/observe-binding-ignores-unchanged/main.html
> prevent mutation bug from incorrectly calling observer

- src/generators/dom/index.ts
- src/shared/index.js
- test/runtime/samples/dev-warning-missing-data-binding/_config.js
- test/runtime/samples/dev-warning-missing-data/_config.js
- test/runtime/samples/dev-warning-readonly-computed/_config.js
- test/runtime/samples/dev-warning-readonly-window-binding/_config.js
> use component name in runtime dev warnings

- src/generators/dom/visitors/Element/Binding.ts
- test/js/samples/input-without-blowback-guard/expected-bundle.js
- test/js/samples/input-without-blowback-guard/expected.js
- test/js/samples/input-without-blowback-guard/input.html
> remove redundant input blowback guard

- src/shared/dom.js
- test/js/samples/media-bindings/expected-bundle.js
> Change let -> var, solves #838

- src/generators/dom/visitors/Element/Binding.ts
Cherry-picking 687acf77330ba3a0132c1b9df78fdf9abb6646f1 from #837
> Add parenthesis around or'd expression

- src/generators/dom/preprocess.ts
- test/runtime/samples/svg-each-block-anchor/_config.js
- test/runtime/samples/svg-each-block-anchor/main.html
> don't use skipped text nodes as anchors

- src/generators/dom/index.ts
- test/js/samples/css-shadow-dom-keyframes/_config.js
- test/js/samples/css-shadow-dom-keyframes/expected-bundle.js
- test/js/samples/css-shadow-dom-keyframes/expected.js
- test/js/samples/css-shadow-dom-keyframes/input.html
> escape shadow DOM CSS

- src/generators/dom/Block.ts
- test/js/samples/collapses-text-around-comments/expected-bundle.js
- test/js/samples/collapses-text-around-comments/expected.js
- test/js/samples/css-media-query/expected-bundle.js
- test/js/samples/css-media-query/expected.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
- test/js/samples/event-handlers-custom/expected-bundle.js
- test/js/samples/event-handlers-custom/expected.js
- test/js/samples/inline-style-optimized-multiple/expected-bundle.js
- test/js/samples/inline-style-optimized-multiple/expected.js
- test/js/samples/inline-style-optimized-url/expected-bundle.js
- test/js/samples/inline-style-optimized-url/expected.js
- test/js/samples/inline-style-optimized/expected-bundle.js
- test/js/samples/inline-style-optimized/expected.js
- test/js/samples/inline-style-unoptimized/expected-bundle.js
- test/js/samples/inline-style-unoptimized/expected.js
- test/js/samples/input-without-blowback-guard/expected-bundle.js
- test/js/samples/input-without-blowback-guard/expected.js
- test/js/samples/legacy-input-type/expected-bundle.js
- test/js/samples/legacy-input-type/expected.js
- test/js/samples/legacy-quote-class/expected-bundle.js
- test/js/samples/legacy-quote-class/expected.js
- test/js/samples/media-bindings/expected-bundle.js
- test/js/samples/media-bindings/expected.js
> remove incorrect argument

- src/generators/dom/visitors/Element/Element.ts
Ref #866
This seems like a reasonable solution, not really sure how to unit test this though.
> do not use self-closing tags in .innerHTML

- src/generators/dom/index.ts
- test/custom-elements/index.js
- test/custom-elements/samples/escaped-css/main.html
- test/custom-elements/samples/escaped-css/test.js
> escape backslashes in CSS for custom elements

- src/css/Stylesheet.ts
- test/css/samples/unknown-at-rule/expected.css
- test/css/samples/unknown-at-rule/input.html
fixes #871. Turns out to be a bit more a special case than I thought, but I don't see any harm in it.
> handle unknown at-rules that are declaration-like

- src/generators/dom/preprocess.ts
- src/generators/server-side-rendering/visitors/EachBlock.ts
- test/runtime/samples/each-block-destructured-array/_config.js
Add dependencies for destructuredContexts
Fixes #896
> Destructure each updates

- .gitignore
- src/generators/dom/preprocess.ts
- test/hydration/samples/each-block-arg-clash/_after.html
- test/hydration/samples/each-block-arg-clash/_before.html
- test/hydration/samples/each-block-arg-clash/_config.js
- test/hydration/samples/each-block-arg-clash/main.html
> Use a block scoped unique name for the context solves #911

- src/shared/index.js
- test/js/samples/collapses-text-around-comments/expected-bundle.js
- test/js/samples/component-static/expected-bundle.js
- test/js/samples/computed-collapsed-if/expected-bundle.js
- test/js/samples/css-media-query/expected-bundle.js
- test/js/samples/css-shadow-dom-keyframes/expected-bundle.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/event-handlers-custom/expected-bundle.js
- test/js/samples/if-block-no-update/expected-bundle.js
- test/js/samples/if-block-simple/expected-bundle.js
- test/js/samples/inline-style-optimized-multiple/expected-bundle.js
- test/js/samples/inline-style-optimized-url/expected-bundle.js
- test/js/samples/inline-style-optimized/expected-bundle.js
- test/js/samples/inline-style-unoptimized/expected-bundle.js
- test/js/samples/input-without-blowback-guard/expected-bundle.js
- test/js/samples/legacy-input-type/expected-bundle.js
- test/js/samples/legacy-quote-class/expected-bundle.js
- test/js/samples/media-bindings/expected-bundle.js
- test/js/samples/non-imported-component/expected-bundle.js
- test/js/samples/onrender-onteardown-rewritten/expected-bundle.js
- test/js/samples/setup-method/expected-bundle.js
- test/js/samples/use-elements-as-anchors/expected-bundle.js
- test/runtime/samples/component-binding-self-destroying/Nested.html
- test/runtime/samples/component-binding-self-destroying/_config.js
- test/runtime/samples/component-binding-self-destroying/main.html
> check component exists after _bind before continuing

- src/generators/dom/preprocess.ts
- src/generators/dom/visitors/Element/Element.ts
- src/generators/server-side-rendering/preprocess.ts
- test/runtime/samples/binding-select-implicit-option-value/_config.js
- test/runtime/samples/binding-select-implicit-option-value/main.html
- test/runtime/samples/binding-select-initial-value-undefined/_config.js
- test/runtime/samples/binding-select-initial-value/_config.js
- test/runtime/samples/binding-select-late/_config.js
- test/runtime/samples/binding-select/_config.js
> Reuse <option> children as value attribute, if there isn't one

- src/parse/state/mustache.ts
- src/utils/reservedNames.ts
- test/validator/samples/each-block-invalid-context-destructured/errors.json
- test/validator/samples/each-block-invalid-context-destructured/input.html
- test/validator/samples/each-block-invalid-context/errors.json
- test/validator/samples/each-block-invalid-context/input.html
> throw error on illegal context

- src/generators/dom/visitors/AwaitBlock.ts
- test/runtime/samples/await-then-catch-anchor/_config.js
- test/runtime/samples/await-then-catch-anchor/main.html
- test/runtime/samples/await-then-catch-if/_config.js
- test/runtime/samples/await-then-catch-if/main.html
> Fix #974 and #975

- README.md
> add brunch plugin

- src/parse/index.ts
> Remove unnecessary 'const' assignment

- src/generators/server-side-rendering/index.ts
- test/js/samples/ssr-no-oncreate-etc/expected-bundle.js
- test/js/samples/ssr-no-oncreate-etc/expected.js
- test/server-side-rendering/index.js
> fix toString method in SSR output

- src/generators/dom/Block.ts
- src/generators/nodes/AwaitBlock.ts
- src/generators/nodes/EachBlock.ts
- src/generators/nodes/Element.ts
- test/runtime/samples/await-then-catch-event/_config.js
- test/runtime/samples/await-then-catch-event/main.html
> fix data references in event handlers inside await-then-catch

- README.md
Mention svelte-hot-loader in the Readme
> Add svelte-hot-loader to the Tools section

- src/generators/nodes/AwaitBlock.ts
- test/runtime/samples/await-component-oncreate/Foo.html
- test/runtime/samples/await-component-oncreate/_config.js
- test/runtime/samples/await-component-oncreate/main.html
Ref #1061. Between this and #1093 we might have everything covered.
> fire oncreate handlers for components inside await blocks

- package.json
- test/runtime/index.js
- yarn.lock
Hopefully fixes the part of #1127 that I can from the code side. The other questions about CI behavior etc. remain.
> update jsdom; update `window.performance.now` test shim

- src/generators/nodes/Attribute.ts
- src/generators/nodes/Binding.ts
- src/generators/nodes/Element.ts
- src/validate/html/validateElement.ts
- test/js/samples/media-bindings/expected-bundle.js
- test/js/samples/media-bindings/expected.js
- test/js/samples/media-bindings/input.html
- test/runtime/samples/binding-audio-currenttime-duration-volume/_config.js
- test/runtime/samples/binding-audio-currenttime-duration-volume/main.html
- test/runtime/samples/binding-audio-currenttime-duration/main.html
Fixes #1143 
Sorry about the multiple tiny commits, please feel free to squash when merging.
> Add audio video volume binding

- src/css/Stylesheet.ts
- src/index.ts
- test/css/samples/cascade-false-empty-rule-dev/_config.js
- test/css/samples/cascade-false-empty-rule-dev/expected.css
- test/css/samples/cascade-false-empty-rule-dev/input.html
- test/css/samples/cascade-false-empty-rule/_config.js
- test/css/samples/cascade-false-empty-rule/input.html
> remove empty style blocks in prod mode

- src/generators/nodes/Component.ts
- test/runtime/samples/store-component-binding/TextInput.html
- test/runtime/samples/store-component-binding/_config.js
- test/runtime/samples/store-component-binding/main.html
> component store bindings

- src/generators/nodes/Component.ts
- test/runtime/samples/store-component-binding-deep/TextInput.html
- test/runtime/samples/store-component-binding-deep/_config.js
- test/runtime/samples/store-component-binding-deep/main.html
- test/runtime/samples/store-component-binding-each/Widget.html
- test/runtime/samples/store-component-binding-each/_config.js
- test/runtime/samples/store-component-binding-each/main.html
Ref #1100. Turns out #1153 wasn't a complete solution; it didn't handle deep bindings. Just a failing test for now
> Deep component store bindings

- src/generators/nodes/IfBlock.ts
- test/js/samples/if-block-no-update/expected-bundle.js
- test/js/samples/if-block-no-update/expected.js
- test/runtime/samples/if-block-else-in-each/_config.js
- test/runtime/samples/if-block-else-in-each/main.html
Fixes #1195 the cheap and easy way. But we should circle back around and clean up some stuff here.
> Fix select_block_type scoping issue

- src/generators/dom/Block.ts
- test/runtime/samples/deconflict-component-refs/_config.js
- test/runtime/samples/deconflict-component-refs/main.html
fixes #1213 (and with it https://github.com/sveltejs/svelte.technology/issues/214)
> prevent context variables being called component or state

- test/runtime/samples/each-block-array-literal/_config.js
- test/runtime/samples/each-block-array-literal/main.html
> failing test for #1217

- src/shared/transitions.js
- test/runtime/samples/transition-css-duration/_config.js
- test/runtime/samples/transition-css-duration/main.html
> scale transition duration by delta

- README.md
- src/generators/server-side-rendering/visitors/Comment.ts
- src/interfaces.ts
- test/js/samples/ssr-preserve-comments/_config.js
- test/js/samples/ssr-preserve-comments/expected-bundle.js
- test/js/samples/ssr-preserve-comments/expected.js
- test/js/samples/ssr-preserve-comments/input.html
Re: #1265
This pull request adds that option, docs, and a simple test.
> Add option preserve comments in SSR rendering.

- src/shared/transitions.js
> only delete applicable transition animations

- src/generators/nodes/EachBlock.ts
- test/runtime/samples/each-block-keyed-static/_config.js
- test/runtime/samples/each-block-keyed-static/main.html
> allow keyed each block to have static content

- src/generators/nodes/EachBlock.ts
- test/runtime/samples/each-block-keyed-empty/_config.js
- test/runtime/samples/each-block-keyed-empty/main.html
Addendum to #1292. Edge case, but currently causes an error
> handle empty each blocks

- src/generators/nodes/Component.ts
> fix duplicated line

- src/css/Selector.ts
- test/css/samples/spread/_config.js
- test/css/samples/spread/expected.css
- test/css/samples/spread/input.html
> bail out of CSS optimisations on encountering spread

- src/css/Selector.ts
- test/css/samples/omit-scoping-element-uppercase/_config.js
- test/css/samples/omit-scoping-element-uppercase/expected.css
- test/css/samples/omit-scoping-element-uppercase/expected.html
- test/css/samples/omit-scoping-element-uppercase/input.html
> make CSS DCE case-insensitive

- src/validate/html/validateElement.ts
- test/validator/samples/binding-select-multiple-dynamic/errors.json
- test/validator/samples/binding-select-multiple-dynamic/input.html
> fail validation if bound <select> has dynamic multiple attribute

- src/generators/Generator.ts
- src/generators/dom/Block.ts
- src/generators/dom/index.ts
- test/runtime/samples/component-name-deconflicted/Nested.html
- test/runtime/samples/component-name-deconflicted/_config.js
- test/runtime/samples/component-name-deconflicted/main.html
> deconflict against inherited contexts

- src/parse/state/tag.ts
- test/runtime/samples/script-style-non-top-level/main-v2.html
> in v2, don't parse for interpolations in non-root style elements

- README.md
> removes depreciated svelte-hot-loader

- src/compile/nodes/EachBlock.ts
- test/js/samples/deconflict-builtins/expected-bundle.js
- test/js/samples/deconflict-builtins/expected.js
- test/js/samples/each-block-changed-check/expected-bundle.js
- test/js/samples/each-block-changed-check/expected.js
> recalculate each block values lazily

- src/compile/nodes/EventHandler.ts
- src/compile/nodes/shared/Expression.ts
- src/utils/flattenReference.ts
- test/runtime/samples/event-handler-custom-this/_config.js
- test/runtime/samples/event-handler-custom-this/main.html
> overwrite this in custom event handlers

- src/Stats.ts
- src/index.ts
- test/stats/index.js
- test/stats/samples/hooks/_config.js
> Return consistently-shaped `stats` object

- src/shared/dom.js
- test/js/samples/bind-width-height/expected-bundle.js
Just ran into a bug with the new dimension bindings. This fixes it
> allow destruction of components with bind:offsetWidth etc

- src/compile/nodes/Element.ts
- test/runtime/samples/refs-no-innerhtml/_config.js
- test/runtime/samples/refs-no-innerhtml/main.html
> mark elements with refs as ineligible for innerhtml

- src/compile/nodes/AwaitBlock.ts
- src/shared/await-block.js
- test/runtime/samples/transition-js-await-block/_config.js
- test/runtime/samples/transition-js-await-block/main.html
Fixes #956. This PR includes #1418
> Allow transitions in await blocks

- src/utils/getStaticAttributeValue.ts
- test/runtime/samples/spread-element-input/_config.js
- test/runtime/samples/spread-element-input/main.html
fixes a bug that popped up in Gitter earlier
> allow spread props on elements with tests for static attributes

- src/utils/globalWhitelist.ts
Should fix https://github.com/sveltejs/svelte/issues/1441
(I couldn't find any tests related to this, let me know if there are any…)
> Add `Promise` to whitelisted globals

- README.md
Add parcel builder. I also though the list was getting a bit unwieldy so I've separated it into sections, feel free to rejig, rename or recombine them.
> Add parcel-plugin to list of tools, categories

- src/shared/transitions.js
- test/runtime/samples/transition-js-args/_config.js
- test/runtime/samples/transition-js-args/main.html
This includes #1448 and #1451 — the actual commit is https://github.com/sveltejs/svelte/commit/b5931b95d41785bdeffd7f814a599e93918813b6. Part of #1431
> Transition args

- src/compile/nodes/Component.ts
- src/compile/nodes/Element.ts
- src/compile/nodes/Slot.ts
- src/utils/quoteIfNecessary.ts
- test/runtime/samples/component-slot-name-with-hyphen/Nested.html
- test/runtime/samples/component-slot-name-with-hyphen/_config.js
- test/runtime/samples/component-slot-name-with-hyphen/main.html
> quote slot names if necessary

- src/compile/nodes/Component.ts
https://github.com/sveltejs/svelte/issues/1433
> Fix  <svelte:component> spread error for #1433

- package.json
- yarn.lock
Hopefully fixes #1404. Let's take a look at those CI results...
> update tiny-glob to fix tests not running on Windows

- src/compile/dom/index.ts
- src/compile/nodes/Element.ts
- test/runtime/samples/transition-js-intro-skipped-by-default-nested/Widget.html
- test/runtime/samples/transition-js-intro-skipped-by-default-nested/_config.js
- test/runtime/samples/transition-js-intro-skipped-by-default-nested/main.html
> nested components skip intro on initial render

- src/compile/dom/index.ts
- test/runtime/samples/if-block-component-without-outro/Widget.html
- test/runtime/samples/if-block-component-without-outro/_config.js
- test/runtime/samples/if-block-component-without-outro/main.html
> always create outro method for top-level block

- src/css/Stylesheet.ts
- src/utils/isKeyframesNode.ts
- test/css/samples/keyframes-autoprefixed/expected.css
- test/css/samples/keyframes-autoprefixed/input.html
Don't know if it's the best implementation, but fixes #1504
> Make the compiler also transform prefixed @keyframes

- src/validate/html/validateEventHandler.ts
- test/validator/samples/method-nonexistent-helper/warnings.json
- test/validator/samples/method-nonexistent/warnings.json
- test/validator/samples/window-event-invalid/warnings.json
Add `refs.*` to the event handler callee warning message
> [![image.png](https://files.gitter.im/sveltejs/svelte/WKO4/thumb/image.png)](https://files.gitter.im/sveltejs/svelte/WKO4/image.png)
> Add refs.* to valid event handler callees warning message

- appveyor.yml
> Update node version 6 => 8 for sucrase

- src/compile/nodes/Component.ts
- src/shared/ssr.js
> provide more helpful error if SSR component tries to render non-SSR component

- src/compile/nodes/IfBlock.ts
- test/runtime/samples/if-block-no-outro-else-with-outro/Widget.html
- test/runtime/samples/if-block-no-outro-else-with-outro/_config.js
- test/runtime/samples/if-block-no-outro-else-with-outro/main.html
Failing test and fix for #1589
> Fixes #1589

- .travis.yml
- README.md
- appveyor.yml
- package-lock.json
> tweak readme, use npm ci

- src/parse/read/context.ts
- test/parser/samples/each-block-destructured/output.json
Simple fix to add end position to object and array patterns
> add end position to object and array patterns

- src/cli/compile.ts
- test/cli/samples/amd/command.sh
- test/cli/samples/amd/expected/Main.js
- test/cli/samples/amd/src/Main.html
Though this is a fairly simple change, I'll work on adding a failing test.
> Properly propagate amdId to the compiler

- src/compile/nodes/EachBlock.ts
- test/runtime/samples/transition-js-nested-each-keyed-2/Widget.html
- test/runtime/samples/transition-js-nested-each-keyed-2/_config.js
- test/runtime/samples/transition-js-nested-each-keyed-2/main.html
> Fixes keyed each blocks for outro

- src/compile/nodes/Element.ts
- test/runtime/samples/class-shortcut-with-class/_config.js
- test/runtime/samples/class-shortcut-with-class/main.html
- test/runtime/samples/class-shortcut/main.html
> Fixes shorthand class directives which do not have classes

- src/compile/render-dom/wrappers/IfBlock.ts
- test/runtime/samples/if-block-elseif-no-else/_config.js
- test/runtime/samples/if-block-elseif-no-else/main.html
Glad I caught this one before releasing 2.13.6...
> Handle elseif blocks with no else

- src/compile/render-dom/wrappers/Head.ts
- test/runtime/samples/head-if-block/_config.js
- test/runtime/samples/head-if-block/main.html
> fix blocks inside <svelte:head>

- src/parse/index.ts
- src/parse/state/tag.ts
- test/parser/samples/attribute-containing-solidus/input.html
- test/parser/samples/attribute-containing-solidus/output.json
> include solidus in attribute values

- src/compile/render-dom/wrappers/EachBlock.ts
- test/runtime/samples/each-block-index-only/_config.js
- test/runtime/samples/each-block-index-only/main.html
> detach each block iterations with no update method

- src/compile/render-dom/wrappers/Element/index.ts
- src/compile/render-dom/wrappers/Head.ts
- test/js/index.js
- test/js/samples/action/expected.js
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/js/samples/use-elements-as-anchors/expected.js
- test/js/samples/window-binding-scroll/expected.js
i managed to disable an entire category of tests and didn't realise for a month
can't believe they let me program
> reinstate tests

- src/Stats.ts
- src/compile/index.ts
- test/stats/samples/props/_config.js
- test/stats/samples/props/input.html
> expose stats.props

- src/compile/render-dom/wrappers/Window.ts
> fix: #1859 (multiple window bindings not supported)

- site/src/routes/repl/_components/Output/index.html
- site/src/routes/repl/_components/Repl.html
- site/static/workers/compiler.js
> show compiled CSS separately

- src/compile/render-dom/Block.ts
- test/runtime/samples/hash-in-attribute/_config.js
- test/runtime/samples/hash-in-attribute/main.html
Fixes the links in the guide's sidebar
> only apply aliasing logic once

- src/compile/render-dom/wrappers/Element/index.ts
- test/js/samples/bind-width-height/expected.js
> use correct context for resize handler

- src/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/binding-this-and-value/_config.js
- test/runtime/samples/binding-this-and-value/main.html
> don't lump in `bind:this` with everything else

- src/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/binding-input-text-contextual-deconflicted/_config.js
- test/runtime/samples/binding-input-text-contextual-deconflicted/main.html
> make event handler names unique across components

- package-lock.json
- package.json
- src/compile/Component.ts
- test/runtime/samples/store-auto-subscribe-in-script/_config.js
- test/runtime/samples/store-auto-subscribe-in-script/main.html
> allow reactive store references anywhere in script

- src/compile/nodes/EventHandler.ts
- src/compile/nodes/shared/Expression.ts
- src/compile/render-dom/wrappers/AwaitBlock.ts
- src/compile/render-dom/wrappers/Document.ts
- src/compile/render-dom/wrappers/EachBlock.ts
- src/compile/render-dom/wrappers/Element/Binding.ts
- src/compile/render-dom/wrappers/Element/index.ts
- src/compile/render-dom/wrappers/IfBlock.ts
- src/compile/render-dom/wrappers/InlineComponent/index.ts
- src/compile/render-dom/wrappers/Title.ts
- src/compile/render-dom/wrappers/shared/Tag.ts
- src/compile/render-dom/wrappers/shared/addActions.ts
- src/compile/render-dom/wrappers/shared/addEventHandlers.ts
- test/runtime/samples/each-block-function/_config.js
- test/runtime/samples/each-block-function/main.html
> render functions that close over contextual data

- src/internal/animations.js
- src/internal/style_manager.js
> fix transitions

- src/compile/render-dom/wrappers/Window.ts
- test/runtime/samples/window-binding-multiple-handlers/_config.js
- test/runtime/samples/window-binding-multiple-handlers/main.html
> fix malformed code in window binding event handlers

- package-lock.json
- package.json
- src/parse/acorn.ts
- src/parse/read/expression.ts
- src/parse/read/script.ts
> upgrade Acorn

- src/compile/render-dom/wrappers/AwaitBlock.ts
- test/runtime/samples/await-containing-if/_config.js
- test/runtime/samples/await-containing-if/main.html
should fix #1939. 'should' because i couldn't quite reproduce the bug as originally stated
> set parent correctly for children of await blocks

- site/content/guide/08-bindings.md
`value=name` --> `value={name}`
> Syntax error on element binding example

- src/compile/render-dom/wrappers/Window.ts
- test/js/samples/window-binding-scroll/expected.js
> fix scroll bindings

- src/compile/nodes/InlineComponent.ts
- test/validator/samples/prop-slot/errors.json
- test/validator/samples/prop-slot/input.html
> disallow `slot` as a prop name in inline components

- src/compile/Component.ts
- src/compile/index.ts
- test/runtime/samples/deconflict-component-name-with-module-global/_config.js
- test/runtime/samples/deconflict-component-name-with-module-global/main.html
> deconflict with globals referenced in module context

- src/compile/Component.ts
- test/runtime/samples/prop-without-semicolon-b/_config.js
- test/runtime/samples/prop-without-semicolon-b/main.html
> insert semicolon where necessary when initing props

- store.mjs
> Ensure derive behaves consistently.

- src/compile/Component.ts
- src/compile/render-dom/index.ts
- src/compile/render-ssr/index.ts
- test/runtime/samples/reactive-values-implicit/_config.js
- test/runtime/samples/reactive-values-implicit/main.html
- test/stats/samples/implicit-reactive/_config.js
- test/stats/samples/implicit-reactive/input.html
> inject lets for reactive declarations where necessary

- src/compile/Component.ts
- test/runtime/samples/reactive-values-non-cyclical/_config.js
- test/runtime/samples/reactive-values-non-cyclical/main.html
- test/validator/samples/reactive-declaration-cyclical/errors.json
- test/validator/samples/reactive-declaration-cyclical/input.html
> better cyclical dependency detection

- src/compile/render-dom/wrappers/Slot.ts
- src/compile/render-ssr/handlers/Element.ts
- src/compile/render-ssr/handlers/Slot.ts
- src/utils/get_slot_data.ts
- src/utils/stringify_attribute.ts
- test/runtime/samples/component-slot-let-static/Nested.html
- test/runtime/samples/component-slot-let-static/_config.js
- test/runtime/samples/component-slot-let-static/main.html
> enclose text/compound slot attributes in backticks

- site/src/routes/blog/index.svelte
My feed reader couldn't find the RSS feed. This fixed it.
> Add rss <link> to blog

- src/compile/Component.ts
- src/compile/wrapModule.ts
- src/interfaces.ts
> remove eval format

- site/content/examples/7guis-crud/App.svelte
- site/content/examples/7guis-flight-booker/App.svelte
> fix two examples

- store.mjs
- test/store/index.js
> add second argument to writable

- src/compile/Component.ts
- src/compile/render-dom/index.ts
- src/compile/render-ssr/index.ts
- test/runtime/samples/props-implicit/_config.js
- test/runtime/samples/props-implicit/main.svelte
- test/runtime/samples/props-undeclared/_config.js
- test/runtime/samples/props-undeclared/main.svelte
> handle implicit and explicit-but-undefined props

- src/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/component-slot-nested-in-element/One.svelte
- test/runtime/samples/component-slot-nested-in-element/Two.svelte
- test/runtime/samples/component-slot-nested-in-element/_config.js
- test/runtime/samples/component-slot-nested-in-element/main.svelte
fixes #2031, and supersedes #2032
> assign elements to correct block when slots are involved

- package.json
- src/compile/Component.ts
- src/compile/nodes/shared/Expression.ts
- src/compile/render-dom/index.ts
- src/compile/render-dom/wrappers/Element/index.ts
- src/compile/render-dom/wrappers/InlineComponent/index.ts
- src/compile/render-ssr/index.ts
- src/interfaces.ts
- src/internal/utils.js
- src/utils/__test__.ts
- src/utils/deindent.ts
- test/runtime/samples/store-auto-subscribe-immediate-multiple-vars/_config.js
- test/runtime/samples/store-auto-subscribe-immediate-multiple-vars/main.svelte
- test/runtime/samples/store-auto-subscribe-immediate/_config.js
- test/runtime/samples/store-auto-subscribe-immediate/main.svelte
- test/runtime/samples/store-resubscribe/_config.js
- test/runtime/samples/store-resubscribe/main.svelte
Somewhat more convoluted than I would have liked, but this fixes #2015
> Initialise store values immediately

- src/cli/compile.ts
Fixes #2112.
Just as I was submitting this, I saw that the CLI tests are currently skipped, with a comment `// TODO figure out what to do with the CLI`. (This explains why CI wasn't failing.) I guess I have a lot of mixed feelings about what to do with the CLI in v3.
> cli: don't pass invalid `sourceMap` option, and display warnings

- src/compile/Component.ts
- src/compile/render-ssr/index.ts
- src/utils/annotateWithScopes.ts
- test/runtime/samples/store-imported-module-b/_config.js
- test/runtime/samples/store-imported-module-b/foo.js
- test/runtime/samples/store-imported-module-b/main.svelte
- test/runtime/samples/store-imported-module/_config.js
- test/runtime/samples/store-imported-module/foo.js
- test/runtime/samples/store-imported-module/main.svelte
- test/runtime/samples/store-imported/_config.js
- test/runtime/samples/store-imported/foo.js
- test/runtime/samples/store-imported/main.svelte
> fix initialisation of imported stores

- README.md
Adding a Bazel example to the list of starter projects
> add bazel sample repo

- src/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/component-slot-named-c/Nested.svelte
- test/runtime/samples/component-slot-named-c/_config.js
- test/runtime/samples/component-slot-named-c/main.svelte
#2124. I *think* this is the correct fix?
> fix slot block lineage

- src/parse/state/mustache.ts
- test/parser/samples/if-block-elseif/input.svelte
- test/parser/samples/if-block-elseif/output.json
- test/runtime/samples/dynamic-component-slot/main.svelte
- test/runtime/samples/if-block-elseif-no-else/main.svelte
- test/runtime/samples/if-block-elseif-text/main.svelte
- test/runtime/samples/if-block-elseif/main.svelte
- test/runtime/samples/if-block-outro-nested-else/main.svelte
- test/runtime/samples/transition-js-if-elseif-block-outro/main.svelte
fixes #2137. Just getting the PR ready in case the voting keeps going the way it's going. `:else if` current leads `:elseif` 7:3
https://www.strawpoll.me/17510302
> change :elseif to :else if

- src/compile/nodes/EventHandler.ts
- test/runtime/samples/event-handler-destructured/_config.js
- test/runtime/samples/event-handler-destructured/main.svelte
> allow event handlers to come from destructured var declarations

- src/compile/Component.ts
- test/runtime/samples/reactive-values-self-dependency-b/_config.js
- test/runtime/samples/reactive-values-self-dependency-b/main.svelte
> tweak semantics of reactive statements

- src/compile/render-dom/wrappers/InlineComponent/index.ts
got this backwards, and it's breaking https://v3.svelte.technology/tutorial/svelte-self
> fix svelte:self

- site/static/workers/bundler.js
Fixes #2208. Also updates version of Rollup used to 1.x.
> REPL: better "could not resolve module" error

- src/compile/render-dom/Block.ts
> deconflict fragment method aliases with other identifiers

- src/compile/render-dom/wrappers/Element/index.ts
- test/runtime/samples/binding-input-checkbox-deep-contextual-b/_config.js
- test/runtime/samples/binding-input-checkbox-deep-contextual-b/main.svelte
> maintain context for contextual binding handlers

- src/compile/nodes/shared/Expression.ts
- src/compile/render-dom/wrappers/InlineComponent/index.ts
- src/compile/render-dom/wrappers/Slot.ts
- src/compile/render-dom/wrappers/shared/get_context_merger.ts
- src/internal/utils.js
- test/runtime/samples/component-slot-let-d/Nested.svelte
- test/runtime/samples/component-slot-let-d/_config.js
- test/runtime/samples/component-slot-let-d/main.svelte
Ref #2163. This is going to be a bit of a brain-bender I think. For now, just fixing some semi-related stuff along the way
> Interpret `changed` inside slotted content

- src/internal/style_manager.js
fixes #2053. Not quite sure how to write a test for this, so i'm just going to gloss over that bit
> only clear out stylesheet after removing a specific animation

- src/internal/transitions.js
- test/runtime/samples/transition-js-deferred-b/_config.js
- test/runtime/samples/transition-js-deferred-b/main.svelte
fixes #2159. Took an embarrassing amount of time to figure what the problem was here.
> call deferred transition function at correct time

- site/src/components/Repl/Input/ComponentSelector.svelte
- site/src/components/Repl/Output/CompilerOptions.svelte
- site/src/components/Repl/Output/index.svelte
- site/src/components/Repl/index.svelte
> rebundle on new file, recompile on option change

- src/internal/ssr.js
- test/runtime/samples/context-api-b/Leaf.svelte
- test/runtime/samples/context-api-b/Nested.svelte
- test/runtime/samples/context-api-b/_config.js
- test/runtime/samples/context-api-b/main.svelte
> set/unset parent component correctly in SSR

- src/compile/Component.ts
- test/runtime/samples/store-assignment-updates/_config.js
- test/runtime/samples/store-assignment-updates/main.svelte
fixes #2170. Quite chuffed with this implementation, thought it was going to be a lot more involved
> update stores when assigning to store values

- site/src/server.js
Fixes #2221. This seems like The Correct way to do it.
> site: serve static assets with allow origin '*'

- src/compile/render-dom/index.ts
- test/js/samples/computed-collapsed-if/expected.js
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/runtime/samples/prop-accessors/_config.js
- test/runtime/samples/prop-accessors/main.svelte
Fixes #2262. I do want to write some runtime tests before this gets merged in.
> Fix getter/setter inclusion logic

- src/compile/render-dom/index.ts
- test/runtime/samples/props-reactive/Nested.svelte
- test/runtime/samples/props-reactive/_config.js
- test/runtime/samples/props-reactive/main.svelte
> allow reactive declarations to only depend on $$props

- site/src/components/Repl/Output/Viewer.svelte
> remove old style tags when updating components

- src/compile/Component.ts
> suppress $props is not defined warning

- site/src/components/Repl/index.svelte
> Change input of a component when click on an error message

- src/compile/nodes/shared/Expression.ts
- test/runtime/samples/event-handler-each-context-invalidation/_config.js
- test/runtime/samples/event-handler-each-context-invalidation/main.svelte
> invalidate correctly inside event handlers

- site/src/routes/repl/index.svelte
> site: tidy repl example loading and fix race condition

- src/compile/Component.ts
- test/vars/samples/actions/_config.js
- test/vars/samples/actions/input.svelte
- test/vars/samples/animations/_config.js
- test/vars/samples/animations/input.svelte
- test/vars/samples/transitions/_config.js
- test/vars/samples/transitions/input.svelte
Fixes #2294 
Fixes https://github.com/sveltejs/eslint-plugin-svelte3/issues/5
> note action/etc. references even when hoistable

- site/src/routes/repl/index.svelte
> Fix zen mode REPL nav CSS

- src/compile/render-dom/wrappers/Slot.ts
- test/runtime/samples/transition-js-slot/Nested.svelte
- test/runtime/samples/transition-js-slot/_config.js
- test/runtime/samples/transition-js-slot/main.svelte
> play transitions in slots

- src/compile/render-dom/wrappers/EachBlock.ts
- test/runtime/samples/array-literal-spread-deopt/_config.js
- test/runtime/samples/array-literal-spread-deopt/main.svelte
> skip array literal length optimization in presence of spread

- site/content/docs/03-run-time.md
Because the site probably shouldn't deploy links to `localhost:3000`.
> docs: remove hardcoded localhost link from API

- site/content/docs/03-run-time.md
> docs: "proeprties" -> "properties"

- site/content/docs/04-compile-time.md
> Fix typos in doc node-sass example

- site/content/docs/03-run-time.md
Changed in f3cb540ce6f7e49fdba2c58540254df6dd42e8b4 (first brought up in #2296), but the docs got missed.
> docs: fix incorrect readable store

- .gitignore
- site/scripts/get-contributors.js
- site/src/routes/index.svelte
fixes #2329. Loading the homepage:
* before — 127 requests, 5.0Mb
* after — 41 requests, 494kb
> use spritesheet for contributors

- site/src/routes/docs/index.svelte
> Site: sections anchors fix

- site/src/routes/docs/_sections.js
- site/src/routes/docs/index.svelte
> Don't update the active section for headings above level 3

- src/compile/nodes/Element.ts
- test/runtime/samples/svg-foreignobject-namespace/_config.js
> apply namespace to foreignObject correctly

- src/compile/css/Stylesheet.ts
remove_css_prefox => remove_css_prefix
> Fix typo remove_css_prefox

- site/content/docs/02-template-syntax.md
- site/content/docs/03-run-time.md
- site/src/routes/docs/index.svelte
- site/src/utils/markdown.js
> Site: code blocks formatting

- site/src/components/Repl/ReplWidget.svelte
- site/src/routes/repl/index.svelte
> repl: use absolute svelteUrl to fix version=local

- site/content/tutorial/05-events/03-event-modifiers/text.md
> Add link to Mozilla docs about events bubbling and capture phase

- site/content/docs/01-component-format.md
- site/src/routes/docs/_GuideContents.svelte
- site/src/routes/docs/_sections.js
- site/src/routes/docs/index.svelte
Fixes #2389 
Here's the sidebar with the current level-4 headings compared to the current sidebar: it is 50% taller, not bad I think.
The numbered bullet point in the sidebar seems a bit weird to me so it could be converted to a normal list, but it's probably a matter of taste :)
> Site: sidebar level-4 headings.

- src/compile/nodes/Binding.ts
- test/validator/samples/binding-let/errors.json
- test/validator/samples/binding-let/input.svelte
> better error for bindings to let: values

- src/compile/render-dom/index.ts
- test/js/samples/css-shadow-dom-keyframes/expected.js
> skip observedAttributes where appropriate

- src/compile/render-dom/wrappers/Slot.ts
- test/hydration/index.js
- test/hydration/samples/text-fallback/Nested.svelte
- test/hydration/samples/text-fallback/_after.html
- test/hydration/samples/text-fallback/_before.html
- test/hydration/samples/text-fallback/main.svelte
> only create fallback content if no slot is provided

- src/compile/render-dom/wrappers/InlineComponent/index.ts
- test/runtime/samples/deconflict-value/Widget.svelte
- test/runtime/samples/deconflict-value/_config.js
- test/runtime/samples/deconflict-value/main.svelte
> deconflict `value` argument in component bindings

- site/src/routes/_components/WhosUsingSvelte.svelte
> Fix broken "your company?" link

- src/compile/Component.ts
- src/compile/nodes/Element.ts
- src/compile/nodes/Slot.ts
- src/compile/render-dom/Renderer.ts
- src/compile/render-dom/index.ts
- src/compile/render-dom/wrappers/Element/index.ts
- src/compile/render-dom/wrappers/Slot.ts
- src/compile/render-ssr/handlers/Element.ts
- src/compile/render-ssr/handlers/Slot.ts
- src/compile/utils/get_slot_data.ts
- test/runtime/samples/component-slot-named-inherits-default-lets/Nested.svelte
- test/runtime/samples/component-slot-named-inherits-default-lets/_config.js
- test/runtime/samples/component-slot-named-inherits-default-lets/main.svelte
> Expose default slot values to named slots

- site/src/routes/repl/embed.svelte
> reinstate /repl/embed

- src/compile/render-dom/wrappers/shared/create_debugging_comment.ts
- test/runtime/samples/component-slot-empty-b/Nested.svelte
- test/runtime/samples/component-slot-empty-b/_config.js
- test/runtime/samples/component-slot-empty-b/main.svelte
> Fix creation of debugging comment for elements without children

- site/content/docs/02-template-syntax.md
- site/content/tutorial/04-logic/05-keyed-each-blocks/text.md
- src/compile/render-dom/wrappers/EachBlock.ts
- src/internal/keyed-each.js
- test/js/samples/each-block-keyed-animated/expected.js
- test/js/samples/each-block-keyed/expected.js
- test/runtime/samples/each-block-keyed-object-identity/_config.js
- test/runtime/samples/each-block-keyed-object-identity/main.svelte
> Use Map for keyed each block lookups

- site/content/tutorial/02-reactivity/04-updating-arrays-and-objects/text.md
> typo in tutorial

- site/src/routes/blog/[slug].json.js
- site/src/routes/blog/[slug].svelte
> site: fix handling of non-existent blog posts

- site/content/blog/2016-11-26-frameworks-without-the-framework.md
- site/content/blog/2017-08-07-the-easiest-way-to-get-started.md
- site/content/blog/2017-09-06-the-zen-of-just-writing-css.md
- site/content/blog/2017-12-31-sapper-towards-the-ideal-web-app-framework.md
- site/content/blog/2018-04-18-version-2.md
- site/content/blog/2018-12-26-svelte-css-in-js.md
- site/content/blog/2018-12-27-virtual-dom-is-pure-overhead.md
- site/content/blog/2019-01-31-svelte-on-the-changelog.md
- site/content/blog/2019-04-16-svelte-for-new-developers.md
- site/src/routes/blog/_posts.js
- site/src/routes/blog/index.json.js
> placeholder for svelte-for-new-developers blog post

- site/content/blog/2019-04-15-setting-up-your-editor.md
> placeholder for setting-up-your-editor blog post

- site/src/routes/_components/WhosUsingSvelte.svelte
> target="_blank" for Whos Using

- site/src/components/TopNav.svelte
- site/src/routes/_components/Blurb.svelte
- site/src/routes/_components/WhosUsingSvelte.svelte
- site/src/routes/blog/[slug].svelte
- site/src/routes/blog/index.svelte
- site/src/routes/docs/_GuideContents.svelte
- site/src/routes/docs/index.svelte
- site/src/routes/examples/_TableOfContents.svelte
- site/src/routes/index.svelte
- site/src/routes/tutorial/[slug]/_TableOfContents.svelte
- site/src/routes/tutorial/[slug]/index.svelte
- site/static/global.css
- site/static/icons/edit.svg
> makes links a bit more obvious, per #2445. also tweaks some /blog css

- site/src/components/PreloadingIndicator.svelte
- site/src/routes/_layout.svelte
fixes #2449. Like any preloading indicator it's basically complete fiction, but it's a better experience than just hanging there
> add a preloading indicator

- site/src/routes/examples/_TableOfContents.svelte
Also simplifies the markup a bit
> fix opacity on examples TOC

- site/src/routes/docs/_sections.js
- site/src/utils/markdown.js
- site/src/utils/slug.js
Transform section titles with the same processor used for content headers
> site: API docs, slugify section titles the same way as content headers

- site/content/tutorial/06-bindings/11-bind-this/text.md
Fixes broken link: `tutorials/onmount` -> `tutorial/onmount`
Broken Link on: https://svelte.dev/tutorial/bind-this
Links to: https://svelte.dev/tutorial/onmount
Small change that I noticed while reading through the tutorial and figured I would fix.
> Fix: Broken Link 

- README.md
> Add missing dot.

- site/content/tutorial/18-debugging/01-debug/text.md
> Added comma; after "Occasionally"

- site/content/tutorial/10-transitions/04-custom-css-transitions/text.md
- site/content/tutorial/18-debugging/01-debug/text.md
> Update text.md, line 34

- site/src/routes/docs/index.svelte
> Fix the shadow in docs sidebar

- site/content/blog/2017-08-07-the-easiest-way-to-get-started.md
since the front page links to this slightly out of date blogpost - i copied over and updated instructions so otherse wont be as confused as i was...
this is unsolicited so feel freee to reject or modify as you wish
> [updating docs] update quick start instructions

- site/content/tutorial/17-module-context/01-sharing-code/text.md
no reason to pause everything when only one can be playing
> simpler, more efficient example

- site/src/template.html
> Site: set initial-scale=1.0 on the viewport

- README.md
`npm run update` script should be executed before dev site will be run.
> add `npm run update` command

- site/content/tutorial/14-composition/04-slot-props/text.md
_as_ you like it...
Sorry no tests for this one.
----
> For want of a word... A PR of exactly three characters, one being a space. 

- site/src/components/InlineSvg.svelte
- site/src/routes/repl/_components/AppControls/index.svelte
- site/src/routes/repl/index.svelte
- site/src/utils/compat.js
> Site: REPL, use the gist or example title in the page title

- site/content/docs/01-component-format.md
> Hint at the reactivity limitation of array methods in the api docs

- site/src/routes/docs/_GuideContents.svelte
- site/src/routes/examples/_TableOfContents.svelte
- site/src/routes/tutorial/[slug]/_TableOfContents.svelte
- site/src/routes/tutorial/[slug]/index.svelte
- site/static/global.css
> Consistent sidebars 2641

- site/content/tutorial/08-stores/02-auto-subscriptions/text.md
> clarify autosubscription scope requirement

- src/compile/utils/scope.ts
- test/runtime/samples/dev-warning-missing-data-binding/main.svelte
- test/runtime/samples/dev-warning-missing-data-component/Foo.svelte
> Fix determining which props need a value in dev mode

- site/content/docs/03-run-time.md
I don't know if this is correct, but it works for me and this is better than nothing.
> Add barebones description of `svelte/register`

- src/compile/render-dom/index.ts
- test/runtime/samples/instrumentation-auto-subscription-self-assignment/_config.js
- test/runtime/samples/instrumentation-auto-subscription-self-assignment/main.svelte
> fix instrumentation of auto-subscription self-assignments

- src/compile/Component.ts
- test/runtime/samples/binding-input-text-contextual-reactive/_config.js
- test/runtime/samples/binding-input-text-contextual-reactive/main.svelte
> invalidate dependencies of reactive declarations

- store.mjs
- test/store/index.js
> use safe_not_equal logic for derived stores

- README.md
Minimal, but just correcting the brand :)
> Update Visual Studio Code brand

- site/content/docs/01-component-format.md
Resolves #2559. Maybe this should also be mentioned in the tutorial though?
> site: document export-as

- README.md
> Added npm and license indicators to README

- site/content/tutorial/01-introduction/03-dynamic-attributes/text.md
Being an attribute, alt should be mentioned as such.
> Replace tag with attribute for alt

- site/content/examples/10-animations/00-animate/App.svelte
I think we need lint `.svelte` file
> Remove whitespace at end of line

- README.md
This MR fixes link to license in README.md and removes trailing tab.
> Fix link to license

- site/src/routes/_components/WhosUsingSvelte.svelte
- site/static/organisations/thunderdome.svg
Open source Agile Planning Poker Tool built using Svelte for the UI, and websockets/go for the backend.  Great showcase of Reactive functionality.
> Add Thunderdome Link to Who's Using

- site/content/docs/02-template-syntax.md
> Add @debug API documentation

- src/internal/animations.js
- src/internal/loop.js
- src/internal/transitions.js
- src/internal/utils.js
- src/motion/spring.js
- src/motion/tweened.js
- test/runtime/index.js
- test/runtime/samples/spring/_config.js
- test/runtime/samples/spring/main.svelte
- test/server-side-rendering/index.js
> ensure spring works server-side

- src/store.ts
- test/store/index.ts
- test/test.js
> handle non-falsy non-function deriver return values

- site/content/blog/2017-08-07-the-easiest-way-to-get-started.md
> Fix setup command in getting started blog

- site/content/docs/02-template-syntax.md
> docs: multiple event listeners on single node

- README.md
update read me added yarn commands and https clone
> update clone with https

- src/store.ts
Fixes https://github.com/sveltejs/svelte/issues/2867
> Additional detail to jsdocs for writable, readable, & derived

- package.json
Fixes #2874 by publishing dist
> publish dist in order to get types

- src/compile/render-dom/Block.ts
- src/compile/render-dom/wrappers/Head.ts
- src/compile/render-dom/wrappers/IfBlock.ts
- src/compile/render-dom/wrappers/RawMustacheTag.ts
- test/runtime/samples/head-if-else-block/_config.js
- test/runtime/samples/head-if-else-block/main.svelte
- test/runtime/samples/head-if-else-raw-dynamic/_config.js
- test/runtime/samples/head-if-else-raw-dynamic/main.svelte
- test/runtime/samples/head-raw-dynamic/Bar.svelte
- test/runtime/samples/head-raw-dynamic/Foo.svelte
- test/runtime/samples/head-raw-dynamic/_config.js
- test/runtime/samples/head-raw-dynamic/main.svelte
Fixed problem with replacing header content if <svelte: head> starts or ends {@html}. #2805  #2438 
{@html} will always be wrapped in `<noscript>` tags in the head.
Also repaired {#if} detaching the block in the head.
> repair dynamic {@html} in head

- src/compile/render-dom/index.ts
- test/js/samples/debug-empty/expected.js
- test/js/samples/debug-foo-bar-baz-things/expected.js
- test/js/samples/debug-foo/expected.js
- test/js/samples/dev-warning-missing-data-computed/expected.js
- test/runtime/samples/dev-warning-unknown-props-with-$$props/Foo.svelte
- test/runtime/samples/dev-warning-unknown-props-with-$$props/_config.js
- test/runtime/samples/dev-warning-unknown-props-with-$$props/main.svelte
- test/runtime/samples/dev-warning-unknown-props-with-$$scope/Foo.svelte
- test/runtime/samples/dev-warning-unknown-props-with-$$scope/_config.js
- test/runtime/samples/dev-warning-unknown-props-with-$$scope/main.svelte
> dont create unknown prop warnings for $$scope etc, or if component has $$props

- package.json
- src/animate.ts
- src/easing.ts
- src/internal/animations.ts
- src/internal/dom.ts
- src/internal/loop.ts
- src/internal/ssr.ts
- src/internal/style_manager.ts
- src/internal/transitions.ts
- src/internal/utils.ts
- src/motion/spring.ts
- src/motion/tweened.ts
- src/motion/utils.ts
- src/transition.ts
- added more types for exported apis: `animate`, `easing`, `transition`, `motion` and `internal`
- added `compiler` typings to list of published files in npm package
> improve typings

- site/content/docs/03-run-time.md
The slide example on the docs is using the `fly` animation, where it should use the `slide` animation.
> docs: fix slide example

- src/compiler/compile/render-dom/wrappers/EachBlock.ts
- src/compiler/compile/render-dom/wrappers/Element/index.ts
> Outro in ForEach is always wrapped in if(local) fixing #2689

- site/src/routes/_components/WhosUsingSvelte.svelte
- site/static/organisations/strixcloud.svg
1. We were using Svelte start from v1. 
2. Currently, we are still on v2 because our project not so small. 
3. Yes, technically our company name different but other parts of the company working on totally different things. 
4. I am using "add-yourself" class because I need extra text and vertical alignment. 
Thanks.
> Add strixcloud logo.

- src/compiler/compile/render-dom/wrappers/Element/index.ts
- src/runtime/internal/animations.ts
follow-up fix to #2871
Sorry, I accidentially committed into master, so I provide a new pull request with the stashed changes.
> follow-up fix to #2871

- .travis.yml
- package.json
> Explicitly support node 8+

- package.json
Mistake made in #2970
Caught by @shinnn
> Fix engine range

- site/content/tutorial/02-reactivity/04-updating-arrays-and-objects/text.md
The "Updating arrays and objects" tutorial contains a comment about "assignments to *properties* of arrays and objects". This pull request adds code that shows how it could be applied to the given example.
> Tutorial: Add implementation for the given tutorial example

- src/compiler/compile/render-dom/wrappers/Title.ts
- test/runtime/samples/head-title-empty/_config.js
- test/runtime/samples/head-title-empty/main.svelte
> allow empty <title> tags

- src/compiler/parse/state/tag.ts
- test/parser/samples/attribute-with-whitespace/input.svelte
- test/parser/samples/attribute-with-whitespace/output.json
> Allow whitespace after = in attributes

- src/compiler/compile/index.ts
Fix for #2843.
I'd add the regression test but I didn't find any existing tests for the compiler, and would like some guidance here.
> Improve file name to component name conversion

- src/compiler/compile/utils/scope.ts
- test/runtime/samples/destructuring-assignment-array/_config.js
- test/runtime/samples/destructuring-assignment-array/main.svelte
> handle member expressions in destructuring assignments

- .eslintrc.json
- package.json
- src/compiler/compile/Component.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/nbsp-div/_config.js
I realised this wasn't already part of the build script so i doubt anyone will remember to run it either.
Better we have it in the build, automatically run.
> add lint to build script

- src/compiler/compile/Component.ts
- test/runtime/samples/reactive-value-function-hoist-b/_config.js
- test/runtime/samples/reactive-value-function-hoist-b/main.svelte
> always bail out of hoisting on encountering local state

- src/runtime/store/index.ts
- test/store/index.ts
> only call subscriber once for writable with callback

- src/compiler/utils/names.ts
per https://github.com/sveltejs/svelte/pull/3098#issuecomment-505294330
> add a few more known globals

- src/compiler/compile/nodes/EventHandler.ts
- test/runtime/samples/event-handler-shorthand-sanitized/_config.js
- test/runtime/samples/event-handler-shorthand-sanitized/main.svelte
> sanitize names of automatically-bubbled events

- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- test/runtime/samples/dynamic-component-nulled-out-intro/_config.js
- test/runtime/samples/dynamic-component-nulled-out-intro/main.svelte
> check for existence of switch instance before introing

- site/content/tutorial/04-logic/05-keyed-each-blocks/text.md
The text in the button is "Remove first thing".
> change "item" to "thing"

- site/content/docs/02-template-syntax.md
> Docs: duplicate slug fix

- src/compiler/compile/css/Selector.ts
- test/css/samples/not-selector/expected.css
- test/css/samples/not-selector/input.svelte
> add scoping attribute for pseudo-class selectors without a type/class

- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- test/runtime/index.js
- test/runtime/samples/await-in-removed-if/_config.js
- test/runtime/samples/await-in-removed-if/main.svelte
fixes #1496. not gonna lie, the way await blocks are implemented scares me a little bit, but this seems to cover all the bases without introducing a ton of new code
> prevent await block mounting inside removed if block

- src/runtime/internal/ssr.ts
- test/runtime/samples/binding-circular/_config.js
- test/runtime/samples/binding-circular/main.svelte
> handle circular values when rendering bindings

- src/compiler/compile/nodes/shared/Expression.ts
- test/runtime/samples/shorthand-method-in-template/Foo.svelte
- test/runtime/samples/shorthand-method-in-template/_config.js
- test/runtime/samples/shorthand-method-in-template/main.svelte
> correctly transform inline shorthand methods

- site/src/routes/tutorial/[slug]/index.svelte
> removed bottom padding to center button text

- src/compiler/compile/nodes/shared/Expression.ts
- test/runtime/samples/component-slot-let-in-binding/Nested.svelte
- test/runtime/samples/component-slot-let-in-binding/_config.js
- test/runtime/samples/component-slot-let-in-binding/main.svelte
> Pass context used in bindings down to slots

- site/content/docs/01-component-format.md
- site/content/docs/03-run-time.md
First stab at clearing some of this stuff up. I'm a bit nervous about dropping all these 'must's on someone so early in the API docs, but I'm not sure where else this belongs. Feedback welcome.
> site: document store contract

- src/compiler/compile/css/Stylesheet.ts
- test/css/samples/global-keyframes-with-no-elements/expected.css
- test/css/samples/global-keyframes-with-no-elements/input.svelte
> Fix global keyframes with no elements

- site/content/docs/03-run-time.md
Added descriptors for set and update methods of the return object of writable in svelte/store.
Addresses issue #3194 regarding the documentation.
> Update 03-run-time.md (Issue #3194)

- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- test/runtime/samples/spread-reuse-levels/Nested.svelte
- test/runtime/samples/spread-reuse-levels/_config.js
- test/runtime/samples/spread-reuse-levels/main.svelte
> reuse unchanged spread levels

- src/compiler/compile/render_dom/index.ts
- test/runtime/samples/props-reactive-b/_config.js
- test/runtime/samples/props-reactive-b/main.svelte
> always update reactive declarations with $$props

- src/runtime/internal/environment.ts
Fixes #3324. I'm not sure what kind of test would make sense for this. I probably won't personally break this again, but a test might still be warranted.
> make raf a noop on server

- src/compiler/compile/nodes/EachBlock.ts
- test/validator/samples/undefined-value/input.svelte
- test/validator/samples/undefined-value/warnings.json
> don't warn when using each index in key

- src/compiler/compile/render_dom/wrappers/RawMustacheTag.ts
- src/runtime/internal/dom.ts
- test/js/samples/each-block-changed-check/expected.js
- test/runtime/samples/each-block-keyed-html-b/_config.js
- test/runtime/samples/each-block-keyed-html-b/main.svelte
fixes the bug in the second repro in #2711 (the other two were fixed by #3329)
> correctly set mount anchor for HTML tags

- test/runtime/samples/component-slot-binding-dimensions-destroys-cleanly/Nested.html
- test/runtime/samples/component-slot-binding-dimensions-destroys-cleanly/_config.js
- test/runtime/samples/component-slot-binding-dimensions-destroys-cleanly/main.html
> Failing test for #1844

- src/compiler/compile/Component.ts
- src/compiler/compile/render_dom/wrappers/Slot.ts
- test/runtime/samples/component-slot-let-f/A.svelte
- test/runtime/samples/component-slot-let-f/B.svelte
- test/runtime/samples/component-slot-let-f/_config.js
- test/runtime/samples/component-slot-let-f/main.svelte
> Assume let variables are dynamic in slots

- .gitignore
- mocha.coverage.opts
Fixes [#3391](https://github.com/sveltejs/svelte/issues/3391)
> Fix travis test coverage

- site/content/docs/02-template-syntax.md
This was explained in the tutorial: https://svelte.dev/tutorial/spread-props But I could not find any documentation on it.
> Document $$props

- src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts
- test/runtime/samples/spread-component-literal/Widget.svelte
- test/runtime/samples/spread-component-literal/_config.js
- test/runtime/samples/spread-component-literal/main.svelte
> generate valid code when spreading literal into props

- rollup.config.js
> Inline estree-walker type definitions in compiler.d.ts

- site/content/examples/03-logic/04-keyed-each-blocks/App.svelte
- site/content/examples/03-logic/04-keyed-each-blocks/Thing.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/app-a/App.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/app-a/Thing.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/app-b/App.svelte
- site/content/tutorial/04-logic/05-keyed-each-blocks/app-b/Thing.svelte
> better keyed each example

- site/src/routes/apps/index.json.js
- site/src/routes/apps/index.svelte
Enable navigation to the next page of apps.
> Fix offset and next page link

- src/compiler/compile/render_dom/wrappers/Element/StyleAttribute.ts
- test/runtime/samples/inline-style-optimisation-bailout/_config.js
- test/runtime/samples/inline-style-optimisation-bailout/main.svelte
> bail out of style tag optimisation when appropriate

- src/compiler/compile/render_dom/wrappers/AwaitBlock.ts
- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- test/js/samples/if-block-no-update/expected.js
- test/runtime/samples/await-conservative-update/_config.js
- test/runtime/samples/await-conservative-update/main.svelte
- test/runtime/samples/await-conservative-update/sleep.js
- test/runtime/samples/if-block-conservative-update/_config.js
- test/runtime/samples/if-block-conservative-update/main.svelte
- test/runtime/samples/if-block-else-conservative-update/_config.js
- test/runtime/samples/if-block-else-conservative-update/main.svelte
WIP — this is actually slightly tricky...
> more conservative if block updates

- src/compiler/compile/Component.ts
- test/runtime/samples/reactive-value-function/_config.js
- test/runtime/samples/reactive-value-function/main.svelte
> mark reassigned/mutated values as non-hoistable

- site/src/routes/_components/WhosUsingSvelte.svelte
- site/static/organisations/buydotstar.svg
Svelte really helped us create our website for buy.* quickly.  Coming from mainly using angular on a daily basis, svelte was a breath of fresh air.  It was easy to get going and a pleasure to use.  I look forward to contributing to this project.
Our website https://buydotstar.com was made to help our users get to the products they want at the right price quickly, promote the goods of others, and give to charity.  As with any website it will be ever evolving but I am glad such a tool exists to make that task easier, thank you.
> Add buydotstar logo

- site/content/examples/05-bindings/10-bind-this/App.svelte
- In https://svelte.dev/examples#bind-this removed superfluous code
> Remove unnecessary code in "bind-this" example

- src/compiler/compile/render_dom/wrappers/Text.ts
- src/runtime/internal/dom.ts
This brings the hydration `claim` code more in-line with what the `create` code does.
> Introduce a `claim_space` helper

- src/compiler/compile/render_dom/wrappers/Element/Binding.ts
> alternative fix for #3426

- package-lock.json
- src/runtime/transition/index.ts
> Added a blur transition

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/js/samples/media-bindings/expected.js
fixes #3524. No test, since I'm not sure what a test would look like
> robustify bind:currentTime

- src/compiler/compile/utils/invalidate.ts
- test/runtime/samples/store-unreferenced/Nested.svelte
- test/runtime/samples/store-unreferenced/_config.js
- test/runtime/samples/store-unreferenced/main.svelte
- test/runtime/samples/store-unreferenced/store.js
> invalidate store values in <script> block

- site/content/tutorial/04-logic/05-keyed-each-blocks/text.md
Fix inconsistency with the app
> Fix a typo

- site/package-lock.json
- site/package.json
Need new props from site-kit's last version
> bump @sveltejs/site-kit version

- site/content/blog/2019-04-15-setting-up-your-editor.md
Here the shortened solution without the extraneous plugin.
> Doc: update file-type association instructions for Atom

- site/content/examples/05-bindings/08-media-elements/App.svelte
Seeking was happening regardless of if a drag was happening
> FIXED: Media Elements Example

- site/content/examples/05-bindings/08-media-elements/App.svelte
- site/content/tutorial/06-bindings/10-media-elements/app-a/App.svelte
- site/content/tutorial/06-bindings/10-media-elements/app-b/App.svelte
Seeking was being caused on the mousemove event, regardless of if the mouse was actually dragging or not
> FIXED: Media Elements Tutorial

- src/compiler/compile/Component.ts
- src/compiler/compile/render_dom/wrappers/DebugTag.ts
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/shared/create_debugging_comment.ts
- src/compiler/compile/render_ssr/handlers/DebugTag.ts
Fix `// TODO this does the same as component.locate! remove one or the other`
> remove Component.locator

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- test/runtime/samples/if-block-compound-outro-no-dependencies/_config.js
- test/runtime/samples/if-block-compound-outro-no-dependencies/main.svelte
Fixes #3595. I have no idea how to convey this succinctly and clearly. Adds tests which currently fail on master.
> fix obscure compound if bug

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/Slot.ts
> produce better code for <slot/>

- site/src/routes/tutorial/[slug]/index.svelte
Make 'Show Me' stand out a bit to reduce the confusion mentioned in #2452.
> reduce confusion mentioned in #2452

- site/src/routes/repl/[id]/_components/AppControls/index.svelte
> site: add REPL imports to .zip's pkg.devDependencies

- site/content/docs/02-template-syntax.md
> Document bind:playbackRate in the API documentation. Closes #3806.

- src/compiler/parse/read/style.ts
- test/validator/samples/invalid-empty-css-declaration/errors.json
- test/validator/samples/invalid-empty-css-declaration/input.svelte
> error on empty css declarations

- site/content/tutorial/16-special-elements/07-svelte-options/app-a/Todo.svelte
- site/content/tutorial/16-special-elements/07-svelte-options/app-b/Todo.svelte
> Minor tutorial fix

- src/compiler/compile/render_dom/wrappers/shared/Tag.ts
should have used `changed(dependencies)`
> use changed(dependencies)

- src/compiler/compile/utils/get_name_from_filename.ts
> feat: support unicode filenames

- test/runtime/samples/await-then-blowback-reactive/Widget.svelte
- test/runtime/samples/await-then-blowback-reactive/_config.js
- test/runtime/samples/await-then-blowback-reactive/main.svelte
Should close #3858 
This test case is a simpler version of the REPL code from the issue. Thanks for the review by the way.
> add await blowback reactive test case

- site/content/tutorial/09-motion/01-tweened/text.md
robertpenner.com seems to be offline, but I went through an archived version to find a live link of a javascript implementation that has the same license on it
> #3864: Update Penner easing functions link

- site/content/tutorial/02-reactivity/04-updating-arrays-and-objects/text.md
- src/runtime/transition/index.ts
Proposition to fix the tutorial as stated on the issue sveltejs#3861
> site/tutorials - Added extra explanation for object reactivity

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/unchanged-expression-escape/_config.js
- test/runtime/samples/unchanged-expression-escape/main.svelte
Fixing https://github.com/sveltejs/svelte/issues/3911
> fix text content escape html

- site/content/examples/20-7guis/05-7guis-crud/App.svelte
I tried to update an item after searching, however the change applied gets reflected in another item. This change will allow to update the intended item correctly.
> Fix crud example update error after searching

- site/content/blog/2019-04-16-svelte-for-new-developers.md
Marking this as a draft because there's some tidying up I'd like to do on sveltejs/template first. Feedback welcome in the meantime
> add blog post

- site/content/examples/00-introduction/02-styling/App.svelte
- site/content/examples/00-introduction/03-nested-components/App.svelte
- site/content/examples/04-events/05-dom-event-forwarding/FancyButton.svelte
- site/content/examples/99-embeds/20181225-blog-svelte-css-in-js/styles.js
- site/content/tutorial/01-introduction/04-styling/app-b/App.svelte
- site/content/tutorial/01-introduction/04-styling/text.md
- site/content/tutorial/01-introduction/05-nested-components/app-a/App.svelte
- site/content/tutorial/01-introduction/05-nested-components/app-b/App.svelte
- site/content/tutorial/05-events/06-dom-event-forwarding/app-a/FancyButton.svelte
- site/content/tutorial/05-events/06-dom-event-forwarding/app-b/FancyButton.svelte
> site: add font fallback for Comic Sans MS

- src/compiler/compile/render_dom/index.ts
- test/runtime/samples/dev-warning-missing-data-function/_config.js
- test/runtime/samples/dev-warning-missing-data-function/main.svelte
Fix https://github.com/sveltejs/svelte/issues/3954
> no missing prop warning for non-writable props

- site/src/routes/_components/WhosUsingSvelte.svelte
- site/static/organisations/paperform.svg
> Adding Paperform logo

- src/compiler/compile/Component.ts
- test/validator/samples/unreferenced-variables/input.svelte
> fix warnings for props that are only used as stores

- src/compiler/compile/create_module.ts
Fixes #4050. No test for now - I'm not immediately sure where that should go or how one would look.
> fix bare imports in `format: 'cjs'` mode

- src/compiler/compile/index.ts
Use `Array.includes()` to check for the existence of an element.
> chore(refactor): Minor code refactoring

- site/content/docs/03-run-time.md
Fix https://github.com/sveltejs/svelte/issues/4137
> Fix wrong link to tweend

- site/content/tutorial/12-actions/01-actions/text.md
Update of tutorial page 12.a making it match with "Show me" result
> tutorial 12.a inconsistency fix

- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/js/samples/media-bindings/expected.js
- test/js/samples/video-bindings/expected.js
- test/runtime/samples/apply-directives-in-order/_config.js
- test/runtime/samples/apply-directives-in-order/main.svelte
I rebased https://github.com/sveltejs/svelte/pull/2737 to the latest master, 
since it has conflicts with the master.
hopefully this get merge soon
> FIX #2446: apply bindings and event handlers in order

- test/server-side-rendering/index.js
Similar to https://github.com/sveltejs/svelte/commit/41d955c23e3f25c413650510c7d3b90db5ee4f9b, this writes the compiled output for `ssr` into the `_output` folder as well.
> write ssr compiled output to disk for easier inspection

- site/src/routes/repl/[id]/index.json.js
When running in dev mode, this makes requests to `/repl[id].json` (other than those loading built-in examples) proxy to the real svelte.dev server, rather than trying to access the database. I think this makes sense as a default. Any thoughts?
> site: in dev mode, proxy /repl/[id].json requests to real server

- site/src/routes/_components/Contributors.svelte
- site/src/routes/index.svelte
Add a `<Contributors/>` component and use it in the website.
> Add a Contributors component

- site/content/docs/01-component-format.md
Fixes #2571. I'd love feedback on whether this seems like a reasonable way to explain this - and in particular on whether I'm on track with the call-the-subscription-function-right-away gotcha.
> site: document Observable interop

- site/content/docs/01-component-format.md
> Adds documentation for global keyframes

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/hydration/samples/each-else/_after.html
- test/hydration/samples/each-else/_before.html
- test/hydration/samples/each-else/main.svelte
Fix https://github.com/sveltejs/svelte/issues/4202
> fix hydrating each else

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- src/runtime/internal/keyed_each.ts
- test/runtime/samples/keyed-each-dev-unique/_config.js
- test/runtime/samples/keyed-each-dev-unique/main.svelte
Closes #4301. Exact error message subject to bikeshedding.
> disallow duplicate each keys in dev mode

- README.md
Fixes https://github.com/sveltejs/svelte/issues/4333
> Remove npm module size badge from Readme

- register.js
Quick fix to address #4364. Do we need tests for this? Fancier formatting?
> Log warnings in svelte/register when in dev-mode (sveltejs#4364)

- src/compiler/compile/render_dom/wrappers/IfBlock.ts
Fixes https://github.com/sveltejs/svelte/pull/4507#issuecomment-594987580
Fixes https://github.com/sveltejs/svelte/issues/4263
> fix lazy code breaks in build

- site/content/docs/03-run-time.md
> fix: self close

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- test/runtime/samples/each-block-keyed-else/_config.js
- test/runtime/samples/each-block-keyed-else/main.svelte
- test/runtime/samples/each-block-unkeyed-else-2/_config.js
- test/runtime/samples/each-block-unkeyed-else-2/main.svelte
https://github.com/sveltejs/svelte/pull/4413 added dirty check for each block.
Need to include the else case in the dirty check as well
This fixes #4536 and fixes #4549.
> Fix else-block update in keyed each-block

- src/compiler/compile/render_dom/wrappers/Slot.ts
- test/runtime/samples/component-slot-fallback-3/Inner.svelte
- test/runtime/samples/component-slot-fallback-3/_config.js
- test/runtime/samples/component-slot-fallback-3/main.svelte
> fix didnt deconflict the variable names

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/shared/create_debugging_comment.ts
- test/runtime/samples/component-slot-fallback-4/Inner.svelte
- test/runtime/samples/component-slot-fallback-4/_config.js
- test/runtime/samples/component-slot-fallback-4/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/4565
> fix create debugging comment for comment

- site/content/tutorial/10-transitions/05-custom-js-transitions/text.md
Instead of placing magic numbers around, I feel this should better portray what this is.
> Make text node type more explicit

- src/compiler/compile/render_dom/wrappers/Slot.ts
- test/runtime/samples/slot-if-block-update-no-anchor/_config.js
- test/runtime/samples/slot-if-block-update-no-anchor/main.svelte
> fix node anchor

- src/compiler/compile/render_dom/wrappers/IfBlock.ts
#4629 fix
untested
update : it works
> if_block exists check missing in block.p

- site/content/docs/00-introduction.md
Fixes https://github.com/sveltejs/svelte/issues/2494
Option B is to link it from the FAQ but I think this is a pretty reasonable place to expect to find it.
> add v2 docs link

- CONTRIBUTING.md
> added punctuation where its missing

- site/content/docs/02-template-syntax.md
Added information about key without index syntax #4700
> Docs/template-syntax, Keyed each blocked without index (issue #4700)

- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-img-redundant-alt/input.svelte
> Fix img-reduntant-alt bug (Breaking)

- CHANGELOG.md
- src/compiler/compile/nodes/Element.ts
- test/validator/samples/a11y-img-redundant-alt/input.svelte
> fix exception with empty alt attribute

- site/content/tutorial/07-lifecycle/04-tick/text.md
Fixes #4756 
another option is to explain what "invalidate" means but this seems like the least confusing solution
> Tutorial text: invalidate -> update

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/RawMustacheTag.ts
- src/runtime/internal/dom.ts
- test/js/samples/each-block-changed-check/expected.js
- test/runtime/samples/raw-mustaches-td-tr/_config.js
- test/runtime/samples/raw-mustaches-td-tr/main.svelte
Thought the solution in https://github.com/sveltejs/svelte/issues/4852#issuecomment-630522812 would be fairly trivial, but it breaks reordering in cases with keyed each blocks, and I don't think I can fix it right now so I'm leaving it here instead for now.
Alternative to #4857
> Alternative fix for #4852.

- site/src/routes/_layout.svelte
> remove BLM banner

- .github/PULL_REQUEST_TEMPLATE.md
This PR addresses a typo found in the PULL_REQUEST template.
> chore(typo): address typo in the PR template

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/shared/bind_this.ts
- test/runtime/samples/binding-this-each-block-property-2/_config.js
- test/runtime/samples/binding-this-each-block-property-2/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/5067
> fix bind:this, skip checking before adding to binding_callbacks

- src/runtime/motion/tweened.ts
> fix(5062): make tweened options optional

- site/content/faq/400-how-can-i-get-syntax-highlighting.md
- site/content/faq/500-what-about-typescript-support.md
This is purely a docs update now that the VS Code extension is shipping to prod. 👍
> Update docs now the lang tools stuff is production ready

- site/content/blog/2019-04-16-svelte-for-new-developers.md
> Blog: remove an obsolete TODO

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/Slot.ts
- test/runtime/samples/props-reactive-slot/Comp.svelte
- test/runtime/samples/props-reactive-slot/_config.js
- test/runtime/samples/props-reactive-slot/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/3364
> $$props reactive for slots

- site/content/docs/02-template-syntax.md
> site: rephrase to clarify that actions can have just one parameter.

- CHANGELOG.md
- src/compiler/parse/index.ts
- src/compiler/parse/state/tag.ts
- test/parser/samples/error-unmatched-closing-tag-autoclose-2/error.json
- test/parser/samples/error-unmatched-closing-tag-autoclose-2/input.svelte
- test/parser/samples/error-unmatched-closing-tag-autoclose/error.json
- test/parser/samples/error-unmatched-closing-tag-autoclose/input.svelte
Fixes https://github.com/sveltejs/svelte/issues/5049
need suggestion on a better error message
> better error message for unclose tag due to autoclosing

- CHANGELOG.md
- src/compiler/compile/nodes/Binding.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/render_dom/wrappers/shared/mark_each_block_bindings.ts
- test/runtime/samples/binding-input-checkbox-deep-contextual/_config.js
- test/runtime/samples/binding-input-group-each-6/_config.js
- test/runtime/samples/binding-input-group-each-6/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/5174
thanks to @dimfeld for figuring out the bug
> fix bind:group contextual reference

- site/content/blog/2019-04-16-svelte-for-new-developers.md
Small documentation update to point to the current Svelte VSCode plugin.
> Update link for Svelte VSCode extension

- CHANGELOG.md
- src/compiler/compile/render_ssr/index.ts
- test/runtime/samples/reactive-value-assign-property/_config.js
- test/runtime/samples/reactive-value-assign-property/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/5247
> fix #5247 - do not declare variable for member assignment in reactive declaration

- site/content/faq/200-are-there-any-video-courses.md
Hey! This is a small FQA change. Adding the recent RichHarris's Frontend masters course. I have ordered it alphabetically. (in order to not tamper with the 'Note'). Please review and merge if possible.
> Adding Rich Harris's Frontend Masters course on FAQ page

- src/compiler/compile/render_dom/Renderer.ts
- src/compiler/compile/render_dom/index.ts
* Simplify an if statement
* Also inlines a variable
> Make two code items easier to understand:

- README.md
[Rendered](https://github.com/benmccann/svelte/tree/opencollective#supporting-svelte)
> Add opencollective link to readme

- CHANGELOG.md
- src/compiler/compile/css/Selector.ts
- test/css/samples/unused-selector-child-combinator/_config.js
- test/css/samples/unused-selector-child-combinator/expected.css
- test/css/samples/unused-selector-child-combinator/input.svelte
> fix no unused css selector warning

- CHANGELOG.md
- src/compiler/compile/css/Selector.ts
- test/css/samples/child-combinator/expected.css
- test/css/samples/child-combinator/input.svelte
Fixes https://github.com/sveltejs/svelte/issues/4795
> fix css specificity for child combinator

- CHANGELOG.md
- src/compiler/compile/nodes/Transition.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/runtime/samples/transition-js-args-dynamic/_config.js
- test/runtime/samples/transition-js-args-dynamic/main.svelte
Fixes https://github.com/sveltejs/svelte/issues/5244
> maintain context for transition

- site/content/tutorial/01-introduction/07-making-an-app/text.md
encourage the use of the svelte vs code extension in the tutorial
> tutorial: update text editor configuration recommendation

- CHANGELOG.md
- src/compiler/compile/nodes/Action.ts
- test/validator/samples/action-object/input.svelte
- test/validator/samples/action-object/warnings.json
> remove undefined warning for action object

- CHANGELOG.md
- src/compiler/utils/names.ts
> add EventSource to the known globals

- CHANGELOG.md
- src/compiler/compile/css/Selector.ts
- test/css/samples/siblings-combinator-with-spread/_config.js
- test/css/samples/siblings-combinator-with-spread/expected.css
- test/css/samples/siblings-combinator-with-spread/expected.html
- test/css/samples/siblings-combinator-with-spread/input.svelte
> fix attribute name is undefined

- README.md
> Discord chat badge

- site/content/faq/200-are-there-any-video-courses.md
Found more video courses that can help others learn Svelte. This PR added links to Pluralsight, Svelte Master Youtube Channel, and Svelte Tutorial for Beginners by The Net Ninja. 
Closes #5349
> Add more video courses links in FAQ

- site/content/tutorial/06-bindings/10-media-elements/app-a/App.svelte
- site/content/tutorial/06-bindings/10-media-elements/app-b/App.svelte
> Track kind added for video element

- site/content/blog/2020-11-01-whats-new-in-svelte-november-2020.md
> Some typos [ci-skip]

- CHANGELOG.md
- rollup.config.js
> add extension to request to support webpack 5

- CHANGELOG.md
- src/compiler/compile/render_dom/index.ts
- src/runtime/internal/dom.ts
- test/custom-elements/samples/$$slot/main.svelte
- test/custom-elements/samples/$$slot/test.js
> support $$slots in custom elements

- CHANGELOG.md
- package.json
Closes https://github.com/sveltejs/svelte/issues/5659
> Add package.json to exports map

- site/content/docs/02-template-syntax.md
resolves https://github.com/sveltejs/svelte/issues/3623 raised by @evdama and @tanhauhau
> document await...catch shorthand

- site/content/blog/2019-04-16-svelte-for-new-developers.md
This is a proposed fix for #5443
Without git installed `npx degit sveltejs/template my-svelte-project` results in 
```
npx: installed 1 in 0.839s
! could not fetch remote https://github.com/sveltejs/template
! could not find commit hash for master
```
From a newbie perspective it isn't immediately obvious that git is required.
I've updated this post to make that more clear.
> Suggested improvement for beginner documentation

- CHANGELOG.md
- src/runtime/index.ts
- test/runtime/samples/context-api-c/Leaf.svelte
- test/runtime/samples/context-api-c/Nested.svelte
- test/runtime/samples/context-api-c/_config.js
- test/runtime/samples/context-api-c/main.svelte
Fixes #5726
- added missing export
- added test case too
> add missing export for hasContext

- site/content/docs/01-component-format.md
- [N/A] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [N/A] This message body should clearly illustrate what problems it solves.
- [N/A] Ideally, include a test that fails without this PR but passes with it.
-  [N/A] Run the tests with `npm test` and lint the project with `npm run lint`
> Add clarification on what makes a reactive block reactive to docs.

- site/content/faq/800-how-do-i-test-svelte-apps.md
Saying "we don't have a good answer to this yet" is a scary thing to encounter. There are numerous solutions that work. We might not have an agreed upon preferred solution, but it's definitely possible to test Svelte apps today.
> Update testing FAQ

- site/package-lock.json
The site builds in production mode if I refresh the `package-lock.json`
> Bump dependencies to fix site building in production mode

- CHANGELOG.md
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_ssr/index.ts
- test/js/samples/capture-inject-state/expected.js
- test/js/samples/unreferenced-state-not-invalidated/expected.js
- test/runtime/samples/reactive-values-uninitialised/_config.js
- test/runtime/samples/reactive-values-uninitialised/main.svelte
> shift initialisation to the top

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/EachBlock.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- test/js/samples/each-block-keyed-animated/expected.js
- test/js/samples/each-block-keyed/expected.js
- test/runtime/samples/animation-js-delay/_config.js
- test/runtime/samples/each-block-keyed-bind-group/_config.js
- test/runtime/samples/each-block-keyed-bind-group/main.svelte
> maintain context for keyed each

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/shared/add_actions.ts
- test/runtime/samples/action-object-deep/_config.js
- test/runtime/samples/action-object-deep/main.svelte
> fix deep object property for action

- CHANGELOG.md
- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- test/runtime/samples/transition-js-if-else-block-not-dynamic-outro/_config.js
- test/runtime/samples/transition-js-if-else-block-not-dynamic-outro/main.svelte
Fixes #5789 
Fixes #5808
~~- [] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs~~
> fix if_block.p is undefined

- CHANGELOG.md
- src/runtime/internal/await_block.ts
- test/runtime/samples/transition-js-await-block-outros/_config.js
- test/runtime/samples/transition-js-await-block-outros/main.svelte
> await transition outros

- .gitignore
- site/scripts/update_whos_using.js
- Issue #5917 
- Adapts to changes from https://github.com/sveltejs/community/pull/377
> Issue 5917 who is using svelte has been updated

- src/compiler/parse/state/tag.ts
- test/parser/samples/action-duplicate/input.svelte
- test/parser/samples/action-duplicate/output.json
> Allow using same action twice

- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_dom/wrappers/Element/index.ts
- src/compiler/compile/render_dom/wrappers/Slot.ts
- src/compiler/parse/state/mustache.ts
- src/runtime/motion/spring.ts
- src/runtime/transition/index.ts
- test/sourcemaps/samples/source-map-generator/_config.js
- test/sourcemaps/samples/sourcemap-basename/_config.js
I'm surprised this isn't already setup :-)
> Add spaces next to infix operators

- CHANGELOG.md
- src/compiler/compile/css/Selector.ts
- test/css/samples/host/expected.css
- test/css/samples/host/input.svelte
> fix :host is removed

- site/content/faq/800-how-do-i-test-svelte-apps.md
Sorry, this is probably too minor to even bother, but spelling errors really annoy me. :(
> Spelling error fix.

- site/content/tutorial/07-lifecycle/03-update/text.md
There may be misstatement with respect to the tense of the first clause, 'is' vs 'has been'.
> Update text.md. A small gramatical issue.

- site/content/tutorial/01-introduction/04-styling/app-a/App.svelte
Minor documentation change, which improves grammar.
> 💬 Improve grammar

- site/src/routes/_layout.svelte
> Add link to SvelteKit to Svelte website.

- src/compiler/compile/render_dom/wrappers/Slot.ts
- test/runtime/samples/transition-js-slot-2/Nested.svelte
- test/runtime/samples/transition-js-slot-2/_config.js
- test/runtime/samples/transition-js-slot-2/main.svelte
> update slot content after abort transition

- site/content/tutorial/06-bindings/06-select-bindings/text.md
The referenced line is now 20 instead of 24
> updated select-bindings tutorial text.md

- site/src/routes/tutorial/[slug]/index.svelte
> remove redundant style

- site/content/examples/11-easing/00-easing/App.svelte
remove redundant css (it's overridden after)
> remove redundant CSS

- site/package-lock.json
- site/package.json
Allows parsing quoted frontmatter
> Bump site-kit

- src/compiler/parse/state/tag.ts
- test/parser/samples/textarea-end-tag/input.svelte
- test/parser/samples/textarea-end-tag/output.json
> fix textarea end tag parsing

- src/compiler/compile/css/Selector.ts
- test/validator/samples/css-invalid-global-selector/errors.json
- test/validator/samples/css-invalid-global-selector/input.svelte
> disallow multiple selectors inside :global()

- src/compiler/compile/render_dom/wrappers/Element/EventHandler.ts
- src/runtime/internal/lifecycle.ts
- test/runtime/samples/component-events-this/Inner.svelte
- test/runtime/samples/component-events-this/Widget.svelte
- test/runtime/samples/component-events-this/_config.js
- test/runtime/samples/component-events-this/main.svelte
> bind this to the forwarded event

- src/compiler/compile/render_dom/Renderer.ts
- src/compiler/compile/render_dom/wrappers/IfBlock.ts
- src/compiler/compile/render_dom/wrappers/Slot.ts
- test/runtime/samples/bitmask-overflow-if-2/_config.js
- test/runtime/samples/bitmask-overflow-if-2/main.svelte
- test/runtime/samples/transition-js-slot-3/Nested.svelte
- test/runtime/samples/transition-js-slot-3/_config.js
- test/runtime/samples/transition-js-slot-3/main.svelte
- test/runtime/samples/transition-js-slot-fallback/_config.js
- test/runtime/samples/transition-js-slot-fallback/main.svelte
> fix slot props not updated when transition aborted

- site/content/docs/01-component-format.md
> update docs for style tag in elements

- .github/stale.yml
> add stale-bot config

- site/content/docs/03-run-time.md
Add documentation for the `crossfade` function in `svelte/transition`.
Fixes https://github.com/sveltejs/svelte/issues/5142
> Add documentation for crossfade

- site/src/routes/_layout.svelte
Closes https://github.com/sveltejs/svelte/issues/5703
> Rename menu item from API to Docs

- site/content/tutorial/08-stores/02-auto-subscriptions/text.md
> Corrects text.

- CONTRIBUTING.md
> Add link to "good first issue" issues in Contributing Guide

- src/compiler/compile/css/Selector.ts
- test/validator/samples/css-invalid-global-placement-3/errors.json
- test/validator/samples/css-invalid-global-placement-3/input.svelte
> :global() with pseudo element should be considered as global

- src/compiler/compile/nodes/Element.ts
https://github.com/sveltejs/svelte/pull/5938 requires something removed by https://github.com/sveltejs/svelte/pull/6457
reverted some of the changes in https://github.com/sveltejs/svelte/pull/6457 to fix the CI
> fix ci after merge conflicts

- site/content/examples/05-bindings/09-media-elements/App.svelte
- site/content/tutorial/06-bindings/10-media-elements/app-a/App.svelte
- site/content/tutorial/06-bindings/10-media-elements/app-b/App.svelte
- site/content/tutorial/06-bindings/10-media-elements/text.md
Played around with the media example for a bit and figured it would be nice if it supported trackpads and touch.
> Trackpad and touch support in media example

- package.json
the new exports of ssr.js and ssr.mjs need to be present in the package or it won't work.
see #6416 
> [fix] add ssr.* to package files so that the exports added in #6416 work

- site/content/tutorial/02-reactivity/01-reactive-assignments/app-a/App.svelte
PR https://github.com/sveltejs/svelte/pull/4060 adjusted the function name as `incrementCount` in the text.md and app-b version.
Proposes the function name should be consistent in app-a version.
> [docs] adjust function name

- site/content/tutorial/10-transitions/09-key-blocks/app-a/App.svelte
- site/content/tutorial/10-transitions/09-key-blocks/app-b/App.svelte
- site/content/tutorial/10-transitions/09-key-blocks/text.md
Closes #6418 
Adds a tutorial step that explains key blocks.
> [docs] Add tutorial step for key blocks

- site/content/faq/800-how-do-i-test-svelte-apps.md
- src/compiler/compile/css/Selector.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_dom/invalidate.ts
- src/runtime/internal/dev.ts
Fixed typos,
Refactored imports - now used shorthand.
> fix typos, use shorthanded imports

- site/content/tutorial/06-bindings/07-multiple-select-bindings/text.md
For better user understanding.
-  [ ] Run the tests with `npm test` and lint the project with `npm run lint` (NA)
> [docs] Multi select works pressing and holding shift key

- package-lock.json
- package.json
- src/compiler/compile/Component.ts
- src/compiler/compile/nodes/shared/Expression.ts
- src/compiler/compile/render_dom/index.ts
- src/compiler/compile/render_ssr/index.ts
- src/compiler/compile/utils/scope.ts
Fixes https://github.com/sveltejs/svelte/issues/6492
> Upgrade Periscopic

- site/content/docs/03-run-time.md
- src/runtime/index.ts
- src/runtime/internal/lifecycle.ts
- src/runtime/ssr.ts
- test/runtime/samples/context-api-d/Leaf.svelte
- test/runtime/samples/context-api-d/Nested.svelte
- test/runtime/samples/context-api-d/_config.js
- test/runtime/samples/context-api-d/main.svelte
> [feat] get all contexts

- src/compiler/compile/render_dom/index.ts
- test/runtime/samples/component-binding-accessors/Nested.svelte
- test/runtime/samples/component-binding-accessors/_config.js
- test/runtime/samples/component-binding-accessors/main.svelte
> [fix] binding when updating through accessors

- src/runtime/store/index.ts
Closes #2710.
Didn't find way to benchmark how faster than before yet.😭
> [chore] refactor: convert subscribers `Array` to `Set`

- src/compiler/compile/css/Selector.ts
- test/css/samples/global-with-child-combinator/_config.js
- test/css/samples/global-with-child-combinator/expected.css
- test/css/samples/global-with-child-combinator/input.svelte
> [fix] global encapsulation

- src/compiler/parse/state/tag.ts
- test/parser/samples/element-with-attribute-empty-string/input.svelte
- test/parser/samples/element-with-attribute-empty-string/output.json
- test/parser/samples/element-with-attribute/input.svelte
- test/parser/samples/element-with-attribute/output.json
> [fix] Create AST node even if HTML element's attribute is empty string

- src/compiler/compile/css/Selector.ts
- test/css/samples/global-with-child-combinator-2/_config.js
- test/css/samples/global-with-child-combinator-2/expected.css
- test/css/samples/global-with-child-combinator-2/expected.html
- test/css/samples/global-with-child-combinator-2/input.svelte
- test/css/samples/global-with-child-combinator-3/_config.js
- test/css/samples/global-with-child-combinator-3/expected.css
- test/css/samples/global-with-child-combinator-3/expected.html
- test/css/samples/global-with-child-combinator-3/input.svelte
- test/css/samples/global-with-child-combinator/expected.html
> [fix] applying :global for > combinator

- src/compiler/interfaces.ts
> [chore] add space to improve formatting in type definitions file

- src/compiler/parse/state/mustache.ts
- test/runtime/samples/await-catch-no-expression/_config.js
- test/runtime/samples/await-catch-no-expression/main.svelte
- test/runtime/samples/await-then-no-expression/_config.js
- test/runtime/samples/await-then-no-expression/main.svelte
> [feat] allow shorthand then and catch with no expression

- package-lock.json
Closes https://github.com/sveltejs/svelte/issues/6074
> [chore] use npm 7 for development
